### ISSUE TITLE
Get-ScheduledTask does not work properly with non-English languages

### ISSUE THREAD

**Issue by HermannGaetan** [PSAppDeployToolkit/PSAppDeployToolkit#10]
Line 4284 AppDeployToolkitMain.ps1 has to be changed: 
 [psobject[]]$SchtasksResults = $exeSchtasksResults | ConvertFrom-CSV -Header "HostName","TaskName","NextRun","Status","LastRun" -ErrorAction 'Stop' 

 This bug was previously resolved but reappeared in Version 3.6.2

**Comment by HermannGaetan** [comment]
On non-english languages, every properties are language specific. e.g. in German, TaskName will be Aufgabename. Therefore, <code>ConvertFrom-CSV -Header</code> is useful.

**Comment by mmashwani** [comment]
Please test the latest 3.6.3 beta from here to see if this issue is fixed for you now:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1

**Comment by HermannGaetan** [comment]
Code look good. I will try it. Thanks.
