### ISSUE TITLE
Set-ActiveSetup function problem

### ISSUE THREAD

**Issue by jyrisi** [PSAppDeployToolkit/PSAppDeployToolkit#100]
Hi
I can't get the Set-ActiveSetup function working with SCCM 2012 installation in my 64-bit Windows 7 computers unless I change the lines in that function from:

			[string]$ActiveSetupKey = "HKLM:SOFTWARE\Microsoft\Active Setup\Installed Components\$Key"
			[string]$HKCUActiveSetupKey = "HKCU:Software\Microsoft\Active Setup\Installed Components\$Key"

to:

			[string]$ActiveSetupKey = "HKLM:SOFTWARE\Wow6432Node\Microsoft\Active Setup\Installed Components\$Key"
			[string]$HKCUActiveSetupKey = "HKCU:Software\Wow6432Node\Microsoft\Active Setup\Installed Components\$Key"

The key is created under the HKLM\Software\Microsoft\Active Setup\Installed Components, but is not created at all under the user hives.

If I change that key path, the key is created under the HKLM\Software\Wow6432Node\Microsoft\Active Setup\Installed Components and under all of these user hives: HKCU\Software\Wow6432Node\Microsoft\Active Setup\Installed Components.

The command I use is: Set-ActiveSetup -StubExePath "$envWinDir\regedit.exe" -Arguments "/S `"C:\ProgramData\blaablaa\settings.reg`"" -Description 'Blaablaa' -Key 'Softwarename'

I've tested this with PSADTK version 3.6.7.

**Comment by That-Annoying-Guy** [comment]
I think your problem is that your REG file is from a 32-bit machine or app. you are calling the 64-bit regedit to import so those changes go to the HKLM:SOFTWARE\

This below will force the changes to go to HKLM:SOFTWARE\Wow6432Node\

	Set-ActiveSetup -StubExePath "C:\Windows\SysWOW64\regedit.exe" -Arguments "/S "C:\ProgramData\blaablaa\settings.reg"" -Description 'Blaablaa' -Key 'Softwarename'

**Comment by jyrisi** [comment]
Thanks for your response. The reg file is from the same 64-bit machine where I'm testing it. But I'll test that "C:\Windows\SysWOW64\regedit.exe" and get back to you after I have some results.

**Comment by amotaz** [comment]
Yes, please try the above, and if you're still having issues, please post your .reg file data as text, your log file and the code you're using in Deploy-application.ps1

**Comment by jyrisi** [comment]
Hi

That did the trick, thanks for helping me out!
