### ISSUE TITLE
[Feature] Add AppDeployToolkitLogo.png in customization documentation

### ISSUE THREAD

**Issue by m-hanisch** [PSAppDeployToolkit/PSAppDeployToolkit#1013]
### Summary of the new feature / enhancement

As a user of PSADT I want to identify all of the customization options available in the toolkit.
The website lacks mentioning the `AppDeployToolkitLogo.png` - it only mentions the `AppDeployToolkitBanner.png` and `AppDeployToolkitLogo.ico`.

Even though this is to some extent self-explainatory, I would like to complete the documentation.

- [/Toolkit/AppDeployToolkit folder](https://psappdeploytoolkit.com/docs/understanding-the-layout/extracted-archive#toolkitappdeploytoolkit-folder)
- [Customising deployments](https://psappdeploytoolkit.com/docs/usage/customizing-deployments)
- [/wiki/toolkit-usage#customizing-the-toolkit](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/wiki/toolkit-usage#customizing-the-toolkit)

Moreover, I came across this file [Sources/AppDeployToolkitBanner.pdn](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/main/Sources/AppDeployToolkitBanner.pdn). What is the purpose of this file and does it need to be adjusted / branded as well?

### Proposed technical implementation details (optional)

I would prepare a pull request as a suggestion based upon the available documentation. 
However, I need to know where I can find the corresponding files (.md or alike I guess) that need to be adjusted.
I am going to start with the wiki article [/wiki/toolkit-usage#customizing-the-toolkit](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/wiki/toolkit-usage#customizing-the-toolkit).
Thank you.

**Comment by m-hanisch** [comment]
Please review my revision, @sintaxasn 
[Updated Toolkit Usage (markdown)](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/wiki/_compare/b9d8cb55f4c404410c294345dfd09db8e087ffc2)

**Comment by mjr4077au** [comment]
All of this stuff's changed for v4, and v4 documentation is improving by the day.
