### ISSUE TITLE
[Bug] Function Write-log does not work if log filename has Square Brackets

### ISSUE THREAD

**Issue by regispicanco** [PSAppDeployToolkit/PSAppDeployToolkit#1014]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

Using a log filename with Square Brackets, the function Write-log does not create log file anda does not return any error. 
The problem occurs because the function Write-Log uses the comand OUT-FILE with the parameter "FilePath". This parameter does not accept Square Brackets.

The "Out-File" command is on line 1419 of the AppDeployToolkitMain.ps1 file

My Solution:
If you replace the "FilePath" parameter with the "LiteralPath" parameter, the Write-Log function will generate the log file correctly, with Square Brackets in the log filename.

The command Out-File in Write-log function also does not have a try-catch structure. So it does not generate any error.

### Steps to reproduce

1. Edit Deploy-Application.ps1
2. Put the following line in Installation Section:

write-log -Message "This is a test!" -LogFileDirectory "c:\temp\Logs" -LogFileName "AppLog[July].log"

### Environment data

```console
OsName               : Microsoft Windows 11 Pro
OSDisplayVersion     : 22H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64 bits
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : pt-BR
OsMuiLanguages       : {pt-BR}
KeyboardLayout       : 00010416
TimeZone             : (UTC-03:00) Brasília
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop

.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.7d36c14f

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\

Cargas de trabalho do .NET instaladas:
NÃ£o hÃ¡ cargas de trabalho instaladas para exibir.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by mjr4077au** [comment]
Not for this reason, but we've already addressed this in the upcoming release: `[System.String]::Format($logLine, $msg) | Out-File -LiteralPath $outFile -Append -NoClobber -Force -Encoding UTF8`

My question to you is, is using `-LogFileDirectory` and  `-LogFileName` parameters something you actively do?

**Comment by regispicanco** [comment]
First and foremost, I would like to commend you on the excellent PSAppDeployToolkit.

The PSAppDeployToolkit offers a wide range of extremely useful functions and features, not only for creating software installation packages but also for general scripting purposes.

I use the PSAppDeployToolkit as a foundation for various scripts. For instance, I have a script to create objects in Active Directory. If there is an error in creating any of the objects, I generate a separate error log that only includes the event of the object that failed. In this case, I call the Write-Log function with the -LogFileDirectory and -LogFileName parameters. This approach is very helpful for error handling because the log is only created when an error occurs.

Overall, scripts created with the PSAppDeployToolkit are very effective because I can utilize the toolkit's well-constructed functions, which include error handling. This allows me to log and debug all stages of my scripts easily.

Therefore, my answer is YES, I actively use the -LogFileDirectory and -LogFileName parameters with the Write-Log function.

**Comment by mjr4077au** [comment]
Thank you for your kind words! I'm fairly new to the team and am still proving myself but I thorougly appreciate the commendment!

It's great to hear how people are using the toolkit as of course we know how it's used in a rather standard way with SCCM or Intune, but the more esoteric uses only become known when we converse with community members like yourself.

Do you use any other parameters of `Write-Log`? It has overrides for a lot of things such as `-LogType`, `-AppendToLogFile`, `-MaxLogHistory`, etc

**Comment by regispicanco** [comment]
I only use these 2 parameters, the others I always leave at default.

I have another issue with the Write-log function that I'm checking. I don't know if it's a function problem or if it's my environment. I still need to understand better.

The problem is when a message has accented characters (very common in Portuguese). These characters do not output correctly in the log file.
But the Write-Log function uses the "UTF8" encoding, which should be enough for accented characters to be correctly placed in the log.
So it's something I'm still checking out. I still need to understand better, I don't have anything conclusive.

**Comment by mjr4077au** [comment]
For this, can you change the coding from `UTF8` to `([System.Text.UTF8Encoding]::new($true))` and test? Also, can you try without any encoding parameter at all? At least in PowerShell 5.x, that'll mean it'll encode as UTF16 LE.

**Comment by regispicanco** [comment]
Hi, I found the problem with encoding. My VS Code is changind the files encoding. So the problem is not with PSAppDeployToolkit. The problem is in my environment.

**Comment by mjr4077au** [comment]
Not a worry! I'll close this for now but if you have any other issues, please let us know!
