### ISSUE TITLE
[Bug] No execute-ProcessasUser by Active Setup with *.cmd as Systemaccount

### ISSUE THREAD

**Issue by IREJDW** [PSAppDeployToolkit/PSAppDeployToolkit#1018]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

If you execute an ActiveSetup via PSADT as a normal user, the ActiveSetup, which calls a cmd file, is executed and the values are written. 

However, if you call this with psexec /IS PATHtoPSADT.exe (i.e. system rights), the registry value is written to HKCU, but the cmd is not called.

### Steps to reproduce

1. Modify Deploy-Application.ps1 
2. Set-ActiveSetup -StubExePath "PATHtoCMD.cmd" -Version "1,2,3"
3. Run with Psexec /IS PATHtoPSADT.exe

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by DanGough** [comment]
Known issue when the .cmd file has a space in the name - and resolved here:

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/1017

Please feel free to take and test this branch, we are hoping to make a new release soon that will include this.
