### ISSUE TITLE
"Specified cast is not valid" error with binary Registry data

### ISSUE THREAD

**Issue by replicaJunction** [PSAppDeployToolkit/PSAppDeployToolkit#102]
I've been running into an InvalidCastException when using Get-InstalledApplication on all systems that have binary data stored in the Registry.

Here's what I mean: on workstations with Netbeans installed, there are two entries at HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall that when viewed in regedit, show "(invalid DWORD data)".  I've tested this in PS 4 and 5 on Windows 7 and 8.1 (x64), using toolkit versions 3.6.5 and 3.6.7.

Here's one of the Registry keys, in .reg format:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-8.0.2.0.201411181905]
"DisplayName"="NetBeans IDE 8.0.2"
"DisplayIcon"="C:\\Program Files\\NetBeans 8.0.2\\bin\\netbeans.exe"
"InstallLocation"="C:\\Program Files\\NetBeans 8.0.2"
"NoModify"=hex(4):01,00,00,00,00,00,00,00
"UninstallString"="\"C:\\Program Files\\NetBeans 8.0.2\\uninstall.exe\""
"Publisher"="NetBeans.org"
"URLUpdateInfo"="http://www.netbeans.org/downloads"
"DisplayVersion"="8.0.2"
"URLInfoAbout"="http://www.netbeans.org"
"Readme"="C:\\Program Files\\NetBeans 8.0.2\\readme.html"
"HelpLink"="http://www.netbeans.org/kb/index.html"


```

In that example, the NoModify name is the one that seems to be invalid.  Here's the exception record from the PSADT log file:

```
[Pre-Installation] :: Error Record:
-------------

Message        : Specified cast is not valid.
InnerException : 

FullyQualifiedErrorId : System.InvalidCastException,Microsoft.PowerShell.Comman
                        ds.GetItemPropertyCommand
ScriptStackTrace      : at <ScriptBlock>, C:\WINDOWS\ccmcache\3e\AppDeployToolk
                        it\AppDeployToolkitMain.ps1: line 1906
                        at Get-InstalledApplication<Process>, C:\WINDOWS\ccmcac
                        he\3e\AppDeployToolkit\AppDeployToolkitMain.ps1: line 
                        1906
                        at <ScriptBlock>, 
                        C:\WINDOWS\ccmcache\3e\Deploy-Application.ps1: line 126
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\WINDOWS\ccmcache\3e\AppDeployToolkit\AppDeployToolkitMa
                  in.ps1:1906 char:165
                  +                 [psobject[]]$regKeyApplication += 
                  Get-ChildItem -LiteralPath $regKey -ErrorA ...
                  +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



	Deploy Application	10/16/2015 3:54:18 PM	2260 (0x08D4)
```

I'm able to reproduce the exception interactively using Get-ItemProperty, so it's not specifically the toolkit's fault:

```powershell
Get-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-8.0.2.0.201411181905
Get-ItemProperty : Specified cast is not valid.
At line:1 char:1
+ Get-ItemProperty -Path HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\C ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ItemProperty], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,Microsoft.PowerShell.Commands.GetItemPropertyCommand
 
```

There's an [issue open on Microsoft Connect about this](https://connect.microsoft.com/PowerShell/feedback/details/801007/get-itemproperty-specified-cast-is-not-valid-error-when-reg-dword-value-has-binary-data) that indicates that including this in a try/catch block causes it to be a terminating error.

The "real" solution, in my opinion, would be for Microsoft to fix the Registry provider for Get-ItemProperty.  The next best solution would be for Netbeans to avoid writing this binary data to the Registry.  Since I'm not counting on either of these to happen in the near future, though, could we come up with a workaround to allow the toolkit to function on machines with Netbeans installed?

One option would be to modify the Get-InstalledApplication function so that the Get-ItemProperty call (line 1906) only gets the Registry properties we're interested in, rather than getting all Registry entries at the provided path. This is wrapped up in a nice, neat Foreach-Object right now, though, so it would take a bit of re-writing since it would take more than one call to Get-ItemProperty.

**Comment by mmashwani** [comment]
What version of the toolkit are you using? I addressed this error in the 3.6.6 release so that the script would not error out when it encounter invalid data in the registry.

**Comment by replicaJunction** [comment]
I'm using 3.6.5 in production right now, but I've seen the same behavior on 3.6.7.

**Comment by amotaz** [comment]
I wasn't able to import your sample reg key to test. When I created my own binary values, I had no issues.  

I did add something I think will work for now to the newest version, Get-ItemProperty will grab only the needed values from the uninstall key. 

Please, grab the current master branch through github and test and let me know. You can see the change to the script on line 1915.

**Comment by amotaz** [comment]
We were able to reproduce your issue and fix it in the current working version, and it will be in the upcoming 3.6.8 release. Let us know how your testing goes.
