### ISSUE TITLE
[Bug] Deploy-Application.exe crashing on several devices

### ISSUE THREAD

**Issue by dextraa9791** [PSAppDeployToolkit/PSAppDeployToolkit#1022]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

We have several devices which are failing to install any applications using deploy-application.exe. Upon further inspection i found that the executable is crashing on these devices due to the following error in the screenshot by just double clicking it using the unchanged source download. All i found online is that this could be due to "Deploy-Application.exe can crash if .NET Framework is not available or corrupt" but havent found a way to check/fix that. I tried running the .net framework troubleshooter but it didn't help.

We have about 40 devices which are having this issue, most of the devices don't have this issue. For the devices that have this issue, it seems that they had this issue for several months, so it isn't any recent change/update.

![mmc_OMZVH4vFnr](https://github.com/user-attachments/assets/11663806-c310-42a9-9079-d0497ec8e078)
![mmc_XuMz2h9kHq](https://github.com/user-attachments/assets/9fdc6537-4dff-4d7d-b5a4-8b76c295ba56)

### Steps to reproduce

1. Download PSAppdeploytoolkit, unzip it
2. Run deploy-application.exe

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64 bits
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : nl-NL
OsMuiLanguages       : {nl-NL}
KeyboardLayout       : 00020409
TimeZone             : (UTC+01:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile
 
.NET SDK:
Version:           8.0.303
Commit:            29ab8e3268
Workload version:  8.0.300-manifests.c915c39d
MSBuild version:   17.10.4+10fbfbf2e
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.19045
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\8.0.303\
 
.NET workloads installed:
There are no installed workloads to display.
 
Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0
 
.NET SDKs installed:
  8.0.303 [C:\Program Files\dotnet\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  None
 
Environment variables:
  Not set
 
global.json file:
  Not found
```

**Comment by DanGough** [comment]
Do you have the .config file in there next to Deploy-Application.exe? I noticed that can cause a crash without it on some machines since it tried to use .NET 3.5.

Also please retry with 3.10.2!

**Comment by mjr4077au** [comment]
The front-end exe has been rewritten for v4 and will be digitally signed as well. Please test with v4 when it's released!
