### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by r4zi3lrrr** [PSAppDeployToolkit/PSAppDeployToolkit#1025]
Hi,

I'm trying to package Python using PSADT, but I'm getting this when trying to deploy via SCCM.

Logs under Configuration Manager:
[Installation] :: [C:\Users\user\Desktop\Python_3.12.4_x64_r00\Files\python-3.12.4-amd64.exe] is a valid fully qualified path, continue.	Execute-Process	19/07/2024 17:36:08	2040 (0x07F8)
[Installation] :: Working Directory is [C:\Users\user\Desktop\Python_3.12.4_x64_r00\Files].	Execute-Process	19/07/2024 17:36:09	2040 (0x07F8)
[Installation] :: Executing [C:\Users\user\Desktop\Python_3.12.4_x64_r00\Files\python-3.12.4-amd64.exe /simple /quiet]...	Execute-Process	19/07/2024 17:36:09	2040 (0x07F8)
[Installation] :: Execution failed with exit code [3].	Execute-Process	19/07/2024 17:36:10	2040 (0x07F8)
[Installation] :: The installation progress dialog does not exist. Waiting up to 5 seconds...	Close-InstallationProgress	19/07/2024 17:36:11	2040 (0x07F8)
[Installation] :: The installation progress dialog was not created within 5 seconds.	Close-InstallationProgress	19/07/2024 17:36:16	2040 (0x07F8)
[Installation] :: Python_3.12.4_x64_EN_00 Installation completed with exit code [3].	Exit-Script	19/07/2024 17:36:16	2040 (0x07F8)

This is what I've got in PSADT:

Execute-Process -Path "$dirFiles\python-3.12.4-amd64.exe" -Parameters '/simple /quiet' -WindowStyle 'Hidden' 

Any ideas, please?

**Comment by That-Annoying-Guy** [comment]
Exitcode 3 is a standard windows exit code

[According to this](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-), it means bad path. 

PSADT just captured it for your benefit.  

Maybe your account is not allowed to launch the python exe from the desktop.

**Comment by r4zi3lrrr** [comment]
You may be right as the PSADT package does seem to install when I run it as an administrator.

I'm trying to install Python using PSADT - with a system account but it keeps on coming up with this Exit code 3.

The strange thing is that other packages have installed using this system account without issue - it's Python which is potentially being problematic.

Any ideas on how to get around it, please?

**Comment by DanGough** [comment]
Run Sysinternals psexec:

`psexec -s -i cmd.exe`

Then test your silent install command there as system. If it fails with the same error code, then the error is nothing to do with the toolkit, and hence this should be closed.
