### ISSUE TITLE
Software title in installation window not clear/big enough.

### ISSUE THREAD

**Issue by MortenRoenborg** [PSAppDeployToolkit/PSAppDeployToolkit#103]
Our users seems to miss what is about to be installed beacuse the title of the program being installed only is present in the top ribbon.
![image](https://cloud.githubusercontent.com/assets/15209121/10600841/c32a397c-770d-11e5-8c38-d273b60bdecf.png)

Would it be meaningfull to make some text to make it more clear?

Maybe something like this:
![image](https://cloud.githubusercontent.com/assets/15209121/10600882/fce4fada-770d-11e5-8da1-02ceaec619d5.png)

Thanks

**Comment by amotaz** [comment]
We'll consider this enhancement and get back to you soon. If we add it, it'll be in a future version.

**Comment by amotaz** [comment]
We will look at possibly making this change in the 4.0 release, but we're not going to make a change like this in the 3.x release.

**Comment by n1x0d** [comment]
I would like to second this request. Thank you.

**Comment by Silthus** [comment]
@MortenRoenborg sorry about the off topic, but just out of interest: how did you do the "On startup" dialog button? And what exactly does it do?

**Comment by MortenRoenborg** [comment]
@Silthus no worries. I implemented the button for a special demand i our firm - our users where tired of all "close apps" prompts. The button basically made an Active Setup entry which executed a custom script at startup that forced a start of the deployment and waited for it to finish before showing the desktop.
By choosing the "On startup" button, the user would not be disturbed by any re-runs of the deployment, but would be forced to reboot the PC within 5 days in order for the installation to complete.

**Comment by luki1412** [comment]
The application title was missing in the window with CloseApps. That will be fixed in the next release. Although it is not in bold.
