### ISSUE TITLE
[Bug] Function Block-AppExecution not working if..

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#1034]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

Function Block-AppExecution not working if there is & in the [string]$installTitle like
[string]$installTitle = "Test & QA"

Importing of the XML fails 100% of 100%

![image](https://github.com/user-attachments/assets/3653c9ef-3b25-4811-943e-6e0e9fe8f4be)

### Steps to reproduce

Create Application with [string]$installTitle = "Test & QA"

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
```

**Comment by DanGough** [comment]
Looks like we may need to escape & in the XML via `[System.Security.SecurityElement]::Escape($string)` here.

**Comment by DanGough** [comment]
Fixed in the PR above.

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/1036/commits/fe105f3eb72b32656bafa8600af789ce9a5d9968
