### ISSUE TITLE
[Bug] Robocopy /IM parameter not supported on older operating systems

### ISSUE THREAD

**Issue by Mrman1093** [PSAppDeployToolkit/PSAppDeployToolkit#1039]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

In using the Copy-File function on a Windows 8 computer, I found it spitting out an error related to Robocopy not supporting the `/IM` parameter. Sure enough, the parameter is a somewhat new addition as it wasn't included in the help output from `/?`. The official documentation for robocopy shows the parameter being added in 2022 but forum posts show it existing as early as 2020. Given that this is an issue on Windows 8, I would imagine that you would run into the same issue on older operating systems such as Windows Server 2008. I was able to get the `Copy-File` function to work properly by manually passing in the default Robocopy parameters used by the function and excluding `/IM`.

https://github.com/MicrosoftDocs/windowsserverdocs/commit/2f9d496e584fb05574406b5e0f3f37e03c102f14
https://stackoverflow.com/questions/40744335/how-do-i-force-robocopy-to-overwrite-files/63518622#63518622

The following is the output provided by Robocopy:

Robocopy output:
ERROR : Invalid Parameter #10 : "/IM"
Simple Usage :: ROBOCOPY source destination /MIR
source :: Source Directory (drive:\path or \\server\share\path).
destination :: Destination Dir  (drive:\path or \\server\share\path).
/MIR :: Mirror a complete directory tree.
For more usage information run ROBOCOPY /?

****  /MIR can DELETE files as well as copy them !

### Steps to reproduce

1. Dot source Deploy-Application.ps1 or AppDeployToolkitMain.ps1
2. Use `Copy-File` function

### Environment data

```console
Get-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
CurrentVersion         : 6.3
CurrentBuild           : 9600
CurrentType            : Multiprocessor Free
InstallationType       : Client
EditionID              : Professional
ProductName            : Windows 8.1 Pro
CurrentBuildNumber     : 9600
BuildLab               : 9600.winblue_gdr.140305-1710
BuildLabEx             : 9600.17041.amd64fre.winblue_gdr.140305-1710


$PSVersionTable
Name                           Value                                                                                                                                      
----                           -----                                                                                                                                      
PSVersion                      4.0                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                        
SerializationVersion           1.1.0.1                                                                                                                                    
CLRVersion                     4.0.30319.34014                                                                                                                            
BuildVersion                   6.3.9600.16394                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                       
PSRemotingProtocolVersion      2.2   


Robocopy version = 6.3.9600.16384
```

**Comment by Mrman1093** [comment]
Proposed solution would be to perform a version check of Robocopy and if the version is older than the revision when the `/IM` parameter was added, don't include it in the default parameters. Wikipedia states that the version number attached to Robocopy is the same as the Windows version for Windows 8 and later.

https://en.wikipedia.org/wiki/Robocopy#Versions

**Comment by DanGough** [comment]
Already fixed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/develop
