### ISSUE TITLE
[Bug] .vscode\PSScriptAnalyzerSettings.psd1 contains a spelling error

### ISSUE THREAD

**Issue by mazessj** [PSAppDeployToolkit/PSAppDeployToolkit#1045]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

I'm no VSCode expert, but it appears there's a misspelled parameter in PSScriptAnalyzerSettings.psd1.

On line 8, it says:
        'PSUseDeclaredVarsMoreThanAssigments'

Shouldn't it be the following?
        'PSUseDeclaredVarsMoreThanAssignments'

--Josh

### Steps to reproduce

1. Review Toolkit\.vscode\PSScriptAnalyzerSettings.psd1 in a text editor

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-05:00) Eastern Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:270
+ ... 'HyperVisorPresent','CsPartOfDomain','CsPCSystemType'); dotnet --info
+                                                             ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by mjr4077au** [comment]
This has been addressed in our v4 branch.
