### ISSUE TITLE
[Feature] Configurable prefix for LogFileName

### ISSUE THREAD

**Issue by rdearson** [PSAppDeployToolkit/PSAppDeployToolkit#1046]
### Summary of the new feature / enhancement

We are currently reviewing the possible configuration change of moving our PSADT logging directory from default configuration to the Intune Management Extension logging directory to ensure that the PSADT logs are captured and uploaded when our Support Teams collect logs from devices via an Intune remote action, or manually via ODC.ps1.

This is driven by a range of ticket escalations where log collection could be made easier for our teams, eg, investigation where the Service Desk have attempted to collect all relevant logs for an incident but did not collect the PSADT logs because they did not think it was related at the time.

Moving the logs themselves is obviously quite easy but it would be great to be able to configure a prefix for the log filenames, allowing log files to be easily sorted and viewed when we are utilising a non-PSADT standard logging directory.

The logging prefix would be exposed by the configuration XML and default to null, so no breaking changes by default, but granting the ability to sort in Explorer easily, identifying the PSADT logs with ease.

Small change and low impact for us but nice to have, saving us from manually modifying the write-log function to include our customisation and having to update the function as new PSADT versions are released.

**Comment by FRacine** [comment]
Actually, we are setting that variable to another folder. So it will still be possible

**Comment by rdearson** [comment]
Yep wouldnt want to remove any other configurations such as change logging destination directory, just the ability to add a prefix :)

**Comment by DanGough** [comment]
If your primary concern is to make it easier to gather the various logs together for support purposes, how about setting `<Toolkit_CompressLogs>` to True in AppDeployToolkitConfig.xml? Then the all the various MSI logs will be zipped up together with the PSADT log.

**Comment by mjr4077au** [comment]
This should be completed as per the comments here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1159#issuecomment-2537615017
