### ISSUE TITLE
[Bug] Deploy-Application.exe hides PowerShell Exit Code on Script Execution Failure

### ISSUE THREAD

**Issue by niemalsnever** [PSAppDeployToolkit/PSAppDeployToolkit#1048]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.0

### Describe the bug

If the `Deploy-Application.ps1` fails to execute - in my case due to a custom parameter not being accepted, PowerShell exits with exit code 1, but `Deploy-Application.exe` returns 0. This causes Software Center to assume a successful operation and to run the detection, which of course fails. Additionally no PSADT log file is produced.

### Steps to reproduce

1. Add a custom parameter to a `Deploy-Application.ps1` script, with a ValidateSet-rule.
2. Run `powershell -File Deploy-Application.ps1 -YourCustomParameter "invalidValue"`.
3. PowerShell fails to validate the parameter value, and exits with exit code 1.
4. Run `Deploy-Application.exe -YourCustomParameter "invalidValue"`
5. `Deploy-Application.exe` exits immediately (as the script fails to run). If you check the exit code, it's 0, indicating success.

It would be expected that `Deploy-Application.exe` returns the exit code from `powershell.exe` verbatim, in this case `1`

### Environment data

```console
OsName               : Microsoft Windows 10 Education
OsOperatingSystemSKU : 121
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Education
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
The front-end has been rewritten for v4 and this shouldn't be an issue anymore.
