### ISSUE TITLE
[Feature] Download from Url

### ISSUE THREAD

**Issue by noyard** [PSAppDeployToolkit/PSAppDeployToolkit#1050]
### Summary of the new feature / enhancement

I have an install that depending upon the conditions of user and options set by the user it will need to download from our intranet site.  I cannot include the files in my install because of licensing reasons. 

Is there a function built already that downloads the file and tests the hash to see if the file is complete.

### Proposed technical implementation details (optional)

DownloadFile($Url, $path, $hash)

**Comment by mjr4077au** [comment]
This has been added to the v4 repo as `Invoke-ADTWebDownload`. Not too long to go now and you'll be able to have a play with it 🤘

**Comment by noyard** [comment]
> This has been added to the v4 repo as `Invoke-ADTWebDownload`. Not too long to go now and you'll be able to have a play with it 🤘

Thank you for putting it in so quickly 🤘

**Comment by mjr4077au** [comment]
Luckily I had some code I could add in for this without reinventing the wheel! There's also two added utilities that could be beneficial:
 * `Get-ADTRedirectedUri`: Can parse permalinks like `https://aka.ms/getwinget` and return `https://github.com/microsoft/winget-cli/releases/download/v1.8.1911/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`
 * `Get-ADTUriFileName`: Can parse any link, including permalinks like `https://aka.ms/getwinget` and return `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`.

**Comment by noyard** [comment]
Is there a way for me to download v4? Is it in alpha or beta yet?

**Comment by mjr4077au** [comment]
Not just yet, but we're hoping to have a preview out soon!
