### ISSUE TITLE
[Bug] Copy-File can fail for some added robocopy options due to order of cmd line args

### ISSUE THREAD

**Issue by apiontek** [PSAppDeployToolkit/PSAppDeployToolkit#1054]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2

### Describe the bug

Copy-File can fail in some circumstances but there ought to be an easy fix.

The reason is the way robocopy is called: with current Copy-File, the robocopy options are put first, then the source, then the dest.

However, robocopy ideally should have [source] [dest] [files to copy if any] [options] (this is also how robocopy is [documented at ss64](https://ss64.com/nt/robocopy.html))

Example failure: `Copy-File -Path C:\my-source\* -Destination C:\my-dest -Recurse -RobocopyAdditionalParams '/XF *.md'`

With current PSADT, this results in a command line ordered like so: `[other options] /XF *.md C:\my-source C:\my-dest *`

robocopy doesn't like this and errors out. However, the following would work: `C:\my-source C:\my-dest * [other options] /XF *.md`

### Steps to reproduce

1. Try `-RobocopyAdditionalParams '/XF *.md'` for example
2. Watch it fail

### Environment data

```console
Here's info from Win 11 but this is also the case on Win 10 in our environment


OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-05:00) Eastern Time (US & Canada)
HyperVisorPresent    : False
CsPartOfDomain       : True
CsPCSystemType       : Mobile

.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.56cd0383
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.401\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  6.0.425 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by T0RST3N** [comment]
Hey,
i also have an error with Copy-File since version 3.10.2. With 3.10.1 everything was OK.
see also here:
https://discourse.psappdeploytoolkit.com/t/copy-file-lastexitcode-16-psadt-3-10-2/5775

**Comment by DanGough** [comment]
The problem is you are supplying the files as additional params. The function will try to take your input path and work out the files (usually just *) from that.

So instead of running:

`Copy-File -Path C:\my-source\* -Destination C:\my-dest -Recurse -RobocopyAdditionalParams '/XF *.md'`

You should be able to do:

`Copy-File -Path C:\my-source\*.md -Destination C:\my-dest -Recurse -RobocopyAdditionalParams '/XF'`

**Comment by DanGough** [comment]
I see, there is only an issue with the order when applying specific params like /XF that expect filenames after it.

I will address this in 4.0.

**Comment by DanGough** [comment]
For now if you want a quick fix, just replace line 5333 in AppDeployToolkitMain.ps1:

```powershell
$RobocopyArgs = "$RobocopyParams $RobocopyAdditionalParams `"$RobocopySource`" `"$RobocopyDestination`" `"$RobocopyFile`""
```

With:

```powershell
$RobocopyArgs = "`"$RobocopySource`" `"$RobocopyDestination`" `"$RobocopyFile`" $RobocopyParams $RobocopyAdditionalParams"
```
