### ISSUE TITLE
[Feature] explicitly set the xml declaration node in the AppDeployToolkitConfig.xml

### ISSUE THREAD

**Issue by neo42mgn** [PSAppDeployToolkit/PSAppDeployToolkit#1056]
### Summary of the new feature / enhancement

I suggest adding the xml declaration node on top of the AppDeployToolkitConfig.xml
`<?xml version="1.0" encoding="utf-8"?>`
I can't provide any example with direct impact of this change, I just noticed that powershell xml objects, add this line automatically, when providing encoding settings.
Are there reasons that stand against adding the declaration node?

**Comment by mjr4077au** [comment]
This has been addressed for our v4 public preview.
