### ISSUE TITLE
[Bug] Dispose() method for $appDeployLogoBannerObject not working when async called AppDeployToolkitMain.ps1

### ISSUE THREAD

**Issue by LFM8787** [PSAppDeployToolkit/PSAppDeployToolkit#1059]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2

### Describe the bug

If you run a blocked application from the temp folder, the `$appDeployLogoBannerObject` is not correctly disposed.

The method [Image.Dispose Method Dispose(Boolean)](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.image.dispose#system-drawing-image-dispose(system-boolean)) doesn't seem to honor his name...

`AppDeployToolkitMain.ps1` at line `17018`
```powershell
# Calculate banner height
[Int32]$appDeployLogoBannerHeight = 0
Try {
    [System.Drawing.Bitmap]$appDeployLogoBannerObject = New-Object -TypeName 'System.Drawing.Bitmap' -ArgumentList ($appDeployLogoBanner)
    [Int32]$appDeployLogoBannerHeight = [System.Math]::Ceiling(450 * ($appDeployLogoBannerObject.Height/$appDeployLogoBannerObject.Width))
    If ($appDeployLogoBannerHeight -gt $appDeployLogoBannerMaxHeight) {
        $appDeployLogoBannerHeight = $appDeployLogoBannerMaxHeight
    }
    $appDeployLogoBannerObject.Dispose($true) # Must dispose() when installing from local cache or else AppDeployToolkitBanner.png is locked and cannot be removed
}
Catch {
}
```

### Steps to reproduce

1. Show-InstallationWelcome -CloseApps 'notepad' -AllowDeferCloseApps -BlockExecution
2. Run notepad when blocked
3. Following error appears (basically, unable to delete object in use):

[Post-Installation] [Remove-Folder] :: Failed to delete folder(s) and file(s) from path [C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution].
Error Record:
-------------

Message        : No se puede quitar el elemento C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution\AppDeployToolkitBanner.png: El proceso no puede obtener
                 acceso al archivo 'AppDeployToolkitBanner.png' porque está siendo utilizado en otro proceso. No se puede quitar el elemento
                 C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution: El directorio no está vacío.

InnerException :

**FullyQualifiedErrorId : No se puede quitar el elemento C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution\AppDeployToolkitBanner.png: El proceso no puede
                        obtener acceso al archivo 'AppDeployToolkitBanner.png' porque está siendo utilizado en otro proceso. No se puede quitar el elemento
                        C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution: El directorio no está vacío.

ScriptStackTrace      : en Remove-Folder<Process>, D:\Downloads\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1: línea 5096
                        en Unblock-AppExecution<Process>, D:\Downloads\Toolkit\AppDeployToolkit\PSADT.ToastNotification\ToastNotificationExtension.ps1:
                        línea 4353
                        en Exit-Script, D:\Downloads\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1: línea 1784
                        en <ScriptBlock>, D:\Downloads\Toolkit\Deploy-Application.ps1: línea 429

PositionMessage : En D:\Downloads\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1: 5096 Carácter: 21
                  +                     Throw $ErrorRemoveFolder
                  +                     ~~~~~~~~~~~~~~~~~~~~~~~~**

### Environment data

```console
OsName : Microsoft Windows 10 Pro
OsDisplayVersion : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture : 64 bits
WindowsVersion : 2009
WindowsProductName : Windows 10 Pro
WindowsBuildLabEx : 19041.1.amd64fre.vb_release.191206-1406
```

**Comment by LFM8787** [comment]
Simple solution 😄 :
```powershell
# Calculate banner height
[Int32]$appDeployLogoBannerHeight = 0
Try {
    [System.Drawing.Bitmap]$appDeployLogoBannerObject = New-Object -TypeName 'System.Drawing.Bitmap' -ArgumentList ($appDeployLogoBanner)
    [Int32]$appDeployLogoBannerHeight = [System.Math]::Ceiling(450 * ($appDeployLogoBannerObject.Height/$appDeployLogoBannerObject.Width))
    If ($appDeployLogoBannerHeight -gt $appDeployLogoBannerMaxHeight) {
        $appDeployLogoBannerHeight = $appDeployLogoBannerMaxHeight
    }
    $appDeployLogoBannerObject.Dispose() # Must dispose() when installing from local cache or else AppDeployToolkitBanner.png is locked and cannot be removed
}
Catch {
}
```

Using the other method [Image.Dispose Method Dispose()](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.image.dispose#system-drawing-image-dispose)

**Comment by mjr4077au** [comment]
Already addressed in v4! We don't read assets from disk like this anymore anyway, we stream them to memory and read them in like that.
