### ISSUE TITLE
Remove-Folder ability to disable recursion

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#106]
Hello,
Logically Remove-Folder should behave in similar manner as Remove-RegistryKey
Remove-Folder should not delete files if there are subdirectories and files if Recurse is disabled.

Why this is needed? - it is needed for cleanup purposes, if you need to delete folder only if there are other files and subfolders - this can mean that no addtional tridparty components installed, then we are safe to remove this folder and will not brake functionality of other files.

With Remove-RegistryKey I can do nice cleanup of for example
# Cleanup Addin "AAAA"

Remove-RegistryKey -Key "HKLM:\SOFTWARE\Microsoft\Office\15.0\Addins\AAAA" -Recurse -ContinueOnError
# Cleanup Addin "BBBB"

Remove-RegistryKey -Key "HKLM:\SOFTWARE\Microsoft\Office\15.0\Addins\BBBB" -Recurse -ContinueOnError
# Cleanup Addin "CCCC"

Remove-RegistryKey -Key "HKLM:\SOFTWARE\Microsoft\Office\15.0\Addins\CCCC" -Recurse -ContinueOnError
# Then we delete parent registry key if there no additional entries (addins that might be installed by third party apps)

Remove-RegistryKey -Key "HKLM:\SOFTWARE\Microsoft\Office\15.0\Addins" -Recurse -ContinueOnError
# Then we delete parent registry key if there no additional entries (addins that might be installed by third party apps)

Remove-RegistryKey -Key "HKLM:\SOFTWARE\Microsoft\Office\15.0" -Recurse -ContinueOnError
# Then we delete parent registry key if there no additional entries (addins that might be installed by third party apps)

Remove-RegistryKey -Key "HKLM:\SOFTWARE\Microsoft\Office" -Recurse -ContinueOnError
# Now we removed only original stuff and have clean registry

So it is obvious that Remove-Folder should function the same:
Delete folder/subfolder and files if -Recurse specified
Otherwise raise an error
If ContinueOnError specified $true - then continue.

**Comment by AcidUser85** [comment]
When you delete a folder with VBScript or even with CMD.exe /C RD command it won't allow to delete folder if it contains subfolders and files until you specify option to force delete it recursively.
So this is expected functionality.
I have searched and did not find any method using PSAppDeployToolkit to delete folder only if it's empty, but this would be really needed for careful cleanup.

**Comment by AcidUser85** [comment]
I have modified "Remove-Folder" to take -Recurse switch and operate same as "Remove-RegistryKey"

And here is working result:

#region Function Remove-Folder
Function Remove-Folder {
<#
.SYNOPSIS
	Remove folder and files if they exist.
.DESCRIPTION
	Remove folder and all files recursively in a given path.
.PARAMETER Path
	Path to the folder to remove.
.PARAMETER ContinueOnError
	Continue if an error is encountered. Default is: $true.
.EXAMPLE
	Remove-Folder -Path "$envWinDir\Downloaded Program Files"
.NOTES
.LINK
	http://psappdeploytoolkit.com
#>
	[CmdletBinding()]
	Param (
		[Parameter(Mandatory=$true)]
		[ValidateNotNullorEmpty()]
		[string]$Path,
		[Parameter(Mandatory=$false)]
		[switch]$Recurse,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullOrEmpty()]
		[boolean]$ContinueOnError = $true
	)
	
	Begin {
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	}
	Process {
		Try {
			If ($Recurse) {
				Write-Log -Message "Delete folder(s) and file(s) recursively from path [$path]..." -Source ${CmdletName}
				$null = Remove-Item -LiteralPath $Path -Force -Recurse -ErrorAction 'Stop'
			}
			Else {
				If($null -eq (Get-ChildItem -LiteralPath $Path -ErrorAction 'Stop')){
					## Check if there are files and subfolder in $Path, if so, executing remove-item will hang. Avoiding this with Get-ChildItem.
					Write-Log -Message "Delete folder [$Path]." -Source ${CmdletName}
					$null = Remove-Item -LiteralPath $Path -Force -ErrorAction 'Stop'
				}
				Else {
					Throw "Unable to delete child file(s) and folder(s) of [$Path] without [-Recurse] switch."
				}
			}
		}
		Catch {
			Write-Log -Message "Failed to delete folder(s) and file(s) recursively from path [$path]. `n$(Resolve-Error)" -Severity 3 -Source ${CmdletName}
			If (-not $ContinueOnError) {
				Throw "Failed to delete folder(s) and file(s) recursively from path [$path]: $($_.Exception.Message)"
			}
		}
	}
	End {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
#endregion

**Comment by amotaz** [comment]
I'm ok with this idea, but we need to preserve backward-compatibility, so we're going to implement this in a future major version. Thanks for the suggestion.

**Comment by luki1412** [comment]
This has been added, without breaking backward-compatibility.
