### ISSUE TITLE
Greek Language support

### ISSUE THREAD

**Issue by idpetrocheilos** [PSAppDeployToolkit/PSAppDeployToolkit#1064]
### Summary of the new feature / enhancement

Hello, a few years ago I had provided the translations for Greek language. I think at some point you implemented the language too. [Link.](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/690)

However, I downloaded the files today and EL language is not there. I am reuploading the files in case you want to add it back.
[AppDeployToolkitConfig.txt](https://github.com/user-attachments/files/17415271/AppDeployToolkitConfig.txt)

In case you don't want to implement it for your own reasons, please feel free to archive this request.

### Proposed technical implementation details (optional)

It is mentioned above.

**Comment by DanGough** [comment]
I'll look into what happened here, I'm sure it was not intentional! I'll ensure that they're back in for the v4.0 preview that's due to be released soon.

**Comment by idpetrocheilos** [comment]
Thank you Dan,
I took the time to refine a few points in the translation so feel free to use the new one if you like.

Thanks for your time! I am glad I can help!

**Comment by DanGough** [comment]
This has been implemented for the upcoming v4 release preview, using your latest translations attached in this issue. Thanks for pointing this out!
