### ISSUE TITLE
Test-PowerPoint on multiple screen

### ISSUE THREAD

**Issue by FlashGordon7** [PSAppDeployToolkit/PSAppDeployToolkit#107]
There is a bug in the function Test-PowerPoint.
When there is more then one screen it does not detect whether PowerPoint is running in fullscreen slideshow mode, if it is on screen 2 it always return False

The problem is in AppDeployToolkitMain.cs where it append(appBounds.Right + appBounds.Left) but i should subtract
if ((appBounds.Bottom - appBounds.Top) == screenBounds.Height && (appBounds.Right - appBounds.Left) == screenBounds.Width)

**Comment by DennisVH** [comment]
This was changed previously from - to + (see https://psappdeploytoolkit.codeplex.com/workitem/140)
May I suggest different calculations when using single or multiple screens (based on above statement)?

**Comment by mmashwani** [comment]
@FlashGordon7 
Can you run the below PowerShell code on the system that you saw this issue on? Report back your results and also point out which one of the results the PowerPoint window was on?

```[system.windows.forms.screen]::AllScreens```

**Comment by mmashwani** [comment]
@FlashGordon7 

I wonder if the subtraction is the real problem or not in your case. I'm thinking it might be that I am getting the handle of the foreground window like so ```hWnd = GetForegroundWindow();```. Then I get the screenbounds using the handle like so ```screenBounds = System.Windows.Forms.Screen.FromHandle(hWnd).Bounds;```

Could it be that in your case the screen that has PowerPoint is not the foreground window so I end up grabbing the bounds for the wrong screen?

**Comment by FlashGordon7** [comment]
Here is the output from 
<code>[System.Windows.Forms.Screen]::AllScreens</code>
```
BitsPerPixel : 32
Bounds       : {X=0,Y=0,Width=1920,Height=1080}
DeviceName   : \\.\DISPLAY1
Primary      : True
WorkingArea  : {X=0,Y=0,Width=1920,Height=1040}

BitsPerPixel : 32
Bounds       : {X=1920,Y=0,Width=1920,Height=1080}
DeviceName   : \\.\DISPLAY2
Primary      : False
WorkingArea  : {X=1920,Y=0,Width=1920,Height=1040}
```
I have also enabled <code>Console.WriteLine(mainWindowTitle);</code>
and added this
```
Console.Write("appBounds.Bottom -> " + appBounds.Bottom);
Console.Write(Environment.NewLine + "appBounds.Top -> " + appBounds.Top);
Console.Write(Environment.NewLine + "screenBounds.Height -> " + screenBounds.Height);
Console.Write(Environment.NewLine + "appBounds.Right -> " + appBounds.Right);
Console.Write(Environment.NewLine + "appBounds.Left -> " + appBounds.Left);
Console.WriteLine(Environment.NewLine + "screenBounds.Width -> " + screenBounds.Width);
```
And the output from that, when Powerpoint is in full screen on DISPLAY1
```
PowerPoint Slide Show - [Presentation1]
appBounds.Bottom -> 1080
appBounds.Top -> 0
screenBounds.Height -> 1080
appBounds.Right -> 1920
appBounds.Left -> 0
screenBounds.Width -> 1920
```
And the output from that, when Powerpoint is in full screen on DISPLAY2
```
PowerPoint Slide Show - [Presentation1]
appBounds.Bottom -> 1080
appBounds.Top -> 0
screenBounds.Height -> 1080
appBounds.Right -> 3840
appBounds.Left -> 1920
screenBounds.Width -> 1920
```
So PowerPoint is the foreground window.
Is it necessary to test for the window resolution / position is it not enough to test for the title *^PowerPoint Slide Show*

**Comment by mmashwani** [comment]
That is a good question. I never tested that. The text in the title bar does not start with "PowerPoint Slide Show" if PowerPoint is not in fullscreen mode?

**Comment by DennisVH** [comment]
The code below based on http://stackoverflow.com/questions/16484894/form-tells-wrong-size-on-windows-8-how-to-get-real-size takes care of the the appBounds.Right being the sum of both Primary and Secondary screen.
It just calculated the rectangle of the application bounds.
In GetWindowRectangle the way the rectangle is calcutated is different for before OS Major Version 6 because they don't have Aero.

I've only tested on Windows 7 x64 with Display 2 as extended monitor

    PS Q:\> [system.windows.forms.screen]::allscreens
    BitsPerPixel : 32
    Bounds       : {X=0,Y=0,Width=1600,Height=900}
    DeviceName   : \\.\DISPLAY1
    Primary      : True
    WorkingArea  : {X=0,Y=0,Width=1600,Height=854}

    BitsPerPixel : 32
    Bounds       : {X=1600,Y=0,Width=1920,Height=1080}
    DeviceName   : \\.\DISPLAY2
    Primary      : False
    WorkingArea  : {X=1600,Y=0,Width=1920,Height=1080}

Code Block

    public class Screen
    {
        [StructLayout(LayoutKind.Sequential)]
        private struct RECT
        {
            public int Left;
            public int Top;
            public int Right;
            public int Bottom;

            public Rectangle ToRectangle()
            {
                return Rectangle.FromLTRB(Left, Top, Right, Bottom);
            }
        }

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = false)]
        private static extern IntPtr GetForegroundWindow();

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = false)]
        private static extern IntPtr GetDesktopWindow();

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = false)]
        private static extern IntPtr GetShellWindow();

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = false)]
        private static extern int GetWindowRect(IntPtr hWnd, out RECT rc);

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = false)]
        static extern int GetWindowText(IntPtr hWnd, StringBuilder text, int count);

        [DllImport("dwmapi.dll")]
        static extern int DwmGetWindowAttribute(IntPtr hwnd, int dwAttribute, out RECT pvAttribute, int cbAttribute);


        private static IntPtr desktopHandle;
        private static IntPtr shellHandle;


        private enum Dwmwindowattribute
        {
            DwmwaExtendedFrameBounds = 9
        }

        private static Rectangle GetWindowRect(IntPtr handle)
        {
            RECT rect;
            GetWindowRect(handle, out rect);
            return rect.ToRectangle();
    }   

        private static bool DWMWA_EXTENDED_FRAME_BOUNDS(IntPtr handle, out Rectangle rectangle)
        {
            RECT rect;
            var result = DwmGetWindowAttribute(handle, (int)Dwmwindowattribute.DwmwaExtendedFrameBounds, out rect, Marshal.SizeOf(typeof(RECT)));
            rectangle = rect.ToRectangle();
            return result >= 0;
        }

        public static Rectangle GetWindowRectangle(IntPtr handle)
        {
            if (Environment.OSVersion.Version.Major < 6)
            {
                return GetWindowRect(handle);
            }
            else
            {
                Rectangle rectangle;
                return DWMWA_EXTENDED_FRAME_BOUNDS(handle, out rectangle) ? rectangle : GetWindowRect(handle);
            }
        }

        public static bool IsFullScreenWindow(string fullScreenWindowTitle)
        {
            desktopHandle = GetDesktopWindow();
            shellHandle = GetShellWindow();

            bool runningFullScreen = false;
            System.Drawing.Rectangle screenBounds;
            const int nChars = 256;
            StringBuilder Buff = new StringBuilder(nChars);
            string mainWindowTitle = "";
            IntPtr hWnd;
            System.Threading.Thread.Sleep(5000);
            hWnd = GetForegroundWindow();

            if (hWnd != null && !hWnd.Equals(IntPtr.Zero))
            {
                if (!(hWnd.Equals(desktopHandle) || hWnd.Equals(shellHandle)))
                {
                    if (GetWindowText(hWnd, Buff, nChars) > 0)
                    {
                        mainWindowTitle = Buff.ToString();
                        //Console.WriteLine(mainWindowTitle);
                    }

                    // If the main window title contains the text being searched for, then check to see if the window is in fullscreen mode.
                    Match match = Regex.Match(mainWindowTitle, fullScreenWindowTitle, RegexOptions.IgnoreCase);
                    if ((!string.IsNullOrEmpty(fullScreenWindowTitle)) && match.Success)
                    {
                        
                        System.Drawing.Rectangle appBounds = GetWindowRectangle(hWnd);

                        screenBounds = System.Windows.Forms.Screen.FromHandle(hWnd).Bounds;

                        if (appBounds == screenBounds)
                        {
                            runningFullScreen = true;
                        }
                    }
                }
            }
            return runningFullScreen;
        }
    }

**Comment by mmashwani** [comment]
Great job figuring that out! Is there any reason that you put the thread to sleep for 5 seconds? I would rather avoid that unless there is a good reason for it being there.

**Comment by mmashwani** [comment]
In my testing, I noticed that if PowerPoint is in fullscreen on the primary monitor and you place the mouse focus on the secondary monitor, then it does not detect that PowerPoint is in fullscreen mode.

**Comment by mmashwani** [comment]
OK, I had to completely re-write the function. I did a lot of testing to try and think of all the different conditions that you could run PowerPoint and presentations in, but I would appreciate if you can do some testing on your side as well to confirm that things are working as expected.

**Comment by DennisVH** [comment]
The function works as expected.
The second check does also captures other applications that run full screen on the primary monitor with focus, f.e. Internet Explorer (F11 full screen)

To eliminate this I suggest the following:
When fullscreen is not detected in first check retrieve Powerpoint Process ID
verify when PresentationMode or FullScreenOrPresentationModeOrLoginScreen is detected that the foregroundwindow is Powerpoint

	Process {
		Try {
			Write-Log -Message 'Check if PowerPoint is in fullscreen slideshow mode...' -Source ${CmdletName}
			[boolean]$IsPowerPointFullScreen = $false
			If (Get-Process -Name 'POWERPNT' -ErrorAction 'SilentlyContinue') {
				Write-Log -Message 'PowerPoint application is running.' -Source ${CmdletName}
				
				## Detect if PowerPoint is in fullscreen mode or Presentation Mode, detection method only works if process is interactive
				If ([Environment]::UserInteractive) {
					#  Check if "POWERPNT" process has a window with a title that begins with "PowerPoint Slide Show"
					#  There is a possiblity of a false positive if the PowerPoint filename starts with "PowerPoint Slide Show"
					[psobject]$PowerPointWindow = Get-WindowTitle -WindowTitle '^PowerPoint Slide Show' | Where-Object { $_.ParentProcess -eq 'POWERPNT'} | Select-Object -First 1
					If ($PowerPointWindow) {
						[boolean]$IsPowerPointFullScreen = $true
						Write-Log -Message 'Detected that PowerPoint process [POWERPNT] has a window with a title that beings with [PowerPoint Slide Show].' -Source ${CmdletName}
					}
					Else {
						Write-Log -Message 'Detected that PowerPoint process [POWERPNT] does not have a window with a title that beings with [PowerPoint Slide Show].' -Source ${CmdletName}
						$PowerPointProcessID = (Get-Process -Name 'POWERPNT' -ErrorAction 'SilentlyContinue').Id
					}
					
					## If previous detection method did not detect PowerPoint in fullscreen mode, then check if PowerPoint is in Presentation Mode (check only work on Windows Vista or higher)
					If ((-not $IsPowerPointFullScreen) -and ([Environment]::OSVersion.Version.Major -gt 5)) {
						#  Note: below method does not detect PowerPoint presentation mode if the presentation is on a monitor that does not have current mouse input control
						[string]$UserNotificationState = [PSADT.UiAutomation]::GetUserNotificationState()
						Write-Log -Message "Detected user notification state [$UserNotificationState]." -Source ${CmdletName}
						Switch ($UserNotificationState) {
							'PresentationMode'
							{
								If ([PSADT.UIAutomation]::GetWindowThreadProcessID([PSADT.UIAutomation]::GetForeGroundWindow()) -eq $PowerPointProcessID)
								{
									[boolean]$IsPowerPointFullScreen = $true
								}
							}
							'FullScreenOrPresentationModeOrLoginScreen'
							{
								If ([PSADT.UIAutomation]::GetWindowThreadProcessID([PSADT.UIAutomation]::GetForeGroundWindow()) -eq $PowerPointProcessID)
								{
									[boolean]$IsPowerPointFullScreen = $true
								}
							}
						}
					}
				}
				Else
				{
					Write-Log -Message 'Unable to run check to see if PowerPoint is in fullscreen mode or Presentation Mode because current process is not interactive. Configure script to run in interactive mode in your deployment tool. If using SCCM Application Model, then make sure "Allow users to view and interact with the program installation" is selected. If using SCCM Package Model, then make sure "Allow users to interact with this program" is selected.' -Severity 2 -Source ${CmdletName}
				}
			}
			Else
			{
				Write-Log -Message 'PowerPoint application is not running.' -Source ${CmdletName}
			}
		}
		Catch
		{
			Write-Log -Message "Failed check to see if PowerPoint is running in fullscreen slideshow mode. `n$(Resolve-Error)" -Severity 3 -Source ${CmdletName}
		}
	}

**Comment by mmashwani** [comment]
Great, thanks for testing and making those updates. I will incorporate your changes into the function.

**Comment by mmashwani** [comment]
I updated the function with your suggestion. I modified things a bit so please test again and let me know if it's working as expected.

**Comment by DennisVH** [comment]
For me it works as expected.
@FlashGordon7, do you have any feedback?

**Comment by FlashGordon7** [comment]
Now I got some time to test.
And it also works as expected for me now. Thanks for the great work :-)
If I try to "Auto" defer when powerpoint is running, I get a installation failed balloon tip notification. 
Is there any way to supresse that?
I have tried this, but I still get the balloon tip notification.
```
$configShowBalloonNotifications = $false
Exit-Script -ExitCode 69012
```
Maybe it's a new issue and should be a parameter for Exit-Script?

**Comment by mmashwani** [comment]
@FlashGordon7 
It's a new issue so please create a new ticket for it. I think we should have a check in the balloon tip notification function so that it does not display anything if user is running PowerPoint in fullscreen mode. I think that would resolve your issue right?

**Comment by FlashGordon7** [comment]
Yes, that should solve it.
