### ISSUE TITLE
Show-InstallationWelcome with AllowDefer or AllowDeferCloseApps parameter doesn't list applications when there are multiple instances of a process

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#1070]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2

### Describe the bug

When using Show-InstallationWelcome with AllowDefer option, application with multiple instances of the same process name aren't listed in the close applications field because the ProcessDescription NoteProperty added to $runningProcesses contains an array.
When using Show-InstallationWelcome with AllowDeferCloseApps option, application with multiple instances of the same process name doesn't show the close applications prompt at all because the ProcessDescription field contains an empty array.
If it is the only application is needs to close the prompt isn't shown at all.

### Steps to reproduce

A: AllowDefer
1. You can test with an installation of Adobe Acrobat Reader and open the application. There are 2 instances of the AcroRd32 process
2. Show-InstallationWelcome -CloseApps 'A3DUtility,AcroRd32,Acrobat,acrodist,acrord32,AcroCEF' -AllowDefer -DeferTimes 3 -ForceCloseAppsCountdown 3600
Result:
![image](https://github.com/user-attachments/assets/419e417b-a6a2-4257-a0ee-4410df239994)

B: AllowDeferClose
1. You can test with an installation of Adobe Acrobat Reader and open the application. There are 2 instances of the AcroRd32 process
2. Show-InstallationWelcome -CloseApps 'A3DUtility,AcroRd32,Acrobat,acrodist,acrord32,AcroCEF' -AllowDeferCloseApps -DeferTimes 3 -ForceCloseAppsCountdown 3600
Result: no prompt is show at al because the deferral because there are no apps to be closed due to $runningProcessDescriptions being empty

Solution is to add | Select-Object -First 1 to line 9269 in AppDeployToolkitMain.ps1
`if (![System.String]::IsNullOrEmpty(($objDescription = ($processObjects | Where-Object {$_.ProcessName -eq $process.ProcessName} | Select-Object -First 1).ProcessDescription)))`

A: AllowDefer and AllowDeferCloseApps
![image](https://github.com/user-attachments/assets/d47162fe-ed7c-480c-9881-de478ce18880)

### Environment data

```console
OsName               : Microsoft Windows 10 Pro Education
OsOperatingSystemSKU : 164
OsArchitecture       : 64 bits
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro Education
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : nl-NL
OsMuiLanguages       : {nl-NL}
KeyboardLayout       : nl-BE
TimeZone             : (UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile
```

**Comment by mjr4077au** [comment]
Thank you, this is patched in our v4 tree 😎
