### ISSUE TITLE
[Bug] Detection of ESP User Account Setup Phase is failing on Windows 365 Cloud PCs

### ISSUE THREAD

**Issue by seanlillis** [PSAppDeployToolkit/PSAppDeployToolkit#1073]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2

### Describe the bug

The code for ESP detection is taken from: https://oofhours.com/2023/09/15/detecting-when-you-are-in-oobe/

$IsOOBEComplete returns 1 if OOBE is complete and 0 otherwise. This is handled as a boolean but this doesn't seem to be the issue because 0 & 1 will match $false and $true. The issue appears to be that $IsOOBEComplete is not consistently returning the correct value during ESP.

### Steps to reproduce

`    If (!($IsOOBEComplete)) {
        Write-Log -Message "Detected OOBE in progress, changing deployment mode to silent." -Source $appDeployToolkitName
        $deployMode = 'Silent'
    }`

![image](https://github.com/user-attachments/assets/28c7764f-f113-4295-935e-1bcb6ebb12c0)

### Environment data

```console
N/A
```

**Comment by Pollewops** [comment]
What needs to be changed to 3.10.2 version to make it work again?

**Comment by mjr4077au** [comment]
> What needs to be changed to 3.10.2 version to make it work again?

@Pollewops at the mininum, I'd change [these lines](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/3bec2493bedff2e16aa4f2b51f9b2bbffa9e4c6f/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L17215C1-L17218C30) to:
```PowerShell
    [int]$IsOOBEComplete = $null
    $hr = [Api.Kernel32]::OOBEComplete([ref] $IsOOBEComplete)

    If ($IsOOBEComplete -eq 0) {
```

**Comment by seanlillis** [comment]
Nice one @mjr4077au - thanks.

**Comment by seanlillis** [comment]
I left out an important detail. This issue is happening on Windows 365 devices during ESP. The logic that works for Autopilot OOBE does not work for Windows 365 devices that are running ESP. Alternative logic is needed for Windows 365 to check if the User Account Setup phase is running, which is where Win32 apps are installing during the ESP on W365.

This is explained in the Microsoft docs below:

"When using Windows Autopilot to provision new physical Windows devices, the ESP runs in two phases: the device ESP and the user ESP. The device ESP runs only during the default out-of-box experience (OOBE). When provisioning Cloud PCs, the device ESP is not used, as there's no OOBE phase, only the user ESP."
 
"If ESP is enabled, the Account setup phase of ESP is shown to the user. (The Device setup phase isn't supported for Cloud PCs. It only occurs during Autopilot in OOBE.)"

[Application deployment in Windows 365: recommended practices | Microsoft Community Hub](https://techcommunity.microsoft.com/blog/windows-itpro-blog/application-deployment-in-windows-365-recommended-practices/3915376)

[Use the Enrollment Status Page with Cloud PCs | Microsoft Learn](https://learn.microsoft.com/en-us/windows-365/enterprise/enrollment-status-page)

A quick and dirty solution is the code below, but I would like to find a more elegant solution.

`# Check if the SystemProductName value contains "Cloud PC" in the registry path
$registryPath = "HKLM:\SYSTEM\CurrentControlSet\Control\SystemInformation"
if ((Get-ItemProperty -Path $registryPath).SystemProductName -like "*Cloud PC*") {
    Write-Output "This machine is a Windows 365 Cloud PC. Checking the ESP User Account Setup phase."
    # Check if the process "WWAHost is running"
    If (Get-Process -Name "WWAHost" -ErrorAction SilentlyContinue) {
        Write-Output "WWAHost process is running."
        $regPathEnrollments = "HKLM:\SOFTWARE\Microsoft\Enrollments"
        # Get all subkeys that contain the string "FirstSync"
        $firstSyncPath = Get-ChildItem -Path $regPathEnrollments -Recurse | Where-Object { $_.PSChildName -contains "FirstSync" }
        if ($firstSyncPath) {
            Write-Output "FirstSync key found"
            foreach ($subkey in $firstSyncPath) {
                if (Get-ItemProperty -Path $subkey.PSPath -Name "IsSyncDone" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty IsSyncDone) 
                {
                    Write-Output "IsSyncDone value: $isSyncDone. The ESP User Account Setup phase is complete."
                } else {
                    Write-Output "IsSyncDone value not found. The ESP User Account Setup phase is still in progress. Setting deployment mode to Silent."
                    $deployMode = 'Silent'   
                }
            }        
        } 
    } else {
        Write-Output "WWAHost process is not running. The ESP User Account Setup phase is not in progress."
    }    
} else {
    Write-Output "This machine is not a Windows 365 Cloud PC."
}
`

**Comment by mjr4077au** [comment]
Thanks for re-opening, this is definitely an area where the OOBE check would likely fail. I'm not immediately sure how one'd do this better, but I'll do some research and testing.

**Comment by seanlillis** [comment]
I've tested this code and it's working, runs silent in ESP on W365 and interactive outside ESP:

````
If ($IsOOBEComplete -eq 0) {
        Write-Log -Message "Detected OOBE in progress, changing deployment mode to silent." -Source $appDeployToolkitName
        $deployMode = 'Silent'
    }
    ElseIf (Get-Process -Name "WWAHost" -ErrorAction SilentlyContinue) {
        Write-Log "The WWAHost process is running. Checking ESP User Account Setup phase."
        $firstSyncPath = Get-ChildItem -Path "HKLM:\SOFTWARE\Microsoft\Enrollments" -Recurse | Where-Object { $_.PSChildName -contains "FirstSync" }
        If ((Get-ItemProperty -Path $firstSyncPath.PSPath -Name "IsSyncDone" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty IsSyncDone) -eq '1') {
            Write-Log "The ESP User Account Setup phase is complete."
        } Else {
            Write-Log "IsSyncDone value not found. The ESP User Account Setup phase is still in progress. Setting deployment mode to Silent."
            $deployMode = 'Silent'  
        }  
    }
```

**Comment by seanlillis** [comment]
Nice one @mjr4077au, looks good, thanks.

**Comment by Pollewops** [comment]
Tested on W365 and cloud device. Worked well.
