### ISSUE TITLE
Test-Driven development? Where might I run the tests?

### ISSUE THREAD

**Issue by lboening** [PSAppDeployToolkit/PSAppDeployToolkit#108]
Are you testing the project? I would like to run the tests. My hope is to make sure the feature I might add does not ruin anything.

**Comment by amotaz** [comment]
We doe some testing. What feature are you interested in adding Iboening?

**Comment by lboening** [comment]
1. I would like to POST a JSON body to a REST service. The contents of the object would come from a Powershell custom object that I would fill depending on my needs. This would help with the reporting from the app deployment event. I know SCCM covers some of this space, but not it rarely gets to the detail I would like to see.

2. I would like to GET a response from a REST service. The response object, a JSON response, could be converted into a Powershell object. I could use this to serve as the source of variables for setting up the script. 

I already do this with a home-made script. I suppose it is a feature enhancement.

I also have a custom of using PESTER to at least add some rudimentary tests to each script. Each script is supposed to have a custom TESTS.ps1 file.

**Comment by lboening** [comment]
I just forked your lovely program! I will try to demo my new feature, new test method.

**Comment by amotaz** [comment]
We'll definitely keep an eye on your fork and look towards integrating anything into our toolkit that looks promising.

**Comment by lboening** [comment]
I suppose this means the issue can be "closed" until I drum up a new feature with a new test.

**Comment by amotaz** [comment]
I think I'd prefer to keep it open here so we can track it. If you have anything new you'd like us to pay special attention to you can post it here. Does that work for you?

**Comment by lboening** [comment]
1. I am preparing a simple test for the forked version. I will add a PESTER test, then see if it runs. 
2. My intention is to add a feature. Maybe I don't have to add a feature. In the readme, it says it is "extensible" by allowing for a spot to run custom actions. Would this be a better approach?
3. I am trying to create a JSON/REST output, from any "running" of the the toolkit, that  can send to my JSON/REST/API/NODEJS/MONGODB server. I already do this with a handful of home-made scripts.

**Comment by luki1412** [comment]
This issue is way out of date so I'm closing it. For the sake of completion:

There isn't an official test environment for this project (yet). We do test the toolkit and it is used heavily in production already as well.

You can send http requests through built-in powershell function Invoke-WebRequest(PS3+) or through .NET classes HttpWebRequest or HttpClient(.NF 4.5+). Since Windows 7 is now out of support, a custom function for this doesn't make much sense anymore.
