### ISSUE TITLE
[Not a Bug] Windows Sandbox on Windows 11 10.0.26100.2454 (2024-11 Cumulative Update Preview) breaks WMI/CIM commands

### ISSUE THREAD

**Issue by mjr4077au** [PSAppDeployToolkit/PSAppDeployToolkit#1088]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2, 3.93.0

### Describe the bug

Upon booting the toolkit under Windows Sandbox at this patch level, the toolkit will fail to initialise with an "Access is denied" error from `Get-CimInstance`/`Get-WmiObject` calls.

### Steps to reproduce

Working on 10.0.26100.2314:
![sandboxWorking](https://github.com/user-attachments/assets/edd42540-b0bc-4be4-bb50-7c5304e1570f)

Broken on 10.0.26100.2454:
![image](https://github.com/user-attachments/assets/4d0829d9-066e-4ce6-9f43-6ab143f843a4)

### Environment data

```console
Windows 11 10.0.26100.2454
```

**Comment by mjr4077au** [comment]
Seems to be resolved!

![image](https://github.com/user-attachments/assets/32e4cc9c-b981-4dd5-b6d5-4eec0d7e3c0a)

**Comment by Vaflor** [comment]
Same here. I reinstalled Sandbox - it worked for some hours (until an update?) then it was broken again. 
no ciminstance or wmi - all access denied.

**Comment by Mailstorm-ctrl** [comment]
Not sure why this was closed. It's busted still. Version 2894

**Comment by mjr4077au** [comment]
I can reopen it but there's nothing we can do about the issue, either.

**Comment by Mailstorm-ctrl** [comment]
Yeah not sure. But re-installing sandbox will work if only temporarily.

**Comment by JonathanPitre** [comment]
seems to work fine on Windows 24H2 build 26100.2705

btw Windows 24H2 Build 26100.2705 has new Windows Sandbox features:

`Windows 11, version 24H2, includes build 26100.2705, which introduced the Windows Sandbox Client Preview. This preview includes features such as runtime clipboard redirection, audio and video input control, and sharing folders with the host at runtime.`

**Comment by JonathanPitre** [comment]
Windows 11 Insider Preview Build 27686
`This build includes the new Windows Sandbox Client Preview that is now updated via the Microsoft Store. It introduces runtime clipboard redirection, audio/video input control, and the ability to share folders with the host at runtime. You can access these via the new “…” icon at the upper right on the app. This preview also includes a very early version of command line support. (Commands may change over time.) You can use the wsb.exe –help command for more information.`

https://www.computerworld.com/article/1614352/windows-11-insider-previews-whats-in-latest-build.html
