### ISSUE TITLE
very small bug with blocked app title

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#109]
version 3.6.6
it looks like somewhere spaces gone from "[string]$appName" in the title for blocked application pop-up.
My configuration was:
	[string]$appVendor = 'Oracle'
	[string]$appName = 'Java 8 Update 66'
	[string]$appVersion = '8.0.660.17'
	[string]$appArch = ''
	[string]$appLang = 'EN'

and when some application was blocked by toolkit script, I see the toolkit popup and it's title is:
"Oracle Java8Update66 8.0.660.17 EN 01"

**Comment by mmashwani** [comment]
Thanks for reporting this. This should be resolved in the next release.
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/c4909598ff3f6c7c5ae2b28d1f447215c8473a15
