### ISSUE TITLE
[Bug] Show-ADTInstallationWelcome -PromptToSave error

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#1107]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

Show-ADTInstallationWelcome -PromptToSave cause an error after clicking the button

![image](https://github.com/user-attachments/assets/ba404547-a149-4e1a-bfde-8c30e3fedbff)

### Steps to reproduce

I ran
$AppsToClose = 'excel'

Show-ADTInstallationWelcome -CloseProcesses "$AppsToClose" -AllowDefer -DeferTimes 3 -BlockExecution -NoMinimizeWindows -PromptToSave -PersistPrompt

Also Switch -TopMost is not working

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile

.NET SDK:
 Version:           8.0.404
 Commit:            7b190310f2
 Workload version:  8.0.400-manifests.c6df56b6
 MSBuild version:   17.11.9+a69bbaaf5

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.404\
```

**Comment by mjr4077au** [comment]
This has been addressed in our develop branch. Thank you for the report!

**Comment by mjr4077au** [comment]
Closing this one off as it'll be in the upcoming point release.
