### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tettekop** [PSAppDeployToolkit/PSAppDeployToolkit#1109]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

Some translations in the NL (Dutch) version are in Norwegian
1. D:\ADT4\PSAppDeployToolkit_4.0.2\Strings\nl
2.  Line58 to64

### Steps to reproduce

my updated version:

@{
    BalloonText    = @{
        Complete        = "voltooid"
        Error           = "gefaald"
        FastRetry       = "onvolledig"
        RestartRequired = "voltooid. Een herstart is nodig"
        Start           = "gestart"
    }
    BlockExecution = @{
        Message = "Het opstarten van deze applicatie werd tijdelijk geblokkeerd om een installatie uit te voeren."
    }
    ClosePrompt    = @{
        ButtonClose           = "Sluit Applicaties"
        ButtonContinue        = "Doorgaan"
        ButtonContinueTooltip = "Selecteer alleen 'Doorgaan' na het sluiten van de bovenstaande toepassing(en)."
        ButtonDefer           = "Uitstel"
        CountdownMessage      = "LET OP: De applicatie(s) worden afgesloten over:"
        Message               = "De volgende applicaties moeten afgesloten worden om de installatie te voltooien.`n`nSla je werk op, sluit de applicaties, en ga verder.`nOf, sla je werk op en klik op 'Sluit Applicaties'."
    }
    DeferPrompt    = @{
        Deadline           = "Deadline:"
        ExpiryMessage      = "Je kan de installatie uitstellen tot de maximale uitsteltermijn is verstreken:"
        RemainingDeferrals = "Aantal keer uitstellen:"
        WarningMessage     = "Na verstrijken van de uitsteltermijn is deze optie niet langer beschikbaar."
        WelcomeMessage     = "De volgende applicatie wordt zometeen geïnstalleerd:"
    }
    DeploymentType = @{
        Install   = "Installatie"
        Repair    = "Reparatie"
        Uninstall = "Verwijderen"
    }
    DiskSpace      = @{
        Message = "Er is onvoldoende schijfruimte voor de installatie van:`n{0}`n`nRuimte nodig: {1}MB`nRuimte beschikbaar: {2}MB`n`nGelieve voldoende schijfruimte vrij te maken om de installatie te starten."
    }
    Progress       = @{
        MessageInstall         = "Installatie bezig. Even geduld..."
        MessageInstallDetail   = "Dit venster wordt automatisch gesloten wanneer de installatie voltooid is."
        MessageRepair          = "Reparatie bezig. Even geduld..."
        MessageRepairDetail    = "Dit venster sluit automatisch wanneer de reparatie is voltooid."
        MessageUninstall       = "Verwijderen bezig. Even geduld..."
        MessageUninstallDetail = "Dit venster wordt automatisch gesloten als de de-installatie voltooid is."
    }
    RestartPrompt  = @{
        ButtonRestartLater = "Minimaliseren"
        ButtonRestartNow   = "Herstart Nu"
        Message            = "Om de installatie te voltooien is een herstart nodig."
        MessageRestart     = "De computer zal herstarten als de teller op nul staat"
        MessageTime        = "Gelieve je werk op te slaan en binnen de toegestane termijn de computer herstarten"
        TimeRemaining      = "Resterende tijd:"
        Title              = "Herstart nodig"
    }
    WelcomePrompt  = @{
        Classic = @{
            CountdownMessage = "De {0} gaat automatisch door over:"
            CustomMessage    = ""
        }
        Fluent  = @{
            Subtitle      = 'PSAppDeployToolkit - App {0}'
            DialogMessage = "Sla je werk op voordat je verdergaat, want de volgende programma's worden automatisch afgesloten."
            DialogMessageNoProcesses = 'Selecteer Installeren om door te gaan met de installatie. Als je nog uitstel hebt, kun je er ook voor kiezen om de installatie uit te stellen.'
            ButtonDeferRemaining = 'resterend'
            ButtonLeftText = 'Uitstellen'
            ButtonRightText = 'Apps sluiten en installeren'
            ButtonRightTextNoProcesses = 'Installeren'
        }
    }
}

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64 bits
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : nl-NL
OsMuiLanguages       : {nl-NL, en-US}
KeyboardLayout       : 00020409
TimeZone             : (UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile


global.json file:
  Not found

Host:
  Version:      6.0.36
  Architecture: x64
  Commit:       f1dd57165b

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by mjr4077au** [comment]
Thanks for your report! Can you please make it clearer what translations require updating? Some new translations were via AI, so its understandable they may not be amazing.

**Comment by tettekop** [comment]
Norwegian lines in the NL version
Lines:
37        MessageInstallDetail = "Dette vinduet lukkes automatisk når installasjonen er fullført."
39        MessageRepairDetail = "Dette vinduet lukkes automatisk når reparasjonen er fullført."
41        MessageUninstallDetail = "Dette vinduet lukkes automatisk når avinstallasjonen er fullført."

59        DialogMessage = 'Lagre arbeidet ditt før du fortsetter, da de følgende programmene lukkes automatisk.'
60        DialogMessageNoProcesses = 'Velg Installer for å fortsette med installasjonen. Hvis du har noen utsettelser igjen, kan du også velge å utsette installasjonen.'
61        ButtonDeferRemaining = 'forbli'
62        ButtonLeftText = 'Utsette'
63        ButtonRightText = 'Lukk apper og installer'
64        ButtonRightTextNoProcesses = 'Installere'


Dutch translations:
37        MessageInstallDetail   = "Dit venster wordt automatisch gesloten wanneer de installatie voltooid is."
39        MessageRepairDetail    = "Dit venster sluit automatisch wanneer de reparatie is voltooid."
41        MessageUninstallDetail = "Dit venster wordt automatisch gesloten als de de-installatie voltooid is."

59          DialogMessage = "Sla je werk op voordat je verdergaat, want de volgende programma's worden automatisch afgesloten."
60          DialogMessageNoProcesses = 'Selecteer Installeren om door te gaan met de installatie. Als je nog uitstel hebt, kun je er ook voor kiezen om de installatie uit te stellen.'
61          ButtonDeferRemaining = 'resterend'
62          ButtonLeftText = 'Uitstellen'
63          ButtonRightText = 'Apps sluiten en installeren'
64          ButtonRightTextNoProcesses = 'Installeren'

**Comment by mjr4077au** [comment]
This has been addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/dbb0f25a0679cfea6333077e6f03fce1014a7683. Full disclosure, this is completely my mistake but thank you for pointing it out and providing the correct translations! 🤜🤛

**Comment by mjr4077au** [comment]
Closing this one now since it's addressed. This will be in the upcoming point release.
