### ISSUE TITLE
Add -SecureParameter switch to Execute-Process, Execute-MSI, etc?

### ISSUE THREAD

**Issue by appPackager** [PSAppDeployToolkit/PSAppDeployToolkit#111]
This is an enhancement request..

The "MsiHiddenProperties" property can be used to prevent Windows Installer from displaying passwords or other confidential information in the MSI log file, however, if those parameters are passed into the msi from the command-line PSAppDeployToolkit still logs those properties.  Can a -SecureParameter optional argument be added to "Execute-Process", "Execute-MSI" and "Execute-ProcessAsUser" routines which, when used, will hide those parameters from the PSAppDeployToolkit log file and maybe write "(Hidden)" in it's place? 

Example of log file entry:
[Installation] :: Executing [c:\windows\notepad.exe /S (Hidden)]...	Execute-Process	11/3/2015 3:07:49 PM	57816 (0xE1D8)

**Comment by amotaz** [comment]
This enhancement makes sense, we'll look to adding it in a future version.

**Comment by amotaz** [comment]
I added this, although if the parameter is not in the MsiHiddenProperties property it will still show up in the msi log. We may add some functionality for that in the next major version.
