### ISSUE TITLE
[Bug] Start / Stop-ADTServiceAndDependencies throws "Cannot convert null to type "System.ServiceProcess.ServiceControllerStatus"

### ISSUE THREAD

**Issue by the-project-group** [PSAppDeployToolkit/PSAppDeployToolkit#1112]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

Hi,
I'm just trying latest version and get an exception when calling `Stop-ADTServiceAndDependencies -Service 'NetBird' `:
![CleanShot 2024-12-05 at 14 18 28@2x](https://github.com/user-attachments/assets/0668e9c0-f575-47bd-bdfd-1e68e1bc4ea3)

```
Message : Cannot convert null to type "System.ServiceProcess.ServiceControllerStatus" due to enumeration values that are not valid. Specify one of the following enumeration values and try again.
The possible enumeration values are "Stopped, StartPending, StopPending, Running, ContinuePending, PausePending, Paused
```

Also I'd like to use additional variables like to use later like:
`Show-ADTInstallationWelcome -CloseProcesses AppExe -DeferTimes 3 -CheckDiskSpace -PersistPrompt -CloseProcessesCountdown 600`

```
$adtSession = @{
    # App variables.
    AppVendor = ''
    AppName = 'Netbird'
    AppVersion = '0.34.0'
    AppArch = ''
    AppLang = 'EN'
    AppRevision = '01'
    AppSuccessExitCodes = @(0)
    AppRebootExitCodes = @(1641, 3010)
    AppScriptVersion = '1.0.0'
    AppScriptDate = '2024-12-05'
    AppScriptAuthor = 'MY NAME'
    AppExe = 'netbird-ui,netbird' # https://psappdeploytoolkit.com/docs/reference/functions/Show-InstallationWelcome/
    AppServiceName = 'NetBird'
```
It also doesn't work if I define the additional variables outside $adtSession like this:
`$AppExe = 'netbird-ui,netbird' # https://psappdeploytoolkit.com/docs/reference/functions/Show-InstallationWelcome/`

But it only works if I set the names directly when they're called:
`Show-ADTInstallationWelcome -CloseProcesses @{ Name = 'netbird'; Description = 'Netbird Windows Service' }, @{ Name = 'netbird-ui'; Description = 'Netbird UI / Systemtray Icon' } -DeferTimes 3 -CheckDiskSpace -PersistPrompt -CloseProcessesCountdown 600`

For other commands like Start-ADTMsiProcess it works if I define it at the beginning:
```
##================================================
## MARK: Variables
##================================================
$AppExe = 'netbird-ui,netbird' # https://psappdeploytoolkit.com/docs/reference/functions/Show-InstallationWelcome/
$AppServiceName = 'NetBird'
$AppMsiFile = Get-Item .\Files\*.msi
$AppMsiFile = $AppMsiFile.Name

...

Start-ADTMsiProcess -Action 'Install' -FilePath $AppMsiFile
```

What am I doing wrong?

### Steps to reproduce

1. Call Stop-ADTServiceAndDependencies or Start-ADTServiceAndDependencies

### Environment data

```console
sName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, de-DE, en-US}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop


global.json file:
  Not found

Host:
  Version:      6.0.36
  Architecture: x64
  Commit:       f1dd57165b

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mjr4077au** [comment]
The underlying issue with `Invoke-ADTServiceAndDependencyOperation` has been resolved with https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/4dc2b95b3efaf59d9d818861ecd2dc94f27b190d. This will come in the next point release.

Regarding your `$AppExe` setup. You can construct full objects using hashtables as initialiser lists like you were doing, or use strings if you don't need to provide a description. With this in mind, you must pass through the strings individually and not a singular comma-joined string. Your example of `$AppExe = 'netbird-ui,netbird'` should be `$AppExe = 'netbird-ui', 'netbird'`, which will work how you'd expect.

**Comment by mjr4077au** [comment]
Thanks for confirming the fix! This will make it into our next point release shortly.
