### ISSUE TITLE
[Bug] $dirFiles not populated when used in Start-ADTProcess

### ISSUE THREAD

**Issue by tintong** [PSAppDeployToolkit/PSAppDeployToolkit#1114]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

When adding $dirFiles in the "-FilePath" switch for Start-ADTProcess, PSADT fails with the following error:

`[2024-12-05 16:01:10.593] [Install] [Start-ADTProcess] [Error] :: File [/test/AudioMothConfigurationAppSetup1.12.0.exe] not found.
[2024-12-05 16:01:10.601] [Install] [Start-ADTProcess] [Error] :: Error occurred while attempting to start the specified process.
Error Record:
-------------

Message               : File [/test/AudioMothConfigurationAppSetup1.12.0.exe] not found.

FullyQualifiedErrorId : PathFileNotFound,Start-ADTProcess
ScriptStackTrace      : at Start-ADTProcess<Process>, C:\temp\v1.12.0\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 19220
                        at Install-ADTDeployment, C:\temp\v1.12.0\Invoke-AppDeployToolkit.ps1: line 163
                        at <ScriptBlock>, C:\temp\v1.12.0\Invoke-AppDeployToolkit.ps1: line 310
                        at <ScriptBlock>, <No file>: line 1

PositionMessage       : At C:\temp\v1.12.0\Invoke-AppDeployToolkit.ps1:163 char:5
                        +     Start-ADTProcess -FilePath "$dirFiles/test/AudioMothConfiguration ...
                        +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2024-12-05 16:01:10.608] [Install] [Invoke-AppDeployToolkit.ps1] [Error] :: Error Record:
-------------

Message               : File [/test/AudioMothConfigurationAppSetup1.12.0.exe] not found.

FullyQualifiedErrorId : PathFileNotFound,Start-ADTProcess
ScriptStackTrace      : at Start-ADTProcess<Process>, C:\temp\v1.12.0\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 19220
                        at Install-ADTDeployment, C:\temp\v1.12.0\Invoke-AppDeployToolkit.ps1: line 163
                        at <ScriptBlock>, C:\temp\v1.12.0\Invoke-AppDeployToolkit.ps1: line 310
                        at <ScriptBlock>, <No file>: line 1

PositionMessage       : At C:\temp\v1.12.0\Invoke-AppDeployToolkit.ps1:163 char:5
                        +     Start-ADTProcess -FilePath "$dirFiles/test/AudioMothConfiguration ...
                        +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

Command I used for the installation of the .exe:
`Start-ADTProcess -FilePath "$dirFiles/test/AudioMothConfigurationAppSetup1.12.0.exe" -ArgumentList "/S" -WindowStyle "Hidden" -WaitForMsiExec`

Please let me know if I have missed anything. First time submitting a bug here.

### Steps to reproduce

1. Create new template
2. Fill in the required info
3. Use "Start-ADTProcess" function install an .exe program, for example:
`Start-ADTProcess -FilePath "$dirFiles/test/AudioMothConfigurationAppSetup1.12.0.exe" -ArgumentList "/S" -WindowStyle "Hidden" -WaitForMsiExec`
4. Run PSADT from a PowerShell window/console

### Environment data

```console
OsName               : Microsoft Windows 10 Education
OsOperatingSystemSKU : 121
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Education
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB}
KeyboardLayout       : en-GB
TimeZone             : (UTC+00:00) Dublin, Edinburgh, Lisbon, London
HyperVisorPresent    : False
CsPartOfDomain       : True
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
Two things here: Windows doesn't use forward slashes (`/`) for file path separators, so please use a backslash (`\`). Lastly, `$dirFiles` is no longer a valid variable, you'd need to use `$adtSession.DirFiles` to access the same data.

Our help is currently being expanded to explain the nuances of our class-based deployment objects and how to access the same familiar properties and will hopefully be live on the website soon.

**Comment by DanGough** [comment]
More info on these new session properties here:

https://psappdeploytoolkit.com/docs/adtsession-object

**Comment by MarkRouleau** [comment]
The documentation for the new Start-ADTProcess still references naked "$dirFiles" here: https://psappdeploytoolkit.com/docs/reference/functions/Start-ADTProcess

**Comment by mjr4077au** [comment]
Thanks for pointing that out, we'll get it amended shortly.

**Comment by tintong** [comment]
Thanks for the updated variable to use.
I can confirm that this works, but need to add it as $($adtSession.DirFiles) if within quotes.

Sorry about the wrong slash, that was me testing things.

**Comment by mjr4077au** [comment]
I'm glad the right variabls are working! The comment-based help has been addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/fb819e7ea9c8c2315aa1141bbf7b5f48244b854a and will be in the next point release.
