### ISSUE TITLE
[Bug] Show-ADTInstallationRestartPrompt ignoring -NoCountdown when not running interactively 

### ISSUE THREAD

**Issue by jeffmw777** [PSAppDeployToolkit/PSAppDeployToolkit#1115]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

Show-ADTInstallationRestartPrompt -NoCountdown produces a one minute restart countdown.  Does not occur when running interactively which shows the old style window.

### Steps to reproduce

1. Execute the command Show-ADTInstallationRestartPrompt -NoCountdown when running non-interactively

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
```

**Comment by mjr4077au** [comment]
I've addressed this in our develop branch via https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/48188000105af4474fee2f20ade40783bf42a782.

![image](https://github.com/user-attachments/assets/0f772187-32f1-45a9-93f2-a983f18e3b9f)

A new point release should be coming out shortly that will incorporate this.
