### ISSUE TITLE
[Bug] Start-ADTProcessAsUser -FilePath notepad.exe doesn't start any process

### ISSUE THREAD

**Issue by the-project-group** [PSAppDeployToolkit/PSAppDeployToolkit#1118]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

I'm testing post installation process execution and can't get it to work:
`Start-ADTProcessAsUser -FilePath notepad.exe -AllActiveUserSessions` (or without AllActiveUserSessions)
The log output is:
`[2024-12-05 20:49:11.427] [Post-Install] [Start-ADTProcessAsUser] [Info] :: Invoking [notepad.exe ] for all active user sessions.`
but it doesn't start the process.

### Steps to reproduce

1.`Start-ADTProcessAsUser -FilePath notepad.exe -AllActiveUserSessions`

### Environment data

```console
sName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, de-DE, en-US}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop


global.json file:
  Not found

Host:
  Version:      6.0.36
  Architecture: x64
  Commit:       f1dd57165b

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mjr4077au** [comment]
What user are you running `Start-ADTProcessAsUser` as? Its typically something we'd expect people call while running as SYSTEM.

**Comment by mjr4077au** [comment]
Generally speaking, its recommended to test all deployments as the user you'd be installing as, which is SYSTEM for most situations.

@mmashwani, can I confirm whether the `PSADT.ProcessEx.StartProcess` code is meant to work while running as any admin user, or only SYSTEM?

**Comment by DanGough** [comment]
Repeatable here, and it does work as the system account.

**Comment by mjr4077au** [comment]
This has been resolved in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/e84a448634fe7a8c134818e9d4ecf5435f3679bd and will be in the next point release. Thanks @mmashwani!

**Comment by rvkasper** [comment]
Thanks all involved!
