### ISSUE TITLE
[Bug] logging not working properly?

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#1120]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

Log ends after Initialization

but there is an msi install

![unnamed](https://github.com/user-attachments/assets/7390572b-6055-49f2-a58e-a03a8901689e)

Write-ADTLogEntry -Message "Installation started" doesnt work. How to add custom log entries from Extension or Invoke-AppDeployToolkit?

### Steps to reproduce

1. Put an msi install, 
2. run installation
3. check the log

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile

.NET SDK:
 Version:           8.0.404
 Commit:            7b190310f2
 Workload version:  8.0.400-manifests.c6df56b6
 MSBuild version:   17.11.9+a69bbaaf5

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.404\
```

**Comment by cyborgrd** [comment]
Bug,  still present on 4.0.3

![image](https://github.com/user-attachments/assets/d169e5fa-2b66-42d6-ab6e-ab8274dc1bce)

**Comment by mjr4077au** [comment]
@cyborgrd is this a new log file, or a continuance of the broken log file?

**Comment by cyborgrd** [comment]
Its a new

**Comment by mjr4077au** [comment]
Can I please confirm your time zone so I can try and replicate your environment? Could you also provide a log file where this issue is exhibited?

**Comment by cyborgrd** [comment]
[Testvendor_Testapp_1.0.0.0_x64_EN_01_PSAppDeployToolkit_Install.log](https://github.com/user-attachments/files/18092311/Testvendor_Testapp_1.0.0.0_x64_EN_01_PSAppDeployToolkit_Install.log)

**Comment by mjr4077au** [comment]
The output looks good to me. Is it just not working in CMTrace?

![image](https://github.com/user-attachments/assets/b47e584a-c97c-45ce-9938-842061efe5b4)

**Comment by mjr4077au** [comment]
@cyborgrd can you please review the discussion in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1154 and download the latest ConfigMgr evaluation ISO, then test with the CMTrace.exe it comes with? I believe it has some fix for your locale as you and the OP of the other issue are both `de-DE` from the looks of it.

**Comment by cyborgrd** [comment]
Thx, that works now. The Problem was outdated CMTrace

**Comment by cyborgrd** [comment]
Can somebody explain how to change the logname? Now is it like

Testvendor_Testapp_1.0.0.0_x64_EN_01_**PSAppDeployToolkit**_Install.log

I Want to change to something like that

Testvendor_Testapp_1.0.0.0_x64_EN_01_**11-12-2024**_Install.log

**Comment by mjr4077au** [comment]
> Thx, that works now. The Problem was outdated CMTrace

Closing as per the notes mentioned here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1154#issuecomment-2537685138


> Can somebody explain how to change the logname? Now is it like
> 
> Testvendor_Testapp_1.0.0.0_x64_EN_01_**PSAppDeployToolkit**_Install.log
> 
> I Want to change to something like that
> 
> Testvendor_Testapp_1.0.0.0_x64_EN_01_**11-12-2024**_Install.log

See: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1159#issuecomment-2537615017
