### ISSUE TITLE
[Bug] Software Center takes ages to give an installed status when using PSADT 4.0

### ISSUE THREAD

**Issue by AnknUH** [PSAppDeployToolkit/PSAppDeployToolkit#1121]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

![image](https://github.com/user-attachments/assets/db181921-e0ab-4450-b13c-164543620ffb)
After installation of software, it takes several minutes to get from the status above to the status below in Software Center.
![image](https://github.com/user-attachments/assets/882b14a0-9e2e-42e6-91b0-1fbf12fd5406)
FYI: the (un)installation has succeeded

### Steps to reproduce

1. Deploy software application as available to workstation
2. install software

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : nl-BE
TimeZone             : (UTC+01:00) Brussels, Copenhagen, Madrid, Paris
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop


Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by mjr4077au** [comment]
Thanks for the report! Is there any further information you could possibly provide? What would be good to know is:

* What the log looks like and how long it took from start to finish
* Whether once finished the PowerShell process closed out and terminated as one would expect
* Whether you were using `Invoke-AppDeployToolkit.exe` or PowerShell directly.

**Comment by AnknUH** [comment]
Good morning!

Thanks for the lightning fast reply :-).  The issue has been resolved.  We are testing on Virtual machines and they tend to show this behaviour from time to time.

BTW: Great job on the new release.  Much appreciated!

Kind regards,

Andy
