### ISSUE TITLE
[Bug] The property 'Fluent' cannot be found on this object. Verify that the property exists.

### ISSUE THREAD

**Issue by HermanGB** [PSAppDeployToolkit/PSAppDeployToolkit#1122]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

Unable to run PSADT v4 on Sandbox or any other platform. (Hyper-V, Sandbox and Computer)
Running from CMD, PowerShell or simply right click and run as administrator on Invoke-AppDeployToolkit.exe

Error: The property 'Fluent' cannot be found on this object. Verify that the property exists.

### Steps to reproduce

On any machine Hyper-V, Computer or Sandbox.
Open Powershell as administrator:

Set-ExecutionPolicy Bypass -Force
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-Module -Name PSAppDeployToolkit -Force -Confirm:$False
New-ADTTemplate -Destination C:\PSADT
& "C:\PSADT\PSAppDeployToolkit_4.0.2\Invoke-AppDeployToolkit.exe"

![Screenshot 2024-12-06 120812](https://github.com/user-attachments/assets/e314dd0b-4ec2-4ae1-964f-a68b2e5bcac1)
![Screenshot 2024-12-06 120740](https://github.com/user-attachments/assets/0e7f2ab1-3363-4995-97b6-cf47ede45777)
[PSAppDeployToolkit_4.0.2_EN_01_PSAppDeployToolkit_Install.log](https://github.com/user-attachments/files/18037316/PSAppDeployToolkit_4.0.2_EN_01_PSAppDeployToolkit_Install.log)

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB, nb-NO}
KeyboardLayout       : en-US
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:270
+ ... 'HyperVisorPresent','CsPartOfDomain','CsPCSystemType'); dotnet --info
+                                                             ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by mjr4077au** [comment]
Can I confirm what language you're running the toolkit in?

**Comment by HermanGB** [comment]
![image](https://github.com/user-attachments/assets/0bb7cad9-9b72-4faa-8596-74d859d6e44f)
Is this enough information? This is a 100% clean Sandbox.

**Comment by mjr4077au** [comment]
I just committed the missing Norwegian strings that will resolve this issue, not sure how they got missed sorry!

Could I kindly ask you to review the commit for this and tell me whether these AI translations make sense, and if not, what the correct text should be? https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/5410861778e54aa09693ce99a25745aaff7e7b54

**Comment by HermanGB** [comment]
Had a quick look and the translate seems to be OK.

**Comment by mjr4077au** [comment]
Thank you! I'll close this as resolved, the amendments will make it into the next point release which is due out soon.

When this action has finished running, you'll be able to download a pre-release ZIP of the module should you wish to try it out before the next point release: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/12198276119
