### ISSUE TITLE
[Bug] Progressbar shown when using Noninteractivemode

### ISSUE THREAD

**Issue by Nilsvw312** [PSAppDeployToolkit/PSAppDeployToolkit#1123]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

When using PSADT 4.0 with the command .\Invoke-AppDeployToolkit.ps1 -DeploymentType install -DeployMode NonInteractive
I still get a progressbar while i would expect to see nothing.

When the same idea for 3.x i don't see any screen popping up.

### Steps to reproduce

1. .\Invoke-AppDeployToolkit.ps1 -DeploymentType install -DeployMode NonInteractive
2. see progressbar
![progressbar](https://github.com/user-attachments/assets/36d5b1ec-3724-46bf-8ba5-40d01dc7dd9e)

3.

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE, fr-FR, it-IT...}
KeyboardLayout       : en-US
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile


global.json file:
  Not found

Host:
  Version:      6.0.36
  Architecture: x64
  Commit:       f1dd57165b

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by mjr4077au** [comment]
The old code used to set `$deployModeSilent` to `$true` when running as NonInteractive, which wasn't exactly correct.

Can I confirm why you'd be running as NonInteractive if you didn't want to see anything? It sounds like you'd want Silent?

**Comment by Nilsvw312** [comment]
Ah you are right. I always used the noniteractive, but silent works as expected for 4.0.2.

**Comment by mjr4077au** [comment]
I'll close this one for now assuming just using Silent achieves what you're after. If there's any further issue, please re-open this issue or create a new one 🤜🤛

**Comment by DanGough** [comment]
Non-Interactive description from v3 documentation:

https://psappdeploytoolkit.com/docs/3.10.2/usage/how-to-deploy
