### ISSUE TITLE
[Bug] [Uninstall] [Start-ADTMsiProcess] [Error] :: Cannot convert value "" to type "System.IO.FileInfo". Error: "The path is not of a legal form."

### ISSUE THREAD

**Issue by Nilsvw312** [PSAppDeployToolkit/PSAppDeployToolkit#1124]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

When running the script to remove a MSI app and the MSI code is not found the script is throwing an error message:
[Start-ADTMsiProcess] [Error] :: Cannot convert value "" to type "System.IO.FileInfo". Error: "The path is not of a legal form."

When the MSI code is found no issue is there.

### Steps to reproduce

1. Try to remove a MSI app based on productcode where the exact MSI code is not present on the system with command:     
Start-ADTMsiProcess -Action 'Uninstall' -ProductCode '{2270A09C-AF5A-4F19-BAF2-4DDC70C80F7B}'
2. It throws an error message: "[2024-12-06 12:50:14.525] [Uninstall] [Start-ADTMsiProcess] [Error] :: Cannot convert value "" to type "System.IO.FileInfo". Error: "The path is not of a legal form."
Error Record:
-------------

Message               : Cannot convert value "" to type "System.IO.FileInfo". Error: "The path is not of a legal form."
InnerException        : System.Management.Automation.PSInvalidCastException: Cannot convert value "" to type "System.IO.FileInfo". Error: "The path is not of a legal form." ---> System.ArgumentException: The path is not of a legal form."
3. I would expect to see something just in the logs like "MSI application is not present"

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE, fr-FR, it-IT...}
KeyboardLayout       : en-US
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile


global.json file:
  Not found

Host:
  Version:      6.0.36
  Architecture: x64
  Commit:       f1dd57165b

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by mjr4077au** [comment]
This has already been addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/0953e85a7ca0370845a15cad802a4a9da573dbb9, which will make it into our next point release due out hopefully today 😊

**Comment by Nilsvw312** [comment]
Great! coultn find the same issue when i used search.
