### ISSUE TITLE
[Bug] Translate in French on install is not good

### ISSUE THREAD

**Issue by Guiradn** [PSAppDeployToolkit/PSAppDeployToolkit#1126]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

Hi everyone, in this \Strings\fr\strings.psd1 there is a grammatical error in the sentence in the code snippet Progress in MessageInstallDetail = "Cette fenêtre se fermera automatiquement lorsque la **dés**installation sera terminée."

This is the correction : MessageInstallDetail = "Cette fenêtre se fermera automatiquement lorsque l'installation sera terminée."

### Steps to reproduce

1.
2.
3.

### Environment data

```console
OsName               : Microsoft Windows 10 Professionnel
OsOperatingSystemSKU : 48
OsArchitecture       : 64 bits
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : fr-FR
OsMuiLanguages       : {fr-FR}
KeyboardLayout       : fr-FR
TimeZone             : (UTC+01:00) Bruxelles, Copenhague, Madrid, Paris
HyperVisorPresent    : False
CsPartOfDomain       : True
CsPCSystemType       : Mobile
```

**Comment by mjr4077au** [comment]
Thanks, @Guiradn! Is this the only bad translation you could see within the strings file? These were AI-generated, so it was expected they'd be a bit average.

**Comment by mjr4077au** [comment]
I'll close this for now assuming the other translations are sufficiently good. If anything else requires revision, please raise a new issue.
