### ISSUE TITLE
[Bug] Documentation error for New-ADTTemplate

### ISSUE THREAD

**Issue by Dirk-Manderin** [PSAppDeployToolkit/PSAppDeployToolkit#1127]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.2

### Describe the bug

The examples in the documentation for the [New-ADTTemplate](https://psappdeploytoolkit.com/docs/reference/functions/New-ADTTemplate) command are incorrect.  They include the -Path parameter, which should be -Destination in 4.0.2.

### Steps to reproduce

1.
2.
3.

### Environment data

```console
N/A
```

**Comment by mjr4077au** [comment]
Thanks for the report! This has been amended in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/135df6a2f00a28b7b7a23eb1278d13db76a2a709, and will be in the next point release.
