### ISSUE TITLE
[Bug] Cannot add type. The type name 'Api.Kernel32' already exists.

### ISSUE THREAD

**Issue by manyomc** [PSAppDeployToolkit/PSAppDeployToolkit#1130]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2

### Describe the bug

While testing, if you leave a PowerShell window open and run multiple passes, you get the following error. As a result, you have to close and reopen PowerShell.

Cannot add type. The type name 'Api.Kernel32' already exists.
At AppDeployToolkit\AppDeployToolkitMain.ps1:17213 char:5

### Steps to reproduce

1. Run the deploy-application.ps1 successfully.
2. In the same PowerShell window, try running it again.
3. Notice error

### Environment data

```console
see last issue, i just input this earlier this week
```

**Comment by mjr4077au** [comment]
Generally speaking, it's recommended for 3.x that everything be done in a fresh PowerShell window every time. Please also note that PSAppDeployToolkit 4.0 has now been released and at this time, there's no intention for further changes to the older 3.x codebase unless extenuating circumstances prevail.
