### ISSUE TITLE
[Bug] Error when updating help for PSAppDeployToolkit module

### ISSUE THREAD

**Issue by nclinch** [PSAppDeployToolkit/PSAppDeployToolkit#1141]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

Error when updating help for PSAppDeployToolkit module

PS Microsoft.PowerShell.Core\FileSystem::\\ntz19afs-cs01\vol2\dept\it\PowerShell> update-help
update-help : Failed to update Help for the module(s) 'PSAppDeployToolkit' with UI culture(s) {en-US} : The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored. The HelpInfoUri 
'https://psappdeploytoolkit.com/docs' does not resolve to a container.
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : InvalidHelpInfoUri,Microsoft.PowerShell.Commands.UpdateHelpCommand

### Steps to reproduce

1. Install-module PSAppDeployToolkit 
2. update-help PSAppDeployToolkit
3.

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-06:00) Central Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile
.NET SDK:
 Version:           9.0.101
 Commit:            eedb237549
 Workload version:  9.0.100-manifests.3068a692
 MSBuild version:   17.12.12+1cce77968

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.101\

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  9.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by mjr4077au** [comment]
This is somewhat addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/2d6848335258d87429612445594fe7befcf247ac, which will be in the next point release. At this stage, we don't provide updatable help like this as the help is intrinsically tied to the module version.

To get current help for the module, you have three choices:
* Simply use `Get-Help` from PowerShell, such as `Get-Help Open-ADTSession`.
* Call `Show-ADTHelpConsole` once the module's imported. This will give you a graphical representation of PowerShell's `Get-Help` output.
* Visit our website for function help, where you can see help for 3.x, as well as 4.x and all point releases: https://psappdeploytoolkit.com/docs/category/functions.
