### ISSUE TITLE
[Bug] Failed to manage archive file [Archive.zip]: The file 'C:\Archive.zip' already exists

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#1144]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

When CompressLogs is enabled in config.psd1, the following error occurs every time PSADT runs.

![image](https://github.com/user-attachments/assets/bb2b34b2-26e5-447f-8528-202642216eae)

Please ensure the zip file gets overwritten instead or a new file with a different name is created.

### Steps to reproduce

1. Enabel CompressLogs in config.psd1
2. Run the same install script at least twice

### Environment data

```console
Windows 11 24H2
```

**Comment by mjr4077au** [comment]
Thanks for the report @JonathanPitre! This was a badly escaped formattable string in the C# side that I've patched up in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/80a6d6458b644d32c7b9215f01d30597e4e761a6.

When [this action](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/12248292855) completes, do you mind downloading the artifact and confirming it's working as expected on your side?

**Comment by mjr4077au** [comment]
Given we've been chatting about other issues and the simple nature of this fix, I'm going to close this assuming its good but if there's further issues, please open the issue again or raise a new one 🤜🤛
