### ISSUE TITLE
[Bug] Invoke-ADTSCCMTask -ScheduleId 'HardwareInventory' - Error Record: MethodNotFound

### ISSUE THREAD

**Issue by 2mmyU** [PSAppDeployToolkit/PSAppDeployToolkit#1146]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

Invoke-ADTSCCMTask -ScheduleId 'HardwareInventory' fails with 'MethodNotFound'

Complete error:

`[Post-Install] :: Failed to trigger SCCM Schedule Task ID [{00000000-0000-0000-0000-000000000001}].
Error Record:
-------------
 
Message               : Method invocation failed because [Microsoft.Management.Infrastructure.CimInstance] does not contain a method named 'TriggerSchedule'.
                        
FullyQualifiedErrorId : MethodNotFound,Invoke-ADTSCCMTask
ScriptStackTrace      : at Invoke-ADTSCCMTask<Process>, D:\psadtv4.0.3\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 10922
                        at Trigger-HardwareInventory, D:\psadtv4.0.3\Invoke-AppDeployToolkit.ps1: line 786
                        at Install-ADTDeployment, D:\psadtv4.0.3\Invoke-AppDeployToolkit.ps1: line 1056
                        at <ScriptBlock>, D:\psadtv4.0.3\Invoke-AppDeployToolkit.ps1: line 1201
                        
PositionMessage       : At D:\psadtv4.0.3\Invoke-AppDeployToolkit.ps1:786 char:4
                        +             Invoke-ADTSCCMTask -ScheduleID 'HardwareInventory'
                        +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	Invoke-ADTSCCMTask	10.12.2024 08:22:26	10956 (0x2ACC)`**

### Steps to reproduce

1. Invoke-ADTSCCMTask -ScheduleId 'HardwareInventory'

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-biters
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : nb-NO
OsMuiLanguages       : {nb-NO}
KeyboardLayout       : nb-NO
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Oslo, Roma, Wien
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile


Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by mjr4077au** [comment]
This should be addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/f83479dffb709530e1038d6bb238a8f22cecc484, but I don't have access to a ConfigMgr environment to test it.

In ~10 minutes, a pre-release copy of the module will be available here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/12255367030. Do you mind testing and reporting your feedback?

**Comment by 2mmyU** [comment]
New error with the new pre-release module:

[Post-Install] :: Failed to trigger SCCM Schedule Task ID [{00000000-0000-0000-0000-000000000001}].
Error Record:
-------------
 
Message               : Cannot bind parameter 'Arguments'. Cannot convert the "{00000000-0000-0000-0000-000000000001}" value of type "System.String" to type "System.Collections.IDictionary".
InnerException        : System.Management.Automation.PSInvalidCastException: Cannot convert the "{00000000-0000-0000-0000-000000000001}" value of type "System.String" to type "System.Collections.IDictionary".
                           ved System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                           ved System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           ved System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           ved System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                           ved System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
                        
FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Invoke-ADTSCCMTask
ScriptStackTrace      : at Invoke-ADTSCCMTask<Process>, D:\PSADTv403\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 11078
                        at Trigger-HardwareInventory, D:\PSADTv403\Invoke-AppDeployToolkit.ps1: line 786
                        at Install-ADTDeployment, D:\PSADTv403\Invoke-AppDeployToolkit.ps1: line 1057
                        at <ScriptBlock>, D:\PSADTv403\Invoke-AppDeployToolkit.ps1: line 1218
                        
PositionMessage       : At D:\PSADTv403\Invoke-AppDeployToolkit.ps1:786 char:4
                        +             Invoke-ADTSCCMTask -ScheduleID 'HardwareInventory'
                        +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 
Error Inner Exception(s):
-------------------------
 
Message : Cannot convert the "{00000000-0000-0000-0000-000000000001}" value of type "System.String" to type "System.Collections.IDictionary".

**Comment by 2mmyU** [comment]
New error with the pre-release module:

```
[Post-Install] :: Failed to trigger SCCM Schedule Task ID [{00000000-0000-0000-0000-000000000001}].
Error Record:
-------------
 
Message               : Cannot bind parameter 'Arguments'. Cannot convert the "{00000000-0000-0000-0000-000000000001}" value of type "System.String" to type "System.Collections.IDictionary".
InnerException        : System.Management.Automation.PSInvalidCastException: Cannot convert the "{00000000-0000-0000-0000-000000000001}" value of type "System.String" to type "System.Collections.IDictionary".
                           ved System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                           ved System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           ved System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           ved System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                           ved System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
                        
FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Invoke-ADTSCCMTask
ScriptStackTrace      : at Invoke-ADTSCCMTask<Process>, D:\PSADTv403\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 11078
                        at Trigger-HardwareInventory, D:\PSADTv403\Invoke-AppDeployToolkit.ps1: line 786
                        at Install-ADTDeployment, D:\PSADTv403\Invoke-AppDeployToolkit.ps1: line 1057
                        at <ScriptBlock>, D:\PSADTv403\Invoke-AppDeployToolkit.ps1: line 1218
                        
PositionMessage       : At D:\PSADTv403\Invoke-AppDeployToolkit.ps1:786 char:4
                        +             Invoke-ADTSCCMTask -ScheduleID 'HardwareInventory'
                        +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 
Error Inner Exception(s):
-------------------------
 
Message : Cannot convert the "{00000000-0000-0000-0000-000000000001}" value of type "System.String" to type "System.Collections.IDictionary".
```

**Comment by mjr4077au** [comment]
@2mmyU I've fixed the bad `-Arguments` setups I had in place for `Invoke-CimMethod` in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/5987c49d95f7f58be7152f988ec997a85a2d6a05. Can you please test off this artifact once it's built? https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/12266690487

If it's all good, this fix will be in the next point release.

**Comment by 2mmyU** [comment]
Hi Mitch
As far as I can tell, it is now working:
![image](https://github.com/user-attachments/assets/4bee107f-62db-4bc7-b11c-3210549b516f)

Thanks for the quick feedback and fix - keep up the good work you guys are doing!

/Tommy

**Comment by mjr4077au** [comment]
Thank you very much!
