### ISSUE TITLE
[Feature] Allow altering the ADT config dynamically

### ISSUE THREAD

**Issue by neo42JBR** [PSAppDeployToolkit/PSAppDeployToolkit#1147]
### Summary of the new feature / enhancement

We will be developing an extension for the v4. This will include a lot of new functions but also help us transition from v3 to v4.

Due to the transition mentioned above we want to update the ADT config object dynamically after initialization, because of to the restricted language mode of psd1 we cannot do this in the settings file. Especially the `Assets` section is of interestest so we can point it to different locations if they exist.

### Proposed technical implementation details (optional)

Maybe add a Set-/Update- ADTConfig function that acts as a setter function for the ADT sections.

**Comment by mjr4077au** [comment]
You can simply call `Get-ADTConfig` and modify its output as objects always reference types in C# (and therefore PowerShell). For instance, this will change the RequireAdmin option:
```PowerShell
$adtConfig = Get-ADTConfig
$adtConfig.Toolkit.RequireAdmin = $false
```

**Comment by neo42JBR** [comment]
Thanks!

**Comment by mjr4077au** [comment]
@neo42JBR just regarding your specific desire to change out the assets after initialisation, are you referring to the classic or fluent assets? For the classic dialogs, we read the contents of the assets into RAM so we minimise disposal issues. This means that a change in path for the icon/banner won't reflect if you simply change the path.
