### ISSUE TITLE
[Bug] Set-ADTActiveSetup - Error on $StubExeExt variable that is not path of function

### ISSUE THREAD

**Issue by MantaRay777** [PSAppDeployToolkit/PSAppDeployToolkit#1148]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

[Install] [Set-ADTActiveSetup] [Error] :: Failed to set Active Setup registry entry.
Error Record:

Message               : The variable '$StubExeExt' cannot be retrieved because it has not been set.

### Steps to reproduce

1. Set active setup with Set-ADTActiveSetup

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC+02:00) Harare, Pretoria
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
Thanks for your report! This issue has been addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/f20a5adb8411874bf22148f86fb4b6c4b22fb5ab, and will be in the next point release.
