### ISSUE TITLE
[Bug]  Copy-ADTFile -Path "$($adtSession.DirFiles)\*" -Destination $destination -Force throws error 60001

### ISSUE THREAD

**Issue by Nilsvw312** [PSAppDeployToolkit/PSAppDeployToolkit#1149]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

When using the -Force command with Copy-ADTFile it shows an error message 60001.
Without -Force it works fine.
Regarding Show-adthelpconsole the command should be available:

    -------------------------- EXAMPLE 3 --------------------------

    PS C:\>Copy-ADTFile -Path 'C:\Path\file.txt' -Destination 'D:\Destination\file.txt' -Force

    Copies the file 'file.txt' from 'C:\Path' to 'D:\Destination', overwriting the destination file if it exists.

Exact command used:
 Copy-ADTFile -Path "$($adtSession.DirFiles)\*" -Destination $destination -Force

I guess would also be helpfull if the part $adtSession.DirFiles would be in the help file for copy-adtfile. Found the variable in another bug ;), but al already saw some updates are coming regarding the docs.

### Steps to reproduce

1. Copy any file/folder from the Files folder with command  Copy-ADTFile -Path "$($adtSession.DirFiles)\*" -Destination $destination -Force

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE, fr-FR, it-IT...}
KeyboardLayout       : en-US
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile


global.json file:
  Not found

Host:
  Version:      6.0.36
  Architecture: x64
  Commit:       f1dd57165b

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by mjr4077au** [comment]
Thanks for the report! I've fixed the bad example showing `-Force` and added an example including `"$($adtSession.DirFiles)"` as excellently suggested in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/2d3dadf4dcb0286acbe520a8020a16134baed44c. These changes will be in the next point release.
