### ISSUE TITLE
Issue - multiple balloon tips orphaned in the system tray

### ISSUE THREAD

**Issue by LMCO-psadt-devs** [PSAppDeployToolkit/PSAppDeployToolkit#115]
After multiple defers in testing I see multiple balloon tips orphaned in system tray...

![systray](https://cloud.githubusercontent.com/assets/15805201/11155790/14072418-8a05-11e5-9e80-8bf58409b8ac.PNG)

**Comment by mmashwani** [comment]
With what version of the toolkit? How are you executing the script multiple times (i.e., are you executing it multiple times from the same PowerShell window?).

**Comment by LMCO-psadt-devs** [comment]
3.6.7...  I am using the deploy-application.exe as administrator and hitting defer.  It is easier to see if you fully expand all system tray icons.

**Comment by amotaz** [comment]
Possibly unrelated question, are you setting the maximum number of deferrals higher than three?

**Comment by LMCO-psadt-devs** [comment]
Nope deferrals is 3...

**Comment by Morkitux** [comment]
Hi,
I meet same issue with same version and no customisation:
>[11-23-2015 14:29:37.757] [Initialization] [PSAppDeployToolkit] :: [PSAppDeployToolkit_TestScript_1.0_EN_01] script version is [3.6.5]
[11-23-2015 14:29:37.777] [Initialization] [PSAppDeployToolkit] :: [Deploy Application] script version is [3.6.5]
[11-23-2015 14:29:37.782] [Initialization] [PSAppDeployToolkit] :: [App Deploy Toolkit Main] script version is [3.6.7]
[11-23-2015 14:29:37.795] [Initialization] [PSAppDeployToolkit] :: [App Deploy Toolkit Extensions] version is [1.5.0]

**Comment by amotaz** [comment]
Just to clarify LMCO, are you executing multiple times from the ISE? multiple times from a single Powershell window? or just doubleclicking deploy-application multiple times?

**Comment by LMCO-psadt-devs** [comment]
Double clicking deploy-application multiple times when picking defer. I can try some other test cases

**Comment by mmashwani** [comment]
Maybe this is a problem during testing when you keep executing the toolkit...but is it really an issue that crops up during a live deployment? If not, then I don't think it makes much sense to pursue this issue much further.

**Comment by LMCO-psadt-devs** [comment]
Muhammad - thanks I will try on my next Firefox package/application :>

As an aside - I call the Deploy-Application.ps1 directly when making deployments/programs in CM12. Is this preferred over the Deploy-Application.exe for any reason in your opinion?

**Comment by mmashwani** [comment]
The only reason to use Deploy-Application.exe is if you do not want the user to see the PowerShell CMD window that flashes for a moment when you execute a script.
