### ISSUE TITLE
[Bug] Impossible to add new parameters to $adtSession

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#1150]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

Certain apps will require new parameters to be added to $adtSession. I've tried adding 'AppRing' for OneDrive install and I get the following error when I run the installation script.

![image](https://github.com/user-attachments/assets/4aad8198-4bd7-48bd-a446-e8f3185e5ad2)
![image](https://github.com/user-attachments/assets/074a8668-eb66-4816-bd79-65815e461d25)

For example, here's a list of parameters that I would like to add deploy OneDrive with Evergreen so it automatically download the latest binary.

```
$AppRing = "Production" # InternalFast, InternalSlow, Insider, Production or Enterprise
[string]$EvergreenUrl = "https://evergreen-api.stealthpuppy.com/app/$($adtSession.AppVendor)$($adtSession.AppName)"
[PSCustomObject]$EvergreenApp = (Invoke-RestMethod -Uri $EvergreenUrl -UseBasicParsing -UserAgent 'Googlebot/2.1 (+http://www.google.com/bot.html)')`
| Where-Object { $_.Ring -eq $($adtSession.AppRing) -and $_.Architecture -eq $($adtSession.AppArch) } | `
Sort-Object -Property @{ Expression = { [System.Version]$_.Version }; Descending = $true } | Select-Object -First 1
$AppVersion = $EvergreenApp.Version
$AppSetupUrl = $EvergreenApp.URI
$AppSetup = Split-Path -Path $AppSetupUrl -Leaf
$AppInstallParameters = "/allusers /silent" # https://learn.microsoft.com/en-us/sharepoint/per-machine-installation
$AppMachineInstall = $false
$DisableAppAutoUpdate = $true
$AutomaticCleanup = $true
$AppDestination = "${env:ProgramFiles}\$($adtSession.AppVendor) $($adtSession.AppName)"
[string]$DirSupportFiles = "$ScriptPath\SupportFiles\$($adtSession.AppName)\$($AppVersion)"
$IsAppInstalled = [boolean](Get-ADTApplication -Name "$($adtSession.AppVendor) $($adtSession.AppName)")
$AppInstalledVersion = (Get-ADTApplication -Name "$($adtSession.AppVendor) $($adtSession.AppName)").DisplayVersion
```

I am doing something wrong or adding new parameters is simply not possible at the moment ?

### Steps to reproduce

1. Add a new parameter to existing $adtSession hash table
2. Run installation script

### Environment data

```console
OsName               : Microsoft Windows 11 Business
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-08:00) Pacific Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
The `$adtSession` hashtable can't be extended because it's used to instantiate the DeploymentSession object, which it when becomes. This is a failing on my part as I did not think about the possibility of people trying to do this. 

I'll leave this open for now as I want to try something as a potential solution, I'll come back to this in ~6 hours.

**Comment by DanGough** [comment]
The session object is really just reserved for things that PSADT internals needs to know about the installation, like the app name, log path, etc.

For any additional variables like you mentioned, I would just define and use them as regular variables, as you would have done in the past with v3.

**Comment by mjr4077au** [comment]
> It would also be nice if we could add extra parameters. For example.
> 
> ```
> [boolean]$EnableUserInstall = $false # Force machine-wide install parameters
> [boolean]$DisableAppAutoUpdate = $true # Disable app auto update sercvice/schedule task/startup process
> [boolean]$EnableCleanup = $true # Deletes setup files after installation completes
> ```

What would you expect happen with these extra parameters, even if you could define them?

**Comment by mjr4077au** [comment]
Yeah, but take `$DisableAppAutoUpdate`, are you expecting we have some automagic for that, or are you just wanting a bool you can reference and so you can fire off your own logic?

**Comment by mjr4077au** [comment]
Alright that's the answer I wanted to hear. I'll come back on this soon.

**Comment by mjr4077au** [comment]
Thanks for the amazing feedback! 🤘. Check out https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/380dfc9e2e8c9c28cd060fceaeeb9b41af34fc4b, it'll be in the next point release.

In the below console output, note the `AppUpdateRing` member of the `$adtSession` class object.
```
C:\Users\mjr40\Repos\PSAppDeployToolkit\src>powershell.exe
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\mjr40\Repos\PSAppDeployToolkit\src> Import-Module .\PSAppDeployToolkit
PS C:\Users\mjr40\Repos\PSAppDeployToolkit\src> $adtSession = Open-ADTSession -SessionState $ExecutionContext.SessionState -PassThru -AppUpdateRing Production 6>$null
PS C:\Users\mjr40\Repos\PSAppDeployToolkit\src> $adtSession


AppUpdateRing               : Production
DeploymentType              : Install
DeploymentTypeName          : Installation
DeployMode                  : Interactive
AllowRebootPassThru         : False
TerminalServerMode          : False
DisableLogging              : False
AppVendor                   :
AppName                     : PSAppDeployToolkit
AppVersion                  : 4.0.3
AppArch                     :
AppLang                     : EN
AppRevision                 : 01
AppSuccessExitCodes         : {0}
AppRebootExitCodes          : {1641, 3010}
AppScriptVersion            :
AppScriptDate               :
AppScriptAuthor             :
InstallName                 : PSAppDeployToolkit_4.0.3_EN_01
InstallTitle                : PSAppDeployToolkit 4.0.3
DeployAppScriptFriendlyName :
DeployAppScriptVersion      :
DeployAppScriptParameters   :
InstallPhase                : Execution
CurrentDate                 : 11-12-2024
CurrentTime                 : 10:40:33
ScriptDirectory             : C:\Users\mjr40\Repos\PSAppDeployToolkit\src
DirFiles                    :
DirSupportFiles             :
DefaultMsiFile              :
DefaultMstFile              :
DefaultMspFiles             : {}
UseDefaultMsi               : False
LogTempFolder               : C:\Users\mjr40\AppData\Local\Temp\PSAppDeployToolkit_4.0.3_EN_01_Install
LogName                     : PSAppDeployToolkit_4.0.3_EN_01_PSAppDeployToolkit_Install.log
CurrentDateTime             : 11/12/2024 10:40:33 AM



PS C:\Users\mjr40\Repos\PSAppDeployToolkit\src>
```
