### ISSUE TITLE
[Bug] Patch My PC certificate is required in an AllSigned environment

### ISSUE THREAD

**Issue by NRMVPS** [PSAppDeployToolkit/PSAppDeployToolkit#1151]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

When attempting to run Invoke-AppDeployToolkit.ps1 in an environment with PowerShell's execution policy set to AllSigned PowerShell will hang waiting for user input. If deployed through MECM the installation will hang showing "installing" and eventually time out. 
Importing the certificate to the Local Computer\Trusted Publishers\Certificates store before installing resolves the issue.
![image](https://github.com/user-attachments/assets/c5fc75fa-6469-49ee-b3b6-51569f675dd2)

### Steps to reproduce

1.Run Invoke-AppDeployToolkit.ps1 on a computer with the PowerShell execution policy set to AllSigned
2.
3.

### Environment data

```console
OsName               : Microsoft Windows 11 Education
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : 121
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Education
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-06:00) Central Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
A copy of the module's public key has been added to the root of the module directory. You can manually side-load this into your device's Trusted Publishers store if required.

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/e1449cc1a2456afa16ad239c484ade54f12e7ed7
