### ISSUE TITLE
[Bug] setting DynamicProcessEvaluation to $false breaks Show-ADTWelcomePromptFluent

### ISSUE THREAD

**Issue by EdijsPerkums** [PSAppDeployToolkit/PSAppDeployToolkit#1155]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

Setting DynamicProcessEvaluation to $false causes Show-ADTWelcomePromptFluent to throw a NPE and crash.
![image](https://github.com/user-attachments/assets/2a76f8a8-b543-46cb-aec4-c75cadb3e0aa)
The processes also will be duplicated and have no icons. 
Pressing "Close Apps & Install" will crash the installation.
NPE happens in "\PSAppDeployToolkit\src\PSADT.UserInterface\PSADT.UserInterface\UserInterface\PSADT.UserInterface.WelcomeDialog.xaml.cs"
StartProcessEvaluationLoopAsync because _processEvaluationService is null.

### Steps to reproduce

1. Set DynamicProcessEvaluation to $false
2. Show-ADTInstallationWelcome -CloseProcesses notepad
3. Invoke-AppDeployToolkit.exe

### Environment data

```console
OsName               : Microsoft Windows 11 Pro
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:270
+ ... 'HyperVisorPresent','CsPartOfDomain','CsPCSystemType'); dotnet --info
+                                                             ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by mjr4077au** [comment]
Fixed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/adb50d07f94b0fd55323f717119639cef03a425e.
