### ISSUE TITLE
[Feature] PSADT 4.x.x Logfilename

### ISSUE THREAD

**Issue by RITSol** [PSAppDeployToolkit/PSAppDeployToolkit#1156]
### Summary of the new feature / enhancement

Hello,

request for a feature to change the logfilename for every session individually.

great

**Comment by mjr4077au** [comment]
Added in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/0c4ce3aa67e95200a446c5b5f007ca50d7ad994d, it'll be part of the next point release.

![image](https://github.com/user-attachments/assets/ba6a222e-47d0-4722-b0b9-fc807e1a3560)
