### ISSUE TITLE
[Feature] Add more flexibility to log files and folder customisation

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#1159]
### Summary of the new feature / enhancement

Hi ! First feature out of two regarding logging:

Since we can have more than one log file for a package deployment (e.g., MSI, InnoSetup, or other custom log files not depending on the PSADT script), we decided to use a dedicated folder per package, naming the folder after the package itself.

For example: a folder named "Software_1.2.3_x86_en_01" containing the log files.

Since we already include the package name in the folder, we simply name our log file "Package.log."

I wrote some custom code in the v3 template, and since I’d like to keep the v4 file signed with your Authenticode certificate, I believe this could be achieved quite easily with a few tweaks, as explained below:

### Proposed technical implementation details (optional)

    Add an option to override the log file name: If specified, this would set the log filename to the given value; otherwise, it would use the default value.
    Expose more internal variables for the LogPath expansion: Currently, we can specify $envXXX variables, but I don’t think it’s possible to access some $adtSession variables, such as $adtSession.InstallName.

Thanks !

**Comment by mjr4077au** [comment]
I've added this stuff and it'll be part of the next point release. You can configure whether logging goes to a subfolder via `config.psd1` (defaults to `$false` to match existing behaviour), and you can specify `LogName` as a parameter for `Open-ADTSession` where you can specify whatever name you want.

![image](https://github.com/user-attachments/assets/568050c3-ecc6-44e9-934a-6922e1822c55)

**Comment by mjr4077au** [comment]
Commits https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/76f531f1461d9029d8effa6e9253dbc3dd42c194 and https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/0c4ce3aa67e95200a446c5b5f007ca50d7ad994d for reference.

**Comment by cyborgrd** [comment]
I'm still not found out how to create a log like

Appvendor_Appname_Appversion_AppArch_AppLang_AppRevision_Date.log

When i try within $adtSession = @{

LogName = "$AppVendor + '_' ...... .log" the Variable $AppVendor is empty, even $adtSession.AppVendor is not working.


}

How i can use the Variables here?

**Comment by mjr4077au** [comment]
You can't reference a variable before it's defined... If you need to access something in $adtSession to define an $adtSession property, you'd do something like the below:
```PowerShell
##================================================
## MARK: Variables
##================================================

$adtSession = @{
    # App variables.
    AppVendor = ''
    AppName = ''
    AppVersion = ''
    AppArch = ''
    AppLang = 'EN'
    AppRevision = '01'
}
$adtSession.LogName = "$($adtSession.AppVendor)_$($adtSession.AppName)"
```

**Comment by cyborgrd** [comment]
I try following at this position

[string]$DeploymentTypeString = $DeploymentType.toString()
#$adtSession.LogName = "{0}_{1}_{2}_{3}_{4}_{5}_{6}_{7}.log" -f $adtSession.AppVendor, $adtSession.AppName, $adtSession.AppVersion, $adtSession.AppArch, $adtSession.AppLang, $adtSession.AppRevision, (Get-Date -Format 'dd-MM-yyyy'), $DeploymentTypeString
    	
But  $DeploymentType seem to be empty after 
$adtSession = @{
    # App variables.
    AppVendor = ''
    AppName = ''
    AppVersion = ''
    AppArch = ''
    AppLang = 'EN'
