### ISSUE TITLE
Ability to Defer Unlimited for SCCM Application Catalog deployments

### ISSUE THREAD

**Issue by mbeck007** [PSAppDeployToolkit/PSAppDeployToolkit#116]
I spent some time trying to figure out if there was a way to provide the user a defer button if applications are open that would interfere with an installation that they decided not to close at this time.  The only method I can see is -AllowDefer but that doesn't provide a Defer button.  Only way to see the button is by adding the -DeferTimes or -DeferDeadline parameters.  

If this ability does exist, please help me understand how to tweak the Show-InstallationWelcome function.  

Other than that - this is such an awesome toolkit.  With I knew about it years ago... 

Mitch

**Comment by amotaz** [comment]
Hello Mitch,
I believe you can do what you need by using the -AllowDeferCloseApps
Parameter for the Show-InstallationWelcome Function.
This parameter is on page 74 of the Admin guide you get when you download the toolkit. We don't currently support unlimited derferals, but you can use a large number for deferTimes to practically achieve this.

Let me know if that works for you
