### ISSUE TITLE
[Feature] Add the ability to maintain a "MasterLog" File with all the package operation result

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#1160]
### Summary of the new feature / enhancement

I suppose that in most companies, when something goes wrong with a package deployment, the package team is contacted.

This is not the case in my company. Most of the time, when a deployment encounters serious problems, a support team is called. 

- Among all the tasks they have to handle, there is one related to checking the package installation result. However, they have absolutely no idea (and no time) to debug a whole package log. All they want (and need) to know is: did the installation seem successful, or is there an error code and an error message?

This is why I had to customize the v3 version to maintain a master log file: I added a line to the master log file in the Exit-Script function, including the return code and a return message (either "Ok" or the error message).

A line in this file looks like this:
[timestamp] [PackageName] [Code] [Message]

Perhaps this feature request could interest someone else?

**Comment by mjr4077au** [comment]
I think you're better off just configuring your deployments to not continually append to the same log file, then asking them to read the end of the log file for success/failure.

![image](https://github.com/user-attachments/assets/b90922f2-971b-44b2-9ee1-fa1e1aa19c1c)

**Comment by mjr4077au** [comment]
Closing this one off due to no contact. If you believe the above isn't satisfactory, please create a new issue.
