### ISSUE TITLE
[Bug] Show-ADTInstallationProgress -WindowLocation Not Working

### ISSUE THREAD

**Issue by Get-SomeCofee** [PSAppDeployToolkit/PSAppDeployToolkit#1161]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

Specifying -WindowLocation does not move the window. 

### Steps to reproduce

`Show-ADTInstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'Top'`
or 'TopLeft', 'Top', 'TopRight', 'TopCenter', 'BottomLeft', 'Bottom', 'BottomRight'

### Environment data

```console
OsName               : Microsoft Windows 10 Education
OsOperatingSystemSKU : 121
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Education
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-06:00) Central Time (US & Canada)
HyperVisorPresent    : False
CsPartOfDomain       : True
CsPCSystemType       : Desktop


Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mjr4077au** [comment]
I've added a warning in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/3bfd1c7b249d1531f929e434aa8ca13be77531fd to indicate that the fluent progress dialog doesn't support relocation.
