### ISSUE TITLE
[Bug] Rearrange string table to that the fluent subtitle isn't obtusely under the WelcomePrompt table

### ISSUE THREAD

**Issue by PckgrTom** [PSAppDeployToolkit/PSAppDeployToolkit#1162]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

I might be misunderstanding this but the modifications don't seem to be reflecting on the PSADT popup windows. Example:

![image](https://github.com/user-attachments/assets/841c2df4-3c12-4083-845f-e258c0b1a5c5)

Still shows:

![image](https://github.com/user-attachments/assets/a147d48e-44c8-45db-8f6d-093ca259645f)

### Steps to reproduce

1. Modify the config file with customizations
2. Test running the exe
3. Standard settings still applied

### Environment data

```console
OsName               : Microsoft Windows 11 Pro
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-08:00) Pacific Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile
```

**Comment by mjr4077au** [comment]
That string can be modified here. We're in the process of performing a slight rearrangement of these strings to make it easier as it shouldn't be buried under the welcome prompt

![image](https://github.com/user-attachments/assets/cd2d82f9-1ff7-4e20-9d28-2fa1f107a229)

**Comment by mjr4077au** [comment]
This needs to stay open as we need the reminder to rearrange the strings table.

**Comment by mjr4077au** [comment]
This has been addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/d35b9663345389f3529c659dd0b731a3505315e1 and https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/b4778e8e02206b040e0b06d5cefd03802f7eae7f. These changes will make it into 4.1.0.

**Comment by mjr4077au** [comment]
> You already complained about my alleged laziness in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1367, but this was unfair. You know nothing about me. A simple documentation how such a string can be replaced, would be much more helpful than just blocking cases faster than someone can answer.

@alexhass the entire tone in #1367 wasn't good. You said "Not clear to me what is the right one. Can you share the string that changes this text with me, please?" and "An image showing what text is what Setting can be helpful in documentation.", whereas at least the OP in this issue had decent attempt himself at trying to get it done. The reality is, you could have easily searched the entire document for `PSAppDeployToolkit - ` and found the text you were trying to replace. You've got to be able to help yourself a little also.

> Still not clear to me what I should do here.

But you've provided the text from the strings.psd1 showing _exactly_ where you should edit it? This harks back to my previous reply about being able to help yourself a little also, which it seems like you've done.

![Image](https://github.com/user-attachments/assets/60e0548e-ddac-449e-8411-748e0c89b3b0)

> I guess I should not edit all translation files or is this what you tried to tell me?

If you've got multiple languages to support, regrettably yes, you'll need to edit each translation unit as required.

> Additionally after reviewing https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/b4778e8e02206b040e0b06d5cefd03802f7eae7f I can see that something goes wrong with your translatable strings, also in 4.1. with "Subtitle". Using a placeholder for "PSAppDeployToolkit" that can be globally replaced for all languages is highly recommended I think.

Agreed but its difficult to represent within the file as its not necessarily right that it's in the config either. It also makes it hard for when an integrator might want to put an absolute string in the translation file and expect it to be used. If it's formatted in the code with something out of the config and the strings.psd1 file, that's not as clear as just having it like we have it now.

> Splitting the strings in 3 strings is for sure correct as this is the only way to translate context sensitive. So you are on a good way.

Thank you. The previous setup was not great as that style of text stitching does not work properly for languages other than English. We love our international community and want to make sure their native languages are represented accurately and as best as possible.

> Are you looking for translators? I see a lot more issues...

Translations by way of PR are always welcome! I'll be honest with you, all of this stuff has been done via AI as I have no other way to get them done. I 100% knew they'd be garbage but it's hard when you don't have members on the team that can speak the languages we translate into.

**Comment by alexhass** [comment]
@mjr4077au I'm sorry, but this was not intentional bad tone. I'm not a native english speaker, this is the german way how we say things and I learned that English speakers may misunderstand it sometimes.

Before I opened the other case I also searched for the string and have not found it. This topic here was a random find and then I found the string in 4.0 based on your commit - I searched for "PSAppDeployToolkit" only and this gave simply tooo many results. I have not expected that this is inside the language files as the BallonText was in Config. So I searched for the same type of placeholder. :-(

I'm new to PSADT and I'm sorry if I may ask something without doing a full project code review. I but have 25 years expirience in software deployment via AD. I'm the creator of several popular MSI setups of projects like Notepad++, Adoptium/Eclipse Temurin, VSCodium, VSCode and others. I also translate Drupal to german for about 15+ years.

Honestly I'm not happy in customizing translatable strings in a project as it pushes me into serious troubles with every update. I hope you can find a placeholder solution for this string like the BallonText. In Drupal we use "named" placeholders what really helped translators a lot. I never done Powershell translation in my life so I have no answer on the best way...

I prefer to do a manual translation of PSADT for german. I create a new case for this. I hope you only use the AI translation on new strings later...

**Comment by mjr4077au** [comment]
@alexhass apologies for the late reply in coming back to you, replies can get lost on closed tickets when I've got too many pots on the boil.

I'll too apologise that I've misinterpreted your other bug reports. I should be more sympathetic to ESL folk as they represent a significant portion of our user base and community. I did genuinely think the string you were wanting changed was sufficiently easy to find though which is probably what rubbed me the wrong way.

I'll make a new bug report to track the centralisation of the overall product name as I can see benefits to it. Regarding the overall quality of the strings, PRs are absolutely welcome for new or improved translations 🤜🤛

**Comment by mjr4077au** [comment]
> So you are on a good way, but I would really replace "PSAppDeployToolkit" with a placeholder that can be set in config.psd1.

@alexhass just to circle back on this old, closed issue. The requested change has been added via https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/66a9400957bd93a9eb49fe46addf60f18da39f61 for 4.1.0. It will make life a lot easier.
