### ISSUE TITLE
[Bug] NitroPDF error when prompted to close & install application

### ISSUE THREAD

**Issue by jrollie** [PSAppDeployToolkit/PSAppDeployToolkit#1168]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

![image](https://github.com/user-attachments/assets/5c6d6f14-0bab-4b67-bfd9-084dcf8e61b5)

[PS-Nitro_14_EN_01_PSAppDeployToolkit_Install.log](https://github.com/user-attachments/files/18117973/PS-Nitro_14_EN_01_PSAppDeployToolkit_Install.log)

I have no issues running this deployment with the v3 Toolkit

I tested other deployments using v4 for other applications with no issues

### Steps to reproduce

1. Have NitroPDF.exe open
2. Run Invoke-AppDeployToolkit.exe that has -CloseProcesses 'NitroPDF' in Show-ADTInstallationWelcome
3. Select Close & Install in the GUI pop up. 

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 22H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-05:00) Eastern Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile
```

**Comment by mjr4077au** [comment]
Patched in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/c3884e1c28c10b45dd7d0a55365430baef17a288, it'll be part of the next point release. A pre-release build of the module can be downloaded from here in about 15 mins if you wish to test: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/12305810660

**Comment by jrollie** [comment]
Remove that line relieved the issue with that exception pop up but still not closing NitroPDF. This is also in the log file attached, I can open a separate Bug ticket if need.

[Pre-Installation] :: Failed to close window [Nitro PDF Pro] for process [NitroPDF].
Error Record:
-------------
Message               : Exception calling "BringWindowToFront" with "1" argument(s): "Failed to set window state. Error code: 0"
InnerException        : System.InvalidOperationException: Failed to set window state. Error code: 0
                           at PSADT.GUI.UiAutomation.BringWindowToFront(IntPtr windowHandle)
                           at CallSite.Target(Closure , CallSite , Type , Object )
FullyQualifiedErrorId : InvalidOperationException
ScriptStackTrace      : at Show-ADTInstallationWelcome<Process>, C:\Users\WDAGUtilityAccount\Desktop\TestTemplate\Nitro14_Converted\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 18122
                        at Install-ADTDeployment, C:\Users\WDAGUtilityAccount\Desktop\TestTemplate\Nitro14_Converted\Invoke-AppDeployToolkit.ps1: line 129
                        at <ScriptBlock>, C:\Users\WDAGUtilityAccount\Desktop\TestTemplate\Nitro14_Converted\Invoke-AppDeployToolkit.ps1: line 300
PositionMessage       : At C:\Users\WDAGUtilityAccount\Desktop\TestTemplate\Nitro14_Converted\PSAppDeployToolkit\PSAppDeployToolkit.psm1:18122 char:45
                        + ...             $null = [PSADT.GUI.UiAutomation]::BringWindowToFront($Ope ...
                        +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error Inner Exception(s):
-------------------------
Message : Failed to set window state. Error code: 0

**Comment by mjr4077au** [comment]
@jrollie I've reviewed our code for this and it's working well. Actually it's working better than before because it actually throws if it can't do it's job now whereas before it'd silently fail. Is it working for other apps and just not Nitro?

**Comment by jrollie** [comment]
This can be closed. Turns out that if Nitro is open with the "Make this your default PDF viewer" prompt open, PSADT is unable to close. If I close out of that window, everything works according. Don't see this being an issue as users will be actively using it in these instances. Sorry for the trouble and thank you for your time.

**Comment by DanGough** [comment]
@jrollie there may still be something to look at here if v3 was able to force close the process under such circumstances but v4 cannot. Please could you confirm if v3 was able to close the app regardless of which state it was in?

**Comment by jrollie** [comment]
Hey Dan,

I actually can confirm that v3 has similar behaviour if I have the "Default
App" window opened.

**Comment by jrollie** [comment]
@DanGough - Apologies. It does seem that only v4 is not working. I thought originally it was the "Default PDF Viewer" hanging the process but I am getting inconsistent results. Still seeing that error posted in the log file for the v4 deployment. v3 seems to be working fine.

**Comment by jrollie** [comment]
The culprit for this is the -PromptToSave switch, that was the difference between my Nitro deployments and others. If I add -PromptToSave the v4 toolkit will not close the applications.

**Comment by mjr4077au** [comment]
Looks like I'll need to install NitroPDF!

**Comment by jrollie** [comment]
@mjr4077au - Can be any application it appears. Anything that has the -PromptToSave switch for Show-ADTInstallationWelcome will break the deployment if the application is open.

**Comment by mjr4077au** [comment]
@jrollie I appreciate your patience and assistance diagnosing this one. This has been addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/ead29de98d9a83436e835a189666c4e799a8f7b7, you'll be able to test it in ~15 minutes when this [GitHub build action](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/12362985111) finishes.
