### ISSUE TITLE
[Feature] Export the command lookup table

### ISSUE THREAD

**Issue by neo42JBR** [PSAppDeployToolkit/PSAppDeployToolkit#1169]
### Summary of the new feature / enhancement

We want to make use of your prework defining a lookup table of commands in our extension module.
Would you be willing to export this table so that we can align the commands used and reduce loading time/ duplicate code?

### Proposed technical implementation details (optional)

Add 
`& $CommandTable.'Export-ModuleMember' -Variable 'CommandTable'`
and add it to the Manifest

**Comment by mjr4077au** [comment]
I don't like the idea of exporting the variable like that, but I could add a getter function if you like?

**Comment by neo42JBR** [comment]
I did not put a lot of thought into how this is exposed. Idk about the method of exposure. If you prefer a function that would be sufficient for us.

**Comment by mjr4077au** [comment]
This has been added in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/09940da187b841b4625a064f2252b9fe46a5475f.
