### ISSUE TITLE
$logDirectory is not set  ( Version 3.6.7 )

### ISSUE THREAD

**Issue by huvogt** [PSAppDeployToolkit/PSAppDeployToolkit#117]
AppDeployToolkitMain.ps1    does not have a section <<  ## Variable: LogFiles  >>  anymore

**Comment by amotaz** [comment]
Do a search for 

## Variables: Log Files

You can see where we define the log file information. 

You can change the log directory location in the config xml file.

**Comment by huvogt** [comment]
I fix the Problem for myself:



The point is that:

In the section  # Variables: Log

The If Condition missing a ELSE Condition

If ($configToolkitCompressLogs) {
        #  If the temp log folder already exists from a previous ZIP operation, then delete all files in it to avoid issues
        If (Test-Path -LiteralPath $logTempFolder -PathType 'Container' -ErrorAction 'SilentlyContinue') {
               $null = Remove-Item -LiteralPath $logTempFolder -Recurse -Force -ErrorAction 'SilentlyContinue'
        }
}

NEW inserted:

Else {
      ## Path to log directory defined in AppDeploy XML config file
      [string]$logDirectory = $configToolkitLogDir
}


regards


Von: amotaz [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. Dezember 2015 18:51
An: PSAppDeployToolkit/PSAppDeployToolkit <PSAppDeployToolkit@noreply.github.com>
Cc: Vogt Hansueli <hansueli.vogt@mobi.ch>
Betreff: Re: [PSAppDeployToolkit] $logDirectory is not set ( Version 3.6.7 ) (#117)


Do a search for

Variables: Log Files

You can see where we define the log file information.

You can change the log directory location in the config xml file.

—
Reply to this email directly or view it on GitHub<https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/117#issuecomment-168227603>.

In der elektronischen Korrespondenz kann die im Schriftverkehr übliche Vertraulichkeit nicht gewährleistet werden. Bitte überprüfen Sie daher sorgfältig, welche Mitteilungen und Beilagen Sie per E-Mail senden und erhalten möchten. Falls Sie dieses E-Mail irrtümlicherweise erhalten haben, bitten wir Sie, die absendende Person zu kontaktieren und dieses E-Mail mit allen Anhängen von Ihrem System zu löschen.

Avec la communication par courrier électronique, la confidentialité des informations n'est pas garantie comme elle l'est usuellement dans la correspondance écrite. Veuillez donc être vigilant lorsque vous envoyez ou recevez des communications et pièces jointes par courriel. Si vous avez reçu ce courriel par erreur, nous vous prions de contacter l'expéditeur/trice et de l'effacer avec toutes les pièces jointes de votre système.

**Comment by mmashwani** [comment]
I don't see what you fixed. What is ```$logDirectory```? That is just a variable that you made up. We don't use it in the toolkit.

If you look at the parameter definitions for Write-Log function, you see this definition:
```[string]$LogFileDirectory = $(If ($configToolkitCompressLogs) { $logTempFolder } Else { $configToolkitLogDir })```

**Comment by huvogt** [comment]
PsADT Dok:  PSAppDeploymentToolkitAdminGuide.docx

7 Toolkit Variables
Page 36:

$logDirectory

Path to log directory defined in XML config file





Von: Muhammad Mashwani [mailto:notifications@github.com]
Gesendet: Montag, 11. Januar 2016 16:00
An: PSAppDeployToolkit/PSAppDeployToolkit <PSAppDeployToolkit@noreply.github.com>
Cc: Vogt Hansueli <hansueli.vogt@mobi.ch>
Betreff: Re: [PSAppDeployToolkit] $logDirectory is not set ( Version 3.6.7 ) (#117)


I don't see what you fixed. What is $logDirectory? That is just a variable that you made up. We don't use it in the toolkit.

If you look at the parameter definitions for Write-Log function, you see this definition:
[string]$LogFileDirectory = $(If ($configToolkitCompressLogs) { $logTempFolder } Else { $configToolkitLogDir })

—
Reply to this email directly or view it on GitHub<https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/117#issuecomment-170579508>.

In der elektronischen Korrespondenz kann die im Schriftverkehr übliche Vertraulichkeit nicht gewährleistet werden. Bitte überprüfen Sie daher sorgfältig, welche Mitteilungen und Beilagen Sie per E-Mail senden und erhalten möchten. Falls Sie dieses E-Mail irrtümlicherweise erhalten haben, bitten wir Sie, die absendende Person zu kontaktieren und dieses E-Mail mit allen Anhängen von Ihrem System zu löschen.

Avec la communication par courrier électronique, la confidentialité des informations n'est pas garantie comme elle l'est usuellement dans la correspondance écrite. Veuillez donc être vigilant lorsque vous envoyez ou recevez des communications et pièces jointes par courriel. Si vous avez reçu ce courriel par erreur, nous vous prions de contacter l'expéditeur/trice et de l'effacer avec toutes les pièces jointes de votre système.

**Comment by mmashwani** [comment]
The Admin Guide document is wrong in this case. It needs to be updated. It should be $configToolkitLogDir.

If you search for $logDirectory in the toolkit, it does not exist anywhere.

**Comment by huvogt** [comment]
OK, I see the point.

In the Version I used the function Write-Log had the parameter:

[Parameter(Mandatory=$false,Position=5)]
                        [ValidateNotNullorEmpty()]
                        [string]$LogFileDirectory = $logDirectory,


Now this Parameter looks different:

            [Parameter(Mandatory=$false,Position=5)]
                        [ValidateNotNullorEmpty()]
                        [string]$LogFileDirectory = $(If ($configToolkitCompressLogs) { $logTempFolder } Else { $configToolkitLogDir }),


So everything is fine.
Thanks



Von: Muhammad Mashwani [mailto:notifications@github.com]
Gesendet: Montag, 11. Januar 2016 16:21
An: PSAppDeployToolkit/PSAppDeployToolkit <PSAppDeployToolkit@noreply.github.com>
Cc: Vogt Hansueli <hansueli.vogt@mobi.ch>
Betreff: Re: [PSAppDeployToolkit] $logDirectory is not set ( Version 3.6.7 ) (#117)


The Admin Guide document is wrong in this case. It needs to be updated. It should be $configToolkitLogDir.

If you search for $logDirectory in the toolkit, it does not exist anywhere.

—
Reply to this email directly or view it on GitHub<https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/117#issuecomment-170585248>.

In der elektronischen Korrespondenz kann die im Schriftverkehr übliche Vertraulichkeit nicht gewährleistet werden. Bitte überprüfen Sie daher sorgfältig, welche Mitteilungen und Beilagen Sie per E-Mail senden und erhalten möchten. Falls Sie dieses E-Mail irrtümlicherweise erhalten haben, bitten wir Sie, die absendende Person zu kontaktieren und dieses E-Mail mit allen Anhängen von Ihrem System zu löschen.

Avec la communication par courrier électronique, la confidentialité des informations n'est pas garantie comme elle l'est usuellement dans la correspondance écrite. Veuillez donc être vigilant lorsque vous envoyez ou recevez des communications et pièces jointes par courriel. Si vous avez reçu ce courriel par erreur, nous vous prions de contacter l'expéditeur/trice et de l'effacer avec toutes les pièces jointes de votre système.
