### ISSUE TITLE
[Feature] Allow extension of the PSADT.Module.DeploymentSession

### ISSUE THREAD

**Issue by neo42JBR** [PSAppDeployToolkit/PSAppDeployToolkit#1178]
### Summary of the new feature / enhancement

We getting along quite well in the quest to migrate our extensions to v4. We used the callback functions to hook into `Open-ADTSession` to call our initialization.

Within it we alter the `ADTConfig` which works as expected, but we would also like to extend the DeploymentSession object with data from our extension so we can leverage the ADT sessions logic.

### Proposed technical implementation details (optional)

Either allow inheritance of the class so we can replace the current session object with ours

-or-

Create a dedicate space within the session object where we can place extension related data

**Comment by DanGough** [comment]
This recent commit allows you to add custom variables when opening the session, and will be in the next release due imminently:

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/380dfc9e2e8c9c28cd060fceaeeb9b41af34fc4b

**Comment by mjr4077au** [comment]
That commit is more to grease the wheels for people extending the `$adtSession` hashtable that's used to instantiate a new session via `Open-ADTSession`. What the OP is asking for is a bit more proper. 

Right now the class is sealed, but I don't see why we couldn't allow inheritance from it. Adding a dictionary that you could add custom values into is possible too, but I'd need to consider how collisions could be avoided between extensions coincidentally trying to set the same key/value pair.

**Comment by mjr4077au** [comment]
I've unsealed the DeploymentSession class, so you should be able to inherit from it with a PowerShell class, or within your own C# code. This was done via https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/5d180400ac9ac5d7e530aa4cbfaaa9d01e0b19aa.

This is a level of customisation I don't think we expected anyone to ask for, so I'm super curious as to what you're working on! If you're on Discord or something, I'd love to chat further about what your needs are and to see how you're going. My username is the same as my GitHub username.

**Comment by neo42JBR** [comment]
Hey Mitch,

would love to get in touch. However, I cannot seem to be able to add you on Discord.
Here is my handle: bretterteig_

**Comment by mjr4077au** [comment]
Just added you before, I'll catch you next time you're online 🤜🤛
