### ISSUE TITLE
[Bug] Variables not being populated

### ISSUE THREAD

**Issue by tintong** [PSAppDeployToolkit/PSAppDeployToolkit#1179]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

In the documentation (https://psappdeploytoolkit.com/docs/variables) you list that variables like "$envProgramFiles" and "$envProgramFilesX86" are available.
However they do not appear to be populated.
Using $adtSession.envProgramFiles and the other one are always empty.

### Steps to reproduce

1. Start a new deployment
2. Add info the script
3. Use either function, like remove folder with $($adtSession.envProgramFiles) and it always fails.

### Environment data

```console
OsName               : Microsoft Windows 10 Education
OsOperatingSystemSKU : 121
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Education
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB}
KeyboardLayout       : en-GB
TimeZone             : (UTC+00:00) Dublin, Edinburgh, Lisbon, London
HyperVisorPresent    : False
CsPartOfDomain       : True
CsPCSystemType       : Desktop
```

**Comment by tintong** [comment]
Then why was I told that I needed to write $adtSession.DirFiles, which is also a environment variable please?

**Comment by mjr4077au** [comment]
That one is a session variable as it directly relates to the deployment itself. Generic variables such as the $env ones are directly available to you.
