### ISSUE TITLE
Test-RegistryValue cannot detect (Default) value

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#118]
Test-RegistryKey -Key $($ARPUninstallHKLM64 + "\$PkgName") -value '(Default)'

always returns $False

Please ideas from the following if needed to fix this:
http://psappdeploytoolkit.com/forums/topic/test-registrykey-for-keys-and-values/

**Comment by amotaz** [comment]
Thanks Guy, We'll look into this

**Comment by amotaz** [comment]
I've done some testing on this. It looks like it will pick up the default value if its been set to something. Otherwise its false. I think that's fine, do you have a compelling reason it should always return positive for (default) ?

**Comment by That-Annoying-Guy** [comment]
I was using it to test for registry key existence.
I should have used (Test-Path -Path $Key -PathType Container) instead.

Could you guys add that to the notes section of the Test-RegistryValue function?

**Comment by amotaz** [comment]
Sure thing, makes sense.

**Comment by amotaz** [comment]
Were you using that instead of test-path for logging reasons? In that case
maybe we'll create a function that mimics that behavior in the next major
version.

**Comment by That-Annoying-Guy** [comment]
I was trying to use PSADT-only functions because I trust them to work better than straight PS2/3/4.
The logging was just a bonus.
