### ISSUE TITLE
[Bug] Invoke-AppDeployToolkit.exe is not able to pass custom parameters containing spaces

### ISSUE THREAD

**Issue by 2mmyU** [PSAppDeployToolkit/PSAppDeployToolkit#1180]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

I am not being able to pass custom parameters when the parameters contains spaces against Invoke-AppDeployToolkit.exe. 

I have a bunch of custom parameters in the param section of the .PS1 script and a bunch of custom functions that I have standardized our company's appdeployment around.
For example a parameter named FriendlyName.

Example:
Invoke-AppDeployToolkit.exe Install -FriendlyName 'Mozilla Firefox'

Both single quotes 'Mozilla Firefox' and double quotes "Mozilla Firefox" fails.

Using names without spaces for example like 'Firefox' works fine.

Param-names with or without spaces worked fine in 3.x.x versions of the toolkit if I encapsulated them with single quotes like this 'Mozilla Firefox'.

Is this a limitation of the new v4 executable, or is this a bug?

### Steps to reproduce

1. Create a custom parameter using spaces

### Environment data

```console
Not able to. Submitting this issue on a mobile.
```

**Comment by mjr4077au** [comment]
In v4, the toolkit doesn't use `powershell.exe -Command`, rather it uses the correct `powershell.exe -File` setup to invoke the script as that's best practice and we're no longer supporting PowerShell 2.x targets 

This means that quoting where you need them in the result is done just like you would within batch scripts or arguments on a scheduled task, etc, and that's would be `\"Mozilla Firefox\"`.

Please refer to https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/335#issuecomment-2537886863 for more info and some screenshots.

**Comment by 2mmyU** [comment]
I must clearly do something wrong using `\"Mozilla Firefox\"`:
![image](https://github.com/user-attachments/assets/718d12ec-1fab-44b5-8e40-2db02c0663c2)

It works fine this way:
![image](https://github.com/user-attachments/assets/fa5ba43b-3773-45f2-afa0-5274793a321a)

**Comment by mjr4077au** [comment]
I think ServiceUI requires ""Mozilla Firefox"" (two double quotes). Give that a try and let me know how you go.

**Comment by 2mmyU** [comment]
Still unable to pass the parameter correctly with two double quotas as well....
![image](https://github.com/user-attachments/assets/1b13dfb8-d566-4dc6-8469-6265119ae94f)

**Comment by mjr4077au** [comment]
So slashes on ServiceUI please 😊. Try without, it should work.

**Comment by 2mmyU** [comment]
I am not following you, I'm sorry...

Another question: Is the use of ServiceUI.exe not necessary anymore to lift the user-prompts to the logged on user runnning in SYSTEM? Is this default behaviour in v4 when using the Fluent GUI?

When I'm not specifying ServiceUI first in the command, it works fine and the user (me) gets the prompts even when running in SYSTEM:
![image](https://github.com/user-attachments/assets/49ede2a0-d7b4-439f-88d6-63f8a7990431)

![image](https://github.com/user-attachments/assets/cd921b70-0604-4c53-8f87-81dd397fa372)

**Comment by 2mmyU** [comment]
Ah, this works!
![image](https://github.com/user-attachments/assets/00d9effb-8fab-415d-a4c4-fa3157f85977)

Thanks for your feedback once again, Mitch! :D

**Comment by mjr4077au** [comment]
No worries at all! 🤜🤛
