### ISSUE TITLE
[Bug] $logName-variable missing from the v4-toolkit?

### ISSUE THREAD

**Issue by 2mmyU** [PSAppDeployToolkit/PSAppDeployToolkit#1182]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

This is from the v3-toolkiit variable references:
![image](https://github.com/user-attachments/assets/3dfcebd5-635e-47ce-bf4e-2d51bd74e52b)

Is the $logName-variable missing from the v4-toolkit?
It would be nice to define the current logfile in use if needed to append other logging to the current PSADT-logfile during installation/uninstallation of the v4-toolkit..

### Steps to reproduce

1. $logName variable missing from the v4-toolkit

### Environment data

```console
Not needed.
```

**Comment by mjr4077au** [comment]
Please wait for the next point release, where you'll be able to provide `-LogName` as an argument to `Open-ADTSession`: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/0c4ce3aa67e95200a446c5b5f007ca50d7ad994d.

**Comment by DanGough** [comment]
You can get the log name in the current version of the toolkit via `$adtSession.LogName`.

**Comment by mjr4077au** [comment]
Thanks @DanGough, I obviously misread the OPs request.

**Comment by 2mmyU** [comment]
Works smoothly::

![image](https://github.com/user-attachments/assets/0498960f-ef38-4710-986c-16b2bb2013d7)

Logfile:
![image](https://github.com/user-attachments/assets/e787bab7-707e-4f31-b16c-c64e4326f0d1)

@DanGough @mjr4077au

**Comment by mjr4077au** [comment]
If you think that's smooth, just wait until I release this in a few days 😏 https://github.com/mjr4077au/PSAppDeployToolkit.WinGet
