### ISSUE TITLE
[Feature] Invoke-ADTFunctionErrorHandler allow overwriting continue type

### ISSUE THREAD

**Issue by neo42JBR** [PSAppDeployToolkit/PSAppDeployToolkit#1183]
### Summary of the new feature / enhancement

Currently the above command will use the ErrorActionPreference of the session. I have a case where I want to generate the error record but specifically want to specify the ErrorActionPreference.

### Proposed technical implementation details (optional)

Add optional parameter for ErrorActionType

**Comment by mjr4077au** [comment]
If you specify an `-ErrorAction` to `Invoke-ADTFunctionErrorHandler`, it'll use that as an override within that function. Can you test and see whether you get the behaviour you're after?

**Comment by neo42JBR** [comment]
PEBCAC

I was just reading the Param block but forgot about [CmdletBinding]
