### ISSUE TITLE
[Bug] Show-ADTInstallationWelcome -CustomText cannot be found

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#1184]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

Show-ADTInstallationWelcome with the argument -CustomText returns an error.

Here's the command I'm using.

`Show-ADTInstallationWelcome -CloseProcesses @{ Name = $adtSession.AppName; Description = "$($adtSession.AppVendor) $($adtSession.AppName) $($AppVersion)" } -Title "Title" -Subtitle "Subtitle" -CustomText "CustomText" -BlockExecution -AllowDeferCloseProcesses -DeferTimes 3 -CheckDiskSpace -PersistPrompt -NoMinimizeWindows`

![image](https://github.com/user-attachments/assets/a238b4d7-963a-46be-8a7f-58a2e537f0a9)

I also noticed that the -Title and -Subtitle arguments have no effects and cannot override the default values.

### Steps to reproduce

1. Add -CustomText "Test Custom Text" to existing Show-ADTInstallationWelcome command
2. Run Invoke-AppDeployToolkit.ps1

### Environment data

```console
OsName               : Microsoft Windows 11 Business
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-08:00) Pacific Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
This parameter is a switch that loads custom text from the strings.psd1 file that you can specify. This is how it was it v3 and how it remains today, and is mentioned in the parameter's help.

I couldn't replicate the title/subtitle issue either, it all appears fine to me?

![image](https://github.com/user-attachments/assets/4eeee89f-cb73-4136-908d-746c7e71222f)

**Comment by b0arkz** [comment]
hi @mjr4077au, I have the same issue with -CustomText switch. but there is no CustomMessage switch in strings.psd1 for Fluent

![image](https://github.com/user-attachments/assets/b30eba07-4497-47e2-bfd7-2911e8318eb9)

any informations/Documentations about how integrate it for Fluent? Changing it in v3 sections does not effect Fluent

**Comment by mjr4077au** [comment]
Hi @b0arkz, currently this isn't a supported UI feature in v4's fluent dialogs. If this is important to you, do you mind creating a separate issue for the feature request so we can get it on the table?

**Comment by b0arkz** [comment]
I Will do ! Thanks for the follow up
