### ISSUE TITLE
[Bug] Show-ADTInstallationWelcome -BlockExecution: Failed to create the scheduled task

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#1185]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

Show-ADTInstallationWelcome with the argument -BlockExecution returns an error.

Here's the command I'm using.
`Show-ADTInstallationWelcome -CloseProcesses @{ Name = $adtSession.AppName; Description = "$($adtSession.AppVendor) $($adtSession.AppName) $($AppVersion)" } -Title "Title" -Subtitle "Subtitle" -BlockExecution -AllowDeferCloseProcesses -DeferTimes 3 -CheckDiskSpace -PersistPrompt -NoMinimizeWindows`
        
![image](https://github.com/user-attachments/assets/17d4766b-88d0-4dd2-857e-ce8cbf633997)

### Steps to reproduce

1. Add -BlockExecution to existing Show-ADTInstallationWelcome command
2. Run Invoke-AppDeployToolkit.ps1

### Environment data

```console
OsName               : Microsoft Windows 11 Business
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-08:00) Pacific Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
Thanks again for another report! Resolved in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/997bb61c18bdf0d04db424e1df988241840eb4eb.
