### ISSUE TITLE
[Bug] Copy-ADTFileUserProfiles: Cannot convert argument oneDrivePath

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#1186]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

I was testing the VLC example script and I got the following error.

![image](https://github.com/user-attachments/assets/1216af4f-9d64-4af1-ac78-ee6dfd8b6915)

For info, the OneDrive variable has a value of "C:\Users\Username\OneDrive - Company"

### Steps to reproduce

1. Have OneDrive for business configured and connected.
2. Run the VLC example script

### Environment data

```console
OsName               : Microsoft Windows 11 Business
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-08:00) Pacific Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
This has been resolved in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/a4fb9b44ae189f16455ed10af2055dfb9310dce1, thanks for the report! 🤜🤛
