### ISSUE TITLE
$logTempFolder should include $deploymentType in its name

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#119]
In AppDeployToolkitMain.ps1 (v3.6.7)

Change

	## Variables: Log Files
	If (-not $logName) { [string]$logName = $installName + '_' + $appDeployToolkitName + '_' + $deploymentType + '.log' }
	#  If option to compress logs is selected, then log will be created in temp log folder ($logTempFolder) and then copied to actual log folder ($configToolkitLogDir) after being zipped.
	[string]$logTempFolder = Join-Path -Path $envTemp -ChildPath $installName

To

	## Variables: Log Files
	If (-not $logName) { [string]$logName = $installName + '_' + $appDeployToolkitName + '_' + $deploymentType + '.log' }
	#  If option to compress logs is selected, then log will be created in temp log folder ($logTempFolder) and then copied to actual log folder ($configToolkitLogDir) after being zipped.
	[string]$logTempFolder = Join-Path -Path $envTemp -ChildPath "${installName}_$deploymentType"

**Comment by mmashwani** [comment]
Pushed this suggestion to latest beta code.
