### ISSUE TITLE
[Bug] New-ADTTemplate with .\ as destination

### ISSUE THREAD

**Issue by ceddshot** [PSAppDeployToolkit/PSAppDeployToolkit#1190]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

When I create a new Template and want to create it in the folder im currently working in with ".\" as the destination, then the folder will be created but an error will occur: 
`PS C:\Softwarevorbereitung> New-ADTTemplate -Name BugReport -Destination .\
New-ADTTemplate: Exception calling "ReadAllText" with "1" argument(s): "Could not find a part of the path 'C:\WINDOWS\system32\BugReport\Invoke-AppDeployToolkit.ps1'."`

### Steps to reproduce

1. Open Powershell
2. Enter New-ADTTemplate -Name "BugReport" -Destination ".\"

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
```

**Comment by mjr4077au** [comment]
This is resolved in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/7c195fb53ed2c360de09f1f3377dccb77c09e0e7, however the function will default to using your present directory as the output directory without having to specify it.
