### ISSUE TITLE
[Feature] Ability to add custom variables to the $adtSession

### ISSUE THREAD

**Issue by Tirakk** [PSAppDeployToolkit/PSAppDeployToolkit#1193]
### Summary of the new feature / enhancement

Hi all,

in v3 we added additional parameters to the ADT Header, like FamilyID and PackageID:

```
    [string]$appCountry = 'DE'                 
    [string]$appEnvironment = 'WRK'                
    [string]$appFunction = 'APP'                 
    [string]$appVendor = ''               
    [string]$appName = ''                 
    [string]$appArch = ''               
    [string]$appVersion = '1.0.0'             
    [string]$appFamilyID = 'F00001'           
    [string]$appPackageID = 'P00001'           
    [string]$appRevision = 'B001' 	             
    [string]$appLang = 'EN'                         
    [string]$appScriptVersion = '35.0.0'           
    [string]$appScriptDate = '??/??/2024'          
    [string]$appScriptAuthor = '' 	                
    # MSStore App Deployment
    [string]$appID = ''                             
    [string]$AppxName = ''                          
    ##*===============================================
    ## Variables: Install Titles (Only set here to override defaults set by the toolkit)
    [String]$installName = "$appCountry"+'_'+"$appEnvironment"+'_'+"$appFunction"+'_'+"$appVendor"+'_'+"$appName"+'_'+"$appArch"+'_'+"$appVersion"+'_'+"$appFamilyID"+'_'+"$appPackageID"+'_'+"$appRevision"
    [String]$installTitle = "$appVendor"+' '+"$appName"+' '+"$appArch"+' '+"$appVersion"
```

And as you ca see, we used these variables throughout the script to write inventory data or use in the log-name for example.

With v4 it's not that mandatory to add additional variables in this place, because the "Open-ADTSession" function is limited to the predefined parameters, so womething like this does not work (The custom properties and the Installname and title part):

```
$adtSession = @{
    # App variables.
    AppVendor = 'Test-Vendor'
    AppName = 'Test-App'
    AppVersion = '105.0.40'
    AppArch = 'x86'
    AppLang = 'DE'
    AppRevision = '01'
    AppSuccessExitCodes = @(0)
    AppRebootExitCodes = @(1641, 3010)
    AppScriptVersion = '36.0.0'
    AppScriptDate = '2024-12-17'
    AppScriptAuthor = 'XXX'

    # Install Titles (Only set here to override defaults set by the toolkit).
    InstallName = "$($adtSession.appCountry)"+'_'+"$($adtSession.appEnvironment)"+'_'+"$($adtSession.appFunction)"+'_'+"$($adtSession.appVendor)"+'_'+"$($adtSession.appName)"+'_'+"$($adtSession.appArch)"+'_'+"$($adtSession.appVersion)"+'_'+"$($adtSession.appFamilyID)"+'_'+"$($adtSession.appPackageID)"+'_'+"$($adtSession.appRevision)"
    InstallTitle = "$($adtSession.appVendor)"+' '+"$($adtSession.appName)"+' '+"$($adtSession.appArch)"+' '+"$($adtSession.appVersion)"

    # Script variables.
    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptVersion = '4.0.3'
    DeployAppScriptParameters = $PSBoundParameters

    # Script parameters.
    DeploymentType = $DeploymentType
    DeployMode = $DeployMode
    AllowRebootPassThru = $AllowRebootPassThru
    TerminalServerMode = $TerminalServerMode
    DisableLogging = $DisableLogging

    
    # Custom Parameters
    appCountry = 'DE'             
    appEnvironment = 'WRK'             
    appFunction = 'APP'                
    appFamilyID = 'F00001'         
    appPackageID = 'P00001'    
    # MSStore App Deployment
    appID = ''                             
    AppxName = ''                          


}
```

And yes, I know these additional parameters aren't exactly session-parameters, more like package-parameters :)

Did anybody face a similar issue and worked out a neat solution?

**Comment by rvkasper** [comment]
I've opted to add 
`$customVars = @{
    AppsClose = ''
}`
Right above the adtSession bit in ours. Can call it up then with 
`$($customVars.AppsClose)`
Iirc @mjr4077au said adtSession is to be read-only

**Comment by mjr4077au** [comment]
@Tirakk, @rvkasper, extending $adtSession with custom variables has already been added in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/380dfc9e2e8c9c28cd060fceaeeb9b41af34fc4b, it'll be in the next point release which is due soon!

**Comment by rvkasper** [comment]
Thank you! I'm really liking what I'm seeing thanks all for the hard work
getting to 4.0

**Comment by rvkasper** [comment]
> @Tirakk, @rvkasper, extending $adtSession with custom variables has already been added in [380dfc9](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/380dfc9e2e8c9c28cd060fceaeeb9b41af34fc4b), it'll be in the next point release which is due soon!

So I'm prepared - will there be any special notation for adding custom vars? We like to define the list for -CloseApps that is passed into Show-ADTInstallationWelcome further up the script (as an example) - so just:
$adtSession = @{
    # App variables.
    ...
    AppScriptAuthor = '<author name>'
    AppsClose = '<your>,<list>,<here>'
}
Thanks again
