### ISSUE TITLE
missing comma in file AppDeployToolkitMain.ps1

### ISSUE THREAD

**Issue by Morkitux** [PSAppDeployToolkit/PSAppDeployToolkit#120]
Hi,

i just download the latest version of your amazing toolkit.
When i launch testing app i meet issue on AppDeployToolkitMain.ps1:
>C:\boulot\sccm\packaging\PSAppDeployToolkit-master\Testing\Deploy-Application.ps1 : Module [C:\boulot\sccm\packaging\PSAppDeployToolkit-master\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1] failed to load: 
Au caractère C:\boulot\sccm\packaging\PSAppDeployToolkit-master\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1:7897 : 20
+         [string]$KBNumber
+                          ~
Parenthèse fermante « ) » manquante dans la liste de paramètres de fonction.
Au caractère C:\boulot\sccm\packaging\PSAppDeployToolkit-master\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1:7877 : 25
+ Function Test-MSUpdates {
+                         ~
Accolade fermante « } » manquante dans le bloc d’instruction.
Au caractère C:\boulot\sccm\packaging\PSAppDeployToolkit-master\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1:7901 : 2
+     )
+     ~
Jeton inattendu « ) » dans l’expression ou l’instruction.
Au caractère C:\boulot\sccm\packaging\PSAppDeployToolkit-master\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1:7967 : 1
+ }
+ ~
Jeton inattendu « } » dans l’expression ou l’instruction.
 
>Au caractère C:\boulot\sccm\packaging\PSAppDeployToolkit-master\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1:7897 : 20
+         [string]$KBNumber
+                          ~
Au caractère Ligne:1 : 1
+ .\Deploy-Application.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Deploy-Application.ps1

So i discovered missing coma on line 7897:
[string]$KBNumber,

**Comment by amotaz** [comment]
Thank you, Good Catch, I'm adding the fix which will be in the upcoming release.
