### ISSUE TITLE
[Bug] Invoke-AppDeployToolkit.exe exit code 60008 when running from pwsh.exe

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#1204]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

For some unknown reason, I can't get **Invoke-AppDeployToolkit.exe** to run properly from the PowerShell 7.

I always get the following error:
![image](https://github.com/user-attachments/assets/2a1a55fe-6d2e-4b73-bca5-561ce6ab1609)

I noticed the process was blocked in Windows Explorer, I unblocked it and it didn't change anything.
![image](https://github.com/user-attachments/assets/61c03987-c67c-40dd-8222-447e80bd1998)

I've tried using Windows Powershell and it worked just fine. So something must be different when executing from PowerShell 7.
![image](https://github.com/user-attachments/assets/95a1adcc-123b-497e-a715-0e4fd8240303)

From experience, I know code to detect the current script path varies depending on the version of PowerShell. If that's the case, here's a function to fix it. It could also be a great addition to PSADT.

```
Function Get-ScriptPath {
<#
.SYNOPSIS
    Returns the current script's path no matter the PowerShell editor or version running.

.NOTES
    Name: Get-ScriptPath
    Version: 1.0

.EXAMPLE
    Get-ScripPath

.LINK

#>

    [CmdletBinding()]
    Param(
        [Parameter(
            Mandatory = $false,
            ValueFromPipeline = $true,
            ValueFromPipelineByPropertyName = $true,
            HelpMessage = "Enter script's path",
            Position = 0
        )]
        [string]$Path
    )

    Begin {
        #$DebugPreference = 'Continue'
        Set-StrictMode -Off
        # Clear variable
        If (-Not [string]::IsNullOrEmpty($scriptPath)) { Remove-Variable -Name scriptPath -Force -ErrorAction SilentlyContinue }
    }

    Process {
        # Manual path entered
        If ($Path) { $scriptPath = Resolve-Path -Path $Path | Select-Object -ExpandProperty Path; $psEditorName = "Manual path" }
        # Visual Studio Code
        ElseIf (-not [String]::IsNullOrEmpty($psEditor)) { $scriptPath = Split-Path -Path $psEditor.GetEditorContext().CurrentFile.Path; $psEditorName = "Visual Studio Code" }
        # PS1 converted to EXE
        ElseIf ($MyInvocation.MyCommand.CommandType -eq 'ExternalScript') { $scriptPath = Split-Path -Path $My$MyInvocation.MyCommand.Source; $psEditorName = "Converted EXE" }
        # Sapien PowerShell Studio
        ElseIf (-not [String]::IsNullOrEmpty($HostInvocation)) { $scriptPath = $HostInvocation.MyCommand.Path; $psEditorName = "Sapien PowerShell Studio" }
        # Windows PowerShell ISE
        ElseIf (-not [String]::IsNullOrEmpty($psISE)) { $scriptPath = Split-Path -Path $psISE.CurrentFile.FullPath; $psEditorName = "Windows PowerShell ISE" }
        # Windows PowerShell 3.0+
        ElseIf (-not [String]::IsNullOrEmpty($MyInvocation.$PSScriptRoot)) { $scriptPath = $MyInvocation.PSScriptRoot; $psEditorName = "Windows PowerShell" }
        ElseIf (-not [String]::IsNullOrEmpty($MyInvocation.MyCommand.Path)) { $scriptPath = Split-Path -Path $MyInvocation.MyCommand.Path -Parent; $psEditorName = "Windows PowerShell" }
        # Windows PowerShell & Powershell
        ElseIf (-not [String]::IsNullOrEmpty($PWD)) { $scriptPath = $PWD.Path; $psEditorName = "PowerShell" }
        # When all else fails
        Else { $scriptPath = (Get-Location).Path; $psEditorName = "Else" }
    }

    End {
        If ([string]::IsNullOrEmpty($scriptPath)) {
            Write-Host -Object "Unable to resolve script's file path!" -ForegroundColor Red
            Start-Sleep -Seconds 3
            Exit
        }
        Write-Debug -Message "PowerShell Editor: $psEditorName"
        Write-Debug -Message "Script Path: $scriptPath"
        return $scriptPath
    }
}
```

### Steps to reproduce

1. Launch Windows Terminal as an admin or pwsh.exe
2. Launch Invoke-AppDeployToolkit.exe

### Environment data

```console
OsName               : Microsoft Windows 11 Business
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-08:00) Pacific Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
Thanks for the report! This was a tricky one... what happens is pwsh.exe sets up PSModulePath, and when powershell.exe runs, it's meant to reset this, but it can't/doesn't when there's something in-between (such as Invoke-AppDeployToolkit.exe).

It's fixed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/1f28319de4769ac708948fe2d7c5dbd72f985d90, and more reading on the specific issue can be done here: https://github.com/PowerShell/PowerShell/issues/18530#issuecomment-1325691850
