### ISSUE TITLE
[Bug] Invoke-AppDeployToolkit.exe -File parameter not working

### ISSUE THREAD

**Issue by DanGough** [PSAppDeployToolkit/PSAppDeployToolkit#1205]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

I am not able to launch a specific script file by overriding with the `-File`  parameter. 

![image](https://github.com/user-attachments/assets/c9881c1c-c5d5-4792-a735-8bc53bdf6753)

### Steps to reproduce

1. Run `Invoke-AppDeployToolkit.exe -File <path to .ps1 file>`

### Environment data

```console
💻
```

**Comment by mjr4077au** [comment]
Fixed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/fbc5ab24009840900cadbd1ed0cfd0e50c3db431.
