### ISSUE TITLE
[Bug] Invoke-AppDeployToolkit.exe error prompts are displayed behind all other windows

### ISSUE THREAD

**Issue by DanGough** [PSAppDeployToolkit/PSAppDeployToolkit#1206]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

When running interactively and the deployment script hits an error, Show-ADTDialogBox pops up with the details of where the script failed.

Invoke-AppDeployToolkit.exe also pops up a dialog with the exit code, however this is displayed behind all other windows. This should be brought to the front if possible.

### Steps to reproduce

1. Get a default v4 template, add `throw-wobbly` or some other garbage command in the script
2. Run Invoke-AppDeployToolkit.exe

### Environment data

```console
💾
```

**Comment by mjr4077au** [comment]
Fixed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/e5239ff0ae6c274fa8d39ac624a06ec9051a0424.
