### ISSUE TITLE
[Bug] Mount-ADTWimFile Automatically Dismounts WIM File During Execution

### ISSUE THREAD

**Issue by b0arkz** [PSAppDeployToolkit/PSAppDeployToolkit#1208]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

I encountered an issue while using the Mount-ADTWimFile function in PSAppDeployToolkit (PSADT). During a deployment process, the WIM file is mounted successfully, but it gets automatically dismounted before subsequent operations can complete, causing the deployment to fail.

### Steps to reproduce

Use the Mount-ADTWimFile function to mount a WIM file in the deployment script:

`Mount-ADTWimFile -ImagePath "PathToWIM" -Path "MountDirectory" -Name "WIMName"`

Perform additional actions (e.g., copy files or schedule tasks) relying on the mounted WIM.
Observe that the WIM file is dismounted automatically at some point in the script execution.

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : fr-BE
TimeZone             : (UTC+01:00) Brussels, Copenhagen, Madrid, Paris
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile
```

**Comment by mjr4077au** [comment]
Are you seeing it dismount in the log files? Is the WIM file local to you, or on a remote location? The call to `Dismount-ADTWimFile` is only in the session closing code (`Close-ADTSession`), so I can't see how this would occur.

**Comment by b0arkz** [comment]
We are in the process of W11 24h2 Upgrade for that I'm using a Wimfile located in $adtdirfiles

The WIM file is local and mounted at C:\ProgramData\FeatureUpdates\WIM using the Mount-ADTWimFile function.
The mount operation succeeds initially and logs confirm this step (WIM file mounted successfully to C:\ProgramData\FeatureUpdates\WIM).

Then i'm creating a STask to perform the setup.exe with this Wim

The script explicitly mounts the WIM using:

`Mount-ADTWimFile -ImagePath "$($adtSession.DirFiles)\w11_24h2.WIM" -Path "C:\ProgramData\FeatureUpdates\WIM" -Name "Windows 11 24H2"`
The subsequent steps rely on this mount to copy files and execute Setup.exe.

Then i'm monitoring the setup with this code : 
```
 #### KICK OFF SCHEDULED TASK ------------------------------------------------------>
   
    Start-Sleep -Seconds 20
   
    #### MONITOR SCHEDULED TASK ------------------------------------------------------->
    $STTaskName = "Win11Upgrade"

    # Loop until the task is no longer running
    while ((Get-ScheduledTask -TaskName $STTaskName).State -eq "Running")
    {
        # Get task information
        $taskInfo = Get-ScheduledTaskInfo -TaskName $STTaskName

        # Verify if the task is being run by SYSTEM
        if ((Get-ScheduledTask -TaskName $STTaskName).Principal.UserId -eq "SYSTEM")
        {
            # Write to the output
            Write-ADTLogEntry -Message "$STTaskName is still running as SYSTEM" -Source $adtSession.InstallPhase
        }
        else
        {
            Write-ADTLogEntry -Message "$STTaskName is still running, but not as SYSTEM" -Source $adtSession.InstallPhase
        }

        # Wait for 10 seconds before checking again
        Start-Sleep -Seconds 10
    }

    Write-ADTLogEntry -Message "$STTaskName has finished running" -Source $adtSession.InstallPhase`
```
    
    Then, i see two lines that dismount the wim automatically
    

```
[Post-Install] :: Dismounting WIM file at path [C:\ProgramData\FeatureUpdates\WIM].	Dismount-ADTWimFile	19/12/2024 15:17:31	7236 (0x1C44)
[Post-Install] :: Successfully dismounted WIM file.	Dismount-ADTWimFile	19/12/2024 15:17:32	7236 (0x1C44)
```


which resulting sometimes by a failed of the IPU at next reboot

> 2024-12-11 17:41:45, Error                 SP         **CApplyWIM: Failure while opening image file C:\ProgramData\FeatureUpdates\WIM\Sources\Install.wim**. Error 0x80070003[gle=0x00000003]
> 2024-12-11 17:41:45, Error                 SP     Operation failed: Apply WIM file PathForNewOSFile, index 3 to C:\$WINDOWS.~BT\NewOS. Error: 0x80070003[gle=0x000000b7]
> 2024-12-11 17:41:45, Error                 SP     COperationQueue::Sort: Could not find an execution phase for 44[gle=0x00000003]
> 2024-12-11 17:41:45, Error                 SP     ExecuteOperations: Operations cannot be sorted. This is a fatal failure.[gle=0x00000003]
> 2024-12-11 17:41:45, Error                 SP     Operation execution failed: 12. hr = 0x80070003[gle=0x00000003]
> 2024-12-11 17:41:45, Error                 SP     ExecuteOperations: Main operation execution failed. Error: 0x8007000D[gle=0x00000003]
> 2024-12-11 17:41:45, Error                 SP     ExecuteOperations: Failed execution phase Safe OS. Error: 0x8007000D[gle=0x00000003]
> 2024-12-11 17:41:45, Error                 SP     CSetupPlatformPrivate::Execute: Execution of operations queue failed, abandoning. Error: 0x8007000D[gle=0x00000003]

**Comment by mjr4077au** [comment]
The fact that it's getting logged in the `Post-Install` section means that you must be dismounting the WIM file somewhere in your own code. Can you post your code where your InstallPhase changes to `Post-Install` through to the end of the function?

The auto-dismount code is deep within `Close-ADTSession`, and the first thing this function does is set the InstallPhase to `Finalization`:

![image](https://github.com/user-attachments/assets/dc844550-904f-4c9c-b4c0-90e19cba5288)

**Comment by b0arkz** [comment]
> The fact that it's getting logged in the `Post-Install` section means that you must be dismounting the WIM file somewhere in your own code. Can you post your code where your InstallPhase changes to `Post-Install` through to the end of the function?
> 
> The auto-dismount code is deep within `Close-ADTSession`, and the first thing this function does is set the InstallPhase to `Finalization`:
> 
> ![image](https://private-user-images.githubusercontent.com/48643140/397734514-dc844550-904f-4c9c-b4c0-90e19cba5288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTY5NjYsIm5iZiI6MTczNDY5NjY2NiwicGF0aCI6Ii80ODY0MzE0MC8zOTc3MzQ1MTQtZGM4NDQ1NTAtOTA0Zi00YzljLWI0YzAtOTBlMTljYmE1Mjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDEyMTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMjgyNzAxMDZhMDMyMDQ0M2QwNTNiMmRlNTI3MDQ2YmFlMDI3NjdkOTMxODExYWYzNDA4NDY4ZDQ2N2ZiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S7zQS3CRj2GTfHjhF1aYokixxN83q-QMXYR8ozw1Ib8)

bad copy past, it was in finalization : 

> [Finalization] :: Dismounting WIM file at path [C:\ProgramData\FeatureUpdates\WIM].	Dismount-ADTWimFile	09/12/2024 19:12:06	2240 (0x08C0)
[Finalization] :: Successfully dismounted WIM file.	Dismount-ADTWimFile	09/12/2024 19:12:08	2240 (0x08C0)

**Comment by b0arkz** [comment]
[Invoke-AppDeployToolkit.zip](https://github.com/user-attachments/files/18210640/Invoke-AppDeployToolkit.zip)

here's my deployment script

[Microsoft_Windows1124H2FeatureUpgrade_EN_01_PSAppDeployToolkit_Install.log](https://github.com/user-attachments/files/18210692/Microsoft_Windows1124H2FeatureUpgrade_EN_01_PSAppDeployToolkit_Install.log)

and a logfile.

after the reboot the IPU randomly failed with the errors as the Wim is DIsmounted by the Close-ADTSession

> 2024-12-11 17:41:45, Error SP CApplyWIM: Failure while opening image file C:\ProgramData\FeatureUpdates\WIM\Sources\Install.wim. Error 0x80070003[gle=0x00000003]
> 2024-12-11 17:41:45, Error SP Operation failed: Apply WIM file PathForNewOSFile, index 3 to C:$WINDOWS.~BT\NewOS. Error: 0x80070003[gle=0x000000b7]
> 2024-12-11 17:41:45, Error SP COperationQueue::Sort: Could not find an execution phase for 44[gle=0x00000003]
> 2024-12-11 17:41:45, Error SP ExecuteOperations: Operations cannot be sorted. This is a fatal failure.[gle=0x00000003]
> 2024-12-11 17:41:45, Error SP Operation execution failed: 12. hr = 0x80070003[gle=0x00000003]
> 2024-12-11 17:41:45, Error SP ExecuteOperations: Main operation execution failed. Error: 0x8007000D[gle=0x00000003]
> 2024-12-11 17:41:45, Error SP ExecuteOperations: Failed execution phase Safe OS. Error: 0x8007000D[gle=0x00000003]
> 2024-12-11 17:41:45, Error SP CSetupPlatformPrivate::Execute: Execution of operations queue failed, abandoning. Error: 0x8007000D[gle=0x00000003]

**Comment by mjr4077au** [comment]
Looking at the logs, I'm pretty sure @DanGough was spot on. As far as I can tell, your script is getting to its natural end point where you call `Show-ADTInstallationPrompt` advising completion, start the async reboot, then close out the session, which will dismount any mounted WIM files.

![image](https://github.com/user-attachments/assets/60baf734-e4fb-46ad-9abc-c5ea95fe7b12)

If your script is getting to the point where it's completing, but it's not complete, then you'll need to work out what additional logic you need to ensure Windows Setup is 100% properly completed before allowing the script to finish.

**Comment by mjr4077au** [comment]
@b0arkz I'm going to close this one for now as I don't believe there's an issue with the toolkit here. If you think otherwise, please let us know and we'll be happy to re-open it.

I also noticed you're on 4.0.3. 4.0.4 has been released with numerous minor fixes so it'd be worth updating to it if you can.
