### ISSUE TITLE
Missing Environment Variables declarations in AppDeployToolkitMain.ps1 v3.6.7

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#121]
Hi guys!
You are doing so well in adding variables like $envUserDesktop, etc. 
Please finish and don't be shy adding a sample of what they should represent. 
Here's what you are missing:

	## Variables: Environment Variables

	[string]$envUserPictures	= [System.Environment]::GetFolderPath('MyPictures')	#C:\Users\Username\Pictures
	[string]$envUserTemplates	= [System.Environment]::GetFolderPath('Templates')	#C:\Users\Username\AppData\Roaming\Microsoft\Windows\Templates
	[String]$envCommonDesktop	= [Environment]::GetFolderPath('CommonDesktop')		#C:\Users\Public\Desktop
	[String]$envCommonDocuments	= [Environment]::GetFolderPath('CommonDocuments')	#C:\Users\Public\Documents
	[String]$envCommonPrograms 	= [Environment]::GetFolderPath('CommonPrograms') 	#C:\ProgramData\Microsoft\Windows\Start Menu\Programs
	[String]$envCommonStartMenu	= [Environment]::GetFolderPath('CommonStartMenu')	#C:\ProgramData\Microsoft\Windows\Start Menu
	[string]$envCommonStartUp	= [Environment]::GetFolderPath('CommonStartUp')		#C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
	[string]$envCommonTemplates = [System.Environment]::GetFolderPath('CommonTemplates') #C:\ProgramData\Microsoft\Windows\Templates

**Comment by sintaxasn** [comment]
Done :) Added to latest source.

**Comment by That-Annoying-Guy** [comment]
Hi Dan, 

I just realized that using .NET to populate the variables might not be a good idea. 
If XP is the lowest .NET version you support, we might have to get the common values out from the registry and forget the user values as they might not exist when running as system.

If we don't we'll see error like this:

					  +         [string]$envCommonStartMenuPrograms = [Environment]::GetFolderPath <<<< ('CommonPrograms')



	Error Inner Exception(s):
	-------------------------

	Message        : Cannot convert value "CommonPrograms" to type "System.Environment+SpecialFolder" due to invalid enumer
					 ation values. Specify one of the following enumeration values and try again. The possible enumeration
					 values are "Desktop, Programs, Personal, MyDocuments, Favorites, Startup, Recent, SendTo, StartMenu, M
					 yMusic, DesktopDirectory, MyComputer, Templates, ApplicationData, LocalApplicationData, InternetCache,
					  Cookies, History, CommonApplicationData, System, ProgramFiles, MyPictures, CommonProgramFiles".

**Comment by mmashwani** [comment]
There is no problem with using .NET to populate the variables. The variables go back to .NET 1.1. The problem is that there is no variables called 'CommonPrograms'. It called 'CommonProgramFiles'.

**Comment by mmashwani** [comment]
https://msdn.microsoft.com/en-us/library/system.environment.specialfolder(v=vs.71).aspx

**Comment by That-Annoying-Guy** [comment]
I wish!
'CommonPrograms' gives you C:\ProgramData\Microsoft\Windows\Start Menu\Programs
'CommonProgramFiles' gives you C:\Program Files\Common Files

This is why I said about adding a sample of what they should represent..

**Comment by mmashwani** [comment]
CommonPrograms first became available with .NET 4. Therefore, we can't use it in the toolkit.
https://msdn.microsoft.com/en-us/library/system.environment.specialfolder(v=vs.100).aspx

**Comment by That-Annoying-Guy** [comment]
Could we do something like this for now?

	$ShellFolders = Get-ItemProperty -Path "HKLM:Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders"
	[String]$envCommonPrograms  = $ShellFolders | Select $Value -ExpandProperty "Common Programs"

**Comment by That-Annoying-Guy** [comment]
From your silence I guess it's "nothing but .Net" for you guys.

**Comment by sintaxasn** [comment]
From our silence I would infer that it's Thanksgiving and we'll discuss when we're back from break.

For now, I'm reopening.

**Comment by That-Annoying-Guy** [comment]
Opps!
I'm sorry to have forgotten about your American holiday.
I'll post the code for the 'common' variables and I'll let you decide if it's worthy of inclusion or not.

Thank you for setting me straight.

**Comment by sintaxasn** [comment]
I've made the relevant changes. Can you recheck this?

**Comment by That-Annoying-Guy** [comment]
It's broken. I'll get you tested code in about 30 minutes.
