### ISSUE TITLE
[Bug] Get-ADTRunningProcesses not properly detecting running processes.

### ISSUE THREAD

**Issue by ryanedlund** [PSAppDeployToolkit/PSAppDeployToolkit#1216]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.4

### Describe the bug

Have this line in the script:

Show-ADTInstallationWelcome -CloseProcesses 'msedge,MicrosoftEdge,MicrosoftEdgeCP,MicrosoftEdgeSH,ms-teams,msedgewebview2' -ForceCloseProcessesCountdown 1800 -PersistPrompt -BlockExecution

But I am not seeing the Installation Welcome screen popup, even with a number of the listed applications running.

With Debug and verbose enabled I see:

[Get-ADTRunningProcesses] [Info] :: Checking for running applications: [msedge,MicrosoftEdge,MicrosoftEdgeCP,MicrosoftEdgeSH,ms-teams,msedgewebview2]
[2024-12-23 17:18:40.445] [Pre-Install] [Get-ADTRunningProcesses] [Info] :: Specified applications are not running.

Even though msedge, ms-teams, and msedgewebview2 all are listed when doing get-process.

This causes Show-ADTInstallationWelcome -CloseProcesses to not work properly, as it doesn't think there is anything running it needs to prompt for/close.

I attempted to manually run Get-ADTRunningProcesses, but that doesn't seem to exist as something I can run.

### Steps to reproduce

1.  In Pre-installation section:

Show-ADTInstallationWelcome -CloseProcesses 'msedge,MicrosoftEdge,MicrosoftEdgeCP,MicrosoftEdgeSH,ms-teams,msedgewebview2' -ForceCloseProcessesCountdown 1800 -PersistPrompt -BlockExecution

2.  With MS Teams. Edge and Webview2 processes running, confirm that script reports "Specified applications are not running." and doesn't close applications as expected.

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-05:00) Eastern Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop

.NET SDK (reflecting any global.json):
 Version:   6.0.428
 Commit:    ef6f5ce48c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.428\

Host:
  Version:      7.0.20
  Architecture: x64
  Commit:       0fb6ac59fb

.NET SDKs installed:
  6.0.428 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by mjr4077au** [comment]
It's because you've passed through a single string of process names, which was one of v3's design mistakes. Take the quotes off each end and it'll work fine.
