### ISSUE TITLE
Updated Get-InstalledApplication in v3.6.8 beta too picky

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#122]
By adding DisplayName,DisplayVersion,UninstallString,InstallSource,InstallLocation,InstallDate,Publisher
to the following line:

	[psobject[]]$regKeyApplication += Get-ChildItem -LiteralPath $regKey -ErrorAction 'SilentlyContinue' -ErrorVariable '+ErrorUninstallKeyPath' | ForEach-Object { Get-ItemProperty -Name DisplayName,DisplayVersion,UninstallString,InstallSource,InstallLocation,InstallDate,Publisher -LiteralPath $_.PSPath -ErrorAction 'SilentlyContinue' -ErrorVariable '+ErrorUninstallKeyPath' | Where-Object { $_.DisplayName } } 2>$null

A stream of errors pour out.
Why? Not every ARP entry has those values. 
E.g. AddressBook doesn't has a DisplayName value so:

	Error Record:
	-------------

	Message        : Property DisplayName does not exist at path HKEY_LOCAL_MACHINE
					 \SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\AddressBook.
	InnerException : 

	FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Micros
							oft.PowerShell.Commands.GetItemPropertyCommand

	PositionMessage : 
					  At C:\Users\srpmaster\Desktop\_TestPackage_using_v3.6.7\AppDe
					  ployToolkit\AppDeployToolkitMain.ps1:1948 char:181
					  +                 [psobject[]]$regKeyApplication += Get-Child
					  Item -LiteralPath $regKey -ErrorAction 'SilentlyContinue' -Er
					  rorVariable '+ErrorUninstallKeyPath' | ForEach-Object { Get-I
					  temProperty <<<<  -Name DisplayName,DisplayVersion,UninstallS
					  tring,InstallSource,InstallLocation,InstallDate,Publisher -Li
					  teralPath $_.PSPath -ErrorAction 'SilentlyContinue' -ErrorVar
					  iable '+ErrorUninstallKeyPath' | Where-Object { $_.DisplayNam
					  e } } 2>$null

It also doesn't have a DisplayVersion Value so:

	 Error Record:
	-------------

	Message        : Property DisplayVersion does not exist at path HKEY_LOCAL_MACH
					 INE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Addres
					 sBook.

**Comment by amotaz** [comment]
Hmm...  That's odd, when I tested the silentlycontinue captured does not
exist errors. I'll look at it again. Thanks for the info.

**Comment by amotaz** [comment]
hmm... yeah this is very odd. I isolated this line of code:
```
Get-ChildItem -LiteralPath "hklm:\software\wow6432node\microsoft\windows\currentversion\uninstall" -ErrorAction 'SilentlyContinue' -ErrorVariable '+ErrorUninstallKeyPath' | ForEach-Object { Get-ItemProperty -Name DisplayName,DisplayVersion,UninstallString,InstallSource,InstallLocation,InstallDate,Publisher -LiteralPath $_.PSPath -ErrorAction 'SilentlyContinue' -ErrorVariable '+ErrorUninstallKeyPath' | Where-Object { $_.DisplayName } } 2>$null"
```

And AddressBook doesnt show up because of that last bit:
```Where-Object { $_.DisplayName }```

With the SilentlyContinue and the 2>$null you shouldnt see any error output.

What do you get when you run that?

**Comment by amotaz** [comment]
Scratch that, I'm able to easily reproduce like you, working on it...

**Comment by amotaz** [comment]
I think I figured it out. This is what's happening. We're capturing the errors that occur during each pass of the uninstall key here:
```-ErrorVariable '+ErrorUninstallKeyPath'```
That is dumped into the log. The function is still working, however you're seeing more errors now that we're targeting specific properties within the keys.

We'll think about how we need to handle this. I'd prefer the log be cleaner.

**Comment by That-Annoying-Guy** [comment]
A log file void of distracting non-errors is good.

On that note, I should probably mention the missing file bug/feature in Remove-File. But I'll create a new issue for that.

**Comment by amotaz** [comment]
Issue resolved, let use know how your testing goes.
