### ISSUE TITLE
[Bug] Set-ADTActiveSetup reports version in HKCU as higher or the same eventhough it is lower.

### ISSUE THREAD

**Issue by CSVDK** [PSAppDeployToolkit/PSAppDeployToolkit#1220]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.4

### Describe the bug

Set-ADTActive Setup creates a active setup using the date as the version for the Activesetup registration in the HKLM and HKCU registry.
When run again the version in HKLM is update to the new date. Unfortunately the Active setup is automatically not run again by PSADT because it claims that the version in HKCU is newer or the same as the version in HKLM, but the version in HKLM is actually higher.

HKCU: Version = 2412,3016,1702
HKLM: Version = 2412,3016,4854

Log entry:
[2024-12-30 16:48:55.544] [Post-Install] [Test-ADTActiveSetup] [Info] :: HKLM and HKCU active setup entries are present. Both Version properties are present and valid. However, they are either the same or HKCU Version property is higher.
[2024-12-30 16:48:55.552] [Post-Install] [Set-ADTActiveSetup] [Warning] :: Skipping executing Active Setup StubPath file for current user.

### Steps to reproduce

1. Use Set-ADTActiveSetup to create a active setup using the date as the version for the Activesetup registration
2. Run the PSADT script.
3. Run the PSADT script again, this will result in the active setup command not being executed as it should, with the log entry described in description.

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64 bits
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : nl-NL
OsMuiLanguages       : {nl-NL, en-US}
KeyboardLayout       : 00020409
TimeZone             : (UTC+01:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:270
+ ... 'HyperVisorPresent','CsPartOfDomain','CsPCSystemType'); dotnet --info
+                                                             ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by mjr4077au** [comment]
Thanks for the report! This should be addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/b9496f10aa3e9abf0e81bb9c5d9bd0ff56532af6 and will be in the next point release.
