### ISSUE TITLE
[Bug] Close-ADTSession not passing through 3010 in 4.0.4

### ISSUE THREAD

**Issue by PaddyBudz** [PSAppDeployToolkit/PSAppDeployToolkit#1221]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.4

### Describe the bug

Close-ADTSession is not passing through 3010 in v4.0.4, this was working fine in 4.0.3

### Steps to reproduce

v 4.0.4
1.insert close-adtsession 3010 in invoke-appdeploytoolkit.ps1
2.run invoke-appdeploytoolkit.exe -allowrebootpassthru from windows powershell or pwsh.exe
3.log should show 
[Finalization] :: [PSAppDeployToolkit_4.0.4_EN_01] install completed with exit code [0]

v4.0.3
1.insert close-adtsession 3010 in invoke-appdeploytoolkit.ps1
2.run invoke-appdeploytoolkit.exe -allowrebootpassthru from windows powershell or pwsh.exe
3. log should show
[Finalization] :: A restart has been flagged as required.	Close-ADTSession	12/30/2024 12:30:09 PM	10164 (0x27B4)
[Finalization] :: [PSAppDeployToolkit_4.0.3_EN_01] installation completed with exit code [3010].	Close-ADTSession	12/30/2024 12:30:09 PM	10164 (0x27B4)

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise Insider Preview
OSDisplayVersion     : Dev
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 27723.1000.amd64fre.rs_prerelease.241004-1602
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-05:00) Eastern Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
Thanks for the report! This has been fixed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/a4b5507e1aa1dd6a8315eece7dbe0b436ac7dd1a and will make it into 4.0.5.
