### ISSUE TITLE
[Bug] Update-ADTGroupPolicy is only targeting Computer settings

### ISSUE THREAD

**Issue by JMOC68** [PSAppDeployToolkit/PSAppDeployToolkit#1222]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.4

### Describe the bug

Update-ADTGroupPolicy is only targeting Computer settings.  Log only shows:
[Install] :: Updating Group Policies for the Computer.

### Steps to reproduce

1. Added Update-ADTGroupPolicy to Install section of Invoke-AppDeployToolkit.ps1
2. Reviewed log file and found that it only mentioned updating Computer settings
3. Ran script again while reviewing Task Manager.  Never saw it run "...cmd.exe" /c "echo N | gpupdate.exe /Target:User

### Environment data

```console
Microsoft Windows 11 Enterprise
23H2
10.0.22631
x64
```

**Comment by JMOC68** [comment]
Removed domain/user/computer names from log file.
[PSAppDeployToolkit_4.0.4_EN_01_PSAppDeployToolkit_Install.log](https://github.com/user-attachments/files/18277671/PSAppDeployToolkit_4.0.4_EN_01_PSAppDeployToolkit_Install.log)

**Comment by mjr4077au** [comment]
Thanks for the report! This has been addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/60760e33624c715e4431e7ffe9e3f4d326177bf4 and will be in the next point release.
