### ISSUE TITLE
[Bug] v4 does not work on Windows Server Core versions

### ISSUE THREAD

**Issue by PaddyBudz** [PSAppDeployToolkit/PSAppDeployToolkit#1223]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.4

### Describe the bug

If you try to run version 4 PSADT on a Windows Server core install the process errors out with the following error:

Open-ADTSession : Exception calling "ConvertImageToIcon" with "1" argument(s): "The specified module could not be found"
At \\DHDVAHMMCMPS01\SCCMPackages\OSD\UPPKG\v4\invoke-appdeploytoolkit.ps1:301 char:23
+ ... dtSession = Open-ADTSession -SessionState $ExecutionContext.SessionSt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Open-ADTSession], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception,Open-ADTSession

### Steps to reproduce

1. Create v4 template or use existing one
2. Run the .ps1 script (the exe errors out with 60008) on a machine running windows server core (2022, and 2025 were tried)
3. ??
4. Profit.

V3.10.2 works fine

### Environment data

```console
OsName               : Microsoft Windows Server 2025 Standard
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows Server 2025 Standard
WindowsBuildLabEx    : 26280.5000.amd64fre.ge_prerelease.240824-1650
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-08:00) Pacific Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:270
+ ... 'HyperVisorPresent','CsPartOfDomain','CsPCSystemType'); dotnet --info
+                                                             ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by mjr4077au** [comment]
This has already been addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/e0c6252b4a13677d04d0d124a46252909029fa62 and will be in the next point release 🤜🤛
