### ISSUE TITLE
Remove-File now mute on ALL errors; Also stops deleting at the first sign of trouble.

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#123]
Previously I complained in Issue #57 "Remove-File treats already deleted (or missing files) as errors"
Mo said he would not fix.
I figured out why: If weird errors show up, they are captured in the log file.
**Sadly, Mo didn't put that in a comment so that functionality was lost to most people.**

But since version 3.6.5, this functionality was nuke by adding **$null =** in front of the key lines, 

	$null = Remove-Item -Path $path -Force -Recurse -ErrorAction 'Stop'

and now any weird errors are now prevented from even being logged. 

I recommend to remove the **$null =** and add the following code at the top of the Process block:

	Process {
		Try { $Exist = Test-Path -Path $path -Verbose -ErrorAction Stop 
		} catch { If ( $($_.Exception) -match 'Access is denied' ) { Write-Log "Path [$path] Access is denied"; Return; $Exist = $false } }

		If ( -not ($Exist) ) {
			Write-Log -Message "Path [$path] does not exist."  -Source ${CmdletName}
			Return
		}

This way we keep Mo's Error trapping idea but we skip files that are permission-blocked or  already deleted without clogging the log file with distracting non-errors.

----------------------------------------

The other issue in Remove-File is that it stops deleting files at the first since of trouble.
If you are clearing out a folder like %temp%, some files are bound to be locked open. 
If you have 500 files to delete and file #130 is open, the other 370 files will not even be looked at.
That is because we don't delete with **-ErrorAction SilentlyContinue**. (If you'd do that, you'd also loose Mo's Error trapping idea)

Now because this might not be used very often, fixing this might be overkill. 
We can either mention this as a CAVEAT in the Notes section of Remove-File 
or add code something like this:

		<snip.
		[Parameter(Mandatory=$false)]
		[ValidateNotNullOrEmpty()]
		[boolean]$UseSilentlyContinue = $false
		<snip>

		If ($UseSilentlyContinue) {
			If ($Recurse) {
				Write-Log -Message "Delete file(s) recursively in path [$path] (AND ignoring errors)..." -Source ${CmdletName}
				Remove-Item -Path $path -Force -Recurse -ErrorAction SilentlyContinue | Out-Null
			}
			Else {
				Write-Log -Message "Delete file in path [$path] (AND ignoring errors)..." -Source ${CmdletName}
				Remove-Item -Path $path -Force -ErrorAction SilentlyContinue | Out-Null
			}
		} Else {
			Try {
				If ($Recurse) {
					Write-Log -Message "Delete file(s) recursively in path [$path]..." -Source ${CmdletName}
					Remove-Item -Path $path -Force -Recurse -ErrorAction 'Stop' | Out-Null
				}
				Else {
					Write-Log -Message "Delete file in path [$path]..." -Source ${CmdletName}
					Remove-Item -Path $path -Force -ErrorAction 'Stop' | Out-Null
				}
			}
			Catch {
				Write-Log -Message "Failed to delete file(s) in path [$path]. `n$(Resolve-Error)" -Severity 3 -Source ${CmdletName}
				If (-not $ContinueOnError) {
					Throw "Failed to delete file(s) in path [$path]: $($_.Exception.Message)"
				}
			}
		}

I don't care which way you decide but you must either mention or deal with the lack of SilentlyContinue in Remove-File.

**Comment by amotaz** [comment]
Added a fix in latest push. Let me if know if you still have issues with your testing.

**Comment by That-Annoying-Guy** [comment]
I'm sorry Amotaz but your cure is worse than the disease.

	PS C:\Users\<MyUserName>\Documents> Remove-File -Path "c:\dont\exist" -ContinueOnError $true
	
	[12-15-2015 17:00:58.293] [Initialization] [Remove-File] :: Failed to delete file(s) in path [c:\dont\exist]. 
	Error Record:
	-------------

	Message        : Cannot find path 'C:\dont\exist' because it does not exist.
	InnerException : 

	FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
	ScriptStackTrace      : at Remove-File<Process>, C:\Users\<MyUserName>\Desktop\PSAppDeployToolkit-master(1)\AppDeployToolkit
							\AppDeployToolkitMain.ps1: line 3274
							at <ScriptBlock>, <No file>: line 1

	PositionMessage : At 
					  C:\Users\<MyUserName>\Desktop\PSAppDeployToolkit-master(1)\AppDeployToolkit\AppDeployToolkitMain.ps1:3274 
					  char:30
					  +             [string[]]$ResolvedPath = Resolve-Path -Path $Path -ErrorVariable '+ErrorRemo ...
					  +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




	[12-15-2015 17:00:58.307] [Initialization] [Remove-File] :: The following error(s) took place while removing file(s) in path [c:\dont\exist]. 
	Error Record:
	-------------

	Message        : Cannot find path 'C:\dont\exist' because it does not exist.
	InnerException : 

	FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
	ScriptStackTrace      : at Remove-File<Process>, C:\Users\<MyUserName>\Desktop\PSAppDeployToolkit-master(1)\AppDeployToolkit
							\AppDeployToolkitMain.ps1: line 3274
							at <ScriptBlock>, <No file>: line 1

	PositionMessage : At 
					  C:\Users\<MyUserName>\Desktop\PSAppDeployToolkit-master(1)\AppDeployToolkit\AppDeployToolkitMain.ps1:3274 
					  char:30
					  +             [string[]]$ResolvedPath = Resolve-Path -Path $Path -ErrorVariable '+ErrorRemo ...
					  +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And I've found out that Remove-RegistryKey does the same thing: 

	[12-15-2015 16:35:18.556] [Uninstallation] [Remove-RegistryKey] [Info] :: Delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{DD7C8305-2061-4C6E-9363-E762B844F505}] [SystemComponent].
	[12-15-2015 16:35:18.572] [Uninstallation] [Remove-RegistryKey] [Error] :: Failed to delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{DD7C8305-2061-4C6E-9363-E762B844F505}] [SystemComponent]. 
	Error Record:
	-------------

	Message        : Property SystemComponent does not exist at path HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentV
					 ersion\Uninstall\{DD7C8305-2061-4C6E-9363-E762B844F505}.
	InnerException : 

	FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.RemoveItemProper
							tyCommand
	ScriptStackTrace      : at Remove-RegistryKey<Process>, C:\Users\<Myusername>\AppData\Local\Temp\Deploy-Application_v1r1
							\AppDeployToolkit\AppDeployToolkitMain.ps1: line 3775
							at Set-ARPChildOfParent<Process>, C:\Users\<Myusername>\AppData\Local\Temp\Deploy-Application_v1
							r1\AppDeployToolkit\AppDeployToolkitExtensions.ps1: line 1965
							at <ScriptBlock>, 
							C:\Users\<Myusername>\AppData\Local\Temp\Deploy-Application_v1r1\Deploy-Application_v1r1.ps1: 
							line 355
							at <ScriptBlock>, <No file>: line 1

	PositionMessage : At C:\Users\<Myusername>\AppData\Local\Temp\Deploy-Application_v1r1\AppDeployToolkit\AppDeployToolkitM
					  ain.ps1:3775 char:14
					  +                     $null = Remove-ItemProperty -LiteralPath $Key -Name $Name -Force -ErrorActi ...
					  +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



**What is so wrong with not complaining that the removal/deletion is already done?**

If you carried this line of thought with New-Folder, it should complain that the folder already exists, but it doesn't. (and that is good!)

	PS C:\Users\<Myusername>\Documents> New-Folder -Path "C:\ProgramData" -ContinueOnError $true
	[12-15-2015 17:14:28.405] [Initialization] [New-Folder] :: Folder [C:\ProgramData] already exists.

If I send this up to QA, they will see a sea of red on the screen, assume the package is broken and send it back. Therefore I will fix these functions in my personal fork so that I can get packages out.

If am the only one that sees it this way, we'll agree to disagree.

**Comment by mmashwani** [comment]
I don't see how the cure is worse then the disease. There are quite a few improvements in the new function compared to the old one but you seem to be focused in on just what you want. We are working with you to create a new function that better deals with all concerns, yours, ours, and the communities. Please be respectful on the threads here. Your tone and the way your are bolding certain lines is coming off as very rude right now.

We will discuss your suggestion and let you know what we decide.

**Comment by That-Annoying-Guy** [comment]
Sorry Mo. 
Looking back, yes it does look rude. ( I guess I did chose my screen name well after all )
With the [resolved] tag I was under the impression that the 'work' was, um, done.
I used bold because that was the important bit in the wall of text I posted.

I guess I am frustrated that Remove-File is so different at how it handles files that are already deleted compared to let's say CMD's del command.

**Comment by mmashwani** [comment]
No worries. Aman and I discussed it and we will add a catch to trap the specific error when the file does not exist and then log an informational or warning message that says the path does not exist. That way an error will not be shown. We will use the same logic in the registry function as well to be consistent.

**Comment by mmashwani** [comment]
I pushed an update to function Remove-File to write a warning instead of an error if the path being deleted does not exist. Please test and let me know if it's working as expected. I haven't had a chance to fully test it.

**Comment by amotaz** [comment]
Hello,
Is the function working now?

**Comment by That-Annoying-Guy** [comment]
Sorry about that. Have been told to ship something out pronto.
I'll do my best to test this today.

**Comment by That-Annoying-Guy** [comment]
PS C:\Users\<MyUserName>\Documents> Remove-File -Path "c:\dont\exist" -ContinueOnError $true
	[12-31-2015 15:28:26.875] [Initialization] [Remove-File] :: Unable to resolve file(s) for deletion in path [c:\dont\exist] because path does not exist.


	PS C:\Users\<MyUserName>\Documents> Remove-File -Path "c:\dontexist" -ContinueOnError $true
	[12-31-2015 15:42:17.795] [Initialization] [Remove-File] :: Unable to resolve file(s) for deletion in path [c:\dontexist] because path does not exist.



	PS C:\Users\<MyUserName>\Documents> Remove-RegistryKey -Key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DontExistKey"
	[12-31-2015 15:37:15.113] [Initialization] [Convert-RegistryPath] :: Return fully qualified registry key path [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DontExistKey].
	[12-31-2015 15:37:15.120] [Initialization] [Remove-RegistryKey] :: Unable to delete registry key [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DontExistKey] because it does not exist.

	PS C:\Users\<MyUserName>\Documents> Remove-RegistryKey -Key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DontExistKey" -Name "DEValueName"
	[12-31-2015 15:37:47.978] [Initialization] [Convert-RegistryPath] :: Return fully qualified registry key path [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DontExistKey].
	[12-31-2015 15:37:47.985] [Initialization] [Remove-RegistryKey] :: Unable to delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DontExistKey] [DEValueName] because registry key does not exist.

	PS C:\Users\<MyUserName>\Documents> Remove-RegistryKey -Key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall" -Name "DEValueName"
	[12-31-2015 15:38:08.036] [Initialization] [Convert-RegistryPath] :: Return fully qualified registry key path [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall].
	[12-31-2015 15:38:08.042] [Initialization] [Remove-RegistryKey] :: Delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall] [DEValueName].
	[12-31-2015 15:38:08.101] [Initialization] [Remove-RegistryKey] :: Failed to delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall] [DEValueName]. 
	Error Record:
	-------------

	Message        : Property DEValueName does not exist at path 
					 HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall.
	InnerException : 

	FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.RemoveItemPropertyCommand
	ScriptStackTrace      : at Remove-RegistryKey<Process>, C:\Users\<MyUserName>\Desktop\PSAppDeployToolkit-v3.6.8Beta31Dec\AppDeplo
							yToolkit\AppDeployToolkitMain.ps1: line 3794
							at <ScriptBlock>, <No file>: line 1

	PositionMessage : At C:\Users\<MyUserName>\Desktop\PSAppDeployToolkit-v3.6.8Beta31Dec\AppDeployToolkit\AppDeployToolkitMain.ps1:3
					  794 char:14
					  +                     $null = Remove-ItemProperty -LiteralPath $Key -Name $Name -Force -ErrorActi ...
					  +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Results:
Remove-File looks good. I'll bring it in and get back if it acts up.

Remove-RegistryKey does not blow up if the Key does not exist, 
but if the value *-Name* you want to delete is already gone, it treats it like a syntax error error.

Thank you for your efforts guys! This issue is almost fixed.
				 
Off-topic: Why to you guys want to go to a module in V4. What are the advantages? How would Extensions be handled? (I live on my extensions) Is there a thread talking about this that exists already?

**Comment by amotaz** [comment]
ok, we added some special handling for removing a registry value. It should show up as a warning if the value does not exist.

**Comment by That-Annoying-Guy** [comment]
I DL'd the latest 30 min ago. Not much difference. Please check if your changes are in the master.

	PS C:\Users\<MyUserName>\Documents> Remove-RegistryKey -Key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall" -Name "DEValueName"
	[01-04-2016 11:27:42.694] [Initialization] [Convert-RegistryPath] :: Return fully qualified registry key path [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall].
	[01-04-2016 11:27:42.703] [Initialization] [Remove-RegistryKey] :: Delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall] [DEValueName].
	[01-04-2016 11:27:42.777] [Initialization] [Remove-RegistryKey] :: Failed to delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall] [DEValueName]. 
	Error Record:
	-------------

	Message        : Requested registry access is not allowed.
	InnerException : 

	FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.RemoveItemProper
							tyCommand
	ScriptStackTrace      : at Remove-RegistryKey<Process>, C:\Users\<MyUserName>\Desktop\PSAppDeployToolkit-
							v3.6.8Beta04Jan\AppDeployToolkit\AppDeployToolkitMain.ps1: line 3802
							at <ScriptBlock>, <No file>: line 1

	PositionMessage : At C:\Users\<MyUserName>\Desktop\PSAppDeployToolkit-v3.6.8Beta04Jan\AppDeployToolkit\Ap
					  pDeployToolkitMain.ps1:3802 char:14
					  +                     $null = Remove-ItemProperty -LiteralPath $Key -Name $Name 
					  -Force -ErrorActi ...
					  +                             
					  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mmashwani** [comment]
What you show above is a registry access error. That will show up in the logs as an error and I don't plan on changing that. The update that was made was that if a registry value being deleted did not exist, then a warning will be written to the log instead of an error. That was also the issue you reported earlier, unless there was some mis-communication.

**Comment by That-Annoying-Guy** [comment]
Thank you for reading my error message. This cold I have seems to be affecting my thoroughness.

	PS C:\Users\<MyUserName>\Documents> Remove-RegistryKey -Key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall" -Name "DEValueName"
	[01-04-2016 14:22:31.948] [Initialization] [Convert-RegistryPath] :: Return fully qualified registry key path [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall].
	[01-04-2016 14:22:31.954] [Initialization] [Remove-RegistryKey] :: Delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall] [DEValueName].
	[01-04-2016 14:22:31.961] [Initialization] [Remove-RegistryKey] :: Unable to delete registry value [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall] [DEValueName] because it does not exist.

Works as advertised
Thank you
close it!
