### ISSUE TITLE
Execute-Process exits script on file not found for target executable

### ISSUE THREAD

**Issue by amotaz** [PSAppDeployToolkit/PSAppDeployToolkit#125]
Execute-Process exits script on file not found for target executable.
This is regardless of ContinueOnError parameter. We can consider the implications of adding a check for ContinueOnError before exiting the script. 

Marking as enhancement since the definition of ContinueOnError currently is strictly defined to a reaction to the executable exit code.

**Comment by amotaz** [comment]
We may modify the continueonerror behavior long term, but not in the next minor release

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/execute-process-exits-script-on-file-not-found-for-target-executable/1194

**Comment by luki1412** [comment]
#479 modifies behavior of -ContinueOnError and another PR adds ability to not exit script on error.
