### ISSUE TITLE
No Balloon Notifications on Windows 10

### ISSUE THREAD

**Issue by n1x0d** [PSAppDeployToolkit/PSAppDeployToolkit#128]
Hello,
not an issue for me just something I noticed: There is no balloon notification on Windows 10.
Kind regards

**Comment by amotaz** [comment]
Windows 10 uses Toast notifications by default. There are various tutorials online on how to move back to using balloon tips.

Are you not get any toast notifications?

**Comment by n1x0d** [comment]
Indeed, I am neither getting any toasts nor am I seeing any balloon notifications. There is nothing in the notification center either.

**Comment by n1x0d** [comment]
Ok, I am stupid. Working as expected!
