### ISSUE TITLE
Allow setting custom $installTitle and $installName

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#130]
At my work we have our own naming convention for log names etc.
In my fork I add a few simple lines in AppDeployToolkitMain.ps1 which allows us to set $installTitle and $installName in Deploy-Application.ps1.

Would you guys be interested in adding the 4 lines added below?

	If (-not $installTitle) {
		[string]$installTitle = ("$appVendor $appName $appVersion").Trim()
	}

	## Sanitize the application details, as they can cause issues in the script
	[char[]]$invalidFileNameChars = [IO.Path]::GetInvalidFileNameChars()
	[string]$appVendor = $appVendor -replace "[$invalidFileNameChars]",'' -replace ' ',''
	[string]$appName = $appName -replace "[$invalidFileNameChars]",'' -replace ' ',''
	[string]$appVersion = $appVersion -replace "[$invalidFileNameChars]",'' -replace ' ',''
	[string]$appArch = $appArch -replace "[$invalidFileNameChars]",'' -replace ' ',''
	[string]$appLang = $appLang -replace "[$invalidFileNameChars]",'' -replace ' ',''
	[string]$appRevision = $appRevision -replace "[$invalidFileNameChars]",'' -replace ' ',''

	## Build the Installation Name
	If (-not ($installName) ) {
		If ($appArch) {
			[string]$installName = $appVendor + '_' + $appName + '_' + $appVersion + '_' + $appArch + '_' + $appLang + '_' + $appRevision
		}
		Else {
			[string]$installName = $appVendor + '_' + $appName + '_' + $appVersion + '_' + $appLang + '_' + $appRevision
		}
	}
	[string]$installName = $installName.Trim('_') -replace '[_]+','_'

In Deploy-Application.ps1, I declare $installName and $installTitle in the ##* VARIABLE DECLARATION section.

What do you think?

**Comment by mmashwani** [comment]
Yeah, that shouldn't be a problem.

**Comment by mmashwani** [comment]
I pushed this change to the latest beta.

**Comment by That-Annoying-Guy** [comment]
Mi Mo,
we just ran into a small issue.
Can you change this:

	If (-not $installName) {
		If ($appArch) {
			[string]$installName = $appVendor + '_' + $appName + '_' + $appVersion + '_' + $appArch + '_' + $appLang + '_' + $appRevision
		}
		Else {
			[string]$installName = $appVendor + '_' + $appName + '_' + $appVersion + '_' + $appLang + '_' + $appRevision
		}
		[string]$installName = $installName.Trim('_') -replace '[_]+','_'
	}

To this ? :

	If (-not $installName) {
		If ($appArch) {
			[string]$installName = $appVendor + '_' + $appName + '_' + $appVersion + '_' + $appArch + '_' + $appLang + '_' + $appRevision
		}
		Else {
			[string]$installName = $appVendor + '_' + $appName + '_' + $appVersion + '_' + $appLang + '_' + $appRevision
		}
	}
	[string]$installName = $installName.Trim('_') -replace '[_]+','_'


Notice the last line is now outside the If statement.

**Comment by mmashwani** [comment]
Done
