### ISSUE TITLE
Logging and Popups broken in 3.6.8

### ISSUE THREAD

**Issue by gerane** [PSAppDeployToolkit/PSAppDeployToolkit#131]
The first issue I am seeing is with using a Custom Log Directory in the AppDeployToolkitConfig.xml. I just recently started to use the popups for specific types of Deployments. The problem I am seeing is the log created by the pop up is not getting placed in the correct directory. I used the $appname variable in my log path to clear up confusion when some of the logs created by some of my installers have generic names or a large number of logs. This way you could easily find all of the logs for a specific toolkit. 

EX: Path\to\logs\$envComputerName\$AppName
Show-InstallationPrompt is writing to Path\to\logs\$envComputerName

The newest problem I am now seeing is that all Packages are completing with exit code 0 in the Toolkit, but the Show-InstallationPrompt is completing with exit code 1618.

I removed the $AppName varaible from my log path to combine logs to see if that changed anything, but it is still showing errors with every install. Here is an example from one of my logs.

Toolkit Portion:
```
[Post-Installation] :: REM_RemoveProvisionedAppxPackages_EN_01 Installation completed with exit code [0].
```

Prompt Portion:
```
[Asynchronous] :: REM_RemoveProvisionedAppxPackages_EN_01  completed with exit code [1618].
```

I am not as concerned with the log directory. I can just remove the variable and have them all in one directory. I am looking through the main script to try to determine where this might be breaking. I am not as familiar with this area so it might take me a little while to go over it.

Command being executed
```powershell
Show-InstallationPrompt -Message "Installation of $installTitle has completed." -ButtonRightText 'OK' -Icon Information -NoWait -Timeout '20'
```

Here is more of the Log at the end of the script
```
[Post-Installation] :: Displaying custom installation prompt with the non-default parameters: [-NoWait:$true -ButtonRightText "OK" -Icon "Information" -Message "Installation of REM Remove Provisioned Appx Packages has completed." -Timeout 20].
[Post-Installation] :: REM_RemoveProvisionedAppxPackages_EN_01 Installation completed with exit code [0].
[Post-Installation] :: Function invoked with bound parameter(s): 

Parameter         Value                 
---------         -----                 
[-BalloonTipIcon] Info                  
[-BalloonTipText] Installation complete.
[Post-Installation] :: Display balloon tip notification with message [Installation complete.].
[Asynchronous] :: [App Deploy Toolkit Main] called with switch [-ShowInstallationPrompt].
[Asynchronous] :: Function invoked with bound parameter(s): 

Parameter          Value                                                              
---------          -----                                                              
[-ButtonRightText] OK                                                                 
[-Icon]            Information                                                        
[-Message]         Installation of REM Remove Provisioned Appx Packages has completed.
[-Timeout]         20 
[Asynchronous] :: Function invoked without any bound parameters.
[Asynchronous] :: Displaying custom installation prompt with the non-default parameters: [-ButtonRightText "OK" -Icon "Information" -Message "Installation of REM Remove Provisioned Appx Packages has completed." -Timeout 20].
[Asynchronous] :: Installation action not taken within a reasonable amount of time.
[Asynchronous] :: Function invoked without any bound parameters.
[Asynchronous] :: REM_RemoveProvisionedAppxPackages_EN_01  completed with exit code [1618].
[Asynchronous] :: Function invoked with bound parameter(s): 

Parameter         Value         
---------         -----         
[-BalloonTipIcon] Warning       
[-BalloonTipText]  not complete.
[Asynchronous] :: Display balloon tip notification with message [ not complete.].
```

**Comment by gerane** [comment]
I am thinking it is connected to -nowait and not Pressing OK on the popup. Am I misunderstanding how that is supposed to be used?

**Comment by mmashwani** [comment]
Well one of the changes I've made in the 3.6.8 beta is to make sure that the toolkit now only creates one main log. So the separate logs that were previously created when you executed dialog windows asynchronously will now write to the main log. You can see these log entries by looking for the different "Thread" id's in the CMTrace log type.

**Comment by gerane** [comment]
When I used $appname as the last log folder, the log for the prompt was now named properly, but in the parent directory instead of the $appname directory. So I was still seeing 2 logs.

**Comment by gerane** [comment]
Yeah, that is what is happening. If I click 'OK' everything finishes just fine.

If I let the prompt time out, it immediately errors with exit code 1618.

After looking into the error code I can see that it is being done when the prompt times out for Show-InstallationWelcome, but I did not see anything about show-installationprompt in the comments. My impression was that since this is a prompt to let the user know everything finished, passing it -nowait would allow the user to still know everything had finished, but without keeping the toolkit from finishing.

Is this proper functionality? I may just have to disable this prompt if that is the case.

**Comment by mmashwani** [comment]
Show-InstallationWelcome relies on Show-InstallationPrompt in the background to display the dialog window.

I think the -NoWait parameter is not doing what you are wanting to do in this case because you are also using the -TimeOut '20' parameter and that is taking precedence. Try without using the -TimeOut parameter and see if -NoWait works as expected then.

**Comment by gerane** [comment]
OK, I'll give that a try. Is the default timer 1hr 55min for that as well?

**Comment by mmashwani** [comment]
No, there should be no timeout in this instance because the -NoWait parameter should cause the prompt to open up in an asynchronous powershell.exe process which does not interrupt the execution of the main PowerShell script.

**Comment by gerane** [comment]
OK, now I understand then. I was hoping -nowait + -timeout would allow the
main script to continue while also putting a timeout on how long the prompt
would stay visible before auto closing.
