### ISSUE TITLE
Suggestion to welcome message title

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#132]
Hi,

I would like to suggest that title is configurable in AppDeployToolkitConfig.xml.
So that users could specify by them-self what to include in title and in which order.
So it could look like this in AppDeployToolkitConfig.xml:

\<Toolkit_WelcomeTitle>$appVendor $appName $appVersion $appLang $appArch $appRevision\</Toolkit_WelcomeTitle>

or one would want to change the order a bit:

\<Toolkit_WelcomeTitle>$appVendor $appName $appVersion $appArch $appLang\</Toolkit_WelcomeTitle>

or add own default prefix:

\<Toolkit_WelcomeTitle>CompanyName $appVendor $appName $appVersion\</Toolkit_WelcomeTitle>

This would make this nice deployment tool a lot more flexible.
And of course if variable is empty, then it shouldn't make unnecessary spaces in title.

**Comment by mmashwani** [comment]
If you use the latest 3.6.8 beta code, you can define $installTitle and $installName both in your DeployApplication.ps2 file and the toolkit will not overwrite it using it's own logic. I think I would rather leave it configurable via the PS1 file rather then the XML or perhaps add it to the XML in a future 4.0 release.
