### ISSUE TITLE
Need MSIInstallParams in XML to handle variables

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#133]
I think this can be done by changing this:

	#  Get MSI Options
	[Xml.XmlElement]$xmlConfigMSIOptions = $xmlConfig.MSI_Options
	[string]$configMSILoggingOptions = $xmlConfigMSIOptions.MSI_LoggingOptions
	[string]$configMSIInstallParams = $xmlConfigMSIOptions.MSI_InstallParams
	[string]$configMSISilentParams = $xmlConfigMSIOptions.MSI_SilentParams
	[string]$configMSIUninstallParams = $xmlConfigMSIOptions.MSI_UninstallParams
	[string]$configMSILogDir = $ExecutionContext.InvokeCommand.ExpandString($xmlConfigMSIOptions.MSI_LogPath)

To this:

	#  Get MSI Options
	[Xml.XmlElement]$xmlConfigMSIOptions = $xmlConfig.MSI_Options
	[string]$configMSILoggingOptions = $xmlConfigMSIOptions.MSI_LoggingOptions
	[string]$configMSIInstallParams = $ExecutionContext.InvokeCommand.ExpandString($xmlConfigMSIOptions.MSI_InstallParams)
	[string]$configMSISilentParams = $ExecutionContext.InvokeCommand.ExpandString($xmlConfigMSIOptions.MSI_SilentParams)
	[string]$configMSIUninstallParams = $ExecutionContext.InvokeCommand.ExpandString($xmlConfigMSIOptions.MSI_UninstallParams)
	[string]$configMSILogDir = $ExecutionContext.InvokeCommand.ExpandString($xmlConfigMSIOptions.MSI_LogPath)

**Comment by That-Annoying-Guy** [comment]
Err... scratch that. The variables I want to use are declared AFTER the XML file is read.
This would have to be handled inside Execute-MSI.

Can this be done?

**Comment by mmashwani** [comment]
You could just re-read the variable from the XML file using the code you suggested above before calling Execute-MSI.

**Comment by That-Annoying-Guy** [comment]
FYI: testing your idea at the end of AppDeployToolkitExtensions.ps1.
It should work.

**Comment by That-Annoying-Guy** [comment]
Works! Thank you! Close it.

	MSI (s) (90:80) [13:39:58:427]: Command Line: ALLUSERS=1 TRANSFORMSSECURE=1 ROOTDRIVE=C:\ ARPNOREPAIR=1 REBOOT=ReallySuppress APPLANG=en CURRENTDIRECTORY=C:\Users\<UserName>\AppData\Local\Temp\Deploy-Application_v1r1\Files CLIENTUILEVEL=3 CLIENTPROCESSID=1092
