### ISSUE TITLE
Get-PendingReboot function should test for SCCM version

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#134]
We haven't gone SCCM2012 (or CM201511) yet but Get-PendingReboot sees that as an error:

	[01-28-2016 12:14:35.352] [Post-Installation] [Get-PendingReboot] :: Failed to get IsSCCMClientRebootPending. 
	Error Record:
	-------------

	Message        : Invalid namespace 
	InnerException : 

	FullyQualifiedErrorId : InvokeWMIManagementException,Microsoft.PowerShell.Commands.InvokeWmiMethod
	ScriptStackTrace      : at Get-PendingReboot<Process>, 
							D:\BK\Projects\SignetChecker_v1r1\AppDeployToolkit\AppDeployToolkitMain.ps1: 
							line 9886
							at <ScriptBlock>, <No file>: line 1

	PositionMessage : At D:\BK\Projects\SignetChecker_v1r1\AppDeployToolkit\AppDeployToolkitMain.ps1:9886 
					  char:40
					  +             [psobject]$SCCMClientRebootStatus = Invoke-WmiMethod -ComputerName 
					  $ComputerN ...
					  +    
					  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




	[01-28-2016 12:14:35.358] [Post-Installation] [Get-PendingReboot] :: Pending reboot status on the local computer [<Censored>]: 


	IsFileRenameRebootPending    : False
	IsWindowsUpdateRebootPending : False
	ComputerName                 : <Censored>
	LastBootUpTime               : 28/01/2016 10:10:27 AM
	IsCBServicingRebootPending   : False
	IsSCCMClientRebootPending    : 
	IsSystemRebootPending        : False
	ErrorMsg                     : {Failed to get IsSCCMClientRebootPending: Invalid namespace }
	PendingFileRenameOperations  : 

I'm proposing that not having SCCM 2012 installed should not be treated as an error and we should be testing the SCCM client version before checking the sccm2012 class for **DetermineIfRebootPending**

According to https://technet.microsoft.com/en-us/library/cc181369.aspx
This is the client version:

	[Version]$SCCMClientVersionSMS = $(Get-WmiObject -ComputerName $ComputerName -NameSpace 'ROOT\ccm' -Class 'SMS_Client' -ErrorAction 'Stop').ClientVersion 
	# SCCM2007 Returns 4.00.6487.2607
	# SCCM2012 Returns 5.00.????
	# SCCM201511 Returns ???


And so you could add this to Get-PendingReboot:

	Try {
		[Version]$SCCMClientVersionSMS = $(Get-WmiObject -ComputerName $ComputerName -NameSpace 'ROOT\ccm' -Class 'SMS_Client' -ErrorAction 'Stop').ClientVersion
	} Catch {
		[Version]$SCCMClientVersionSMS = 0.0.0.0
	}
	
	If ($SCCMClientVersionSMS -gt '5.0') {
		#Read SCCM2012 Class for DetermineIfRebootPending 
	} Else {
		"SCCM not installed or version older than 2012"
	}	

What do you think?

**Comment by mmashwani** [comment]
That is a great suggestion and thanks for providing example code. I will work on getting this integrated.

**Comment by mmashwani** [comment]
Let me know if you figure out the sccm client version for SCCM 2016. I don't know if you have the technical preview installed or not...

**Comment by That-Annoying-Guy** [comment]
BTW: It's called CM1511 (CM + YYMM) not SCCM 2016 

and it looks like version numbers are going to be VERY close to 2012's
http://anoopcnair.com/2015/12/08/download-and-install-sccm-configmgr-1511-rtm-version-remember-not-sccm-2016/

So I'm guessing it's going to be version 5.0.8???.??? for the CM1511 client

**Comment by mmashwani** [comment]
I just pushed a commit to resolve this issue:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/e0eb64ea3b5f2aa2aba6142e9aa0d29c04e0944e

It is a slightly different method than suggested above. Please test and let me know if it's working as expected.

**Comment by That-Annoying-Guy** [comment]
It works! thank you!
