### ISSUE TITLE
Set-DeferHistory does not write Defer Times Remaining in log.

### ISSUE THREAD

**Issue by FlashGordon7** [PSAppDeployToolkit/PSAppDeployToolkit#135]
The Function Set-DeferHistory does not write Defer Times Remaining.
`Write-Log -Message "Set deferral history: [DeferTimesRemaining = $deferTimes]." -Source ${CmdletName}`
It should be:
`Write-Log -Message "Set deferral history: [DeferTimesRemaining = $deferTimesRemaining]." -Source ${CmdletName}`

**Comment by mmashwani** [comment]
Thanks for reporting that. Fixed in commit:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/cfe15ac11552cf50056c2e5e6ac9102e8a8cd4f0
