### ISSUE TITLE
Get-RegistryKey returns $null when DWORD value is Zero(0)

### ISSUE THREAD

**Issue by LMCO-psadt-devs** [PSAppDeployToolkit/PSAppDeployToolkit#136]
When calling Get-RegistryKey -Key _SomeKey_ -Value _SomeValue_, where _SomeValue_ is a REG_DWORD, the function returns $null if the actual value in the registry is set to 0 (Zero).

_(AppDeployToolkitMain: Line 3491)_
`If ($regKeyValue) { Write-Output -InputObject $regKeyValue } Else { Write-Output -InputObject $null }`

if $regKeyValue is a `DWORD/QWORD` and actually 0 ... it should probably return 0, not null.

**Comment by mmashwani** [comment]
Thanks for pointing that out. The comparison should actually be like this for it to work correctly:
```If ([string]$regKeyValue) { Write-Output -InputObject $regKeyValue } Else { Write-Output -InputObject $null }```

**Comment by mmashwani** [comment]
Resolved in commit:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/cfe15ac11552cf50056c2e5e6ac9102e8a8cd4f0

**Comment by LMCO-psadt-devs** [comment]
After rethinking this ... the function should only resolve to $null if the registry value does not exist.

For example, having a REG_SZ value set to "" (empty string) is different than not having an entry present at all.

I replaced the affected code with `Write-Output $regKeyValue` to accomplish this.

**Comment by mmashwani** [comment]
I see your point. I just pushed some updates to the Get-RegistryKey function so that it only returns $null if the key does not exist, if there are no values under the key, or if the requested value does not exist.

Please test and let me know if it's working as expected now.
