### ISSUE TITLE
No balloon tip notification if running PowerPoint in fullscreen mode

### ISSUE THREAD

**Issue by FlashGordon7** [PSAppDeployToolkit/PSAppDeployToolkit#137]
I think we should have a check in the balloon tip notification function so that it does not display anything if user is running PowerPoint in fullscreen mode.

**Comment by amotaz** [comment]
fixed in latest push, please test if you can

**Comment by FlashGordon7** [comment]
I have done some testing and it seem to work fine, Thanks.
