### ISSUE TITLE
Get-HardwarePlatform Error on Surface Devices

### ISSUE THREAD

**Issue by dmcnaughton** [PSAppDeployToolkit/PSAppDeployToolkit#138]
The Get-HardwarePlatform function returns Virtual for Microsoft Surface devices. The offending line is `ElseIf ($hwMakeModel.Manufacturer -like '*Microsoft*') { $hwType = 'Virtual:Hyper-V' }`
I have been able to resolve it by replacing the above line with the below line.

`ElseIf ($hwMakeModel.Manufacturer -like '*Microsoft*' -and (-not $hwMakeModel.Model -like "*Surface*")) { $hwType = 'Virtual:Hyper-V' }`

Below is a link to the output of `gwmi win32_computersystem | Select *` performed on a Microsoft Surface Pro 3 device for further debugging uses:
http://pastebin.com/f5XewBhX

**Comment by amotaz** [comment]
thanks for the heads up, I'll take a look. I have access to a surface I can test with.

**Comment by amotaz** [comment]
ok, pushed the change to the latest beta. Please test and confirm if you can.

**Comment by dmcnaughton** [comment]
I did a test on my Surface here and it worked fine. Thanks for the quick response!
