### ISSUE TITLE
Remove-MsiApplication -FilteredApplication causes "unable to index into an object type system.char" error

### ISSUE THREAD

**Issue by jeffgorrell** [PSAppDeployToolkit/PSAppDeployToolkit#139]
InnerException: System.Management.Automation.Runtime.Exception: Method invocation failed because [System.Char] doesn't contain a method named 'get_Item'.

Seems to always error on "If ($Filter[0][2] -eq 'RegEx'"

Usage to replicate fault is something like:
Remove-MsiApplication -Name "Java 8 Update" -FilteredApplication @('Is64BitApplication', '$true', 'Exact')

App Deploy Toolkit Main script version is 3.6.8

**Comment by mmashwani** [comment]
$true should not be in single quotes. We want to refer to boolean true in this comparison and the single quotes around it forces PS to treat it as text.

Also, look at the notes and examples for the function. If you are only using a single filter for the -FilterApplication or -ExcludeFromUninstall parameters, then you need to prepend ,, before the filter. This is necessary because of how PS automatically expands arrays and we want to make sure that we pass an array to the function or it will not work.

Command should look like this. Does this work without error?
```
Remove-MsiApplication -Name "Java 8 Update" -FilteredApplication @(,,@('Is64BitApplication', $true, 'Exact'))
```

**Comment by Latupho** [comment]
I'm not 100% sure if this issue, I have at hands, is the same, but it looks like it. I'm on version 3.6.7 and I'm running `Remove-MSIApplications -name 'Navisworks'`. The error I get from the uninstall log is the following (See attached log file.)
[Autodesk_Naviswork_2016_EN_01_PSAppDeployToolkit_Uninstall.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/114108/Autodesk_Naviswork_2016_EN_01_PSAppDeployToolkit_Uninstall.txt)

When I do a debug on line 2471 = `Execute-MSI @ExecuteMSISplat` I get the following error at line 2464, where PS ISE have selected this variable `$removeMSIApplication`. Error message I get is the following:

> Execute-MSI : Cannot validate argument on parameter 'Path'. The "($_ -match $MSIProductCodeRegExPattern) -or ('.msi','.msp' -contains [IO.Path]::GetExtension($_))" validation script
>  for the argument with value "Autodesk Navisworks 2016 Exporters - 64 bit - English Language Pack (SP1)" did not return a result of True. Determine why the validation script failed,
>  and then try the command again.
> At C:\Users\dli\Desktop\Autodesk Naviswork\2016.0.0.F\1\SCCM\AppDeployToolkit\AppDeployToolkitMain.ps1:2471 char:18
> +                     Execute-MSI @ExecuteMSISplat
> +                                 ~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Execute-MSI], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationError,Execute-MSI

And about here, I can't fully follow what it talks about, "Cannot validate argument on parameter 'Path'.".

Is this a new issue or the same?

**Comment by mmashwani** [comment]
@Latupho 
That is a different issue. Create a new issue for it.
