### ISSUE TITLE
web site is down 

### ISSUE THREAD

**Issue by scotty92fr** [PSAppDeployToolkit/PSAppDeployToolkit#14]
the web site http://psappdeploytoolkit.com/ is down with "Internal Server Error"

**Comment by mmashwani** [comment]
I can access it just fine.

**Comment by scotty92fr** [comment]
since yesterday evening (from my side) I cannot access, I access to the github repository but not the site.

I tried with 3 PC on 2 Location an 3 diffèrent network and / or proxy and from 3 different browser.

That is all I can say :(
![capture](https://cloud.githubusercontent.com/assets/6825089/7250134/ffb134ae-e81f-11e4-8a0d-cd4ed6b249ea.PNG)

**Comment by mmashwani** [comment]
Yeah, seeing the same error once I logged out of the site. I must have been loading a cached version of the site.

**Comment by sintaxasn** [comment]
Seems to be a glitch with the forum component. I've disabled the forums while we investigate, but the site is back up and working.

**Comment by mmashwani** [comment]
Forums are back up and running. Closing issue.
