### ISSUE TITLE
$envLogonServer contains LogonServerName.full.dns.path.com instead of LogonServerName

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#149]
The code in AppDeployToolkitMain.ps1 (v3.6.8) currently appends a full DNS path to the value of $env:LOGONSERVER

So instead of getting **\\LogonServerName** or even **LogonServerName**
I get **LogonServerName.full.dns.path.com**

Is this a bug or a feature?

**Comment by mmashwani** [comment]
I designed it to be that way.
