### ISSUE TITLE
v3.6.8 nitpics

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#150]
## Write-Log needs example for -LogOnly

```
.EXAMPLE
    Write-Log "This message will ONLY show in the logs" -WriteHost $false
```

---
## Test-ServiceExists -Paththru give WAY more info but you MUST KNOW the property name

Test-ServiceExists needs an example in the comments to show how get the full list:

```
.PARAMETER PassThru
    Return the WMI service object.
    Use the following to obtain list of properties that are available:
    Test-ServiceExists -Name <ServiceName> -PassThru | select *
```

---
## Test-ServiceExists should explain service status vs. state

Source:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa394418%28v=vs.85%29.aspx

service status vs. state

State
    Data type: string
    Access type: Read/write

```
Current state of the base service.

The values are:
"Stopped"
"Start Pending"
"Stop Pending"
"Running"
"Continue Pending"
"Pause Pending"
"Paused"
"Unknown"
```

Status
    Data type: string
    Access type: Read-only

```
Current status of the object. Various operational and nonoperational statuses can be defined. 
Operational statuses include: "OK", "Degraded", and "Pred Fail" (an element, such as a SMART-enabled 
hard disk drive, may be functioning properly but predicting a failure in the near future). 
Nonoperational statuses include: "Error", "Starting", "Stopping", and "Service". 
The latter, "Service", could apply during mirror-resilvering of a disk, reload of a user 
permissions list, or other administrative work. Not all such work is online, yet the 
managed element is neither "OK" nor in one of the other states.

The values are:
"OK"
"Error"
"Degraded"
"Unknown"
"Pred Fail"
"Starting"
"Stopping"
"Service"
```

---
## PSADT's PowerShell v2.0-ism in Get-PendingReboot function

If you run this in PS2:

```
[boolean]$IsSccmClientNamespaceExists = [boolean](Get-WmiObject -Namespace 'ROOT\CCM\ClientSDK' -List -ErrorAction 'Stop' | Where-Object { $_.Name -eq 'CCM_ClientUtilities' })
```

you'll see this:

```
Invalid namespace 
At :line:1 char:51
+ [boolean]$IsSccmClientNamespaceExists = [boolean](G <<<< et-WmiObject -Namespace 'ROOT\CCM\ClientSDK' -List -ErrorAction 'Stop' | Where-Object { $_.Name -eq 'CCM_ClientUtilities' })
```

In anything higher, you don't see any RED on the screen

```
Try {
    [boolean]$IsSccmClientNamespaceExists = [boolean](Get-WmiObject -Namespace 'ROOT\CCM\ClientSDK' -List -ErrorAction 'Stop' | Where-Object { $_.Name -eq 'CCM_ClientUtilities' })
} catch {
    Write-Host "boom"
}
```

This returns $false in PS2 but I'm not sure if you'll feel comfortable with it:

```
[boolean]$IsSccmClientNamespaceExists = [boolean](Get-WmiObject -Namespace 'ROOT\CCM\ClientSDK' -List -ErrorAction 'SilentlyContinue' | Where-Object { $_.Name -eq 'CCM_ClientUtilities' })
```

Not a big deal but I thought you should know.

---
## We have $envUserStartMenuPrograms but not $envCommonStartMenuPrograms

Instead we have the uber descriptive $envCommonPrograms (Is that the common folder in ProgramFiles? No that's $envCommonProgramFiles)
Let's end the confusion and Change:

```
[String]$envCommonPrograms  = [Environment]::GetFolderPath('CommonPrograms')    #C:\ProgramData\Microsoft\Windows\Start Menu\Programs
```

to: 

```
[String]$envCommonStartMenuPrograms     = [Environment]::GetFolderPath('CommonPrograms')    #C:\ProgramData\Microsoft\Windows\Start Menu\Programs
```

---
## Get-LoggedOnUser needs more in .NOTES

What is IsLocalAdmin?   A Local account that is member of the Administrators group or _THE_ real Local Administrator account that get created upon initial install of Windows?

---
## Description of IsActiveUserSession property should say:

```
If a console user exists, then that will be the active user session.
If no console user exists but users are logged in, such as on terminal servers, then the first logged-in non-console user that {has} {ConnectState=} 'Active' or 'Connected' is the active user.
```

---
## PSADT's QueryUser class to work under PowerShell 2.0 

I can't get PSADT's QueryUser class to work under PowerShell 2.0 
Not a big deal but I thought you should know.

**Comment by mmashwani** [comment]
Regarding the issue with QueryUser class not working under PS 2.0...I have successfully tested it on systems with PS 2.0. Can you get me the begging of the log file on a system where it does not work for you? Is there some kind of error that is generated or does it simply not return any data?

**Comment by mmashwani** [comment]
@That-Annoying-Guy Please provide any information you can as per the above request.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/v3-6-8-nitpics/1229
