### ISSUE TITLE
Issue with not detected installed MSI product

### ISSUE THREAD

**Issue by madsps** [PSAppDeployToolkit/PSAppDeployToolkit#153]
Wrapper won't remove MSI if DisplayName contains one of the following "Hotfix", "Cumulative Update", "Security Update" or KB.

For example I have one MSI product installed with DisplayName="My Application v5 Hotfix 10". In this case wrapper will skip this product because of the following code: 

```
If (-not $IncludeUpdatesAndHotfixes) {
    If ($regKeyApp.DisplayName -match '(?i)kb\d+') { Continue }
    If ($regKeyApp.DisplayName -match 'Cumulative Update') { Continue }
    If ($regKeyApp.DisplayName -match 'Security Update') { Continue }
    If ($regKeyApp.DisplayName -match 'Hotfix') { Continue }
 }
```

As far as I can see the `Get-InstalledApplication` function has `IncludeUpdatesAndHotfixes` parameter (switch) to disable such behavior. But, unfortunately, there is no way to pass this parameter directly to the `Execute-MSI` function.

Is it possible to fix this?

**Comment by amotaz** [comment]
I've added the code for this in the latest push. 
Both Remove-MSIApplications and Execute-MSI now have the IncludeUpdatesAndHotfixes Parameter
