### ISSUE TITLE
DeferHistory

### ISSUE THREAD

**Issue by superz202** [PSAppDeployToolkit/PSAppDeployToolkit#156]
Hi,

I understand there is an issue on the DeferHistory in version 3.6.2 and it is fixed in version 3.6.4.
Registry key for deferrals not being correctly set#31

Is it possible to let me know what is needed to resolve this issue? I have mulitples packages in production that is built base on version 3.6.2 and if i can fixed the particular area that caused this issue, it will be easier.

Thanks and regards
Superz202

**Comment by mmashwani** [comment]
Just copy the Set-DeferHistory and Get-DeferHistory functions from the latest version of the toolkit to your 3.6.2 version of the toolkit.

**Comment by superz202** [comment]
hi, I compared the 2 functions from version 3.6.2 and 3.6.8 and both look the same to me. Can find any differences in the 2 functions.

Is there anything missed out?

**Comment by superz202** [comment]
Sorry ignore my previous comment
