### ISSUE TITLE
Execute-ProcessAsUser wait bug

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#157]
Hi,

I would like to report a bug in Execute-ProcessAsUser function.

If I use like this
1) Run Execute-ProcessAsUser -Wait
2) Run Execute-ProcessAsUser

This works fine.
BUT!

If I use like this
1) Run Execute-ProcessAsUser
2) Run Execute-ProcessAsUser -Wait

Then it hangs  on first invocation and in log it shows "waiting for scheduled task to complete".
Expected behavior is that code should run first invocation and let it execute in background and it should then stop on second invocation and wait for it to complete.

**Comment by mmashwani** [comment]
I have a forthcoming update that should resolve this issue. I will update this thread once I commit.

**Comment by seanlillis** [comment]
This issue is no longer reproducible so looks to have been resolved in a previous commit.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
