### ISSUE TITLE
Typo in Get-HardwarePlatform Function

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#159]
There is a typo in the Get-HardwarePlatform Function line 1786
`$hwBios = Get-WmiObject -Class 'Win32_BIOS' -ErrorAction 'Stop' | Select-Object -Property 'Version', 'SerialNnumber'`

SerialN**n**umber should be SerialNumber

**Comment by amotaz** [comment]
Fixed in 3.6.9 thanks for the find.
