### ISSUE TITLE
Set-RegistryKey delete spaces in key name when variables are used with the key parameter.

### ISSUE THREAD

**Issue by alears01** [PSAppDeployToolkit/PSAppDeployToolkit#160]
Ex:
[string]$appVendor = 'Adobe'
[string]$appName = 'Flash Player'
[string]$appVersion = '21.0.0.182'

Set-RegistryKey -Key "HKEY_LOCAL_MACHINE\SOFTWARE\FSTQ\$Appvendor\$appName" -Name 'Version' -Value "$AppVersion" -Type String

See result in Registry here:
![image](https://cloud.githubusercontent.com/assets/18037786/13999870/c289670a-f114-11e5-94fd-7a41fa3d9306.png)

**Comment by amotaz** [comment]
$appName is a variable used in the toolkit for storing the application name and it is sanitized of special characters including spaces for use in other places in the toolkit. If you use a different variable name (one not used by the toolkit) you wont have this issue.

**Comment by alears01** [comment]
Ok thanks a lot.

2016-05-10 14:08 GMT-04:00 amotaz <notifications@github.com>:

> $appName is a variable used in the toolkit for storing the application
> name and it is sanitized of special characters including spaces for use in
> other places in the toolkit. If you use a different variable name (one not
> used by the toolkit) you wont have this issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/160#issuecomment-218241680>
>



-- 

Alexandre Arsenault
alexandre.arsenault@gmail.com
