### ISSUE TITLE
Show-InstallationRestartPrompt should be more user friendly

### ISSUE THREAD

**Issue by khaffner** [PSAppDeployToolkit/PSAppDeployToolkit#161]
The buttons "Restart Now" and "Restart Later" should switch places. In my experience, the "safe" option in Windows dialogue boxes is the choice on the right.

I would also like a parameter to change the repetition delay between "Restart Later" clicks. The default now seems to be a few minutes, and that behavior is annoying to end users who really can't restart at the time. I know I can edit the AppDeployToolkitConfig.xml, but I feel this should have it's own parameter. I suggest "RestartPromptDelay" followed by the number of seconds. 
Show-InstallationPrompt handles this nicely with the Defer option.

**Comment by EmmanuelTsouris** [comment]
Interesting thought. Cancel buttons are usually on the right, and according to the [Microsoft Design Guidelines for Dialog Boxes](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742499(v=vs.85).aspx), "When assigning order, assume that users display dialog boxes for their intended purpose; so, for example, users display choice dialogs to make choices, not to review and click Cancel." 

So is the intended purpose of the Show-InstallationRestartPrompt to restart now or later? 
Would it be reasonable to assume the intent is to restart now, unless there's a compelling reason to postpone (equivalent in concept to a cancel)? Maybe an alternative might be to have a flexible option to reverse the order when needed?

**Comment by khaffner** [comment]
The intended purpose is of course to restart the computer. As a sysadmin, I would prefer it happens right away. But that is a bad experience for the end user, so I would like to give them the option to defer the restart. It is often no problem to defer the restart for several hours or days. But some users practically never restart their computer unless they are forced to. This would be nice at the end of some of my deployments:
Show-InstallationRestartPrompt -AllowDefer -DeferDays 3

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-installationrestartprompt-should-be-more-user-friendly/1238

**Comment by luki1412** [comment]
Partially implemented in #577 
Restart later has been renamed in one of the previous version due to it being misleading. It only minimizes the window. We will add more options in v4

**Comment by mjr4077au** [comment]
Our v3 dialogs are now on feature lock, with all focus going to the new v4 dialogs. If there's any comments or suggestions for the v4 dialogs, feel free to create a new issue.
