### ISSUE TITLE
Close open applications has faulty logic 

### ISSUE THREAD

**Issue by LMCO-psadt-devs** [PSAppDeployToolkit/PSAppDeployToolkit#162]
The `Show-InstallationWelcome` function determines the current running process associated with the `$CloseApps` list.
It then creates the `$runningProcessDescriptions`and passes it to `Show-WelcomePrompt` (`-ProcessDescriptions`)

The `Show-WelcomePrompt` populates the list of applications to close (`$listBoxCloseApps`) during the creation of the form.

*_Here lies the problem *_... 
    This dialog could remain open for an extended period of time, during which applications that are required to be closed (`$CloseApps`/`$ProcessDescriptions`) could be started/stopped.
    This would present inaccurate data to the user.
    Worse than that ... if an application that was identified to be closed (`Show-InstallationWelcome -CloseApps`) was opened while waiting on input from the user, it would never be added to the `$listBoxCloseApps`ListBox and NEVER be closed by `Show-InstallationWelcome` after the `Show-WelcomePrompt` dialog closed.

This functionality needs to be more dynamic to:
- Indicate all of the open applications that will need to be closed (in real-time ... not from a static list)
- Actually close all of the applications in the `-CloseApps` parameter (if the `Show-WelcomePrompt` determines that apps need to close).

This could be accomplished by dynamically updating the ListBox whenever the `$timer_tick` event is fired (when the `$labelCountdown` is updated).
If once a second is _too taxing_ on the system, create a new timer event that fires every x seconds (make it configurable, default to 5?).

Finally, in the "_Close Programs_" button click event:
- Verify that the list of applications to close in the ListBox was accurate at the time it was clicked.
- If it was not accurate ... repopulate the ListBox and inform the user that the list has changed since they elected to "_Close Programs_"

**Comment by webbird** [comment]
This may be the reason for a strange behaviour a customer reported: Sometimes it happens that the list of apps to close is empty. I'm still waiting for logs so I have no more info at the moment, just a screenshot of the empty app list.

**Comment by wala0003** [comment]
I modified the existing code to do just this and submitted it in a different issue.

**Comment by amotaz** [comment]
I like this suggestion, but it will require a breaking change to Show-WelcomePrompt. I'm going to wait to add this to the next major version.
