### ISSUE TITLE
Error Test-MSUpdates with KB2919355

### ISSUE THREAD

**Issue by Reclad** [PSAppDeployToolkit/PSAppDeployToolkit#164]
Hi,

When i try to install KB2919355 (Update 1) in Windows 8.1 Computer, Test-MSUpdates detect it but it's not true. ("Regex" detect it but for another KB because it appear in the description of KB2961858.)

<img width="974" alt="capture" src="https://cloud.githubusercontent.com/assets/350119/14569804/2d64f880-0341-11e6-95e4-82158f7c3459.PNG">

> [Installation] :: Check if Microsoft Update [KB2919355] is installed. Test-MSUpdates  15/04/2016 19:26:37 252 (0x00FC)
> [Installation] :: Discovered the following Microsoft Update: 
> 
> Title       : Mise à jour de sécurité pour Windows 8.1 pour les systèmes x64 (KB2961858) sans KB2919355
> Date        : 15/04/2016 16:07:02
> Operation   : Installation
> Status      : Successful
> Description : Un problème de sécurité qui pourrait avoir un impact sur votre système a été identifié dans un produit 
>               logiciel Microsoft. Vous pouvez renforcer la protection de votre système en installant cette mise à jour 
>               de Microsoft. Pour consulter la liste complète des problèmes résolus par cette mise à jour et en savoir 
>               plus, reportez-vous à l'article correspondant de la Base de connaissances Microsoft. Une fois la mise à 
>               jour installée, vous serez peut-être amené à redémarrer l’ordinateur.
> 
>   Test-MSUpdates  15/04/2016 19:26:37 252 (0x00FC)
> [Installation] :: Microsoft Update [KB2919355] is installed.  Test-MSUpdates  15/04/2016 19:26:37 252 (0x00FC)
> [Installation] :: KB Number [KB2919355] is already installed. Continue... Install-MSUpdates   15/04/2016 19:26:37 252 (0x00FC)

Thanks ! (Excuse my english)

**Comment by amotaz** [comment]
I'm probably going to add this code, however there is one issue. I have some machines here which have Definition updates for windows defender and those do not use Parentheses. I'm thinking for the toolkit, that case isn't important, but we'll need a way to keep people informed of the issue. 
I'll let you know when I push the change. Thanks for the find.

**Comment by amotaz** [comment]
Ok, I've pushed the change. Please let me know how your testing goes.
