### ISSUE TITLE
Error 1624 when using Execute-MSI with Parameters TARGETDIR="$Env:programfiles\..."

### ISSUE THREAD

**Issue by Sevenon7** [PSAppDeployToolkit/PSAppDeployToolkit#165]
Hi,

When attempting to use the TARGETDIR property to specify an installation directory, the installer keeps failing w/ an error code of 1624 despite there are no TRANSFORMS. Once the TARGETDIR property is removed the install goes through successfully.

Logs are available upon request.

Cheers.

**Comment by Sevenon7** [comment]
[python-3.4.4.amd64_Install.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/222432/python-3.4.4.amd64_Install.txt)

**Comment by Sevenon7** [comment]
[PythonSoftwareFoundation_Python_3.4.4_x86x64_EN_01_PSAppDeployToolkit_install.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/222433/PythonSoftwareFoundation_Python_3.4.4_x86x64_EN_01_PSAppDeployToolkit_install.txt)

**Comment by dilorenzo1987** [comment]
How do you pass that? Using "-AddParameters?"

**Comment by dilorenzo1987** [comment]
Can you please show me your deploy-application.ps1

**Comment by Sevenon7** [comment]
![image](https://cloud.githubusercontent.com/assets/5060598/15157973/c00c919c-16a2-11e6-9ab6-c3b11d19a6aa.png)

**Comment by Sevenon7** [comment]
I also tried using the -AddParameters option but the results were the same.

**Comment by amotaz** [comment]
can you please try this:
'REBOOT=ReallySuppress /QN ALLUSERS=1 TARGETDIR="$($Env:programfiles\Cygwin"'

**Comment by Sevenon7** [comment]
No luck unfortunately. Getting "MSI (s) (50:2C) [11:56:47:392]: Product: Python 3.4.4 (64-bit) -- Error 1606. Could not access network location $($Env:programfiles)\Cygwin." now.

**Comment by cyborgrd** [comment]
Try please

-Parameters "REBOOT=ReallySuppress /QN ALLUSERS=1 TARGETDIR=`"$env:programfiles\cygwin\`""

**Comment by Sevenon7** [comment]
@cyborgrd that worked! Interesting it took the grave accent mark vs the apostrophe.

**Comment by Sevenon7** [comment]
thank you!

**Comment by cyborgrd** [comment]
i had the same problem. MSI don't accepts paths without quotas if the path contains a space.  You can also use following

-Parameters "REBOOT=ReallySuppress /QN ALLUSERS=1 TARGETDIR=""$env:programfiles\cygwin\"""

but with the grave mark it looks better
