### ISSUE TITLE
Custom icon in taskbar

### ISSUE THREAD

**Issue by foleysteven** [PSAppDeployToolkit/PSAppDeployToolkit#168]
When supplying a custom AppDeployToolkitLogo.ico icon file, it is applied to the window/dialog, but not to the taskbar. In Windows 7 and newer, with the taskbar buttons configured to combine (which is default), the custom icon is not applied to the taskbar.

I added the following code to fix the situation.
To the UiAutomation class of AppDeployToolkitMain.cs:

```
[DllImport("shell32.dll", CharSet = CharSet.Auto, SetLastError = false)]
public static extern int SetCurrentProcessExplicitAppUserModelID([MarshalAs(UnmanagedType.LPWStr)] string AppID);
```

To AppDeployToolkitMain.ps1:
`[PSADT.UiAutomation]::SetCurrentProcessExplicitAppUserModelID($appDeployToolkitName)`

I was not sure the best placement for the code in AppDeployToolkitMain.ps1, but I added it just before this comment: "If the ShowInstallationPrompt Parameter is specified, only call that function." Also the function only works on Windows 7 and newer, so it should probably be wrapped in some OS version detection code. And obviously the pinvoke signature could be moved to a more appropriate class.

Here is more info on the SetCurrentProcessExplicitAppUserModelID function:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd378422%28v=vs.85%29.aspx

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/custom-icon-in-taskbar/1233

**Comment by mjr4077au** [comment]
Thank you for your suggestion, I've implemented this in our v4 branch which is due for a preview release soon!
