### ISSUE TITLE
Common Programs variable

### ISSUE THREAD

**Issue by foleysteven** [PSAppDeployToolkit/PSAppDeployToolkit#169]
PSADT v3.6.8 added a variable for "Common Programs" as $envCommonPrograms. A similar user-based variable already existed and is named $envUserStartMenuPrograms. I think the $envCommonPrograms variable should be (re)named $envCommonStartMenuPrograms. $envCommonPrograms is an ambiguous name and is not consistent with the name used for the user based variable.

**Comment by amotaz** [comment]
Change pushed, thank you for the suggestion.
