### ISSUE TITLE
Running Show-InstallationWelcome with -BlockExecution parameter doesn't always unblock applications once installation is completed

### ISSUE THREAD

**Issue by Taranis1** [PSAppDeployToolkit/PSAppDeployToolkit#170]
We have started using the PSAppDeployToolkit recently and have run into a few snags when using the -BlockExecution parameter.  When installation completes in some instances, the blocked apps remain blocked.  We need to manually relaunch the deployment on the affected computer in order for the apps to unblock properly.

Anything that I could do to stop this behavior from happening?

Thanks!

**Comment by amotaz** [comment]
Hi Taranis,
When you run into this issue again, can you please provide some log files. We're not able to reproduce this issue.

**Comment by amotaz** [comment]
Have you been able to produce a log for this issue Taranis1 ?
