### ISSUE TITLE
Show-InstallationPrompt Button Text Removes Ampersand

### ISSUE THREAD

**Issue by bmkaiser** [PSAppDeployToolkit/PSAppDeployToolkit#172]
When using an ampersand (&) within the value of button text, the ampersand is removed. This seems to be the only reserved character that this happens to. I tested dollar ($), hash (#), percent (%) and tick (`) and they all appeared as expected.

```powershell
Show-InstallationPrompt -ButtonMiddleText 'Uninstall & Continue'
```
![no ampersand](https://cloud.githubusercontent.com/assets/5446414/14918051/ee133a8e-0def-11e6-8572-60a7e06b58ba.jpg)

**Comment by LMCO-psadt-devs** [comment]
The single ampersand is dedicated to underlining.
Use ... `Show-InstallationPrompt -ButtonMiddleText 'Uninstall && Continue' ` instead

**Comment by bmkaiser** [comment]
That did the trick. Thank you, @LMCO-psadt-devs
