### ISSUE TITLE
Copy-File Doesn't Allow for Wildcards in -Destination Path

### ISSUE THREAD

**Issue by bmkaiser** [PSAppDeployToolkit/PSAppDeployToolkit#175]
When looking to copy a file to a directory that doesn't have a known name, using a wildcard returns an error "Illegal characters in path.".

``` powershell
Copy-File -Path "patterns.ini"  -Destination "$installDir\*.default\adblockplus"
```

In this example, the Firefox profile folder name is different for each user profile. This issue can be worked around by storing the results of Get-Item in a variable and then using the variable in place of the wildcard folder.

**Comment by Latupho** [comment]
What about doing this:
`Copy-File -Path "patterns.ini"  -Destination "$((Get-ChildItem -Path "$installDir\*.default\adblockplus" -Directory | Get-Item).fullname)"` ?

As I see it, it will give the same result...

**Comment by bmkaiser** [comment]
I ended up doing something similar to this, but hadn't considered putting the Get-Item as part of the Destination argument. I think I ended up storing it in a variable seperately.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/copy-file-doesnt-allow-for-wildcards-in-destination-path/1237

**Comment by mjr4077au** [comment]
Using wildcards in the Destination parameter is quite dangerous as you have no control or knowledge ahead of time about the expected outcome. The native PowerShell cmdlets don't support this for this reason, and regrettably neither will we.
