### ISSUE TITLE
All versions (including 3.6.8) - sits in background for Powershell v5

### ISSUE THREAD

**Issue by montag64** [PSAppDeployToolkit/PSAppDeployToolkit#176]
If I download and run Deploy-Application.exe out of the toolkit folder as an admin (without making any script or source changes), I have no issues on Windows 7. I see the default prompts and everything runs as expected. If I do the same thing on Windows 10 LTSB x64, Deploy-Application.exe and powershell.exe open and sit in the background, but do nothing. I do not get any logs. This has been reproduced on 2 Windows 10 computers. It appears to be an issue for all the versions I tested (3.6.8 to 3.6.1). 

My PowerShell version on Windows 10 is:

Major  Minor  Build  Revision

5      0      10240  16384

We have packages in our environment (v3.6.4 mostly, or a hybrid of 3.6.1 and 3.6.7) that run perfectly fine on Windows 10, which was totally puzzling to me. It took me 6 or so hours of trial and error, but I believe I've discovered what the root cause is.

If I download any version of the PSAppDeployToolkit on a Win 10 machine, I have the do-nothing issue as described above. If I open the Deploy-Application.ps1, AppDeployToolkitMain.ps1, and AppDeployToolkitExtensions.ps1 in PowerShell ISE and put a space (or any text in the code comments) and then save the files, it suddenly starts working, but only if I edit and save all those files. That led me to think that it might be that I'm editing these PS files (of an older version) and saving them as v5 files, because the actual code and files are identical (according to diff checkers and WinMerge). 

As I had mentioned with Windows 7, I had no issues like this. This was the PS version:

Major  Minor  Build  Revision

2      0     -1     -1

As soon as I upgraded that PC to PowerShell v. 5, I had the same issue again as on Win 10, _but only for Toolkit files that had not already been ran on the Win7 PC._ I downloaded 3.6.8 fresh again, ran it, and again had the issue. I could resolve the issue like in Win 10 by editing the script files within the toolkit and saving them, and it works permanently after that. 

Is this an issue with Windows or with the Toolkit? Is there anything that can be done to resolve this in the future? If nothing else, I would recommend my workaround for Win10 users or those on PS v5. 

Feel free to reach out to me if you need more info. I really like the tool and hope that my contribution helps the dev team.

![psv5_issue](https://cloud.githubusercontent.com/assets/19194941/15048369/eaac0b78-12ae-11e6-9c15-818ad4955970.png)

**Comment by sbf-** [comment]
Have a look at the encoding (unicode/ASCII) - Probably it goes wrong there.
Open the file in notepad, save as and at the left of the save button you can see the encoding. It should be ANSI (8-bit) I guess

**Comment by amotaz** [comment]
I am unable to reproduce this issue running windows 10 with powershell 5. Have you been able to track down the cause, perhaps it is some sort of web filtering or av scanning causing a corruption of your downloaded files?

**Comment by amotaz** [comment]
Any update on this issue?

**Comment by montag64** [comment]
I'm pretty sure the problem derives from blocking untrusted filestreams in Windows. Essentially there is some default in PowerShell 5 that prevents a user from running PowerShell scripts from the internet (although no error is given).

**Comment by montag64** [comment]
I just checked my theory and it appears to be correct. Note the text in yellow. 
![image](https://cloud.githubusercontent.com/assets/19194941/21086709/9cfdd7c4-bfe4-11e6-98a2-6ad1818af51d.png)

If I check "unblock" then it works without issue. The security attribute seems to be tripped on every single filetype in the zip folder. I'm not entirely sure if it's just my organization has set this via group policy or if this a feature in Windows, but it's worth mentioning that a user such as myself should be aware of this.

An easy fix:

1) Download and extract the SysinternalsSuite by Mark Russinovich:
https://technet.microsoft.com/en-us/sysinternals/bb842062.aspx?f=255&MSPPError=-2147217396

2) Unzip PSAPPDEPLOY and open up an elevated command prompt, then cd to the Sysinterals directory.

3) Assuming your SysInternalsSuite folder is located in C:\ and your PC is 64-bit, run the following commands:

streams64.exe -s -d "<root of the PSAPPDEPLOY extracted toolkit>" -nobanner

This will recursively remove all the filestreams that cause the scripts to be blocked. I just tested it and it works well afterward without the need for editing all the files.

**Comment by amotaz** [comment]
Yup, makes sense. This is a feature of the OS. I believe it can be disabled via GPO, however, most organizations will leave it on. I'll add this to the faq however, thank you.

**Comment by DennisVH** [comment]
an easier solution than the SysInternals tool is to use the Unblock-File powershell cmdlet

**Comment by montag64** [comment]
@DennisVH yes, you're correct, I use streams

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/all-versions-including-3-6-8-sits-in-background-for-powershell-v5/1243

**Comment by luki1412** [comment]
The latest toolkit runs just fine on windows 10. Please give it another test.

**Comment by luki1412** [comment]
This issue is very out of date now. The toolkit fully supports Windows 10. Please download the latest version.
