### ISSUE TITLE
$envOSVersion not reliable in editors like ISE and PowerGUI

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#180]
If you run the following line from AppDeployToolkitMain.ps1 in ISE or PowerGUI, you get different versions than straight PowerShell.exe:

```
[version]$envOSVersion = [Environment]::OSVersion.Version
```

This more noticeable in Windows 8.1 where it returns Windows 8's version number!

Meanwhile it looks like  **.OSVersion is deprecated** 
We should use something else because in future versions of .Net it may be removed and no longer supported.  
http://msdn.microsoft.com/en-us/library/system.environment.osversion(v=vs.100).aspx
(Notice it doesn't come up for .Net 4.5 and above) 

Workaround:

```
[version]$envOSVersion = ([Regex]'(\d+\.){2}\d+').Match( (get-item (Join-Path ([Environment]::SystemDirectory) 'ntdll.dll')).VersionInfo.FileVersion ).Value
```

Source: http://powershell.com/cs/media/p/41298.aspx

**Comment by amotaz** [comment]
I was able to reproduce this issue in windows 8 and I added a fix. Please test to confirm. Thank you for the find.

**Comment by That-Annoying-Guy** [comment]
It works in Win7 fully patched and win7 vanilla unpatched.

Thank you!

**Comment by amotaz** [comment]
thank you for the confirmation. I was able to test on Windows 8.1 and Windows 10 as well, but I welcome any other results.

**Comment by That-Annoying-Guy** [comment]
FYI: fix not mentioned in CHANGELOG.txt

**Comment by That-Annoying-Guy** [comment]
FYI: This change has been undone in change labelled "Updated how OS version number are handled"

 **.OSVersion is deprecated**
