### ISSUE TITLE
Install-MSUpdates limitation

### ISSUE THREAD

**Issue by r1kardo** [PSAppDeployToolkit/PSAppDeployToolkit#181]
If you manually uninstall one of the updates and if you wat to intall this update again, It will not install because the function Install-MSUpdates will search in update history only for success or failure installs. It will not search if an update was uninstalled.

**Comment by amotaz** [comment]
I would still like to track this issue.

**Comment by r1kardo** [comment]
I reported the problem again . Thanks!

**Comment by bhaezlr** [comment]
We have the same problem. We downdrilled the problem to the call of 'Test-MsUpdates'.
We solved the problem by changing the call of Test-MSUpdates by Get-Hotfix.

**Comment by amotaz** [comment]
I've added some code which checks using get-hotfix first before trying the com object method. Please test and verify. I'm also going to further work on the com object check, as I think its not fully functional. I'm going to mark this as resolved, but will push out an update to the com object function later. Let me know if you run into any issues.
