### ISSUE TITLE
There is no Set-ScheduledTask function

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#186]
PSADT has a Get-ScheduledTask but no matching Set-ScheduledTask.

If you guys are planning to stay compatible at PowerShell  v2, I have Set-ScheduledTask function that can create a scheduled task on local computer or remote computer using a COM object and XML text exported from windows' Task Scheduler GUI.

If you are interested, I can post it here. 
(The WordPress-based Extension section does not like code and I have tried on multiple occasions.)

**Comment by cyborgrd** [comment]
It where be cool

**Comment by amotaz** [comment]
Yes, please post your code

**Comment by That-Annoying-Guy** [comment]
#Region Function Set-ScheduledTask
	Function Set-ScheduledTask {
	<#
	.SYNOPSIS
		Creates or removes a scheduled task on a local computer or remote computer
	.DESCRIPTION
		Creates a scheduled task on local computer or remote computer using COM object and XML text. 
		Returns $True if successful. $False otherwise.
		
		To obtain the XML, simply export it using "Task Scheduler" from an existing task. 
		CAVEAT: Only handles task folders *ONE* level deep.
		Does not use Schtasks.exe, Uses COM object which has more options.
	.PARAMETER TaskXmlContent
		Contents of a Task XML file as [XmlDocument] or [xml].
		populate a variable using a Here-String [@" "@] or get-content -Path <PathToTheXMLfile>
	.PARAMETER TaskNamePath
		Name of the task (and TaskFolder) to be created/removed
		TaskFolder is auto-created if needed.
		[TODO SomeDay: Optional *if* TaskXmlContent Description's Last line is @@@MyTaskFolder\MyTaskName]
	.PARAMETER TaskUser
		Default: $null
		TaskUser can be $null if task is running as SYSTEM or a group (e.g. BUILT-IN\USERS)
	.PARAMETER TaskPwd
		Default: $null
		TaskPwd can be $null if task is running as SYSTEM or a group (e.g. BUILT-IN\USERS)
	.PARAMETER ComputerName
		Name of Computer where to create the task. Default: localhost
	.PARAMETER Remove
		Remove the task specified by TaskNamePath [and ComputerName]
	.PARAMETER RemoveTaskFolderIfEmpty
		Works with -Remove parameter. Deletes the folder containing the targeted task if it's empty.
	.PARAMETER ContinueOnError
		Continue if an error is encountered. Default: $false.
	.EXAMPLE
		[XML]$TaskXmlFileContent = Get-Content "C:\stuff\ExportedTask.xml"
		Set-ScheduledTask -TaskNamePath 'MyTaskName' -TaskXmlContent $TaskXmlFileContent -ComputerName $Computer
		Creates 'MyTaskName' task in Root Task folder (\) from "C:\stuff\ExportedTask.xml"
	.EXAMPLE
		Set-ScheduledTask -TaskNamePath 'MyTaskName' -Remove -ComputerName $Computer
		Removes the 'MyTaskName' task from Root Task folder (\)
	.EXAMPLE
		[xml]$TaskXmlContent = @" ...<xml stuff>... "@
		Set-ScheduledTask -TaskNamePath "MyTaskFolder\MyTaskName" -TaskXmlContent $TaskXmlContent
		Creates task in MyTaskFolder Task folder (\MyTaskFolder) and creates 'MyTaskName' task using contents of an XML file
		
		CAVEAT: Cannot create more than ONE level deep.
		(IOW, this will not work: "MyTaskFolder\2ndLevelTaskFolder\MyTaskName")
	.EXAMPLE
		Set-ScheduledTask -TaskNamePath "MyTaskFolder\MyTaskName" -Remove
		Set-ScheduledTask -TaskNamePath "\MyTaskFolder\MyTaskName" -Remove
		Removes task from MyTaskFolder Task folder (\MyTaskFolder)
		CAVEAT: Cannot delete from more than ONE level deep.
	.EXAMPLE
		Set-ScheduledTask -TaskNamePath "MyTaskFolder\MyTaskName" -Remove -RemoveTaskFolderIfEmpty
		Removes task from MyTaskFolder Task folder (\MyTaskFolder)
		Removes MyTaskFolder Task folder *if* it then becomes empty
		CAVEAT: Cannot delete from more than ONE level deep.
	.EXAMPLE
		Set-ScheduledTask -TaskNamePath "\MyTaskFolder\*" -Remove -RemoveTaskFolderIfEmpty
		Removes MyTaskFolder Task folder and its Tasks. (BE CAREFUL!!)
		CAVEAT: Cannot delete from more than ONE level deep.
	.NOTES
		MASSIVE CAVEAT: Microsoft has configured task security in such a way that only and admin account can create/delete/run a task.
		you cannot have a process/task running as SYSTEM create/delete/run a task due to security concerns.
		But MS has added an exception by allowing SMS/SCCM/CM to create/delete/run a task.
		The Task can also have an action to delete itself using schtasks.exe
		
		Version 1.0 (02-Jun-2016)
		Denis St-Pierre (Ottawa, Canada)
		Powershell v2.0 and up.
		LIMITATION: Cannot handle more than one task folder deep 
		For syntax use: Get-Help Set-ScheduledTask
		
		TODO: add regex validation on $TaskNamePath Parameter to Filter out '/', Drive letters and UNC paths
	#>
		[CmdletBinding()]
		Param (
			[Parameter(Mandatory=$True)]
			[ValidateNotNullorEmpty()]
			[string]$TaskNamePath = '',
			[Parameter(Mandatory=$True,ParameterSetName='Create')]
			[ValidateNotNullorEmpty()]
			[xml]$TaskXmlContent,
			[Parameter(Mandatory=$True,ParameterSetName='Remove')]
			[ValidateNotNullorEmpty()]
			[Switch]$Remove,
			[Parameter(Mandatory=$false)]
			[ValidateNotNullorEmpty()]
			[string]$ComputerName = "localhost",
			[Parameter(Mandatory=$false,ParameterSetName='Create')]
			[ValidateNotNullorEmpty()]
			[string]$TaskUser = $null,
			[Parameter(Mandatory=$false,ParameterSetName='Create')]
			[ValidateNotNullorEmpty()]
			[string]$TaskPwd = $null,
			[Parameter(Mandatory=$false,ParameterSetName='Remove')]
			[ValidateNotNullOrEmpty()]
			[switch]$RemoveTaskFolderIfEmpty,
			[Parameter(Mandatory=$false)]
			[ValidateNotNullOrEmpty()]
			[bool]$ContinueOnError = $false
		)

		Begin {
			## Get the name of this function and write header
			[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
			Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
			Remove-Variable TaskFolderPath -ErrorAction SilentlyContinue #Needed for debug to make sense
			
			Try {
				[System.__ComObject]$ScheduleObj = New-Object -ComObject("Schedule.Service") #Need Admin do to this!
				$ScheduleObj.connect($ComputerName)
				[System.__ComObject]$TaskRootFolderObj = $ScheduleObj.GetFolder("\")
			} Catch {
				[string]$exceptionMessage = "$($_.Exception.Message) `($($_.ScriptStackTrace)`)"
				[String]$message = "ERROR: Cannot connect to [Schedule.Service]. Are we running elevated? $exceptionMessage"
				If ($ContinueOnError) {
					Write-Log -Message $message -Severity 3 -Source ${CmdletName}
					Return $false #exit function
				} else { Throw "ERROR: [$Message]" }
			}
			#TODO SomeDay: Retrieve TaskNamePath from TaskXmlContent Description's Last line is @@@MyTaskFolder\MyTaskName
			Write-Log -Message "TaskNamePath is [$TaskNamePath]" -Source ${CmdletName}
			
			If ( $TaskNamePath -match '\\') { #Found a '\' = Get $TaskName and $TaskFolderPath from $TaskNamePath
				[string]$TaskName = [System.IO.Path]::GetFileName($TaskNamePath)
				[string]$TaskFolderPath = [System.IO.Path]::GetDirectoryName($TaskNamePath)
				Write-Log -Message "TaskFolder is [$TaskFolderPath]  TaskName is [$TaskName]" -Source ${CmdletName}
			} else {
				[string]$TaskName = $TaskNamePath
	#			[string]$TaskFolderPath = "\"	#RootTaskFolder
			}
		}
		Process {
			#Remove ALL Tasks
			If ( ($Remove) -and ($TaskName -eq "*") ) {
				#Remove ALL Tasks in ONE Task Folder (Except ROOT Task Folder)
				If ($TaskRootFolderObj.Path -eq $TaskFolderObj.Path ) {
					[String]$message = "Will NOT delete all tasks in [ROOT Task Folder]. Allowing this would break too many things!"
					If ($ContinueOnError) {
						Write-log -Message $Message -Severity 3 -Source ${CmdletName}
						Return $false #exit function
					} else { Throw "ERROR: [$Message]" }
				}
				
				Try {
					[System.__ComObject]$TaskFolderObj = $ScheduleObj.GetFolder($TaskFolderPath)
				} Catch [System.Management.Automation.MethodInvocationException] { 
					if ($_.Exception.HResult -eq -2146233087) {		#Task folder does not exist
						[String]$message = "Task folder [${TaskFolderPath}] does not exist. Nothing to Delete."
						Write-log -Message $message -Severity 2 -Source ${CmdletName}
						Return $true
					} Else {
						[string]$ExceptionType = $_.Exception.GetType()
						[string]$ExceptionHResult = $_.Exception.HResult
						[string]$exceptionMessage = "$($_.Exception.Message) ExceptionType:[$ExceptionType] ExceptionHResult [$ExceptionHResult] `($($_.ScriptStackTrace)`)"
						If ($ContinueOnError) {
							Write-log -Message $exceptionMessage -Severity 3 -Source ${CmdletName}
							Write-log -Message $message -Severity 3 -Source ${CmdletName}
							Return $true #exit Function
						} else { Throw "ERROR: $message $exceptionMessage" }
					}
				} Catch {
					[string]$exceptionMessage = "$($_.Exception.Message)] `($($_.ScriptStackTrace)`)"
					[String]$message = "Task folder [$TaskFolderPath] does not exist. Nothing to Delete. $exceptionMessage"
					If ($ContinueOnError) {
						Write-log -Message $message -Severity 3 -Source ${CmdletName}
						Return $True #exit function
					} else { Throw "ERROR: $message" }
				}
				
				Write-Log -Message "Deleting Task folder [$($TaskFolderObj.Path)] regardless of the number of tasks in the folder" -Source ${CmdletName}
				Try {
					[System.__ComObject]$AllTasks = $TaskFolderObj.GetTasks(1) #1= include hidden tasks too
				} Catch {
					[string]$exceptionMessage = "$($_.Exception.Message)] `($($_.ScriptStackTrace)`)"
					[String]$message = "Unable to get the Tasks in Task folder [$TaskFolderPath] $exceptionMessage"
					If ($ContinueOnError) {
						Write-log -Message $message -Severity 3 -Source ${CmdletName}
						Return $false #exit function
					} else {
						Throw "ERROR: $message"
					}
				}
				[Int32]$TotalNumTasks = $AllTasks.count
				Write-log -Message "[$TaskFolderPath] has [$TotalNumTasks] task(s)"  -Source ${CmdletName}
				If ($TotalNumTasks -gt 0 ) {
					ForEach ($Task in $AllTasks) {
						Try {
							$Task.Stop(0)	#Just in case, should test if running first
							Start-Sleep -Seconds 1
							$TaskFolderObj.DeleteTask($Task.Name,0)
							Write-Log -Message "Task [$($Task.Name)] was deleted" -Source ${CmdletName}
						} Catch {
							[String]$message = "Cannot delete task [$($Task.Name)]. Might not exist or not stopped"
							If ($ContinueOnError) {
								Write-log -Message $message -Severity 3 -Source ${CmdletName}
							} else { Throw "ERROR: $message" }
						}
					}
				
					#Are they all gone?
					[System.__ComObject]$AllTasks = $TaskFolderObj.GetTasks(1) # 1 = include hidden tasks too
					If ($($AllTasks.Count) -ne 0) { 
						[string]$ErrMess = "ERROR: Not all tasks have been deleted from the task folder."
						ForEach ($Task in $AllTasks) {
								$ErrMess = $ErrMess + "`nTask [$($Task.Name)]"
						}
						If ($ContinueOnError) {
							Write-log -Message $ErrMess -Severity 3 -Source ${CmdletName}
							Return $false #exit function
						} else { Throw "ERROR: $ErrMess" }
					} else {
						#Write-log -Message "INFO:No Tasks to delete in task folder[$SubFolderPath]." -Source ${CmdletName}
					}
				} else {
					Write-Log -Message "INFO: No tasks to delete in task folder [$SubFolderPath]." -Source ${CmdletName}
				}

				#Delete the Task Folder
				if ($RemoveTaskFolderIfEmpty) {
					#CAVEAT : you must use .DeleteFolder method with the PARENT of the task folder you want to delete
					#CAVEAT2: I didn't bother to add code for subfolders b/c I didn't need it.
					$SubFolderName = Split-Path -Path $TaskFolderObj.Path -Leaf
					$ParentFolderPath = Split-Path -Path $TaskFolderObj.Path -Parent
					Try {
						[System.__ComObject]$ParentFolderObj = $ScheduleObj.GetFolder($ParentFolderPath)
					} Catch {
						[string]$exceptionMessage = "$($_.Exception.Message) `($($_.ScriptStackTrace)`)"
						Throw "Task folder [${ParentFolderPath}] does not exist. Nothing to Delete. $exceptionMessage"
						Return $true #exit Function
					}
					#No need to check for left-over tasks. We did this already above
					
					Try {
						$ParentFolderObj.DeleteFolder($SubFolderName,$null)
						Write-Log -Message "Task folder [$SubFolderName] was deleted" -Source ${CmdletName}
						Return $true #exit Function
					} Catch {
						$exceptionMessage = "$($_.Exception.Message) `($($_.ScriptStackTrace)`)"
						[String]$message = "Unable to delete Task folder [$SubFolderName] $exceptionMessage"
						If ($ContinueOnError) {
							Write-log -Message $message -Severity 3 -Source ${CmdletName}
							Return $false #exit Function
						} else { Throw "ERROR: $message" }
					}
				} Else {
					#Write-log "Not attempting to delete Task Folder [$($TaskFolderObj.Path)]" -Source ${CmdletName}
					Return $true #exit Function
				}
				
			}
		
			#Remove ONE Task
			If ( ($Remove) -and ($TaskName -ne "") ) {
				Try {
					[System.__ComObject]$TaskFolderObj = $ScheduleObj.GetFolder($TaskFolderPath)
				} Catch [System.Management.Automation.MethodInvocationException] { 
					if ($_.Exception.HResult -eq -2146233087) {		#Task folder does not exist
						[String]$message = "Task folder [${TaskFolderPath}] does not exist. Nothing to Delete."
						Write-log -Message $message -Severity 2 -Source ${CmdletName}
						Return $true
					} Else {
						[string]$ExceptionType = $_.Exception.GetType()
						[string]$ExceptionHResult = $_.Exception.HResult
						[string]$exceptionMessage = "$($_.Exception.Message) ExceptionType:[$ExceptionType] ExceptionHResult [$ExceptionHResult] `($($_.ScriptStackTrace)`)"
						If ($ContinueOnError) {
							Write-log -Message $exceptionMessage -Severity 3 -Source ${CmdletName}
							Write-log -Message $message -Severity 3 -Source ${CmdletName}
							Return $true #exit Function
						} else { Throw "ERROR: $message $exceptionMessage" }
					}
				} Catch {
					[string]$ExceptionType = $_.Exception.GetType()
					[string]$ExceptionHResult = $_.Exception.HResult
					[string]$exceptionMessage = "$($_.Exception.Message) ExceptionType:[$ExceptionType] ExceptionHResult [$ExceptionHResult] `($($_.ScriptStackTrace)`)"
					If ($ContinueOnError) {
						Write-log -Message $exceptionMessage -Severity 3 -Source ${CmdletName}

						Return $true #exit Function
					} else { Throw "ERROR: $message $exceptionMessage" }
				}
				
				Write-Log -Message "Task [$TaskName] will be removed"  -Source ${CmdletName}
				Try {
					[System.__ComObject]$task = $TaskFolderObj.gettask($TaskName)
					$Task.Stop(0)	#Stop the task, Just in case
					Start-Sleep -Seconds 1
					$TaskFolderObj.DeleteTask($TaskName,0)
					Write-Log -Message "Task [$TaskName] was deleted" -Source ${CmdletName}
				} Catch [System.Management.Automation.MethodInvocationException] {
					If ($_.Exception.HResult -eq -2146233087) {		#Task folder does not exist
						[String]$message = "Task [$TaskName] does not exist. Nothing to Delete."
						Write-log -Message $message -Severity 2 -Source ${CmdletName}
						#Don't exit in-case we have -RemoveTaskFolderIfEmpty
					} Else {
						[string]$ExceptionType = $_.Exception.GetType()
						[string]$ExceptionHResult = $_.Exception.HResult
						[string]$exceptionMessage = "$($_.Exception.Message) ExceptionType:[$ExceptionType] ExceptionHResult [$ExceptionHResult] `($($_.ScriptStackTrace)`)"
						If ($ContinueOnError) {
							Write-log -Message $exceptionMessage -Severity 3 -Source ${CmdletName}
							Write-log -Message $message -Severity 3 -Source ${CmdletName}
							Return $true #exit Function
						} else { Throw "ERROR: $message $exceptionMessage" }
					}
				} Catch {
					[string]$ExceptionType = $_.Exception.GetType()
					[string]$ExceptionHResult = $_.Exception.HResult
					[string]$exceptionMessage = "$($_.Exception.Message) ExceptionType:[$ExceptionType] ExceptionHResult [$ExceptionHResult] `($($_.ScriptStackTrace)`)"
					Write-log -Message $exceptionMessage -Severity 3 -Source ${CmdletName}
					[String]$message = "INFO: Cannot delete task [$TaskName]. It might not exist."
					Write-log -Message $message -Severity 3 -Source ${CmdletName}
					Return $True #exit Function
				}
				
				#TODO: JIC, Check if the Task is still in $TaskFolderObj or not ( use gettasks() ?)

				if ($RemoveTaskFolderIfEmpty) {
					If ($TaskRootFolderObj.Path -eq $TaskFolderObj.Path ) {
						[String]$message = "INFO: Cannot delete [ROOT task] folder."
						If ($ContinueOnError) {
							Write-log -Message $message -Severity 3 -Source ${CmdletName}
						} else { Throw "ERROR: $message" }
					} else {
						Try {
							#CAVEAT : you must use .DeleteFolder method with the PARENT of the task folder you want to delete
							#CAVEAT2: I didn't bother to add code for subfolders b/c I didn't need it.
							$SubFolderName	= Split-Path -Path $TaskFolderObj.Path -Leaf
							$ParentFolderPath = Split-Path -Path $TaskFolderObj.Path -Parent
							
							Try {
								[System.__ComObject]$ParentFolderObj = $ScheduleObj.GetFolder($ParentFolderPath)
							} Catch {
								[string]$exceptionMessage = "$($_.Exception.Message) `($($_.ScriptStackTrace)`)"
								Throw "Cannot Get Task folder [${ParentFolderPath}] in order to delete [$SubFolderName]. $exceptionMessage"
								Return $false #exit Function
							}
							#Is $TaskFolder empty? 
							[System.__ComObject]$AllTasks = $TaskFolderObj.GetTasks(1) #1= include hidden tasks too
							If ($($AllTasks.Count) -eq 0) {
								$ParentFolderObj.DeleteFolder($SubFolderName,$null)
								Write-Log -Message "Task folder [$SubFolderName] was deleted" -Source ${CmdletName}
							} Else {
								Write-Log -Message "INFO: Cannot delete Task folder [$SubFolderName]. It still contains [$($AllTasks.Count)] task(s)." -Severity 2 -Source ${CmdletName}
							}
							Return $True #exit Function
						} Catch {
							$exceptionMessage = "$($_.Exception.Message) `($($_.ScriptStackTrace)`)"
							[String]$message = "Unable to delete Task folder [$SubFolderName] $exceptionMessage"
							If ($ContinueOnError) {
								Write-log -Message $message -Severity 3 -Source ${CmdletName}
								Return $false #exit Function
							} else { Throw "ERROR: $message" }
						}
					} #Else
				} Else {
					#Write-log "Not attempting to delete Task Folder [$($TaskFolderObj.Path)]" -Source ${CmdletName}
					Return $true #exit Function
				}
			} 
			
			#Create Task
			If ($TaskName -eq "*") {
				[String]$message = "Cannot create task named [$TaskName]"
				If ($ContinueOnError) {
					Write-log -Message $message -Severity 3 -Source ${CmdletName}
					Return $false #exit Function
				} else { Throw "ERROR: $message" }
			}	
			
			If (-not ( $TaskXmlContent) ) {
				[String]$message = "Cannot create task without -TaskXmlContent parameter"
				If ($ContinueOnError) {
					Write-log -Message $message -Severity 3 -Source ${CmdletName}
					Return $false #exit Function
				} else { Throw "ERROR: $message" }
			}
			
			If ($TaskFolderPath) { 	#Create TaskFolder if needed
				Write-Log -Message "Creating Task folder [${TaskFolderPath}]"  -Source ${CmdletName}
				Try { $TaskRootFolderObj.CreateFolder($TaskFolderPath) } Catch { } #ignore already exists error
				Try {
					[System.__ComObject]$TaskFolderObj = $ScheduleObj.GetFolder($TaskFolderPath)
					Write-Log -Message "Success." -Source ${CmdletName}
				} Catch {
					[String]$message = "Task folder [${TaskFolderPath}] does not exist. Cannot create task in non-existing task folder."
					If ($ContinueOnError) {
						Write-Log -Message $message -Severity 3 -Source ${CmdletName}
						Return $false
					} Else { Throw "ERROR: $message" }
				}
			} Else {	#Task will be created in the "Root" Task Folder
				[System.__ComObject]$TaskFolderObj = $TaskRootFolderObj
			}
			
			#Creating task (In sub-folder if needed)
			[System.__ComObject]$NewTask = $ScheduleObj.NewTask($null)		#Create blank task
			If ( $($TaskXmlContent.gettype().name) -eq "XmlDocument") {
				$NewTask.XmlText = $TaskXmlContent.OuterXml -as [string]	#load XmlText property
			} ElseIf ( $($TaskXmlContent.gettype().name) -eq "String") {
				$NewTask.XmlText = $TaskXmlContent		#load XmlText property
			} Else {
				[String]$message = "-TaskXmlContent as [$($TaskXmlContent.gettype().name)] is not supported. Please cast as [XmlDocument] or [string]."
				If ($ContinueOnError) {
					Write-log -Message $message -Severity 3 -Source ${CmdletName}
					Return $false #exit Function
				} else { Throw "ERROR: $message" }			
			}
			
			#It can overwrite an existing task just fine provided that the task folder exists already
			# but just in case...
			Try {
				Write-Log -Message "Creating Task [$TaskName]..." -Source ${CmdletName}
				$RegistrationResult = $TaskFolderObj.RegisterTaskDefinition($TaskName, $NewTask, 6, $TaskUser, $TaskPwd, 1, $null)
				#Write-log "DEV: $RegistrationResult"  -Source ${CmdletName}
				Write-Log -Message "Success. Returning True" -Source ${CmdletName}
			} catch {
				[string]$exceptionMessage = "$($_.Exception.Message) `($($_.ScriptStackTrace)`)"
				[String]$message = "Unable to import task [$TaskName] $exceptionMessage"
				If ($ContinueOnError) {
					Write-log -Message $message -Severity 3 -Source ${CmdletName}
					Return $false
				} Else { throw "ERROR: $message" }
			}
			# $RegistrationResult is a Massive block of text but not as [String]
			# [String]$RegistrationResultString = Out-String -InputObject $RegistrationResult
			# Return $RegistrationResultString
			Return $true
		}
		End {
			Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
		}
	} # Set-ScheduledTask
	#Endregion Function Set-ScheduledTask

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/there-is-no-set-scheduledtask-function/1239

**Comment by JonathanPitre** [comment]
+1 I would love to see that function in a future release of PSADT

**Comment by Dennis-Bezold** [comment]
+1

**Comment by mjr4077au** [comment]
This functionality is covered by the native `ScheduledTasks` module provided by Windows 8 and newer targets. The pending v4 preview only supports supported versions of Windows, and all supported Windows releases contain the `ScheduledTasks` module.
