### ISSUE TITLE
Get-PendingReboot example in documentations always return false

### ISSUE THREAD

**Issue by MortenRoenborg** [PSAppDeployToolkit/PSAppDeployToolkit#188]
"(Get-PendingReboot).IsSystemRebootPending" shown in the example will always return false. I think it should be "(Get-PendingReboot).RebootPending" instead.

**Comment by That-Annoying-Guy** [comment]
[06-14-2016 13:17:38.297] [Initialization] [Get-PendingReboot] :: Pending reboot status on the local computer [censored]: 

	IsFileRenameRebootPending    : False
	IsWindowsUpdateRebootPending : False
	ComputerName                 : [censored]
	LastBootUpTime               : 14/06/2016 9:40:00 AM
	IsCBServicingRebootPending   : False
	IsSCCMClientRebootPending    : 
	IsSystemRebootPending        : False
	ErrorMsg                     : 
	PendingFileRenameOperations  : 

It would not work. **RebootPending** is not a property that **Get-PendingReboot** returns.

**Comment by MortenRoenborg** [comment]
Hey orange
I'm probably using a old version of the AppdeployToolkitMain hence:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/51
My bad

**Comment by That-Annoying-Guy** [comment]
No big deal. I'm just happy you know what you are doing.

Amotaz, you can close this issue.
