### ISSUE TITLE
Get-RegistryKey function needs example of how to read a "(Default)" value of a key

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#191]
```
.EXAMPLE
    Get-RegistryKey -Key "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\VLC.3g2" -Value "(Default)"
```

**Comment by That-Annoying-Guy** [comment]
Here's how to integrate it with the new -DoNotExpandEnvironmentNames parameter:

					#  Get the Value (do not make a strongly typed variable because it depends entirely on what kind of value is being read)
					If (( $IsRegistryValueExists) -or ($Name -eq '(Default)') ){
						If ($DoNotExpandEnvironmentNames) {
							$regKeyValue = $(Get-Item -Path $key -ErrorAction 'Stop').getvalue($Value,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
						} ElseIf ($Name -eq '(Default)') {
	                        ## Get Default registry key value with the following workaround, because Get-ItemProperty contains a bug and cannot get Default registry key value
							$regKeyValue = $(Get-Item -Path $key -ErrorAction 'Stop').GetValue($null) #$null = Default Value of the key
						} Else {
							$regKeyValue = $regKeyValue | Select-Object -ExpandProperty $Value -ErrorAction 'SilentlyContinue'
						}
					}
					Else {
						Write-Log -Message "Registry key value [$Key] [$Value] does not exist. Return `$null." -Source ${CmdletName}
						$regKeyValue = $null
					}

**Comment by That-Annoying-Guy** [comment]
Would you rather have a pull request?

**Comment by amotaz** [comment]
In the future, pulls are fine, but we're getting ready to do a release soon so can't accept it now.
