### ISSUE TITLE
Execute-Process crashes with dpinst when Start-Process succeeds

### ISSUE THREAD

**Issue by macxcool** [PSAppDeployToolkit/PSAppDeployToolkit#192]
I'm trying to install drivers with dpinst.exe. If I run:

```
dpinst /q /path "Path to Drivers"
```

everything's OK.
If I use:

```
Execute-Process -Path "Path to dpinst" -Parameters "/q /path `"Path to Drivers`""
```

the script exits with an error from dpinst
If I use:

```
Start-Process -FilePath "Path to dpinst" -ArgumentList "/q /path `"Path to Drivers`"" -Wait
```

everything is OK as well.
No matter what I try, I can't get Execute-Process to work with this.

**Comment by That-Annoying-Guy** [comment]
Looks like a translation issue. (My guess /q  ==> `/q  )
Get a copy of Echoargs.exe (https://duckduckgo.com/?q=Echoargs.exe&ia=web)
and rename it to dpinst.exe

Echoargs.exe will tell you what Arguments **dpinst.exe** gets in the end.

**Comment by macxcool** [comment]
I don't know what you mean That-Annoying-Guy. I use forward slashes all the time as commanline parameters and this has never happened before?
I tried Echoargs, and the parameters it's receiving are what I'd expect.

**Comment by That-Annoying-Guy** [comment]
Too little to go on. I cannot help you. sorry

**Comment by macxcool** [comment]
Tell me what you need and I'll get it for you.

**Comment by That-Annoying-Guy** [comment]
Have you tried this?:

	Start-Process -FilePath "Path to dpinst" -ArgumentList '/q /path "Path to Drivers"' -Wait

I just replaced the " for '
and `" for "

I think this can be done because you are not using $vars in -ArgumentList 

Either way, the actual error message might help.

**Comment by amotaz** [comment]
Hi Maxcool, Did That-Annoying-Guy's suggestion resolve your issue?
