### ISSUE TITLE
Write-Log cannot resolve $ExecuteMSIResult.ExitCode attribute

### ISSUE THREAD

**Issue by Brachus12** [PSAppDeployToolkit/PSAppDeployToolkit#193]
When I attempt to show an ExitCode from an Execute-MSI process in my log, the Write-Log cmdlet does not appear to be able to pull just the ExitCode out of the array
`
 Write-Log -Message "Result is $ExecuteMSIResult.ExitCode" -Source 'Execute-MSI' -LogType CMTrace`

_<![LOG[[Pre-Installation] :: Result is @{ExitCode=0; StdErr=; StdOut=}.ExitCode]LOG]!><time="09:22:12.775-240" date="06-30-2016" component="Execute-MSI" context="domain/me" type="1" thread="3440" file="Deploy-Application.ps1">_

**Comment by gerane** [comment]
Write it like this

Write-Log -Message "Result is $($ExecuteMSIResult.ExitCode)" -Source
'Execute-MSI' -LogType CMTrace

**Comment by gerane** [comment]
If not, ".ExitCode" is viewed as part of the string.

**Comment by Brachus12** [comment]
Thanks! That got it. I had tried parenthesis but without the second $
