### ISSUE TITLE
Is there a license agreement to use the software?

### ISSUE THREAD

**Issue by DawnWertz** [PSAppDeployToolkit/PSAppDeployToolkit#194]

**Comment by That-Annoying-Guy** [comment]
No. The only mention of license is in the "PowerShell App Deployment Toolkit Administrator Guide" on page 6:

Licensing

The PowerShell App Deployment Toolkit is provided under the Microsoft Public License:
https://psappdeploytoolkit.codeplex.com/license

We have invested a lot of personal time in the creation and ongoing development, maintenance and support of this community tool – it is not part of our day jobs! Donations to the project are welcome, please visit the following page for details on making a contribution:

https://psappdeploytoolkit.codeplex.com/wikipage?title=Donate
