### ISSUE TITLE
Consolidate html log file 

### ISSUE THREAD

**Issue by smbasha27** [PSAppDeployToolkit/PSAppDeployToolkit#196]
Dear Team, I just started looking to this tool,  I'm looking for a feature consolidate html which gives package information deployment information, system information and status of each actions as success or failure by reading all individual logs with the return code.
[Test SuiteApps1.zip](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/391736/Test.SuiteApps1.zip)

**Comment by That-Annoying-Guy** [comment]
I maintain a private fork of PSADT.
We use the Temp Log Directory feature to place all our log files when the script runs.
By default, the Temp Log Directory feature Zip the logs when it's done. I was fine with it but my group asked me make it to merge the log files into one log file as per existing package wrappers we already use. This was A-LOT-OF-WORK.  (And this was only ONE of the gotta-have-features I had to add)
I doubt the PSADT developers would be interested in adding (never-mind creating) the functionality you are asking for. I might be able to help determine where in the AppDeployToolkitMain.ps1 file to place your changes but that's it.

**Comment by smbasha27** [comment]
No doubt, this is fantastic tool and very useful for pkg and deployment. I'm looking towards service desk team going to the html log and understand what was happen, where the installation is broken instead of loading the log file to the cms tracer to investigate. Any help in adding a function to generate html log file with actions reading from log file is much appreciated.

**Comment by That-Annoying-Guy** [comment]
I've seen this (https://www.reddit.com/r/PowerShell/comments/4fxrnm/powershell_output_to_html/) but I'm no HTML wiz. This should give you an idea of how to structure your code.

Store your "Set-HtmlReport" function in AppDeployToolkitExtensions.ps1. This way as new versions of PSADT come out, you just replace everything but AppDeployToolkitExtensions.ps1.

As to _where_ to trigger it from inside PSADT, put the line calling your "Set-HtmlReport" function at the end of Exit-Script function (in AppDeployToolkitMain.ps1) around this line:

	If ($configToolkitCompressLogs) {

Good luck!

**Comment by amotaz** [comment]
We'll look into possibly adding some of this functionality into the next major revision.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/consolidate-html-log-file/1220

**Comment by mjr4077au** [comment]
Apologies but I don't see this feature request occurring. The only potential I see for expanding the logging would be logging to the Windows event logs for SIEM collection, etc.
