### ISSUE TITLE
Update program list dynamically

### ISSUE THREAD

**Issue by wala0003** [PSAppDeployToolkit/PSAppDeployToolkit#198]
Hello,
I made some additions to allow the list of open apps to automatically refresh and only show apps that are still open. Also, the user dialog will now automatically continue the installation once all the required applications are closed. It isn't particularly elegant nor tested extensively but I thought you'd maybe consider this addition.

[AppDeployToolkitMain.zip](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/411555/AppDeployToolkitMain.zip)

**Comment by seanlillis** [comment]
Just scrolling through the open issues and I noticed this - I've actually included exactly the functionality you are looking for in the next release.

**Comment by seanlillis** [comment]
This is included in v3.7.0.
