### ISSUE TITLE
Show-InstallationWelcome dialog window text is offset to the left

### ISSUE THREAD

**Issue by mmashwani** [PSAppDeployToolkit/PSAppDeployToolkit#2]
While the main text from the Show-InstallationWelcome dialog window is centered, it is offset slightly to the left. When additionally using the countdown variable option, it is noticeably shifted to the left.

In some of the installation windows there is a blue circle icon with a letter "i" in it that is just to the left of the main text. On those windows that have the icon the text is properly centered, but on those windows without the icon on the left the text is pushed left so it's not centered properly.

This issue was migrated from CodePlex:
https://psappdeploytoolkit.codeplex.com/workitem/177

**Comment by LMCO-psadt-devs** [comment]
Any news on this?  One idea to re-center the countdown timer is in AppDeployToolkitMain.ps1 - line 6022:
$labelCountdown.Margin = '75,0,0,0'

**Comment by LMCO-psadt-devs** [comment]
OK - my proposed 2 edits:
    $labelDefer.Margin = '20,0,20,0'
    $labelCountdown.Margin = '75,0,0,0'

**Comment by mmashwani** [comment]
Thanks for the suggestion. I've integrated your proposal into the latest beta. It will be in the next release.

**Comment by n1x0d** [comment]
Well, I agree: It was indeed offset to the left. But after that "fix" it is now way offset to the right (German Windows 10).

**Comment by mmashwani** [comment]
Hmm, OK, I will revert the change for now as this obviously requires more testing to properly resolve.

**Comment by luki1412** [comment]
Will be fixed in the next release.
