### ISSUE TITLE
User's display UI is not detected in all cases

### ISSUE THREAD

**Issue by Fatbob1** [PSAppDeployToolkit/PSAppDeployToolkit#20]
In 3.6.3 the detection of the language with MUI packs does not work as expected  for Windows 7 x64 :

In the AppDeployToolKitMain.Ps1 – [scriptblock]$xmlLoadLocalizedUIMessages
1/ There is a Typo : The code looks for “PrefferedUILanguages” instead of “PreferredUILanguages” (Actual of the value name in registry
2/ None of the 2 possible GPO settings have been considered. These should be considered first since the should have precedence. The block for windows 7 / Vista machines should looks like something like 

Possible resolution : 
```
#  Read language for Win Vista/Win 7 machines
If (-not $HKULanguages) {
	[string[]]$HKULanguages = Get-RegistryKey -Key 'HKLM\Software\Policies\Control Panel\Desktop' -Value 'PreferedUILanguages' -SID $RunAsActiveUser.SID
}
If (-not $HKULanguages) {
	[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Software\Polices\Control Panel\Desktop' -Value 'PreferedUILanguages' -SID $RunAsActiveUser.SID
}
If (-not $HKULanguages) {
	[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\Desktop' -Value 'PrefferedUILanguages' -SID $RunAsActiveUser.SID
}
If (-not $HKULanguages) {
	[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\Desktop\MuiCached' -Value 'MachinePreferredUILanguages' -SID $RunAsActiveUser.SID
}
If (-not $HKULanguages) {
	[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\International' -Value 'LocaleName' -SID $RunAsActiveUser.SID
}
```

**Comment by mmashwani** [comment]
This issue should now be resolved in the beta 3.6.4 located here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit

Please test and let me know if it's working as expected now.

**Comment by Fatbob1** [comment]
Hi 

I have first to excuse myself because i've a (couple of) mistakes : 
1/ The path to check for the Computer GPO is : 
HKLM\SOFTWARE\Policies\Microsoft\MUI\Settings' -Value 'PreferredUILanguages'
2/ I also made a Typo because in  "PreferredUILanguages" I forgot the 1 "rr"

Enough with my errors, and after correction in you code , now the results  
-- The detection for the "free" (no GPO applied) works fine
-- But the Detection for setting by GPO so far i not working : It gets only the "free" setting, the one I speak about in the previous Point. I've spent countless of hours to figure out where the problem might be (Typo, registry wrong path) and of course I didn't find something so far. I behaves just like for whatever reason the script can not read the EXISTING registry keys. The thing I've noticed is that for the GPO the Value is REG_SZ and for the "free" setting is REG_Multi_SZ ..  I am a bit out of idea since I can not trace $HKULanguages after each reading in the registry.. that would really help (If I use the write-log function with the variable, the script just does not run.. but I might be wring somewhere or the value read is somehow "out of range) 

My code : 

#  If a user is logged on, then get primary UI language for logged on user (even if running in session 0)
	If ($RunAsActiveUser) {
		#  Read language defined by Group Policy
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKLM\SOFTWARE\Policies\Microsoft\MUI\Settings' -Value 'PreferredUILanguages'                                    
		}
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\SOFTWARE\Polices\Microsoft\Control Panel\Desktop' -Value 'PreferredUILanguages' -SID $RunAsActiveUser.SID
		}
		#  Read language for Win 8 machines
		[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\International\User Profile' -Value 'Languages' -SID $RunAsActiveUser.SID
		#  Read language for Win Vista/Win 7 machines
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\Desktop' -Value 'PreferredUILanguages' -SID $RunAsActiveUser.SID
		}
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\Desktop\MuiCached' -Value 'MachinePreferredUILanguages' -SID $RunAsActiveUser.SID
		}
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\International' -Value 'LocaleName' -SID $RunAsActiveUser.SID
		}
		#  Read language for Win XP machines
		If (-not $HKULanguages) {
			[int32]$HKULocale = Get-RegistryKey -Key 'HKCU\Control Panel\International' -Value 'Locale' -SID $RunAsActiveUser.SID
			If ([string]$HKULocale) {
				[int32]$HKULocale = '0x' + $HKULocale
				[string[]]$HKULanguages = ([Globalization.CultureInfo]($HKULocale)).Name
			}
		}

**Comment by Fatbob1** [comment]
Back On the desk

I finally out what the problem was. Since I 've found a way to trace the variable -Big deal ;-) - I 've quicly discovered that it was very well detected for the GPO setting BUT after that the script tries to read the variable for "Win 8"... and since, obviously, it does not exist on Win7, it is reset to a nul value. Therefore when it comes to the "free" setting the test sees a null variable and the sets it to the free setting. To make it shorter : the test on Win 8 was missing. 

That's the code that is working for me on Win7 x64 : 

'#  If a user is logged on, then get primary UI language for logged on user (even if running in session 0)
	If ($RunAsActiveUser) {
		#  Read language defined by Group Policy
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKLM\SOFTWARE\Policies\Microsoft\MUI\Settings' -Value 'PreferredUILanguages'
		}
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\SOFTWARE\Policies\Microsoft\Control Panel\Desktop' -Value 'PreferredUILanguages' -SID $RunAsActiveUser.SID
		}
		#  Read language for Win 8 machines
        If (-not $HKULanguages) {
		    [string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\International\User Profile' -Value 'Languages' -SID $RunAsActiveUser.SID
        }
		#  Read language for Win Vista/Win 7 machines
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\Desktop' -Value 'PreferredUILanguages' -SID $RunAsActiveUser.SID
		}
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\Desktop\MuiCached' -Value 'MachinePreferredUILanguages' -SID $RunAsActiveUser.SID
		}
		If (-not $HKULanguages) {
			[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Control Panel\International' -Value 'LocaleName' -SID $RunAsActiveUser.SID
		}
		#  Read language for Win XP machines
		If (-not $HKULanguages) {
			[int32]$HKULocale = Get-RegistryKey -Key 'HKCU\Control Panel\International' -Value 'Locale' -SID $RunAsActiveUser.SID
			If ([string]$HKULocale) {
				[int32]$HKULocale = '0x' + $HKULocale
				[string[]]$HKULanguages = ([Globalization.CultureInfo]($HKULocale)).Name
			}
		}

**Comment by mmashwani** [comment]
Thanks for testing out the beta 3.6.4. I've made the appropriate changes as discussed above. Please test the latest code again and let me know if it's working as expected.

**Comment by Fatbob1** [comment]
Hi I'll will test on thursday and let you know 

Best regards

**Comment by Fatbob1** [comment]
Hi 

So I did all the test i could foresee and it works well in any configuration on Win7x64 except in only in one case : the User GPO. The right registry key is 
'HKCU\Software\Polices\Microsoft\Control Panel\Desktop' 
and in the code it is : 
'HKCU\Software\Polices\Control Panel\Desktop'  (line 254) : 'Microsoft' key is missing 

Best regards

**Comment by mmashwani** [comment]
Great, thanks for all your help. I've updated the code with the right key.
