### ISSUE TITLE
Any way to pass arbitrary parameters to Deploy-Application.exe?

### ISSUE THREAD

**Issue by DSBloom** [PSAppDeployToolkit/PSAppDeployToolkit#200]
Is there any way to pass "custom" parameters to Deploy-Application.exe? 

For example:
`Deploy-Application.exe /MyParam`

So that later in the Deploy-Application.ps1 script we can perform certain actions if /MyParam was used?

Whenever I try and do something like that Deploy-Applicaiton.exe just doesn't launch.

**Comment by That-Annoying-Guy** [comment]
I have never used DeployApplication.exe and I'm weak in CS but from what I can tell from the source code in DeployApplication.cs, it seem you need to do it this way:

Deploy-Application.exe -File "<Path to Deploy-Application.ps1>" -Command "Params"

But this is but a pure guess.  Deploy-Application.exe is not a fully supported feature of PSADT. Your best bet is to poke around the website for other mentions of Deploy-Application.exe.

**Comment by nadcraker** [comment]
Thanks for the tip. I'll look into that. But it looks like the Deploy-Application.ps1 file validates the parameters, and won't accept anything that it is not expecting.
`

	Param (
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[string]$StatusMessage = $configProgressMessageInstall,
		[Parameter(Mandatory=$false)]
		[ValidateSet('Default','BottomRight')]
		[string]$WindowLocation = 'Default',
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[boolean]$TopMost = $true
	)`

**Comment by That-Annoying-Guy** [comment]
So.
Just follow the pattern and add the parameters you need to Deploy-Application.ps1
I do this all the time.

I don't think this is a bug in PSADT other than Deploy-Application.exe needs to be documented. I know there was talk to officially support it in a future major version like v4. 
Time will tell.

**Comment by nadcraker** [comment]
Well, I was hoping to leave PSADT as 'stock' as possible, but your suggestion is simple enough to implement and see how it goes.

So I'll change my Deploy-Application.ps1 CMDLETBINDING section to look like this:


'Param (
	[Parameter(Mandatory=$false)]
	[ValidateSet('Install','Uninstall')]
	[string]$DeploymentType = 'Install',
	[Parameter(Mandatory=$false)]
	[ValidateSet('Interactive','Silent','NonInteractive')]
	[string]$DeployMode = 'Interactive',
	[Parameter(Mandatory=$false)]
	[switch]$AllowRebootPassThru = $false,
	[Parameter(Mandatory=$false)]
	[switch]$TerminalServerMode = $false,
	[Parameter(Mandatory=$false)]
	[switch]$DisableLogging = $false,
    [Parameter(Mandatory=$false)]
    [string[]]$CustomParams
)
`

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/any-way-to-pass-arbitrary-parameters-to-deploy-application-exe/1213

**Comment by mjr4077au** [comment]
This already works fine from my testing:

![image](https://github.com/user-attachments/assets/ccf6d687-a85b-470d-8b6f-b6c7ab8e2668)
![image](https://github.com/user-attachments/assets/743fd0b8-0672-4945-9a77-2156623dc0e4)
