### ISSUE TITLE
Show-InstallationWelcome should have $TestIfRunningOnly switch

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#202]
Hi Guys,
Show-InstallationWelcome can detect if an app is running but I can't use it to return $true/$false if one of the apps in the $CloseApps list is running.

What if I need to Exit because of time of day?
What if I need to kill processes in a specific order?
What if we have a "Don't close an app for an install" policy?

The latter is my current case and I just replicated some of Show-InstallationWelcome's code to do it.

I don't know if Show-InstallationWelcome already returns anything but code like the following should be easy to add to the Show-InstallationWelcome function:

```
    If ($TestIfRunningOnly) {
        $runningProcesses = Get-RunningProcesses -ProcessObjects $processObjects
        [string]$runningProcessDescriptions = ($runningProcesses | Where-Object { $_.ProcessDescription } | Select-Object -ExpandProperty 'ProcessDescription' | Select-Object -Unique | Sort-Object) -join ','
        Write-log "The following from the `$CloseApps list were found running: [$runningProcessDescriptions]" -Severity 2
        Return $true
    }
```

What do you think?
(BTW: Would you guys prefer Pull Requests instead? Can you guys use Pull Requests from a private or hidden fork on GitHub? )

**Comment by MortenRoenborg** [comment]
Hi guys

Just an addition to your post. We deploy all apllications with silent parameters, and detect if the process needed closed is open, and changes the deploymethod if it is. As shown below:

`	[string]$appsToClose = 'aura,excel'
	$appsToCloseDeploymode = $appsToClose.Split(",")
		
# Determines deployment method, if no applicattions open, then silent install
		$appsToCloseDeploymode | ForEach-Object {
			if (Get-Process "$_" -ErrorAction SilentlyContinue) {
				write-log "Process $_ is running switching silentmode off..."
				$deployModeSilent = $false
			}
		}
Show-InstallationWelcome -CloseApps $appsToClose -MinimizeWindows $false -AllowDefer -DeferTimes "3"`

**Comment by Hedkandi** [comment]
"What if we have a "Don't close an app for an install" policy?" - This is exactly what we have in my workplace. I changed the behaviour to exit with a specific exitcode incase running in silent mode and application is running. If we want to force this we use the -silent switch on Show-InstallationWelcome. I would love to see some sort of change to this. SCCM have this function builtin from 1702 and it exits with an exitcode when application is running, unless forced. - https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1702#application-management

**Comment by Hedkandi** [comment]
Maybe let it fallback to defer is silent mode is used?

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-installationwelcome-should-have-testifrunningonly-switch/1244

**Comment by mjr4077au** [comment]
The v4 preview will have a SessionDetection boolean in the config where you can turn off any Session 0 DeployMode manipulation, which should address the concern. With SessionDetection set to $false, it'll be up to you to ensure that the user can see your interactive dialog while running as SYSTEM (either via the right checkboxes in SCCM, or via ServiceUI, etc).
