### ISSUE TITLE
Using Start-Process, always returns 1 on any error

### ISSUE THREAD

**Issue by JamesH7** [PSAppDeployToolkit/PSAppDeployToolkit#203]
I have to launch the tool outside of an sccm environment, and I have an issue that could be addressed by adjusting how the script exits.

Could the exit-script function be adjusted to use the following for exiting?
    $host.SetShouldExit($ExitCode) 
    Exit

The problem is encountered when the script is ran through Start-Process.

It appears to be a known thing with powershell. 
testExit.ps1
exit 55
# $host.setshouldexit(55)
# Exit

You can launch PowerShell and test it.
$info = start-process -filepath "powershell.exe" -ArgumentList {"c:\temp\testExit.ps1"} -PassThru -wait
$info.exitcode

**Comment by That-Annoying-Guy** [comment]
Welcome to the "SCCM doesn't always fit" club.

We have to launch EVERYTHING with a CMD wrapper and this includes PSAppDeployToolkit

So we create a Deploy-Application.CMD with something like this:

	set "_Powershell=%SYSTEMROOT%\%_SYSROOTCORE%\WindowsPowerShell\v1.0\powershell.exe"
	"%_Powershell%" -ExecutionPolicy Bypass "& '%~dp0%FN%.ps1' Install NonInteractive "; exit $LASTEXITCODE
	SET ERR=%ERRORLEVEL%
	Echo [%~NX0] RESULT CODE=%ERR%
	TIMEOUT.exe /T 10 /NOBREAK 1>nul 2>nul
	EXIT /B %ERR%

We get our PS ExitCodes as CMD/Batch ERRORLEVEL with 2 caveats:

1. We may get the wrong ExitCode in PowerShell 2 (E.g. PS syntax error = ERRORLEVEL 0 )
2. If PS ExitCode is higher than 65536, CMD *MAY* Rollover the ExitCode before it becomes an ERRORLEVEL (IOW ExitCode 65536 ==> ErrorLevel 0)

**Comment by amotaz** [comment]
There's a method for avoiding this issue outlined in the top of the script deploy-application.ps1
