### ISSUE TITLE
Unclear parameter descriptions for Show-InstallationWelcome

### ISSUE THREAD

**Issue by macxcool** [PSAppDeployToolkit/PSAppDeployToolkit#204]
There are a couple of unclear descriptions for the parameters of Show-InstallationWelcome. Since this is a complex function with many parameters it's important for these to be very precise.

PersistPrompt - 'Specify whether to make the prompt persist...'. It is unclear which prompt. Since the switch comes immediately after 'PromptToSave', is this the prompt being referenced?

BlockExecution - '... the process/application...'. It should be made clear that these are the processes referred to in 'CloseApps'. Also, I assume that this is ignored if there is no 'CloseApps' specified.

AllowDefer and AllowDeferCloseApps - Are these meant to be mutually exclusive? What happens if you specify both?

**Comment by amotaz** [comment]
We'll have a solution in the future to avoid this confusion.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/unclear-parameter-descriptions-for-show-installationwelcome/1226
