### ISSUE TITLE
Show-InstallationProgress not showing all content

### ISSUE THREAD

**Issue by MortenRoenborg** [PSAppDeployToolkit/PSAppDeployToolkit#205]
Hi guys
By making new lines, the window doesn't show all the text content. I'm using v.3.6.7 of the main script.
![image](https://cloud.githubusercontent.com/assets/15209121/18091569/64882064-6ec9-11e6-8900-408d7be96e68.png)
Has this been resolved in a newer version of the toolkit? 
Thanks

**Comment by toughen** [comment]
I hope it's OK to post this here.

My workaround for this was to change either the width/height or font size in the XAML. This starts at line 6890 in AppDeployToolkitMain.ps1 (v3.6.8). Also the RowDefinition Height is static, so I changed that to "*" too.

**I have no history on this so obviously do your own testing and beware that this may cause other issues.**

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-installationprogress-not-showing-all-content/1235
