### ISSUE TITLE
ForceCountdown in Show-InstallationWelcome causes an endless loop

### ISSUE THREAD

**Issue by macxcool** [PSAppDeployToolkit/PSAppDeployToolkit#206]
If I use -CloseApps, one of those apps is running and I use AllowDefer with ForceCountdown, an endless loop is created where the app isn't killed and the 'Continue' prompt is shown over and over with the following in the log file, over and over:
`[Pre-Installation] :: Function Start   Get-RunningProcesses    8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Function invoked with bound parameter(s): 

Parameter         Value                                       

---

[-ProcessObjects] @{ProcessName=iexplore; ProcessDescription=}
[-OutVariable]    runningProcesses                            

```
Get-RunningProcesses    8/31/2016 8:34:09 AM    5516 (0x158C)
```

[Pre-Installation] :: Check for running application(s) [iexplore]...    Get-RunningProcesses    8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: The following processes are running: [iexplore].  Get-RunningProcesses    8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Resolve process descriptions...   Get-RunningProcesses    8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Finished checking running application(s). Get-RunningProcesses    8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Function End  Get-RunningProcesses    8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Function Start    Show-WelcomePrompt  8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Function invoked with bound parameter(s): 

Parameter                  Value            

---

[-MinimizeWindows]         True  
[-PersistPrompt]           False  
[-ForceCloseAppsCountdown] False  
[-ProcessDescriptions]     Internet Explorer
[-CustomText]              False  
[-TopMost]                 True  
[-ForceCountdown]          1  
[-CloseAppsCountdown]      0                

```
Show-WelcomePrompt  8/31/2016 8:34:09 AM    5516 (0x158C)
```

[Pre-Installation] :: Prompt user to close application(s) [Internet Explorer]...    Show-WelcomePrompt  8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Countdown has [0] seconds remaining.  Show-WelcomePrompt  8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Countdown timer has elapsed. Force continue.  Show-WelcomePrompt  8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: Function End  Show-WelcomePrompt  8/31/2016 8:34:09 AM    5516 (0x158C)
[Pre-Installation] :: User selected to continue...  Show-InstallationWelcome    8/31/2016 8:34:09 AM    5516 (0x158C)
`

**Comment by amotaz** [comment]
This issue is resolved if you use ForceCloseAppsCountdown parameter rather than just ForceCountdown. The behavior of these parameters is a bit confusing, because there are a lot of different cases we're covering. So I think in the next major version I'll put in some parameter set logic to cover this type of situation, however for now, it would be a major breaking change. Please test by configuring ForceCloseAppsCountdown and let me know if that resolves the issue.

**Comment by suprnova74** [comment]
I've run into this as well when trying to use -allowdefer while also checking for apps to close both with a countdown and figured a workaround.  you cannot use "-Allowdefer -forcecountdown xxx" combined with -closeapps -forcecloseappscountdown xxx.  If you use -allowdefer without the -forcecountdown combined with the -forcecloseappscountdown, it will never close once the closeappscountdown reaches zero.  

The workaround is to call the -defer check first, then the closeapps.  It uses two separate pop-ups and timers, but it works.  An example:

#first, check for deferal
	    Show-InstallationWelcome -AllowDefer -DeferTimes 5 -ForceCountdown 300
#now check for apps and provide closeapp delay
		Show-InstallationWelcome -CloseApps 'communicator=Microsoft Office Communicator,outlook=Microsoft Office Outlook,lync=Microsoft Lync,iexplore=Microsoft Internet Explorer' -ForceCloseAppsCountdown 300 -BlockExecution -PersistPrompt

**Comment by amotaz** [comment]
We'll have a solution in the future to avoid this confusion by using parameter sets

**Comment by CodaAmok** [comment]
I used the below and also encountered this issue

> Show-InstallationWelcome -CloseApps 'WINWORD,ONENOTE,OUTLOOK,POWERPNT,EXCEL,MSACCESS,MSPUB,lync,VISIO,WINPROJ' -BlockExecution -AllowDeferCloseApps -ForceCountdown 10 -DeferTimes 3 -RequiredDiskSpace 4000 -CheckDiskSpace -MinimizeWindows $false -CustomText $true

Just a continuation of the below for hours on an overnight test

```
[Pre-Installation] :: Check for running application(s) [WINWORD,ONENOTE,OUTLOOK,POWERPNT,EXCEL,MSACCESS,MSPUB,lync,VISIO,WINPROJ]...	Get-RunningProcesses	23/06/2017 02:51:11	1056 (0x0420)
[Pre-Installation] :: The following processes are running: [WINWORD].	Get-RunningProcesses	23/06/2017 02:51:11	1056 (0x0420)
[Pre-Installation] :: Resolve process descriptions...	Get-RunningProcesses	23/06/2017 02:51:11	1056 (0x0420)
[Pre-Installation] :: Finished checking running application(s).	Get-RunningProcesses	23/06/2017 02:51:11	1056 (0x0420)
[Pre-Installation] :: Prompt user to close application(s) [Microsoft Word]...	Show-WelcomePrompt	23/06/2017 02:51:11	1056 (0x0420)
[Pre-Installation] :: User has the option to defer.	Show-WelcomePrompt	23/06/2017 02:51:11	1056 (0x0420)
[Pre-Installation] :: Countdown has [0] seconds remaining.	Show-WelcomePrompt	23/06/2017 02:51:11	1056 (0x0420)
[Pre-Installation] :: Countdown timer has elapsed. Force continue.	Show-WelcomePrompt	23/06/2017 02:51:11	1056 (0x0420)
[Pre-Installation] :: User selected to continue...	Show-InstallationWelcome	23/06/2017 02:51:11	1056 (0x0420)
```

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/forcecountdown-in-show-installationwelcome-causes-an-endless-loop/1223

**Comment by RowdyChildren** [comment]
Modifying lines 6267 thru 6278 to include the following
```
				If ($countdownTime -lt $currentTime) {
					If ($forceCountdown -eq $true) {
						Write-Log -Message 'Countdown timer has elapsed. Force continue.' -Source ${CmdletName}
						$buttonContinue.PerformClick()
						$buttonCloseApps.PerformClick()
					}
					Else {
						Write-Log -Message 'Close application(s) countdown timer has elapsed. Force closing application(s).' -Source ${CmdletName}
						$buttonCloseApps.PerformClick()
						$buttonContinue.PerformClick()
					}
				}
```

seems to re mediate the issue, we are adding $buttonCloseApps.PerformClick() and $buttonContinue.PerformClick() to the respective if statements. I am looking at a more elegant solution than this but if anyone runs into this issue you can solve it the the above .

**Comment by luki1412** [comment]
This is not really a bug. It is a bad design decision. If you use -ForceCountdown the toolkit with start a countdown and when it reaches 0, it will click the Continue button. The continue button however does not close processes, it just checks whether the user closed them. If they are still open, the window will popup again but since the timer is still at 0, it will click the Continue button again, turning it into an endless loop, until the user closes the programs.

What you should do instead is to use -ForceCloseAppsCountdown which will click the Close Apps button instead, closing the programs forcefully.

We are going to remove the Continue button in v4 as it doesn't really achieve anything. For now, please use -ForceCloseAppsCountdown when you specify -CloseApps
