### ISSUE TITLE
Get-InstalledApplication Returns Incorrect UninstallString

### ISSUE THREAD

**Issue by pchatham** [PSAppDeployToolkit/PSAppDeployToolkit#208]
Hello,

I am trying to get the Uninstall Path String of various apps and I am running into an issue.
The Uninstall String is duplicated and therefore returning errs when using it to uninstall apps.

`(Get-InstalledApplication -Name "App" -Exact).UninstallString`

When ran locally is returns
`"C:\ProgramPath\Folder\App.exe"`

When ran using SCCM as system using:

`powershell.exe -ExecutionPolicy bypass -NonInteractive -noprofile -File .\Deploy-Application.ps1 -DeploymentType UnInstall -DeployMode Silent -Verbose`

it Returns

`"C:\ProgramPath\Folder\App.exe  C:\ProgramPath\Folder\App.exe"`

**Comment by amotaz** [comment]
Hi pchatham, I am not able to reproduce this issue, and investigating the code, I cannot see where this might be caused. Can you provide a log file and a exported reg file of the targeted application?
