### ISSUE TITLE
LogName parameter in Execute-MSI should detect when a path or extension is given.

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#209]
```
Execute-MSI -Action Uninstall -Path '{ABCDEF00-0000-0000-0000-000000000000}' -LogName "c:\Temp\ThatAnnoyGuyMSITEst.log" 

Executing [C:\Windows\system32\msiexec.exe /x "{ABCDEF00-0000-0000-0000-000000000000}" ALLUSERS=1 ROOTDRIVE=C:\ REBOOT=ReallySuppress /QN /L*v "<Toolkit_LogPath>\Deploy-Application_v1r1\c:\Temp\ThatAnnoyGuyMSITEst.log_Uninstall.log"]...
[09-07-2016 12:38:40.016] [Installation] [Get-MsiExitCodeMessage] :: Get message for exit code [1622].
[09-07-2016 12:38:40.024] [Installation] [Execute-Process] :: Execution failed with exit code [1622]: Error opening installation log file.  Verify that the specified log file location exists and is writable.
```

Instead, Execute-MSI Should throw an error like "Parameter is logNAME not LogPATH!".
.
.

```
Execute-MSI -Action Uninstall -Path '{ABCDEF00-0000-0000-0000-000000000000}' -LogName "MSITEST_Remove.log"

[09-07-2016 12:45:18.561] [Installation] [Execute-Process] :: Executing [C:\Windows\system32\msiexec.exe /x "{ABCDEF00-0000-0000-0000-000000000000}" ALLUSERS=1 ROOTDRIVE=C:\  REBOOT=ReallySuppress  /QN /L*v "<Toolkit_LogPath>\Deploy-Application_v1r1\MSITEST_Remove.log_Uninstall.log"]...
```

Instead, Execute-MSI Should respect the extension given or throw an error like "Parameter is logNAME not LogNameAndExt!".

.
.
Then we have the gratuitous _Uninstall appended. E.g. (MSITEST_Remove.log_Uninstall.log)
I agree something like this is needed since by default PSADT chucks all the log files into one folder.
In my shop we have had _Remove appended to all our log files when an uninstall is done for the past 15+ years and since I started to use PSADT I've modified it to tack on _Remove to the main log. Then somewhere around v3.6.8 this became an issue.

I could just change the one line in Execute-MSI to have _Remove appended instead of _Uninstall but I would have to do it everytime a new version of PSADT comes out.
Or the following line could be added to Execute-MSI:

```
'Remove' { $option = '/x'; [string]$msiLogFile = "$logPath" + '_Remove'; $msiDefaultParams = $msiUninstallDefaultParams }
```

Another enhancement would be to throw an error if $logname ends with Install, _Patch, _Repair, _ActiveSetup, _Remove or _Uninstall since Execute-MSI adds these labels automatically.

As always, the final decision is your.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/logname-parameter-in-execute-msi-should-detect-when-a-path-or-extension-is-given/1219

**Comment by mjr4077au** [comment]
The parameter in our v4 branch is now called `-LogFileName` for clarity. Your gratuitous example above shouldn't be able to occur anymore either.
