### ISSUE TITLE
Execute-ProcessAsUser needs WorkingDirectory parameter

### ISSUE THREAD

**Issue by macxcool** [PSAppDeployToolkit/PSAppDeployToolkit#210]
I'm trying to have GPU Caps Viewer dump an XML file where I want it to. It needs to be run as a user and it drops an xml file in the current working directory. When I run the script as System it wants to put the xml file in C:\Windows\System32 (I think because the working directory set up for the schtasks exe is there) but the user doesn't have rights to do that, of course.
I'd like to be able to set the working directory in the Execute-ProcessAsUser function.

**Comment by That-Annoying-Guy** [comment]
In  Execute-ProcessAsUser function there is a here-string containing an XML file used to create the task. a portion is this:

	<Exec>
	  <Command>$Path</Command>
	  <Arguments>$Parameters</Arguments>
	</Exec>

Change it to this to add $WorkingDirectory 

	<Exec>
	  <Command>$Path</Command>
	  <Arguments>$Parameters</Arguments>
	  <WorkingDirectory>$WorkingDirectory </WorkingDirectory>
	</Exec>

To create the $WorkingDirectory parameter in the Execute-ProcessAsUser function, change this part in the parameters section:

		[Parameter(Mandatory=$false)]
		[ValidateNotNullOrEmpty()]
		[boolean]$ContinueOnError = $true
	)

to this:

		[Parameter(Mandatory=$false)]
		[ValidateNotNullOrEmpty()]
		[String]$WorkingDirectory = $envSystem32Directory
		[Parameter(Mandatory=$false)]
		[ValidateNotNullOrEmpty()]
		[boolean]$ContinueOnError = $true
	)

CAVEATS: Does not test if $WorkingDirectory is a valid path that exists.

**Comment by macxcool** [comment]
OK. I've tested it. Your solution works. All that's needed is some logic to validate the path. Man that's a lot easier than trying to get psexec to do this ;-).
I know this likely won't be going into 3.6.9, but can it go into a future version? Very nice.

**Comment by That-Annoying-Guy** [comment]
I don't know. I'm not part of the "Inner Circle".
I'm just a user like you.
I just happen to maintain a heavily modified private fork.

Amotaz done check-in once in a while and seems to have rights to the repository...

**Comment by macxcool** [comment]
@That-Annoying-Guy Is there any downside, that you know of, to always putting a working directory into the XML? I'd think that the parent folder of the executable could be the default.
I was also thinking that, maybe, a null string could be there by default (the task scheduler should ignore that, shouldn't it).
I don't like messing with the main script. I'd rather add a modified version of the function to the extensions file if I really need to.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/execute-processasuser-needs-workingdirectory-parameter/1224
