### ISSUE TITLE
removes network shares after script ends

### ISSUE THREAD

**Issue by Symbiot78** [PSAppDeployToolkit/PSAppDeployToolkit#211]
Hi

I am mapping different network shares in a psappdeploy script but at the end it removes all mapped shares.  ( not by design :) )

I created the script earlier on but adapted it to psappdeploy to get some niceness and features added.... as standalone script it works just fine and doesn't remove the newly created shares.

I posted in the forum but thought I'd add it here if it's a bug..

here's a link to the post including the script...

http://psappdeploytoolkit.com/forums/topic/psapp-doesnt-something-quirky-when-using-new-psdrive/

**Comment by Symbiot78** [comment]
This occurs when using the script via the established VPN but NOT when domain-joined.

**Comment by That-Annoying-Guy** [comment]
Known new-psdrive issue.
FYI: Do not double post into issue section!

**Comment by Symbiot78** [comment]
ok, so it's a known issue and of course not a psappdeploy issue.

if anyone stumbles past this post I tried adding:

-scope global

and it seems to persist the drives now.
