### ISSUE TITLE
Refresh-Desktop (sporadically) stalling script execution on Win10 system.

### ISSUE THREAD

**Issue by LMCO-psadt-devs** [PSAppDeployToolkit/PSAppDeployToolkit#212]
Below was the last visible line in the log before forcibly terminating the script. The Deploy-Application.ps1 script execution remained in this state until following day.

> [Pre-Uninstallation] :: Refresh the Desktop and the Windows Explorer environment process block.

As mentioned in the title this behavior is sporadic, however, when it occurs the Deploy-Application.ps1 script execution does **not** time out. I recommend that a timeout parameter be added to the Refresh-Desktop function to allow the script to continue in the event that the Refresh-Desktop stalls during the Deploy-Application.ps1 script's execution.

**Comment by amotaz** [comment]
Question, are you specifically calling refresh-desktop during your pre-uninstallation phase? If not, can you paste in deploy-application code
