### ISSUE TITLE
Error on Get-PendingReboot

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#213]
Hi,

I am getting this error. We are running Windows 8.1 french and sccm 2012 R2 and PSADT 3.6.8
We are launching:
`Set-StrictMode -off
	$Var_PendingReboot=Get-PendingReboot
Set-StrictMode -Version Latest`

`[09-20-2016 14:46:55.030] [Pre-Installation] [Test-RegistryValue] :: Registry key value [Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager] [P
endingFileRenameOperations] does not exist.
[09-20-2016 14:46:56.483] [Pre-Installation] [Get-PendingReboot] :: Failed to get IsSCCMClientRebootPending. 
Error Record:
-------------

Message        : 
InnerException : 

FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.InvokeWmiMethod
ScriptStackTrace      : à Get-PendingReboot<Process>, C:\Sovgarde\WordQ4.0.96.0_Frv1\_Include\AppDeployToolkit\AppDeployToolkitMain.ps1 : ligne 9965
                        à <ScriptBlock>, C:\Sovgarde\WordQ4.0.96.0_Frv1\WordQ4.0.96.0_Frv1.ps1 : ligne 554

PositionMessage : Au caractère C:\Sovgarde\WordQ4.0.96.0_Frv1\_Include\AppDeployToolkit\AppDeployToolkitMain.ps1:9965 : 41
                  +                 [psobject]$SCCMClientRebootStatus = Invoke-WmiMethod -ComputerName $Computer ...
                  +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by That-Annoying-Guy** [comment]
I think this is your problem:

     System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.InvokeWmiMethod

You should be running WordQ4.0.96.0_Frv1.ps1 as an **elevated** administrator.
Are you?

If not, I am amazed that the script go that far.

**Comment by FRacine** [comment]
Yes I am running the script with elevated privileged. The script is running fine but I got this exception when checking for Get-PendingReboot.

**Comment by amotaz** [comment]
where you able to resolve this?

**Comment by FRacine** [comment]
Seems the SCCM client was not ok. I got this on VM Machine.

**Comment by amotaz** [comment]
ok, cool. Feel free to reopen if you find it was the toolkit.
