### ISSUE TITLE
Enhancement: Copy-File will not copy psobject

### ISSUE THREAD

**Issue by chstanley** [PSAppDeployToolkit/PSAppDeployToolkit#214]
First off - Love the toolkit, great work! We use it for literally every app we pacakage. It is always stable too, works everytime, so thanks again for the enterprise grade, free tool. :+1: :+1: 

The enhancement i am requesting is small, here are my commands:
`$dllFiles = Get-Childitem -path $dirfiles -filter *.dll`
`Copy-File $dllFiles -Destination $envSystem32Directory`
Error i get:
`Copy-File : Cannot process argument transformation on parameter 'Path'. Cannot convert value to type System.String`

It doesnt like my $dllfiles object.
Let me know if you need additional information.
Thanks!
~chstanley

**Comment by bruckect** [comment]
Since you are using Get-ChildItem it is going to return multiple properties. Have you tried using the FullName property like you would if you used the built-in Copy-Item cmdlet?
`Copy-File -Source $($dllFiles.FullName) -Destination $envSystem32Directory`

**Comment by chstanley** [comment]
@bruckect : I tried your suggestion but unfortunately, i got the same error message.
> like you would if you used the built-in Copy-Item cmdlet
If i were to use the copy-item cmdlet, i wouldnt have to use the `FullName` property, i would just do:
`Copy-Item -Path $dllFiles -Destination $envSystem32Directory`
and it would work just fine.
~chstanley

**Comment by DennisVH** [comment]
Can you try changing the Path string parameter to an array of strings in the Copy-File function.
`[string]$Path,` to `[string[]]$Path,`

**Comment by amotaz** [comment]
HI chstanley, Did DennisVH's suggestion fix your issue?

**Comment by DennisVH** [comment]
This will be resolved in the next release

**Comment by seanlillis** [comment]
This is included in v3.7.0.
