### ISSUE TITLE
Use in SCCM Applications with user interaction

### ISSUE THREAD

**Issue by Pollewops** [PSAppDeployToolkit/PSAppDeployToolkit#217]
I use AppDeployToolkit and am very happy with it !

I use it in SCCM Current Branch and have an issue when using it when Application deployment.
To be able to interact to the user the application needs to be configured "Only when a user is logged on" and check "Allow users to view and interact with the program installation".
That is working fine.

But..when I want to use the same application for deployment using a Task Sequence it is not working due to the assignment to "Only when a user is logged on".
If I change it to "Whether or not a user is logged on" the application will silently install during the Task Sequence, but the interaction when deploying to a logged on user is not available :-(

How to fix this ? Any help or assistance appreciated.

**Comment by z442a9** [comment]
Use ServiceUI.exe.

Take a look at this for example:

http://deploymentresearch.com/Research/Post/270/Troubleshooting-CM2012-Task-Sequence-Actions-Using-ServiceUI

**Comment by yulasinio** [comment]
You can use serviceUI, create another deployment type to install for system whether or not the user is logged on or create package's which work a lot better in TS.

**Comment by Paradox355** [comment]
Application model is really finicky when it comes to task sequences. Best bet it to create separate one with single deployment type configured as needed, and only use that for OSD. Or just use packages like yulasinio suggested, they work way better for OSD.
