### ISSUE TITLE
Preexistence of the package

### ISSUE THREAD

**Issue by chalamsoft** [PSAppDeployToolkit/PSAppDeployToolkit#218]
I could not able to find any example script(deploy-Application.ps1) to find the preexistence of the setup.exe application installed using a key file or registry. how to fill the INSTALLCHECKVARIABLE section

**Comment by That-Annoying-Guy** [comment]
There is no reference to "INSTALLCHECKVARIABLE" in PSADT.
Even Google does not know what "INSTALLCHECKVARIABLE" is.

Please re-word your question.
