### ISSUE TITLE
Using Deferrals with SCCM Application Model

### ISSUE THREAD

**Issue by HighflyIs** [PSAppDeployToolkit/PSAppDeployToolkit#220]
At the moment we are having some issues trying to use the AppDeploy Toolkit with the application model in SCCM. We currently give users 3 deferrals with 24 hours between notifications. We set the applications to install at different times in the day. That was working without issue with the packaging model, where we were able to set the installation to re-run each day if the install failed (installation is classed as  a failure if the user defers). We are using SCCM 2012 R2 SP1.

We are now trying to use the Application model and take advantages of the benefits that come with Applications vs Packages. Each time that SCCM runs the "Application Deployment Evaluation Cycle" in SCCM then the notification pops up and takes one off the number of deferrals remaining. Is there a way to stop the number going down if the user has already been notified of the application within the last 24 hours?

We could set the "Application Deployment Evaluation Cycle" to only run every 24 hours but then all our applications would try to deploy at that time rather than the original deployment time +24 hours.

We would still need the user to be able to run the application on demand from the Software Center.

Any help would be appreciated.

**Comment by yulasinio** [comment]
Can you not use a date base deferral instead of using a set numbers of deferrals?
For Example:
`Show-InstallationWelcome -AllowDefer -DeferDeadline '23/11/2016'`

**Comment by amotaz** [comment]
This is a request that would fall under a major revision. I would suggest using the DeferDeadline parameter suggested by yulasinio above. It's not the cleanest to manage, but should work. We'll take into consideration your request for the next major revision.

**Comment by dersonc** [comment]
I have something like this as an extension and added a trigger for it when the users defer the install. I published it in the forum at http://psappdeploytoolkit.com/forums/topic/function-to-trigger-and-application-evaluation-cycle-after-a-specified-time/

**Comment by seanlillis** [comment]
You could use the DeferDays parameter so that the deferral count does not reduce irrespective of how many times in a day the App Deployment Eval cycle has run and the user has opted to defer. You can combine it with DeferDeadline to set a final deadline for the installation.
