### ISSUE TITLE
Get-InstalledApplication doesn't perform actual RegEx search by default

### ISSUE THREAD

**Issue by agadzevych** [PSAppDeployToolkit/PSAppDeployToolkit#222]
Get-InstalledApplication doesn't perform RegEx search on "Display Name", as it's stated in Help.

Reason: RegEx special characters are escaped, so below line is equivalent to strict string comparison. 

Line: 2007  $regKeyApp.DisplayName -match [regex]::Escape($application)

**Comment by amotaz** [comment]
I added a -regex tag and modified the language in the help text. Please test and verify.
