### ISSUE TITLE
deploy-application.exe 64 Bit

### ISSUE THREAD

**Issue by edi8** [PSAppDeployToolkit/PSAppDeployToolkit#223]
Hi, 

I'm having a problem with an ADT script, where I try to uninstall a bunch of applications. These are 64 Bit applications and - as we want to have userinteraction, but don't want to display the powershell window, we start the ADT using the "deploy-application.exe". Now the problem is, that the deploy-application.exe is a 32 bit process and therefore always starts the 32 Bit powershell. This means, that the "get-installedapplications" function will not find any installed 64 bit application. 

Any help/solution for this (except starting the deploy-application.ps1 directly)?! 

thanks, 
best regards, 
edi

**Comment by amotaz** [comment]
This is likely an issue with your software delivery method. Check the tool you're using to deploy and make sure its not running or set to run the deploy-application.exe as a 32-bit application.

 I just tested to confirm, searching for apps under both uninstall keys without any problem.
