### ISSUE TITLE
Invoke-HKCURegistrySettingsForAllUsers failing on ContinueOnError

### ISSUE THREAD

**Issue by jacobeSCCM** [PSAppDeployToolkit/PSAppDeployToolkit#227]
Invoke-HKCURegistrySettingsForAllUsers fails while applying user settings. The first reg value is successfully changed, but the second one fails. Even when ContinueOnError's value is not changed, this cmdlet fails when processing that value. Some values have been changed below to preserve anonymity.

Stack:
## <Create script block for HKCU Policy Reg keys>

                              [scriptblock]$HKCURegistrySettings = {
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\Common\WebIntegration' -Name 'WebIntegrationEnabled' -Value 0 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\Common\internet' -Name 'UseOnlineContent' -Value 0 -Type DWord -SID $UserProfile.SID.
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\Common\internet' -Name 'BasicAuthLevel' -Value 2 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\outlook\Preference' -Name 'DisableManualArchive' -Value 0 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\outlook\Preference' -Name 'DoAging' -Value 0 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\outlook\Security' -Name 'PromptForCredentials' -Value 0 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\outlook' -Name 'DisableAntiSpam' -Value 1 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\word\options\assist' -Name 'fSmartQuote_8_1' -Value 0 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\common\general' -Name 'skydrivesigninoption' -Value 3 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\common\general' -Name 'OptInDisable' -Value 1 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\common\signin' -Name 'signinoptions' -Value 1 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Registration' -Name 'AcceptAllEulas' -Value 1 -Type DWord -SID $UserProfile.SID
                                            Set-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Microsoft\CTF\LangBar' -Name 'ShowStatus' -Value 3 -Type DWord -SID $UserProfile.SID
                              }
                              Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $HKCURegistrySettings

Errors (first one, same error for each line above):

<![LOG[[Post-Installation] :: Get the User Profile Path, User Account SID, and the User Account Name for all users that log onto the machine.]LOG]!><time="13:33:02.071-300" date="11-29-2016" component="Get-UserProfiles" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Convert the SID [S-1-5-18] to an NT Account name.]LOG]!><time="13:33:02.398-300" date="11-29-2016" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Convert the SID [S-1-5-19] to an NT Account name.]LOG]!><time="13:33:02.535-300" date="11-29-2016" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Convert the SID [S-1-5-20] to an NT Account name.]LOG]!><time="13:33:02.599-300" date="11-29-2016" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Convert the SID [S-1-5-21-3283536547-2396439389-1474086371-532564] to an NT Account name.]LOG]!><time="13:33:02.664-300" date="11-29-2016" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Convert the SID [S-1-5-21-816263271-3694610053-3590786942-1176338] to an NT Account name.]LOG]!><time="13:33:02.869-300" date="11-29-2016" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Convert the SID [S-1-5-21-816263271-3694610053-3590786942-146953] to an NT Account name.]LOG]!><time="13:33:02.945-300" date="11-29-2016" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Convert the SID [S-1-5-21-816263271-3694610053-3590786942-390451] to an NT Account name.]LOG]!><time="13:33:03.005-300" date="11-29-2016" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Convert the SID [S-1-5-21-936965776-983522453-2177657969-500] to an NT Account name.]LOG]!><time="13:33:03.062-300" date="11-29-2016" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Load the User [DOMAIN\Username] registry hive in path [HKEY_USERS\S-1-5-21-3283536547-2396439389-1474086371-532564].]LOG]!><time="13:33:03.535-300" date="11-29-2016" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Execute ScriptBlock to modify HKCU registry settings for all users.]LOG]!><time="13:33:05.047-300" date="11-29-2016" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Return fully qualified registry key path [Registry::HKEY_USERS\S-1-5-21-3283536547-2396439389-1474086371-532564\Software\Policies\Microsoft\Office\Common\WebIntegration].]LOG]!><time="13:33:05.141-300" date="11-29-2016" component="Convert-RegistryPath" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Create registry key [Registry::HKEY_USERS\S-1-5-21-3283536547-2396439389-1474086371-532564\Software\Policies\Microsoft\Office\Common\WebIntegration].]LOG]!><time="13:33:05.191-300" date="11-29-2016" component="Set-RegistryKey" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Set registry key value: [Registry::HKEY_USERS\S-1-5-21-3283536547-2396439389-1474086371-532564\Software\Policies\Microsoft\Office\Common\WebIntegration] [WebIntegrationEnabled = 0].]LOG]!><time="13:33:05.371-300" date="11-29-2016" component="Set-RegistryKey" context="NT AUTHORITY\SYSTEM" type="1" thread="5384" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Failed to modify the registry hive for User [DOMAIN\UserName] with SID [S-1-5-21-3283536547-2396439389-1474086371-532564] 
Error Record:
-------------

Message        : Cannot process argument transformation on parameter 
                 'ContinueOnError'. Cannot convert value "System.String" to 
                 type "System.Boolean". Boolean parameters accept only Boolean 
                 values and numbers, such as $True, $False, 1 or 0.
InnerException : System.Management.Automation.ArgumentTransformationMetadataExc
                 eption: Cannot convert value "System.String" to type 
                 "System.Boolean". Boolean parameters accept only Boolean 
                 values and numbers, such as $True, $False, 1 or 0. ---> 
                 System.Management.Automation.PSInvalidCastException: Cannot 
                 convert value "System.String" to type "System.Boolean". 
                 Boolean parameters accept only Boolean values and numbers, 
                 such as $True, $False, 1 or 0.
                    at System.Management.Automation.ArgumentTypeConverterAttrib
                 ute.ThrowPSInvalidBooleanArgumentCastException(Type 
                 resultType, Type convertType)
                    at System.Management.Automation.ArgumentTypeConverterAttrib
                 ute.Transform(EngineIntrinsics engineIntrinsics, Object 
                 inputData, Boolean bindingParameters, Boolean 
                 bindingScriptCmdlet)
                    --- End of inner exception stack trace ---
                    at System.Management.Automation.ArgumentTypeConverterAttrib
                 ute.Transform(EngineIntrinsics engineIntrinsics, Object 
                 inputData, Boolean bindingParameters, Boolean 
                 bindingScriptCmdlet)
                    at System.Management.Automation.ParameterBinderBase.BindPar
                 ameter(CommandParameterInternal parameter, 
                 CompiledCommandParameter parameterMetadata, 
                 ParameterBindingFlags flags)

FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-RegistryKey
ScriptStackTrace      : at <ScriptBlock>, 
                        C:\windows\ccmcache\u\Deploy-Application.ps1: line 159
                        at Invoke-HKCURegistrySettingsForAllUsers<Process>, C:\
                        windows\ccmcache\u\AppDeployToolkit\AppDeployToolkitMai
                        n.ps1: line 395
                        at <ScriptBlock>, 
                        C:\windows\ccmcache\u\Deploy-Application.ps1: line 173
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\windows\ccmcache\u\Deploy-Application.ps1:159 char:150
                  + ...  -Name 'UseOnlineContent' -Value 0 -Type DWord -SID 
                  $UserProfile.SID.
                  +                                                            
                               ~

**Comment by jacobeSCCM** [comment]
Issue update: this issue was "fixed" by creating one ScriptBlock for every single registry key change. This means that there were 13 total ScriptBlocks created for the 13 keys changed above. This works but is untenable for larger HKCU deployments.

**Comment by amotaz** [comment]
There's a . at the end of the second line. Can you verify that that is not the cause.
