### ISSUE TITLE
Using Write-log to write on a central log

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#229]
Hi,

I need distributing an application to 2000 computers and I would like them writing to a central log. Is it possible to use the write-log function to this purpose? My worry is about more than one computer trying to write simultaneously to the same log.

Thanks,

**Comment by Latupho** [comment]
Don't believe write-log minds several machines write to this log. It's desigend to write to a log, from several Sessions or namespaces, so writing to a central space, with others is okey.
The only Issue I see, is that Write-log don't write from what computer eatche line is from, so I think the log will be hard to write...

My suggestion is to collect the logs from the computers, and copy them to a central system, ordered by Computer name.

I have something that does that here at work, I use BITS to tranfer the files.
More about [bits here](https://blogs.technet.microsoft.com/heyscriptingguy/2012/08/25/weekend-scripter-use-powershell-and-bits-to-simplify-downloading-large-files/).

It will also reduce the noise on the network ALOT.

**Comment by FRacine** [comment]
Hi,

This way it seems to be working;

```
 If ((test-path $Str_EmplacementJournalunifie) -eq $true) { #On teste la disponibilité de l'emplacement réseau

                    If ((test-path $Str_LogAutomove) -eq $false) {

                        Write-log "Initialisation du journal" -LogFilename "$var_PackageName.log" -LogFileDirectory $Str_EmplacementJournalunifie -Severity 1 -Source 'Post-installation'
                    }
 
                    Do {
                        $lockstatus = 0
                        $file = $null
                        $status = $null

                        Try {
                        
                            #Lock File
                            #$file=[System.io.File]::Open("$str_LogAutoMove",'Open','ReadWrite','None')
                            $file=[System.io.File]::Open("$str_LogAutoMove",'Append','Write','Write')
                            $status = "Success"
                        } 
                        Catch {
                        
                            Write-log "Échec du verrouillage du fichier $($str_LogAutoMove)"
                            $status = "Fail"
                        }

                        Write-log "Réussite du verrouillage du fichier $($str_LogAutoMove)"

                        If ($status -eq "Success") {
                        
                            #Check for open handle. If valid, then lock was successful.
                            If ($file.Handle -ne $null) {
                                
                                Write-log "Validation du handle du verrou."
                                $lockstatus = 1
                            }
                        }
                        Else {
                            
                            Write-log "Validation attente."
                            Start-Sleep (Get-Random -Minimum 2 -Maximum 10)
                        }
                        
                        Write-Host "LockStatus = " $lockstatus

                        $Int_Loop=$Int_Loop+1 #On incrémente le compteur afin de ne pas avoir un boucle infinie
                    }
                    Until ($lockstatus -eq 1 -or $Int_Loop -gt $Int_Looplock) #On sort si on a un verrou ou si on arrive au maximum de tentative de verrouillage.
                 
                    If ($lockstatus -eq 1) {

                        Write-Log "$($Strinfo)" -LogFilename "$var_PackageName.log" -LogFileDirectory $Str_EmplacementJournalunifie  -Severity 1 -Source 'Post-installation'
                        Write-Log "$($Strtatouage)" -LogFilename "$var_PackageName.log" -LogFileDirectory $Str_EmplacementJournalunifie  -Severity 1 -Source 'Post-installation'
                    }
                    Else  {Write-log "Pas d'inscription dans le journal $($str_LogAutoMove) faute de verrouillage."}
                
                    $file.Close() #Déverrouillage du fichier
                }
```

Notice:
$file=[System.io.File]::Open("$str_LogAutoMove",'Append','Write','Write')
This is trying to lock the file if failed then it will loop

```
If ($file.Handle -ne $null) {
      Write-log "Validation du handle du verrou."
       $lockstatus = 1
 }
```
This is testing the handle.

Start-Sleep (Get-Random -Minimum 2 -Maximum 10)
This is making sleeping fail lock for different time

At the end:
$file.Close() #Déverrouillage du fichier
To unlock the file.

Thanks,

**Comment by SCHEFFRA** [comment]
It might be technically possible but I have not had any good experiences in writing logfiles over the network by reducing execution performance
of the scripts keeping the files open while execution. Therefore we decided to write the logfiles locally and copy them to network share at the end of the process.

**Comment by Latupho** [comment]
As @SCHEFFRA are saying, is what I understand of the community, also the seen as best practice.
Ons you have a job that can do this, it's good to have, and easy to reuse.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/using-write-log-to-write-on-a-central-log/1218

**Comment by luki1412** [comment]
Does not seem feasible. Imagine a deployment of a script to 1000 computers at once and then they all start writing... to the same central log. That could cause a lot of network issues not mentioning that there would have to behavior for if Write-Log on a specific machine fails to send the message to the central log then it would be timing out, slowing down the script execution and also not recording what it is doing, to the central log because it is unable to do so. It would have to retry or save it and retry later. 

A way better option is to just to tell the script to send a copy of the log at the end. Especially because we plan to add html log output, you just copy that for a nice simple website report that even helpdesk team could read.
