### ISSUE TITLE
problem with "Get-InstalledApplication"

### ISSUE THREAD

**Issue by scotty92fr** [PSAppDeployToolkit/PSAppDeployToolkit#23]
Hi,

I am using the 3.6.3. I need to detect "Microsoft Sync Framework 2.1 Core Components (x64) ENU (KB2567595)".

is it not detected because of the KB2567595? on line 1733 of the AppDeployToolKitMain.ps1 there is a jump for it 

how can I turn arround it ? 
Thanks in advance

**Comment by mmashwani** [comment]
Use the -IncludeUpdatesAndHotfixes parameter of the function.

**Comment by scotty92fr** [comment]
Great it work, Many thanks. Next time I will prefered to use forum more that issue tracking because it was not an issue
