### ISSUE TITLE
Set-PinnedApplication PinToTaskbar does not work in Windows 10

### ISSUE THREAD

**Issue by Tjindarr** [PSAppDeployToolkit/PSAppDeployToolkit#230]
Set-PinnedApplication PinToTaskbar does not work in Windows 10

**Comment by amotaz** [comment]
This issue is a change in Windows 10. We've added code to gracefully handle this situation in 3.6.9. 
https://connect.microsoft.com/PowerShell/feedback/details/1609288/pin-to-taskbar-no-longer-working-in-windows-10
