### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by Tjindarr** [PSAppDeployToolkit/PSAppDeployToolkit#232]
i Found a function that can trigger a task sequence that is already in software center.
https://powersheller.wordpress.com/2012/05/24/sccm-2012-execute-task-sequence-with-powershell/

Its great for deploying OS upgrades so that the user does not need to start software center and triggering it manually.

`Function Execute-TaskSequence {
    Param (
        [parameter(Mandatory = $true)]
        [string]$Name
    )
    Try {
        Write-Log -Message "Connecting to the SCCM client Software Center..."
        $softwareCenter = New-Object -ComObject "UIResource.UIResourceMgr"
    }
    Catch {
        Throw "Could not connect to the client Software Center."
    }
    If ($softwareCenter) {
        Write-Log -Message "Searching for deployments for task sequence [$name]..."
        $taskSequence = $softwareCenter.GetAvailableApplications() | Where { $_.PackageName -eq "$Name" }
        If ($taskSequence) {
            $taskSequenceProgramID = $taskSequence.ID
            $taskSequencePackageID = $taskSequence.PackageID
            Write-Log -Message "Found task sequence [$name] with package ID [$taskSequencePackageID]."
            # Execute the task sequence
            Try {
                Write-Log -Message "Executing task sequence [$name]..."
                $softwareCenter.ExecuteProgram($taskSequenceProgramID,$taskSequencePackageID,$true)
                Write-Log -Message "Task Sequence executed."
            }
            Catch {
                Throw "Failed to execute the task sequence [$name]"
            }
        }
    }
}`

**Comment by amotaz** [comment]
That's interesting. Thank you for the info. I don't think it's a good fit for this project however, we're more geared towards application model deloyment. However, I'll keep this in mind if we need it to solve some issue..

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/new-function/1214

**Comment by luki1412** [comment]
Not everyone is running the toolkit in SCCM so this function belongs in Extensions.ps1 for everyone that needs it. Thanks for the idea though. Feel free to post it as a snippet on our forums - https://discourse.psappdeploytoolkit.com/ for others to use.
