### ISSUE TITLE
Remove-Folder prompting to confirm

### ISSUE THREAD

**Issue by pchatham** [PSAppDeployToolkit/PSAppDeployToolkit#234]
when using Remove-Folder 

Remove-Folder -Path 'C:\TempFolder'

Returns a prompt to confirm as 'Recurse' has not been set

Running non-interactive returns error :

```
[Pre-Installation] :: Failed to delete  'C:\TempFolder' Client from path  'C:\TempFolder'
Error Record:
Message        : Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
```

**Comment by That-Annoying-Guy** [comment]
Yup, I have it too. I just DL'd the current 3.6.9 beta.

It's related to issue #184

**Comment by amotaz** [comment]
This is a small tweak I'll make with the next push I do. I'll post here when that's up. Thanks for the heads up.

**Comment by That-Annoying-Guy** [comment]
I can't wait any longer. In the Remove-Folder Function, I added **-Recurse**

	Remove-Item -LiteralPath $FolderSubObject.FullName -Force -ErrorAction 'Stop' -Recurse

and I got errors if sub-folders had sub-folders.

So I added a test-path around the line like this:

						If (Test-Path -LiteralPath $FolderSubObject.FullName) {
							Remove-Item -LiteralPath $FolderSubObject.FullName -Force -ErrorAction 'Stop' -Recurse
						} Else {
							#Skip over SUB-folder that was deleted with Parent folder
						}

This will do until your small tweak gets posted.

**Comment by amotaz** [comment]
Ok, I made a change. It will definitely not prompt to delete now. 

I'm not sure what functionality you're after exactly That-Annoying-Guy, but try this out. One thing I will not do is completely ignore errors. I've made it so that it will not fatal error if there's an issue deleting stuff, but it will log all of the errors.

Thank you
