### ISSUE TITLE
NotifyIcon remains visible after script has finished and disappears on mouse over

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#238]
We added the following lines in the Deploy-Application.ps1 as we want to have a notification icon during the installation of an application:
`$script:NotifyIcon = New-Object -TypeName 'System.Windows.Forms.NotifyIcon' -Property @{`
`	Icon = New-Object -TypeName 'System.Drawing.Icon' -ArgumentList $appDeployLogoIcon`
`	Text = "$appNameInclSpaces $appVersion $DeploymentType"`
`	Visible = $true`
`}`

The reason why the icon remains in the Notification Tray is that it never gets disposed.
Is it possible to add the disposal of the NotifyIcon in the Exit-Script function?

`## Dispose NotifyIcon`
`$script:notifyIcon.Dispose()`
right before
`## Exit the script, returning the exit code to SCCM`
`If (Test-Path -LiteralPath 'variable:HostInvocation') { $script:ExitCode = $exitCode; Exit } Else { Exit $exitCode }`

We don't want to make modifications to AppDeployToolkitMain.ps1 and adding $script:notifyIcon.Dispose() in the Exit-Script function doesn't cause errors or breaks any logic.

Thanks

**Comment by amotaz** [comment]
Added, thank you

**Comment by DennisVH** [comment]
The icon does not disappear when
`	If ($script:notifyIcon) { Try { $script:notifyIcon.Dispose() } Catch {} }`
is added to Close-InstallationProgress

It does disappear when
`	If ($script:notifyIcon) { Try { $script:notifyIcon.Dispose() } Catch {} }`
is added right before
`	## Exit the script, returning the exit code to SCCM`
`	If (Test-Path -LiteralPath 'variable:HostInvocation') { $script:ExitCode = $exitCode; Exit } Else { Exit $exitCode }`

**Comment by amotaz** [comment]
yup, you're right. I added it to the wrong section. Updated. Please test and verify.

**Comment by DennisVH** [comment]
Verified and working. Thanks
