### ISSUE TITLE
parameter -SecureParameter in Execute-ProcessAsUser like there is in Execute-Process

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#239]
Request to also have -SecureParameter switch in Execute-ProcessAsUser function so that it hides the parameters passed to the executable ran as user from the Toolkit log file

I think following is sufficient:
Adding SecureParameter after Parameter in Execute-ProcessAsUser param block
` 		[Parameter(Mandatory=$false)]`
`		[switch]$SecureParameters = $false,`

Update logging when creating the scheduled task
`## Create Scheduled Task to run the process with a logged-on user account`
`If ($Parameters)`
`{`
`If ($SecureParameters){ Write-Log -Message "Create scheduled task to run the process [$Path (Parameters Hidden)] as the logged-on user [$userName]..." -Source ${CmdletName} }`
`	Else { Write-Log -Message "Create scheduled task to run the process [$Path $Parameters] as the logged-on user [$userName]..." -Source ${CmdletName} }`
`}`

**Comment by amotaz** [comment]
Added, please test and verify. Thank you

**Comment by DennisVH** [comment]
Another part needs to be updated
`		## Trigger the Scheduled Task`
`		If ($Parameters) {`
`			Write-Log -Message "Trigger execution of scheduled task with command [$Path $Parameters] as the logged-on user [$userName]..." -Source ${CmdletName}
		}`
to
`		## Trigger the Scheduled Task`
`		If ($Parameters) {`
`            If ($SecureParameters) {`
`			    Write-Log -Message "Trigger execution of scheduled task with command [$Path (Parameters Hidden)] as the logged-on user [$userName]..." -Source ${CmdletName}`
`            }`
`            Else {`
`			    Write-Log -Message "Trigger execution of scheduled task with command [$Path $Parameters] as the logged-on user [$userName]..." -Source ${CmdletName}           `
`            }`
`		}`

Also in line 4678 the closing bracket around $Path (Parameters Hidden) is missing
`				Write-Log -Message "Create scheduled task to run the process [$Path (Parameters Hidden) as the logged-on user [$userName]..." -Source ${CmdletName}`

**Comment by amotaz** [comment]
Done and pushed. Good suggestion and catch. Please test and verify

**Comment by DennisVH** [comment]
Verified and working. Thanks
