### ISSUE TITLE
ShowBlockedAppDialog Optional when using -blockexecution

### ISSUE THREAD

**Issue by OXY-IT** [PSAppDeployToolkit/PSAppDeployToolkit#240]
Hi guys,

Do you think it is possible (or if it already is, can you tell me how) that when using -blockexecution the ShowBlockedAppDialog can be made optional.

In some deployments we just want the application blocked and don't want to show a prompt when the user or installer tries to start the application.

For now we've just out-commented the "Show-InstallationPrompt -Title $installTitle -Message $configBlockExecutionMessage -Icon 'Warning' -ButtonRightText 'OK'" from the AppDeployToolkitMain.ps1

But that's not as gracious as the rest of the framework offcourse, resulting in different versions used of the framework, which pains our collective IT OCD.

Would be awesome, hope you guys see something in this :)

**Comment by amotaz** [comment]
you can directly call the Block-AppExecution

**Comment by ofortun** [comment]
I came across this issue in my search of a solution. I am running into the same scenario that @OXY-IT describes. I need to block an exe from running during an MSI uninstallation, and don't want any window to popup. I am deploying an app via SCCM. I wanted to share my workaround.

The 'Block-AppExecution' function still shows a prompt if the exe launches.
I edited line 5243 of AppDeployToolkit\AppDeployToolkitMain.ps1. I added $FALSE so it looks like this:
`ShowBlockedAppDialog:$FALSE`

The full line:
```powershell
[string]$debuggerBlockMessageCmd = "`"powershell.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -File `" & chr(34) & `"$dirAppDeployTemp\$scriptFileName`" & chr(34) & `" -ShowBlockedAppDialog:$FALSE -AsyncToolkitLaunch -ReferredInstallTitle `" & chr(34) & `"$installTitle`" & chr(34)"
```

I also added a note in my Deploy-Application.ps1 as a reminder, which also gets written to the log.
```powershell
Show-InstallationWelcome -CloseApps 'exeName' -Silent -BlockExecution
Write-Log -Message "Line 5243 of AppDeployToolkit\AppDeployToolkitMain.ps1 was modified. :$FALSE was added to -ShowBlockedAppDialog. This is to hide the window when blocking Process exeName" -Severity 2 -Source $deployAppScriptFriendlyName
```
