### ISSUE TITLE
Documentation missing on feature? - bundle dependency chain

### ISSUE THREAD

**Issue by stgrdk** [PSAppDeployToolkit/PSAppDeployToolkit#243]
How to use this feature?

Bundle multiple application installations to overcome the supported limit of 5 applications in the CM12 application dependency chain.

**Comment by That-Annoying-Guy** [comment]
I think you are blowing it up in your mind.

After this line

    ## <Perform Installation tasks here>

Just call The various MSIs/EXEs one after another. (maybe add Try/catches to test if each installed ok)

	Execute-MSI -Action Install -Path $appMSINAME1 -Transform $appMSTNAME1 -LogName "${appMSTNAME1}_MSI"

	Execute-MSI -Action Install -Path $appMSINAME2 -Transform $appMSTNAME2 -LogName "${appMSTNAME2}_MSI"

	Execute-MSI -Action Install -Path $appMSINAME3 -Transform $appMSTNAME3 -LogName "${appMSTNAME3}_MSI"

	Execute-MSI -Action Install -Path $appMSINAME4 -Transform $appMSTNAME4 -LogName "${appMSTNAME4}_MSI"

	Execute-Process -Path "setup5.exe" -Parameters "-s -f2`"$logTempFolder\$SetupEXE5.log`""
