### ISSUE TITLE
Add RetryInterval and RetryCount to Remove-Folder

### ISSUE THREAD

**Issue by bruckect** [PSAppDeployToolkit/PSAppDeployToolkit#244]
This may be resolved with Issue #234. However, we are using v3.6.8 of the toolkit and have been noticing an issue when deleting certain folders. The error is that "the directory is not empty". I have been putting Remove-Folder inside of a while loop and had success in retrying the deletion. I wanted to see if there was appetite for this type of addition. If so, i can submit a PR.

```
function Remove-FolderWrapper {
<#
	.SYNOPSIS
		A wrapper script for PSAppDeployToolkit's Remove-Folder function
	
	.DESCRIPTION
		Adds the ability to retry the folder deletion every X seconds for X amount of times.
	
	.PARAMETER Path
		Path to the folder to remove.
	
	.PARAMETER RetryInterval
		The amount of seconds until we try to delete the folder again
	
	.PARAMETER RetryCount
		The amount of amount times we will to try to remove the folder.
	
	.PARAMETER ContinueOnError
		Continue if an error is encountered. Default is: $true.
	
	.EXAMPLE
		PS C:\> Remove-FFBFolder -Path 'C:\Temp' -RetryInterval 30 -RetryCount 10
		Attempt to delete C:\Temp, every 30 seconds for 5 minutes
	
	.NOTES
		Additional information about the function.
#>
	[CmdletBinding()]
	param (
		[Parameter(Mandatory = $true)]
		[ValidateNotNullOrEmpty()]
		[string]$Path,
		[Parameter(Mandatory = $true)]
		[ValidateNotNullOrEmpty()]
		[System.Int32]$RetryInterval,
		[Parameter(Mandatory = $true)]
		[ValidateNotNullOrEmpty()]
		[System.Int32]$RetryCount,
		[Parameter(Mandatory = $false)]
		[ValidateNotNullOrEmpty()]
		[boolean]$ContinueOnError
	)
	
	begin {
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	}
	process {
		$i = 0
		while ($i -lt $RetryCount) {
			if (Test-Path -Path $Path -ErrorAction SilentlyContinue) {
				if ($ContinueOnError) {
					Remove-Folder -Path $Path -ContinueOnError $true
					$i = $RetryCount
				} else {
					Remove-Folder -Path $Path
					Start-Sleep -Seconds $RetryInterval
					$i++
				}
			} else {
				$i = $RetryCount
			}
		}
	}
	end {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
```

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/add-retryinterval-and-retrycount-to-remove-folder/1216

**Comment by ScottMonolith** [comment]
@sintaxasn - that link is no longer valid.  I've been trying to use the Remove-Folder function, but it seems to fail silently (I'm guessing because by default it continues on error) - I'm hoping some retry logic would help.  Please advise, was this ever taken up?  Should I write my own?

Thanks.

**Comment by mjr4077au** [comment]
@ScottMonolith, we've implemented this within v4 which should be at the very least previewing around October. I know this doesn't help quite at the moment but v3.x is only receiving critical fixes at this point in time.

![image](https://github.com/user-attachments/assets/030ade83-ce6e-4e78-a4fe-e98204d825b0)

**Comment by ScottMonolith** [comment]
@mjr4077au - thanks for the response.  Looks like there will be some breaking changes, which I suppose a major version upgrade warrants.

I will implement my own simple retry logic for now and be on the lookout for v4.  Thanks again!

**Comment by sintaxasn** [comment]
> @mjr4077au - thanks for the response. Looks like there will be some breaking changes, which I suppose a major version upgrade warrants.

Actually, we're aiming for zero breaking changes :) There's been a phenomenal amount work gone into making the upgrade as frictionless as poissible.

**Comment by mjr4077au** [comment]
Closing out this issue as it's addressed per previous comments.
