### ISSUE TITLE
Script not signed error - SCCM 2012

### ISSUE THREAD

**Issue by Minsy** [PSAppDeployToolkit/PSAppDeployToolkit#245]
Hi,

I have used PSAppDeployToolkit to create a folder and copy a file to it.  It works fine when run locally however, get the following error when I try via SCCM 2012:

Error Code: 0x87D00327 (-2016410841)
Error Description: Script not signed

Wondered if there was a way of incorporating the Set-ExecutionPolicy -ExecutionPolicy 'ByPass' on the command line I'm using within the application within SCCM 2012.

PS ... I have searched for the error on line which takes me to this page but wondered if the above was at all possible:
https://www.petervanderwoude.nl/post/deployment-of-configuration-baseline-failed-with-error-script-is-not-signed-in-configmgr-2012/

**Comment by That-Annoying-Guy** [comment]
FYI: Your question is not a bug. It should have been posted at http://psappdeploytoolkit.com/forums/forum/general/

Your Answer: Try by using a semi-colon ; to separate each command.
