### ISSUE TITLE
Issue with -PassThru/AllowRebootPassThru

### ISSUE THREAD

**Issue by danolson312** [PSAppDeployToolkit/PSAppDeployToolkit#246]
I have the -PassThru parameter set in my script.  I'm passing the -AllowRebootPassThru parameter set to true in my command line.  The log verifies that both the AllowRebootPassThru is set to $true and that the Execute-MSI line is returning a 3010.  But the default Exit-Script line at the end of the default ps1 file is not passing the 3010 to SCCM.  Attached are links to both the PS1 file and the log files (both install log files that get created).  
Is this a bug or do I have some syntax wrong?

Side note: we are using SCCM v1606.  I am deploying this application wo W7x86, W7x64, and W10x64 (three different scripts, but all are experiencing same issues)

MSI log - http://pastebin.com/VaJyt3Ar
PSADT log - http://pastebin.com/9zVALmMd
PS1 script - http://pastebin.com/V0KGswT9

**Comment by PLogFinder** [comment]
Setting -PassThru on Execute-MSI means you want to collect the output from the cmdlet yourself and you will handle it.  Try leaving -PassThru off the Execute-MSI cmdlet.  -AllowRebootPassThru on the script makes the Exit-Script cmdlet pass the return code back up the line to SCCM (but only if it hasn't been 'handled' at a lower level with -PassThru on Execute-MSI).  Also, I would simply code the switch parameter -AllowRebootPassThru by itself (no need in call for longhand spec:  -AllowRebootPassThru:$true as far as I know).

**Comment by danolson312** [comment]
I took the -PassThru parameter off of the Execute-MSI cmdlet.  Now the log shows that the script is Exit-Script with 3010.  But it doesn't seem to be passing through to SCCM.  The application keeps failing with 0x1(1) error.  After doing a machine policy refresh or restart, the application detects and shows as installed.

Still not able to get the SCCM prompt to restart the computer to finish the installation

**Comment by amotaz** [comment]
What is your commandline in SCCM for this package?

**Comment by danolson312** [comment]
The commandline I am using is 
`PowerShell.exe -Executionpolicy bypass .\Deploy-Application.ps1 -DeploymentType "Install" -DeployMode "Silent" -AllowRebootPassThru`

**Comment by PLogFinder** [comment]
Recommend to use the EXE provided, it supports all the interaction with the environment.  In your case I'd probably use:
`Deploy-Application.exe -DeployMode NonInteractive -AllowRetootPassThru`
and
`Deploy-Application.exe -DeploymentType Uninstall -DeployMode NonInteractive -AllowRetootPassThru`
(assuming you have the uninstall block set up too)

**Comment by PLogFinder** [comment]
If you run it stand-alone as admin (not with SCCM) from a command line, what do you get in %ERRORLEVEL%?  Eg changing directory to package, and running it with:
`start "" /wait Deploy-Application.exe -DeployMode NonInteractive -AllowRebootPassThru`
then when it finishes:
`echo %ERRORLEVEL%`

**Comment by danolson312** [comment]
(Thank you for that start "" /wait trick.  I wasn't sure how to test for error level)

It is returning errorcode 3010

**Comment by danolson312** [comment]
I ended up doing a hack to make this work.  Even though both the MSI and the script were returning 3010, it wasn't passing it through to SCCM properly.  The app would fail with 0x1 error.  I ended up adding a custom exit code in the deployment type of 1 as soft reboot.  Seems to work fine now.  Kind of frustrated that it doesn't work as intended, but I've wasted enough time on this already.  Need to press on.  Thanks for everyones input!

**Comment by That-Annoying-Guy** [comment]
One of my co-workers ran into this problem and wrote a function for something like this:

	Function Throw-WithErrorCode {
	<#  
	.SYNOPSIS  
		Throws an error *AND* exits with a specific ExitCode
	.DESCRIPTION
		Throws error message, catches and logs the message
		Then exit with a specific ExitCode. All in one function call.
	.PARAMETER Message
		Message used in the throw and is then logged
	.PARAMETER ExitCode
		ExitCode used when exiting script
	.INPUTS
		Toolkit Exit Code Ranges:
		60000 - 68999: Reserved for built-in exit codes used in the Toolkit modules.
		69000 - 69999: Recommended for user customized exit codes in Deploy-Application.ps1
		70000 - 79999: Recommended for user customized exit codes in AppDeployToolkitExtensions.ps1
	.OUTPUTS
		ExitCode
	.NOTES  
		Original Concept and Author: Matt Friedrich
		Optional $source parameter: Denis St-Pierre
	.LINK
	#>  
		[CmdletBinding()]
		Param (
			[Parameter(Mandatory=$True,Position=0,ValueFromPipeline=$True,ValueFromPipelineByPropertyName=$True)]
			[AllowEmptyCollection()]
			[Alias('Text')]
			[String[]]$Message,
			[Parameter(position=1, Mandatory=$False, HelpMessage='An integer representing an error/return code')]
			[ValidatePattern('[0-9]')]
			[String]$ExitCode,
			[Parameter(Mandatory=$false)]
			[ValidateNotNull()]
			[string]$Source = ''
		)
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Try {
			Write-Log -Message $($Message|Out-String) -WriteHost $True -Severity 3 -Source ${CmdletName}
			Throw $Message	#Cause error
		} Catch {
			If ($Source -eq '') { $Source = ${CmdletName} }
			[Int32]$Script:MainExitCode = $ExitCode
			[String]$mainErrorMessage = @{'Message:' = "$($_.Exception.Message)";'ScriptStackTrace:'="$($_.ScriptStackTrace)";'InnerException:'="$($_.Exception.InnerException)"} `
				| Format-Table -AutoSize -Wrap -HideTableHeaders | Out-String
			Write-Log -Message $mainErrorMessage -WriteHost $True -Severity 3 -Source $Source
			Exit-Script -ExitCode $MainExitCode
		}
	} #Throw-WithErrorCode

**Comment by PLogFinder** [comment]
Just some follow-up... in case it's useful for anyone:

SCCM has a bug for powershell v3 cmdlet Start-Process ... -wait that the PSAppDeployToolkit avoids by using another way for calling EXEs, but if you write your own Start-Process it could break (but only under SCCM).  It's a similar (same?) bug as for powershell remote execution.  There may be other powershell things that break in SCCM, but I've found that if I use the PSADTk functions I tend to avoid those sort of problems.  If there's such a bug, I've not tripped over that one yet.

Something that makes return code 1 is a syntax error in the powershell script - hunt carefully for red "~" in the PS editor.  If it's running your installer OK, then the location of the problem may be in later code, past your working code, so your get-around sounds useful if you don't need to know about other return codes from the script completing cleanly.  

I get a return code 1 when I comment out the zero-config script code blocks, but forget to comment out the trailing "}" that's out on a line by itself :)

**Comment by PLogFinder** [comment]
Some other ideas for return code 1 in this post:
https://www.reddit.com/r/SCCM/comments/2gb80y/error_code_0x11_incorrect_function_action_failed/
Cheers.
