### ISSUE TITLE
http://psappdeploytoolkit.com/wp-login.php no longer working

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#247]
Tried in Chrome and got:

The psappdeploytoolkit.com page isn’t working
psappdeploytoolkit.com redirected you too many times.
ERR_TOO_MANY_REDIRECTS

(BTW: No, I do not Twit, FB, G+, etc...)

**Comment by That-Annoying-Guy** [comment]
issue is local to my workplace

**Comment by That-Annoying-Guy** [comment]
Issue persists and occurs at home too.

I suspect this is the issue:
http://www.wpbeginner.com/wp-tutorials/how-to-fix-wordpress-login-page-refreshing-and-redirecting-issue/

**Comment by amotaz** [comment]
Can you please see if the tweaks to the site resolved this issue?

**Comment by That-Annoying-Guy** [comment]
The page isn’t redirecting properly

**Firefox** has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

-----------------------**Chrome** below ----------------------
The psappdeploytoolkit.com page isn’t working

psappdeploytoolkit.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

(Yes, I cleared the cookies)
