### ISSUE TITLE
Some glitch with 3.6.9

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#248]
Hi,

I am implementing 3.6.9 this morning and noticed some little glitch:
1. Documentation is still label as 3.6.8 instead 3.6.9
2. On opening AppDeployToolkitConfig.xml, Notepad++ is showing "XML Parsin error at line 1: Document labelled UTF16 but has UTF-8 content"

Thanks,

**Comment by amotaz** [comment]
Hi, please verify the XML encoding on your end

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
