### ISSUE TITLE
Disk Space vs Installer Size Check

### ISSUE THREAD

**Issue by ml58158** [PSAppDeployToolkit/PSAppDeployToolkit#249]
Is there a way to check the free disk space against the installer size and fail the installer if there is not enough space?

**Comment by amotaz** [comment]
We don't have a built in solution to this, and I'd be hesitant to add something since installer's tend to be compressed, so installer size is kind of arbitrary. I'd be open to ideas if anyone has one. Otherwise, a bit of custom code should do it.

**Comment by seanlillis** [comment]
Show-InstallationWelcome includes the -CheckDiskSpace switch:

Specify whether to check if there is enough disk space for the installation to proceed. If this parameter is specified without the RequiredDiskSpace parameter, the required disk space is calculated automatically based on the size of the script source and associated files.
