### ISSUE TITLE
On Windows 10 $envOSVersionRevision is not the same as value in winver.exe

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#251]
The version revision in BuildLabEx is not the same as the revision displayed when running winver.exe on a Windows 10 pre RS1.
https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/windows-10-build-information/562d52ed-bf2f-42b9-b24a-2f190c2a7147

I would suggest to use the value in UBR instead.

`If ($envOSVersionMajor -eq 10) {$envOSVersionRevision = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name 'UBR' -ErrorAction SilentlyContinue).UBR}`
`Else { [string]$envOSVersionRevision = ,((Get-ItemProperty -Path 'HKLM:SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name 'BuildLabEx' -ErrorAction 'SilentlyContinue').BuildLabEx -split '\.') | ForEach-Object { $_[1] } }`
`If ($envOSVersionRevision -notmatch '^[\d\.]+$') { $envOSVersionRevision = '' }`
`If ($envOSVersionRevision) { [string]$envOSVersion = "$($envOSVersion.ToString()).$envOSVersionRevision" } Else { "$($envOSVersion.ToString())" }`

**Comment by DennisVH** [comment]
This will be resolved in the next release

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
