### ISSUE TITLE
Test-ServiceExists and Set-ServiceStartMode not playing together

### ISSUE THREAD

**Issue by PZan** [PSAppDeployToolkit/PSAppDeployToolkit#252]
# Issue
Test-ServiceExists only fetches service from Win32_Service and not from Win32_BaseService. When using Test-ServiceExists in an if statement to set a "base service" start mode, it will never find the service, and therefore never set startmode. You can use mrxsmb10 as an example.

# Suggested solution
Add a second Get-WmiObject to the Test-ServiceExists function, if the first query doesn't return a result.

Something in the likes of the following would probably do:
`if ( ! ( $ServiceObject ) ) {
    $ServiceObject = Get-WmiObject -ComputerName $ComputerName -Class 'Win32_BaseService' -Filter "Name='$Name'" -ErrorAction 'Stop'
}`

Ps. New on Github, hope this is the correct way of submitting an issue.

**Comment by seanlillis** [comment]
Thanks, this will be included in the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
