### ISSUE TITLE
Dialog boxes off center

### ISSUE THREAD

**Issue by Joey40** [PSAppDeployToolkit/PSAppDeployToolkit#253]
A few users in the WinAdmins Slack have been discussing an issue with the text in some dialog boxes being off-center (see attached image).  A proposed fix (by user @ajeoae) was to modify the label properties in AppDeployToolkitMain.ps1 as follows:

```
                ## Generic Label properties
		$labelPadding = '40,0,20,0'
```

![image](https://cloud.githubusercontent.com/assets/18147723/23513895/a18e573a-ff33-11e6-822c-5cda7c7db562.png)

Link to Slack invite: https://slofile.com/slack/winadmins 
We are in the #psappdeploytoolkit channel

**Comment by mmashwani** [comment]
I think the problem I have found with this change in the past is that the text then becomes off-center on machines in non-english languages. I am not sure why that is. It's something that requires further digging. If you find anything, please do share.

**Comment by CodaAmok** [comment]
@joey52685 Adjusting $labelPadding like that does seem to make it appear more centered. There are two $labelPadding variables though FYI.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/dialog-boxes-off-center/1228
