### ISSUE TITLE
Feature Request: Add Vendor switch to Remove-MSIApplications

### ISSUE THREAD

**Issue by LionZum** [PSAppDeployToolkit/PSAppDeployToolkit#257]
I saw some people trying to remove all apps by a vendor and thought that the remove-msiapplications would be perfect but I don't think you can search by vendor.  It could be a useful switch for some people to search on.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/feature-request-add-vendor-switch-to-remove-msiapplications/1183

**Comment by mjr4077au** [comment]
This has been addressed in v4, as you can now use natural filterscript setups, very similar to how you'd filter with `Where-Object`.
