### ISSUE TITLE
Write-FunctionHeaderOrFooter (Add parameter type to logging)

### ISSUE THREAD

**Issue by LMCO-psadt-devs** [PSAppDeployToolkit/PSAppDeployToolkit#258]
Add the parameter type column to the log.

`[string]$CmdletBoundParameters = $CmdletBoundParameters | Format-Table -Property @{ Label = 'Parameter'; Expression = { "[-$($_.Key)]" } }, @{ Label = 'Value'; Expression = { $_.Value }; Alignment = 'Left' }, @{ Label = 'Type'; Expression = { $_.Value.GetType().Name }; Alignment = 'Left' } -AutoSize -Wrap | Out-String`

**Comment by seanlillis** [comment]
This will be included in the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
