### ISSUE TITLE
Enable-TerminalServerInstallMode - "Failed to change terminal server into user execute mode"

### ISSUE THREAD

**Issue by appPackager** [PSAppDeployToolkit/PSAppDeployToolkit#26]
Environment: 
* Microsoft Windows Server 2008 R2 Enterprise Service Pack 1 64-bit 6.1.7601.65536
* Citrix XenApp 6.5
* PowerShell 4.0
* App Deploy Toolkit 3.6.3
* NT AUTHORITY\SYSTEM
* English Language
* SCCM 2012 command-line: Deploy-Application test.ps1 -TerminalServerMode

PSAppDeployToolkit Trace Log:
[Initialization] :: Failed to change terminal server into user install mode. 
Error Record:
-------------
Message        : User session is ready to install applications.
InnerException : 

FullyQualifiedErrorId : User session is ready to install applications.
ScriptStackTrace      : at Enable-TerminalServerInstallMode<Process>, C:\WINDOW
                        S\ccmcache\8\AppDeployToolkit\AppDeployToolkitMain.ps1:
                         line 7942
                        at <ScriptBlock>, C:\WINDOWS\ccmcache\8\AppDeployToolki
                        t\AppDeployToolkitMain.ps1: line 9175
                        at <ScriptBlock>, C:\WINDOWS\ccmcache\8\test.ps1: line 
                        96
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\WINDOWS\ccmcache\8\AppDeployToolkit\AppDeployToolkitMai
                  n.ps1:7942 char:38
                  +             If ($global:LastExitCode -ne 0) { Throw 
                  $terminalServerResult }
                  +                                               
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~

When running the change.exe user /install command from a command window it, by default, returns a value of 1 on success.  In my opinion the PowerShell code is mistakenly looking for a return code of 0 (as success).

**Comment by mmashwani** [comment]
Thanks for reporting this. I have made the appropriate fix in the latest 3.6.4 beta found here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit

Please test and let me know if it is working as expected now.
