### ISSUE TITLE
Documentation File Out of Date

### ISSUE THREAD

**Issue by NathanTheGr8** [PSAppDeployToolkit/PSAppDeployToolkit#260]
The version number in the included download still says version 3.6.8. I am not sure if this was intentional or not. It seems like some of the doc was updated for 2.6.9 because the Execute-Process has the SecureParameters but Execute-ProcessAsUser doesn't.

**Comment by amotaz** [comment]
about to push a fix, thanks for the find.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
