### ISSUE TITLE
Use Approved Cmdlet Verbs

### ISSUE THREAD

**Issue by LMCO-psadt-devs** [PSAppDeployToolkit/PSAppDeployToolkit#261]
It would make sense to follow [Microsoft's verb naming rules](https://technet.microsoft.com/en-us/library/ms714428%28v=vs.85%29.aspx) (or `Get-Verb`) when creating Cmdlets.

The use of `Refresh` as a verb violates this convention.

**Comment by Hedkandi** [comment]
I would like this also

**Comment by LMCO-psadt-devs** [comment]
Change:
   `Refresh-Desktop `to `Update-Desktop`
   `Refresh-SessionEnvironmentVariables `to `Update-SessionEnvironmentVariables`

Both of the new cmdlets should be aliased to the previous names to account for backwards compatibility

**Comment by LMCO-psadt-devs** [comment]
Change:
   `Refresh-Desktop `to `Update-Desktop`
   `Refresh-SessionEnvironmentVariables `to `Update-SessionEnvironmentVariables`

Both of the new cmdlets should be aliased to the previous names to account for backwards compatibility

**Comment by seanlillis** [comment]
This will be fixed in the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
