### ISSUE TITLE
Unable to logon on forum

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#263]
I tried on multiple browser and computer and I can't find the icons to get login on other forum than this one. What is happening?

**Comment by amotaz** [comment]
there are some problems with the site, that one of the members is working on. I'll reply again once its been resolved.

**Comment by That-Annoying-Guy** [comment]
Does this have any relation to issue #247?

**Comment by FRacine** [comment]
I believe not. I just see Nothing to get logon on forum so it is impossible to post anything.

**Comment by amotaz** [comment]
We believe the issue is resolved, Can you please test and confirm?

**Comment by FRacine** [comment]
I confirm.

**Comment by amotaz** [comment]
Thanks
