### ISSUE TITLE
$appName

### ISSUE THREAD

**Issue by AgetroNairb** [PSAppDeployToolkit/PSAppDeployToolkit#264]
I use $appName in my dialogs but the Main script removes some of the "invalid" characters, thus removing spaces. I've made the following changes to my copy of the Main script and wanted to suggest the changes for the next version. This leaves the $appName alone to be used in the default script but still removes the invalid characters for the log filename.

`##` Sanitize the application details, as they can cause issues in the script
[char[]]$invalidFileNameChars = [IO.Path]::GetInvalidFileNameChars()
[string]$ValidAppVendor = $appVendor -replace "[$invalidFileNameChars]",'' -replace ' ',''
[string]$ValidAppName = $appName -replace "[$invalidFileNameChars]",'' -replace ' ',''
[string]$ValidAppVersion = $appVersion -replace "[$invalidFileNameChars]",'' -replace ' ',''
[string]$ValidAppArch = $appArch -replace "[$invalidFileNameChars]",'' -replace ' ',''
[string]$ValidAppLang = $appLang -replace "[$invalidFileNameChars]",'' -replace ' ',''
[string]$ValidAppRevision = $appRevision -replace "[$invalidFileNameChars]",'' -replace ' ',''

`##` Build the Installation Name
If ($ReferredInstallName) { [string]$installName = $ReferredInstallName }
If (-not $installName) {
	If ($ValidAppArch) {
		[string]$installName = $ValidAppVendor + '_' + $ValidAppName + '_' + $ValidAppVersion + '_' + $ValidAppArch + '_' + $ValidAppLang + '_' + $ValidAppRevision
	}
	Else {
		[string]$installName = $ValidAppVendor + '_' + $ValidAppName + '_' + $ValidAppVersion + '_' + $ValidAppLang + '_' + $ValidAppRevision
	}
}

**Comment by LMCO-psadt-devs** [comment]
Leverage `$installName` and `$installTitle`.
They are used for the dialogs if you need special characters

**Comment by AgetroNairb** [comment]
Yeah, that's what I've used in the past as a workaround but I think not changing the $appName might be a cleaner way of doing it.
