### ISSUE TITLE
Show-InstallationWelcome -BlockExecution

### ISSUE THREAD

**Issue by lucafabbri365** [PSAppDeployToolkit/PSAppDeployToolkit#265]
Platform: Windows 10 1703 (Build 15063.14); PowerShell version: 5.1.15063.0
The "-BlockExecution" parameter doesn't seem to work.

_Example:_

`Show-InstallationWelcome -CloseApps 'notepad' -BlockExecution -AllowDeferCloseApps -DeferTimes 3 -CheckDiskSpace -PersistPrompt`
`Show-InstallationProgress`

I can open "notepad" while installing.

**Comment by skinnystick22** [comment]
I have this same issue. Seems like, from looking at the logs, that there is an issue with the -BlockExecution Switch. This is turn makes the logs show that a part of the installName variable is thought to be a Parameter to the switch. I will upload the portion of my log to reflect this issue.

**Comment by Reclad** [comment]
Do you use the latest version? (3.6.9)
Make sure that the Deploy-Application.ps1 script and the AppDeployToolkit folder are up-to-date.

The script must be deployed as an Administrator or SCCM as a system (and not a user) installation.

You should see in your logs something like :
`[Pre-Installation] :: Set registry key value: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe] [Debugger = wscript.exe "C:\Users\Public\PSAppDeployToolkit\AppDeployToolkit_BlockAppExecutionMessage.vbs"].`

**Comment by lucafabbri365** [comment]
Yes, I'm using latest version (**3.6.9**).
Log file C:\Windows\Logs\Software\<PSAppDeployToolkit>.log doesn't contain any "Image File Execution" string.
This is the "Pre-Installation" part:

`[string]$installPhase = 'Pre-Installation'
Show-InstallationWelcome -CloseApps 'notepad' -BlockExecution -AllowDeferCloseApps -DeferTimes 3 -CheckDiskSpace -PersistPrompt
Show-InstallationProgress`

I launched the "Deploy-Application.ps1" file manually, from PowerShell opened with highest privileges ("Run as administrator"), then it discovers "notepad.exe" is opened. After I close it, the script continues to run; while it happen I can still open "notepad.exe". I expected it was blocked from running but it doesn't seem to be blocked..

Any advice ?

**Comment by lucafabbri365** [comment]
Guys, I found the issue !!! It is related to this other post I opened few
