### ISSUE TITLE
Execute-MSI Repair uses /f instead of /fv

### ISSUE THREAD

**Issue by D3nsha** [PSAppDeployToolkit/PSAppDeployToolkit#266]
**Execute-MSI -Action "Repair"** now uses /f instead of /fv in 3.6.9, meaning that it will attempt repair from the MSI cache instead of using the supplied source file.

**Comment by Hedkandi** [comment]
When you are using SCCM downloaded packages gets wiped when the cache is cleared and repair operations after this uses the MSI from the old location.

This function should use the default parameters for repair and /v to point out the new location of the msi.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/execute-msi-repair-uses-f-instead-of-fv/1181

**Comment by luki1412** [comment]
Added as a parameter -RepairFromSource for Execute-MSI in the latest version 3.8.2
