### ISSUE TITLE
Variablelist should have $currentUILanguage

### ISSUE THREAD

**Issue by Hedkandi** [PSAppDeployToolkit/PSAppDeployToolkit#267]
In our environment we have a wim-file with multiple languages but we usually have swedish keyboards connected to our computers. When we encounter a computer with english UI we want to install the english version of the application.
$currentLanguage uses Get-Culture:
"The Get-Culture cmdlet gets information about the current culture settings. This includes information about the current language settings on the system, such as the keyboard layout, and the display format of items such as numbers, currency, and dates."

I guess i can get the language with Get-UICulture and use that but i think it would be nice to have a $currentUILanguage variable.

$currentLanguage is populated by:
[Globalization.CultureInfo]$culture = Get-Culture
[string]$currentLanguage = $culture.TwoLetterISOLanguageName.ToUpper()

$currentUILanguage would be populated by:
[Globalization.CultureInfo]$uiculture = Get-UICulture
[string]$currentUILanguage = $uiculture.TwoLetterISOLanguageName.ToUpper()

**Comment by seanlillis** [comment]
This will be added to the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
