### ISSUE TITLE
"Failed to get the ProductCode from the MSI file. Continue with requested action [Patch]..."

### ISSUE THREAD

**Issue by appPackager** [PSAppDeployToolkit/PSAppDeployToolkit#27]
I have the following line of code within my test.ps1:
      Execute-MSI -Action Patch -Path "wiv-1050-006.msp" 

PSAppDeployKit log states the following:
[Pre-Installation] :: Failed to get the MSI table [Property]. 
Error Record:
-------------

Message        : Exception calling "InvokeMember" with "8" argument(s): 
                 "OpenDatabase,DatabasePath,OpenMode"
InnerException : System.Runtime.InteropServices.COMException (0x80004005): 
                 OpenDatabase,DatabasePath,OpenMode

FullyQualifiedErrorId : COMException
ScriptStackTrace      : at <ScriptBlock>, \\bvlsccmdv2\certify\readyforqa\Darin
                        \AppDeployToolkit\AppDeployToolkitMain.ps1: line 6956
                        at Get-MsiTableProperty<Process>, \\bvlsccmdv2\certify\
                        readyforqa\Darin\AppDeployToolkit\AppDeployToolkitMain.
                        ps1: line 6978
                        at Execute-MSI<Process>, \\bvlsccmdv2\certify\readyforq
                        a\Darin\AppDeployToolkit\AppDeployToolkitMain.ps1: 
                        line 2024
                        at <ScriptBlock>, 
                        \\bvlsccmdv2\certify\readyforqa\Darin\test.ps1: line 
                        135
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At \\bvlsccmdv2\certify\readyforqa\Darin\AppDeployToolkit\App
                  DeployToolkitMain.ps1:6956 char:4
                  +             Write-Output 
                  $Object.GetType().InvokeMember($MethodName, 
                  [Reflection.BindingF ...
                  +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error Inner Exception(s):
-------------------------

Message        : OpenDatabase,DatabasePath,OpenMode
InnerException : 


Should .msp properties be interrogated or just .msi???

**Comment by mmashwani** [comment]
Thanks for reporting this. I have made the appropriate fix in the latest 3.6.4 beta found here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit

Please test and let me know if it is working as expected now.
