### ISSUE TITLE
Unsaved Data

### ISSUE THREAD

**Issue by rsaada** [PSAppDeployToolkit/PSAppDeployToolkit#271]
Is there a way to force an open application to close even if it contains unsaved data? For example, let's say a user left Word open with some text but never saved it. Winword is defined in the -CloseApps argument. Currently the Toolkit will not close Word and continue the installation unless a user saves the data or clicks don't save. Is there a way to force it to close and continue after a specified amount of time?

**Comment by sineljogy** [comment]
Hi

Do you integrate the `-CloseAppsCountdown` parameter is your command? Unsaved document in Word has been successfully killed after 10 seconds, I've used this command:

`Show-InstallationWelcome -CloseApps "winword=Microsoft Office Word" -CloseAppsCountdown 10`
