### ISSUE TITLE
Show-BalloonTip on Windows 10 RS1 shows source (Windows PowerShell) in Toast

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#272]
As of Windows 10 RS1 the NotifyIcon.ShowBalloonTip adds the source that generates the BalloonTip message.

![balloontip windows powershell](https://cloud.githubusercontent.com/assets/12512689/25887982/a632273c-3564-11e7-8551-91fa9ea98f53.png)

To be able to modify this text, a Toast needs to be created in Windows 10 instead of a BalloonTip

Example before RS1
![balloontip toast before rs1](https://cloud.githubusercontent.com/assets/12512689/25887294/d476bb38-3561-11e7-82a6-b09c61cbaa60.png)

Example after RS1 (with as source $InstallTitle)
![balloontip toast after rs1](https://cloud.githubusercontent.com/assets/12512689/25887295/d6ba2754-3561-11e7-9980-f52ee48d9ab6.png)

Proposed code:

`
#region Function Show-BalloonTip
Function Show-BalloonTip {
<#
.SYNOPSIS
	Displays a balloon tip notification in the system tray.
.DESCRIPTION
	Displays a balloon tip notification in the system tray.
.PARAMETER BalloonTipText
	Text of the balloon tip.
.PARAMETER BalloonTipTitle
	Title of the balloon tip.
.PARAMETER BalloonTipIcon
	Icon to be used. Options: 'Error', 'Info', 'None', 'Warning'. Default is: Info.
.PARAMETER BalloonTipTime
	Time in milliseconds to display the balloon tip. Default: 500.
.EXAMPLE
	Show-BalloonTip -BalloonTipText 'Installation Started' -BalloonTipTitle 'Application Name'
.EXAMPLE
	Show-BalloonTip -BalloonTipIcon 'Info' -BalloonTipText 'Installation Started' -BalloonTipTitle 'Application Name' -BalloonTipTime 1000
.NOTES
.LINK
	http://psappdeploytoolkit.com
#>
	[CmdletBinding()]
	Param (
		[Parameter(Mandatory=$true,Position=0)]
		[ValidateNotNullOrEmpty()]
		[string]$BalloonTipText,
		[Parameter(Mandatory=$false,Position=1)]
		[ValidateNotNullorEmpty()]
		[string]$BalloonTipTitle = $installTitle,
		[Parameter(Mandatory=$false,Position=2)]
		[ValidateSet('Error','Info','None','Warning')]
		[Windows.Forms.ToolTipIcon]$BalloonTipIcon = 'Info',
		[Parameter(Mandatory=$false,Position=3)]
		[ValidateNotNullorEmpty()]
		[int32]$BalloonTipTime = 10000
	)
	
	Begin {
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	}
	Process {
		## Skip balloon if in silent mode
		If (($deployModeSilent) -or (-not $configShowBalloonNotifications) -or (Test-PowerPoint)) { Return }

		## Dispose of previous balloon
		If ($script:notifyIcon) { Try { $script:notifyIcon.Dispose() } Catch {} }
		
		## Get the calling function so we know when to display the exiting balloon tip notification in an asynchronous script
		Try { [string]$callingFunction = $MyInvocation.Value.MyCommand.Name } Catch { }
		
		If ($envOSVersionMajor -lt 10)
		{
			
			If ($callingFunction -eq 'Exit-Script')
			{
				Write-Log -Message "Display balloon tip notification asynchronously with message [$BalloonTipText]." -Source ${CmdletName}
				## Create a script block to display the balloon notification in a new PowerShell process so that we can wait to cleanly dispose of the balloon tip without having to make the deployment script wait
				[scriptblock]$notifyIconScriptBlock = {
					Param (
						[Parameter(Mandatory = $true, Position = 0)]
						[ValidateNotNullOrEmpty()]
						[string]
						$BalloonTipText,
						[Parameter(Mandatory = $false, Position = 1)]
						[ValidateNotNullorEmpty()]
						[string]
						$BalloonTipTitle,
						[Parameter(Mandatory = $false, Position = 2)]
						[ValidateSet('Error', 'Info', 'None', 'Warning')]
						$BalloonTipIcon, # Don't strongly type variable as System.Drawing; assembly not loaded yet in asynchronous scriptblock so will throw error
						[Parameter(Mandatory = $false, Position = 3)]
						[ValidateNotNullorEmpty()]
						[int32]
						$BalloonTipTime,
						[Parameter(Mandatory = $false, Position = 4)]
						[ValidateNotNullorEmpty()]
						[string]
						$AppDeployLogoIcon
					)
					
					## Load assembly containing class System.Windows.Forms and System.Drawing
					Add-Type -AssemblyName 'System.Windows.Forms' -ErrorAction 'Stop'
					Add-Type -AssemblyName 'System.Drawing' -ErrorAction 'Stop'
					
					[Windows.Forms.ToolTipIcon]$BalloonTipIcon = $BalloonTipIcon
					$script:notifyIcon = New-Object -TypeName 'System.Windows.Forms.NotifyIcon' -Property @{
						BalloonTipIcon = $BalloonTipIcon
						BalloonTipText = $BalloonTipText
						BalloonTipTitle = $BalloonTipTitle
						Icon = New-Object -TypeName 'System.Drawing.Icon' -ArgumentList $AppDeployLogoIcon
						Text = -join $BalloonTipText[0 .. 62]
						Visible = $true
					}
					
					## Display the balloon tip notification asynchronously
					$script:NotifyIcon.ShowBalloonTip($BalloonTipTime)
					
					## Keep the asynchronous PowerShell process running so that we can dispose of the balloon tip icon
					Start-Sleep -Milliseconds ($BalloonTipTime)
					$script:notifyIcon.Dispose()
				}
				
				## Invoke a separate PowerShell process passing the script block as a command and associated parameters to display the balloon tip notification asynchronously
				Try
				{
					Execute-Process -Path "$PSHOME\powershell.exe" -Parameters "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & {$notifyIconScriptBlock} '$BalloonTipText' '$BalloonTipTitle' '$BalloonTipIcon' '$BalloonTipTime' '$AppDeployLogoIcon'" -NoWait -WindowStyle 'Hidden' -CreateNoWindow
				}
				Catch { }
			}
			## Otherwise create the balloontip icon synchronously
			Else
			{
				Write-Log -Message "Display balloon tip notification with message [$BalloonTipText]." -Source ${CmdletName}
				[Windows.Forms.ToolTipIcon]$BalloonTipIcon = $BalloonTipIcon
				$script:notifyIcon = New-Object -TypeName 'System.Windows.Forms.NotifyIcon' -Property @{
					BalloonTipIcon = $BalloonTipIcon
					BalloonTipText = $BalloonTipText
					BalloonTipTitle = $BalloonTipTitle
					Icon = New-Object -TypeName 'System.Drawing.Icon' -ArgumentList $AppDeployLogoIcon
					Text = -join $BalloonTipText[0 .. 62]
					Visible = $true
				}
				
				## Display the balloon tip notification
				$script:NotifyIcon.ShowBalloonTip($BalloonTipTime)
			}
		}
		Else
		{
			[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
			[Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime] | Out-Null
			
			$Toast = @"
				<toast>
 	 				<visual>
 			   			<binding template="ToastGeneric">
      						<text>$BalloonTipTitle</text>
      						<text>$BalloonTipText</text>
    					</binding>
  					</visual>
				</toast>
"@
			
			$ToastXml = New-Object -TypeName System.Xml.XmlDocument
			$ToastXml.LoadXml($Toast)
			
			switch ($BalloonTipIcon)
			{
				"Info" { $IconIndex = 76 }
				"Warning" { $IconIndex = 79 }
				"Error" { $IconIndex = 93 }
				"None" { $IconIndex = 0 }
			}
			
			If ($IconIndex -ne 0)
			{
				$IconExtractorCode = @"
using System;
using System.Drawing;
using System.Runtime.InteropServices;

namespace System
{
    public class IconExtractor
    {

        public static Icon Extract(string file, int number, bool largeIcon)
        {
            IntPtr large;
            IntPtr small;
            ExtractIconEx(file, number, out large, out small, 1);
            try
            {
                return Icon.FromHandle(largeIcon ? large : small);
            }
            catch
            {
                return null;
            }
        }
    
        [DllImport("Shell32.dll", EntryPoint = "ExtractIconExW", CharSet = CharSet.Unicode, ExactSpelling = true, CallingConvention = CallingConvention.StdCall)]
        private static extern int ExtractIconEx(string sFile, int iIndex, out IntPtr piLargeVersion, out IntPtr piSmallVersion, int amountIcons);
    }
}
"@
				
				Add-Type -TypeDefinition $IconExtractorCode -ReferencedAssemblies System.Drawing
				$icon = [System.IconExtractor]::Extract("imageres.dll", $IconIndex, $true)
				$bmp = $icon.ToBitmap()
				$bmp.save("$($envTemp)BalloonTipIcon.png", "png")
				
				$ImageElement = $ToastXml.CreateElement("image")
				$ImageElement.SetAttribute("src", "file://$($envTemp)BalloonTipIcon.png")
				$ImageElement.SetAttribute("placement", "appLogoOverride")
				$ToastXml.toast.visual.binding.AppendChild($ImageElement)
			}
			
			$xml = New-Object -TypeName Windows.Data.Xml.Dom.XmlDocument
			$xml.LoadXml($toastXml.OuterXml)
			
			$toastNotification = [Windows.UI.Notifications.ToastNotification]::new($xml)
			$toastNotification.ExpirationTime = [DateTimeOffset]::Now.AddMilliseconds($BalloonTipTime)
			
			$notifier = [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier("$installTitle")
			$notifier.Show($toastNotification)
			
			Start-Sleep -Seconds 1 #so Icon is shown properly in Toast
			Remove-File_EY -Path "$($envTemp)BalloonTipIcon.png"
		}
	}
	End {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
`

The only option I found to show an icon in a Toast is to refer to a physical file.
Therefore I use the IconExtractor C# code to get the Info/Warning/Error icon from imageres.dll and save that temporarily to $($envTemp)BalloonTipIcon.png
Setting the source ($InstallTitle) is done by $notifier = [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier("$installTitle")

**Comment by seanlillis** [comment]
Let's save this for a future release. We should consider including some of the other Toast functionality using the BurnToast module for reference (we do not want to create a dependency by including the module in the toolkit) https://github.com/Windos/BurntToast

It probably makes more sense to break away from the Show-BalloonTip function and create a new Function for Show-ToastNotification for use on W10. Add a "SourceName" parameter with default value pointing to a new variable $installSourceName "PowerShell App Deployment Toolkit", configurable in the XML file.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-balloontip-on-windows-10-rs1-shows-source-windows-powershell-in-toast/1246

**Comment by mjr4077au** [comment]
We've had toast notifications for some time, however we've added the ability to redefine the AppID of our process for balloon tips as per #168.
