### ISSUE TITLE
Ability to modify existing shortcut

### ISSUE THREAD

**Issue by macxcool** [PSAppDeployToolkit/PSAppDeployToolkit#273]
Apparently, if you load a shortcut using 
`$shortcut = $shell.CreateShortcut($path.FullName)`
like the New-Shortcut function is doing now, if the shortcut already exists you can modify its parameters and then save it back out again. This would be a great way of adding something like a Hotkey to an existing shortcut.
Perhaps a -Modify switch can be added that will do this modification and maybe an additional switch for -overwrite with a backup made otherwise.

**Comment by That-Annoying-Guy** [comment]
Why stop there?
If we can read an existing shortcut, why not have a switch that returns the settings of a shortcut or even a Get-Shortcut function.

That way I would get rid of one of my custom functions.

**Comment by macxcool** [comment]
I agree. You could use Get-Shortcut to read in the parameters of an existing shortcut, modify or add some of them, and then write the new shortcut back out, either into a new file or overwriting the existing one. I like it. It would be nice to add HotKey as a parameter to New-Shortcut then, and create a new Get-Shortcut function that could work together with New-Shortcut. I'm trying to figure out what that would look like.

**Comment by That-Annoying-Guy** [comment]
FYI: I have a good start to these Get-Shortcut and Set-Shortcut functions. I will post them if Sean wants them.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/ability-to-modify-existing-shortcut/1186
