### ISSUE TITLE
Execute-MSI does not pass -AddParameters or -Parameters

### ISSUE THREAD

**Issue by ACiDGRiM** [PSAppDeployToolkit/PSAppDeployToolkit#274]
Execute MSI does not pass the parameters specified with -addparameters or -parameters

`Execute-MSI -Action Install -Path "$dirFiles\PrinterInstallerClient.msi" -AddParameters "/QN HOMEURL=http://url"`

Executes like this:

`Executing [C:\Windows\system32\msiexec.exe /i "C:\Windows\ccmcache\eh\Files\PrinterInstallerClient.msi" REBOOT=ReallySuppress /QB-! /L*v "C:\Windows\Logs\Software\PrinterInstallerClient_Install.log"`

Oddly enough, if running 
```

 . .\AppDeployToolkit\AppDeployToolkitMain.ps1
Execute-MSI -Action Install -Path "$dirFiles\PrinterInstallerClient.msi" -AddParameters "/QN HOMEURL=http://url"
```

The expected execution is run

`Executing [C:\Windows\system32\msiexec.exe /i "C:\Windows\ccmcache\eh\Files\PrinterInstallerClient.msi" REBOOT=ReallySuppress /QB-! /QN HOMEURL=http://url /L*v "C:\Windows\Logs\Software\PrinterInstallerClient_Install.log"`

See attached file renamed to .txt

[Deploy-Application - Copy.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/1020589/Deploy-Application.-.Copy.txt)

**Comment by ACiDGRiM** [comment]
Changing Execute-MSI -Action Install
to
Execute-MSI -Action "Install"

Resolved the issue

**Comment by xxcchhyy** [comment]
Same situation here on latest release

"Install" didn't work for me

I've tried some options - AddParameters, Parameters, '' "", but none of them works

**Comment by That-Annoying-Guy** [comment]
This issue should be closed
