### ISSUE TITLE
Show-InstallationRestartPrompt and the Zero-Config MSI Install feature clash

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#275]
If you call the Countdown-to-Reboot GUI from inside Deploy-Application.ps1:

`Show-InstallationRestartPrompt -Countdownseconds 600`

This calls AppDeployToolkitMain.ps1 a second time as a separate instance to display the Countdown-to-Reboot GUI without blocking Deploy-Application.ps1 that called it.

But before that happens, AppDeployToolkitMain.ps1 sees an MSI in the \Files\ folder and installs it thanks to the Zero-Config MSI Installation feature. (I don't use this feature BTW)

If your MSI is small and installs fine for you with the defaults or your package has no MSI, ignore this bug. But for me, my MSI has an external CAB file of 1GB and need properties to be set. So I stare at a blank screen for 10 minutes...

## Solution
In AppDeployToolkitMain.ps1 in the ScriptBody section, look for 

`If ($defaultMsiFile) {`

Replace with:

`If (($defaultMsiFile)  -and -not $ReferredInstallName ) {`

**Comment by seanlillis** [comment]
Thanks, this fix has been added for the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
