### ISSUE TITLE
Install-MSUpdates detects update even after install

### ISSUE THREAD

**Issue by nimega** [PSAppDeployToolkit/PSAppDeployToolkit#277]
I used appdeploy to install updates via Install-MSUpdates which works great the first run.

After manually uninstalling the updates and rebooting the system it still detects that the update is installed, however it is not. Many reboots and no go anyway.

Using vbs to detect installed updates it states that the update is NOT installed, but running appdeploy it still shows as installed and won't install it again.
![appdeploy log](https://cloud.githubusercontent.com/assets/17589911/26623633/9c5c3212-45ee-11e7-8db2-a852de7a23c7.PNG)
![vbs log](https://cloud.githubusercontent.com/assets/17589911/26623632/9c5a5960-45ee-11e7-9b52-a43c23826dd5.PNG)

**Comment by rilax1010** [comment]
I had a similar issue. We've built a new custom Cmdlet to manage Microsoft Updates using wusa.exe and working with exit codes...
We can manage some special cases with exit codes:
2359301 = Reboot required
2359302 = Update is already installed
2359303 = Update is already uninstalled
-2145124329 = Not applicable

**Comment by seanlillis** [comment]
This is a bug with the com object method in Test-MSUpdates. We'll need to do more digging to understand why it doesn't detect uninstalls.

**Comment by DennisVH** [comment]
@nimega, can you provide the source code of the vbs that you use to detect if a Microsoft Update is installed or not?
(KB2588507.vbs and KB2921916.vbs in the screenshot)

**Comment by Silencer0001** [comment]
I've replaced the COM section with this code since Get-Hotfix wasn't working on some of my W7 stations. For me the COM object worked great. But after removing the update on a windows 7 x64 machine, PSADT still reported that the app was installed with the COM section.

Code:
`            If (-not $kbFound) {
                ## CUSTOM: Check for update using WMI
                Write-Log -Message 'Unable to detect Windows update history via Get-Hotfix cmdlet. Trying via Get-WMIObject in the class Win32_QuickFixEngineering.' -Source ${CmdletName}
			    gwmi -query "SELECT * FROM Win32_QuickFixEngineering WHERE HotFixID = '$kbNumber'" -ErrorAction 'SilentlyContinue' | ForEach-Object { $kbFound = $true }
            }`

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/install-msupdates-detects-update-even-after-install/1215

**Comment by mjr4077au** [comment]
This code's been thoroughly reworked in v4, which is due for a public preview soon. If this issue is still a problem against v4, on supported Windows 10/11 targets, please let us know.
