### ISSUE TITLE
Using Show-InstallationRestartPrompt wipes the log file

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#278]
f you call the Countdown-to-Reboot GUI from inside Deploy-Application.ps1:

`Show-InstallationRestartPrompt -Countdownseconds 600`

This calls AppDeployToolkitMain.ps1 a second time as a separate instance to display the Countdown-to-Reboot GUI without blocking Deploy-Application.ps1 that called it.
This works fine but the second instance of AppDeployToolkitMain.ps1 also wipes out the log file of  Deploy-Application.ps1. (My private fork rolls log files but this bug rolls the log files for nothing and creates confusion in the field)

## Solution
in AppDeployToolkitMain.ps1, edit Show-InstallationRestartPrompt function to add **-DisableLogging**:

Replace
`			Start-Process -FilePath "$PSHOME\powershell.exe" -ArgumentList "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -File `"$scriptPath`" -ReferredInstallTitle `"$installTitle`" -ReferredInstallName `"$installName`" -ReferredLogName `"$logName`" -ShowInstallationRestartPrompt $installRestartPromptParameters -AsyncToolkitLaunch" -WindowStyle 'Hidden' -ErrorAction 'SilentlyContinue'`

with
`			Start-Process -FilePath "$PSHOME\powershell.exe" -ArgumentList "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -File `"$scriptPath`" -ReferredInstallTitle `"$installTitle`" -ReferredInstallName `"$installName`" -ReferredLogName `"$logName`" -ShowInstallationRestartPrompt $installRestartPromptParameters -AsyncToolkitLaunch -DisableLogging" -WindowStyle 'Hidden' -ErrorAction 'SilentlyContinue'`

And around line 10500:
Replace
```
	$appDeployMainScriptAsyncParameters.Remove('ReferredLogName')
	Show-InstallationRestartPrompt @appDeployMainScriptAsyncParameters
```

with
```
	$appDeployMainScriptAsyncParameters.Remove('ReferredLogName')
	$appDeployMainScriptAsyncParameters.Remove('DisableLogging')
	Show-InstallationRestartPrompt @appDeployMainScriptAsyncParameters
```

(I'll try to setup a fork and a pull request since this is getting a bit much)

**Comment by seanlillis** [comment]
I can't reproduce this issue, the Show-InstallationPrompt and Show-InstallationRestartPrompt append to the same log file in [Asynchronous] entries, without overwriting previous content. This is the case if you run the basic Deploy-Application.ps1 script with those functions. How can I reproduce the issue? Under what conditions are you seeing these functions wipe out the log file? If there is a bug here, my first preference would be to fix it by not overwriting log file content, or alternativel by creating a new log file with the calling function appended to it, in order to preserve logging for those functions.

**Comment by That-Annoying-Guy** [comment]
Maybe it happens only if you use:
<Toolkit_AppendLogsInstead>True</Toolkit_AppendLogsInstead>

I'll have to DL the most recent version and try it. All I know is that it overwrote the log file on Win7 SP1 English.

BTW: Can I update or delete my "That-Annoying-Guy/PSAppDeployToolkit" fork without screwing up the pull requests for you? (New to this Pull request thing. I pkg apps. I only deal with Github for PSADT)

**Comment by seanlillis** [comment]
I couldn't find that XML option anywhere, is that your own addition?

I think you are good to update your fork. We'll work around it if it interferes with the pull request, I don't think we'll pull the changes as they are anyway, I used a slightly different fix for one of the issues you raised.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/using-show-installationrestartprompt-wipes-the-log-file/1193

**Comment by luki1412** [comment]
Write-Log doesn't overwrite files only appends them. The xml setting you mentioned isn't one of ours.
Seems like this is a bug in your own fork of the toolkit or it is related to an older version of the toolkit.
