### ISSUE TITLE
AppDeployToolkitBanner with variable size

### ISSUE THREAD

**Issue by Hedkandi** [PSAppDeployToolkit/PSAppDeployToolkit#280]
It would be nice if the forms from Show-Installation* would resize to fit an image of variable size but with a minimum size to hold labelcontents and buttons

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/appdeploytoolkitbanner-with-variable-size/1179

**Comment by luki1412** [comment]
The UI now scales with the height of the image. The width we keep fixed.
