### ISSUE TITLE
Execute-ProcessAsUser without -Wait: Task is deleted before Task is started

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#281]
When running Execute-ProcessAsUser without the -Wait parameter in a few cases it happens that the Task is deleted before the Task Engine received message to start the task.

In the log file everything show correct, but in Event Viewer\Applications and Services Logs\Microsoft\Windows\TaskScheduler I get the following:
Information ; 2017/6/1 15:14:33 ; Task Triggered by User ; Task Scheduler launched "{...}" instance of task "\PSAppDeployToolkit-ExecuteAsUser" for user "..."
Information ; 2017/6/1 15:14:34 ; Task registration deleted ; User "NT Authority\System" deleted Task Scheduler task "\PSAppDeployToolkit-ExecuteAsUser"
Information ; 2017/6/1 15:14:34 ; Task Engine received message to start task ; Task Engine "...:Interactive[1]" received a message from Task Scheduler service requesting to launch task "\PSAppDeployToolkit-ExecuteAsUser"
Error ; 2017/6/1 15:14:34 ; Task Start Failed ; Task Scheduler failed to start "\PSAppDeployToolkit-ExecuteAsUser" for user "...". Additional Data: Error Value: 2147942402.

Suggested solution is to add Start-Sleep -Seconds 1 when Wait parameter is not set:
`## Wait for the process launched by the scheduled task to complete execution`
`If ($Wait) {`
`	Write-Log -Message "Waiting for the process launched by the scheduled task [$schTaskName] to complete execution (this may take some time)..." -Source ${CmdletName}`
`Start-Sleep -Seconds 1`
`While ((($exeSchTasksResult = & $exeSchTasks /query /TN $schTaskName /V /FO CSV) | ConvertFrom-CSV | Select-Object -ExpandProperty 'Status' | Select-Object -First 1) -eq 'Running') {`
`Start-Sleep -Seconds 5`
`}`
`#  Get the exit code from the process launched by the scheduled task`
`[int32]$executeProcessAsUserExitCode = ($exeSchTasksResult = & $exeSchTasks /query /TN $schTaskName /V /FO CSV) | ConvertFrom-CSV | Select-Object -ExpandProperty 'Last Result' | Select-Object -First 1`
`Write-Log -Message "Exit code from process launched by scheduled task [$executeProcessAsUserExitCode]." -Source ${CmdletName}`
`}`
`Else	{ Start-Sleep -Seconds 1 }`
`## Delete scheduled task`

**Comment by seanlillis** [comment]
This will be fixed in the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
