### ISSUE TITLE
Execute-MSI fails with systems that are still using PowerShell 2.0

### ISSUE THREAD

**Issue by z442a9** [PSAppDeployToolkit/PSAppDeployToolkit#282]
Just noticed that if I use execute-msi function with systems that are still at PowerShell 2.0 it will fail.

![image](https://user-images.githubusercontent.com/22090797/26865099-e29a87f4-4b63-11e7-8a17-516d300dc168.png)

**Comment by That-Annoying-Guy** [comment]
Execute-MSI is a PSAppDeployToolkit-defined function and have nothing to do with running XP/2003 with PowerShell 2.0. It's more likely your Deploy-Application.ps1 is not loading \AppDeployToolkit\AppDeployToolkitMain.ps1 which defines the Execute-MSI function .

**Comment by z442a9** [comment]
These are Windows 7 machines with PS2.0. This is odd because Windows 10 machines run the script without any problems.

**Comment by That-Annoying-Guy** [comment]
Then that means the Execute-MSI does not get declared when  loading \AppDeployToolkit\AppDeployToolkitMain.ps1.

The log file would should shed some light on this. I don't you should not be able to see this error message. Something else must have broken before you got this far.

**Comment by z442a9** [comment]
It was error in the script. I used VSCode to edit the file and there was some odd spaces in "Execute-MSI" line that VSCode didn't show, but when I opened the file in PowerShell ISE I noticed those with the help of color syntax highlighting.
