### ISSUE TITLE
BalloonTip doesn't launch asynchronously when initiated from Exit-Script

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#283]
On Windows 7 x64 the BalloonTip stating that the installation is finished, isn't shown.
Reason is that the BalloonTip isn't started asynchronously because the $callingFunction variable is empty.
`Try { [string]$callingFunction = $MyInvocation.Value.MyCommand.Name }`

To populate the $callingFunction correctly line should be:
`Try { [string]$callingFunction = (Get-Variable -Name MyInvocation -Scope 1).Value.Mycommand.Name }`

I've tested by adding 
`Write-Log -Message "callingfunction = [$callingFunction]"`
After the Try/Catch statement.

**Comment by seanlillis** [comment]
Thanks a lot, we'll add this fix to the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
