### ISSUE TITLE
Get-UserProfile Freezes

### ISSUE THREAD

**Issue by ml58158** [PSAppDeployToolkit/PSAppDeployToolkit#284]
Hello,

When I run get-userprofile, the code will start iterating through all the users, then will freeze up and never complete.

It doesn't return any errors and doesn't show any log notes, but will just freeze infinitely until the script is killed.

Example Code:

		$sourcepath =  "$dirSupportFiles\caddtools\"
		$fullpath = $env:APPDATA + "\CDMS\updatecaddtools\UpdateCaddTools.exe"
		$ProfilePaths = Get-UserProfiles | Select-Object -ExpandProperty 'ProfilePath' -Verbose
		
		ForEach ($Profile in $ProfilePaths) {
    	New-Folder -Path $fullpath
		Copy-File -Path $sourcepath -Destination $fullpath
		}

**Comment by ml58158** [comment]
I also get alot of SID errors as well.

]LOG]!><time="09:18:32.953-240" date="06-09-2017" component="ConvertTo-NTAccountOrSID" context="CDM_INC\LARKINM" type="3" thread="15552" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Convert the SID [S-1-5-80-3122520773-3457611151-16741425-567802887-1405509344] to an NT Account name.]LOG]!><time="09:18:32.965-240" date="06-09-2017" component="ConvertTo-NTAccountOrSID" context="CDM_INC\LARKINM" type="1" thread="15552" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Failed to convert the SID [S-1-5-80-3122520773-3457611151-16741425-567802887-1405509344] to an NT Account name. It may not be a valid account anymore or there is some other problem. 
Error Record:
-------------

Message        : Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be 
                 translated."
InnerException : System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be 
                 translated.
                    at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, 
                 Type targetType, Boolean forceSuccess)
                    at System.Security.Principal.SecurityIdentifier.Translate(Type targetType)
                    at CallSite.Target(Closure , CallSite , Object , Type )

FullyQualifiedErrorId : IdentityNotMappedException
ScriptStackTrace      : at ConvertTo-NTAccountOrSID<Process>, 
                        C:\Users\larkinm\Desktop\PW_CE_2.96\AppDeployToolkit\AppDeployToolkitMain.ps1: line 4058
                        at <ScriptBlock>, 
                        C:\Users\larkinm\Desktop\PW_CE_2.96\AppDeployToolkit\AppDeployToolkitMain.ps1: line 4169
                        at <ScriptBlock>, 
                        C:\Users\larkinm\Desktop\PW_CE_2.96\AppDeployToolkit\AppDeployToolkitMain.ps1: line 4168
                        at Get-UserProfiles<Process>, 
                        C:\Users\larkinm\Desktop\PW_CE_2.96\AppDeployToolkit\AppDeployToolkitMain.ps1: line 4166
                        at <ScriptBlock>, C:\Users\larkinm\Desktop\PW_CE_2.96\Deploy-Application.ps1: line 242
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\Users\larkinm\Desktop\PW_CE_2.96\AppDeployToolkit\AppDeployToolkitMain.ps1:4058 char:6
                  + ...             $NTAccount = $NTAccountSID.Translate([Security.Principal. ...
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



Error Inner Exception(s):
-------------------------

Message        : Some or all identity references could not be translated.
InnerException :

**Comment by That-Annoying-Guy** [comment]
Find a utility or different way to get an NT Account name from sid **S-1-5-80-3122520773-3457611151-16741425-567802887-1405509344**.

If you get a similar error, you might have a broken local SAM or Registry.

----- Technical stuff below -----
Get-UserProfile relies on ConvertTo-NTAccountOrSID. 
The line that is failing in ConvertTo-NTAccountOrSID is:
`$NTAccountSID = New-Object -TypeName 'System.Security.Principal.SecurityIdentifier' -ArgumentList $SID`

But ConvertTo-NTAccountOrSID has a Try/catch and should just make it just return nothing or blank back to Get-UserProfile.

What I don't know is where in the log does the hanging occur? Is it before this section or after it?
