### ISSUE TITLE
Remove-File hangs if -Recurse is not used and item is a folder and isn't empty.

### ISSUE THREAD

**Issue by macxcool** [PSAppDeployToolkit/PSAppDeployToolkit#287]
Remove-File hangs if -Recurse isn't used and the item is a non-empty folder. This is because Remove-Item throws up a dialog asking if you want to continue. Since we have Remove-Folder and Remove-File has a -Recurse switch, can we just have Remove-File check for sub-items and throw an error and continue in this case?

**Comment by seanlillis** [comment]
I've pushed a commit to fix this in the next release:

Fixed issue in Remove-File where a confirmation dialogue would hang the script if a non-empty folder is encountered when the Recurse switch is not specified

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
