### ISSUE TITLE
Exit-Script should never be called inside of Internal toolkit functions. 

### ISSUE THREAD

**Issue by gerane** [PSAppDeployToolkit/PSAppDeployToolkit#288]
The toolkit should never call Exit-Script inside of a function like Execute-* or the UI functions. The function should throw an error and the Deploy-Application Catch block should handle the Exit-Script. This behavior goes against the normal expected behavior of PowerShell. 

When using standard switches such as Passthru it should be implemented the way the user expects. This could cause considerable issues for users. A user expects passthru to allow output to be passed down the pipeline, but the implementation in some of the commands in the toolkit have a completely different implementation. In the Execute-* commands, if you don't use passthru or continueonerror, it runs Exit-Script inside of the function, meaning the standard way of handling errors and standard passthru practices aren't followed. The function should throw and error regardless of passthru being applied, and the catch block should handle the exception. If continueonerror is true, then it should ignore the error and continue on as expected. It shouldn't mean the function itself kills off everything.

In my scenario, I have added special error handling and output handling to the try and catch blocks of the Deploy-Application.ps1 files. I do this for added logging and metrics. I have custom extensions for logging to event logs, logstash and things like this to be able to monitor issues at a higher level. The way the toolkit has implemented Exit-Script, passthru, continueonerror and several other commands break the standard way PowerShell is supposed to work and is expected to work. This means that my error handling functions are bypassed in those scenarios. I have spoken with others who have added custom logging and error handling to the catch block as well, so this is likely impacting others without them realizing it as well.

I had thought about modifying the Exit-Script command originally to add my logging, but went against it to make upgrading the toolkit easier. I think adding it to the ends of the try and catch block should be the proper way to do this, and the toolkit should only throw errors internally and allow the final catch block handle the  Exit-Script.

I am also wondering if you could help me understand where all the toolkit does this. I know where Exit-Script is called, but it gets more difficult when you might have other internal commands calling commands that use Exit-Script.

EDIT: I wanted to add, there are also situations where you want to run a command and catch the error to avoid further execution in that try block, but continue on after the catch block. Normally you might have some that looks like this.

```powershell
Try
{
    command-GetsExecuted
    command-ThrowsError
    command-GetsSkipped
}
Catch [command-ThrowsErrorType]
{
    "Do something here without throwing an error to handle the command-ThrowsError exception"
}
Catch
{
    Throw
}

"Continue on with script"
```

However, this won't work as expected in the Toolkit. You wouldn't use Passthru on Execute-Process if you weren't using it in a pipeline if Passthru worked like it is expected to work, and you wouldn't supply ContinueOnError $true because you want to to throw an error so the 3rd command gets skipped and you can do something based on the error type to remedy issue or do something else.

Instead you would have to supply Passthru to all execute-process commands even though they aren't in a pipeline, which goes against how people expect PowerShell to work.

**Comment by LMCO-psadt-devs** [comment]
I 100% agree that no PSADT function should Exit the script ... at most it should throw an exception that could be caught in the main body of the Deploy-Application.ps1 script.

**Comment by gerane** [comment]
I wanted to open an issue for discussion. I wasn't sure if there was a
reason it was implemented like this. I was looking into what it might take
to do a pull request to fix this, but there are a lot of moving parts that
I am not totally familiar with.

It seems like you should be able to replace all instances of Exit-Script
with Throw + a specific error or error type. In the Exit-Script command,
you could look for those specific errors or types and return special return
codes based on that.

I could be overlooking something, so was hoping to get some feedback on the
issue.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/exit-script-should-never-be-called-inside-of-internal-toolkit-functions/1171

**Comment by luki1412** [comment]
I added two PRs for this that allow you to use a parameter that stops Execute- functions from calling Exit-Script allowing you to handle it yourself. Other functions that call it are mainly Show- functions that require it due to them allowing to defer installation or trigger restart. We can't really change those.

**Comment by luki1412** [comment]
You can now stop functions from exiting the script through a parameter. Then you can handle the exit code on your own.
