### ISSUE TITLE
Query - User Files and Keys

### ISSUE THREAD

**Issue by keane2017** [PSAppDeployToolkit/PSAppDeployToolkit#289]
Good morning,
apologies I am new to the toolkit

can you advise if it has functionality to input files for the logged on user in appdata for example?
and to input HKCU Keys for the logged on user?
this is specifically around SCCM Deployments and we have a need not to log the user off but there is sometimes a need to input either of the above to get the user up and running without logging off and we have a vb wrapper which does this but I'm looking to move away from it to this?

Thanks and apologies if this has being answered somewhere, I have read the documentation and not 100% sure

Thanks

**Comment by cyborgrd** [comment]
You can use script like thatfor folder and files:


`			$Users = Get-UserProfiles | Where-Object { $_.ProfilePath -NotMatch 'Default' }
			for ($i=0; $i -lt $Users.count; $i++){
			$UserProfilePath = $Users.ProfilePath[$i]
			$Userpath = "$UserProfilePath\AppData\Roaming\Adobe"
			if (Test-Path $Userpath)
				{ 
				Write-Log -Message "Try to delete: '$($Userpath)'" -Source "$($MyInvocation.MyCommand)" -Severity 2
				Remove-Folder -Path "$Userpath" }
       		}`

and for regs:
`$HKCURegistrySettings = {
        Remove-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Fischer & Kerrn' -SID $UserProfile.SID -Recurse -ErrorAction SilentlyContinue
        Remove-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Fischer & Kerrn A/S' -SID $UserProfile.SID -Recurse -ErrorAction SilentlyContinue #Funktioniert wegen dem / nicht
		Remove-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Wow6432Node\Microsoft\Active Setup\Installed Components\{181EC36C-EBE7-470A-BF94-85EC7D35AAA3}' -SID $UserProfile.SID -Recurse -ErrorAction SilentlyContinue
		Remove-RegistryKey -Key 'HKEY_CURRENT_USER\Software\Microsoft\Active Setup\Installed Components\Concierge-Services-Resources-Userkeys' -SID $UserProfile.SID -Recurse -ErrorAction SilentlyContinue
		}
		Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $HKCURegistrySettings`

**Comment by cyborgrd** [comment]
If you want only logged on user, you can filter it by variable 
If ($usersLoggedOn)

**Comment by keane2017** [comment]
Hi
thanks for a swift response,
would I then have to add the scripts elsewhere?
i.e. if you used your scripts above where do they live in psappdeploytoolkit?

sorry I'm very new to this.

**Comment by cyborgrd** [comment]
I ot really understand what you mean. I've posted only examples, how you can copy or remove files or folders to user profiles. You must change it and integrate in your installer script

**Comment by keane2017** [comment]
Good morning
apologies for the late response
been very new to this, can I just clarify something.

if I have a file which needs to go into appdata/local, can this file be stored in the wrapper when deployed or does it need to be in the msi then called from the msi?

**Comment by cmschube** [comment]
> *if I have a file which needs to go into appdata/local, *


See page 39 of the documentation for how to use the Copy-File function.
There's even an example on how to use it.. $envLocalAppData will give you
the path to c:\users\<username>\AppData\Local which you can build off of to
get where you need to go.. Check the documentation for variable "shortcuts"
to specific locations  (pages 33-37)..


C:\PS>Copy-File -Path "$dirSupportFiles\MyApp.ini" -Destination
> "$envLocalAppData\MyApp.ini"


*can this file be stored in the wrapper when deployed or does it need to be
> in the msi then called from the msi? *


 You can store files in and use the $dirFiles or $dirSupportFiles variable
locations which are built into the script to copy files to the local
machines..  I tend to leave the msi installers alone (i.e. don't add
anything to them - let them install and finish using the standard options)
and manipulate my "end state" of the installation within the
"Post-Installation" section in the DeployApplication.ps1.


Hope this helps.

**Comment by That-Annoying-Guy** [comment]
FYI: this stuff will only work for the user profile that is running the wrapper.
If you need it to copy a file to all existing and future users on the machine, consider using Set-ActiveSetup.
