### ISSUE TITLE
Remove initial focus from buttons

### ISSUE THREAD

**Issue by LMCO-psadt-devs** [PSAppDeployToolkit/PSAppDeployToolkit#290]
Current dialogs, when displayed, get focus and have a default button focused as well.
This is an issue if the user is working and presses the <_Enter_> or <_Space_> keys when the dialog appears. This results in the user inadvertently electing to do something (or miss an important prompt) without realizing it.

It would be nice to have the option to prevent the buttons from having focus when the dialog is presented.
This could easily be accomplished by setting focus to a non button control inside the Load event.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/remove-initial-focus-from-buttons/1189

**Comment by mjr4077au** [comment]
This has been added into v4.
