### ISSUE TITLE
Deploy-Application.exe logging / meaningful exitcodes

### ISSUE THREAD

**Issue by LMCO-psadt-devs** [PSAppDeployToolkit/PSAppDeployToolkit#291]
Deploy-Application.exe needs to have its own log to capture its processing steps, **_especially_** if something does not go as planned.

It also needs to have some meaningful exit codes, in cases of failure.

If I run Deploy-Application.exe (from a CfgMgr deployment), I have no visibility to the standard error/out messages written by Deploy-Application.exe to the console. On top of that, it returns a successful exit code of zero (0) even when it fails.

_Example 1:_
%> `$rc = Execute-Process -Path .\Deploy-Application.exe -Parameters "-DeployMode Silent -InvalidParam" -PassThru`
%> `$rc | Format-List *`

StdOut   : No '-Command' parameter specified on command-line. Adding parameter '-Command
           "C:\LMADT\Scripts\testbeta\1.0.0\Deploy-Application.ps1"'...
           Administrator rights are required...
           PowerShell Path: C:\WINDOWS\System32\WindowsPowerShell\v1.0\PowerShell.exe
           PowerShell Parameters: -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden
           -Command & { & 'C:\LMADT\Scripts\testbeta\1.0.0\Deploy-Application.ps1' -DeployMode
           Silent -InvalidParam; Exit $LastExitCode }
**ExitCode : 0**
StdErr   :

_Example 2:_
%> `$rc = Execute-Process -Path .\Deploy-Application.exe -Parameters "-File c:\tmp\thisdoesnotexist.ps1" -PassThru`
%> `$rc | Format-List *`

StdOut   : .ps1 file specified on command-line. Appending '-Command' parameter name...
           Unable to find the App Deploy Script file: c:\tmp\thisdoesnotexist.ps1.
           Please ensure you have all of the required files available to start the installation.
           A critical component of the App Deployment Toolkit is missing.
**ExitCode : 0**
StdErr   :

1. These failures should not return an ExitCode of zero (0) 
2. The error message should be in StdErr, not StdOut

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/deploy-application-exe-logging-meaningful-exitcodes/1192

**Comment by Howard0101** [comment]
Additionally if you do make a mistake in the syntax of Powershell in the Deploy-Application.ps1 (like a superfluous bracket), the Deploy-Application.exe simply returns ErrorCode 0 eventhough your PS1 is never run. To catch this kind of mistake is really hard. It will be extremely helpful if the exe returns any kind of error from powershell as non-zero return code. Please implement this soon. Thank you.

**Comment by mjr4077au** [comment]
This has been addressed in our v4 branch.
