### ISSUE TITLE
unable to store return code in a varaibale

### ISSUE THREAD

**Issue by harshakola1985** [PSAppDeployToolkit/PSAppDeployToolkit#294]
Hi,
I'm trying to store return code executed by the process, but unfortunately  return code value is always blank
Execute-MSI -Action Uninstall -Path "{35159268-7E2F-47D1-AAF2-A951A61DB5B4}" -PassTru

Write-host "MSI Return code is : $returnCode"

Any advise..

**Comment by HpotsirhcH** [comment]
Hi,
you have to store the output in a variable like this:
$output = Execute-MSI -Action Uninstall -Path "{35159268-7E2F-47D1-AAF2-A951A61DB5B4}" -PassThru
Write-host "MSI Return code is : $($output.ExitCode)"

that worked for me.

**Comment by harshakola1985** [comment]
Ty will give a try

**Comment by harshakola1985** [comment]
It didn't work from me. I was trying to call same command . return value is an empty string..

**Comment by HpotsirhcH** [comment]
I tried it again and it worked for me. What toolkit version did you use?
Can you send the part of the code?

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/unable-to-store-return-code-in-a-varaibale/1188
