### ISSUE TITLE
Ram variable request

### ISSUE THREAD

**Issue by NathanTheGr8** [PSAppDeployToolkit/PSAppDeployToolkit#295]
I suck at naming variables meaningfully and succinctly but having a global variable for system ram would be nice. Something like

$ram = Get-WMIObject -class Win32_PhysicalMemory -ComputerName $env:COMPUTERNAME | Measure-Object -Property capacity -Sum | % {[Math]::Round(($_.sum / 1GB),2)}

I am using this for deployment of chrome. I only want to deploy Chrome to 64bit OS and when ram > 4. Just thought I would share the idea to see if it would be something other people liked.

**Comment by seanlillis** [comment]
This will be available in the next release as $envSystemRAM

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
