### ISSUE TITLE
Show-InstallationProgress: The C++ module failed to load during appdomain initialization. System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll

### ISSUE THREAD

**Issue by bruckect** [PSAppDeployToolkit/PSAppDeployToolkit#298]
I am running this installation on Server Core 2016 with the latest Windows Updates. [Other issues on GitHub have led me to believe this has to do with .NET 4.7 installed](https://github.com/Microsoft/dotnet/issues/431). I completely agree that this is a problem, however I am running this installation Non Interactively OR Silently. It appears that all other Toolkit functions do not display their GUI elements as long as $deployModeSilent or $deployModeNonInteractive are set. I have done some testing/debugging and see that there appears to be a return line for $deployModeSilent so the GUI **_should_** never be displaying, but yet is is. I have added additional write-log lines as outlined below and they are never output to the log or the console.

```
Function Show-InstallationProgress {
            Begin {
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	    }
	    Process {
		Write-Log -Message "Deploy Mode Silent = [$deployModeSilent]" -Source ${CmdletName}
		Write-Log -Message "Deploy Mode NonInteractive = [$deployModeNonInteractive]" -Source ${CmdletName}
		If ($deployModeSilent) { Return }
#< Part of the function that draws the GUI #>
}
```

Since I never see my Write-Log lines output, it would appear that Show-InstallationProgress is also referenced somewhere else outside of AppDeployToolkitMain.ps1, like Deploy-Application.exe or AppDeployToolkitMain.cs perhaps? 

As a quick and dirty workaround, I have modified my Deploy-Application.ps1 to do this check before we call Show-InstallationProgress. 

```
if (-not ($deployModeSilent -or $deployModeNonInteractive)) {
        Show-InstallationProgress -StatusMessage "Uninstalling previous versions of $installTitle. Please Wait..."
}
```
This is a clunky workaround in my opinion and I think this should be a relatively straightforward fix, but I'm not sure where else to dig in.

I'm happy to do more troubleshooting or provide additional info for re-producing this issue.

See full error details below. 

> [Pre-Installation] :: Error Record:
> -------------
> 
> Message        : The type initializer for '<Module>' threw an exception.
> InnerException : <CrtImplementationDetails>.ModuleLoadException: The C++ 
>                  module failed to load during appdomain initialization.
>                   ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Fr
>                  amework64\v4.0.30319\WPF\wpfgfx_v0400.dll ---> 
>                  System.ComponentModel.Win32Exception: The specified module 
>                  could not be found
>                     --- End of inner exception stack trace ---
>                     at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* 
>                  relDllPath, UInt16* baseDllPath)
>                     at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
>                     at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr 
>                  cleaningUpFunc)
>                     at ?A0x3dfe6d80.CreateCModuleInitialize()
>                     at ?A0x3dfe6d80.??__E?A0x3dfe6d80@cmiStartupRunner@@YMXXZ()
>                     at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
>                     at <CrtImplementationDetails>.LanguageSupport.InitializePer
>                  AppDomain(LanguageSupport* )
>                     at <CrtImplementationDetails>.LanguageSupport._Initialize(L
>                  anguageSupport* )
>                     at <CrtImplementationDetails>.LanguageSupport.Initialize(La
>                  nguageSupport* )
>                     --- End of inner exception stack trace ---
>                     at 
>                  <CrtImplementationDetails>.ThrowModuleLoadException(String 
>                  errorMessage, Exception innerException)
>                     at <CrtImplementationDetails>.LanguageSupport.Initialize(La
>                  nguageSupport* )
>                     at .cctor()
> 
> FullyQualifiedErrorId : System.TypeInitializationException
> ScriptStackTrace      : at <ScriptBlock>, 
>                         C:\Windows\ccmcache\9\Deploy-Application.ps1: line 132
>                         at <ScriptBlock>, <No file>: line 1
>                         at <ScriptBlock>, <No file>: line 1
> 
> PositionMessage : At C:\Windows\ccmcache\9\Deploy-Application.ps1:132 char:9
>                   +         Show-InstallationProgress -StatusMessage 
>                   "Uninstalling previo ...
>                   +         
>                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Error Inner Exception(s):
> -------------------------
> 
> Message        : The C++ module failed to load during appdomain initialization.
>                  
> InnerException : System.DllNotFoundException: C:\Windows\Microsoft.NET\Framewor
>                  k64\v4.0.30319\WPF\wpfgfx_v0400.dll ---> 
>                  System.ComponentModel.Win32Exception: The specified module 
>                  could not be found
>                     --- End of inner exception stack trace ---
>                     at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* 
>                  relDllPath, UInt16* baseDllPath)
>                     at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
>                     at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr 
>                  cleaningUpFunc)
>                     at ?A0x3dfe6d80.CreateCModuleInitialize()
>                     at ?A0x3dfe6d80.??__E?A0x3dfe6d80@cmiStartupRunner@@YMXXZ()
>                     at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
>                     at <CrtImplementationDetails>.LanguageSupport.InitializePer
>                  AppDomain(LanguageSupport* )
>                     at <CrtImplementationDetails>.LanguageSupport._Initialize(L
>                  anguageSupport* )
>                     at <CrtImplementationDetails>.LanguageSupport.Initialize(La
>                  nguageSupport* )
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Message        : C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v04
>                  00.dll
> InnerException : System.ComponentModel.Win32Exception (0x80004005): The 
>                  specified module could not be found
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Message        : The specified module could not be found
> InnerException :

**Comment by HpotsirhcH** [comment]
Hello, 
i had the same issue a few days ago with a normal C#/WPF application in windows PE. The Issue was here that with Windows 10 1703 Microsoft moved the wpf components in the HTA extension for PE. I dont know, is there a way to activate WINPE features in Core? The main issue here that all requiered WPF Dll are not installed.

So i think you or in the PSADT must run a check and if the server a core server, the deploymode changed to silent.

A short way for this is:
if (Test-Path "$envwindir\explorer.exe") { $DeployMode = "NonInteractive" } 

I hope this will help you

Regards

**Comment by bruckect** [comment]
Thanks for the suggestion @HpotsirhcH. I tried it and I am still getting the same error, I have narrowed the issue to be around the $DeployModeSilent variable within the Show-InstallationProgress function. It appears that even thought I call Show-InstallationProgress from Deploy-Application.ps1, it isn't directly being invoked from AppDeployToolkitMain.ps1. As I stated above, I manually added some Write-Log lines to the Begin block of the Show-InstallationProgress function and they are never written to the screen or to the log. So the block of code inside of Show-InstallationProgress that is supposed to creating the GUI is never executed. The error message appears to manifest itself the same way as yours did, but I have no desire to have the GUI appear when I specify $DeployMode = 'Silent' or $DeployMode = 'NonInteractive'.

Does this make sense?

**Comment by HpotsirhcH** [comment]
@bruckect Does something like that appear in your log "Bypassing Installation Prompt [Mode: " ? If not the $deployModeSilent is still false.

You can also do some thing like that.
if (Test-Path "$env:windir\explorer.exe") { $NoWindows = $true }

if (!$NoWindows)
{
## Show Welcome Message, 
		Show-InstallationWelcome 		
		## Show Progress Message (with the default message)
		Show-InstallationProgress
}

**Comment by bruckect** [comment]
@HpotsirhcH That is basically the same workaround that I proposed originally and it works fine, however, my concern is why the Toolkit's logic to handle this isn't firing. I really appreciate your help working around the issue, but I have done that, I was just hoping to work toward a longer term solution.

**Comment by andregabrich** [comment]
> Message : The type initializer for '' threw an exception.
InnerException : .ModuleLoadException: The C++
module failed to load during appdomain initialization.

I had this error when I tried to initialize a calendar app installed on MS Outlook, CalDav Synchronizer.
After many tries to solve this, I re-installed Microsoft Netframework, and my application worked. I hope that this tip help someone. 

Have a nice day. ;)
