### ISSUE TITLE
Install-Msupdates

### ISSUE THREAD

**Issue by psstewart** [PSAppDeployToolkit/PSAppDeployToolkit#302]
The function install-msupdates is not working correctly when installing .msp files. It gives the error cannot find the msi file. 

To install the .msp files, the "Installation type for Windows Installer Patch" code needs to be changed to $file.fullname in the install-msupdates function. 

Correct code is below. 

If (-not (Test-MSUpdates -KBNumber $kbNumber)) {
					Write-Log -Message "KB Number [$KBNumber] was not detected and will be installed." -Source ${CmdletName}
					Switch ($file.Extension) {
						#  Installation type for executables (i.e., Microsoft Office Updates)
						'.exe' { Execute-Process -Path $file -Parameters '/quiet /norestart' -WindowStyle 'Hidden' -ContinueOnError $true }
						#  Installation type for Windows updates using Windows Update Standalone Installer
						'.msu' { Execute-Process -Path 'wusa.exe' -Parameters "`"$file`" /quiet /norestart" -WindowStyle 'Hidden' -ContinueOnError $true }
						#  Installation type for Windows Installer Patch
						'.msp' { Execute-MSI -Action 'Patch' -Path $file.fullname -ContinueOnError $true }
					}
				}

**Comment by seanlillis** [comment]
Can you check which version of the toolkit you are running? This bug was fixed in v3.6.8:
"Fixed issue in Install-MSUpdates where the full path to the update file was not passed to Execute-Process for installation"

**Comment by psstewart** [comment]
Version 3.6.9. The installation for the Windows Installer Patch .msp does not pass to the execute-msi correctly.

**Comment by seanlillis** [comment]
OK, but your suggested correct code is there in v3.6.9 $file.fullname so I'm not sure what the issue. I couldn't reproduce it.

**Comment by psstewart** [comment]
Probably user error on my end. Thank you for looking into the issue.
