### ISSUE TITLE
Lnk case sensitive

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#303]
Function New-Shortcut 

Line 4528
(($path.FullName).EndsWith('.lnk')) is case sensitive. Not sure how twist it to make it not case sensitive.

**Comment by sbf-** [comment]
Make it lowercase first:
`(($path.FullName).ToLower().EndsWith('.lnk'))`

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
