### ISSUE TITLE
Test-MSUpdates makes wrong assumption about Powershell 2.0

### ISSUE THREAD

**Issue by jopels** [PSAppDeployToolkit/PSAppDeployToolkit#304]
The `Test-MSUpdates` function checks for the installed PowerShell version.

`If ([int]$envPSVersionMajor -ge 3) {
				Get-Hotfix -Id $kbNumber -ErrorAction 'SilentlyContinue' | ForEach-Object { $kbFound = $true }
			}
			Else {
				Write-Log -Message 'Older version of Powershell detected, Get-Hotfix cmdlet is not supported.' -Source ${CmdletName}
			}`

If the installed version of PowerShell is below 3, it does not use the `Get-Hotfix` function, although there is no reason to do so, as I am running Powershell 2.0 and I can use `Get-Hotfix` just fine. Or did I miss something here?

**Comment by seanlillis** [comment]
Can you check which version of the toolkit you are running? This bug was fixed in v3.6.8:

"Fixed issue in Install-MSUpdates where the full path to the update file was not passed to Execute-Process for installation"

**Comment by seanlillis** [comment]
I can't see why PS v3.0 is required for this cmdlet, we'll remove this in the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
