### ISSUE TITLE
Documentation Modifications

### ISSUE THREAD

**Issue by jt-65** [PSAppDeployToolkit/PSAppDeployToolkit#306]
The following 
"Issue" is such a strong word, but being new to the PSADT, I rely on the documentation.  I'm using the 3.6.9 documentation with the 3.6.9 toolkit.

Remove-File - The documentation indicates that -ContinueOnError is a switch parameter, but it is not.  I have to pass a Boolean value with this parameter or I receive "Missing an argument for parameter..."

Set-RegistryKey - it took me three tries to determine that DWord value data should be passed as decimal. It's not explicitly stated, and there is not example for DWord.  As for DWord examples, any example, for any registry-related function, always seems to use values that are the same in hex and decimal, so they didn't help clear up this issue.

**Comment by jt-65** [comment]
Here's another.  $envCommonPrograms is NOT set in AppDeployToolkitMain

**Comment by seanlillis** [comment]
This will be updated in the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
