### ISSUE TITLE
Set-RegistryKey and Foward Slashes

### ISSUE THREAD

**Issue by bruckect** [PSAppDeployToolkit/PSAppDeployToolkit#308]
I would like to resurrect an issue that was Closed in 3.6.9 based on this issue https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/158.

It turns out, that the fix that was put in place `$key = $key.Replace('/',"$([char]0x2215)")` does not place the proper forward slash that is created by other applications. I have had success by modifying the line to `$key = $key.Replace('/',"$([char]0x002F)")`. [It seems that others on Reddit have uncovered this same issue.](https://www.reddit.com/r/PowerShell/comments/34kvyv/how_do_you_escape_in_powershell/s)

Can we please update the Set-RegistryKey function to include this modification or some type of switch that can give us either option?

**Comment by DennisVH** [comment]
This will be resolved in the next release

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
