### ISSUE TITLE
Registry key for deferrals not being correctly set

### ISSUE THREAD

**Issue by 4niljain** [PSAppDeployToolkit/PSAppDeployToolkit#31]
There seems to be a bit of a bug in 3.6.2 where it seems when deferrals are enabled, the variable $regKeyDeferHistory does not get correctly set.  This is because it has a dependency on the $InstallName variable being defined but it seems that this is being constructed later in the script.  This results in the deferral value being set in HKLM\Software\PSAppDeploy rather than in for example HKLM\Software\PSAppDeploy\$InstallName.

This can cause an issue in the scenario of an older package in which this is not an issue is run first and deferred.  If a package based on 3.6.2 is then subsequently run, it will take on the $InstallName value on the first package tha's run and so effect the deferral number for the older package (assuming they've both run in the same Windows session).

**Comment by sintaxasn** [comment]
Thanks, this has been fixed and will be included in 3.6.4
