### ISSUE TITLE
Execute-ProcessAsUser

### ISSUE THREAD

**Issue by Danimal247** [PSAppDeployToolkit/PSAppDeployToolkit#311]
Looking for guidance in order to execute a simple Powershell script under the Users context - I have two scenarios that I've tested, one works and the other doesn't. 

1. This doesn't work, I suspect because it's calling a new instance of powershell.exe that $dirFiles (aka the Files directory in the deployment toolkit) isn't available to the new instance of powershell? 

``Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command & { & `"$dirFiles\myscript.ps1`"; Exit `$LastExitCode``

2. This does work, but it complicates the application deployment because I have to copy the script to the C:\ drive in the pre-installation section, execute it during the installation section, and then remove it in the post-installation section.

``Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command & { & `"C:\myscript.ps1`"; Exit `$LastExitCode }" -Wait``

What's the most appropriate way to handle this situation? In batch scripting with SCCM, I often rely on the %~DP0 feature to execute files out of the current directory (to which the parent folder name is dynamic and not known in advance).

**Comment by harmar1** [comment]
Hi Danimal247,

this works for me:

Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command & { & `"$dirSupportFiles\myscript.ps1`"; Exit `$LastExitCode }" -RunLevel LeastPrivilege -Wait -PassThru

**Comment by Danimal247** [comment]
Hi hamar1,

Thanks for your reply. I tried tackling your suggestion today, but it didn't work as suggested.

I tried playing around some more and discovered that two `'s were able to resolve my issue. I have no idea why, and I would not have discovered this on my doing without looking at additional examples.

#Executes successfully 
``Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command & { & `"$dirFiles\myscript.ps1`"; Exit `$LastExitCode }" -RunLevel LeastPrivilege -Wait -PassThru``

#Doesn't execute successfully 
``Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command & { & "$dirFiles\myscript.ps1"; Exit `$LastExitCode }" -RunLevel LeastPrivilege -Wait -PassThru``

...and provides the following at the console:

_[Post-Installation] [Execute-Process] :: Standard error output from the process: ERROR: No mapping between account names and security IDs was done.(35,5):LogonType:
[Post-Installation] [Execute-Process] :: Execution completed with exit code [1].
[Post-Installation] [Execute-ProcessAsUser] :: Failed to create the scheduled task by importing the scheduled task XML file [C:\Users\Public\PSAppDeployToolkit\PSAppDeployToolkit-ExecuteAsUser.xml]._

**Comment by Danimal247** [comment]
So I wanted to discover if the back ticks were the cause of this issue the entire time, and it turns out they are. Reducing the command down to the following still works:

#Executes Successfully
``Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command & {`"$dirFiles\myscript.ps1`"; Exit `$LastExitCode }"``

Hope this helps someone out!

**Comment by Danimal247** [comment]
I would like to add onto my original question...

When using Execute-ProcessAsUser, how do I get it to run a Batch script instead of a Powershell script? All of my testing so far indicates this isn't going to work...I've tried several variations of cmd /c, launcher scripts, etc. 

I think this would be excellent functionality, if not already baked into the toolkit, it would be amazing to include it as it will make using existing .bat or .cmd deployments easily transferable. 

I have had success using `Execute-Process "C:\temp\test.bat" ` - but these particular scripts need to run as the logged on user and access batch environmental variables like %appdata%

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.

**Comment by Danimal247** [comment]
Hi Sean, can you elaborate what is fixed now? Is it the syntax, and if so what part is no longer necessary?
