### ISSUE TITLE
Windows 10 INPlace UPGrade

### ISSUE THREAD

**Issue by itadder** [PSAppDeployToolkit/PSAppDeployToolkit#312]
Anyone know of issues with PSAppDeploytoolkit used for the in-place upgrade of Windows 10?

**Comment by skinnystick22** [comment]
I have the same question, also has anyone tried inplace upgrades on computers that have encryption?

**Comment by skinnystick22** [comment]
Correction, not only does the machines we want to push to have encryption, that encryption has a preboot that comes up for the registered user to login to before you can even login to Windows. Please let me know if the above question by itadder is possible, as well as if anyone else works somewhere they use encryption and preboot.

**Comment by skinnystick22** [comment]
I have been playing around with this and the setup.exe from the root of the Windows 10 ISO, as well as the setup.exe in the sources folder both throw an unknown command line parameter when I pass it ‘/auto Upgrade /quiet /noreboot /copylogs “C:\Windows\Logs\Software”’. I get the same error when using the Execute-Process from PSADT as well as Start-Process built in function.

**Comment by CosmicSingularity** [comment]
What is the encryption product used. With McAfee Drive encryption you have
to upgrade to 7.2 and use the /ReflectDrivers ""%SystemDrive%\Program
Files\McAfee\Endpoint Encryption\OSUpgrade" in the setup command line
parameters. For preboot, the security team applied epo policy to enable use
of mcafee utility to bypass preboot for X number of reboots.

**Comment by skinnystick22** [comment]
We use Symantec Endpoint Encryption. What version of the Windows 10 Installer are you using, Pro, Enterprise? With the Pro version it argues with the parameters I pass it. Like the first one I pass it, /auto upgrade. It says auto is unknown.

**Comment by clreinki** [comment]
We use PSAD for Win10 in-place upgrades and it works flawlessly.  Below is the code I've used with success (note that $dirfiles contains the entire Win 10 install dvd contents):

```
If ($deploymentType -ine 'Uninstall') {
		##*===============================================
		##* PRE-INSTALLATION
		##*===============================================
		[string]$installPhase = 'Pre-Installation'
		## <Perform Pre-Installation tasks here>
		Write-Log -Message "Checking if Windows Update reboot pending..." -Source "PSAD" -LogType "CMTrace"
		$pend = (Get-PendingReboot).IsWindowsUpdateRebootPending
		If ($pend) {
			Write-Log -Message "Reboot Pending: Yes" -Source "PSAD" -LogType "CMTrace"
			Exit-Script -ExitCode 69001
		}
		Else {
			Write-Log -Message "Reboot Pending: No" -Source "PSAD" -LogType "CMTrace"
		}
		Write-Log -Message "Checking if Laptop..." -Source "PSAD" -LogType "CMTrace"
		$lap = (Test-Battery -PassThru).IsLaptop
		If ($lap) {
			Write-Log -Message "IsLaptop: True" -Source "PSAD" -LogType "CMTrace"
			$bat = (Test-Battery -PassThru).BatteryLifePercent
			If ($bat -lt 0.33) {
				Write-Log -Message "Stopping Update Due to Low Battery" -Source "PSAD" -LogType "CMTrace"
				Exit-Script -ExitCode 69001
			}
			Else {
				Write-Log -Message "Battery is Charged" -Source "PSAD" -LogType "CMTrace"
			}
		}
		Else {
			Write-Log -Message "IsLaptop: False" -Source "PSAD" -LogType "CMTrace"
		}
		Write-Log -Message "Pre-Installation Checks Completed" -Source "PSAD" -LogType "CMTrace"
		
		##*===============================================
		##* INSTALLATION 
		##*===============================================
		[string]$installPhase = 'Installation'
		## <Perform Installation tasks here>
		Write-Log -Message "Starting Upgrade..." -Source "PSAD" -LogType "CMTrace"
		Execute-Process -Path "$dirFiles\setup.exe" -Parameters "/quiet /noreboot /auto upgrade /migratedrivers all /ShowOOBE none /Compat IgnoreWarning /Telemetry Disable"
		Write-Log -Message "Upgrade Completed - Awaiting Reboot..." -Source "PSAD" -LogType "CMTrace"
		
		##*===============================================
		##* POST-INSTALLATION
		##*===============================================
		[string]$installPhase = 'Post-Installation'
		## <Perform Post-Installation tasks here>
		Show-InstallationPrompt -Title 'Windows Update Completed' -Message 'A large Windows update has been applied to your computer.  When you next reboot your computer, it will take approximately 1 hour to complete the update.  IT recommends rebooting when you leave today!' -MessageAlignment 'Left' -ButtonMiddleText 'OK I will reboot when I leave' -PersistPrompt -Timeout 14400
		
	}
```

**Comment by skinnystick22** [comment]
I will give your code a try today and see what happens. Another question, what version of Windows 10 are you using? Pro, Enterprise?

**Comment by clreinki** [comment]
Win 10 Enterprise

**Comment by skinnystick22** [comment]
We are just using Windows 10 Pro. I still haven’t had time today to test your install, but most of the time Windows 10 Pro argued with me about the arguments being passed to it saying they were unknown.

**Comment by skinnystick22** [comment]
Still no luck in getting this to install. 
[Installation] :: Execution failed with exit code [-1047526904].

Has anyone used Microsoft's Windows 10 ADK to prepare an image before installing Windows 10?

**Comment by z442a9** [comment]
skinnystick:

-1047526904 =  Compatibility issues found (hard block):  0xC1900208

Check your Windows 10 upgrade logs so you will find what is causing this error.
