### ISSUE TITLE
$RunAsActiveUser.IsLocalAdmin seems to always be $false - Doesn't detect Admin

### ISSUE THREAD

**Issue by macxcool** [PSAppDeployToolkit/PSAppDeployToolkit#313]
No matter what I do, I always get $false with $RunAsActiveUser.IsLocalAdmin. Can we add in a test like:

([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")

so a script can detect a logged-on user that is in the Administrators Group one way or another?

Thanks

**Comment by seanlillis** [comment]
Thanks, this will be fixed in the next release.

**Comment by seanlillis** [comment]
The suggested fix will not set the correct value in all cases. On servers and in virtual environments, the suggested fix will not necessarily pull the admin status of the correct user.

Can you please provide more info about how the code was executed and also include screenshots of user groups to prove that the current code is not working properly?

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/runasactiveuser-islocaladmin-seems-to-always-be-false-doesnt-detect-admin/1175

**Comment by luki1412** [comment]
Works fine for me. IsLocalAdmin is from User session info.

**Comment by seanlillis** [comment]
No response from @macxcool, closing this as complete.
