### ISSUE TITLE
New DeployMode= "Unattended"

### ISSUE THREAD

**Issue by evgenyfedorov2** [PSAppDeployToolkit/PSAppDeployToolkit#315]
Hi,

There are following Deploy Modes:

1. Interactive -  Show-InstallationWelcome, Show-InstallationProgress displayed
2. Silent - Nothing is displayed
3. Noninteractive - Nothing is displayed

I think we need to have something like "Unattended" deploy mode, where Show-Installation Progress windows would be displayed, but not Show-InstallationWelcome. This would allow users see the progress bar and evertyhing, but would not require any user input

Could you treat it as a feature request?

**Comment by clreinki** [comment]
You can use the "-Silent" parameter when calling Show-InstallationWelcome to allow for unattended/non-interactive execution.  I believe your desired functionality is already implemented.

**Comment by yudinetz** [comment]
Let me explain again:

I have Show-InstallationWelcome and Show-InstallationProgress in the script and it works fine in Interactive mode - I see the welcome message and the progress one.
Now, I need to have some switch to make visible ShowInstallationProgress only (without Show-InstallationWelcome).
Silent switch does not help- it makes invisible both of the above pop-ups.

**Comment by CosmicSingularity** [comment]
If you have no need to close apps, allow defer, or anything else
show-installationwelcome does, comment it out. with a simple #. boom, no
show-installationwelcome.and you still get progress.

**Comment by yudinetz** [comment]
CosmicSingularity, thanks for the answer. I think this is the obvious way, but it does require a script modification. I would like to avoid script modifications and have it via switch option :)

**Comment by luki1412** [comment]
Adding another type would complicate the show-* functions even more and introduce more bugs for little to no advantage. You can easily just use a couple of If statements to show just what you need.
