### ISSUE TITLE
Remove-MSIApplications FilterApplication RegEx-Mode don't use regular expressions

### ISSUE THREAD

**Issue by bammab** [PSAppDeployToolkit/PSAppDeployToolkit#317]
Hi,

I'm testing this framework since yesterday and think there is something wrong.
The FilterApplication and ExcludeFromUninstall Parameter seems not to be handled correctly. If you would to use detection mode RegEx, it only use a "contains text". I don't know if this a feature or a bug, but if a feature the name should be contains - not regex.

# Expected Behavior

RegEx mode from filter (not the global name matching for get-installedapplication) should do really a regex match (eg. "Java \d Update \d{3}")

# Actual Behavior

RegEx mode does a string match operation - alias contains, because the string would be escaped!

# Fix

Code from AppDeployToolkitMain.ps1 (from section "should be uninstalled" by FilterApplication - ExcludeFromUninstall equivalent):
`
If ($Filter[2] -eq 'RegEx') {
If ($installedApplication.($Filter[0]) -match [regex]::Escape($Filter[1])) {
`
The escape don't allow to use regex really!

Should be:
`
If ($Filter[2] -eq 'RegEx') {
If ($installedApplication.($Filter[0]) -match $Filter[1]) {
`
and (optinally) add mode 'contains'
`
ElseIf ($Filter[2] -eq 'Contains') {
If ($installedApplication.($Filter[0]) -match [regex]::Escape($Filter[1])) {
`

Need to be done twice (FilterApplication and ExcludeFromUninstall sections)! 

I could create a pull-request with a fix, but I don't know how do you want to constribute to this project. 

# Debug Information

PSAppDeployToolkit: 3.6.9
PSVersion: 5.1.15063.726
OS: Windows 10 (1703) (64-bit)
Admin rights: YES

**Comment by seanlillis** [comment]
Thanks, this will be resolved in the next release.

**Comment by seanlillis** [comment]
This is fixed in v3.7.0.
