### ISSUE TITLE
Show-InstallationRestartPrompt dialog box is not showing the full message

### ISSUE THREAD

**Issue by Koditghyala** [PSAppDeployToolkit/PSAppDeployToolkit#319]
We have more than 7 lines of message which needs to be displayes for end use via Show-InstallationRestartPrompt. But it is only showing first 6 lines.

Can you please confirm, if there is any limit on message length.

Please let me know, if i need to change any parameter to display more lines.

**Comment by seanlillis** [comment]
This is a hard coded limit of the Windows form "ClientSize" property on the Show-InstallationRestartPrompt and the size and positioning of the labels and buttons within it. There is no parameter to increase the size. The sizes and positioning of the form elements would need to be adjusted manually in the code to increase the size of the label containing the message text.
