### ISSUE TITLE
Method invocation failed because [System.Threading.Mutex] doesn't contain a method named 'Dispose'

### ISSUE THREAD

**Issue by somethingwhere** [PSAppDeployToolkit/PSAppDeployToolkit#32]
On Windows 7 x64 with Powershell running on .Net 2.0 there is no dispose method - see MSDN method list 

https://msdn.microsoft.com/en-us/library/system.threading.mutex_members%28v=vs.80%29.aspx

replacing dispose() with close() on lines 2690 and 9033 allows script to run successfully

Affects scripts when a remove-msiapplications is run before execute-msi and the blocked-execution dialog from running.

**Comment by mmashwani** [comment]
Thanks for reporting this. The Dispose() method was introduced in .NET 3.5. I have switched to using Close() method in the latest beta.

**Comment by mmashwani** [comment]
I decided to call Dispose() method first in a Try block and if that fails, then call Close() method in the Catch block. Please test and see if this works fine for you. Latest beta is here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit

**Comment by mmashwani** [comment]
Never mind the above post. While sometimes the Close() and Dispose() method can do slightly different things, that is not the case here. Both method are the exact same. I went back to only calling Close(). I also moved the ReleaseMutex() method call out of the Finally block as it is not recommended to place it there.
