### ISSUE TITLE
Get-InstalledApplication uses wrong registry key to detect applications

### ISSUE THREAD

**Issue by yudinetz** [PSAppDeployToolkit/PSAppDeployToolkit#320]
Hi,
Currently, the function uses these keys:
'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall','HKLM:SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall'

which does not always work because it is up to a MSI file developer to create or not a sub-key in those keys. Windows Installer technology itself keeps all ProductCode's here HKEY_CLASSES_ROOT\Installer\Products.

I will probably come up with a Pull Request when I have time.

**Comment by seanlillis** [comment]
Best practice for MSI is to write the package information in the HKLM keys. Some of the information in HKCR has been encoded by Microsoft, e.g. package code. We cannot determine most of the information we need from this key, such as uninstall information and there's no easy way to correlate the HKCR key with the HKLM keys. 

"Rule 21: Avoid Using Configuration Data You Don’t Own

As part of the initial design for the Installer, the consistency of installations was achieved via Microsoft taking ownership of the code for the install engine. This includes the location and format of all configuration data. This data is managed by the Installer and direct access by users or applications is discouraged; in fact some of the data is encoded to make it very difficult to manipulate manually. 

You should not try to peek directly into Windows Installer configuration information. Instead, use the Windows Installer API to get the information you need. Accessing the data this way ensures that your package or application will continue to work even if the underlying configuration data changes location or format. "

Source: https://blogs.msdn.microsoft.com/windows_installer_team/2006/05/12/tao-of-the-windows-installer-part-2/

**Comment by seanlillis** [comment]
Hi,
These registry keys follow best practice for MSI. The problem with using HKEY_CLASSES_ROOT\Installer\Products is that it does not contain the same useful information as the "uninstall" keys and there is no way to

**Comment by seanlillis** [comment]
To add, this is the approach recommended by Microsoft:

https://blogs.technet.microsoft.com/heyscriptingguy/2011/11/13/use-powershell-to-quickly-find-installed-software/

**Comment by SierraEcoBravo** [comment]
May want to look at adding detection for HKCU:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall for user based installs. Used by Squirrel and Click-Once installers. Microsoft Teams and Yammer use these keys (as they are User only installs /sigh).
