### ISSUE TITLE
Execute-Process runs language independent for Windows\System32 exe's

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#321]
When the UI language is not English, some exe's (schtasks, fsutil, ...) return output in the UI language and not in English.

Following modification works around this issue and returns the output in English
line 161 - 201
line 313 - 336

https://gist.github.com/DennisVH/3fd0008ead048542783d588082eae434

**Comment by seanlillis** [comment]
Hey Dennis, thanks for the proposed fix, let's include this fix in the next release. Perhaps FRacine who reported the issue in #228 would be willing to test.

**Comment by FRacine** [comment]
Hi,

The problem with #228 is the result is hardcode inside Execute-ProcessAsUser. So I cannot see how it may solve the issue.

**Comment by DennisVH** [comment]
I've tested with schtasks.exe on a Win10 x64 with French UI and that works.
Unfortunately it doesn't work on a Win10 x64 Japanese UI. That requires an additional codepage change (chcp 437).
This enhancement will require some additional investigation for which UI languages a codepage change is required and if it doesn't influence the output (unknown characters)

**Comment by Robert-LTH** [comment]
How about the proposed fix on this page: https://social.technet.microsoft.com/Forums/windowsserver/en-US/6ed8f2d9-082a-4c86-8066-e9b2391f5dff/how-to-change-language-in-powershell-to-english

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/execute-process-runs-language-independent-for-windows-system32-exes/1166

**Comment by mjr4077au** [comment]
This has been addressed in v4 via the fix here: https://stackoverflow.com/a/63115866. In v4, simply call `Set-ADTPowerShellCulture -CultureInfo en-US`, etc to achieve the required result. Will throw if the specified culture is not installed.
