### ISSUE TITLE
Test-Powerpoint doesn't work for non-english OS

### ISSUE THREAD

**Issue by jeppe742** [PSAppDeployToolkit/PSAppDeployToolkit#322]
Test-Powerpoint doesn't work for non-english OS, since the window title is only named "powerpoint slide show' in english.

E.g. in danish the title begins with "PowerPoint-diasshow"
![image](https://user-images.githubusercontent.com/12828495/34483054-7c4510ca-efbc-11e7-911d-7b485ef2feb4.png)

**Comment by seanlillis** [comment]
This will be resolved in the next release with an additional check for a Window Title with "PowerPoint-"
