### ISSUE TITLE
Execute-ProcessAsUser failing with -wait language translation problem

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#324]
Any news on this issue? As a few language problems seems showing up and this issue was submit a long time ago, I would like to know if someone would confirm it may be solve in the next revision?

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/228

**Comment by seanlillis** [comment]
See #321 - we will look to include this proposed fix in the next release.
