### ISSUE TITLE
Unable to use New-Object -COMObject Microsoft.SMS.TSEnvironment

### ISSUE THREAD

**Issue by harshakola1985** [PSAppDeployToolkit/PSAppDeployToolkit#325]
Hi,
I'm trying to create a New object using New-Object -COMObject Microsoft.SMS.TSEnvironment. when i run the script in Application model, Script fails stating unable to load Com Object "Microsoft.SMS.TSEnvironment"

Any help

**Comment by rilax1010** [comment]
Hi
Are you running your script inside a Task Sequence execution?

**Comment by harshakola1985** [comment]
I'm using application Model. I think it should work with Task sequence with out any issue.

**Comment by lumirjasny** [comment]
Hi, 
let me add:
The Com Object "Microsoft.SMS.TSEnvironment" is accessible from Application Model, but only during OS installation is running (Task sequence is running). There is small percentage of cases when task sequence (OS installation) was finished but the SCCM was not switched to non-Task sequence and then the Com Object "Microsoft.SMS.TSEnvironment" does not throw an error during New-Object.
So like you already mentioned. If you are creating Com Object "Microsoft.SMS.TSEnvironment" not in task sequence then error occurre so you can use it in Application model to detect if script runs or not in task sequence.
