### ISSUE TITLE
catch inside the toolkit

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#327]
Hi,

From my script I am launching a window saying "wait installation in progress". I am using executeprocess as user function.

If the installation is failing from Inside the toolkit then the script end but my window is still on screen. Is it a way to prevent the Execute-process to not ending but instead just returning the failure making me able to trap it?

Thanks,

**Comment by DennisVH** [comment]
Use $result = Execute-Process ... -Passthru
$result contains ExitCode, stdOut and stdErr
script will not end but you will need to configure the errorhandling yourself.
look at main line 2943-2975 as guideline

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/catch-inside-the-toolkit/1160

**Comment by luki1412** [comment]
> Hi,
> 
> From my script I am launching a window saying "wait installation in progress". I am using executeprocess as user function.
> 
> If the installation is failing from Inside the toolkit then the script end but my window is still on screen. Is it a way to prevent the Execute-process to not ending but instead just returning the failure making me able to trap it?
> 
> Thanks,

I added a parameter that will stop the function from exiting the script. It will be available in the next release.
