### ISSUE TITLE
3.7.0 Show-InstallationWelcome error when called with no parameters (AppDeployToolkitMain line 5871)

### ISSUE THREAD

**Issue by bshiznit** [PSAppDeployToolkit/PSAppDeployToolkit#328]
When calling Show-InstallationWelcome with no parameters:
[DBG]: PS C:\WINDOWS\system32>> Show-InstallationWelcome
Get-RunningProcesses : Cannot bind argument to parameter 'ProcessObjects' because it is null.
At AppDeployToolkitMain.ps1:5871 char:49
+ ...  While ((Get-RunningProcesses -ProcessObjects $processObjects -OutVar ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-RunningProcesses], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-RunningProcesses

**Comment by DennisVH** [comment]
@bshiznit: changing Function Get-RunningProcesses parameter ProcessObjects Mandatory to false and running Show-InstallationWelcome with no parameters doesn't show a welcome prompt.
Therefore I would suggest to just comment out Show-InstallationWelcome if you don't pass CloseApps/AllowDefer/CheckDiskSpace parameter.
Or are you expecting different behavior?

**Comment by mmashwani** [comment]
I discovered this issue today and filed a bug report without realizing we already had one for this issue. Please see below issue for the fix to this bug:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/343

**Comment by bshiznit** [comment]
Pull request too 😉
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/330

I'm using that fix (since 3.7.0 released basically) in our local toolkit.
We use it for the defer even when no applications are required to be
closed, so -CloseApps is empty.

Let me know if I can provide anything.

-Ryan

On Mar 15, 2018 5:48 PM, "Muhammad Mashwani" <notifications@github.com>
wrote:

I discovered this issue today and filed a bug report without realizing we
already had one for this issue. Please see below issue for the fix to this
bug:
#343 <https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/343>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/328#issuecomment-373558346>,
or mute the thread

**Comment by DennisVH** [comment]
This will be resolved in the next release

**Comment by bshiznit** [comment]
Thanks! Keep up the great work team

**Comment by cwmoriarty** [comment]
> This will be resolved in the next release

was this ever resolved? I still see it in 3.7.0

**Comment by luki1412** [comment]
> > This will be resolved in the next release
> 
> was this ever resolved? I still see it in 3.7.0

Yes it was in newer releases.
