### ISSUE TITLE
Help examples incorrect for Enable-TerminalServerInstallMode & Disable-TerminalServerInstallMode

### ISSUE THREAD

**Issue by appPackager** [PSAppDeployToolkit/PSAppDeployToolkit#331]
The help use examples for Enable-TerminalServerInstallMode and Disable-TerminalServerInstallMode have "Mode" truncated (i.e. Enable-TerminalServerInstall instead of Enable-TerminalServerInstallMode)

**Comment by DennisVH** [comment]
will be fixed in the next release

**Comment by seanlillis** [comment]
Thanks - this was actually corrected in the documentation for the 3.7.0 release, but not in the source code.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/help-examples-incorrect-for-enable-terminalserverinstallmode-disable-terminalserverinstallmode/1167

**Comment by luki1412** [comment]
Fixed.
