### ISSUE TITLE
3.7.0 - Multiple process termination logic: Show-InstallationWelcome -CloseApps  

### ISSUE THREAD

**Issue by a-hodevs** [PSAppDeployToolkit/PSAppDeployToolkit#332]
New functionality of toolkit introduced an issue to logic of getting multiple processes closed by clicking "Close Process" button. When processes passes to Show-InstallationWelcome started after Welcome Dialog is displayed they appear in the process list, but after you click "Close Process" button they do not get terminated. And UI dialog is Displayed once again.
Steps to replicate issue:
1)	Process definition: Show-InstallationWelcome -CloseApps "notepad,regedit"-CloseAppsCountdown "7200"
2)	Initial state: Both Processes are running, Deploy-Application.exe executed
3)     UI Displayed 2 processes running
4)	Close one of the processes (Notepad)
5)     UI Displayed 1 processes running (Regedit)
6)	Now, open Notepad again
7)     UI Displayed 2 processes running
8)     Click “Close Programs” button
6)	Result: Regedit has been terminated, but UI pop-up displayed to terminate Notepad 2nd time. It I do the trick once again, it will pop-up again.

**Comment by GiddyVulcan** [comment]
Would that be because the Close-Process logic is updating every two seconds, instead of instantaneously?

**Comment by a-hodevs** [comment]
Hi,
I've spend more time and identified that issue existed in previous versions as well, including v3.6.9. 
It's just no one tested this approach until 3.7.0 introduced ability to manipulate with process list.
Issue is caused by logic of terminating processes, where: At first running process is identified by name, but terminated by ID. But between process displayed to user via Show-InstallationWelcome and terminated by pressing "Close Programs" button process name ID might get changed.
In my tests I've added extra function to identify process IDs for running process name(s) after the "Close Programs" button is pressed. So that only valid IDs are processes to termination.

Answering question above:  The Close-Process logic of getting updated in 2, 5 seconds or instantly does not affect on reported issue, Process IDs are not getting updated. 
I think the best is to evaluate Process IDs for validity before termination and terminate all IDs for the running Process name (as user already confirm process termination by pressing the button).

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/3-7-0-multiple-process-termination-logic-show-installationwelcome-closeapps/1170
