### ISSUE TITLE
Set-ActiveSetup ran a night!

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#333]
Hi,

I am trying a script with the latest PSADTK 3.7.0. By running the script manually, everything was looking fine.

But with SCCM the script ran indefinitely.
[Post-Installation] :: Waiting for the process launched by the scheduled task [PSAppDeployToolkit-ExecuteAsUser] to complete execution (this may take some time)...	Execute-ProcessAsUser	2018-02-21 16:13:40	2212 (0x08A4)

The task scheduler has the PSADTK at running.

PSAppDeployToolkit-ExecuteAsUser.vbs:
```
strCommand = chr(34) & "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" & chr(34) & " -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & \" & chr(34) & "C:\PROGRA~1\ORGANI~1\INSTTR~1\Trousses\CITEWH~1.536\ACTIVE~1\ACTIVE~1.PS1\" & chr(34) & "}"
set oWShell = CreateObject("WScript.Shell")
intReturn = oWShell.Run(strCommand, 0, true)
WScript.Quit intReturn
```

PSAppDeployToolkit-ExecuteAsUser.xml
```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo />
  <Triggers />
  <Settings>
	<MultipleInstancesPolicy>StopExisting</MultipleInstancesPolicy>
	<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
	<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
	<AllowHardTerminate>true</AllowHardTerminate>
	<StartWhenAvailable>false</StartWhenAvailable>
	<RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
	<IdleSettings>
	  <StopOnIdleEnd>false</StopOnIdleEnd>
	  <RestartOnIdle>false</RestartOnIdle>
	</IdleSettings>
	<AllowStartOnDemand>true</AllowStartOnDemand>
	<Enabled>true</Enabled>
	<Hidden>false</Hidden>
	<RunOnlyIfIdle>false</RunOnlyIfIdle>
	<WakeToRun>false</WakeToRun>
	<ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
	<Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
	<Exec>
	  <Command>wscript.exe</Command>
	  <Arguments>"C:\Users\Public\PSAppDeployToolkit\PSAppDeployToolkit-ExecuteAsUser.vbs"</Arguments>
	</Exec>
  </Actions>
  <Principals>
	<Principal id="Author">
	  <UserId>ADMEQ\admracfr13</UserId>
	  <LogonType>InteractiveToken</LogonType>
	  <RunLevel>HighestAvailable</RunLevel>
	</Principal>
  </Principals>
</Task>

```

**Comment by FRacine** [comment]
We had no problems with previous versions of PSADTK.

**Comment by FRacine** [comment]
Hi,

Update:
Sound, if I ran execute-processasuser once with nowait to launch a window saying "installation running please wait" then later in the script by running the activesetup the script will hang.

If I disable the first Execute-ProcessAsUser -nowait then just ran the set-activesetup everything is fine...
As soon as I kill the first window the script will complete.

Why?

Thanks,

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/set-activesetup-ran-a-night/1177

**Comment by luki1412** [comment]
Set-ActiveSetup calls execute-processasuser also. Since they create a vbs script under the same name in the same location, one overwrote the other.
