### ISSUE TITLE
ForceCloseAppsCountdown 

### ISSUE THREAD

**Issue by hipslu** [PSAppDeployToolkit/PSAppDeployToolkit#334]
if an installation is started with
> Show-InstallationWelcome -CloseApps $apps -BlockExecution -ForceCloseAppsCountdown $WaitSeconds -CheckDiskSpace -PersistPrompt -AllowDefer -DeferTimes 3

and the $apps are not running, it will countdown to zero and then wait forever without starting at all.
fix which seems to work: changed line 6274 of AppDeployToolkitMain.ps1 from

> $buttonCloseApps.PerformClick()

to

> if ($script:runningProcessDescriptions) {
> $buttonCloseApps.PerformClick()
> } else {
> $buttonContinue.PerformClick()
> }

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/forcecloseappscountdown/1164

**Comment by DennisVH** [comment]
This will be fixed in the next release
