### ISSUE TITLE
Function: Set-PinnedApplication does not work anymore on Windows 10

### ISSUE THREAD

**Issue by crobillard77** [PSAppDeployToolkit/PSAppDeployToolkit#339]
The function to Pin and Unpin shortcuts to the task bar and start menu does not work anymore.
The tool kit contains the code for a supposed workaround for Windows 10, but not working.

This should be at least mentioned in the documentation.

**Comment by pchatham** [comment]
Don’t forget - this function only works in the User context 
I’ve used it in 3.7.0 successfully as user 
Does not work as System/ConfigMgr

**Comment by crobillard77** [comment]
I was running it in the user context logged on with RPD. I tried again, logged on normaly and running it in the user context, and same thing. This does not work, either PinToStartMenu or PinToTaskBar. 

You get this error.
[03-06-2018 19:04:10.786] [Pre-Installation] [Invoke-Verb] :: Performing action [Pin to taskbar] is not programmatically supported for this file [C:\Windows\Notepad.exe].

Anyways, you should documention with this issue better, since it's not working on a Windows 10 with the latest updates.

I dont really need this feature, but a DEV told me they had a ticket open about this with Microsoft, and they didnt believe it was working. So I tested it. I get to the same conclusion.

Thank you very much for your reply.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/function-set-pinnedapplication-does-not-work-anymore-on-windows-10/1159
