### ISSUE TITLE
Change default InstallationDefer_ExitCode

### ISSUE THREAD

**Issue by dersonc** [PSAppDeployToolkit/PSAppDeployToolkit#34]
In the new version of the toolkit the default exit codes changed to use the 60000 - 68999 range, but the InstallationDefer_ExitCode is still 5000. I suggest changing it on the XML settings to be 65000, using the same range as the other exit codes from the toolkit.

```
<InstallationDefer_ExitCode>65000</InstallationDefer_ExitCode>
```

**Comment by mmashwani** [comment]
This has been resolved in the latest 3.6.5 beta.
