### ISSUE TITLE
Create a process as logged on user from System context

### ISSUE THREAD

**Issue by ghost** [PSAppDeployToolkit/PSAppDeployToolkit#340]
We can use ServiceUI but maybe this could be integrated to PSAppDeployToolkit?

http://rzander.azurewebsites.net/create-a-process-as-loggedon-user/

Just saying..

**Comment by cyborgrd** [comment]
I tried the solution some months ago, but our corporate AV blocks it as Virus (false positive) it is not easy to put every package using it to white list

**Comment by z442a9** [comment]
Really? Scanned it in virustotal and all green.

**Comment by DennisVH** [comment]
Have you tried the Execute-ProcessAsUser function?
Execute a process with a logged in user account, by using a scheduled task, to provide interaction with user in the SYSTEM context.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/create-a-process-as-logged-on-user-from-system-context/1162
