### ISSUE TITLE
Function Test-NetworkConnection / Possible Change for Windows 10 Support

### ISSUE THREAD

**Issue by SPatrickStevens** [PSAppDeployToolkit/PSAppDeployToolkit#342]
I've been using PSADT for years, but I had not used the Test-NetworkConnection function until yesterday. It appears that it might need to look for a $_.NetConnectionID -match 'Ethernet' to work properly on Windows 10. Matching 'Local' did not work on the various test machines that I had available when specifically running Windows 10.

Proposed change:

`[psobject[]]$networkConnected = Get-WmiObject -Class 'Win32_NetworkAdapter' | Where-Object { ($_.NetConnectionStatus -eq 2) -and ($_.NetConnectionID -match 'Local' -or $_.NetConnectionID -match 'Ethernet') -and ($_.NetConnectionID -notmatch 'Wireless') -and ($_.Name -notmatch 'Virtual') } -ErrorAction 'SilentlyContinue'`

Thanks for all of the awesome work on the toolkit!

**Comment by DennisVH** [comment]
This will be resolved in the next release

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/function-test-networkconnection-possible-change-for-windows-10-support/1158
