### ISSUE TITLE
Bug in Get-RunningProcesses causes Show-InstallationWelcome to fail

### ISSUE THREAD

**Issue by mmashwani** [PSAppDeployToolkit/PSAppDeployToolkit#343]
If Show-InstallationWelcome is invoked and the -CloseApps option is not used, then the function fails.

The fix is to change the Get-RunningProcesses function so that the -ProcessObjects parameter is not mandatory.

Change line 5514 from:
[Parameter(Mandatory=$true,Position=0)]

To:
[Parameter(Mandatory=$false,Position=0)]

**Comment by Tenet33** [comment]
If Show-InstallationPrompt without -NoWait then Bug in Get-RunningProcesses

**Comment by DennisVH** [comment]
This will be resolved in the next release

**Comment by luki1412** [comment]
Resolved.
