### ISSUE TITLE
Deferral prompt shows "...about to be installed" when deployment type is 'uninstall'

### ISSUE THREAD

**Issue by astratom** [PSAppDeployToolkit/PSAppDeployToolkit#344]
The deferral welcome message shows the same message when installing and uninstalling.
Taken from AppDeployToolkitConfig.xml:
<DeferPrompt_WelcomeMessage>The following application is about to be installed:</DeferPrompt_WelcomeMessage>

Could a separate deferral welcome message be added when the deployment type is "uninstall"?

We're deploying an application uninstallation with a deferral and it sounds confusing because the prompt says the application is about to be installed.

**Comment by bshiznit** [comment]
I need to put a pull request in with a proper fix. I put a workaround in this issue:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/41

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/deferral-prompt-shows-about-to-be-installed-when-deployment-type-is-uninstall/1157
