### ISSUE TITLE
No logging info in Remove-Folder

### ISSUE THREAD

**Issue by My-userid** [PSAppDeployToolkit/PSAppDeployToolkit#347]
There is no logging info in the Function "Remove-Folder". Only errors are logged.
I think there should also be an indication if the function is running successfully.

So right now there is no trace in the logfile that the function has been run.

Using v.3.7.0

**Comment by DennisVH** [comment]
This will be fixed in the next release

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/no-logging-info-in-remove-folder/1141

**Comment by luki1412** [comment]
Logging was added to the function.
