### ISSUE TITLE
Execute PowerShell script inside the package

### ISSUE THREAD

**Issue by LuizHAP** [PSAppDeployToolkit/PSAppDeployToolkit#348]
I'm trying to run the power shell script inside the script with the command below, however it does not run the script.

`Execute-Process -Path "$PSHOME\powershell.exe" -Parameters "-executionpolicy bypass -File & {`"$dirSupportFiles\Remove-PreviousOfficeInstalls.ps1`"; Exit `$LastExitCode }"`

Log:

_[Uninstallation] :: Standard error output from the process: Falha ao processar -File ''C:\Users\lpansarini\Desktop\Programas_para_revisar\Office_x86\SupportFiles\Remove-PreviousOfficeInstalls.ps1'': Não há suporte para o formato do caminho dado. Especifique um caminho válido para o parâmetro -File.
[Uninstallation] :: Execution failed with exit code [-196608]._

PS1 script (https://github.com/OfficeDev/Office-IT-Pro-Deployment-Scripts/tree/master/Office-ProPlus-Deployment/Remove-PreviousOfficeInstalls)

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/execute-powershell-script-inside-the-package/1151
