### ISSUE TITLE
do not uninstall utorrent 3.4.8

### ISSUE THREAD

**Issue by erwiniturrieta** [PSAppDeployToolkit/PSAppDeployToolkit#349]
Hello everyone.
I need help with this.
I am trying to perform an uninstall of Utorrent through SCCM with Appdeploytoolkit but a problem occurs to me.
Only uTorrent is recorded in the profile of the user who installs it and only that user can uninstall it, this is the code that I am using, try to uninstall and then delete the folder Appdata Utorrent.
# <Perform uninstallation="" tasks="" here="">

#Execute - Process - Path 'uTorrent.exe'-'/ Uninstall S' Parameters
		
        Get-ChildItem - Path "C:Users*AppDataRoaminguTorrentutorrent.exe" | " Foreach-Object {Execute-Process - Path $_ - Parameters '/ Uninstall S'}

##*===============================================
		#* POST-UNINSTALLATION
		##*===============================================
		[string] $installPhase = 'Post-Uninstallation'
		
		## <Perform post-uninstallation="" tasks="" here="">
		
        Get-ChildItem - Path "C:Users*AppDataRoaminguTorrent" | " Foreach-Object {Remove-Item $_ - Force - Recurse} but does not work for me, only removes the folder and the application still appears in programs and features.

If I run of form of local and manual form at the session of the user who installed it works correctly. Uninstall (does not appear in programs and features) and eliminates the appdata folder.

someone will have done that can help me

**Comment by michalzobec** [comment]
if this application was installed to User profile and not to Computer, user have rights to uninstall.

equivalent of user profile directory C:\Users\{username}\AppData\Roaming is variable $envAppData

so your command will be

` Execute-Process -Path "$envAppData\uTorrent\uTorrent.exe" -Parameters '/uninstall /s' `

**Comment by erwiniturrieta** [comment]
Thanks for your answer michalzobec.
I will try with this code and inform if it works for me.

**Comment by erwiniturrieta** [comment]
323/5000
michalzobec
Unfortunately, it did not work for me.
if I execute it locally and manually if it works, but it does not work if I try to deploy from sccm.
indeed the program is installed in the user's profile in Path C: \ Users \ Username \ AppData \ Roaming \ uTorrent.
Any idea how to achieve it through deployment of SCCM?

**Comment by dilorenzo1987** [comment]
SCCM executes in system context (and therefore in the systemprofile). 
The uTorrent uninstaller however must be executed for each user in their own user context.

You could try building something around the Execute-ProcessAsUser cmdlet.

Regards,
Fabio Di Lorenzo

**Comment by michalzobec** [comment]
@erwiniturrieta for future is better and more easy for you, make own installation packages installed per Computer, installation per User make many problems ;)

**Comment by erwiniturrieta** [comment]
unfortunately these facilities were made by users with notebooks in their homes.
Now it is necessary to implement a deployment to eliminate this kind of software.
I still can not find a way to uninstall Utorrent, the display passes profile by profile but it does not manage to uninstall the application.
Does anyone have any idea how to get it ??

**Comment by luki1412** [comment]
Can use active setup and run whats inside uninstall string, possibly with silent switch. Active setup is run before desktop is displayed and in user's context.
