### ISSUE TITLE
Deploy-Application.exe: Open File - Security Warning

### ISSUE THREAD

**Issue by SierraEcoBravo** [PSAppDeployToolkit/PSAppDeployToolkit#351]
We are trying to run Deploy-Application.exe from a UNC path for maunal installs and are getting a warning 

> The publisher could not be verified. Are you sure you want to run this software?
> 
> Name: ...PathToApplication\Deploy-Application.exe
> Publisher: **Unknown Publisher**
> Type: Application
> From: \\UNC\ShareName\PathToApplication\

We have tried to use an AppLocker rule to allow this to run without a prompt, but we are seeing mixed results.

Would signing Deploy-Application.exe help?

**Comment by SierraEcoBravo** [comment]
Thanks for the feedback @CosmicSingularity. 

I was able to sign it with an internal code certificate, but it did not help (much). The download flag was not an issue (these have been in use for a while, I found out after posting). In further research everything was working fine and then the warnings started to appear (someone changed the environment).

Enhancement Question: Is is possible to have the PSADT team sign this executable, so we don't see "Unknown Publisher"

**Comment by michalzobec** [comment]
@SierraEcoBravo 

hello, you have your _internal code certificate_ in Trusted Root CA? if not, this is source of your problem. or your _internal code certificate_ is generated from your internal CA?

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/deploy-application-exe-open-file-security-warning/1149

**Comment by mjr4077au** [comment]
The binary will be digitally signed for v4.
