### ISSUE TITLE
Unable to login on Forum

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#352]
On the other PSADTK forums, it is not possible to login with gmail. What is happening?

**Comment by That-Annoying-Guy** [comment]
I'm lockout too. I reported this a year+ ago in issue #247 

I hope you have better luck than me.

**Comment by TXTechie** [comment]
Being new to using the PSADT, I wanted to create an account both the ask questions and to provide assistance, but I am unable to create a new account so that I can login and interact.

**Comment by jt-65** [comment]
I've been unable to log in using Google as well.  Error 400 redirect_uri_mismatch.  

The redirect URI in the request, http://psappdeploytoolkit.com, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/515607522914-bpkskba9123eacvijd7aqn1nuda5e7iq.apps.googleusercontent.com?project=515607522914

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/unable-to-login-on-forum/1152

**Comment by seanlillis** [comment]
The forums have been moved to discourse
