### ISSUE TITLE
Some weird quotation chars used in ApplDeployToolKitMain.ps1 in Function Execute-MSP() line 571

### ISSUE THREAD

**Issue by PH0MB** [PSAppDeployToolkit/PSAppDeployToolkit#353]
$Database = $Installer.GetType().InvokeMember(“OpenDatabase”, “InvokeMethod”, $Null, $Installer, $($mspFile,([int32]32)))

In above code Char(93) =“ And char(94) = ” is used causing the script to crash on some machines.
-----
C:\Temp\Application\Deploy-Application.ps1 : Module [C:\Temp\Application\AppDeployToolk
it\AppDeployToolkitMain.ps1] failed to load:
At C:\Temp\Application\AppDeployToolkit\AppDeployToolkitMain.ps1:571 char:49
+         $Database = $Installer.GetType().InvokeMember(â?oOpenDatabaseâ??, â?o
InvokeMet ...
+                                                       ~
------
replacing it with regular quotes "" solves the matter.

$Database = $Installer.GetType().InvokeMember("OpenDatabase", "InvokeMethod", $Null, $Installer, $($mspFile,([int32]32)))

**Comment by seanlillis** [comment]
This will be resolved in the next release. Thanks.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/some-weird-quotation-chars-used-in-appldeploytoolkitmain-ps1-in-function-execute-msp-line-571/1147

**Comment by luki1412** [comment]
Fixed.
