### ISSUE TITLE
Remove-Folder function typo

### ISSUE THREAD

**Issue by epnash** [PSAppDeployToolkit/PSAppDeployToolkit#354]
Version 3.7.0
AppDeployTookitMain.ps1 Function Remove-Folder
Line 3264 needs a closing ) instead of }
Write-Log -Message "Delete folder [$path] recursively..." -Source $(CmdletName}

**Comment by cyborgrd** [comment]
No it must to be Source ${CmdletName}

**Comment by epnash** [comment]
OK but then it should be {} and not (} as it is now?

**Comment by cyborgrd** [comment]
Ye

**Comment by DennisVH** [comment]
This is fixed in the next release

**Comment by pchatham** [comment]
Tested 
This can be closed
