### ISSUE TITLE
Show-InstallationPrompt and switch statement oddness

### ISSUE THREAD

**Issue by z442a9** [PSAppDeployToolkit/PSAppDeployToolkit#356]
Maybe not a toolkit issue but I don't understand why this isn't working as I want. Switch statement default value is never evaluated for some reason. I want it to be evaluated when the Show-InstallationPrompt goes to timeout. 
```

$promptOptions = @{
            Title            = 'My Title'
            Message          = 'My Message'
            MessageAlignment = 'Left'
            ButtonLeftText   = 'Yes'
            ButtonRightText  = 'No'
            Icon             = 'Question'
            PersistPrompt    = $true
            MinimizeWindows  = $true
            TimeOut          = 30
            ExitOnTimeout    = $false
        }

        $userInput = Show-InstallationPrompt @promptOptions
    
        switch ($userInput) {
           'Yes'{ Write-Log -Message 'Clicked Yes' -Source $deployAppScriptFriendlyName -Severity 1 }
           'No' { Write-Log -Message 'Clicked No' -Source $deployAppScriptFriendlyName -Severity 1 }
           Default { Write-Log -Message 'Clicked nothing. Timeout' -Source $deployAppScriptFriendlyName -Severity 1 }
        }
```

**Comment by z442a9** [comment]
Thanks annoying guy! It worked when casting $userInput as string. Before you posted that I resolved this with:

`if (-not $userInput) { Exit-Script -ExitCode 1 } ` before running switch statement. I really don't still understand why Switch Default value vas never evaluated for null value. I thought it will always run no matter what the value is if it's not hitting any other options.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-installationprompt-and-switch-statement-oddness/1133
