### ISSUE TITLE
Can apps be installed on Windows ServerCore editions with this module?

### ISSUE THREAD

**Issue by KurtDeGreeff** [PSAppDeployToolkit/PSAppDeployToolkit#357]

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/can-apps-be-installed-on-windows-servercore-editions-with-this-module/1145

**Comment by luki1412** [comment]
This toolkit relies on multiple visual libraries from net framework, so I'm assuming that's where it will fail however I don't think the toolkit has been tested on servercore or nano versions of windows server yet.

**Comment by mjr4077au** [comment]
Just to close the loop on this old issue, while v3 and v4 classic dialogs do not work under Server Core, our v4 fluent dialogs do, which should provide full functionality under such environments.

![image](https://github.com/user-attachments/assets/54d2d243-0da6-4aa2-a96f-ce0667fe6f5e)

I've added a guard clause in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/37ea5d48c70bc4fe76e783db6140e9fd8d2d40ef to indicate this.
