### ISSUE TITLE
Exit-Script -ExitCode 3010 does not work

### ISSUE THREAD

**Issue by austinwongcarter** [PSAppDeployToolkit/PSAppDeployToolkit#36]
If you have a process where you want to manually Exit the Script and trigger an SCCM "Soft Reboot", it does not work. The script will always send an exit code of 0. 

I've tried various versions of "Exit-Script -ExitCode 3010" with -AllowRebootPassThru but nothing works. 

Looking at AppDeployToolkitMain.ps1, it looks like the only way it will return a '3010' if $msiRebootDetected is true. I need to be able to exit with 3010 even when I don't use an MSI.

-Austin

**Comment by mmashwani** [comment]
Just set $msiRebootDetected to $true to get it to work. That variable has "Script" scope so you can change the value anywhere in your script.

**Comment by austinwongcarter** [comment]
I suppose that will work, I just modified the AppDeployToolKitMain.ps1 to have this at line 804:

If ( ($AllowRebootPassThru) -and (($msiRebootDetected) -or ($exitCode -eq 3010)) ) {
			Write-Log -Message 'A restart has been flagged as required.' -Source ${CmdletName}
			[string]$balloonText = "$deploymentTypeName $configBalloonTextRestartRequired"
			[int32]$exitCode = 3010
		}
        ElseIf( ($AllowRebootPassThru) -and ($exitCode -eq 1641) ) {
            Write-Log -Message 'A restart has been flagged as required.' -Source ${CmdletName}
			[string]$balloonText = "$deploymentTypeName $configBalloonTextRestartRequired"
			[int32]$exitCode = 1641
		}
		Else {
			[int32]$exitCode = 0
		}

This seemed like a better solution, because the functions now work as expected.

-Austin

**Comment by mmashwani** [comment]
I agree, that is a better solution. I made a few modifications to your logic and added it to the latest beta found here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit

Please test and let me know if it's working as expected.

**Comment by austinwongcarter** [comment]
Thanks, this seems to be working perfectly.

**Comment by mmashwani** [comment]
I'm going to keep the ticket open until 3.6.5 comes out of beta.
