### ISSUE TITLE
Application is not getting installed through "Deploy-Application.exe"

### ISSUE THREAD

**Issue by bagati123** [PSAppDeployToolkit/PSAppDeployToolkit#360]
Hi 
I am unable to install the application using "Deploy-Application.exe", however when I run "Deploy-Application.ps1" application is getting installed. Could you please help what might be the issue.

**Comment by sbf-** [comment]
Do you run Deploy-Application.exe "as administrator"? This is important.

**Comment by bagati123** [comment]
Yes and I tried using PSEXEC also.

**Comment by MIHSssweeny** [comment]
Try copying folder locally then running.
When you run as administrator you lose access to the rest of the source files on network shares

**Comment by bagati123** [comment]
I don't get it. I have copied complete files and folder to my system and tried to run "Deploy-Application.exe" still its nor running.

**Comment by sbf-** [comment]
What command line do you use? From my experience, using wrong syntax silently exits deploy-application.exe

**Comment by bagati123** [comment]
I tried following commands
Deploy-Application.exe -DeploymentType "Install" -DeployMode "Silent"
Deploy-Application.exe -DeploymentType "Install"
Deploy-Application.exe

**Comment by bagati123** [comment]
Its resolved.
I have commented the below command in "Deploy-Application.ps1"
Confirm-Details

**Comment by bagati123** [comment]
Resolved the issue.
