### ISSUE TITLE
When using a code that triggers SCCM FAST RETRY in the XML InstallationUI_ExitCode parameters, defer remaining never goes below 1.

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#361]
Step to reproduce :
- Specify code 1618 for "InstallationUI_ExitCode" parameter in the XML
- Use a low time-out value (unless you want to wait for ~2h at each attempt). I use 5.
- Create an empty package and use theses parameters for SIW :
Show-InstallationWelcome -CloseApps 'notepad' -AllowDeferCloseApps -DeferTimes 3
- Start notepad and deploy your package.
- Let the UI expiration occurs.

#1 attempt : 2 deferals remaining
#2 attempt : 1 deferal remaining
#3 attempt : 0 deferal remaining, but Set-DeferHistory never fire because of the "if" condition when $deferTimes = 0.
```
If (($deferTimes) -or ($deferDeadlineUniversal)) {
	Set-DeferHistory -DeferTimesRemaining $DeferTimes -DeferDeadline $deferDeadlineUniversal
}
```

Proposed fix (Unless letting 1 defer for user that doesn't answer to the pop-up is a wanted feature !)
```
If (($deferTimes -ge 0) -or ($deferDeadlineUniversal)) {
	Set-DeferHistory -DeferTimesRemaining $DeferTimes -DeferDeadline $deferDeadlineUniversal
}
```

Regards

**Comment by DennisVH** [comment]
This will be fixed in the next release

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/when-using-a-code-that-triggers-sccm-fast-retry-in-the-xml-installationui-exitcode-parameters-defer-remaining-never-goes-below-1/1155

**Comment by luki1412** [comment]
Fixed.
