### ISSUE TITLE
Microsoft .NET Framework: The term 'Get-RunningProcessesDynamically' is not recognized...

### ISSUE THREAD

**Issue by SierraEcoBravo** [PSAppDeployToolkit/PSAppDeployToolkit#362]
In Show-WelcomePrompt: If $timerRunningProcesses is started, it is not stopped when Show-WelcomePrompt exits. It appears that if there is a scope shift .NET will throw an error dialog as follows (this is on Windows 10):

![image](https://user-images.githubusercontent.com/22754283/41814327-c9e43220-7716-11e8-844b-09cef8d66aa2.png)

By adding $timerRunningProcesses.Stop() before exiting Show-WelcomePrompt the issue is resolved.

**Comment by kankberry** [comment]
Where exactly would I put $timerRunningProcesses.Stop() without blowing up the whole function? I tried a few spots and none of them fixed it.

**Comment by cyborgrd** [comment]
Hello, please provide the solution for all. Thx

**Comment by SierraEcoBravo** [comment]
`		Switch ($result) {
			OK { $result = 'Continue' }
			No { $result = 'Defer' }
			Yes { $result = 'Close' }
			Abort { $result = 'Timeout' }
		}
		#region PSADT #362 fix: .NET error due to scope shift; need to stop the external process
		If ($configInstallationWelcomePromptDynamicRunningProcessEvaluation) {
			$timerRunningProcesses.Stop()
		}
		#endregion PSADT #362 fix
		Write-Output -InputObject $result
	}
	End {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
#endregion


#region Function Show-InstallationRestartPrompt`

The code is towards the end of Function Show-WelcomePrompt...

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/microsoft-net-framework-the-term-get-runningprocessesdynamically-is-not-recognized/1139

**Comment by dianneman** [comment]
Thanks, solved also my issue !

**Comment by DennisVH** [comment]
This will be fixed in the next release

**Comment by luki1412** [comment]
Fixed.
