### ISSUE TITLE
Android Studio - Problem with installation

### ISSUE THREAD

**Issue by krzesniakkamil** [PSAppDeployToolkit/PSAppDeployToolkit#365]
Hi,I have a problem with silent installation Android Studio. 
During installation i have a error:
[07-16-2018 21:37:29.236] [Installation] [Execute-Process] :: Execution failed with exit code [1223].

My install script:

```
 ##*===============================================
		##* INSTALLATION X64
##*===============================================
		If ($envOSArchitecture -eq '64-Bit') {
        Execute-Process -Path "$dirFiles\android-studio-ide-173.4819257-windows.exe" -Parameters "/NCRC /S /D" #-WindowStyle Hidden

```

**Comment by That-Annoying-Guy** [comment]
Judging by the /NCRC switch, this is a NSIS installer. That error number is not a PSADT error. (They start at 60000)

Look in the PSADT log file for the command line that PSADT uses that causes the 1223 error.
I bet it will happen without PSADT if you try it in a CMD window.

After that, you can try searching using for solutions using the terms: **NSIS ERROR 1223** 
or by contacting the makers of Android Studio.

Please note that PSADT does NOT stop you from trying to install while NOT elevated. 
IOW: make sure you are running Deploy-Application.ps1 **_elevated_**.

**Comment by krzesniakkamil** [comment]
I installed it on a test computer and then copied the installer files to the program files and the SDK to the directory activities and managed to solve the problem of moving around. If someone has a problem I can insert my code.

**Comment by DennisVH** [comment]
According to http://www.edugeek.net/forums/windows-7/173153-android-studio-unattended-install.html exit code 1223 can be threated as success.
So you can run
`Execute-Process -Path "$dirFiles\android-studio-ide-173.4819257-windows.exe" -Parameters "/NCRC /S /D" -IgnoreExitCodes '1223'`

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/android-studio-problem-with-installation/1142
