### ISSUE TITLE
Set-ActiveSetup creates StubExePath for PS1 that will not run.(W7+W10)

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#366]
I have to admit I never needed this to work until now but it fails in both windows 7 and 10 (1709)

```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & \"C:\Admutils\Uninstall\HostNameTool_v2r2\SupportFiles\HostNameTool_v2r2_HKCU.ps1\"}
At line:1 char:131
+ ... licy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & \"C ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

The solution seems to be to remove both **\\** and the offending **&**:

`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command {  &"C:\Admutils\Uninstall\HostNameTool_v2r2\SupportFiles\HostNameTool_v2r2_HKCU.ps1"}`

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/set-activesetup-creates-stubexepath-for-ps1-that-will-not-run-w7-w10/1140

**Comment by DennisVH** [comment]
This will be fixed in next release.
Changed -Command to (replace ~ witch backtick):
`-Command ~"& { & ~\~"$StubExePath~\~"}~""`
