### ISSUE TITLE
Set full controll permissions to folder 

### ISSUE THREAD

**Issue by krzesniakkamil** [PSAppDeployToolkit/PSAppDeployToolkit#367]
Hi everyone,
I am looking for a solution to give permissions to the directory and all files in it.
I would like the permission to have only one group in AD.
If it can not be done, every computer user.
I tried solutions like "icacls" but it did not work ...

And:
`$Acl = Get-Acl "\\R9N2WRN\Share"
$Ar = New-Object System.Security.AccessControl.FileSystemAccessRule("user", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
$Acl.SetAccessRule($Ar)
Set-Acl "\\R9N2WRN\Share" $Acl...`

Maybe I could not use it .. The directory is in "Program Files"

**Comment by luki1412** [comment]
Why does ICACLS not work? I have used it multiple times without issues.

**Comment by z442a9** [comment]
$myADGroup = 'DOMAIN\ADGroup'
$myFolder = "$envProgramFiles\myFolder"

# Full Access to folder 
icacls $myFolder  /grant $myADGroup':(OI)(CI)(RX)'

**Comment by krzesniakkamil** [comment]
@z442a9 thx. It's work perfectly. 

But For FULL. Permission to folder I must use F not RX

```
$myADGroup = 'DOMAIN\ADGroup'
$myFolder = "$envProgramFiles\myFolder"

icacls $myFolder  /grant $myADGroup':(OI)(CI)(F)'
```
