### ISSUE TITLE
Create "Repair" Deployment Type

### ISSUE THREAD

**Issue by seanlillis** [PSAppDeployToolkit/PSAppDeployToolkit#368]
Create "Repair" Deployment Type to support the new ConfigMgr 1807 app repair feature.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/create-repair-deployment-type/1137

**Comment by g4m3c4ck** [comment]
I have written code for this. No major changes were needed. 
The code is posted here https://discourse.psappdeploytoolkit.com/t/add-repair-feature-of-configmgr-1810/1453/3 in your forums.

Attaching a working Deploy-Application.ps1 if needed.

[Deploy-Application.zip](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/2793481/Deploy-Application.zip)

**Comment by My-userid** [comment]
> I have written code for this. No major changes were needed.
> The code is posted here https://discourse.psappdeploytoolkit.com/t/add-repair-feature-of-configmgr-1810/1453/3 in your forums.
> 
> Attaching a working Deploy-Application.ps1 if needed.
> 
> [Deploy-Application.zip](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/2793481/Deploy-Application.zip)

There is more to it than that, if it should be complete.
The translations need to be updated too. And config.xml also.

something like (XML file):
`<DeploymentType_Repair>Repairing</DeploymentType_Repair>`

and (Main.ps1 - line 10812)
```
Switch ($deploymentType) {
	'Install'   { $deploymentTypeName = $configDeploymentTypeInstall }
	'Uninstall' { $deploymentTypeName = $configDeploymentTypeUnInstall }
        'Repair' { $deploymentTypeName = $configDeploymentTypeRepair }
	Default { $deploymentTypeName = $configDeploymentTypeInstall }
}
```

**Comment by PorreKaj** [comment]
Found my self in need of just this today.

**Comment by luki1412** [comment]
#458
