### ISSUE TITLE
Refresh-Desktop is not refreshing the global environment block

### ISSUE THREAD

**Issue by appPackager** [PSAppDeployToolkit/PSAppDeployToolkit#37]
According to help the Refresh-Desktop method refreshes the desktop icons, however,  AppDeployToolkitMain.cs also mentions it will update environment variables (i.e. public static void RefreshDesktopAndEnvironmentVariables()).  In performing testing I do not find indication that the environment block is actually refreshing. I have very similar code I added to my extensions which does refresh the environment.  I was wondering if we can fix the existing SendMessageTimeout to pass the proper params to also allow refresh of the environment block? See my extension code below:
```
 #region Function Refresh-GlobalEnvironment
Function Refresh-GlobalEnvironment {
<#
.SYNOPSIS
	Notifies other processes that the global environment block has changed. This lets 
	other processes pick changes to ENV: without having to reboot or logoff/logon. A 
	non-zero result from SendMessageTimeout indicates success.
.DESCRIPTION
	Notifies other processes that the global environment block has changed. This lets 
	other processes pick changes to ENV: without having to reboot or logoff/logon. A 
	non-zero result from SendMessageTimeout indicates success.
.EXAMPLE
	Refresh-GlobalEnvironment
.LINK
	Http://poshcode.org/2049
#>
	if (-not ("win32.nativemethods" -as [type])) {
    # import sendmessagetimeout from win32
    add-type -Namespace Win32 -Name NativeMethods -MemberDefinition @"
[DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
public static extern IntPtr SendMessageTimeout(
    IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam,
    uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
"@
}

$HWND_BROADCAST = [intptr]0xffff;
$WM_SETTINGCHANGE = 0x1a;
$result = [uintptr]::zero

# notify all windows of environment block change
Write-Log ("Notifying all windows of global environment block change...")
[win32.nativemethods]::SendMessageTimeout($HWND_BROADCAST, $WM_SETTINGCHANGE, [uintptr]::Zero, "Environment", 2, 5000, [ref]$result);
}
#endregion
```

**Comment by mmashwani** [comment]
Please post code in code blocks so it's easier to read. You can do so by surround the code block with three back ticks before and after (I edited your post to add the code block).

Refresh-Desktop will refrest desktop icons and also update the environment block for Windows Explorer so that new processes that are spawned reflect the newly created environment variables. Processes load environment variables at initial start and then it is impossible to update the environment block for that process unless you restart the process. If you need to use an environment variable you just created in the same process that created it, then make a call to Refresh-SessionEnvironmentVariables.

**Comment by mmashwani** [comment]
Please explain in detail what behaviour you notice when using the custom code you posted above vs the behaviour you notice when you use the code in the toolkit. That will give me a better understanding of the issue and what I need to fix.

**Comment by appPackager** [comment]
Perform your test as follows:
1. Open Regedit and change the PATH value located at: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment;Path
2. Open a command prompt and type SET. Note the value for PATH. It should be the old value prior to making a change.
3. Run Refresh-Desktop
4. Open a new command prompt and type SET. Note the value still reflects the value you saw in step #2.
5. Run Refresh-GlobalEnvironment
6. Open a new command prompt and type SET. Note the value for PATH now reflects the change you made in step 1.

**Comment by appPackager** [comment]
The change required to resolve the issue is to make the following change to AppDeployToolkitMain.cs:
old:
```
public static void RefreshDesktopAndEnvironmentVariables()
		{
			// Update desktop icons
			SHChangeNotify(0x8000000, 0x1000, IntPtr.Zero, IntPtr.Zero);
			// Update environment variables
			SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, IntPtr.Zero, "Environment", SMTO_ABORTIFHUNG, 100, IntPtr.Zero);
		}
```

new:
```
public static void RefreshDesktopAndEnvironmentVariables()
		{
			// Update desktop icons
			SHChangeNotify(0x8000000, 0x1000, IntPtr.Zero, IntPtr.Zero);
			// Update environment variables
			SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, IntPtr.Zero, null, SMTO_ABORTIFHUNG, 100, IntPtr.Zero);
		}
```

**Comment by mmashwani** [comment]
Thanks for the update. I've implemented the fix in the latest beta.

**Comment by twahab** [comment]
Hello, we are running version 3.8.1 of the toolkit and seen where the explorer.exe process is stopped during the installation step using Execute-Msi function.  It sounds to me it's happening during the [Installation] :: Refresh the Desktop and the Windows Explorer environment process block.	Update-Desktop	8/6/2020 3:51:08 PM	16600 (0x40D8) Step.  The package completes running to post-installation step, however then user has to sign in and out to get explorer back or launch taskmgr and initiate explorer.exe.  Would appreciate any feedback, thanks
