### ISSUE TITLE
Execute-ProcessAsUser admin prompt when run via SCCM

### ISSUE THREAD

**Issue by JustinSparksIT** [PSAppDeployToolkit/PSAppDeployToolkit#370]
We recently locked down our user’s machines by removing local admin rights, however, we seem to be having some issues with applications that need to be run in the user’s context. When creating an application and setting the install behavior to “Install for System”, then running the setup executable using Execute-ProcessAsUser we are getting prompted for Administrator credentials when installing via SCCM even though the application is set to install as system. Any ideas on how to change this behavior? 

Execute-ProcessAsUser -Path “$dirFiles\HighQ Drive Setup.exe” -Parameters “/quiet” -Wait

**Comment by That-Annoying-Guy** [comment]
Either **$dirFiles** is a location where regular users have no perms to read/execute.
Or 
**HighQ Drive Setup.exe** is trying to make changes to where Regular users have no perms.

Use ProcMon https://docs.microsoft.com/en-us/sysinternals/downloads/procmon to find out what is going on.

**Comment by sbf-** [comment]
Installing SW for users is a real pain... especially for removing it. Try to avoid it as much as possible.
Today, all modern setups should install for machine and install user settings when the application is launched or at logon.
I don't know this "HighQ Drive" application, but I'm almost sure it can be installed for machine.
When you install it as regular user, does the setup ask for elevation?

**Comment by Robert-LTH** [comment]
In AppDeployToolkitConfig.xml did you change <Toolkit_RequireAdmin>True</Toolkit_RequireAdmin> to <Toolkit_RequireAdmin>False</Toolkit_RequireAdmin> ?

**Comment by LuizHAP** [comment]
I have a script that I need to use with user login (modification of the C: \ Users folder, for example) and in the same script I need to install a program that needs administrator. Is there any way to change this information during the script?

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/execute-processasuser-admin-prompt-when-run-via-sccm/1136

**Comment by DennisVH** [comment]
Either chain 2 programs in SCCM, 1 running as system, 1 running as user 

or

Use 'install for System' in SCCM
Install the program using Execute-MSI / Execute-Process

to modify files for each profile directory you can use:
`[psobject[]]$UserProfiles = Get-UserProfiles`
`ForEach ($UserProfile in $UserProfiles)`
`{`
`    If(Test-Path -Path  "$($UserProfile.ProfilePath)")`
`    {`
`        #create new folder`
`        If(-not (Test-Path -Path "$($UserProfile.ProfilePath)\NewFolderPath"))`
`        {`
`            New-Folder_EY -Path  "$($UserProfile.ProfilePath)\NewFolderPath"`
`        }`
`        Copy-File ...`
`        Remove-File ...`
`        Remove-Folder ...`
`    }`
`    Else`
`    {`
`        Write-Log -Message "Profile Path [$($UserProfile.ProfilePath)] does not exist. Skip User Profile." -Severity 2`
`    }`
`}`

**Comment by mjr4077au** [comment]
Whatever was going on here, it wasn't a PSADT issue. `Execute-ProcessAsUser` is now `Start-ADTProcessAsUser` in v4 and it works fundamentally different, albeit achieving the desired outcome, and without any vbscript dependencies.
