### ISSUE TITLE
Use wildcard in execute-msi

### ISSUE THREAD

**Issue by dianneman** [PSAppDeployToolkit/PSAppDeployToolkit#372]
Execute-MSI -Action Install -Path "$dirFiles\Recast*.msi"

Does not accept wildcards. Will result in an error. Hopefully this will be supported in a new release.  I know, I can make it work with gci etc.

**Comment by dianneman** [comment]
That's correct, but can't use that in the suite I'm installing

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/use-wildcard-in-execute-msi/1128

**Comment by mjr4077au** [comment]
I'm sorry but we won't support this as it gives no reliable control over the installation order. You're best to set up your successive `Execute-MSI` calls (`Start-ADTMsiProcess` in v4) in the appropriate order for a guaranteed outcome.
