### ISSUE TITLE
Show-InstallationPrompt with -NoWait does not show in v3.7.0 when both Title and Message parameters are used

### ISSUE THREAD

**Issue by middletonk** [PSAppDeployToolkit/PSAppDeployToolkit#374]
Hey folks, thanks so much for the years of great work and support on PSADT! Got a weird one for you.

The following code works as expected in PSADT v3.7.0 in that an asynchronous popup is generated:
`Show-InstallationPrompt -Message "Software v18 has been successfully installed. Please reboot at your earliest convenience, and thank you!" -Icon Information -ButtonRightText "OK" -NoWait`

And here's nearly the same code, where both Title and Message are defined, but a popup is not generated:
`Show-InstallationPrompt -Title "Installation Complete" -Message "Software v18 has been successfully installed. Please reboot at your earliest convenience, and thank you!" -Icon Information -ButtonRightText "OK" -NoWait`

Details: This is being replicated reliably on a Windows 10 1607 device with PowerShell's AllSigned execution policy being enforced over group policy (and all PSADT core files signed). We also took a Windows 7 SP1 device, reduced the execution policy, and experienced the same oddity.

More details of the deployment script, which may be relevant (software and company names altered for sake of example):

[string]$appVendor = ''

[string]$appName = ''

[string]$appVersion = ''

[string]$installName = 'Company Software Deployment'

[string]$installTitle = 'Company Software Deployment'

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-installationprompt-with-nowait-does-not-show-in-v3-7-0-when-both-title-and-message-parameters-are-used/1129

**Comment by ericvanvoorthuizen** [comment]
When dotsourcing another PS script from PSADT-script  (e.g.     . C:\Scripts\Test.ps1) then function Show-InstallationPrompt in Test.ps1 does not show prompt at all when using parameter -NoWait. Removing the parameter -Title will not be a workaround in the case you really need the parameter -NoWait.

**Comment by ericvanvoorthuizen** [comment]
Function Show-InstallationPrompt does not show prompt at all when using parameter -NoWait and using a variable as or in the message parameter. Removing the parameter -Title will not be a workaround in the case you really need the parameter -NoWait i.c.m. using a variable as or in the Message parameter.
Will this behaviour also be fixed in next release?

**Comment by luki1412** [comment]
> Function Show-InstallationPrompt does not show prompt at all when using parameter -NoWait and using a variable as or in the message parameter. Removing the parameter -Title will not be a workaround in the case you really need the parameter -NoWait i.c.m. using a variable as or in the Message parameter.
> Will this behaviour also be fixed in next release?

Yes the function now works with the -NoWait parameter.
