### ISSUE TITLE
Install-MSUpdates et Test-MSUpdates

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#376]
I am installing KB917607 and then removing it manually.

1. Test-msupdates is not detecting it but using COM. With Com it detects the KB even if is remove. So I cannot reinstall it with Install-MSUpdates.

2. There are no way to remove the MSUpdates, with PSADTK. So, I am suggesting it should be improve.

Thanks,

**Comment by DennisVH** [comment]
similar issue as #277

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/install-msupdates-et-test-msupdates/1127

**Comment by FRacine** [comment]
Any news about that issue?

**Comment by FRacine** [comment]
Any news with that issue?
The issue happened on .Net Framework installation. Detecting if the KB is already present or not.

**Comment by luki1412** [comment]
Test-MSUpdates checks via Get-HotFix first and then through the COM object Microsoft.Update.Session.

Net Framework is a windows feature not an update. It gets updates but Net Framework itself isnt an update. You can use Get-WindowsOptionalFeature to check whether Net Framework is installed or check registry entries. On windows servers it's Get-WindowsFeature.

**Comment by fethiarras** [comment]
Hi, 

This link is not accessible : https://discourse.psappdeploytoolkit.com/t/install-msupdates-et-test-msupdates/1127

I've got the following screen : 
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/134372405/cc446fd2-0e03-4aaa-848a-93b8368a7bd5)

**Comment by mjr4077au** [comment]
Duplicate of #277.
