### ISSUE TITLE
-ShowInstallationRestartPrompt don't resume script after reboot

### ISSUE THREAD

**Issue by LuizHAP** [PSAppDeployToolkit/PSAppDeployToolkit#377]
Hello, when running the script below, after reboot, it does not continue to install the program as per the script. Introducing the error below.

```
[Asynchronous] :: Display restart prompt with a [60] second countdown.
[Asynchronous] :: Force restart the computer...
[Installation] :: Execution complete and the exit code [1073807364] is being ignored.
[Installation] :: Refresh the Desktop and the Windows Explorer environment process block.
```

```
Remove-MSIApplications -Name 'Check Point VPN' -ContinueOnError $True
cmd.exe /C netcfg -v –u ms_ndislwf
Show-InstallationRestartPrompt -Countdownseconds 30
Execute-MSI -Action Install -Path 'E80.84_CP_VPN.msi' -Parameters '/qn /norestart' -ContinueOnError $True
```

**Comment by Rolento76** [comment]
You won't be able to continue the script after a reboot. You can try stopping and starting processes/services in lieu of a reboot for your netcfg command. Or use a task sequence that can handle the reboot. Or if possible, save the reboot for the end of the script.

**Comment by LuizHAP** [comment]
> You won't be able to continue the script after a reboot. You can try stopping and starting processes/services in lieu of a reboot for your netcfg command. Or use a task sequence that can handle the reboot. Or if possible, save the reboot for the end of the script.

My problem is that after performing this command, I need to install a VPN program. Reboot is required from the installation.
I looked for other scripts and found the script that treats the reboot, but I could not include it along with the PSADT code

https://www.codeproject.com/Articles/223002/Reboot-and-Resume-PowerShell-Script

**Comment by DennisVH** [comment]
@LuizHAP, the link you refer to uses the HKLM:\SOFTWARE\Microsoft\CurrentVersion\Run key in the registry to launch the powershell script at logon.
This logic can also be used to launch the PSADT, but only if it does not require elevated rights as items in the Run key are executed as User without elevated rights.

As you need to install software which requires elevated rights I would suggest to create a scheduled task which runs as System, launches at logon and executes the PSADT.
`$TaskName = "$appName_$AppVersion"`

`$Service = New-Object -ComObject ("Schedule.Service")`
`$Service.Connect()`
`$rootFolder = $service.GetFolder("\")`
`$TaskDefinition = $service.NewTask(0)`

`$TaskDefinition.RegistrationInfo.Author = 'IT Services'`

`$TaskDefinition.Triggers.Create(9) #9=Logon Trigger`

`$TaskDefinition.Principal.RunLevel = (1) #1=HighestAvailable`

`$TaskDefinition.Settings.DisallowStartIfOnBatteries = $false`
`$TaskDefinition.Settings.StopIfGoingOnBatteries = $false`
`$TaskDefinition.Settings.AllowDemandStart = $true`
`$TaskDefinition.Settings.Hidden = $false`

`$TaskDefinitionAction = $TaskDefinition.Actions.Create(0)`
`$TaskDefinitionAction.Path = path to Deploy-Application.exe`
`$TaskDefinitionAction.Arguments = "-DeploymentType Install -DeployMode Silent -Step2"`

`$rootFolder.RegisterTaskDefinition("$Name", $TaskDefinition, 6, "SYSTEM", $null, 5) #Create Task which runs as System wether or not user is logged on`

I would also add an additional parameter to Deploy-Application.ps1 
`[parameter(Mandatory=$true)]`
`[int]$Step`

so you can split the logic you want to execute and remove the scheduled task
`If($Step -eq 1)`
`{`
`Remove-MSIApplications -Name 'Check Point VPN' -ContinueOnError $True`
`cmd.exe /C netcfg -v –u ms_ndislwf`
put here logic to create scheduled task (see above)
`Show-InstallationRestartPrompt -Countdownseconds 30`
`}`
`ElseIf($Step -eq 2)`
`{`
`Execute-MSI -Action Install -Path 'E80.84_CP_VPN.msi' -Parameters '/qn /norestart'`
`Try`
`{`
`$Service = New-Object -ComObject ("Schedule.Service")`
`$Service.Connect()`
`$rootFolder = $service.GetFolder("\")`
`$rootFolder.DeleteTask("$appName_$appVersion", 0)`
`Write-Log -Message "Removed scheduled task: $appNameInclSpaces $appVersion"`
`}`
`Catch`
`{`
`If ($_.Exception.InnerException.InnerException.HResult -eq '-2147024894')`
`{`
`Write-Log -Message 'Scheduled Task is already removed'`
`}`
`Else`
`{`
`Write-Log -Message "Failed to remove Scheduled Task: $($_.Exception.InnerException.InnerException.Message)"`
`}`
`}`
`}`

**Comment by That-Annoying-Guy** [comment]
Could it be related to issue #359?

**Comment by DennisVH** [comment]
@LuizHAP 
That is correct.
As you set Step as a mandatory parameter you need to pass this to Deploy-Application.exe:
Deploy-Application.exe -Step 1

You can work around passing the Step parameter to Deploy-Application.exe in the initial run by setting the default parameter value to 1
`[int]$Step=1`
Make sure you set parameter Step in TaskDefinitionAction.Arguments:
`$TaskDefinitionAction.Arguments = "-Step 2"`

@That-Annoying-Guy
This is not related to #359 
Just a question how to continue running script after a configured reboot in the script.

**Comment by LuizHAP** [comment]
> @LuizHAP
> That is correct.
> As you set Step as a mandatory parameter you need to pass this to Deploy-Application.exe:
> Deploy-Application.exe -Step 1
> 
> You can work around passing the Step parameter to Deploy-Application.exe in the initial run by setting the default parameter value to 1
> `[int]$Step=1`
> Make sure you set parameter Step in TaskDefinitionAction.Arguments:
> `$TaskDefinitionAction.Arguments = "-Step 2"`
> 
> @That-Annoying-Guy
> This is not related to #359
> Just a question how to continue running script after a configured reboot in the script.

This solved my problem. Thanks!
