### ISSUE TITLE
Get-ScheduledTask return value

### ISSUE THREAD

**Issue by powershellking** [PSAppDeployToolkit/PSAppDeployToolkit#381]
The Get-ScheduledTask function in the toolkit returns a pscustomobject on completion. It would be better to return an object of type  Microsoft.Management.Infrastructure.CimInstance#Root/Microsoft/Windows/TaskScheduler/MSFT_ScheduledTask or $null if there's an error as the Powershell-native function does, because with the pscustomobject yout can't work with the pipeline directly (for example pipe the results from get-scheduledtask to unregister-scheduledtask).

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/get-scheduledtask-return-value/1122

**Comment by DennisVH** [comment]
Root/Microsoft/Windows/TaskScheduler/MSFT_ScheduledTask is not available on Windows 7 and lower.
Please check #373 for workaround
