### ISSUE TITLE
Documentation Bug: Execute-MSI -SkipMSIAlreadyInstalledCheck

### ISSUE THREAD

**Issue by Nick-C** [PSAppDeployToolkit/PSAppDeployToolkit#382]
In the documentation -SkipMSIAlreadyInstalledCheck is shown as being a $true or $false parameter:

> -SkipMSIAlreadyInstalledCheck [<SwitchParameter>]
>         Skips the check to determine if the MSI is already installed on the system. Default is: $false.
>         
>         Required?                    false
>         Position?                    named
>         Default value                False
>         Accept pipeline input?       false
>         Accept wildcard characters?  false

However if you actually pass this as in this example:

`Execute-MSI -Action Install -Path 'AcroRead.msi' -Transform 'Settings.mst' -Parameters '/q /norestart' -SkipMSIAlreadyInstalledCheck $true`

The install script then appends True to the msiexec parameters which causes it to error:

> [Installation] :: Executing [C:\WINDOWS\system32\msiexec.exe /i "C:\WINDOWS\ccmcache\1n\Files\AcroRead.msi" TRANSFORMS="C:\WINDOWS\ccmcache\1n\Files\Settings.mst" TRANSFORMSSECURE=1 /q /norestart True /L*v "C:\WINDOWS\Logs\Software\AcroRead_Install.log"]...

Removing the $true parameter allows the install to progress successfully.

**Comment by SierraEcoBravo** [comment]
`Execute-MSI -Action Install -Path 'AcroRead.msi' -Transform 'Settings.mst' -Parameters '/q /norestart' -SkipMSIAlreadyInstalledCheck:$true`

would also work, as **-SkipMSIAlreadyInstalledCheck** is a switch ($true/$false), not a Boolean. The default value of a switch parameter is $false; having it set to $false in the parameter block is redundant. 

I agree that clarification that this is a switch in the documentation would be helpful.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/documentation-bug-execute-msi-skipmsialreadyinstalledcheck/1131

**Comment by luki1412** [comment]
In the latest documentation it is specified as SwitchParameter. It is true that they are not the same as Booleans  but they are similar. They have two values: present and notpresent. You can specify :$true and :$false after them to treat them like Booleans which is why we specify Default value as $false or $true for switches so it is more clear instead of just Present/Notpresent because someone could assume they can put the value "Present" after the switch to enable them.
