### ISSUE TITLE
Function Get-LoggedOnUser hangs if a deleted active directory user is still present in local admin group

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#383]
Hello guys !
To be able to get this error, the target computer should be a domain member.
1- Create a domain/AD user.
2- Add this user in the local "Administrators" group on your target computer.
3- Delete the domain user.
4- When looking at your "Administrators" group members, no more username, but a SID associated with a "?" icon.
5- Run PSADT. It should hang at Get-LoggedOnUser.

The cause : 
- Get-LoggedOnUser calls [PSADT.QueryUser]::GetUserSessionInfo
- The C# code hangs at line 573 which is : 
`localAdminGroupSidsList.Add((new NTAccount(member.Name)).Translate(typeof(SecurityIdentifier)).Value);`
and the part of the line that hangs is the Translate();

**Comment by Sulquendi** [comment]
Proposed fix in AppDeployToolkit.cs : 
After : 
`string localAdminGroupName = new SecurityIdentifier("S-1-5-32-544").Translate(typeof(NTAccount)).Value.Split('\\')[1];`
Add:
`string validSidPattern = @"^S-\d-\d+-(\d+-){1,14}\d+$";`

Replace:
`localAdminGroupSidsList.Add((new NTAccount(member.Name)).Translate(typeof(SecurityIdentifier)).Value);`

By:
```
if (Regex.IsMatch(member.Name, validSidPattern))
						{
							localAdminGroupSidsList.Add(member.Name);
						} else {
							localAdminGroupSidsList.Add((new NTAccount(member.Name)).Translate(typeof(SecurityIdentifier)).Value);
						}
```

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/function-get-loggedonuser-hangs-if-a-deleted-active-directory-user-is-still-present-in-local-admin-group/1120

**Comment by sintaxasn** [comment]
v

**Comment by DennisVH** [comment]
@Sulquendi thanks for providing a solution.
This will be fixed in the next release.

**Comment by luki1412** [comment]
Fixed.
