### ISSUE TITLE
Set-pinAppliction on Windows 10

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#384]
Is it me or the result is different on Windows 8.1 and Windows 10? I have a script a on Windows 8.1 the shortcut are appearing as pin on taskbar but not on Windows 10.

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/set-pinappliction-on-windows-10/1123

**Comment by sintaxasn** [comment]
Accidentally closed while testing a Discourse forum sync. Apologies!

**Comment by FRacine** [comment]
HI,

Why "wont fix"? May I get a little more informations?

**Comment by DennisVH** [comment]
@FRacine sorry, I forgot to click the comment button:
Microsoft does not want to provide a method to add/remove pin items to the taskbar on Windows 10.
Therefore Microsoft removed the "pin to taskbar" item from the Verbs collection to programatically add/remove items to the taskbar on Windows 10. The option is still available interactively on the user interface.

There is a 3rd party utility syspin from technosys which is a closed source standalone exe that apparently works.

After some further research I did find references how to do it in C#. I'll look into it if I can get it to work in the toolkit.

**Comment by FRacine** [comment]
I agree.

**Comment by harmar1** [comment]
Hi Team,

not sure if this might be helpful:

http://alexweinberger.com/main/pinning-network-program-taskbar-programmatically-windows-10/

https://social.msdn.microsoft.com/Forums/en-US/c2d71ce0-9c92-434c-a0c3-b019db83b775/pin-application-to-taskbar-in-win-10-programmatically-c?forum=csharpgeneral

**Comment by DennisVH** [comment]
This will be fixed in the next release

**Comment by finitenamespace** [comment]
Am I the only one still having this issue? Running version 3.7.0, and I've even tried the "try placing it in your Start Menu first" workaround. No dice.

```
[07-19-2019 15:27:41.723] [Installation] [Invoke-Verb] :: Performing action [Pin to taskbar] is not programmatically supported for this file [C:\Users\Userspace\AppData\Roaming\Microsoft\Windows\Start Me
nu\Programs\notepad.exe - Shortcut.lnk].
```

**Comment by mjr4077au** [comment]
Duplicate of #339.

**Comment by InteXX** [comment]
@DennisVH 

> After some further research I did find references how to do it in C#

I know it's been five years, seven months and three weeks since you posted, but you wouldn't happen to still have those references, would you?
