### ISSUE TITLE
Remove-RegistryKey not working for users that are not logged in

### ISSUE THREAD

**Issue by SweetMusic4no1** [PSAppDeployToolkit/PSAppDeployToolkit#386]
```
[scriptblock]$HKCURegistrySettings = {
    Write-Log -Message "SID = $($UserProfile.SID)"
    Remove-RegistryKey -Key "HKEY_CURRENT_USER\Software\Classes\.ext" -SID $UserProfile.SID
    Remove-RegistryKey -Key "HKEY_CURRENT_USER\Software\Classes\PID" -SID $UserProfile.SID -Recurse
    Remove-Folder -Path "$($UserProfile.ProfilePath)\$idirName"        
}
```
This is my code. It only removes the registry keys for users that are logged in. I tried HKCU:\ as well, same result.
Remove-Folder is working correctly for everyone.

**Comment by SweetMusic4no1** [comment]
It ignores the system account, ofcourse.... it won't be very wise to remove anything from there :)
I am not using set-strictmode and the script runs as system.
It seems to me that the problem is specifically with the Classes subkey...

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/remove-registrykey-not-working-for-users-that-are-not-logged-in/1119

**Comment by sintaxasn** [comment]
Accidentally closed

**Comment by bshiznit** [comment]
> 
> 
> It ignores the system account, ofcourse.... it won't be very wise to remove anything from there :)
> I am not using set-strictmode and the script runs as system.
> It seems to me that the problem is specifically with the Classes subkey...

How are you invoking the code in the script block? How you invoke it determines what profiles are affected (from the help):
[scriptblock]$HKCURegistrySettings = {
    
    Set-RegistryKey -Key 'HKCU\Software\Microsoft\Office\14.0\Common' -Name 'qmenable' -Value 0 -Type DWord -SID $UserProfile.SID
	Set-RegistryKey -Key 'HKCU\Software\Microsoft\Office\14.0\Common' -Name 'updatereliabilitydata' -Value 1 -Type DWord -SID $UserProfile.SID
}
Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $HKCURegistrySettings

OR:
Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $HKCURegistrySettings -UserProfiles (Get-UserProfiles -ExcludeSystemProfiles $true)

**Comment by mjr4077au** [comment]
OP not responded to last question asked. Further to this, the registry code has been tested and confirmed working in prep for v4 preview. If this is still an ongoing issue, please raise the issue again so it can be re-reviewed against v4.
