### ISSUE TITLE
Compiling AppDeployToolkitMain.cs to AppDeployToolkitMain.dll

### ISSUE THREAD

**Issue by enternoescape** [PSAppDeployToolkit/PSAppDeployToolkit#387]
I ran into a problem with privilege management software that my company uses after installing the August rollups for Windows 10 1709. The issue is that when csc.exe runs elevated by the privilege management software, it will throw an exception. If the user is a local admin, this will not happen since elevation was handled directly by the OS.

My workaround is to compile AppDeployToolkitMain.cs to a dll and make the appropriate change to AppDeployToolkitMain.ps1. This is working very well and gets around the run-time compiling issue. Also, before anyone asks, we have reached out to the vendor, but their progress on this issue has been very slow.

I can't think of any reason why this might cause problems since we use a fairly standardized Windows 10 environment, but I just wanted to know if there is a reason other than convenience as to why we don't precompile this library? .Net version compatibility is the only thing that comes to mind.

I was going to ask about this in the forums, but this is more of a dev question and I don't want to log in with a social media account (which appears to be the only option).

**Comment by sintaxasn** [comment]
Hey there,

My guess would be an integrity level mismatch between your elevated application and some component on the .NET framework (such as csc.exe). Chances are you elevate with High Integrity for the toolkit (say, Deploy-Application.exe) but have a .NET process rule in your privilege management software that is dropping to medium integrity. 

.NET version compatibility is really the main reason - we still support Win 7 and .NET 2.0. The next release we'll be aiming for a much higher version.

Re forums - I've just finished a migration to Discourse. You can sign up without a social media account.

Dan

**Comment by enternoescape** [comment]
@sintaxasn Thanks for the insight.
