### ISSUE TITLE
Path not exist, errorcode 60001, erroraction not working

### ISSUE THREAD

**Issue by pilgi3** [PSAppDeployToolkit/PSAppDeployToolkit#389]
I'am looking for a registry value and if the value not exist i get the error code 60001 even when i add the property -ErrorAction Continue.
The script exists with an error message.
When i try the same in the powershell ise, it works.

I know it could be that the value not exist, and the script should go on.
How can i prevent this process?

My test script:
$versionCheck = Get-ItemPropertyValue -Path HKLM:\SOFTWARE\WOW6432Node\TeamViewer -Name Version -ErrorAction Continue

if ($versionCheck -match "H")
{
    Write-Host "Host"
} else {

    Write-Host "full"
}

**Comment by bshiznit** [comment]
Hi there - you should use the internal toolkit function Get-RegistryKey and specify a -Value for that:
Get-RegistryKey -Key HKLM:\SOFTWARE\WOW6432Node\TeamViewer -ContinueOnError $true -Value Version

You should refer to PSAppDeploymentToolkitAdminGuide.docx for items like this, or "run" the AppDeployToolkitMain.ps1 in the ISE to get the Command pane populated with the PSADT functions (you'll need to hit refresh)...

**Comment by pilgi3** [comment]
Hi, thank you for your help. I forgot the built-in function :( . Now it works!
