### ISSUE TITLE
test-msupdates

### ISSUE THREAD

**Issue by dilorenzo1987** [PSAppDeployToolkit/PSAppDeployToolkit#39]
## Check using Update method (to catch Office updates)
		[__comobject]$Session = New-Object -ComObject Microsoft.Update.Session
		[__comobject]$Collection = New-Object -ComObject Microsoft.Update.UpdateColl
		[__comobject]$Installer = $Session.CreateUpdateInstaller()
		[__comobject]$Searcher = $Session.CreateUpdateSearcher()
		[int32]$updateCount = $Searcher.GetTotalHistoryCount()
		If ($updateCount -gt 0) {
			$Searcher.QueryHistory(0, $updateCount) | Where-Object { $_.Title -match $kbNumber } | ForEach-Object { $kbFound = $true }
		}

Also returns true for Updates which were installed once but uninstalled meanwhile (History).

Can you fix that? I did it meanwhile by removing this code snippet.

Regards,
Fabio

**Comment by mmashwani** [comment]
I just pushed a change to the latest 3.6.5 beta to try and fix this issue. Can you test it and let me know if it's working as expected?

Beta found here (make sure to download all files):
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit
