### ISSUE TITLE
Support for Reinstall (SCCM 1810)

### ISSUE THREAD

**Issue by My-userid** [PSAppDeployToolkit/PSAppDeployToolkit#390]
Would be nice with support of a "reinstall" parameter to support the new function in SCCM 1810.

"Specify a repair command line for Windows Installer and Script Installer deployment types. Then if you enable the option on the deployment, a new button is available in Software Center to Repair the application. When you configure an application with a repair program, users can start the command from Software Center."

**Comment by charltonstanley** [comment]
+1 yes please!

**Comment by khaffner** [comment]
#369 like this?

**Comment by My-userid** [comment]
Yeah :)

**Comment by charltonstanley** [comment]
Found a workaround for this. Insert this code in the `Repair Program:` field: `cmd.exe /c Deploy-Application.exe Uninstall && Deploy-Application.exe Install`

**Comment by g4m3c4ck** [comment]
I have written working code for this. Execute-MSI in the main script already had code to execute a repair. 
The rest was easy to write.

I posted it here https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/368 and here https://discourse.psappdeploytoolkit.com/t/add-repair-feature-of-configmgr-1810/1453

**Comment by paulwetter** [comment]
A Repair feature was just added in 3.8.1 to match the CM Application model Repair.  So, I would say that this issue can be closed.

**Comment by luki1412** [comment]
#458
