### ISSUE TITLE
Get-loggedonuser does not resolve IsLocalAdmin correctly when local group contains sid accounts

### ISSUE THREAD

**Issue by dianneman** [PSAppDeployToolkit/PSAppDeployToolkit#392]
In my test environment the Get-LoggedOnUser resolves "IsLocalAdmin" to false when the local administrator groups contains sid accounts. Probably accounts that don't exist anymore but still have a reference to the group. If this is the case the IsLocalAdmin resolves always to false even if you have local administrative permissions. 
If you remove the unknown sid account the get-loggedonuser function resolves the actual value of true. 
Maybe a little error handling should be enough to make this always validate the right value.

![accounts](https://user-images.githubusercontent.com/39791149/49947533-c7f38980-fef1-11e8-9196-7a381dbbc108.png)

**Comment by DennisVH** [comment]
Same as #383
