### ISSUE TITLE
Get-InstalledApplication dont work correctly with localized program version

### ISSUE THREAD

**Issue by jin-2018** [PSAppDeployToolkit/PSAppDeployToolkit#393]
I have Russion version of Windows, Office, Visio, etc.

`PS D:\UninstallAllVisio\AppDeployToolkit> Import-Module .\AppDeployToolkitMain.ps1
PS D:\UninstallAllVisio\AppDeployToolkit> (Get-InstalledApplication -Name "Microsoft Visio").DisplayName`
Microsoft Visio  2016
Microsoft Visio Professional 2016
Microsoft Visio MUI (Russian) 2016

But in registry I have this:
Microsoft Visio профессиональный 2016
Microsoft Visio Professional 2016
Microsoft Visio MUI (Russian) 2016

I think problem in this part of function:
` ## Remove any control characters which may interfere with logging and creating file path names from these variables

$appDisplayName = $regKeyApp.DisplayName -replace '[^\u001F-\u007F]',''
$appDisplayVersion = $regKeyApp.DisplayVersion -replace '[^\u001F-\u007F]',''
$appPublisher = $regKeyApp.Publisher -replace '[^\u001F-\u007F]',''`

**Comment by jin-2018** [comment]
May be replace on this code?

## Remove any control characters which may interfere with logging and creating file path names from these variables
$appDisplayName = $regKeyApp.DisplayName -replace '[^\p{L}\p{Nd} .]', ''
$appDisplayVersion = $regKeyApp.DisplayVersion -replace '[^\p{L}\p{Nd}] .', ''
$appPublisher = $regKeyApp.Publisher -replace '[^\p{L}\p{Nd} .]', ''

**Comment by DennisVH** [comment]
This will be fixed in the next release

**Comment by jin-2018** [comment]
Thank you.
I see this in comment: "the creation of file name is only used in Execute-MSI function and the logic there already replaces invalid filename characters".
But i used Get-InstalledApplication in my Deploy-Application.ps1.
Will there be problem with control character in the future?

**Comment by DennisVH** [comment]
@jin-2018 
I removed -replace '[^\u001F-\u007F]',''`
$appDisplayName = $regKeyApp.DisplayName 
$appDisplayVersion = $regKeyApp.DisplayVersion 
$appPublisher = $regKeyApp.Publisher

As appDisplayName, appDisplayVersion and appPublisher values are only used for logging in Execute-MSI (triggered by Remove-MSIApplications) and Execute-MSI has logic to remove invalid filename characters, the -replace '[^\u001F-\u007F]',''` was obsolete in Get-InstalledApplication

**Comment by jin-2018** [comment]
Thank you. I understood.

**Comment by luki1412** [comment]
Get-InstalledApplication only removes invalid filename characters now. Fixed.
