### ISSUE TITLE
executeasuser.vbs naming

### ISSUE THREAD

**Issue by tda90** [PSAppDeployToolkit/PSAppDeployToolkit#398]
Hello Everyone,
I've a little problem with the generated "PSAPPDEPLOYTOOLKIT-EXECUTEASUSER.vbs" file.
Sine we're implementing AppBlocker I will have to sign or to whitelist trough hash.

Now we have a couple of applications which need the executeasuser.vbs.
I've seen that the name of this VBS is always the same (and it's hardcoded in the AppDeployToolkitMain.ps1).

Now my question is... what happen if you have 2 application which need executeasuser.vbs?
Since the executeasuser.vbs has always the same name and is always in the same location? (C:\Users\PUBLIC\PSAPPDEPLOYTOOLKIT\PSAPPDEPLOYTOOLKIT-EXECUTEASUSER.VBS) ?

Thank you for helping.
Regards

**Comment by luki1412** [comment]
Execute-ProcessAsUser is used for executing an application in another user's context. That is why it creates a new vbs file on every execution. However it keeps overwriting the same file. After task scheduler runs the process and gets an exit code, the task gets deleted. The file stays there. It should be cleaned up.

**Comment by seanlillis** [comment]
Closing as an answered question.
