### ISSUE TITLE
Cannot use $dirFiles in declare variables section

### ISSUE THREAD

**Issue by pilgi3** [PSAppDeployToolkit/PSAppDeployToolkit#402]
I want to fill in the $appVersion with an script, but it looks like the $dirFiles not define.

`##*===============================================
	## Variables: Application
	[string]$appVendor = 'xxx'
	[string]$appName = 'xxx'
    [string]$appVersion = Get-ChildItem -Path "$dirFiles\*" -Include *.exe | ForEach-Object {[System.Diagnostics.FileVersionInfo]::GetVersionInfo($_).FileVersion}
	[string]$appArch = 'x64'
	[string]$appLang = 'MUI'
	[string]$appRevision = '01'
	[string]$appScriptVersion = '1.0.0'
##*===============================================`

`$test =  Get-ChildItem -Path "$dirFiles\*" -Include *.exe | ForEach-Object {[System.Diagnostics.FileVersionInfo]::GetVersionInfo($_).FileVersion}
Write-Log -Message "$test"`

I see the version in the Logfile. But in the declare section the $appVersion is empty.
Can i do this in other ways?
Define a static path is not possible, because sccm cache folder names are random.

**Comment by cyborgrd** [comment]
The Variable $dirFiles is declared in the Main
You can use it only after the part where the main is loaded

**Comment by cyborgrd** [comment]
After this part


	## Dot source the required App Deploy Toolkit Functions
	Try {
		[string]$moduleAppDeployToolkitMain = "$scriptDirectory\AppDeployToolkit\AppDeployToolkitMain.ps1"
		If (-not (Test-Path -LiteralPath $moduleAppDeployToolkitMain -PathType 'Leaf')) { Throw "Module does not exist at the specified location [$moduleAppDeployToolkitMain]." }
		If ($DisableLogging) { . $moduleAppDeployToolkitMain -DisableLogging } Else { . $moduleAppDeployToolkitMain }
	}
	Catch {
		If ($mainExitCode -eq 0){ [int32]$mainExitCode = 60008 }
		Write-Error -Message "Module [$moduleAppDeployToolkitMain] failed to load: `n$($_.Exception.Message)`n `n$($_.InvocationInfo.PositionMessage)" -ErrorAction 'Continue'
		## Exit the script, returning the exit code to SCCM
		If (Test-Path -LiteralPath 'variable:HostInvocation') { $script:ExitCode = $mainExitCode; Exit } Else { Exit $mainExitCode }
	}

**Comment by pilgi3** [comment]
Ok i understand.
I tried a different way and this works:
`[string]$appVersion = Get-ChildItem -Path "$PSSCriptRoot\Files\*" -Include *.exe | ForEach-Object { [System.Diagnostics.FileVersionInfo]::GetVersionInfo($_).FileVersion }`
