### ISSUE TITLE
$dirFiles and $dirSupportFiles path different

### ISSUE THREAD

**Issue by pilgi3** [PSAppDeployToolkit/PSAppDeployToolkit#403]
When i modify the Deploy-Application.ps1 in the PowerShell ISE the $dirFiles and $dirSuppportFiles are "wrong".

`PS C:\Windows\ccmcache\1r> $dirfiles
C:\Windows\ccmcache\1r\AppDeployToolkit\Files`

But the folder looks like:
![2019-04-09 07_00_34-1r](https://user-images.githubusercontent.com/44865075/55774395-3f4abb80-5a95-11e9-873c-e1e5879ec74a.jpg)

If i move the to folder to "AppDeployToolkit" and run the exe, the script fails, cannot find $dirFiles.

> The path "C:\Windows\ccmcache\1r\Files" cannot be found.

For testing we has to define $dirFiles and $dirSupportFiles seperatly in PowerShell ISE.

Is this a bug or normal?

**Comment by Nabsku** [comment]
Hi,

I think I know what your issue is. 

Are you redefining the script directories after dot-sourcing the AppDeployToolkitMain.ps1? When dot-sourcing the toolkit, it sets these three variables:

```
[string]$dirFiles = Join-Path -Path $scriptParentPath -ChildPath 'Files'
[string]$dirSupportFiles = Join-Path -Path $scriptParentPath -ChildPath 'SupportFiles'
```

What you can do is:

1.  Change the abovementioned variables or
2. Set the variables yourself after dot-sourcing the toolkit

Let me know if that fixes your issue. :)

**Comment by pilgi3** [comment]
No, we don't modify the AppDeployToolkitMain.ps1
When i create a new Application i will do this:

- Open PowerShell ISE as Admin
- Change to work directory like "c:\install\AppName"
The folder looks exactly the same as the picture above.
- Import-Module -Path .\AppDeployToolkit\AppDeployToolkitMain.ps1
We import the module, cause the commands.

Check $dir and $scriptParentPath
`PS C:\install\test> $dirfiles
C:\install\test\AppDeployToolkit\Files`

`PS C:\install\test> $scriptParentPath
C:\install\test\AppDeployToolkit`

Because the Import-Module sets the $scriptParentPath "wrong" or why is there "AppDeployToolkit" in the path?

Do answer your second question, if i set them manually the path is correct.

**Comment by Nabsku** [comment]
Hi,

as written above, the AppDeployToolkitMain.ps1 file, when sourced, instanciates a few variables. You're accessing two of those ($dirFiles and $scriptParentPath). So, what the Toolkit is doing isn't "right or wrong", it's just doing what it is told to do. 


Here's how $scriptParentPath is set:
```
If ($invokingScript) {
	#  If this script was invoked by another script
	[string]$scriptParentPath = Split-Path -Path $invokingScript -Parent
}
Else {
	#  If this script was not invoked by another script, fall back to the directory one level above this script
	[string]$scriptParentPath = (Get-Item -LiteralPath $scriptRoot).Parent.FullName
}
```
$dirFiles is set like this:

`[string]$dirFiles = Join-Path -Path $scriptParentPath -ChildPath 'Files'`

If you want set those two variables yourself, either change the way they're assigned in the Toolkit or change them in your Deploy-Application.ps1 (after the Main.ps1 is sourced).

**Comment by pilgi3** [comment]
OK thank you. I will set the variables myself in PowerShell ISE.
