### ISSUE TITLE
Execute-Process -MsiExecWaitTime parameter passes ticks instead of seconds

### ISSUE THREAD

**Issue by einbahn** [PSAppDeployToolkit/PSAppDeployToolkit#406]
When you pass an integer value to -MsiExecWaitTime, the value is converted to a timespan object of 300 ticks, which is 0.03 Milliseconds, not the desired timespan of 5 minutes

The function works correctly if you don't supply a value to MsiExecWaitTime, since the default parameter value is the result of the new-timespan cmdlet which works correctly.  
![msiexecwaittime](https://user-images.githubusercontent.com/20565012/57414074-b1154280-71c4-11e9-8c58-c29d1c657052.PNG)

**Comment by luki1412** [comment]
#415 fixes this issue

**Comment by luki1412** [comment]
This was fixed.
