### ISSUE TITLE
3.7.0 ForceCloseAppsCountdown or CloseApps unable to close app when run

### ISSUE THREAD

**Issue by sylhous** [PSAppDeployToolkit/PSAppDeployToolkit#408]
Hello,
I use SCCM for installations.
We noticed that open applications do not close (even if there is no user on the computer).
I use the latest version.
We put 5 munites and at the end here is the log :
Thanks for your help,

[Pre-Installation] :: Close applications countdown has [300] seconds remaining.	Show-WelcomePrompt	2019-05-10 12:49:29	9112 (0x2398)
[Pre-Installation] :: Countdown has [300] seconds remaining.	Show-WelcomePrompt	2019-05-10 12:49:29	9112 (0x2398)
[Pre-Installation] :: The running processes have changed. Updating the apps to close: [Internet Explorer]...	Show-WelcomePrompt	2019-05-10 12:49:32	9112 (0x2398)
[Pre-Installation] :: Countdown timer has elapsed. Force continue.	Show-WelcomePrompt	2019-05-10 12:54:30	9112 (0x2398)
[Pre-Installation] :: User selected to continue...	Show-InstallationWelcome	2019-05-10 12:54:30	9112 (0x2398)
[Pre-Installation] :: Check for running application(s) [PuTTY,IEXPLORE]...	Get-RunningProcesses	2019-05-10 12:54:32	9112 (0x2398)
[Pre-Installation] :: The following processes are running: [iexplore].	Get-RunningProcesses	2019-05-10 12:54:32	9112 (0x2398)
[Pre-Installation] :: Resolve process descriptions...	Get-RunningProcesses	2019-05-10 12:54:32	9112 (0x2398)
[Pre-Installation] :: Prompt user to close application(s) [Internet Explorer]...	Show-WelcomePrompt	2019-05-10 12:54:32	9112 (0x2398)
[Pre-Installation] :: Countdown has [0] seconds remaining.	Show-WelcomePrompt	2019-05-10 12:54:32	9112 (0x2398)
[Pre-Installation] :: Countdown timer has elapsed. Force continue.	Show-WelcomePrompt	2019-05-10 12:54:32	9112 (0x2398)
[Pre-Installation] :: User selected to continue...	Show-InstallationWelcome	2019-05-10 12:54:32	9112 (0x2398)
[Pre-Installation] :: Check for running application(s) [PuTTY,IEXPLORE]...	Get-RunningProcesses	2019-05-10 12:54:34	9112 (0x2398)
[Pre-Installation] :: The following processes are running: [iexplore].	Get-RunningProcesses	2019-05-10 12:54:34	9112 (0x2398)
[Pre-Installation] :: Resolve process descriptions...	Get-RunningProcesses	2019-05-10 12:54:34	9112 (0x2398)
[Pre-Installation] :: Prompt user to close application(s) [Internet Explorer]...	Show-WelcomePrompt	2019-05-10 12:54:34	9112 (0x2398)
[Pre-Installation] :: Countdown has [0] seconds remaining.	Show-WelcomePrompt	2019-05-10 12:54:34	9112 (0x2398)
[Pre-Installation] :: Countdown timer has elapsed. Force continue.	Show-WelcomePrompt	2019-05-10 12:54:34	9112 (0x2398)
[Pre-Installation] :: User selected to continue...	Show-InstallationWelcome	2019-05-10 12:54:34	9112 (0x2398)
[Pre-Installation] :: Check for running application(s) [PuTTY,IEXPLORE]...	Get-RunningProcesses	2019-05-10 12:54:36	9112 (0x2398)
[Pre-Installation] :: The following processes are running: [iexplore].	Get-RunningProcesses	2019-05-10 12:54:36	9112 (0x2398)
[Pre-Installation] :: Resolve process descriptions...	Get-RunningProcesses	2019-05-10 12:54:36	9112 (0x2398)
[Pre-Installation] :: Prompt user to close application(s) [Internet Explorer]...	Show-WelcomePrompt	2019-05-10 12:54:36	9112 (0x2398)
[Pre-Installation] :: Countdown has [0] seconds remaining.	Show-WelcomePrompt	2019-05-10 12:54:36	9112 (0x2398)
[Pre-Installation] :: Countdown timer has elapsed. Force continue.	Show-WelcomePrompt	2019-05-10 12:54:36	9112 (0x2398)
[Pre-Installation] :: User selected to continue...	Show-InstallationWelcome	2019-05-10 12:54:36	9112 (0x2398)
[Pre-Installation] :: Check for running application(s) [PuTTY,IEXPLORE]...	Get-RunningProcesses	2019-05-10 12:54:38	9112 (0x2398)
[Pre-Installation] :: The following processes are running: [iexplore].	Get-RunningProcesses	2019-05-10 12:54:38	9112 (0x2398)
[Pre-Installation] :: Resolve process descriptions...	Get-RunningProcesses	2019-05-10 12:54:38	9112 (0x2398)
[Pre-Installation] :: Prompt user to close application(s) [Internet Explorer]...	Show-WelcomePrompt	2019-05-10 12:54:38	9112 (0x2398)

**Comment by pchatham** [comment]
Can you paste in your pre-installation code?
This may help anyone identify the issue
