### ISSUE TITLE
Get-FileVersion - gets Product version not File version

### ISSUE THREAD

**Issue by djkranky** [PSAppDeployToolkit/PSAppDeployToolkit#409]
The "Get-FileVersion" function gets the "Product version" not the "File version".  The Product version and File version are not always the same.

**Comment by luki1412** [comment]
No it returns file version. Tested it and checked the code. Sometimes it doesn't include the private part of version however it returns the correct version.

**Comment by JonathanPitre** [comment]
@djkranky is right it returns the product version, not the file version. It would be nice to add an argument to chose between these two options.

**Comment by luki1412** [comment]
[TestApp.zip](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/3978731/TestApp.zip)

Here I uploaded a test app I just made. Test the command on it. If you run the exe, it will tell you its product and file version, or you can just look in the properties. The file version is 1.1.1.1 and the command correctly displays that. The product version is 3.3.3.3

The command displays the correct version.

**Comment by djkranky** [comment]
I tested with that TestApp.exe you provided, and yes "Get-FileVersion" reports that File Version correctly.  I just tested though with a file in the Win 7, system32 folder and that one is showing the Product Version, not the File Version.  See attached screenshots.

![image](https://user-images.githubusercontent.com/50680772/71125525-b734be00-21ac-11ea-8a50-ab3b71d83634.png)

![image](https://user-images.githubusercontent.com/50680772/71125539-bf8cf900-21ac-11ea-9c2f-0b07e0d59ce0.png)

**Comment by luki1412** [comment]
Based on multiple threads like these: https://stackoverflow.com/questions/5460199/fileversioninfo-fileversion-returns-productversion

It seems like Windows Explorer doesn't always show the right version.

And as I have said, we are using: .FileVersionInfo.FileVersion
Its a property named FileVersion from Net Framework, not some random function that gets that info.

However I think there is no reason to not add Product version for this command as a parameter, in case anyone needs it.

**Comment by JonathanPitre** [comment]
Here's an example where the file version can't be reported properly. I'm guessing this could be caused by extra spaces.

![image](https://user-images.githubusercontent.com/15003329/71424867-76352180-2664-11ea-8e1a-477ae192d7fc.png)

![image](https://user-images.githubusercontent.com/15003329/71424869-7a613f00-2664-11ea-8793-29752a15c656.png)

**Comment by luki1412** [comment]
That would be this part: 
```
## Remove product information to leave only the file version
$fileVersion = ($fileVersion -split ' ' | Select-Object -First 1)
```
Don't know why this was added. The scripter should handle the version him/herself.

**Comment by luki1412** [comment]
The function Get-FileVersion was modified to allow returning of both File and Product versions and the return value is no longer truncated. Windows Explorer isn't always returning the expected version however that is not a bug in the toolkit.
