### ISSUE TITLE
Display correct wording in Show-InstallationWelcome during Uninstall

### ISSUE THREAD

**Issue by muecom** [PSAppDeployToolkit/PSAppDeployToolkit#41]
When Show-InstallationWelcome is used during DeploymentType = 'Uninstall', all default texts show '...install...' / '...Installation...'.
It would be very nice if additional default text would be added to the xml and the cmdlet switches the text dependent of the DeploymentType

**Comment by mmashwani** [comment]
Show-InstallationWelcome was really only designed to be used for installs, not other deployment types.

**Comment by luphisto** [comment]
I would appreciate to see thes feature to. In many cases it is necessary to do NOT a silent uninstall deplyoment. And if you plan to give the user the chance to close his open programs or allow the use of deferrals on an uninstall deployment, you will need the Show-InstallationWelcome cmdlet. It is confusing for the user as they think a program would be installed instead of removed.

**Comment by mcroach** [comment]
I came here today to submit the same feature request as it is confusing to our users and we need to prompt them to close applications prior to commencing with the uninstall.

**Comment by bshiznit** [comment]
I will submit a proper PR time permitting - in the meantime we are working around this by doing a find/replace on the variables that hold the label box text:
`[string]$installPhase = 'Pre-Uninstallation'
		
		## Show Welcome Message, close Internet Explorer with a 60 second countdown before automatically closing
        $configDeferPromptExpiryMessage = $configDeferPromptExpiryMessage.Replace('installation', 'uninstallation')
        $configClosePromptMessage = $configClosePromptMessage.Replace('installation', 'uninstallation')
        $configDiskSpaceMessage = $configDiskSpaceMessage.Replace('installation', 'uninstallation')
        $configRestartPromptMessage = $configRestartPromptMessage.Replace('installation', 'uninstallation')
        $configBlockExecutionMessage = $configBlockExecutionMessage.Replace('installation', 'uninstallation')
        $configDeferPromptWelcomeMessage = $configDeferPromptWelcomeMessage.Replace('installed', 'uninstalled')`

**Comment by davelee212** [comment]
Just started using PSADT and have the same frustration.  Minor as it seems, it will confuse users.  I'm going to look into using bshiznet's workaround for the moment.

**Comment by ll4mat** [comment]
The same here. Would also appreciate it if the wording was correct.

**Comment by FPyC639** [comment]
Is this  issue still open? I would like to work on it.

**Comment by mjr4077au** [comment]
We'll have this addressed for the v4.0 preview, I'd rather not take in anything non-critical for now as all that code has been heavily rewritten already.

**Comment by mjr4077au** [comment]
This has been (finally) addressed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/d35b9663345389f3529c659dd0b731a3505315e1 and https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/b4778e8e02206b040e0b06d5cefd03802f7eae7f. Appreciate everyone's patience. These changes will make it into 4.1.0.

**Comment by phunkysc** [comment]
Missed this ticket. This is good news! Apologies for raising the BUG.
