### ISSUE TITLE
Persistinterval conflicting documentation/ default value

### ISSUE THREAD

**Issue by Jeroen-J-Bakker** [PSAppDeployToolkit/PSAppDeployToolkit#411]
The information in the parameter description for various cmdlets states for persistprompt (a.o. show-installationprompt) that the prompt is reset to center screen every 10 seconds.

_.PARAMETER PersistPrompt
	Specify whether to make the prompt persist in the center of the screen every 10 seconds. The user will have no option but to respond to the prompt - resistance is futile!_

But in the AppDeployToolkitConfig.xml the parameter is defaulted to 60 seconds.

		<InstallationPrompt_PersistInterval>60</InstallationPrompt_PersistInterval>

**Comment by luki1412** [comment]
#420 Fixes it.

**Comment by luki1412** [comment]
Fixed.
