### ISSUE TITLE
Show-InstallationRestartPrompt only allows a maximum of 24 hours.

### ISSUE THREAD

**Issue by megaman2isthebest** [PSAppDeployToolkit/PSAppDeployToolkit#412]
Hi Folks,

I am unable to get the Show-InstallationRestartPrompt to exceed past 24 hours. Here is my command 4 days:

Show-InstallationRestartPrompt -Countdownseconds 345600

If I put this in, the countdown will remain at 24 hours. Is this a bug or is there another way to increase this?

**Comment by adipiciu** [comment]
It's a display only bug.

If you want to display it correctly, you need to modify 2 lines of code. This line appears 2 times in AppDeployToolkitMain.ps1

`$labelCountdown.Text = [string]::Format('{0}:{1:d2}:{2:d2}', $remainingTime.Hours, $remainingTime.Minutes, $remainingTime.Seconds)`
modify to
`$labelCountdown.Text = [string]::Format('{0}:{1:d2}:{2:d2}', $remainingTime.Days * 24 + $remainingTime.Hours, $remainingTime.Minutes, $remainingTime.Seconds)`

**Comment by luki1412** [comment]
Added a pull request for the fix by adipiciu.

#418

**Comment by adipiciu** [comment]
The line appears 2 times in AppDeployToolkitMain.ps1
So it should be replaced in both locations. It was replaced only in one place.

**Comment by luki1412** [comment]
It actually appears 4 times in the script. Added a pull request for the other 3.
#424

**Comment by luki1412** [comment]
This was fixed.
