### ISSUE TITLE
Request for Feature: Defer option without Admin rights

### ISSUE THREAD

**Issue by Mikeoes** [PSAppDeployToolkit/PSAppDeployToolkit#413]
Hi All,

I would like to request the feature of using the Defer option for users who aren't Local Admin. This would help a lot to deployment of applications via Intune for example. So they have an interface but can defer.

**Comment by SierraEcoBravo** [comment]
In the XML file, you can change the default registry hive for Defer and other toolkit options to HKCU instead of HKLM.

Works fine when we are not running as Admin.
