### ISSUE TITLE
Function Show-InstallationProgress not working

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#417]
In the last commit is the "Function Show-InstallationProgress" not more working

Installation] :: Failure while displaying progress dialog. 
Error Record:
-------------

Message        : Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
InnerException : 

FullyQualifiedErrorId : InvokeMethodOnNull
ScriptStackTrace      : bei <ScriptBlock>, <Keine Datei>: Zeile 96

PositionMessage : In Zeile:96 Zeichen:5
                  +                 $null = $script:ProgressSyncHash.Window.ShowDialog()
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 Error Record:
-------------

Message        : Die Eigenschaft "ToolTip" wurde für dieses Objekt nicht gefunden. Vergewissern Sie sich, dass die 
                 Eigenschaft vorhanden ist und festgelegt werden kann.
InnerException : 

FullyQualifiedErrorId : PropertyNotFound
ScriptStackTrace      : bei <ScriptBlock>, <Keine Datei>: Zeile 95

PositionMessage : In Zeile:95 Zeichen:5
                  + ...               $script:ProgressSyncHash.Window.ToolTip = $installTitle
                  +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 Error Record:
-------------

Message        : Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
InnerException : 

FullyQualifiedErrorId : InvokeMethodOnNull
ScriptStackTrace      : bei <ScriptBlock>, <Keine Datei>: Zeile 93

PositionMessage : In Zeile:93 Zeichen:5
                  + ...             $script:ProgressSyncHash.Window.Add_MouseLeftButtonDown({ ...
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 Error Record:
-------------

Message        : Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
InnerException : 

FullyQualifiedErrorId : InvokeMethodOnNull
ScriptStackTrace      : bei <ScriptBlock>, <Keine Datei>: Zeile 91

PositionMessage : In Zeile:91 Zeichen:5
                  + ...             $script:ProgressSyncHash.Window.Add_Closing({ $_.Cancel = ...
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 Error Record:
-------------

Message        : Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
InnerException : 

FullyQualifiedErrorId : InvokeMethodOnNull
ScriptStackTrace      : bei <ScriptBlock>, <Keine Datei>: Zeile 89

PositionMessage : In Zeile:89 Zeichen:5
                  + ...             $script:ProgressSyncHash.ProgressText = $script:ProgressS ...
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 Error Record:
-------------

Message        : Ausnahme beim Aufrufen von "Load" mit 1 Argument(en):  "Fehler beim Erstellen von "Height" aus dem 
                 Text ""."
InnerException : System.Windows.Markup.XamlParseException: Fehler beim Erstellen von "Height" aus dem Text "". ---> 
                 System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
                    bei System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
                    bei System.Windows.Markup.XamlGridLengthSerializer.FromString(String s, CultureInfo cultureInfo, 
                 Double& value, GridUnitType& unit)
                    bei System.Windows.GridLengthConverter.ConvertFrom(ITypeDescriptorContext typeDescriptorContext, 
                 CultureInfo cultureInfo, Object source)
                    bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(ServiceProviderContext 
                 serviceContext, XamlValueConverter`1 ts, Object value)
                    bei System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, 
                 XamlValueConverter`1 typeConverter, Object value, XamlMember property, String targetName, 
                 IAddLineInfo lineInfo)
                    --- Ende der internen Ausnahmestapelüberwachung ---
                    bei System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri 
                 baseUri)
                    bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory 
                 writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, 
                 Uri baseUri)
                    bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean 
                 skipJournaledProperties, Uri baseUri)
                    bei System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
                    bei System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, 
                 XamlParseMode parseMode)
                    bei CallSite.Target(Closure , CallSite , Type , Object )

FullyQualifiedErrorId : XamlParseException
ScriptStackTrace      : bei <ScriptBlock>, <Keine Datei>: Zeile 88

PositionMessage : In Zeile:88 Zeichen:5
                  + ...             $script:ProgressSyncHash.Window = [Windows.Markup.XamlRea ...
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error Inner Exception(s):
-------------------------

Message        : Fehler beim Erstellen von "Height" aus dem Text "".
InnerException : System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
                    bei System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
                    bei System.Windows.Markup.XamlGridLengthSerializer.FromString(String s, CultureInfo cultureInfo, 
                 Double& value, GridUnitType& unit)
                    bei System.Windows.GridLengthConverter.ConvertFrom(ITypeDescriptorContext typeDescriptorContext, 
                 CultureInfo cultureInfo, Object source)
                    bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(ServiceProviderContext 
                 serviceContext, XamlValueConverter`1 ts, Object value)
                    bei System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, 
                 XamlValueConverter`1 typeConverter, Object value, XamlMember property, String targetName, 
                 IAddLineInfo lineInfo)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Message        : Die Eingabezeichenfolge hat das falsche Format.
InnerException :

**Comment by luki1412** [comment]
Can confirm. Redownloaded the toolkit, seems like the dynamic banners broke this function.

#419 fixes the issue

**Comment by sintaxasn** [comment]
Should be resolved but please verify

**Comment by luki1412** [comment]
Fixed.
