### ISSUE TITLE
Bug in Read language for Win XP machines

### ISSUE THREAD

**Issue by stefaz** [PSAppDeployToolkit/PSAppDeployToolkit#42]
Hi,

i just found a bug in v3.6.4 that breaks the Initialization phase of the toolkit. 
the issue is found at https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L271 where it reads "[int32]$HKULocale = Get-RegistryKey -Key 'HKCU\Control Panel\International' -Value 'Locale' -SID $RunAsActiveUser.SID".
Converting $HKULocale to int32 fails because the LocaleID in "HKCU\Control Panel\International\Locale" is actually stored as hex and can contain characters (as is the case with germany=0xc07) - in this case [int32]$HKULocale is invalid.

thx,
Stefan

**Comment by mmashwani** [comment]
In the registry, Locale is stored as the hex number 0xc07 for German XP? On the English flavors of Windows I've checked, that registry value is stored as a decimal, not a hex.

**Comment by mmashwani** [comment]
I see what the problem is. I've implemented a fix in the latest 3.6.5 beta. Please grab the latest code from here: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1

Let me know if it's working fine for you now.

**Comment by stefaz** [comment]
yes, it's working now - thank you!

**Comment by mmashwani** [comment]
Thanks for testing. I like to keep tickets opened untill we have a final release.
