### ISSUE TITLE
ForceCloseAppsCountdown timer and closed application in background

### ISSUE THREAD

**Issue by FirefoxFX** [PSAppDeployToolkit/PSAppDeployToolkit#421]
Hi,
I am running into a problem when I have the following settings set and in the background the user closed the application outside of the deploymentToolkit.

These are my settings:
Show-InstallationWelcome -CloseApps 'Application' -AllowDefer -DeferTimes 3 -CloseAppsCountdown 60 -BlockExecution -PersistPrompt -ForceCloseAppsCountdown 3600

The deploymentToolkit keeps counting down from an hour until there is no time left and it keeps at 00:00:00 and doesn't continue because it wants to kill the Application that is already closed in the background and not with the close button inside the deploymenttoolkit.

When I then start the application the toolkit detects it and immediately kills it and continues the installation. 
I hope you can fix this issue so that it detects that the program is already closed during the countdown so that it not complete the whole countdown or if not during the countdown that after the countdown it detects if the applications is still there or not and starts the installation.

Thanks for the great program.

**Comment by luki1412** [comment]
Hello,

are we talking about the latest dev version or release 3.7.0?

**Comment by FirefoxFX** [comment]
Hi,

This is with the 3.7.0 release. With the latest master (I dowloaded this morning) the issue is fixed and after the timer ends, with no program open in the backgroun,d the installation starts.
Thanks.
