### ISSUE TITLE
Show-InstallationWelcome - Stop-Process throws exception if process has already exited

### ISSUE THREAD

**Issue by oem111** [PSAppDeployToolkit/PSAppDeployToolkit#422]
Hello Developers,
I would like to report an Issue that I faced.

During my installation of "Cisco Webex" we stop the IBM Notes processes as well in order to guarantee the integration of the webex features.

Example: 
$CloseApps = "nsd,ntmulti,SUService"
Show-InstallationWelcome -CloseApps $CloseApps -AllowDefer -DeferTimes $DeferTimes -ForceCloseAppsCountdown $ForceCloseAppsCountdown

The three processes should be Windows services could have some child dependencies so that the will be killed if another terminated,

The systems are Windows 10 x64 based with PowerShell 5.1 and Windows 7 x64 based with PowerShell 4.
My installation script sometimes throws this exception. I guess 1 to 2 out of 10 fails.

<![LOG[[Pre-Installation] :: The following processes are running: [nsd,ntmulti,SUService].]LOG]!><time="16:07:06.671120" date="07-26-2019" component="Get-RunningProcesses" context="NT AUTHORITY\SYSTEM" type="1" thread="3608" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Resolve process descriptions...]LOG]!><time="16:07:06.671120" date="07-26-2019" component="Get-RunningProcesses" context="NT AUTHORITY\SYSTEM" type="1" thread="3608" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Force close application(s) [IBM Notes/Domino,SUService,wnsd] without prompting user.]LOG]!><time="16:07:06.781120" date="07-26-2019" component="Show-InstallationWelcome" context="NT AUTHORITY\SYSTEM" type="1" thread="3608" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Error Record:
-------------

Message        : Process has exited, so the requested information is not 
                 available.
InnerException : 

FullyQualifiedErrorId : System.InvalidOperationException
ScriptStackTrace      : at Show-InstallationWelcome<Process>, C:\windows\ccmcac
                        he\1u\AppDeployToolkit\AppDeployToolkitMain.ps1: line 
                        6001
                        at <ScriptBlock>, 
                        C:\windows\ccmcache\1u\Deploy-Application.ps1: line 143
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\windows\ccmcache\1u\AppDeployToolkit\AppDeployToolkitMa
                  in.ps1:6001 char:5
                  +                 $runningProcesses | Stop-Process -Force 
                  -ErrorAction 'SilentlyContinue'
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Sadly, regardless of the ErrorAction 'SilentlyContinue', AppDeployKit terminates with 60001

<![LOG[[Pre-Installation] :: CiscoWebEx_MeetingsDesktopApp_33.7.3.7_x86_en-US_01 Installation completed with exit code [60001].]LOG]!><time="16:07:07.532120" date="07-26-2019" component="Exit-Script" context="NT AUTHORITY\SYSTEM" type="1" thread="3608" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: -------------------------------------------------------------------------------]LOG]!><time="16:07:07.547120" date="07-26-2019" component="Exit-Script" context="NT AUTHORITY\SYSTEM" type="1" thread="3608" file="Deploy-Application.ps1">


Is there a possibility to add a "try and catch" construct that catches the "InvalidOperationException"?
Maybe the use of "continue on Error" could help as well.

A solution could be like this:

If ($runningProcesses) {
    [string]$runningProcessDescriptions = ($runningProcesses | Where-Object { $_.ProcessDescription } | Select-Object -ExpandProperty 'ProcessDescription' | Select-Object -Unique | Sort-Object) -join ','
	Write-Log -Message "Force close application(s) [$($runningProcessDescriptions)] without prompting user." -Source ${CmdletName}
    try
    { 
        $runningProcesses | Stop-Process -Force -ErrorAction 'Stop' 
    }
    catch
    {
        If (-not $ContinueOnError) {
            Throw "Failed to stop processes [$($runningProcessDescriptions)]: $($_.Exception.Message)"
        }
        else
        {
            Write-Log -Message "Force close application(s) ignored exception - Continue on Error";
        }
    }
	Start-Sleep -Seconds 2
}

KR

oem111

**Comment by luki1412** [comment]
AFAIK this parameter is for processes only. You will need to stop the service through Stop-Service. Services have permissions though. Antimalware software usually has very limiting permissions so you can't stop the service or change the permissions.

**Comment by DennisVH** [comment]
@luki1412 Agree that services need to be treated as services and not as processes.
@oem111 Toolkit function that you can use is Stop-ServiceAndDependencies
