### ISSUE TITLE
ForceCloseAppsCountdown waits for the amount off time with or without the application is active

### ISSUE THREAD

**Issue by FirefoxFX** [PSAppDeployToolkit/PSAppDeployToolkit#423]
Hi,

I have a question about the latest version of PSAppDeployToolkit. The problem is that when ForceCloseAppsCountdown is defined it waits for the amount off time whether the application is active or not. Can this be changed that if ForceCloseAppsCountdown is defined but when the application is not active the timer will be ignored and the installation starts direct?

Here is my command line:
Show-InstallationWelcome -CloseApps 'APPLICATION' -AllowDefer -DeferTimes 3 -CloseAppsCountdown 60  -BlockExecution -CheckDiskSpace -PersistPrompt -ForceCloseAppsCountdown 3600

Kind regards,

**Comment by DennisVH** [comment]
Adding the parameter -AllowDeferCloseApps allows the installation to continue when the application is not active.
Show-InstallationWelcome -CloseApps 'APPLICATION' -AllowDefer -AllowDeferCloseApps -DeferTimes 3 -CloseAppsCountdown 60 -BlockExecution -CheckDiskSpace -PersistPrompt -ForceCloseAppsCountdown 3600

**Comment by FirefoxFX** [comment]
Hi Dennis,

That did the trick thanks.
