### ISSUE TITLE
Application deployment executable error

### ISSUE THREAD

**Issue by kevball2** [PSAppDeployToolkit/PSAppDeployToolkit#425]
Running into an issue with the latest zip download of the toolkit. Issue is with launching the application executable but getting an error "There is no Unicode byte order mark. Cannot Switch to Unicode"

![image](https://user-images.githubusercontent.com/22545150/63462471-a3f12c00-c420-11e9-9939-398a9d93b21d.png)

Tried a couple downloads but no luck getting even the default package to run

**Comment by luki1412** [comment]
Thats because of the config xml file. When you download it from here, its encoded in UTF8 however in the file UTF16 is specified so you get this error. Regular releases should contain file with correct encoding. Dont know why UTF16 was necessary honestly. I can create a pull request.

**Comment by luki1412** [comment]
This was fixed.
