### ISSUE TITLE
Windows Defender says Virus Detected

### ISSUE THREAD

**Issue by bahnjee** [PSAppDeployToolkit/PSAppDeployToolkit#429]
Windows Defender is blocking the download of PSADT.  Says it's found "HackTool:PowerShell/PowerSploit.E ".

Turning off Defender temporarily allowed the file to download but running PSADT throws an error.  I'll post a separate issue for that because I don't think it's related (the error is the reason I tried to re-download).

**Comment by luki1412** [comment]
I believe that is caused by the impersonation script. The script is not a part of the toolkit but it is here on the repository so when you download the entire zip, it downloads the script as well. You only need the **Toolkit** folder.

**Comment by bahnjee** [comment]
If the "impersonation script" is **Invoke-ProcessWithLogonToken.ps1** then I'd say you're right.  More digging this morning shows this file as the reason for the false virus detection.

I'm good now.  Sorry for the trouble.
