### ISSUE TITLE
Install-MSUpdates Not Functioning

### ISSUE THREAD

**Issue by Landru73** [PSAppDeployToolkit/PSAppDeployToolkit#43]
Using the latest (3.6.5) download zip of the kit.  When running the Install-MSUpdates against some .MSU hotfix files, the installation does not complete.  The log files show it testing it, confirming it doesn't exist, and then immediately saying it does exist, and continues on.  This:
```
Check if Microsoft Update [kb2775511] is installed.]LOG]!><time="09:59:18.369-300"
<![LOG[[Installation] :: Microsoft Update [kb2775511] is not installed.]LOG]!><time="09:59:25.405-300" date="06-03-2015" component="Test-MSUpdates" context="DOMAIN\user" type="1" thread="2020" file="Deploy-Application.ps1">
<![LOG[[Installation] :: KB Number [kb2775511] is already installed. Continue...]LOG]!><time="09:59:25.414-300" date="06-03-2015" component="Install-MSUpdates" context="DOMAIN\user" type="1" thread="2020" file="Deploy-Application.ps1">
```

**Comment by mmashwani** [comment]
Can you share the full log?

**Comment by MaartenPauchet** [comment]
Hi, I have the same issue with some hotfixes required for IE11 deployment. the log file is below:

[Initialization] :: *******************************************************************************	PSAppDeployToolkit	6/5/2015 09:29:05	496 (0x01F0)
[Initialization] :: *******************************************************************************	PSAppDeployToolkit	6/5/2015 09:29:05	496 (0x01F0)
[Initialization] :: [Microsoft_InternetExplorer_11_x64_EN_01] setup started.	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: Script [C:\WINDOWS\ccmcache\1\AppDeployToolkit\AppDeployToolkitMain.ps1] dot-source invoked by [C:\WINDOWS\ccmcache\1\Deploy-Application.ps1]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: Script [C:\WINDOWS\ccmcache\1\AppDeployToolkit\AppDeployToolkitExtensions.ps1] dot-source invoked by [C:\WINDOWS\ccmcache\1\AppDeployToolkit\AppDeployToolkitMain.ps1]	PSAppDeployToolkitExt	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: [Microsoft_InternetExplorer_11_x64_EN_01] script version is [1.0.0]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: [Deploy Application] script version is [3.6.1]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: The following non-default parameters were passed to [Deploy Application]: [-AllowRebootPassThru:$true]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: [App Deploy Toolkit Main] script version is [3.6.5]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: [App Deploy Toolkit Extensions] version is [1.5.0]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: Computer Name is [HVDSCCMTST01.intl.att.com]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: Current User is [NT AUTHORITY\SYSTEM]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: OS Version is [Microsoft Windows 7 Professional Service Pack 1 64-bit 6.1.7601.65536]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: OS Type is [Workstation]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: Current Culture is [en-US] and UI language is [EN]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: Hardware Platform is [Virtual:VMWare]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: PowerShell Host is [ConsoleHost] with version [3.0]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: PowerShell Version is [3.0 x64]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: PowerShell CLR (.NET) version is [4.0.30319.1026]	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: *******************************************************************************	PSAppDeployToolkit	6/5/2015 09:29:06	496 (0x01F0)
[Initialization] :: Display session information for all logged on users: 


NTAccount           : INTL\smsservice
SID                 : S-1-5-21-1935655697-630328440-725345543-18122
UserName            : smsservice
DomainName          : INTL
SessionId           : 1
SessionName         : Console
ConnectState        : Active
IsCurrentSession    : True
IsConsoleSession    : True
IsActiveUserSession : True
IsUserSession       : True
IsRdpSession        : False
IsLocalAdmin        : False
LogonTime           : 6/5/2015 9:03:05 AM
IdleTime            : 00:00:00
DisconnectTime      : 
ClientName          : 
ClientProtocolType  : 
ClientDirectory     : 
ClientBuildNumber   : 0



	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: The following users are logged on to the system: [INTL\smsservice].	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: Current process is running with user account [NT AUTHORITY\SYSTEM] under logged in user session for [INTL\smsservice].	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: The following user is the console user [INTL\smsservice] (user with control of physical monitor, keyboard, and mouse).	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: The active logged on user is [INTL\smsservice].	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: The active logged on user [INTL\smsservice] has a primary UI language of [EN].	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: The following UI messages were imported from the config XML file: [UI_Messages_EN].	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: The active logged on user [INTL\smsservice] has a DPI scale factor of [100] with DPI pixels [96].	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: Unable to load COM Object [Microsoft.SMS.TSEnvironment]. Therefore, script is not currently running from a SCCM Task Sequence.	PSAppDeployToolkit	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: Service [EventSystem] exists.	Test-ServiceExists	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: Get the service [EventSystem] startup mode.	Get-ServiceStartMode	6/5/2015 09:29:08	496 (0x01F0)
[Initialization] :: Service [EventSystem] startup mode is set to [Automatic].	Get-ServiceStartMode	6/5/2015 09:29:09	496 (0x01F0)
[Initialization] :: Get the service object for service [EventSystem].	Start-ServiceAndDependencies	6/5/2015 09:29:09	496 (0x01F0)
[Initialization] :: Service [EventSystem] with display name [COM+ Event System] has a status of [Running].	Start-ServiceAndDependencies	6/5/2015 09:29:09	496 (0x01F0)
[Initialization] :: Service [RpcSs] exists.	Test-ServiceExists	6/5/2015 09:29:09	496 (0x01F0)
[Initialization] :: Get the service [RpcSs] startup mode.	Get-ServiceStartMode	6/5/2015 09:29:09	496 (0x01F0)
[Initialization] :: Service [RpcSs] startup mode is set to [Automatic].	Get-ServiceStartMode	6/5/2015 09:29:10	496 (0x01F0)
[Initialization] :: Get the service object for service [RpcSs].	Start-ServiceAndDependencies	6/5/2015 09:29:10	496 (0x01F0)
[Initialization] :: Service [RpcSs] with display name [Remote Procedure Call (RPC)] has a status of [Running].	Start-ServiceAndDependencies	6/5/2015 09:29:10	496 (0x01F0)
[Initialization] :: Service [EventLog] exists.	Test-ServiceExists	6/5/2015 09:29:10	496 (0x01F0)
[Initialization] :: Get the service [EventLog] startup mode.	Get-ServiceStartMode	6/5/2015 09:29:10	496 (0x01F0)
[Initialization] :: Service [EventLog] startup mode is set to [Automatic].	Get-ServiceStartMode	6/5/2015 09:29:10	496 (0x01F0)
[Initialization] :: Get the service object for service [EventLog].	Start-ServiceAndDependencies	6/5/2015 09:29:10	496 (0x01F0)
[Initialization] :: Service [EventLog] with display name [Windows Event Log] has a status of [Running].	Start-ServiceAndDependencies	6/5/2015 09:29:10	496 (0x01F0)
[Initialization] :: Service [Schedule] exists.	Test-ServiceExists	6/5/2015 09:29:11	496 (0x01F0)
[Initialization] :: Get the service [Schedule] startup mode.	Get-ServiceStartMode	6/5/2015 09:29:11	496 (0x01F0)
[Initialization] :: Service [Schedule] startup mode is set to [Automatic].	Get-ServiceStartMode	6/5/2015 09:29:11	496 (0x01F0)
[Initialization] :: Get the service object for service [Schedule].	Start-ServiceAndDependencies	6/5/2015 09:29:11	496 (0x01F0)
[Initialization] :: Service [Schedule] with display name [Task Scheduler] has a status of [Running].	Start-ServiceAndDependencies	6/5/2015 09:29:11	496 (0x01F0)
[Initialization] :: The task scheduler service is in a healthy state: True.	PSAppDeployToolkit	6/5/2015 09:29:11	496 (0x01F0)
[Initialization] :: Session 0 detected, process running in user interactive mode, user(s) logged in.	PSAppDeployToolkit	6/5/2015 09:29:11	496 (0x01F0)
[Initialization] :: Installation is running in [Interactive] mode.	PSAppDeployToolkit	6/5/2015 09:29:11	496 (0x01F0)
[Initialization] :: Deployment type is [Installation].	PSAppDeployToolkit	6/5/2015 09:29:11	496 (0x01F0)
[Pre-Installation] :: Recursively install all Microsoft Updates in directory [C:\WINDOWS\ccmcache\1\SupportFiles].	Install-MSUpdates	6/5/2015 09:29:11	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2533623] is installed.	Test-MSUpdates	6/5/2015 09:29:11	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2533623] is not installed.	Test-MSUpdates	6/5/2015 09:30:08	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2533623] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:30:08	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2639308] is installed.	Test-MSUpdates	6/5/2015 09:30:08	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2639308] is not installed.	Test-MSUpdates	6/5/2015 09:30:18	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2639308] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:30:18	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2670838] is installed.	Test-MSUpdates	6/5/2015 09:30:18	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2670838] is not installed.	Test-MSUpdates	6/5/2015 09:30:29	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2670838] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:30:29	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2729094] is installed.	Test-MSUpdates	6/5/2015 09:30:29	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2729094] is installed.	Test-MSUpdates	6/5/2015 09:30:39	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2729094] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:30:39	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2731771] is installed.	Test-MSUpdates	6/5/2015 09:30:39	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2731771] is not installed.	Test-MSUpdates	6/5/2015 09:30:49	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2731771] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:30:49	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2786081] is installed.	Test-MSUpdates	6/5/2015 09:30:49	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2786081] is installed.	Test-MSUpdates	6/5/2015 09:31:00	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2786081] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:31:00	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2834140] is installed.	Test-MSUpdates	6/5/2015 09:31:00	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2834140] is not installed.	Test-MSUpdates	6/5/2015 09:31:10	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2834140] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:31:10	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2882822] is installed.	Test-MSUpdates	6/5/2015 09:31:10	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2882822] is not installed.	Test-MSUpdates	6/5/2015 09:31:21	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2882822] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:31:21	496 (0x01F0)
[Pre-Installation] :: Check if Microsoft Update [KB2888049] is installed.	Test-MSUpdates	6/5/2015 09:31:21	496 (0x01F0)
[Pre-Installation] :: Microsoft Update [KB2888049] is not installed.	Test-MSUpdates	6/5/2015 09:31:31	496 (0x01F0)
[Pre-Installation] :: KB Number [KB2888049] is already installed. Continue...	Install-MSUpdates	6/5/2015 09:31:31	496 (0x01F0)
[Pre-Installation] :: Check for running application(s) [iexplore]...	Get-RunningProcesses	6/5/2015 09:31:31	496 (0x01F0)
[Pre-Installation] :: The following processes are running: [iexplore].	Get-RunningProcesses	6/5/2015 09:31:31	496 (0x01F0)
[Pre-Installation] :: Resolve process descriptions...	Get-RunningProcesses	6/5/2015 09:31:31	496 (0x01F0)
[Pre-Installation] :: Finished checking running application(s).	Get-RunningProcesses	6/5/2015 09:31:31	496 (0x01F0)
[Pre-Installation] :: Prompt user to close application(s) [Internet Explorer]...	Show-WelcomePrompt	6/5/2015 09:31:31	496 (0x01F0)
[Pre-Installation] :: Close applications countdown has [3600] seconds remaining.	Show-WelcomePrompt	6/5/2015 09:31:31	496 (0x01F0)
[Pre-Installation] :: User selected to force the application(s) to close...	Show-InstallationWelcome	6/5/2015 09:32:05	496 (0x01F0)
[Pre-Installation] :: Stop process iexplore...	Show-InstallationWelcome	6/5/2015 09:32:05	496 (0x01F0)
[Pre-Installation] :: Stop process iexplore...	Show-InstallationWelcome	6/5/2015 09:32:05	496 (0x01F0)
[Pre-Installation] :: Stop process iexplore...	Show-InstallationWelcome	6/5/2015 09:32:05	496 (0x01F0)
[Pre-Installation] :: Stop process iexplore...	Show-InstallationWelcome	6/5/2015 09:32:06	496 (0x01F0)
[Pre-Installation] :: Check for running application(s) [iexplore]...	Get-RunningProcesses	6/5/2015 09:32:08	496 (0x01F0)
[Pre-Installation] :: Application(s) are not running.	Get-RunningProcesses	6/5/2015 09:32:08	496 (0x01F0)
[Pre-Installation] :: Finished checking running application(s).	Get-RunningProcesses	6/5/2015 09:32:08	496 (0x01F0)
[Installation] :: Get properties from MSI file [C:\WINDOWS\ccmcache\1\Files\IE11-Setup-Full.msi] in table [Property].	Get-MsiTableProperty	6/5/2015 09:32:08	496 (0x01F0)
[Installation] :: Get information for installed Product Code [{17845BC1-EBBA-4AF7-AD41-7DA0C392C698}]...	Get-InstalledApplication	6/5/2015 09:32:08	496 (0x01F0)
[Installation] :: Executing MSI action [Install]...	Execute-MSI	6/5/2015 09:32:09	496 (0x01F0)
[Installation] :: [msiexec.exe] successfully resolved to fully qualified path [C:\WINDOWS\system32\msiexec.exe].	Execute-Process	6/5/2015 09:32:09	496 (0x01F0)
[Installation] :: Check to see if mutex [Global\_MSIExecute] is available. Wait up to [10 minute(s)] for the mutex to become available.	Test-IsMutexAvailable	6/5/2015 09:32:09	496 (0x01F0)
[Installation] :: Mutex [Global\_MSIExecute] is available for an exclusive lock.	Test-IsMutexAvailable	6/5/2015 09:32:09	496 (0x01F0)
[Installation] :: Working Directory is [C:\WINDOWS\ccmcache\1\Files].	Execute-Process	6/5/2015 09:32:10	496 (0x01F0)
[Installation] :: Executing [C:\WINDOWS\system32\msiexec.exe /i "C:\WINDOWS\ccmcache\1\Files\IE11-Setup-Full.msi" /QN /L*v "C:\WINDOWS\ITO\Logs\IE11-Setup-Full_Install.log"]...	Execute-Process	6/5/2015 09:32:10	496 (0x01F0)
[Installation] :: Execution completed successfully with exit code [0].	Execute-Process	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: Return fully qualified registry key path [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Main\EnterpriseMode].	Convert-RegistryPath	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: Update registry key value: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Main\EnterpriseMode] [Enable = ].	Set-RegistryKey	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: Microsoft_InternetExplorer_11_x64_EN_01 Installation completed with exit code [0].	Exit-Script	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: Display balloon tip notification asyhchronously with message [Installation complete.].	Show-BalloonTip	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: [C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe] is a valid fully qualified path, continue.	Execute-Process	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: Working Directory is [C:\WINDOWS\System32\WindowsPowerShell\v1.0].	Execute-Process	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: Executing [C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe [PowerShell ScriptBlock]]...	Execute-Process	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: NoWait parameter specified. Continuing without waiting for exit code...	Execute-Process	6/5/2015 09:32:42	496 (0x01F0)
[Post-Installation] :: -------------------------------------------------------------------------------	Exit-Script	6/5/2015 09:32:42	496 (0x01F0)

**Comment by That-Annoying-Guy** [comment]
You could look at WMI:

	#region Get-ListOfInstalledUpdates
	Function Get-ListOfInstalledUpdates {
	<#
	.SYNOPSIS
		Returns an [array] of all the Updates installed on this computer
	.DESCRIPTION
		More reliable than the searcher method but is slower.
	.EXAMPLE
		Get-ListOfInstalledUpdates
	.NOTES
	#>	

		#Get list of updates installed, only get the KBnumber
		[array]$InstalledUpdates= Get-WmiObject -class win32_quickfixengineering -Property HotFixID
	#	return $InstalledUpdates

		#I meant only the KBnumber god dammit!
		[array]$CleanedUpList=@()
		foreach ($update in $InstalledUpdates) {
			#$update.HotFixID
			[array]$CleanedUpList += $update.HotFixID
		}

		return $CleanedUpList
	}
	#Endregion Get-ListOfInstalledUpdates

**Comment by Landru73** [comment]
I ended up commenting out the code spoken of in Issue #39 to get mine to work.  I wasn't doing Office patches for mine, so the removal worked.

**Comment by mmashwani** [comment]
Can you please test the updated function in the latest 3.6.5 beta? I think I have this issue resolved now.
