### ISSUE TITLE
If no apps to close, install silently

### ISSUE THREAD

**Issue by MechaClick** [PSAppDeployToolkit/PSAppDeployToolkit#433]
Is there a way to skip the dialog box if there are no apps running that need to be closed, while having the defer option on?

If the app being updated isn't running, then install silently in the background.
If the app being updated is running, prompt the user and allow defer.

In my scenario, there is no need to allow the user to defer if the application isn't running and/or prompt them at all.

Thanks!

**Comment by pchatham** [comment]
There is no built-in function for this, that I am aware of.
You can achieve what you describe with some logic prior to `Show-InstallationWelcome`

This should get you started


`if (Get-Process notepad -ErrorAction SilentlyContinue) {
    
    # App is running, present UI
    Show-InstallationWelcome -CloseApps 'Notepad'

} else {

    # App is not running - force install
    Show-InstallationWelcome -CloseApps 'Notepad' -Silent

}`


Hope this helps!

**Comment by MechaClick** [comment]
This worked!

Thank you
