### ISSUE TITLE
Symantec Application Parameter Issue

### ISSUE THREAD

**Issue by TekJunki** [PSAppDeployToolkit/PSAppDeployToolkit#434]
Hello, there everyone, so I was in the process of packaging up Symantec Critical System Protection using the toolkit and this package will be used within a Task Sequence. I have everything working except for the install of the application. Below you will see the official Symantec install parameters and I am trying to put them into the toolkit and I am running it an issue. My guess is that I am goofing up with the quotations. Any help is greatly appreciated and thank you for your time as well.

**Offical Symantec Install Command: (Test In PSEXEC and it works)**
agent.exe /s /v"MANAGEMENT_SERVER=x.x.x.x SSL_CERT_FILE=c:\Agent-cert.ssl -l*v+! %temp%\SISAgentSetup.log /qn"

**Currently In Toolkit Command: (Not Working)**
Execute-Process -Path "agent.exe" -Parameters "/s /v MANAGEMENT_SERVER=x.x.x.x SSL_CERT_FILE=C:\IT_Installers\xxx.ssl -l*v+! C:\osdlogs2\Software_Installations\SISAgentSetup.log /qn"

Thank you again :)

**Comment by macxcool** [comment]
If you want to copy the parameters you have in the 'official symantec install command', you'll have to escape the quotes or use single quotes, like this
`Execute-Process -Path 'agent.exe' -Parameters '/s /v"MANAGEMENT_SERVER=x.x.x.x SSL_CERT_FILE=c:\Agent-cert.ssl -l*v+! %temp%\SISAgentSetup.log /qn"'`
If you don't have any variables in your string that need to be expanded, single quotes are the way to go. If you do have variables in there, then use `" to include literal quotes.

**Comment by RobinBeismann** [comment]
Also place the Agent-cert.ssl in the PSADT\Files folder and reference it with "$dirFiles\Agent-cert.ssl", the $dirFiles variable is available during installation and points to the files folder in the CCM Cache.

**Comment by macxcool** [comment]
If you're going to use a variable, like $dirFiles or $dirSupportFiles, then you'll have to use double quotes for the whole parameters string and single quotes or escaped quotes for the /v string.
```
Execute-Process -Path "$dirFiles\agent.exe" -Parameters "/s /v`"MANAGEMENT_SERVER=x.x.x.x SSL_CERT_FILE=C:\IT_Installers\xxx.ssl -l*v+! C:\osdlogs2\Software_Installations\SISAgentSetup.log /qn`""
```

**Comment by TekJunki** [comment]
Thank you both for your feedback, I will try it out and report back. Can you share with me what I was doing wrong in this process so I can learn for future reference? Really appreciate the time and help with this :)

**Comment by TekJunki** [comment]
Lol, I love you guys, your recommendation worked like a charm. Please forgive me as I am new to this PowerShell language and a guy with no background in programming at all. It has been a struggle learning this language, but using this Awesome tool, I am starting to understand it a little bit at a time. Again thank you so much for your time and help and hopefully, I will get little info on what did wrong :)

**Comment by RobinBeismann** [comment]
Just as hint: Always keep the files which belong to the package, with the package. This ensures the same experience on all devices.

**Comment by TekJunki** [comment]
> Just as hint: Always keep the files which belong to the package, with the package. This ensures the same experience on all devices.

I appreciate the help and will keep this in mind. I usually keep everything in the Files folder but I didn't know that I can leverage the CCM Cache folder to get everything done. Lol originally I was planning to copy the SSL Cert locally to the machine as you saw above, but I am going to try out your recommendation and see what happens :)

**Comment by RobinBeismann** [comment]
If you keep everything within the package, you're effectively leaving the content distribution to SCCM, which is meant to do exactly this. If you have multiple Deployment Points in several sites, this pays off pretty fast. PSADT does it job and translates $dirFiles to the Files Directory whereever it is on the disk right now.
