### ISSUE TITLE
AppDeployToolkitMain.ps1 failed to load:  You must provide a value expression on the right-hand side of the '-' operator

### ISSUE THREAD

**Issue by z442a9** [PSAppDeployToolkit/PSAppDeployToolkit#436]
For some reason some machines are giving me this error and I'm not sure what is the issue. 
AppDeployToolkit\AppDeployToolkitMain.ps1] failed to load:  You must provide a value expression on the right-hand side of the '-' operator.
 
At \AppDeployToolkit\AppDeployToolkitMain.ps1:7520 char:17

+             If ($Action - <<<< in 'PintoStartMenu', 'UnpinfromStartMenu')
At line:1 char:25
+ .\deploy-application.ps1 <<<< 
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Deploy-Application.ps1
 
Any ideas? Some machines run this same script fine.

**Comment by snowmountainer** [comment]
I noticed the same error on a computer running Windows 7 64-bit. 
-------------------------------------------------------------------------
$PSVersionTable

Name                           Value                                                                                                                                                                                                       
----                           -----                                                                                                                                                                                                       
CLRVersion                     2.0.50727.8806                                                                                                                                                                                              
BuildVersion                   6.1.7601.23403                                                                                                                                                                                              
PSVersion                      2.0                                                                                                                                                                                                         
WSManStackVersion              2.0                                                                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0}                                                                                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                                                                                                     
PSRemotingProtocolVersion      2.1

**Comment by SierraEcoBravo** [comment]
Someone please correct me but PowerShell 2 doesn't support the -in Comparison operator. Check the version of PowerShell on the systems with the error.

Good luck.

**Comment by luki1412** [comment]
> Someone please correct me but PowerShell 2 doesn't support the -in Comparison operator. Check the version of PowerShell on the systems with the error.
> 
> Good luck.

That is correct. The -in parameter isnt supported under the ps 2.0 version that comes with win 7. There is a simple fix for this case but Im not sure if there are any other changes we would need to do to support this version.

**Comment by snowmountainer** [comment]
@SierraEcoBravo: Yes that's true. I noticed that the Windows Management Framework 5.1 is missing from the computer mentioned. After installation, PSAppDeployToolkit works.

**Comment by Spartan-196** [comment]
Should this be taken as an indicator that the system requirements listed in the admin guide are no longer valid?

>  The system requirements are as follows: 
>  • PowerShell 2.0 
>  • Windows NT 5.1 and above

**Comment by RobinBeismann** [comment]
I'm running multiple packages on computers with Powershell 2.0, I didn't try pinning an application through.
I'd suggest that we update the code so it is fully compatible with PS2.0, I don't think it's too much effort.

**Comment by Spartan-196** [comment]
I have been doing so as well with prior to the 3.8.0 release. I had similar results to @z442a9 when running on 3.8.0 packages on systems on PS2.0. The failure point was when AppDeployToolkitMain.ps1 was dot sourced it would fail the import and exit with toolkit exit code 60008.

As @SierraEcoBravo points out the -in operator is not supported in PS2.0, it may be possible to switch this over to -contains and move which side of the operator the value is on. However the actual logic match might differ between those operators

**Comment by Spartan-196** [comment]
@RobinBeismann  Thanks for merge request #437!

**Comment by luki1412** [comment]
Fixed.
