### ISSUE TITLE
Function Get-InstalledApplication : bypass any updates or hotfixes

### ISSUE THREAD

**Issue by EvgeniyPolikarov** [PSAppDeployToolkit/PSAppDeployToolkit#438]
I had an issue with uninstalling msi via ADT, because it had KB with number in DisplayName. And it took some time to determine what is the problem, which was "## Bypass any updates or hotfixes" section in Get-InstalledApplication function.

So, I suggest, that maybe it will be better, if appropriate message will be written to log file in case DisplayName matches bypassing template.
But in this case "## Bypass any updates or hotfixes" section should be after checking if ProductCode/application name matches Uninstall registry hive.

I hope that maybe my suggestion will make ADT even better.

Thanks.

**Comment by luki1412** [comment]
It will now log how many items were skipped due to them being updates.

**Comment by mjr4077au** [comment]
This issue was addressed long ago.
