### ISSUE TITLE
Fix Set-ActiveSetup purging error (PADT 3.8.0)

### ISSUE THREAD

**Issue by madsps** [PSAppDeployToolkit/PSAppDeployToolkit#439]
Hello,

I suppose the following issue [#427](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/427) was resolved in PADT 3.8.0.

However implemented solution causes a new error. I'm talking about following code:
` If (Test-Path -Path $HKCUActiveSetupKey) {
Remove-RegistryKey -Key $HKCUActiveSetupKey -SID $UserProfile.SID -Recurse
}
`

Lets have a look on example inside the `Invoke-HKCURegistrySettingsForAllUsers` function (mentioned above code will be executed by it):
`Execute ScriptBlock which contains code to manipulate HKCU registry.
Make sure read/write calls to the HKCU registry hive specify the -SID parameter or settings will not be changed for all users.
Example: Set-RegistryKey -Key 'HKCU\Software\Microsoft\Office\14.0\Common' -Name 'qmenable' -Value 0 -Type DWord -SID $UserProfile.SID
`

As you can see all read/write calls must use -SID parameter in order to run under the specific user. In PADT 3.8.0 **If (Test-Path -Path $HKCUActiveSetupKey)** will always be executed under the user who launched installation. As result it will remove Active Setup entry for this user only. 

One of possible solutions is to replace `Test-Path` with `Get-RegistryKey -key $HKCUActiveSetupKey -SID $UserProfile.SID`

**Comment by luki1412** [comment]
This has been resolved. Please download the latest version.
