### ISSUE TITLE
ActiveSetup not triggering for installing user due to AppLocker

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#447]
When you install a PSADT script and it uses Set-ActiveSetup, it will run what is placed in the StubPath value for the user that is running the PSADT script. This saves the installing user a reboot.

This works fine until your organization decides to use Windows 10's AppLocker feature.
AppLocker is designed to stop scripts and EXE from running from the User's profile.
AppLocker is great to block scripts that the user downloads (knowingly or not) and user-created scripts. Usually AppLocker is configured to whitelist locations where users have no permissions.  

FYI: When AppLocker blocks a script, it lies to the process that launch the script and returns exitcode 0. IOW: The script never runs but the parent process thinks it did.

For PSADT to run the StubPath it creates a **c:\users\PSADT\$appDeployToolkitName-ExecuteAsUser.vbs** script. Because the VBS script is created in a profile folder, AppLocker blocks the script and returns exitcode 0 to the main PSADT script.

Since we configured AppLocker to allow script to run in C:\ProgramFiles\ for other applications,
OUR solution was to move the PSADT folder to C:\ProgramFiles\ 
This works because PSADT is always run elevated (at least in my shop) and therefore has the permissions to write to C:\ProgramFiles\.

The **c:\users\PSADT** path is set in AppDeployToolkitConfig.xml so we changed:

		<Toolkit_TempPath>$envSystemDrive\Users\Public</Toolkit_TempPath>
		
to:

		<Toolkit_TempPath>$envProgramFiles</Toolkit_TempPath>

This fixed the issue. 

It's up to the main authors of PSAppDeployToolkit to decide if this should be the new default or not.

I hope other users of AppLocker can chime in to validate or put down my solution.

**Comment by luki1412** [comment]
AppLocker ignores scripts running inside windows folder and program files by default. I would rather use Windows folder. Also the name for the vbs script is way too long IMO.

**Comment by luki1412** [comment]
The default temp path was changed to Windows\Temp when running with admin rights. Which is not accessible to user at all. So the script will run fine but the ActiveSetup script/app has to be elsewhere, accessible to user but without write access.
