### ISSUE TITLE
Installation Process dialog is not closing after the installation finishes

### ISSUE THREAD

**Issue by headcra6** [PSAppDeployToolkit/PSAppDeployToolkit#448]
In quite a rare but possible case, I faced the mentioned behavior. In my script, I show the installation process dialog and perform some checks right after that. If some of the checks are failed I stop the script with Exit-Script 69001. According to the Log file the script finished but the Installation Process still exists and SCCM is not receiving the final exit code.
I've looked into the main and find the root cause. The following scenario takes place:
1. Installation started
2. The Show-InstallationProcess run scriptblock in async mode to show the dialog
3. Before the dialog shows up the exit-script started Close-InstallationProcess function and does not close anything because the dialog is not yet appeared. 
4. The Exit-Script function finished
5. Finally, the dialog appears and the installation hangs on it

This issue is reproducing on a low resource PC's/VM's and became visible after we upgrade to Windows 10 1903.

So I added a couple of lines in Show-InstallationProcess and it helps for me in this issue:
```
$progressData = $progressCmd.BeginInvoke() # the creation of the dialog started asynchronously
#  Allow the thread to be spun up safely before invoking actions against it.
#  Setup counter
[int]$skipConunter = 0
[int]$skipConunterLimit = 10
do
{
	Start-Sleep -Seconds 1
        $skipCounter++
	Write-Log -Message "Waiting for displaying progress dialog for ${skipCounter}sec ..." -Source ${CmdletName}
	If ($script:ProgressSyncHash.Error) {
		Write-Log -Message "Failure while displaying progress dialog. `n$(Resolve-Error -ErrorRecord $script:ProgressSyncHash.Error)" -Severity 3 -Source ${CmdletName}
		Break
	}
} While (($script:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState -ne 'Running') -Or ($skipCounter -lt $skipCounterLimit) )
```
This code will wait for 10 sec (or whatewer set in $skipCounterLimit, let's assume that if dialog is not appeared in 10 sec it won't apear at all, I think the Error will apears earlier if it is and quit the loop with Break) and proceed with the code.

In my case, it takes 2-3 secs to show up the dialog and after that it closes successfully 

Please review

**Comment by luki1412** [comment]
I think a better way would be to modify Exit-Script to close all windows opened by the toolkit.

**Comment by headcra6** [comment]
The Exit-Script already does it with Close-InstallationProcess. The issue I described covers the case when the InstallProgress dialog is not yet created and Exit-Script is called. 
Simple example, if you show the dialog and after that, you check for the existence of the prerequisite. and if it is not found you are going to close the script with custom error. On a slow PC you will get an issue

**Comment by luki1412** [comment]
Close-Installation would need to check whether the window is still needed and not create one/close it if not.

**Comment by headcra6** [comment]
The Close-InstallationProcees does the following, it checks the condition:
`$script:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState -eq 'Running'`
In my case, this value is not yet defined, because of the instance of the dialog is not created yet. When the Exit-Script started this condition skipped.

**Comment by luki1412** [comment]
I modified the function. Can you please download the main script from our repository and test again?
