### ISSUE TITLE
Remove-MSIApplications function failed for MSI's with ARPNOREMOVE

### ISSUE THREAD

**Issue by headcra6** [PSAppDeployToolkit/PSAppDeployToolkit#449]
The function **Remove-MSIApplications** failed with the error "_Skipping removal of application **DisplayName** because uninstall string **UninstallString** does not match "msiexec"._". This issue appeared in cases when target MSI installed with APRNOREMOVE property set and caused by the absence of UninstallString in the registry. The function is seeking "msiexec" in the Uninstall string for as I understand to check if the product is MSI.
I would recommend changing this validation and seek msi products here:
**_HKLM:\SOFTWARE\Classes\Installer\Products_** or **_HKEY_CLASSES_ROOT\Installer\Products_**

Here the function I have for this check:
```
function Get-IfProductCodeIsMSI {
    param (
        [Parameter(Mandatory,ValueFromPipeline)]
        [guid]$ProductCode
    )
    $keyInstallerProducts="HKLM:\SOFTWARE\Classes\Installer\Products"
    $ProductCode.ToByteArray() | ForEach-Object { $productID += ($_ -band 15).ToString('X') + ($_ -shr 4).ToString('X') }
    Return Test-Path "$keyInstallerProducts\$productID"
}
```

And it can be used in the following way:
Define Product Code
`$productCode = '{B930C9EB-203C-49EE-8E29-C9DB46FFFB0C}'`
Get result to varaibale
```
$IsMSI = Get-IfProductCodeIsMSI -ProductCode $productCode
Write-Host $IsMSI

```
Or use pipline
`Write-Host ($productCode | Get-IfProductCodeIsMSI)
`

**Comment by DennisVH** [comment]
#461

**Comment by DennisVH** [comment]
Fix has been implemented
