### ISSUE TITLE
Set-ActiveSetup does not create HKCU Active Setup > Installed Components entries

### ISSUE THREAD

**Issue by Joelster73** [PSAppDeployToolkit/PSAppDeployToolkit#45]
Since the HKCU Active Setup > Installed Components entries are not created after the StubPath is executed for the current user, when they log off and back in it will re-run the StubPath which could cause issues (in my current case importing HKCU registry entries - if the user changes these entries then logs out and back in they will be re-imported and overwritten).

**Comment by mmashwani** [comment]
Thanks for reporting this issue. I just pushed a fix for this to the 3.6.5 beta. Please test from here and let me know if it's working as expected now:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit

**Comment by Joelster73** [comment]
Working as expected. Thanks for the super fast response on this!
