### ISSUE TITLE
Execute-MSI does not replace bad characters in log names properly and Zip-compressions of logfolder might fail

### ISSUE THREAD

**Issue by Basti890** [PSAppDeployToolkit/PSAppDeployToolkit#452]
I have Discovered this when using `Execute-MSI uninstall "PRODUCTCODE"` the logname is generatet by using the data from the registry entry of this software.
By using this characters like : ®™ are not removed from the Log-Name and the when using Zip-compression for the logs the operation fails due bad filenames.
So for this Software I get an error after the uninstall.
 
![Window-2019-11-13 10_07_34](https://user-images.githubusercontent.com/11937981/68749369-64407780-05fe-11ea-97de-fe0b1531cf5d.png)

**Comment by Basti890** [comment]
As a quick fix I'm now using the -LogName Parameter to set for this specif uninstall operation a custom LogName.

**Comment by luki1412** [comment]
Fixed.
