### ISSUE TITLE
Have you planned to release a compiled version with the dotnet 4.0 framework?

### ISSUE THREAD

**Issue by LaurentDardenne** [PSAppDeployToolkit/PSAppDeployToolkit#453]
Hello,
have you planned to release a compiled version with the dotnet 4.0 framework?

We have a workstation master that does not integrate the dotnet 2.0 framework or the 3.5 version, so the current version does not work.

I have created a private fork for this case, to your knowledge is there any particular points to check / test?

**Comment by luki1412** [comment]
What issues did you have when running toolkit on a machine with only .NET 4?

**Comment by LaurentDardenne** [comment]
For now no if I compile with dotnet 4.0.
This version would be used via MS Intune

**Comment by luki1412** [comment]
What do you mean compiled? There is only a simple .exe that needs to be compiled and thats a simple launcher that can run on any .NET framework. Everything else is poweshell and some config files.

**Comment by LaurentDardenne** [comment]
>  
> What do you mean compiled? 
Like _dotnet build_ 
Thank you.
