### ISSUE TITLE
Setting a meaningful window-title ...

### ISSUE THREAD

**Issue by NordicAT** [PSAppDeployToolkit/PSAppDeployToolkit#454]
Hello,

I do NOT use a deployment-solution like SCCM.
I call the PSAppDeployToolkit from a PowerShell-script. 

It is not important, but the call looks somehow like this:
```Powershell
Start-Process -FilePath "PowerShell.exe" -WorkingDirectory "C:\Temp\MyPackage" -PassThru -Wait -ArgumentList "-ExecutionPolicy ByPass","-NoProfile","-NoLogo","-File `"C:\Temp\MyPackage\Deploy-Application.ps1`"","-DeploymentType `"Install`"","-DeployMode `"Silent`""
```

The PowerShell-window opens and the installation of the package starts. Unfortunately the window has no meaningful title:

![Window-Title](https://user-images.githubusercontent.com/42859522/69279955-ae6cbe80-0be5-11ea-8d96-e743e72594eb.png)

When installing a lot of packages in a sequence I would love to see the package-name in the window-title somehow like this:

![Windows-Title-mod](https://user-images.githubusercontent.com/42859522/69280641-1bcd1f00-0be7-11ea-969e-3dc55529a62e.png)

Getting the title like in the example above is a one-liner:

```Powershell
$Host.UI.RawUI.WindowTitle = "$DeploymentType - $installTitle"
```

I would love, if you could implement this.

Thank you!

**Comment by luki1412** [comment]
I don't think there would be an issue with implementing this. It's just something not many people use because you have the wrapper .EXE that starts powershell exe silently so the toolkit displays a window while powershell works silently in the background, therefore there is no reason for a title.

**Comment by NordicAT** [comment]
I did just run a deployment with the latest codebase.
The window-title is set as requested.

Great - Thank you for the support!
