### ISSUE TITLE
Show-InstallationPrompt timeout not working using PersistPrompt after closing 

### ISSUE THREAD

**Issue by Captaincaveman1** [PSAppDeployToolkit/PSAppDeployToolkit#455]
Hi All, I've been using PSADT for a little while now and its been awesome. I think I just found a bug in the Show-InstallationPrompt dialog when using the Timeout and PersistPrompt.  Basically after attempting to close using the X in the top right corner of the dialog, the dialog reappears as expected but the timeout now does not work, the dialog sits there forever.  Here is a code example of what I'm doing.

Main {
Function Display-Popup {

    $message="A critical update needs to be applied in " + [math]::Round(($TimeLeft.TotalMinutes),0) + " after which forced restart will occur. Select Defer to defer this message for 30 minutes or select Install Now to apply the update immediately..."
    $ButtonPressed=(Show-InstallationPrompt -title 'Critical Update' -message $message -ButtonLeftText 'Defer' -ButtonRightText 'InstallNow' -Icon None -PersistPrompt -timeout 60 -ExitOnTimeout $false -MessageAlignment Left -MinimizeWindows $true)
    return $ButtonPressed
}

$StartTime=(Get-Date)
$Duration=New-TimeSpan -Minutes 100
$TimeLeft=  $Duration - (New-TimeSpan -Start $StartTime -End (Get-Date))

do {
    switch (Display-Popup) {

        "Defer" {$TimeLeft=  $Duration - (New-TimeSpan -Start $StartTime -End (Get-Date)); $Timer=[math]::Round(($TimeLeft.TotalMinutes),0); Write-Host "User selected Defer, time left is $timer" ; Start-Sleep -s 1800}
        "InstallNow" {Write-Host "User selected InstallNow"; $Duration =New-TimeSpan -Minutes -1;Break }

    }
    $TimeLeft=  $Duration - (New-TimeSpan -Start $StartTime -End (Get-Date))
    $Timer=[math]::Round(($TimeLeft.TotalMinutes),0)
    Write-Host "Timer = $timer minutes"
} While ($timer -ge 0)

}

I've already updated to PSADT 3.8  and the issue persists...

Cheers

Captain

**Comment by luki1412** [comment]
This is a confirmed bug. Will look into it.
