### ISSUE TITLE
Extend AppDeployToolkitHelp with AppDeployToolkitExtensions functions

### ISSUE THREAD

**Issue by dianneman** [PSAppDeployToolkit/PSAppDeployToolkit#459]
I'd like to extend the ToolkitHelp.ps1 with my own functions. Other people can quickly find help for these functions when needed, it's all at one place. 

_AppDeployToolkitMain.ps1_ does not dot source _AppDeployToolkitExtensions.ps1_ when called from _AppDeployToolkitHelp.ps1_. This needs to be changed or dot source directly from the _AppDeployToolkitHelp.ps1_ file

`. "$scriptDirectory\AppDeployToolkitExtensions.ps1"`

edit: Maybe split of function pane to seperate customs from original, default prefix for function or names in different color?

![CustomFunctionHelp](https://user-images.githubusercontent.com/39791149/70607167-3c90ff00-1bfe-11ea-84a1-a52ec173c68f.png)

**Comment by luki1412** [comment]
This has been resolved, please download the latest version.

**Comment by dianneman** [comment]
> This has been resolved, please download the latest version.

Thanks!
