### ISSUE TITLE
Renaming Deploy-Application.exe triggers .Net requirement

### ISSUE THREAD

**Issue by v01ded** [PSAppDeployToolkit/PSAppDeployToolkit#460]
Hi,

I have create a simple package that will enable .Net Framework on Windows 10 machine using the command  
 ` Execute-Process -Path "$envSystem32Directory\Dism.exe" -Parameters "/Online /Disable-Feature /FeatureName:NetFX3" -WindowStyle Hidden`

The package runs well when I launch it with Deploy-Application.exe. However, if renew the Deploy-Application.exe to another any other name, I will get the Windows's Prompt to enable .Net Framework 3.5(https://images.app.goo.gl/1SZqVwAuEkyoaSYH7). I did not rename the Deploy-Application.exe.config and Deploy-Application.ps1 files.

Cheers.

Stanley Lim

**Comment by luki1412** [comment]
But you say enable yet the command specifies /Disable-Feature. When you try to install/enable it, you need to specify sources on windows 10.

What I think you are trying to say is that the toolkit doesnt work on windows 10 without net framework without 3.5/2.0. Is that correct?

**Comment by v01ded** [comment]
> But you say enable yet the command specifies /Disable-Feature. When you try to install/enable it, you need to specify sources on windows 10.
> 
> What I think you are trying to say is that the toolkit doesnt work on windows 10 without net framework without 3.5/2.0. Is that correct?

Sorry type mistake, it should be enable.

Either way, if we rename the original Deploy-Application.exe to another fileaname, I will get a Windows's Prompt for .Net 3.5 installation if the W10 system does not already have .NET enable.

By default the system that i tried to run the Toolkit on does not have .NET enable and a numerous of installer created previously runs perfectly. Recently, I decided to rename the Deploy-Application.exe  to a name that better reflect the application it is installing and stumble upon this issue

**Comment by luki1412** [comment]
> > But you say enable yet the command specifies /Disable-Feature. When you try to install/enable it, you need to specify sources on windows 10.
> > What I think you are trying to say is that the toolkit doesnt work on windows 10 without net framework without 3.5/2.0. Is that correct?
> 
> Sorry type mistake, it should be enable.
> 
> Either way, if we rename the original Deploy-Application.exe to another fileaname, I will get a Windows's Prompt for .Net 3.5 installation if the W10 system does not already have .NET enable.
> 
> By default the system that i tried to run the Toolkit on does not have .NET enable and a numerous of installer created previously runs perfectly. Recently, I decided to rename the Deploy-Application.exe to a name that better reflect the application it is installing and stumble upon this issue

Did you also rename the .exe.config file ?

**Comment by v01ded** [comment]
> > > But you say enable yet the command specifies /Disable-Feature. When you try to install/enable it, you need to specify sources on windows 10.
> > > What I think you are trying to say is that the toolkit doesnt work on windows 10 without net framework without 3.5/2.0. Is that correct?
> > 
> > 
> > Sorry type mistake, it should be enable.
> > Either way, if we rename the original Deploy-Application.exe to another fileaname, I will get a Windows's Prompt for .Net 3.5 installation if the W10 system does not already have .NET enable.
> > By default the system that i tried to run the Toolkit on does not have .NET enable and a numerous of installer created previously runs perfectly. Recently, I decided to rename the Deploy-Application.exe to a name that better reflect the application it is installing and stumble upon this issue
> 
> Did you also rename the .exe.config file ?

Yes, tried that.  Same issue faced.

**Comment by luki1412** [comment]
I can not replicate this. I uninstalled .net framework 3.5,renamed the exe and the exe.config and then started it. ran without issues.

**Comment by luki1412** [comment]
You are trying to install net framework that's why it is opening the window. You need to supply location for net framework 2/3.5 files because they are not present by default, you have to copy them from windows 10 iso.

The toolkit itself supports net framework 2.0, 3.5, 4+

**Comment by Ar5had07** [comment]
I just had the same issue.  I renamed Deploy-Application.exe to Install.exe and now it's prompting for .Net if you dont have it installed.

**Comment by luki1412** [comment]
You have to change the name of the .config file as well.

**Comment by Ar5had07** [comment]
> You have to change the name of the .config file as well.

Are you talking about this configfile? And that file is not referenced anywhere on any script to be changed?
![image](https://user-images.githubusercontent.com/46709367/103358002-76080700-4aac-11eb-91f7-61e374c18b9c.png)

**Comment by Ar5had07** [comment]
Oh you mean this one.  My apologies.
![image](https://user-images.githubusercontent.com/46709367/103358052-9cc63d80-4aac-11eb-8add-8c92af6c4dd7.png)

**Comment by hkystar35** [comment]
I ran into this same issue and was glad to find a resolution.
