### ISSUE TITLE
Set-PinnedApplication does not work anymore on Windows 10 1903

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#467]
Set-PinnedApplication does not work anymore on Windows 10 1903

**Comment by luki1412** [comment]
_"The items that are pinned to the Start menu or taskbar is a user preference. Applications should not be overriding the user’s preferences. In the long term, programmatically pinning items to the taskbar or Start menu in Windows 10 will not be supported. Only the user will be able to pin items."_

Programmatically you can do it but it will ask the user - https://docs.microsoft.com/en-us/windows/uwp/design/shell/pin-to-taskbar

**Comment by Rustamus82** [comment]
Stil not working neither in windows 10 nor windows 11, any plan to make it work again?

**Comment by mjr4077au** [comment]
Apologies but no, it's been removed from the upcoming v4 due to its non-functioning state.
