### ISSUE TITLE
Allow Execute-ProcessAsUser to run PowerShell scriptblocks

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#468]
Add logic to allow Execute-ProcessAsUser to run PowerShell scriptblocks

**Comment by DennisVH** [comment]
This will be fixed in the next release

An example to run Set-PinnedApplication as user
Prerequisites: 
- log file location is writable by Users
- Toolkit_LogStyle is set to Legacy

Code:
```[string]$installPhase = 'Pre-Installation'
        $scriptblockstring = $ExecutionContext.InvokeCommand.ExpandString(". '$scriptDirectory\AppDeployToolkit\AppDeployToolkitMain.ps1' -DisableLogging -ReferredLogName '$logName'") + [environment]::NewLine
        $scriptblockstring += '$DisableLogging = $False' + [environment]::NewLine
        $scriptblockstring += $ExecutionContext.InvokeCommand.ExpandString("Set-PinnedApplication -Action 'PintoStartMenu' -FilePath '$envCommonStartMenu\Programs\Notepad++.lnk'")
        $scriptblock = [scriptblock]::Create($scriptblockstring)
        
        Execute-ProcessAsUser -Path "$pshome\powershell.exe" -Parameters "-executionpolicy bypass -command `"& { $scriptblock }`"" -Wait```

**Comment by Sulquendi** [comment]
Hello !

With Constrained Language Mode, PSADT scripts needs the "Toolkit_RequireAdmin" => True, which conflicts with executing the toolkit in User mode.

**Comment by luki1412** [comment]
> Hello !
> 
> With Constrained Language Mode, PSADT scripts needs the "Toolkit_RequireAdmin" => True, which conflicts with executing the toolkit in User mode.

Please create a new issue with logs and details about the issue.
