### ISSUE TITLE
Execute Process fails on empty argument list in Constrained Language mode

### ISSUE THREAD

**Issue by kimoppalfens** [PSAppDeployToolkit/PSAppDeployToolkit#469]
Hi, I am testing PSAppDeployToolkit with Windows Defender Application control.

The following line in execute-process fails.
$stdOutBuilder = New-Object -TypeName 'System.Text.StringBuilder' -ArgumentList ''
I replaced it with
$stdOutBuilder = New-Object -TypeName 'System.Text.StringBuilder' -ArgumentList [String]::Empty

See error message below.
[01-01-2020 20:20:00.032] [Installation] [Execute-Process] :: Function failed, setting exit code to [60002].
Error Record:
-------------

Message        : Cannot validate argument on parameter 'ArgumentList'. Cannot process input. The argument "System.Object[]" is not trusted.
InnerException : System.Management.Automation.ValidationMetadataException: Cannot process input. The argument "System.Object[]" is not
                 trusted.
                    at System.Management.Automation.ValidateTrustedDataAttribute.Validate(Object arguments, EngineIntrinsics
                 engineIntrinsics)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter,
                 CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)

FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.NewObjectCommand
ScriptStackTrace      : at Execute-Process<Process>, C:\Users\kim.oppalfens\Downloads\Putty\AppDeployToolkit\AppDeployToolkitMain.ps1: line
                        2776
                        at Execute-MSI<Process>, C:\Users\kim.oppalfens\Downloads\Putty\AppDeployToolkit\AppDeployToolkitMain.ps1: line 2363
                        at <ScriptBlock>, C:\Users\kim.oppalfens\Downloads\Putty\Deploy-Application.ps1: line 140
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\Users\kim.oppalfens\Downloads\Putty\AppDeployToolkit\AppDeployToolkitMain.ps1:2776 char:85
                  + ... r = New-Object -TypeName 'System.Text.StringBuilder' -ArgumentList ''
                  +                                                                        ~~

Error Inner Exception(s):
-------------------------

Message        : Cannot process input. The argument "System.Object[]" is not trusted.
InnerException :

**Comment by luki1412** [comment]
Constrained Language mode is not supported as it disables critical parts of the toolkit. For example Add-Type is not allowed, which is responsible for loading modules for example Windows Forms/WPF.

You need to add scripts to your approved scripts so they run in Full Language mode.
