### ISSUE TITLE
PSADT v3.6.4 nitpicks

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#47]
Hi Mo,

1-In AppDeployToolkitMain.ps1, the "Zero-Config MSI installation" section wants to write logs (line 
8815) right after it's been disabled in line 8806. Why?

2-If using "CompressedLogs" and installing with SCCM, the Zipped log files created are not readable by regular users. The created ZIP file does not inherit the folder permissions. The workaround I did in my private fork was copy the ZIP file to the folder, delete original, and rename the copy to the original name. This worked fine until my package created big log files. The .CopyHere method is slow because it insists on showing an animated GUI and returns control to the script before it finishes. So we end up with a race condition. My File-perm workaround copies the zip file in mid-creation. So I have to either create another band-aid to wait for the ZIP file to stop growing or bring-in an external ZIP utility like 7zip. (What would you recommend?)

3-If using "CompressedLogs", there are no examples in Deploy-Application.ps1 of how to force log files of Setup.EXE to the $logTempFolder folder. Here are some:

		# Launch EXE from the "\Files" sub-directory
		# Launch InstallShield Setup.exe. Force log files to the logging folder
		#Execute-Process -Path "setup.exe" -Parameters "-s -f2`"$configToolkitLogDir\$installName.log`""
		# Launch InstallShield Setup.exe (MSIs inside). Force log files to the logging folder
		#Execute-Process -Path "setup.exe" -Parameters "/s /v`"ALLUSERS=1 /qn /L* \`"$configToolkitLogDir\$installName.log\`""

FYI: I'm slated to package some apps with VERY-old installers, I'll send up the Deploy-Application.ps1 for those once I'm done.

**Comment by mmashwani** [comment]
1) Logging is disabled because all of the variables required for creating a log file are not defined at this point in time. The Write-Log lines are still able to display the messages to the console if you are troubleshooting something with that portion of the code so those Write-Log lines are still useful.

2) I will have to investigate this a bit more.

3) I will add these examples.

**Comment by That-Annoying-Guy** [comment]
Hi Mo!
RE: 2) I have solve it with the following:


	## Compress the log files and remove the temporary folder
	If ($configToolkitCompressLogs) {
		Try {
			#  Add the file header for zip files to a file and create a 0 byte .zip file
			Set-Content -Path $zipFileName -Value ('PK' + [char]5 + [char]6 + ("$([char]0)" * 18)) -ErrorAction 'Stop'
			
			$zipFile = $shellApp.NameSpace($zipFileName)
			#The following only works if source folder has ONE file.
			#When .CopyHere method adds the 2nd (and Nth) file, the perms on the ZIP file are fubar'd
			#and you get a GUI error message about permissions (b/c .CopyHere is a GUI thing)
			#ForEach ($file in (Get-ChildItem -Path $logTempFolder -ErrorAction 'Stop')) {
			#	Write-Log -Message "Compress log file [$($file.Name)] to [$zipFileName]..." -Source ${CmdletName}
			#	$zipFile.CopyHere($file.FullName)
			#	Start-Sleep -Milliseconds 500
			#}

			#Solution: http://powershell.org/wp/forums/topic/missing-file-permission-after-creating-zip-file/feed/
			#workAround: Give it an ARRAY of files and call .CopyHere ONCE
			#$ArrOfFilesToBackUp = (new-object -com shell.application).NameSpace($logTempFolder)
			$ArrOfFilesToBackUp = $shellApp.NameSpace($logTempFolder)
			$ZipFile.CopyHere($ArrOfFilesToBackUp.Items())
			Write-TempLog " Waiting to Compress $($ArrOfFilesToBackUp.count) files to $ZipFileName"

			#The .CopyHere method is slow b/c it wants to show animated GUI before Zipping.
			#It opens the Zip file everytime it adds a file so checking if the ZIp is Locked Open is not reliable
			#We must watch the Size of the zip file and wait for it to stop growing.
			[Int32]$OldZipSize = $oFile.Length #in bytes
			[int]$MaxLoops	= 8
			[Int]$LoopNum	= 0
			do {
				Start-Sleep -Milliseconds 200
				$oFile = New-Object System.IO.FileInfo $zipFileName
				$LoopNum++
				[Int32]$ZipSize = $oFile.Length #in bytes
				If ( $ZipSize -gt $OldZipSize) {
					[Int32]$OldZipSize= $ZipSize
					Write-TempLog "Zip file Growing...[Loop# $LoopNum]"
					$LoopNum=0
				}
				Remove-Variable oFile -ErrorAction SilentlyContinue #Make sure we don't get a stale file handle
			} until ($LoopNum -gt $MaxLoops)
			Write-TempLog "$zipFileName has stopped growing"			
			
			Start-Sleep -Milliseconds 1000 #Extra delay, JIC
			
			#ISSUE: .CopyHere method creates Zipped log files that is only readable if elevated, users cannot read.(Zip Icon has padlock, too)
			Write-TempLog "Fix Perms of the created ZIP file by copying Parent folder's perms"
			$oACL_to_clone_from = Get-Acl "C:\Admutils\Logs\Install"
			Set-Acl -Path $zipFileName -AclObject $oACL_to_clone_from  #Yes! you can copy perms from the parent folder!

			If (Test-Path -Path $logTempFolder -PathType Container -ErrorAction 'Stop') {
				Remove-Item -Path $logTempFolder -Recurse -Force -ErrorAction 'Stop' | Out-Null
			}
		}
		Catch {
			Write-Log -Message "Failed to compress the log file(s). `n$(Resolve-Error)" -Severity 3 -Source ${CmdletName}
		}
		
	}
	


It not as sexy as using 7Zip's public domain LZMA .CS file but works for now and is a lot less work.
Going with the 7zip EXE was creating sub-directories inside the ZIP files so it's still work but more baggage.

**Comment by mmashwani** [comment]
I have added the extra examples to the Execute-Process function and also updated the zip file compression option to fix the above reported issue. Please test and let me know if it's working as expected.

**Comment by That-Annoying-Guy** [comment]
It works good.
Thank you!

I'm surprised that switching Write-TempLog to Write-Log doesn't break anything.  The messages don't show in the logs but that's ok with me. (That's b/c the log(s) have already been compressed by that point)


BTW: In the docs, it should explain more of what you can do with this. (Proposed changes below in [  ] )

CompressLogs (option in AppDeployToolkitConfig.xml) - One of the Toolkit Options in the AppDeployToolkitConfig.xml file is CompressLogs. Enabling this option will create a temporary logging folder where [the toolkit will] save all of the log files you want [to one] single ZIP file[.] [From inside Deploy-Application.ps1 you can also copy other log files from non-MSI installers to the temporary folder and they too will be part of the ZIP file. The log files inside the ZIP file will be intact and you'll keep the history of installation attempts. ]


To enable the CompressLogs, set the follow option in AppDeployToolkitConfig.xml to True:
<Toolkit_CompressLogs>True</Toolkit_CompressLogs>
When set to True, the following happens:
•	Both toolkit and MSI logs are temporally placed in $envTemp\$installName which gets cleaned up at the end of the install.
•	At the end of the install / uninstall, the logs are compressed into a new zip file which is placed in the LogFolder location in the config file.
•	The Zip file name indicates whether it is an Install / Uninstall and has the timestamp in the filename so previous logs do not get overwritten.[ (e.g. PS_AppDeployToolkitMain_3.6.5_EN_01_Install_2015-07-03-03-48-26.zip) ]
•	If your package creates other log files, you can send them to the temporary logging FOLDER at $envTemp\$installName.
