### ISSUE TITLE
Show-InstallationWelcome does not show name of product being installed if CloseApps is used

### ISSUE THREAD

**Issue by MarcD2K20** [PSAppDeployToolkit/PSAppDeployToolkit#470]
In AppDeployToolkitMain.ps1, lines 6432 - 6438 the code prevents the name of the product being displayed in the dialog if CloseApps is specified, which is confusing for the end-user if the application is deployed to them as "Required" via SCCM.

## Initial form layout: Close Applications / Allow Deferral
If ($showCloseApps) {
	$labelAppNameText = $configClosePromptMessage
}
ElseIf (($showDefer) -or ($forceCountdown)) {
	$labelAppNameText = "$configDeferPromptWelcomeMessage `n$installTitle"
}

Changing line 6434 to the following, fixes this issue. (The escape characters are messing it up a bit, but you get the idea)

$labelAppNameText = "$configDeferPromptWelcomeMessage `n$installTitle`n`n$configClosePromptMessage"

**Comment by MarcD2K20** [comment]
changing this now shows the deferpromptwelcomemessage when uninstalling the software as well, so it doesn't work perfectly doing it the way I did and there's probably a far more elegant way to fix this.

**Comment by luki1412** [comment]
Will be fixed in the next release.
