### ISSUE TITLE
$envUserDesktop unavailable when deploying as System through Intune

### ISSUE THREAD

**Issue by Ellestad1995** [PSAppDeployToolkit/PSAppDeployToolkit#476]
I'm deploying a program with Intune.
As part of the installation phase I need to create a shortcut on the Desktop. The "Program" doesn't have an installer itself. 

In Intune the Install behavior is 'System', since I'm deploying it to "Program Files". The user on the system doesn't have Administrator privileges and can't write to certain directories. 

The problem is that the variable $envUserDesktop is empty.
The logs show that $envUserDesktop is empty. 
During the install PSAppDeployToolkit do recognize the active logged in user. Meaning it should be possible to get the Desktop location I believe. 
It's probably correct that $envUserDesktop is empty since it gets it from the current user, which is System and doesn't have a Desktop. 

Would it be an idea to get similar variables for the active logged in user?

Is there a recommended way to get the active user Desktop location in these situations?

Edit:
It seems that other programs are setting shortcuts to "$envCommonDesktop". Is this the recommended way?

**Comment by luki1412** [comment]
No $envUserDesktop targets currents user desktop, which is SYSTEM under SCCM and InTune.
$envCommonDesktop for shortcuts that are for allusers. For a specified user you can either loop through $envSystemDrive\Users and then add \Desktop\shortcut.lnk path to it and remove the shortcut or target just the active user's desktop "$envSystemDrive\Users\$($RunAsActiveUser.UserName)\Desktop\shotcut.lnk".
