### ISSUE TITLE
Sometimes fails to run interactively even when forcing the option

### ISSUE THREAD

**Issue by ajfrcc** [PSAppDeployToolkit/PSAppDeployToolkit#48]
I am using the PSADT to deploy Java via SCCM, prompting users to close browsers.  If I set it to install as required in SCCM with a deadline, and set it to run weather or not a user is logged in, but window set to normal, not hidden, if the deadline hits, the installation goes, force closing the browsed.  If the user triggers it out of Software Center before the deadline, it will run interactively as expected.  I can get the logs and commands being run tomorrow at work, but I wanted to log the issue now while it was still on my mind.

Using PSADT version 3.6.4 on Windows 7 Enterprise x64, client and software deployment managed by SCCM 2012 R2 SP1.

Thanks for an awesome tool!
-Anthony

**Comment by mmashwani** [comment]
If your install is running under the SYSTEM account, it will not display interactively unless you  use something like ServiceUI.exe to force the install to run in a user session.

**Comment by ajfrcc** [comment]
I have the deployment types configured to install for system, whether or not a user is logged in, with normal visibility.  When it appears in Software Center, and the logged in user manually triggers it to install, it runs interactively as expected.  When it hits the deadline and mandatory installs, it is still visible, but the log shows it not running interactive, even when forcing the -Interactive option in PSADT.

**Comment by mmashwani** [comment]
I'm not sure what you mean by this line. You will need to be more explicit and provide the detailed log entries that match up with your statements so I can see what is going on.

**Comment by dersonc** [comment]
Include the last version of PSExec.exe and the 32 bit version of ServiceUI.exe in the same folder as your Deploy-Application.exe.

Then create Install.bat on the same location:
```
PSExec.exe -si -accepteula %cd%\ServiceUI.exe %cd%\Deploy-Application.exe
```

And create Uninstall.bat on the same location:
```
PSExec.exe -si -accepteula %cd%\ServiceUI.exe %cd%\Deploy-Application.exe Uninstall
```

Setup your CM object like this:
![cm-psappdeploy](https://cloud.githubusercontent.com/assets/12057635/8504524/e9a950bc-2198-11e5-9acd-4cfcdd4af8c4.png)

The package should now display the user interface anytime a user is logged on even if you set it to run whether or not a user is logged on with normal visibility.

**Comment by ajfrcc** [comment]
This is getting closer, but now an "Interactive Services Detection" window pops up as well, and when I click to view the message, it takes me to the ServiceUI window.

**Comment by dersonc** [comment]
Use the following settings for user experience:
![cmue](https://cloud.githubusercontent.com/assets/12057635/8558301/e39077d6-24c8-11e5-9db6-2e7a85a0db60.png)

**Comment by ajfrcc** [comment]
I am closing this issue, I ended up using an SCCM global condition to run a small PowerShell script to detect if any users are logged in, and made extra deployment types.
