### ISSUE TITLE
Test-PowerPoint does not check Windows 10 presentation mode

### ISSUE THREAD

**Issue by modernuser2017** [PSAppDeployToolkit/PSAppDeployToolkit#481]
I just tested the new version of the AppDeployToolkit. While testing I found a bug in the Test-PowerPoint function. PowerPoint in fullscreen mode is detected quite well but as the comments in the function suggest, I expected that the presentation mode that can be enabled in mobility center on notebooks would also be detected as presentation mode but that's not the case. Could you please add a check of the presentation mode to the function? I found out that the following registry keys need to be checked:

HKEY_CURRENT_USER\Software\Microsoft\MobilePC\AdaptableSettings\Activity Wert Activity: 0 means off, 1 means on and
HKEY_CURRENT_USER\Software\Microsoft\MobilePC\AdaptableSettings\Activity\1 Wert CountTransient: 0 means off, 1 means on

Thanks in advance.

**Comment by mjr4077au** [comment]
Better late than never, right? This has been added in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/5f3d79e9b5251130eb944a727dc3f2e25907b694.
