### ISSUE TITLE
Remove-MSIApplications ignores AllowRebootPassThru

### ISSUE THREAD

**Issue by pilgi3** [PSAppDeployToolkit/PSAppDeployToolkit#489]
I uninstall vmware tools with this powershell command
`Remove-MSIApplications -Name "VMware Tools" -Exact`

Works fine and get back exit code "3010" but will be ignored?!
![image](https://user-images.githubusercontent.com/44865075/80593360-6027db00-8a21-11ea-802f-a49190fcc936.png)

My uninstall command
`"Deploy-Application.exe" -DeploymentType "Uninstall" -DeployMode "Silent" -AllowRebootPassThru`
I also have tried
`"Deploy-Application.exe" -DeploymentType "Uninstall" -DeployMode "NonInteractive" -AllowRebootPassThru`

Install the application works fine.
`Execute-Process -Path "setup.exe" -Parameters "/S /v ""/qn /l*v ""$LogFilePath\VMwareTools_$appVersion.log"" ADDLOCAL=ALL REMOVE=Hgfs,VMCI,AppDefense,FileIntrospection,NetworkIntrospection REBOOT=R"`

My install command
`"Deploy-Application.exe" -AllowRebootPassThru`

**Comment by macxcool** [comment]
That's working as intended, I think. The exit code is ignored by the script (i.e. the script doesn't act on it), but passed on to whatever's launching the script. Usually this is SCCM, which will then take action based on the exit code.

**Comment by pilgi3** [comment]
But why there is no reboot pending. I set this in the user experience tab
![image](https://user-images.githubusercontent.com/44865075/80600458-b77f7880-8a2c-11ea-8055-8b2f35f3a98b.png)

Installation logfile
![image](https://user-images.githubusercontent.com/44865075/80600649-04fbe580-8a2d-11ea-8f35-e5f5c065afe4.png)

**Comment by macxcool** [comment]
Now you're asking for support for SCCM. This isn't an SCCM support forum.
However, what you've shown there should the default setting for Deployment Types in SCCM/MECM and SCCM should schedule a reboot. If you have further questions, ask on an SCCM forum like https://forums.prajwaldesai.com/forums/configuration-manager.4/

**Comment by pilgi3** [comment]
I am a SCCM technician, so i know what this settings does.
In my opinion the problem is the remove-msiapplication command start up the msiexec and get back the exit code 3010. 
The script ignore this and at the end of the script give back 0.
When you look at the install logfile the last line contains 3010. 
In the uninstall logfile the last line contains 0.

**Comment by pilgi3** [comment]
When i remove -AllowRebootPassThru at the install command this happens
![image](https://user-images.githubusercontent.com/44865075/80609926-fca9a780-8a38-11ea-903d-0e7051f00a60.png)

Looks like similar as the uninstall.

**Comment by luki1412** [comment]
The toolkit turns success exit codes with reboot into regular success exit codes.
-AllowRebootPassThru prevents that, allowing the toolkit to return the true exit code.

This parameter is not handled by Remove-MSIApplications in any way.
Exit-Script handles it based on exit codes.

**Comment by paulwetter** [comment]
So, it sounds like it is returning a 3010 when it should (-AllowRebootPassThru) a 0 when it should (no -AllowRebootPassThru).
have you looked at your AppEnforce.log client side in CM?

**Comment by pilgi3** [comment]
Yes i have checked the AppEnforce.log
Install entries
![image](https://user-images.githubusercontent.com/44865075/80678512-50f56b80-8abb-11ea-9306-752f3ae18401.png)

Uninstall entries
![image](https://user-images.githubusercontent.com/44865075/80678701-bf3a2e00-8abb-11ea-8cb6-bfcc26eee24d.png)

**Comment by pilgi3** [comment]
I tried with the MSI product code and the command Execute-MSI commandlet
`Execute-MSI -Action "Uninstall" -Path "{BA27AC44-2E23-4291-8894-87E93A19B753}"`

Exitcode was not ignored and passthru successful
![image](https://user-images.githubusercontent.com/44865075/80679775-d7ab4800-8abd-11ea-9559-5f344d9e10d5.png)

I have to check the product key every new version so it would be awesome if it works with Remove-MSIApplications!

**Comment by pilgi3** [comment]
> The toolkit turns success exit codes with reboot into regular success exit codes.
> -AllowRebootPassThru prevents that, allowing the toolkit to return the true exit code.
> 
> This parameter is not handled by Remove-MSIApplications in any way.
> Exit-Script handles it based on exit codes.

May it is possible in future release that the commandlet "Remove-MSIApplications" could handle this?

**Comment by luki1412** [comment]
> > The toolkit turns success exit codes with reboot into regular success exit codes.
> > -AllowRebootPassThru prevents that, allowing the toolkit to return the true exit code.
> > This parameter is not handled by Remove-MSIApplications in any way.
> > Exit-Script handles it based on exit codes.
> 
> @luki1412
> May it is possible in future release that the commandlet "Remove-MSIApplications" could handle this?

Which version of the toolkit are you using? Also, remember that msiexec only returns 3010 when needed(unless instructed to do every time), usually because it cant remove a file because it is in use.
It will return 0 if it can do what it needs.

**Comment by pilgi3** [comment]
> > > The toolkit turns success exit codes with reboot into regular success exit codes.
> > > -AllowRebootPassThru prevents that, allowing the toolkit to return the true exit code.
> > > This parameter is not handled by Remove-MSIApplications in any way.
> > > Exit-Script handles it based on exit codes.
> > 
> > 
> > @luki1412
> > May it is possible in future release that the commandlet "Remove-MSIApplications" could handle this?
> 
> Which version of the toolkit are you using? Also, remember that msiexec only returns 3010 when needed(unless instructed to do every time), usually because it cant remove a file because it is in use.
> It will return 0 if it can do what it needs.

We are using the version 3.8.1.
I clearly understand but you can see in the logfile we get back 3010 but the script ignores the Exitcode.
As i mentioned earlier the behavior is as expected with the comandlet "Execute-MSI -Action Uninstall".
The msiexec command is the same whether I use "Remove-MSIApplications" or "Execute-MSI" now (logfile).

**Comment by paulwetter** [comment]
Try this:

`Remove-MSIApplications -Name "VMware Tools" -Exact -ContinueOnError $false`

Looks like Remove-MSIApplications has -ContinueOnError set to true which then passes all the way through Execute-MSI to the Execute-Process that will ignore exit codes if ContinueOnError (bool) is true.  This makes sense in a way that you want to blanket "attempt/best effort" remove an app with Remove-MSIApplications.

Execute-Process and Execute-MSI by default has the ContinueOnError set to false.

**Comment by pilgi3** [comment]
@paulwetter Thanks for your tip, now it works as it should!
![image](https://user-images.githubusercontent.com/44865075/80938777-a8a51700-8dda-11ea-8f5e-dbcea1eb2676.png)
