### ISSUE TITLE
New-Folder function ignores $LogWriteToHost

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#49]
If you try to suppress the console from coming up with <Toolkit_LogWriteToHost>False</Toolkit_LogWriteToHost>

The New-Folder function does not handle $configToolkitLogWriteToHost

Therefore if you run:
    New-Folder -Path "C:\Temp\MyNewFolder"

You'll see the console come up to show this:

    Directory: C:\Temp

    Mode                LastWriteTime     Length Name                                                                              
    ----                -------------     ------ ----                                                                              
    d----        17/06/2015  12:25 PM            MyNewFolder  

I changed this line:

    New-Item -Path $Path -ItemType Directory -ErrorAction 'Stop'

to this:

    New-Item -Path $Path -ItemType Directory -ErrorAction 'Stop' > $null

and it no longer shows the console:

**Comment by mmashwani** [comment]
Fixed this in the latest beta.
