### ISSUE TITLE
Get-UICulture issue

### ISSUE THREAD

**Issue by Robert-LTH** [PSAppDeployToolkit/PSAppDeployToolkit#492]
https://github.com/dotnet/runtime/issues/35638

When running Get-UICulture as SYSTEM you end up with the user Culture instead of the UICulture.

In my env i get sv-SE instead of expected en-US.

A workaround would be to read the NLS UI language from registry until the fix has been implemented in dotnet.

**Comment by Robert-LTH** [comment]
The issue in dotnet has been fixed in version 5 but i dont know if that will be fixed in 4.8.
5.0 is set to release in november this year according to https://devblogs.microsoft.com/dotnet/introducing-net-5/

**Comment by luki1412** [comment]
Thank you for the bug report Robert-LTH. We cannot wait until NF v5 is released due the toolkit supporting NF 3.5 - PS 2 for toolkit version 3. We need to implement a solution compatible with NF 3.5.

**Comment by luki1412** [comment]
I tried it in a vm and I'm getting the correct culture info, unless the info from control panel is incorrect also. Can you please tell me how to replicate and test this?

![NLS](https://user-images.githubusercontent.com/20016096/82561333-7d108380-9b73-11ea-928e-3e15fe0f3552.png)

**Comment by Robert-LTH** [comment]
It has been a while since I got asked about this but the other day we discussed this in our group and it looks like Microsoft has fixed the issue.
