### ISSUE TITLE
Need small changes in Deploy-Application_v1r1.ps1 RE: $mainExitCode

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#50]
Hi Mo,
In my private fork I do Log file rotation and compression.
If anything bad happens, I need to exit gracefully with an exitcode but NO logging. So I can't use Exit-Script.
I do a Throw but set the exitcode somehow and I've figured out how to do this by using $mainExitCode just before I do the Throw.

For it to work, Deploy-Application_v1r1.ps1 would need to have a small change:

	Catch {
		[int32]$mainExitCode = 60008
		Write-Error -Message "Module [$moduleAppDeployToolkitMain] failed to load: `n$($_.Exception.Message)`n `n$($_.InvocationInfo.PositionMessage)" -ErrorAction 'Continue'
		Exit $mainExitCode
	}

to

	Catch {
		If ($mainExitCode -eq 0){ [int32]$mainExitCode = 60008 } # To make $mainExitCode from Log Handling come out
		Write-Error -Message "Module [$moduleAppDeployToolkitMain] failed to load: `n$($_.Exception.Message)`n `n$($_.InvocationInfo.PositionMessage)" -ErrorAction 'Continue'
		Exit $mainExitCode
	}

One thing I'm not sure though, is if I need to change the scope of $mainExitCode. IOW:

	[int32]$mainExitCode = 0

becomes:

	[int32]$Global:mainExitCode = 0

Are you keen to add these changes?

**Comment by mmashwani** [comment]
Included the suggested changes in the latest beta. It is not necessary to make the variable scope global. The variable is currently in script scope and that should work fine.

**Comment by That-Annoying-Guy** [comment]
Thank you Mo!
