### ISSUE TITLE
Commit 3b7b883 breaks the way applications that spawn multiple processes are closed

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#502]
**Describe the bug**
After commit 3b7b883, unable to close applications that spawns multiple processes (i.e: Firefox.exe,, iexplore.exe)

**To Reproduce**
- Open FF and/or IE 
- Add this in your install section : 
`Show-InstallationWelcome -CloseApps 'iexplore,firefox,MicrosoftEdge' -BlockExecution -CloseAppsCountdown 300 -AllowDeferCloseApps -DeferTimes 3 -CheckDiskSpace -PersistPrompt`
- Run and wait for the pop-up asking you to close processes
- Use the close processes button, IE and FF won't close.

**Toolkit Version:**
3.8.2

**Comment by luki1412** [comment]
This function's process closing function needs to be reworked.

**Comment by luki1412** [comment]
This will be resolved in the next version.
