### ISSUE TITLE
-BlockedExecution pop-up does not show due to Powershell Constrained Language Mode

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#504]
**Describe the bug**
The Pop-up telling the end user that the application he's trying to launch is blocked is not showing on machines where Powershell [constrained language](https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/) mode is on

**To Reproduce**
1. Create a test pkg and configure Show-InstallationWelcome to block some apps and use the -BlockExecution parameter
2. Start one app to show the "close apps" pop-up and launch your package
3. Close App pop-up shows, close your app to allow the package install
4. Wait until you see the "installing ..." pop-up and start your blocked app
5. The pop-up telling you that your app is blocked is not showing as it should

**Toolkit Version:**
any

**Additional context**
I did some debugging on this. It appears that the AppDeployToolkit_BlockAppExecutionMessage.vbs is started as it should. It starts the main script with -ShowBlockedAppDialog -AsyncToolkitLaunch etc. but the script fails with some error and nothing gets displayed.

This is related to the context : when you put the Debugger Value in the IFEO key, the commandline is started without elevation. Now if you start two Cmd prompts, one as administrator and one without elevation, if you enter the full script invocation command line in both prompts (powershell.exe -executionpolicy bypass -nologo -noprofil -file "C:\Windows\Temp\AppDeployToolkitMain.ps1" -ShowBlockedAppDialog -AsyncToolkitLaunch -ReferredInstallTile "Test Pkg 1.0.0") then you will get the pop-up when started as admin, and you will get a powershell error related to dot sourcing forbidden as started without elevation.

**Comment by luki1412** [comment]
Constrained Language Mode will probably never be supported due to it blocking Add-Type, COM objects, dot sourcing and other code. Just Add-Type is used for loading assemblies for the UI.

**Comment by Sulquendi** [comment]
In this case, PSADT is working all the way on machines were the Constrained Language Mode policy is on, provided it is running as localsystem or elevation, except the "your app is blocked" pop-up that runs in user mode. So i came up with a fix involving the VBS : displaying a MsgBox instead of starting AppDeployToolKitMain.ps1.

**Comment by luki1412** [comment]
Depending on what is enabling Constrained Language Mode, you can add exceptions. Some of them exclude some folders by default.
