### ISSUE TITLE
In Version 3.8.2 the AppDeployToolkitConfig.xml is UTF-8 encoded and not UTF-8-BOM which leads to display errors.

### ISSUE THREAD

**Issue by Belial2003** [PSAppDeployToolkit/PSAppDeployToolkit#509]
**Describe the bug**
The encoding for AppDeployToolkitConfig.xml was correct in version 3.8.1.
UTF-8 leads to wrongly displayed characters (e.g. in German) for the Show-InstallationWelcome Screen

**Screenshots**
![displaybug](https://user-images.githubusercontent.com/60741123/82416283-0f346100-9a7a-11ea-8d92-6dd558584815.png)

**Toolkit Version:**
3.8.2

**Comment by luki1412** [comment]
Thank you for the report. We are already aware of the issue and a fix has been implemented. Will be available in the next version.
