### ISSUE TITLE
In Windows 10 Enterprise with the Korean Language Pack, XML files aren't imported using UTF-8, but rather ANSII

### ISSUE THREAD

**Issue by HighMans** [PSAppDeployToolkit/PSAppDeployToolkit#510]
**Describe the bug**
We have machines over in korea that are running the korean language pack and they are bombing out when importing the AppDeploymentToolkitConfig.xml. It looks like they're importing the XML files as ANSII which causes some of the characters to be "<" messing up the tags.

Error in Korean: 

    **File Location**\Deploy-	Application.ps1 : Module [**File Location**\AppDeployToolkitMain.ps1] fail
	ed to load:
	값 "System.Object[]"을(를) "System.Xml.XmlDocument" 유형으로 변환할 수 없습니다. 오류: "줄 430, 위	치 4의 'RestartPrompt
	_ButtonRestartLater' 시작 태그가 'UI_Messages_JA'의 끝 태그와 일치하지 않습니다. 줄 432, 위치 4"
Erorr in English:

	*File Location**\Deploy-Application.ps1 : Module [**File Location**\AppDeployToolkitMain.ps1] failed to load:
	The value "System.Object []" cannot be converted to type "System.Xml.XmlDocument". Error: 	"RestartPrompt at line 430, position 4
	Start tag _ButtonRestartLater 'does not match end tag of' UI_Messages_JA '. Row 432, position 4 "

**To Reproduce**
1. Launch PowershellAppDeployment in a machine with the Korean Language Locale

**Toolkit Version:**
[e.g. 3.8.3]

**Additional context**
The fix for me was to add "-encode utf8" to the get-content for the xml file.

Line 254 in AppDeployToolkitMain.ps1:
`[Xml.XmlDocument]$xmlConfigFile = Get-Content -LiteralPath $AppDeployConfigFile`

to

`[Xml.XmlDocument]$xmlConfigFile = Get-Content -LiteralPath $AppDeployConfigFile -Encoding UTF8`

**Comment by luki1412** [comment]
Hello, its not just Korean language. We are aware of the issue. It will get fixed in the next release.
