### ISSUE TITLE
Repair Functionality Addition

### ISSUE THREAD

**Issue by Sri-Boddupalli** [PSAppDeployToolkit/PSAppDeployToolkit#511]
**Is your feature request related to a problem? Please describe.**
In my organization we need to repair couple of applications when necessary(Mostly after the patch Tuesday for Legacy applications). We deploy applications via SCCM and usually we make them available to users and they run Install/uninstall from Software Center. Most of our packagers use PSADT as the default standard. But When repair is needed we have to create a separate package all together and deploy it to users. 

**Describe the solution you'd like**
-Single command just like Install and Uninstall
Deloy-Application.exe Repair 

-Add Repair function inside the Deploy-Application.ps1
If we can add Pre-Repair/Repair/Post-Repair function and separate dedicated section along with Pre-Install/Install/Post-Install and Pre-Uninstall/Uninstall/Post-Uninstall which we have already in PSADT that would be very helpful.

**Describe alternatives you've considered**
We create our own repair scripts and deploy then to users via SCCM. 

**Additional context**

**Comment by luki1412** [comment]
Hello, Repair mode was added in release: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases/tag/3.8.1

Are you using an outdated toolkit version?

**Comment by Sri-Boddupalli** [comment]
Thank you @luki1412 . 

Just verified our internal prod repo and Yes looks like we are still using Toolkit 3.7. My first action tomorrow is update our prod toolkit. Appreciate it,
