### ISSUE TITLE
Return Process Id from Execute-Process when -PassThru is specified

### ISSUE THREAD

**Issue by iainbrighton** [PSAppDeployToolkit/PSAppDeployToolkit#513]
**Describe the solution you'd like**
When launching `Execute-Process` with `-NoWait -PassThru` parameters, it would be beneficial to have visibility of the process that is launched so that it can be monitored or waited upon later during the install script. Adding the process Id (PID) to the $ExecutionResults object returned would enable this.

**Additional context**
The Citrix Receiver/Workspace App requires the mouse to be moved during the USB component installation. Having the ability to start the install process and programmatically move the mouse cursor until the process has exited would be possible with this addition.

I'm happy to submit a PR for this if the general consensus is that this is a worthwhile addition.

Thanks,
Iain

**Comment by luki1412** [comment]
I agree. Some people might decide to check on process' progress after it has been started with -NoWait
