### ISSUE TITLE
Import error AppDeployToolkitMain.ps1

### ISSUE THREAD

**Issue by pilgi3** [PSAppDeployToolkit/PSAppDeployToolkit#517]
**Describe the bug**
We want to install an application and get an error before it starts (6008).

**To Reproduce**
1. Open PowerShell and navigate to path ...\AppDeployToolkit
2. Type "ipmo .\AppDeployToolkitMain.ps1"

**Screenshots**
![image](https://user-images.githubusercontent.com/44865075/83640893-1183d880-a5ad-11ea-9cbd-8391280bd985.png)

**Toolkit Version:**
[e.g. 3.8.2]

**Additional context**
This happens on Windows 10 1909, but not on all devices.
We tried on this devices previous version and there is no issue.
What could be the reason for the error message?

**Comment by SCHEFFRA** [comment]
Try to open the AppDeployToolkitConfig.xml in a XML editor. You should see an error within the japanees UI localization. Check the XML syntax. Did you use a "<" or ">" within some cutsome text that may destroy XML structure?

**Comment by luki1412** [comment]
This should get fixed by https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/500
The encoding of the xml file was changed. You can either download the latest build from github or use previous version.

**Comment by pilgi3** [comment]
So we know about a fix, we will wait for the version 3.8.3 yet!
