### ISSUE TITLE
$envOSVersion variable assignment missing

### ISSUE THREAD

**Issue by biloumaxou** [PSAppDeployToolkit/PSAppDeployToolkit#520]
On AppDeployToolkitMain.ps1, line 170, $envOSVersion variable assignment is missing in else bloc.

current line:
If ($envOSVersionRevision) { [string]$envOSVersion = "$($envOSVersion.ToString()).$envOSVersionRevision" } Else { "$($envOSVersion.ToString())" }

What I proposed:
If ($envOSVersionRevision) { [string]$envOSVersion = "$($envOSVersion.ToString()).$envOSVersionRevision" } Else { **[string]$envOSVersion =** "$($envOSVersion.ToString())" }

best regards,

**Comment by luki1412** [comment]
Thank you for the report. Will be fixed in the next version.
