### ISSUE TITLE
Removing not empty folders with -disablerecursion

### ISSUE THREAD

**Issue by psour** [PSAppDeployToolkit/PSAppDeployToolkit#529]
**Describe the bug**
If you want to delete a folder without recursion, you end up with a challenge response from remove-item if the folder contains subfolder/s. 

**To Reproduce**
New-Folder C:\Test
New-Folder C:\Test\Folder
Remove-Folder -Path 'C:\Test' -DisableRecursion

**Toolkit Version:**
3.8.1

Added pull request:
[https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/530](url)

**Comment by luki1412** [comment]
The thing is this is not necessarily a bug. It's more about what you want the code to do when it finds a non empty folder inside a folder you told it to remove without recursion. It can either error out or just ignore the folder and continue removing files and empty folders.
