### ISSUE TITLE
Pop-Up for MSI error codes during UI Installation

### ISSUE THREAD

**Issue by bm109591** [PSAppDeployToolkit/PSAppDeployToolkit#53]
Hi Team, 

Could you Please help to get Pop-Up message boxes for MSI error codes during normal installation? 

I tried to modify the AppDeployToolkitConfig.xml by adding the below content, but installation is not happened. 
"" 

Please do needful. Thanks in advance 

Regards, 
Bala

**Comment by mmashwani** [comment]
I don't understand what you're asking above.

**Comment by bm109591** [comment]
Hi Mashwani, 

Need to get the error prompts if the application fails to install during non silent installation. 
Ex: If the msi returns the error exit code as 1623 the should get the pop-up message as Fatal error during installation.

Thank you!

**Comment by mmashwani** [comment]
This is the issues log for the toolkit. I don't understand what you are trying to report. Is there a bug in the toolkit you want fixed? I need some details. All you have given me is a vague description of what you would like to happen. If you need a pop-up message to display an error message, then the toolkit and PowerShell have features available that allow you to do this already in your own personal scripts. This is not something I will add to the toolkit by default.

**Comment by bm109591** [comment]
This is not about toolkit but at all.

Need syntax for displaying message boxes for MSI error codes are occurred during basic installation.

**Comment by bm109591** [comment]
Is it possible to get error with help of  "Get-MsiExitCodeMessage -MsiErrorCode 1618"?

**Comment by mmashwani** [comment]
Yes, that will give you the description for exit code 1618. Then you can display it to the user if you wish.

**Comment by bm109591** [comment]
Thanks Mashwani  for prompt response :)

is it possible to get prompts for other unknown errors?

**Comment by mmashwani** [comment]
This will translate Windows error codes to their description:
```
function Resolve-Win32Error {
  param(
    [Parameter(Mandatory=$true, ValueFromPipeline=$true)]
    [ValidateScript({$_.GetType().Name -eq 'Int32'})]
    [Int32]$ErrorCode
  )
  
  return (New-Object ComponentModel.Win32Exception($ErrorCode)).Message
}
```
