### ISSUE TITLE
Problem with Get-PendingReboot

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#533]
Get-PendingReboot needs very long time

![Pending](https://user-images.githubusercontent.com/16757493/87642356-b1568980-c749-11ea-894c-bae41c5d6180.PNG)
![Pending2](https://user-images.githubusercontent.com/16757493/87642358-b1ef2000-c749-11ea-8613-4e5f0a1c1891.PNG)

**Comment by cyborgrd** [comment]
The problem exists also if the value is empty or not exists

**Comment by luki1412** [comment]
How long are we talking about?

**Comment by cyborgrd** [comment]
I found the problem. It was my computer. The sccm client was suspended, this part of script

[psobject]$SCCMClientRebootStatus = Invoke-WmiMethod -ComputerName $ComputerName -NameSpace 'ROOT\CCM\ClientSDK' -Class 'CCM_ClientUtilities' -Name 'DetermineIfRebootPending' -ErrorAction 'Stop'

hang.

May be we should build a pre check.

How to verifiy this problem: suspend the ccm.exe with process explorer, and try Get-PendingReboot

**Comment by luki1412** [comment]
Well if it takes just as long to check then there might be no point in implementing it.
That is why I asked you how long did it take for you.

**Comment by cyborgrd** [comment]
I started, an next day it was still not done. I think if the sccm agent is suspended it wil never ends

**Comment by luki1412** [comment]
I think you mean ccmexec.exe. Also why would it be suspended? If you suspend it yourself, then that isn't really something people have to deal with. Almost any process can be suspended. A sleeping process obviously won't respond to these requests.
