### ISSUE TITLE
Get-MsiTableProperty function cannot handle duplicate Properties in $TableProperties

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#54]
Installing an MSI with Transform.
It installs OK (exitcode = 0) 
But PSADT v3.6.4 decides to probe the MSI for its Property table.
For some reason it finds duplicate properties in the Table ( caused by the Transform?) and blows-up.
This shows up on the screen but not in the log file:
![get-msitableproperties-error2](https://cloud.githubusercontent.com/assets/12900014/8419001/b7b2d48c-1e84-11e5-9932-35727f5f93f0.png)

The key part is the orange rectangle I put on the print-screen. It translates to:
Add-Member : Impossible to add a member named << dotnettextbox >> because a member of this name already exists. If you are certain to want to replace the existing member, use the Force parameter.

The chunk of code it references it line 7046 in the current master for function "Function Get-MsiTableProperty"

Here is the chuck below:

			While ($Record) {
				#  Add property and value to custom object
				$TableProperties | Add-Member -MemberType 'NoteProperty' -Name (& $GetProperty -Object $Record -PropertyName 'StringData' -ArgumentList @(1)) -Value (& $GetProperty -Object $Record -PropertyName 'StringData' -ArgumentList @(2))
				#  Retrieve the next row in the table
				[__comobject]$Record = & $InvokeMethod -Object $View -MethodName 'Fetch'
			}

I'll add the -Force parameter to Add-Member and get back to you.

**Comment by That-Annoying-Guy** [comment]
The -Force parameter did the trick. no more red text.

Turns out the error happened when it was about to install the second MSI.
Both MSIs have transforms and are launched from the same Deploy-Application_v1r1.ps1 script.
It was trying to get the 2nd MSI's PRODUCTCODE property. 

Without the -Force parameter, it still got the product code but it tripped on that dotnettextbox property.

Add the -Force parameter and this issue is done.

			While ($Record) {
				#  Add property and value to custom object
				$TableProperties | Add-Member -MemberType NoteProperty -Name (& $GetProperty -Object $Record -PropertyName 'StringData' -ArgumentList @(1)) -Value (& $GetProperty -Object $Record -PropertyName 'StringData' -ArgumentList @(2)) -Force
				#  Retrieve the next row in the table
				[__comobject]$Record = & $InvokeMethod -Object $View -MethodName 'Fetch'
			}

**Comment by mmashwani** [comment]
This issue has been resolved in the latest beta.
