### ISSUE TITLE
Issue with AppDeployToolkitConfig.xml

### ISSUE THREAD

**Issue by lemers00** [PSAppDeployToolkit/PSAppDeployToolkit#541]
**Describe the bug**
We are deploying a package silently. Only in China, Korea, Japan are we getting error code 60008 on all devices. 

**To Reproduce**
I ran the Deploy-Application.ps1 manually in ISE on a machine in China and I see the error below.
I have tried changing this line in AppDeployToolkitConfig.xml , even though it is running silently.
<InstallationUI_LanguageOverride>EN</InstallationUI_LanguageOverride>

**Screenshots**
This is the error:
![image](https://user-images.githubusercontent.com/69167782/89219699-249f2e80-d585-11ea-960a-b51d15dddc99.png)

**Toolkit Version:**
[e.g. 3.8.1]
3.8.2
**Additional context**

**Comment by luki1412** [comment]
Could you try this: https://discourse.psappdeploytoolkit.com/t/special-characters-in-gui/2729/3
