### ISSUE TITLE
Remove-MSIApplications -SecureParameters

### ISSUE THREAD

**Issue by Katzuki2001** [PSAppDeployToolkit/PSAppDeployToolkit#542]
**Is your feature request related to a problem? Please describe.**
I am having issues with a program called Heimdal Thor Agent, when I uninstall it, I need to feed it a password, but the program during installation updates itself to another version than the one I am installing. (The company only lets me download older versions that auto update themselves during installation). I cannot use the original MSI file to uninstall, and I have no way of really knowing which version it has installed and there for do not have the GUID of the software. 

**Describe the solution you'd like**
I would like to have the -SecureParameters added to Remove-MSIApplications, so that i can use that to feed the password to the uninstallation process.

**Describe alternatives you've considered**
I would have to make an entirely new function to do pretty much exactly what Remove-MSIApplications does from scratch

**Additional context**
None

**Comment by mjr4077au** [comment]
This has been added to v4 (function is now called `Uninstall-ADTApplication`).
