### ISSUE TITLE
Explorer Process stopping during when installing msi app

### ISSUE THREAD

**Issue by twahab** [PSAppDeployToolkit/PSAppDeployToolkit#543]
Explorer.exe process is terminated when installing an msi.  Package finishes installing but the user has to hit cntrl+Alt+del or taskmgr.exe to start explorer.exe.  We are using version 3.8.2 of the PSAD.  

**Toolkit Version:**
3.8.2

I believe it could be coming from this step but wanted to see if anyone encountered this issue before if there is a workaround we can implement to prevent the explorer.exe process from terminating.

[Pre-Installation] :: Refresh the Desktop and the Windows Explorer environment process block.	Update-Desktop	8/6/2020 3:50:42 PM	16600 (0x40D8)

thanks

**Comment by cyborgrd** [comment]
Try to install with property MSIRESTARTMANAGERCONTROL=Disable

**Comment by luki1412** [comment]
Refresh-Desktop doesn't terminate any process. It only sends messages to desktop so refreshes.

**Comment by twahab** [comment]
thanks for the updates, I will try with the arg MSIRESTARTMANAGERCONTROL=Disable and report back, below is the initial part of the log, just wanted to provide more input

[Initialization] :: *******************************************************************************	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: *******************************************************************************	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: [LiteraCorp._LiteraMetadact_4.7.0.140_EN_01] setup started.	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: Script [C:\WINDOWS\ccmcache\ed\AppDeployToolkit\AppDeployToolkitMain.ps1] dot-source invoked by [C:\WINDOWS\ccmcache\ed\Deploy-Application.ps1]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: Script [C:\WINDOWS\ccmcache\ed\AppDeployToolkit\AppDeployToolkitExtensions.ps1] dot-source invoked by [C:\WINDOWS\ccmcache\ed\AppDeployToolkit\AppDeployToolkitMain.ps1]	PSAppDeployToolkitExt	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: [LiteraCorp._LiteraMetadact_4.7.0.140_EN_01] script version is [1.0.0]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: [Deploy Application] script version is [3.6.8]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: The following non-default parameters were passed to [Deploy Application]: [-DeploymentType "Install"]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: [App Deploy Toolkit Main] script version is [3.8.2]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: [App Deploy Toolkit Extensions] version is [3.8.2]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: Computer Name is ]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: Current User is [NT AUTHORITY\SYSTEM]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: OS Version is [Microsoft Windows 10 Enterprise 64-bit 10.0.18363.959]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: OS Type is [Workstation]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: Current Culture is [en-US], language is [EN] and UI language is [EN]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: Hardware Platform is [Physical]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: PowerShell Host is [ConsoleHost] with version [5.1.18362.752]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: PowerShell Version is [5.1.18362.752 x64]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: PowerShell CLR (.NET) version is [4.0.30319.42000]	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: *******************************************************************************	PSAppDeployToolkit	8/6/2020 3:50:22 PM	16600 (0x40D8)
[Initialization] :: Display session information for all logged on users: 
SessionId           : 2
SessionName         : RDP-Tcp#2
ConnectState        : Active
IsCurrentSession    : True
IsConsoleSession    : False
IsActiveUserSession : True
IsUserSession       : True
IsRdpSession        : True
IsLocalAdmin        : False
LogonTime           : 8/6/2020 8:19:35 AM
IdleTime            : 00:00:22.3574814
DisconnectTime      : 8/6/2020 2:19:54 PM
ClientProtocolType  : RDP
ClientDirectory     : C:\WINDOWS\system32\mstscax.dll
ClientBuildNumber   : 18362



	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: The following users are logged on to the system:	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: Current process is running with user account [NT AUTHORITY\SYSTEM] under logged in user session for [SMRH\dhein].	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: There is no console user logged in (user with control of physical monitor, keyboard, and mouse).	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: The active logged on user is .	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: The active logged on user  has a primary UI language of [EN].	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: The following UI messages were imported from the config XML file: [UI_Messages_EN].	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: The active logged on user  has a DPI scale factor of [125] with DPI pixels [120].	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: Unable to load COM Object [Microsoft.SMS.TSEnvironment]. Therefore, script is not currently running from a SCCM Task Sequence.	PSAppDeployToolkit	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: Service [EventSystem] exists.	Test-ServiceExists	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: Get the service [EventSystem] startup mode.	Get-ServiceStartMode	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: Service [EventSystem] startup mode is set to [Automatic].	Get-ServiceStartMode	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: Get the service object for service [EventSystem].	Start-ServiceAndDependencies	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: Service [EventSystem] with display name [COM+ Event System] has a status of [Running].	Start-ServiceAndDependencies	8/6/2020 3:50:23 PM	16600 (0x40D8)
[Initialization] :: Service [RpcSs] exists.	Test-ServiceExists	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Get the service [RpcSs] startup mode.	Get-ServiceStartMode	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Service [RpcSs] startup mode is set to [Automatic].	Get-ServiceStartMode	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Get the service object for service [RpcSs].	Start-ServiceAndDependencies	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Service [RpcSs] with display name [Remote Procedure Call (RPC)] has a status of [Running].	Start-ServiceAndDependencies	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Service [EventLog] exists.	Test-ServiceExists	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Get the service [EventLog] startup mode.	Get-ServiceStartMode	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Service [EventLog] startup mode is set to [Automatic].	Get-ServiceStartMode	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Get the service object for service [EventLog].	Start-ServiceAndDependencies	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Service [EventLog] with display name [Windows Event Log] has a status of [Running].	Start-ServiceAndDependencies	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Service [Schedule] exists.	Test-ServiceExists	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Get the service [Schedule] startup mode.	Get-ServiceStartMode	8/6/2020 3:50:24 PM	16600 (0x40D8)
[Initialization] :: Service [Schedule] startup mode is set to [Automatic].	Get-ServiceStartMode	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Initialization] :: Get the service object for service [Schedule].	Start-ServiceAndDependencies	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Initialization] :: Service [Schedule] with display name [Task Scheduler] has a status of [Running].	Start-ServiceAndDependencies	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Initialization] :: The task scheduler service is in a healthy state: True.	PSAppDeployToolkit	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Initialization] :: Session 0 detected, process running in user interactive mode, user(s) logged in.	PSAppDeployToolkit	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Initialization] :: Installation is running in [Interactive] mode.	PSAppDeployToolkit	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Initialization] :: Deployment type is [Installation].	PSAppDeployToolkit	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Evaluate disk space requirements.	Show-InstallationWelcome	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Retrieve free disk space for drive [C:].	Get-FreeDiskSpace	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Free disk space for drive [C:]: [41117 MB].	Get-FreeDiskSpace	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Successfully passed minimum disk space requirement check.	Show-InstallationWelcome	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Check for running application(s) [outlook,winword,excel,thinclient,lcp_main]...	Get-RunningProcesses	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Application(s) are not running.	Get-RunningProcesses	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Check if PowerPoint is in either fullscreen slideshow mode or presentation mode...	Test-PowerPoint	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: PowerPoint application is not running.	Test-PowerPoint	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: PowerPoint is running in fullscreen mode [False].	Test-PowerPoint	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Display balloon tip notification with message [Installation started.].	Show-BalloonTip	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Spin up progress dialog in a separate thread with message: [Litera Metadact 4.7 Installation in Progress...].	Show-InstallationProgress	8/6/2020 3:50:25 PM	16600 (0x40D8)
[Pre-Installation] :: Get information for installed Application Name(s) [Paynegroup Metadata Assistant]...	Get-InstalledApplication	8/6/2020 3:50:26 PM	16600 (0x40D8)
[Pre-Installation] :: Skipped 3 entries while searching, because they were considered Microsoft updates.	Get-InstalledApplication	8/6/2020 3:50:26 PM	16600 (0x40D8)
[Pre-Installation] :: Found no application based on the supplied parameters.	Get-InstalledApplication	8/6/2020 3:50:26 PM	16600 (0x40D8)
[Pre-Installation] :: Found [0] application(s) that matched the specified criteria [Paynegroup Metadata Assistant].	Remove-MSIApplications	8/6/2020 3:50:26 PM	16600 (0x40D8)
[Pre-Installation] :: No applications found for removal. Continue...	Remove-MSIApplications	8/6/2020 3:50:26 PM	16600 (0x40D8)
[Pre-Installation] :: Get information for installed Application Name(s) [Litera Metadact-e]...	Get-InstalledApplication	8/6/2020 3:50:26 PM	16600 (0x40D8)
[Pre-Installation] :: Skipped 3 entries while searching, because they were considered Microsoft updates.	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Found no application based on the supplied parameters.	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Found [0] application(s) that matched the specified criteria [Litera Metadact-e].	Remove-MSIApplications	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: No applications found for removal. Continue...	Remove-MSIApplications	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Get information for installed Application Name(s) [Litera Metadact]...	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Found installed application [Litera Metadact] version [4.7.0.140] using contains matching for search term [Litera Metadact].	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Skipped 3 entries while searching, because they were considered Microsoft updates.	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Found [1] application(s) that matched the specified criteria [Litera Metadact].	Remove-MSIApplications	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Adding application to list for removal: [Litera Metadact ].	Remove-MSIApplications	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Remove application [Litera Metadact ].	Remove-MSIApplications	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Resolve product code to a publisher, application name, and version.	Execute-MSI	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Get information for installed Product Code [{4970FD97-D366-4597-BA8B-D6754A1A84F9}]...	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Found installed application [Litera Metadact] version [4.7.0.140] matching product code [{4970FD97-D366-4597-BA8B-D6754A1A84F9}].	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Skipped 3 entries while searching, because they were considered Microsoft updates.	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Get information for installed Product Code [{4970FD97-D366-4597-BA8B-D6754A1A84F9}]...	Get-InstalledApplication	8/6/2020 3:50:27 PM	16600 (0x40D8)
[Pre-Installation] :: Found installed application [Litera Metadact] version [4.7.0.140] matching product code [{4970FD97-D366-4597-BA8B-D6754A1A84F9}].	Get-InstalledApplication	8/6/2020 3:50:28 PM	16600 (0x40D8)
[Pre-Installation] :: Skipped 3 entries while searching, because they were considered Microsoft updates.	Get-InstalledApplication	8/6/2020 3:50:28 PM	16600 (0x40D8)
[Pre-Installation] :: Executing MSI action [Uninstall]...	Execute-MSI	8/6/2020 3:50:28 PM	16600 (0x40D8)
[Pre-Installation] :: [msiexec.exe] successfully resolved to fully qualified path [C:\WINDOWS\system32\msiexec.exe].	Execute-Process	8/6/2020 3:50:28 PM	16600 (0x40D8)
[Pre-Installation] :: Check to see if mutex [Global\_MSIExecute] is available. Wait up to [10 minute(s)] for the mutex to become available.	Test-IsMutexAvailable	8/6/2020 3:50:28 PM	16600 (0x40D8)
[Pre-Installation] :: Mutex [Global\_MSIExecute] is available for an exclusive lock.	Test-IsMutexAvailable	8/6/2020 3:50:28 PM	16600 (0x40D8)
[Pre-Installation] :: Working Directory is [C:\WINDOWS\system32].	Execute-Process	8/6/2020 3:50:29 PM	16600 (0x40D8)
[Pre-Installation] :: Executing [C:\WINDOWS\system32\msiexec.exe /x "{4970FD97-D366-4597-BA8B-D6754A1A84F9}" REBOOT=ReallySuppress /QN /L*v "C:\Users\Public\SMRH\Logs\Software\LiteraCorp._LiteraMetadact_4.7.0.140_Uninstall.log"]...	Execute-Process	8/6/2020 3:50:29 PM	16600 (0x40D8)
[Pre-Installation] :: Execution completed successfully with exit code [0].	Execute-Process	8/6/2020 3:50:42 PM	16600 (0x40D8)
[Pre-Installation] :: Refresh the Desktop and the Windows Explorer environment process block.	Update-Desktop	8/6/2020 3:50:42 PM	16600 (0x40D8)
[Installation] :: Read data from Windows Installer database file [C:\WINDOWS\ccmcache\ed\Files\Metadact.msi] in table [Property].	Get-MsiTableProperty	8/6/2020 3:50:42 PM	16600 (0x40D8)
[Installation] :: Get information for installed Product Code [{4970FD97-D366-4597-BA8B-D6754A1A84F9}]...	Get-InstalledApplication	8/6/2020 3:50:43 PM	16600 (0x40D8)
[Installation] :: Skipped 3 entries while searching, because they were considered Microsoft updates.	Get-InstalledApplication	8/6/2020 3:50:43 PM	16600 (0x40D8)
[Installation] :: Found no application based on the supplied parameters.	Get-InstalledApplication	8/6/2020 3:50:43 PM	16600 (0x40D8)
[Installation] :: Executing MSI action [Install]...	Execute-MSI	8/6/2020 3:50:43 PM	16600 (0x40D8)
[Installation] :: [msiexec.exe] successfully resolved to fully qualified path [C:\WINDOWS\system32\msiexec.exe].	Execute-Process	8/6/2020 3:50:43 PM	16600 (0x40D8)
[Installation] :: Check to see if mutex [Global\_MSIExecute] is available. Wait up to [10 minute(s)] for the mutex to become available.	Test-IsMutexAvailable	8/6/2020 3:50:43 PM	16600 (0x40D8)
[Installation] :: Mutex [Global\_MSIExecute] is available for an exclusive lock.	Test-IsMutexAvailable	8/6/2020 3:50:43 PM	16600 (0x40D8)
[Installation] :: Working Directory is [C:\WINDOWS\ccmcache\ed\Files].	Execute-Process	8/6/2020 3:50:44 PM	16600 (0x40D8)
[Installation] :: Executing [C:\WINDOWS\system32\msiexec.exe /i "C:\WINDOWS\ccmcache\ed\Files\Metadact.msi" /norestart /QN /L*v "C:\Users\Public\SMRH\Logs\Software\Metadact_Install.log"]...	Execute-Process	8/6/2020 3:50:44 PM	16600 (0x40D8)
[Installation] :: Execution completed successfully with exit code [0].	Execute-Process	8/6/2020 3:51:08 PM	[Installation] :: Refresh the Desktop and the Windows Explorer environment process block.	Update-Desktop	8/6/2020 3:51:08 PM	16600 (0x40D8)
