### ISSUE TITLE
Can't access https://discourse.psappdeploytoolkit.com

### ISSUE THREAD

**Issue by bahnjee** [PSAppDeployToolkit/PSAppDeployToolkit#544]
I'd ask in the PSAppDeployToolkit Community but that's what won't load for me.  The main site (psappdeploytoolkit.com) comes up just fine, but the Community (discourse.psappdeploytoolkit.com) pages will not load.  No error...not even a timeout message...the page will just spin and spin and never load.  NOTE:  This is only on our business network; connecting from anywhere else works just fine.  So I know it's something that our overly-security-minded IT Director has blocked.  I just don't know what to ask him to lighten up on.

In case it helps figure this out, our IT Director has blocked any site not located in the US.  I see psappdeploytoolkit.com is hosted by Cloudflare; perhaps it's their discourse tools you're using and perhaps it's located outside the US?

Thanks to anyone who might point me in the right direction.

**Comment by cybermoloch** [comment]
To help though, the IP is with Hurricane Electric and is in the US. Maybe they are also blocking "social media" and anything with "discourse" in the domain or URL is being blocked.

You will have to take it up with your IT Director and good luck. (Maybe ask for an exception for IT?)
