### ISSUE TITLE
Toolkit variables can be replaced by functions causing problems

### ISSUE THREAD

**Issue by cybermoloch** [PSAppDeployToolkit/PSAppDeployToolkit#550]
Toolkit variables declared in `AppDeployToolkitMain.ps1` can be overridden by custom functions (even by accident.)

All variables should be declared as `ReadOnly` or `Constant` -- ReadOnly would be easier as we can -Force in the main script to update them but would prevent accidental overrides by custom functions. If a user REALLY wants to override, they can with `-Force`,

As per dev discussion:
1. ReadOnly or Constant?
2. Splatting or vanilla for `Set-Variable`?

Non-splat version makes the script VERY hard to read.

Regex fixes:
Find: `\[(.*)\]\$(.*(\S))\s*= (.*)\n`
Normal-Replace: `Set-Variable -Name '$2' -Value ( ($4) -as [$1]) -Option ReadOnly -Force\n`
Splat-Replace: `\n$$$2Params = @{\n    Name = '$2'\n    Value = ( ($4) -as [$1] )\n}\nSet-Variable @$2Params -Option ReadOnly -Force\n`

**Comment by mjr4077au** [comment]
This has been address with the v4 re-architecture.
