### ISSUE TITLE
Hook into switching of phases

### ISSUE THREAD

**Issue by Robert-LTH** [PSAppDeployToolkit/PSAppDeployToolkit#551]
**Is your feature request related to a problem? Please describe.**
I want to be able to execute code from an extension at certain points in the script. 

**Describe the solution you'd like**
I would like a command like:
Register-PhaseScriptblock -Phase 'Start-Preinstallation' -Scripblock { Write-Log "Executing at the start of Preinstallation" }
Register-PhaseScriptblock -Phase 'End-Preinstallation' -Scripblock { Write-Log "Executing at the end of Preinstallation" }
Register-PhaseScriptblock -Phase 'End-script' -Scripblock { Write-Log "Executing at the end of Deploy-Application.ps1" }

**Describe alternatives you've considered**
I have considered altering the Deploy-Application.ps1 but it makes it harder to implement extensions.

**Additional context**

**Comment by mjr4077au** [comment]
The upcoming v4 release has callback hooks for injecting commands that can run. It won't accept scriptblocks, but it will accept any CommandInfo object (i.e. a defined function's CommandInfo as can be obtained via `Get-Command -Name '<<FunctionName>>'`).
