### ISSUE TITLE
Powershell Application Toolkit - Run a command after you defer

### ISSUE THREAD

**Issue by rvelthuis1965** [PSAppDeployToolkit/PSAppDeployToolkit#552]
If you use the defer function is it possible to run something before it defers ? I’d like to create a log on my server that shows me when someone defers just to keep track of install status. The log would just show the computer name and the defer number.

**Comment by mjr4077au** [comment]
Resolved via discussed fix in #551. It's now possible in the upcoming v4 release to add callbacks when an ADTSession opens/closes, where you can do what you're asking for.
