### ISSUE TITLE
dot-source invoked by error

### ISSUE THREAD

**Issue by Gordy-7** [PSAppDeployToolkit/PSAppDeployToolkit#554]
**Describe the bug**
Updated the PSDT to the latest. tested an application we have already packaged using the previous version. The application will no longer install when testing via the PSDT tool.

**To Reproduce**
Steps to reproduce the behaviour:
1. cmd prompt as admin. 
2. psexec -i -s cmd.exe (to mirror system i.e. sccm).
3. cd to where content is located i.e. c:\packages\app1
4. run: deploy-application.exe install interactive

**Screenshots**
we receive the following log error:

[Initialization] :: Script [C:\packages\app1\AppDeployToolkit\AppDeployToolkitMain.ps1] dot-source invoked by [C:\packages\app1\Deploy-Application.ps1]

**Toolkit Version:**
[e.g. 3.8.3]

**Additional context**
We have updated our tool in the past with no issues.

**Comment by luki1412** [comment]
What powershell version are you running it on?

**Comment by Gordy-7** [comment]
Hi,

5.1.17763.1007

**Comment by luki1412** [comment]
So you have been using 3.8.1 and now you are trying out 3.8.2. Is that correct?

**Comment by Gordy-7** [comment]
Thats correct.

Basically, we update every time there is a new release.

Our previous deployment scripts work fine when we update the files (AppDeployToolkit and its contents and the deploy.exe's) before its only v3.8.2 where i have seen this issue.

**Comment by luki1412** [comment]
This is probably related to: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/517
