### ISSUE TITLE
Execute-ProcessAsUser is not working with last commit

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#557]
Execute-ProcessAsUser fails 

[Post-Installation] :: Error Record:
-------------

Message        : Cannot validate argument on parameter 'Path'. The "Test-Path $_" validation script for the argument 
                 with value 
                 "C:\Users\Public\KPMG\PSAppDeployToolkit\ExecuteAsUser\PSAppDeployToolkit-ExecuteAsUser.vbs" did not 
                 return a result of True. Determine why the validation script failed, and then try the command again.
InnerException : System.Management.Automation.ValidationMetadataException: The "Test-Path $_" validation script for 
                 the argument with value 
                 "C:\Users\Public\KPMG\PSAppDeployToolkit\ExecuteAsUser\PSAppDeployToolkit-ExecuteAsUser.vbs" did not 
                 return a result of True. Determine why the validation script failed, and then try the command again.
                    at System.Management.Automation.ValidateScriptAttribute.ValidateElement(Object element)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal 
                 parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)

FullyQualifiedErrorId : ParameterArgumentValidationError,Set-Permission
ScriptStackTrace      : at Execute-ProcessAsUser<Process>, 
                        \\defr4srv42\Work\_test\AppDeployToolkit\AppDeployToolkitMain.ps1: line 5162
                        at <ScriptBlock>, \\defr4srv42\Work\_test\TestVendor_TestApp_8.0_x86.ps1: line 336
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At \\defr4srv42\Work\_test\AppDeployToolkit\AppDeployToolkitMain.ps1:5162 char:24
                  + ... et-Permission -Path "$executeAsUserTempPath\$schTaskName.vbs" -User $ ...
                  +                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error Inner Exception(s):
-------------------------

Message        : The "Test-Path $_" validation script for the argument with value 
                 "C:\Users\Public\KPMG\PSAppDeployToolkit\ExecuteAsUser\PSAppDeployToolkit-ExecuteAsUser.vbs" did not 
                 return a result of True. Determine why the validation script failed, and then try the command again.
InnerException : 

![executeasuiser](https://user-images.githubusercontent.com/16757493/93881339-0e893100-fcdf-11ea-8131-0ddba74ebdd0.JPG)

**Comment by luki1412** [comment]
Thanks for the report.

**Comment by luki1412** [comment]
Fixed by #559
