### ISSUE TITLE
Gap missing in message window

### ISSUE THREAD

**Issue by NordicAT** [PSAppDeployToolkit/PSAppDeployToolkit#566]
**Describe the bug**
When using the cmdlet "Show-InstallationPrompt" to display a short text in v.3.8.3, the gap between the header and the icon is missing:

![GUI-v3 8 3-show](https://user-images.githubusercontent.com/42859522/94904057-024d6280-049b-11eb-9690-8faffea33c0a.png)

Not a big issue, but this does not look OK to me during testing the new toolkit compared to previous versions.
Maybe a little padding of ~5 px should be added to the top and to the bottom.
<br/>  

**To Reproduce**

Add the following code-line to "Deploy-Application.ps1":
`Show-InstallationPrompt -Message "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam." -ButtonRightText "OK" -Icon Information -NoWait`

Running the script should bring up the message-window.
<br/>  

**Screenshots**
Display message in v.3.8.3:
![GUI-v3 8 3](https://user-images.githubusercontent.com/42859522/94903602-5572e580-049a-11eb-84ab-00d483403b5e.png)

Display message in v.3.8.0:
![GUI-v3 8 0](https://user-images.githubusercontent.com/42859522/94903652-6885b580-049a-11eb-9f4f-f26b2d65cf20.png)
<br/>  

**Toolkit Version:**
3.8.3

**Powershell Version:**
5.1

**Additional context**
none

**Comment by luki1412** [comment]
It scales with text now. I guess we could make the base size a little bit bigger in the next update.

**Comment by NordicAT** [comment]
Hi @luki1412 - Thank you!
