### ISSUE TITLE
NO LOGFILE is created, when running two PSADTK-packages one after another in PowerShell ISE

### ISSUE THREAD

**Issue by NordicAT** [PSAppDeployToolkit/PSAppDeployToolkit#567]
**Describe the bug**
NO LOGFILE is created for the second package, when running two PSADTK-packages one after another in PowerShell ISE.
Have a look at the video below for more details ...

It is not a big issue, but caught my attention, while converting my packages to the latest version.
Restarting the PS ISE does fix this of course.
<br>

**To Reproduce**
1. Prepare two PSADTK-packages for testing
2. Open the "Deploy-Application.ps1" of the first package in PowerShell ISE and run it
3. Verify that a logfile has been created
4. Open the "Deploy-Application.ps1" of the second package in PowerShell ISE and run it.
5. Verify that **NO LOGFILE** has been created!?
<br>

**Screenshots**
![LogFileMissing](https://user-images.githubusercontent.com/42859522/95000155-b4ca1600-05be-11eb-9633-0ab79afbfb8d.gif)
<br>

**Toolkit Version:**
Tested with 3.8.0 and 3.8.3
<br>

**Powershell Version:**
5.1 (Tested on Windows Server 2019)
<br>

**Additional context**
None

**Comment by luki1412** [comment]
The issue here is that the variable that is used for log name is only changed if its empty. Since you are running two scripts, the name is created in the first one and reused in the second one. This is a bug. Thanks for reporting.

**Comment by NordicAT** [comment]
@luki1412 Thank you very much for investigating! :pray:
