### ISSUE TITLE
UI timeout value not working in v3.8.3

### ISSUE THREAD

**Issue by d2bromwi** [PSAppDeployToolkit/PSAppDeployToolkit#568]
If I change 'InstallationUI_Timeout' in 'AppDeployToolkitConfig.xml' to 10 seconds, the install ignores it.

The line in the Deploy-Application.ps1 file is:
Show-InstallationWelcome -CloseApps 'notepad' -CloseAppsCountdown 5 -AllowDeferCloseApps -DeferTimes 3

I've tested in the previous 5 versions of PSADT and all work as expected (i.e. exits after 10 seconds if no response).

NB - I lowered the above values to test different scenarios and capture all the screenshots.

**Comment by luki1412** [comment]
I don't recall there being any changes to the function's logic in the last update.

**Comment by enternoescape** [comment]
I observed the same issue with Show-InstallationPrompt and determined that $formInstallationPrompt.DialogResult is left on None when $buttonAbort.PerformClick() is executed. I was able to work around the issue by adding $formInstallationPrompt.DialogResult = 'Abort' before $buttonAbort.PerformClick() changing the code from:

$timer.Add_Tick({
Write-Log -Message 'Installation action not taken within a reasonable amount of time.' -Source ${CmdletName}            
$buttonAbort.PerformClick()
})

to

$timer.Add_Tick({
Write-Log -Message 'Installation action not taken within a reasonable amount of time.' -Source ${CmdletName}            
$formInstallationPrompt.DialogResult = 'Abort'
$buttonAbort.PerformClick()
})

This workaround gets things working correctly, but it doesn't explain why is suddenly broke.

**Comment by RorySRut** [comment]
I am seeing the same thing with Show-InstallationPrompt in version 3.8.3.  Dialog does not time out.  It just keeps writing 'Installation action not taken within a reasonable amount of time.' in the log file.  You have to click a button.  Version 3.8.1 works fine.  Would like to see 'abort' returned to the calling script when the dialog times out though.

**Comment by RorySRut** [comment]
In the Show-InstallationPrompt function, rem out the line '$buttonAbort.Visible = $false' in the Button Abort area.  Then Show-InstallationPrompt works as expected.  I have not looked at ShowInstallation-Welcome yet.

## Button Abort (Hidden)
		$buttonAbort.DataBindings.DefaultDataSourceUpdateMode = 0
		$buttonAbort.Name = 'buttonAbort'
		$buttonAbort.Size = '1,1'
		$buttonAbort.DialogResult = 'Abort'
		$buttonAbort.TabStop = $false
		## $buttonAbort.Visible = $false
		$buttonAbort.UseVisualStyleBackColor = $true
        $buttonAbort.Location = "0,0"
		$buttonAbort.add_Click($buttonAbort_OnClick)

**Comment by RorySRut** [comment]
Also just fixed Show-InstallationPrompt so that it returns 'abort' when dialog times out and ExitOnTimeout is $false.  Add the line 'Write-Output -InputObject $result' to the 'Abort' switch at the end of the function.

Switch ($result) {
				'Yes' { Write-Output -InputObject $buttonRightText }
				'No' { Write-Output -InputObject $buttonLeftText }
				'Ignore' { Write-Output -InputObject $buttonMiddleText }
				'Abort' {
					# Restore minimized windows
					$null = $shellApp.UndoMinimizeAll()
					If ($ExitOnTimeout) {
						Exit-Script -ExitCode $configInstallationUIExitCode
					}
					Else {
						Write-Log -Message 'UI timed out but `$ExitOnTimeout set to `$false. Continue...' -Source ${CmdletName}
						Write-Output -InputObject $result
					}
				}
			}
