### ISSUE TITLE
 Fix issue where ActiveSetup HKCU keys are set when -ExecuteForCurrentUser parameter is set to False

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#570]
**Describe the bug**
The ActiveSetup keys are set in HKCU even when the ExecuteForCurrentUser parameter is set to False.
This results in the ActiveSetup never running for the Active User.

**To Reproduce**
`Set-ActiveSetup -StubExePath "..." -Description "..." -Key "..." -ExecuteForCurrentUser:$false`

**Toolkit Version:**
3.8.3

**Powershell Version:**
5.1

Fix
https://github.com/DennisVH/PSAppDeployToolkit/commit/82a5ea12e6990adf94389cd52da1b09180c9b316

**Comment by luki1412** [comment]
ExecuteForCurrentUser is there only for Execute-ProcessAsUser to not be executed under current user. It should still set active setup entries.
