### ISSUE TITLE
 Fix logging in Stop-ServiceAndDependencies function when stop of dependent services fails

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#571]
**Describe the bug**
correct logging (replace start with stop)

**Toolkit Version:**
3.8.3

**Powershell Version:**
5.1

Fix
https://github.com/DennisVH/PSAppDeployToolkit/commit/e43190d80ee4550dad83787b56e55c09da3ea20c

**Comment by luki1412** [comment]
You should be able to create PR for this. If not I'll do it.
