### ISSUE TITLE
Module AppDeployToolkitMain.ps1 failed to load

### ISSUE THREAD

**Issue by pilgi3** [PSAppDeployToolkit/PSAppDeployToolkit#572]
**Describe the bug**
Error 6008
```
Module [C:\Windows\ccmcache\1a\AppDeployToolkit\AppDeployToolkitMain.ps1] failed to load: 
You cannot call a method on a null-valued expression.
```
We try to install a application in user context with no admin rights via MEMCM.
The application will be downloaded in c:\windows\ccmcache.
To open CCMCACHE admin rights are necessary.

**To Reproduce**
1. Start PowerShell ISE and open the C:\Windows\ccmcache\1a\Deploy-Application.ps1
2. Click on 'Run Script'
3. See error in the powershell section
4. Toogle Breakpoint at row 100
5. Click on 'Run Script'
6. Read out the variable $moduleAppDeployToolkitMain

**Screenshots**
![image](https://user-images.githubusercontent.com/44865075/95977672-6ff17b00-0e19-11eb-9f83-09cb80eacf07.png)
![image](https://user-images.githubusercontent.com/44865075/95978541-9bc13080-0e1a-11eb-97e8-ab6bd462b1c0.png)

**Toolkit Version: 3.8.3**
We tested with the version 3.8.1 but did not work.
But with version 3.8.0 it works.

**Powershell Version: 5.1**

**Additional context**
Set <Toolkit_RequireAdmin>False</Toolkit_RequireAdmin> in the AppDeployToolkitConfig.xml
The variable $moduleAppDeployToolkitMain looks fine (screenshot.

**Comment by luki1412** [comment]
Your **$appArch** is commented out. Uncomment it.

**Comment by pilgi3** [comment]
Thank you very much! Now it works!
