### ISSUE TITLE
ActiveSetup for a logged in user is executed every time the installation is started

### ISSUE THREAD

**Issue by Oliver495** [PSAppDeployToolkit/PSAppDeployToolkit#579]
**Describe the bug**
ActiveSetup for a logged in user is executed every time the installation is started,
even the HKLM and HKCU Regkey (Version) has not changed.

**To Reproduce**
Set-ActiveSetup -StubExePath "$envProgramFilesX86\Mozilla Thunderbird\ActiveSetupThunderbird.ps1" `
                -Description 'das Kopieren Ihres Thunderbird Profils vor dem Update. Bitte warten...' `
                -Version '78,4,0,1.0'

1. Log in Windows
2. Start installation, the ActiveSetup runs and HKLM and HKCU is present -> ok
3. Start installation again, the ActiveSetup runs again.

The ActiveSetup-Regkey and especially the Version-Regkey is always the same.
I assume that the ActiveSetup should only run if the Version has changed.

Workaround: In my "ActiveSetupThunderbird.ps1" i check the "Version" Regkey from HKLM and HKCU. If it is the same, i quit my ps1.

**Toolkit Version:**
3.8.3

**Comment by luki1412** [comment]
This will be fixed in the next version. Thanks for reporting.
