### ISSUE TITLE
Error in function Execute-MSI and parameter ExitOnProcessFailure

### ISSUE THREAD

**Issue by ducke** [PSAppDeployToolkit/PSAppDeployToolkit#580]
**Describe the bug**

The ExitOnProcessFailure parameter does not work with `Execute-MSI`. If you set the parameter to `$false`, then this parameter will not be passed on to `Execute-Process` function.

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/5706e1eec6750ff4c1194589012b07b14ccbb274/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L2660

With `$false` the parameter is not added to the splatting object. Since the function `Execute-Process` sets the parameter to `$true` by default, 
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/5706e1eec6750ff4c1194589012b07b14ccbb274/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L3023
the function will always execute the `Exit-Script` in the event of an error. The same applies to all [Boolean] and [switch] parameters that are transferred to the `Execute-Process` function from `Execute-MSI`.

**To Reproduce**

`$ExecutionMsiResult = Execute-MSI -Action "Install" -Path "DummyMSI-1603.msi" -Transform "DummyMSI-1603.mst" -ExitOnProcessFailure $false -PassThru`

**Screenshots**

**Toolkit Version:**
Version of our toolkit you are using. 3.8.2

**Powershell Version:**
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Additional context**

**Comment by luki1412** [comment]
Switches should work because they are present or not present. If they are present we add them to the hashtable if they are not we dont, which means it wont be present in the parameter list for the function.

You are correct about booleans though. We can just remove the if statement in front of them to fix it, since they always have a default value.
