### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by scerazy** [PSAppDeployToolkit/PSAppDeployToolkit#583]
**My Question/Issue:**
PS E:\temp\visio> .\Deploy-Application.ps1
At E:\temp\visio\Deploy-Application.ps1:236 char:52
+ Show-DialogBox -Text $mainErrorMessage -Icon ‘Stop’
+ ~
The string is missing the terminator: ‘.
At E:\temp\visio\Deploy-Application.ps1:114 char:75
+ … deploymentType -ine ‘Uninstall’ -and $deploymentType -ine ‘Repair’) {
+ ~
Missing closing ‘}’ in statement block or type definition.
At E:\temp\visio\Deploy-Application.ps1:56 char:5
+ Try {
+ ~
Missing closing ‘}’ in statement block or type definition.
At E:\temp\visio\Deploy-Application.ps1:239 char:1
+
The Try statement is missing its Catch or Finally block.
+ CategoryInfo : ParserError: (:) [], ParseException
+ FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

**What I have tried so far:**
Googling the issue.

**Screenshots or additional details:**
Taskbar icon doesn't appear either.

**Comment by luki1412** [comment]
Seems like you have a typo in your script. Either a missing } or '. Without looking at the script in question, we can't really help you.

**Comment by scerazy** [comment]
The script is as downloaded with a couple of tiny changes for testing. Errors come from parts that did NOT get touched/changed

**Comment by luki1412** [comment]
We test the toolkit prior to release. Also, as you can see you are the only one currently saying the default script has broken code in it so this doesnt look like an error in the downloaded script but in the changes you've made.
