### ISSUE TITLE
When Deploying to Machine that is imaged with JA-JP culture PSADT will not execute and pass an error indicating an error with the xml

### ISSUE THREAD

**Issue by robhawk601** [PSAppDeployToolkit/PSAppDeployToolkit#587]
**Describe the bug**
When executing .\Deploy-Application.ps1 -DeploymentType 'Install' -deploymode 'Silent' on a machine that has been imaged in the JA-JP Culture PSADT will not execute and passed an error "System.Object[]" to type "System.Xml.XmlDocument". Error: "The 'RestartPrompt_ButtonRestartNow' start tag on line 431 position 4 does not match the end tag of 'UI_Messages_JA'. Line 432, position 4.

to get around the fix i have copied the xml from 3.8.0.

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/75047504/100287909-b534cb00-2fc9-11eb-9053-97d72d44955f.png)

**Toolkit Version:**
Version of our toolkit you are using. Found this is occurring in these versions 3.8.1, 3.8.2, 3.8.3

**Powershell Version:**
Windows 10 1909 and 5.1 version of powershell

**Additional context**

**Comment by robhawk601** [comment]
Also appears to be happening when a machine has been imaged in the zh-cn culture.
![image](https://user-images.githubusercontent.com/75047504/100556387-466fae80-32f6-11eb-97fa-7f4125e9335c.png)

**Comment by luki1412** [comment]
Just tested with Japanese and it works just fine.

![test1](https://user-images.githubusercontent.com/20016096/100729696-62905000-33c9-11eb-8529-31b8223e04b3.png)

**Comment by luki1412** [comment]
We have changed the encoding of the files to UTF8 with BOM. Please download the latest version of the toolkit.
