### ISSUE TITLE
New Feature: Re-launch toolkit as 64-bit (Intune)

### ISSUE THREAD

**Issue by seanlillis** [PSAppDeployToolkit/PSAppDeployToolkit#589]
Intune runs Win32 app installations as 32-bit on 64-bit systems, which means scripts don't write to the correct native registry hives.

Re-launching the toolkit as 64-bit if run in a 32-bit PowerShell process would be a useful feature, like in this example: https://z-nerd.com/blog/2020/03/31-intune-win32-apps-powershell-script-installer/

**Comment by mjr4077au** [comment]
@seanlillis are you still keen on such a feature? I'm personally not a fan as if I want to boot the toolkit up in x86 mode, I should be able to without the toolkit monkeying around on me. People should be using `%SystemRoot%\sysnative\WindowsPowerShell\v1.0\powershell.exe` if they require Intune to use the 64-bit interpreter.

**Comment by That-Annoying-Guy** [comment]
I have code that I put in the Front script to do this.
It forces 64bit and elevation but you can strip out the elevation part out.

**Comment by mjr4077au** [comment]
If you wanted to share it here, feel free to. The other reason why I don't think it's necessary is that the exe handles this for users anyway

**Comment by That-Annoying-Guy** [comment]
While I agree it might not be needed if you use the EXE.
Meanwhile at my day job, we don't use the (v3) EXE because we couldn't make it launch renamed front scripts.
We place this in all our front scripts before the AppDeployToolkitMain.ps1 even loads.

```
# Get the ID and security principal of the current user account
$myWindowsID = [System.Security.Principal.WindowsIdentity]::GetCurrent()
$myWindowsPrincipal = new-object System.Security.Principal.WindowsPrincipal($myWindowsID)

# Get the security principal for the Administrator role
$adminRole = [System.Security.Principal.WindowsBuiltInRole]::Administrator

[Boolean]$Is64BitProcess = [boolean]([IntPtr]::Size -eq 8)

# Check to see if we are currently running "as Administrator" *AND* running 64 bit
If (($myWindowsPrincipal.IsInRole($adminRole)) -and ($Is64BitProcess -eq $true)) {
	# We are running "as Administrator" - so change the title to indicate this
	$Host.UI.RawUI.WindowTitle = $myInvocation.MyCommand.Definition + " (Elevated+64bit) [$DeploymentType]"
	clear-host
} Else {
	If ($Is64BitProcess -eq $false) { Write-Host "NOT running 64Bit" -ForegroundColor Yellow }
	If (-not ($myWindowsPrincipal.IsInRole($adminRole))) { Write-Host "NOT running Elevated as Administrator" -ForegroundColor Yellow }
	Write-Host "Relaunching..." -ForegroundColor Yellow
	start-sleep -Seconds 4

	# Create a new process object that starts PowerShell
	If ($Is64BitProcess -eq $false) {
		Write-Host 'Launching [C:\Windows\sysnative\WindowsPowerShell\v1.0\PowerShell]'
		Start-Sleep -Seconds 2
		$ProcessStartInfo = new-object System.Diagnostics.ProcessStartInfo "C:\Windows\sysnative\WindowsPowerShell\v1.0\PowerShell";
	} Else {
		Write-Host 'Launching PowerShell with same bitness (64bit)'
		Start-Sleep -Seconds 2
		$ProcessStartInfo = new-object System.Diagnostics.ProcessStartInfo "PowerShell";
	}
	#Specify the current script path and name as a parameter
	#CAVEAT: Because we used Param() for this script, Built-in $Args cannot be used
	[String]$MyArgs = "-DeploymentType $DeploymentType -DeployMode $DeployMode"

	[String]$PathToThisScript = $myInvocation.MyCommand.Definition
	$ProcessStartInfo.Arguments = "-ExecutionPolicy Bypass & '$PathToThisScript' $MyArgs"

	# Indicate that the new process should be elevated
	$ProcessStartInfo.Verb = "runas";

	#Plead with User to not close this window that launched new instance of this script
	[string]$installName = ($MyInvocation.MyCommand.Name).Replace(".ps1","")
	#region MinimizeCallingConsole
	#DO NOT INDENT HERE_STRINGS!!
	$Script:showWindowAsync = Add-Type -MemberDefinition @"
[DllImport("user32.dll")]
public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);
"@ -Name "Win32ShowWindowAsync" -Namespace Win32Functions -PassThru
	$null = $showWindowAsync::ShowWindowAsync((Get-Process -Id $pid).MainWindowHandle, 2) #Minimize *ME*
	#endregion MinimizeCallingConsole

	Write-Host "Do NOT close this Un-elevated/32-bit instance of [$installName] `r`nIt will close by itself when the Elevated 64bit window is done." -ForegroundColor Red
	# Start the new process
	$newProcess = New-Object -TypeName 'System.Diagnostics.Process' -ErrorAction 'Stop'
	$newProcess.StartInfo = $processStartInfo
	$newProcess.Start() | Out-Null # Out-Null needed b/c $newProcess.Start() kicks out $true

	## Instructs the $newProcess component to wait indefinitely for the associated process to exit.
	$newProcess.WaitForExit()
	#If we don't wait, the CMD will think we are done and delete the cached files in %temp%

	## HasExited indicates that the associated process has terminated, either normally or abnormally. Wait until HasExited returns $true.
	While (-not ($newProcess.HasExited)) { $newProcess.Refresh(); Start-Sleep -Seconds 1 }

	# Exit from the current, unelevated and/or 32bit process
	# and loose exitcode chain 
	exit
}
```

**Comment by mjr4077au** [comment]
The exe now tries to invoke the script that matches the exe's name, so I think your issue for not using the exe has been resolved.

The code above is a bit on the heavier side, let's see if you're able to use the exe and it placates the need for this stuff.

**Comment by DanGough** [comment]
You could always use v3 to launch alternate script names, I’ve done it a few times myself.

I think rather than adding more bloat to the deployment script, the best solution is to just use the exe here as it already takes this into account - and even supports a switch to force it into 32-bit mode if you ever wanted to.

**Comment by That-Annoying-Guy** [comment]
I'd place the code in an appendix as optional code for the Front Script.
Intermediate/pro users could add it if they need it.

As for the v3 EXE, I couldn't get the syntax right and we've been using SCCM with "interact with user" so that hid the PS Console.
Intune will probably never get the "interact with user" check box.

**Comment by mjr4077au** [comment]
> I think rather than adding more bloat to the deployment script, the best solution is to just use the exe here as it already takes this into account - and even supports a switch to force it into 32-bit mode if you ever wanted to.

I agree with this position also, will close this one off for now.
