### ISSUE TITLE
Deploy-Application.exe fails to run sometimes.

### ISSUE THREAD

**Issue by Ken-Fitz** [PSAppDeployToolkit/PSAppDeployToolkit#59]
Issue: Deploy-Application.exe launches Powershell.exe only for a few seconds, no logs created.

Tested: Using Different previously working PS1
Results: repeated attempts to launch ALLWAYS at some point does launch and runs as expected (usually 2 to 3 launch attempts, rarely 4)

Tested: New PS1s using new template code from zip.
Results: They have same behaviour as above. 

Version of kit used: 3.6.4

**Comment by mmashwani** [comment]
That isn't enough detail to help in any meaningful way.

I would recommend looking at the other issues in the issues log to see if you are running into one of those issues. The ones marked resolved has fixes implemented in the latest beta found here:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit

Also you can look at the changelog to see the fixes implemented in the latest beta:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/CHANGELOG.txt

Try the beta and see if the problem goes away.

**Comment by Ken-Fitz** [comment]
Ok I did manage (I think) solve it.
I restarted the VM and it started working OK, Al I can assume is that in some instances after prior run fails powershell gets messed up.

After the restart so far (after about 20 or so runs) it has run 1st time.
Odd behaviour never the less.
Not sure what caused it to terminate PS.

**Comment by mmashwani** [comment]
Great, glad it's working now. I've seen a similar issue once that got resolved by a restart.
