### ISSUE TITLE
PSAppDeployToolkit PDF

### ISSUE THREAD

**Issue by zacharyshupp** [PSAppDeployToolkit/PSAppDeployToolkit#590]
**My Question/Issue:**
Good Evening,

I have been looking over your project and must say its well done. I would like to know what you use to convert all your markdown files into a Single PDF. I have some private projects that have a lot of markdown files and I havent found a good method to create an offline file for people to read. 

Thanks for your time.

**Comment by sintaxasn** [comment]
Hi Zachary,

Apologies for the delayed response. Unfortunately, I didn't find a good method to automate this myself, so this was a lot of manual work to get all of the existing help split out into individual markdown files per section and per function. Then I combined them into a single file just using PowerShell... Something like `(ForEach $file in (Get-ChildItem -Path <Path>) { Get-Content | Out-File Output.md -Append }`. Then fired it up in Typora to finalise formatting and output to a PDF using a Typora theme.

There's got to be a better way of producing good looking PDFs from markdown source. I'd like to figure out what that looks like. I think it's also work investigating this: https://devblogs.microsoft.com/powershell/youve-got-help/ for our new build pipeline
