### ISSUE TITLE
$envOSVersionMajor  and Minor as [Int] instead of [string]

### ISSUE THREAD

**Issue by Sulquendi** [PSAppDeployToolkit/PSAppDeployToolkit#591]
Hello, 

in the main.ps1, you have theses lines : 
`[string]$envOSVersionMajor = $envOSVersion.Major

[string]$envOSVersionMinor = $envOSVersion.Minor

[string]$envOSVersionBuild = $envOSVersion.Build`

Using [Int] type ([version] major, minor are [Int]) would allow version comparison without having to cast [int].

Regards

**Comment by mjr4077au** [comment]
This has been done for v4. Agreed completely, strings were dumb here.
