### ISSUE TITLE
Show-InstallationPrompt -> Parameter Timeout works in Ver. 3.8.2 but not in 3.8.3

### ISSUE THREAD

**Issue by Oliver495** [PSAppDeployToolkit/PSAppDeployToolkit#592]
**Describe the bug**
The timeout works in Ver. 3.8.2, but not in 3.8.3
Even after 1 hour the message windows does not close.

**To Reproduce**
## <Perform Pre-Installation tasks here>
Show-InstallationPrompt -Message "We install now xyz" -ButtonRightText 'OK' -Timeout 5 -ExitOnTimeout $false

**Toolkit Version:**
Version of our toolkit you are using: 3.8.3

**Additional context**
Is there a workaround, maybe with the *.xml?

**Comment by luki1412** [comment]
This will be fixed in the next version.
