### ISSUE TITLE
Get-InstalledApplication not detecting userspace installed apps

### ISSUE THREAD

**Issue by l0ser140** [PSAppDeployToolkit/PSAppDeployToolkit#593]
If application installed not systemwide but in userspace, Get-InstalledApplication will not found it.
It should search at least in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall` registry branch.

**Comment by luki1412** [comment]
We can add it as a parameter. Thanks for the report.

**Comment by mhertaya** [comment]
Hi,
also interested in this feature ;-)
Thanks

**Comment by mjr4077au** [comment]
This has been addressed for the upcoming v4 preview release.
