### ISSUE TITLE
Problems with installation of DocsCorp with switch

### ISSUE THREAD

**Issue by DavidAndersen1973** [PSAppDeployToolkit/PSAppDeployToolkit#595]
I have make a scrips for installation of DocsCorp Clean Docs, in the installation there are a switch there is needed, but when i run the installation it comes with an error:
![image](https://user-images.githubusercontent.com/76728159/103272153-5f828280-49bc-11eb-9074-f0a67e5e7051.png)

I have tried to run this without the switch and then the program is running fine, but some other issue appear thats why i need this switch.

Here is my installation:

		## <Perform Installation tasks here>
		
		Execute-MSI -Action 'Install' -Path 'cleanDocs3-1-0-15-x86.msi ERCTRAINMODE=OFF'
		Copy-File -Path "$dirFiles\cleanSendPolicy.xml" -Destination "$envProgramFilesX86\DocsCorp\CleanDocs\CleanSendPolicy.xml"
		Copy-File -Path "$dirFiles\DocsCorp.cleanDocs.Settings.xml" -Destination "$envProgramFilesX86\DocsCorp\CleanDocs\DocsCorp.cleanDocs.Settings.xml"
		Execute-Process -FilePath "reg.exe" -Parameters "IMPORT `"$dirFiles\clean.reg`"" -PassThru

Is there any way this switch can be written so the installation will run ?

The switch is: ERCTRAINMODE=OFF

Thanks

David

**Comment by luki1412** [comment]
It is a parameter so it does not go into the Path.

```
Execute-MSI -Action 'Install' -Path 'cleanDocs3-1-0-15-x86.msi' -Parameters 'ERCTRAINMODE=OFF'
```

**Comment by DavidAndersen1973** [comment]
Thanks alot Luki1412 it works :-)
