### ISSUE TITLE
Set-Itempermission doesn't work with SIDs

### ISSUE THREAD

**Issue by PasqualeMueller2** [PSAppDeployToolkit/PSAppDeployToolkit#598]
Hi together,

I used  the set-acl cmdlet in the past to modify folder permissions and now I wanted to use set-itempermission.
However, when I am using SIDs, it shows me the following error:
![image](https://user-images.githubusercontent.com/77000664/103637593-01214b00-4f4c-11eb-83e8-041ddbb116c4.png)

Lines I used:
New-Folder -Path "C:\Mydir"
#Set Permission (S-1-5-11 stands for authenticated users)
Set-ItemPermission -Path "C:\Mydir" -User "*S-1-5-11" -Permission "Write"

According to the help console, I should prefix the SID with a * what I did.
The result is the same when I remove the doublequotes around the SID.
I got the SID from the link in the help: https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows
If I am using "domain\user1" it works without any problems

Toolkit Version: 3.8.3
Powershell Version:5.1.19041.610
Greets Pasquale

**Comment by luki1412** [comment]
Thanks for the report. This will be fixed in the next version.
