### ISSUE TITLE
Issue in Get-PendingReboot

### ISSUE THREAD

**Issue by bm109591** [PSAppDeployToolkit/PSAppDeployToolkit#60]
Hi Team,

I come across an issue with Get-PendingReboot function. Please find the following part of script I used below, 

if ((Get-PendingReboot).IsSystemRebootPending){
            Show-InstallationPrompt -Message "Reboot is pending for installing SAP GUI 7.40 in the Computer" -ButtonRightText 'OK' -Icon Information -NoWait
			Exit-Script -ExitCode 129
        }
![issue](https://cloud.githubusercontent.com/assets/12154193/8727829/7e2670c4-2bff-11e5-80e6-ca62732a52bb.PNG)

Please help me as soon as possible.

Thank you so much! 

Regards
Bala

**Comment by mmashwani** [comment]
The parameter -Path should have been -Key for the call to Test-RegistryValue. I fixed it in the latest beta.

**Comment by bm109591** [comment]
It worked. Many Thanks Mashwani for quick response :)
