### ISSUE TITLE
Execute-MSI can not handle Commas in Transform and Patch paths

### ISSUE THREAD

**Issue by DLAPLME** [PSAppDeployToolkit/PSAppDeployToolkit#604]
Hi

I've stumbled upon a minor issue in the logic behind the handling of the Transform and Patch properties of the Execute-MSI function. It seems like it doesn't like Commas ',' in the paths of either.  

The logfile lists the execute command as: [Installation] :: Executing [C:\WINDOWS\System32\msiexec.exe /i `"C:\Users\Username\OneDrive\Skrivebord\Plantronics, Inc Plantronics Hub Software v3.20.53033.23105 en-US\Files\PlantronicsHubInstaller_x64.msi" TRANSFORMS="C:\Users\Username\OneDrive\Skrivebord\Plantronics; Inc Plantronics Hub Software v3.20.53033.23105 en-US\SupportFiles\PlantronicsHubInstaller_x64.mst" TRANSFORMSSECURE=1 REBOOT=ReallySuppress /QB-! /L*v "C:\WINDOWS\Logs\Software\PlantronicsHubInstaller_x64_Install.log"]...`

As you can see the path to the MSI-file is correct and has "Plantronics, Inc" in the path. Under the Transforms property the path is changed to contain "Plantronics; Inc" with a semi-colon instead. 

I do believe the responsible code is located in AppDeployToolkitMain.ps1 at line 2573 and again at line 2583: 
```
		If ($transform) {
			[string[]]$transforms = $transform -split ','
			0..($transforms.Length - 1) | ForEach-Object {
				If (Test-Path -LiteralPath (Join-Path -Path (Split-Path -Path $msiFile -Parent) -ChildPath $transforms[$_]) -PathType 'Leaf') {
					$transforms[$_] = Join-Path -Path (Split-Path -Path $msiFile -Parent) -ChildPath $transforms[$_].Replace('.\','')
				}
				Else {
					$transforms[$_] = $transforms[$_]
				}
			}
			[string]$mstFile = "`"$($transforms -join ';')`""
		}
```

It looks like this code tries to handle the possibility of assigning multiple Transform files in one comma separated string. 

Kind regards

Lasse

**Comment by luki1412** [comment]
You are right, it serves that purpose. What Im getting from this is that the documentation does not clearly state that you can use commas as separators.

**Comment by DLAPLME** [comment]
I believe I understand the reason behind the Transform and Patch parameters. Both take a [string] as a value. And if you want to be able to honor the ability of MSI files to apply multiple transform- and patch-files, when it makes perfect sense to be able use a separated string. 
But the consequence then is that the separator is no longer a valid character in the path to either the transforms or applied patches. 
It's breaks the consistency compared to the Path parameter where a comma in the path to the MSI-file is a perfectly valid, and as a comma is a valid character in a Windows URI path, it just seemed as an discrepancy.
A possible solution could be to let the Transform and Patch parameters take an array as a value. But again that could be a breaking change for some people. 

/Lasse

**Comment by luki1412** [comment]
Changing the parameter type to a string array would not fix your problem. Its just an enhancement.
I dont know why the comma was added as a separator but removing it could break scripts.
The best option I can think of here would be to add another parameter that lets you change the separator to another character and it would default to a comma. This way, it would break nothing and you could change it to a semi-colon to avoid issues you are having.

**Comment by sintaxasn** [comment]
@luki1412, I may be wrong about this, but I *think* this was implemented to ensure a semi-colon was used where earlier versions of Windows Installer did accept a comma. I suspect we can probably take this out safely.

However, if we want to keep it in, I would be more in favour of replacing all commas with semicolon, splitting it into an array with semicolon as separator, and then attempting to resolve each transform. If they fail, fall back on the original without modification. Thoughts?

**Comment by DLAPLME** [comment]
That would be a very elegant solution. My workaround is somewhat more crude, but along the same line. 

```
		If ($transform) {
			if (Test-Path -LiteralPath $transform -PathType Leaf) {
				[string]$mstFile = "`"$transform`""
			}
			else {
				[string[]]$transforms = $transform -split ','
				0..($transforms.Length - 1) | ForEach-Object {
					If (Test-Path -LiteralPath (Join-Path -Path (Split-Path -Path $msiFile -Parent) -ChildPath $transforms[$_]) -PathType 'Leaf') {
						$transforms[$_] = Join-Path -Path (Split-Path -Path $msiFile -Parent) -ChildPath $transforms[$_].Replace('.\', '')
					}
					Else {
						$transforms[$_] = $transforms[$_]
					}
				}
				[string]$mstFile = "`"$($transforms -join ';')`""
			}
		}

```
Seemed to get the job done.

```
[Installation] :: Working Directory is [C:\Users\Username\OneDrive\Skrivebord\Plantronics, Inc Plantronics Hub Software v3.20.53033.23105 en-US\Files].	Execute-Process	21-01-2021 21:08:12	26080 (0x65E0)
[Installation] :: Executing [C:\WINDOWS\System32\msiexec.exe /i "C:\Users\Username\OneDrive\Skrivebord\Plantronics, Inc Plantronics Hub Software v3.20.53033.23105 en-US\Files\PlantronicsHubInstaller_x64.msi" TRANSFORMS="C:\Users\Username\OneDrive\Skrivebord\Plantronics, Inc Plantronics Hub Software v3.20.53033.23105 en-US\SupportFiles\PlantronicsHubInstaller_x64.mst" TRANSFORMSSECURE=1 REBOOT=ReallySuppress /QB-! /L*v "C:\WINDOWS\Logs\Software\PlantronicsHubInstaller_x64_Install.log"]...	Execute-Process	21-01-2021 21:08:12	26080 (0x65E0)
[Installation] :: Execution completed successfully with exit code [0].	Execute-Process	21-01-2021 21:08:29	26080 (0x65E0)

```

The idea being to test the string if it's already a valid file path and pass that string along. If not, do the string parsing magic already in place.

**Comment by luki1412** [comment]
@sintaxasn Function help does not say anything about multiple transforms and/or a separator so I would say it is safe to remove. If they use commas then msiexec is just going to terminate with an error that it cannot find the transform file. So we should also add a note to the function help that if needed, multiple transforms/patches can be used but they must be separated by a semi-colon.

@DLAPLME That would not fix the problem if you had two or more of them though.
