### ISSUE TITLE
Typo: Line 254: AppDeployToolKitMain.PS1 [v3.6.4 Release)

### ISSUE THREAD

**Issue by martmengle** [PSAppDeployToolkit/PSAppDeployToolkit#61]
Running Windows 8.1 Enterprise there's both a typo and an incorrect path to the GPO language preferences..

Incorrect Path + Typo:
[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Software\Polices\Microsoft\Control Panel\Desktop' -Value 'PreferredUILanguages' -SID $RunAsActiveUser.SID

Just Typo Fixed:
[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Software\Policies\Microsoft\Control Panel\Desktop' -Value 'PreferredUILanguages' -SID $RunAsActiveUser.SID

Correct Path (W8.1 + Typo Fixed)
[string[]]$HKULanguages = Get-RegistryKey -Key 'HKCU\Software\Policies\Microsoft\Windows\Control Panel\Desktop' -Value 'PreferredUILanguages' -SID $RunAsActiveUser.SID

**Comment by mmashwani** [comment]
Good catch. Thanks for reporting. The latest beta has this issue resolved.
