### ISSUE TITLE
Support for Webhooks or similar solution

### ISSUE THREAD

**Issue by pandrews1976** [PSAppDeployToolkit/PSAppDeployToolkit#611]
Microsoft Teams has the ability to send notifications to a Teams channel using a webhook. We've modified the Exit-Script function that when a script failure occurs it send a notification off to a Teams channel for our team to investigate. This notification is based on the following documentation:

https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using

https://msendpointmgr.com/2017/10/06/configmgr-osd-notification-service-teams/

https://msendpointmgr.com/2019/07/10/how-to-notify-a-microsoft-teams-channel-when-a-new-windows-device-has-enrolled-in-microsoft-intune/

With each release of PSADT we need to copy this code into the new AppDeployToolkitMain.ps1 and Deploy-Application.ps1 files. Posting this here as a possible future addition to PSADT as well looking to the community to see if there is a better way to implement/provide customization outside of having to modify AppDeployToolkitMain.ps1.

**Modifications to Deploy-Application.ps1**
_Added to Synopsis/Documentation_
.PARAMETER webhookConnectorEnabled
	The Incoming Webhook connector enables external services to notify you about activities that you want to track. To use this connector, you'll 
	need to create certain settings on the other service, which needs to support a webhook that's compatible with the Office 365 connector 
	format. Default is: False
.PARAMETER webhookConnectorExcludeExitCodes
	List the exit codes to excluded from generating a notification, i.e 69797. To exclude multiple code separate with comma.
.PARAMETER webhookConnectorURL
	System generated URL for the Incoming Webhook connector to send data to your group.

Added to Paramerter Block
	,[Parameter(Mandatory = $false)]
	[switch]$webhookConnectorEnabled = $false,	
	[Parameter(Mandatory = $false)]
	[string]$webhookConnectorExcludeExitCodes = '69228,69797',
	[Parameter(Mandatory = $false)]
	[string]$webhookConnectorURL = 'webhookURL'

**Modifications to AppDeployToolkitMain.ps1**
Function Exit-Script {
<#
.SYNOPSIS
	Exit the script, perform cleanup actions, and pass an exit code to the parent process.
.DESCRIPTION
	Always use when exiting the script to ensure cleanup actions are performed.
.PARAMETER ExitCode
	The exit code to be passed from the script to the parent process, e.g. SCCM
.PARAMETER webhookConnectorEnabled
    The Incoming Webhook connector enables external services to notify you about activities that you want to track. To use this connector, you'll 
    need to create certain settings on the other service, which needs to support a webhook that's compatible with the Office 365 connector 
    format. Default is: False
.PARAMETER webhookConnectorURL
    System generated URL for the Incoming Webhook connector to send data to your group.
.EXAMPLE
	Exit-Script
.EXAMPLE
	Exit-Script -ExitCode 1618
.NOTES
.LINK
	http://psappdeploytoolkit.com
#>
`	[CmdletBinding()]
	Param (
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[int32]$ExitCode = 0
	)

	## Get the name of this function
	[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name

	## Stop the Close Program Dialog if running
	If ($formCloseApps) { $formCloseApps.Close }

	## Close the Installation Progress Dialog if running
	Close-InstallationProgress

	## If block execution variable is true, call the function to unblock execution
	If ($BlockExecution) { Unblock-AppExecution }

	## If Terminal Server mode was set, turn it off
	If ($terminalServerMode) { Disable-TerminalServerInstallMode }

	## Determine action based on exit code
	Switch ($exitCode) {
		$configInstallationUIExitCode { $installSuccess = $false }
		$configInstallationDeferExitCode { $installSuccess = $false }
		3010 { $installSuccess = $true }
		1641 { $installSuccess = $true }
		0 { $installSuccess = $true }
		Default { $installSuccess = $false }
	}

	## Determine if balloon notification should be shown
	If ($deployModeSilent) { [boolean]$configShowBalloonNotifications = $false }

	If ($installSuccess) {
		If (Test-Path -LiteralPath $regKeyDeferHistory -ErrorAction 'SilentlyContinue') {
			Write-Log -Message 'Remove deferral history...' -Source ${CmdletName}
			Remove-RegistryKey -Key $regKeyDeferHistory -Recurse
		}

		[string]$balloonText = "$deploymentTypeName $configBalloonTextComplete"
		## Handle reboot prompts on successful script completion
		If (($AllowRebootPassThru) -and ((($msiRebootDetected) -or ($exitCode -eq 3010)) -or ($exitCode -eq 1641))) {
			Write-Log -Message 'A restart has been flagged as required.' -Source ${CmdletName}
			[string]$balloonText = "$deploymentTypeName $configBalloonTextRestartRequired"
			If (($msiRebootDetected) -and ($exitCode -ne 1641)) { [int32]$exitCode = 3010 }
		}
		Else {
			[int32]$exitCode = 0
		}

		Write-Log -Message "$installName $deploymentTypeName completed with exit code [$exitcode]." -Source ${CmdletName}
		If ($configShowBalloonNotifications) { Show-BalloonTip -BalloonTipIcon 'Info' -BalloonTipText $balloonText -NoWait }
	}
	ElseIf (-not $installSuccess) {
		Wr

ite-Log -Message "$installName $deploymentTypeName completed with exit code [$exitcode]." -Source ${CmdletName}
		If (($exitCode -eq $configInstallationUIExitCode) -or ($exitCode -eq $configInstallationDeferExitCode)) {
			[string]$balloonText = "$deploymentTypeName $configBalloonTextFastRetry"
			If ($configShowBalloonNotifications) { Show-BalloonTip -BalloonTipIcon 'Warning' -BalloonTipText $balloonText -NoWait }
		}
		Else {
			[string]$balloonText = "$deploymentTypeName $configBalloonTextError"
			If ($configShowBalloonNotifications) { Show-BalloonTip -BalloonTipIcon 'Error' -BalloonTipText $balloonText -NoWait }
			
			Write-Log -Message "$installName $deploymentTypeName completed with exit code [$exitcode]." -Source ${CmdletName}

			$ignoreExitCodeMatch = $false
			If ($webhookConnectorExcludeExitCodes) {
				#  Split the processes on a comma
				[int32[]]$ignoreExitCodesArray = $webhookConnectorExcludeExitCodes -split ','
				ForEach ($ignoreCode in $ignoreExitCodesArray) {
					If ($exitCode -eq $ignoreCode) { $ignoreExitCodeMatch = $true }
				}
			}

            If (($webhookConnectorEnabled) -and ($ignoreExitCodeMatch -eq $false)) {
                [string]$dateTime = (Get-Date -Format 'yyyy-MM-dd HH\:mm\:ss').ToString()

                #Creating JSON to output into teams
                $body = ConvertTo-Json -Depth 4 @{
                    "@type" = "MessageCard"
                    "@content" = "https://schema.org/extensions"
    
                    title  = "Application Deployment Failed" 
                    text = "$DeploymentType of application [<span style=color:Yellow;> $appVendor $appName $appVersion </span>] failed with error code [ <span style=color:Yellow;>$exitCode </span>]."
    
                    sections = @(
                        @{
                            text  = "<ul style=list-style-type:square;>
                                <li><strong>Computer Name</strong> - $envComputerName</li>
                                <li><strong>Operating System</strong> - $envOSName</li>
                                <li><strong>Version</strong> - $envOSVersion</li>
                                <li><strong>Architecture</strong> - $envOSArchitecture</li>
                                <li><strong>Logged on User</strong> - $($RunAsActiveUser.NTAccount)</li>
                                <li><strong>Invoked As User</strong> - $ProcessNTAccount</li>
                            </ul>"
                        },
	                    @{
                            text  = "<ul style=list-style-type:square;>
                                <li><strong>Script Execution Path</strong> - $scriptParentPath</li>
                                <li><strong>Script Author</strong> - $appScriptAuthor</li>
                                <li><strong>Script Date</strong> - $appScriptDate</li>
                                <li><strong>Script Version</strong> - $appScriptVersion</li>
								<li><strong>PSAppDeployToolkit Version</strong> - $deployAppScriptVersion</li>
                            </ul>"
                        },
                        @{
                            text  = "<ul style=list-style-type:square;>
                                <li><strong>Log File</strong> - file://$envComputerName/c$/ProgramData/Logs/$logName</li>
                            </ul>"
                        },

	                    @{
		                    text = "$dateTime"
	                    }
                    )
                }

                Invoke-RestMethod -uri $webhookConnectorURL -Method Post -body $body -ContentType 'application/json'	
            }
		}
	}

	[string]$LogDash = '-' * 79
	Write-Log -Message $LogDash -Source ${CmdletName}

	## Archive the log files to zip format and then delete the temporary logs folder
	If ($configToolkitCompressLogs) {
		## Disable logging to file so that we can archive the log files
		. $DisableScriptLogging

		[string]$DestinationArchiveFileName = $installName + '_' + $deploymentType + '_' + ((Get-Date -Format 'yyyy-MM-dd-HH-mm-ss').ToString()) + '.zip'
		New-ZipFile -DestinationArchiveDirectoryPath $configToolkitLogDir -DestinationArchiveFileName $DestinationArchiveFileName -SourceDirectory $logTempFolder -RemoveSourceAfterArchiving
	}

	If ($script:notifyIcon) { Try { $script:notifyIcon.Dispose() } Catch {} }
	## Reset powershell window title to its previous title
	$Host.UI.RawUI.WindowTitle = $oldPSWindowTitle
	## Reset variables in case another toolkit is being run in the same session
	$global:logName = $null
	$global:installTitle = $null
	$global:installName = $null
	$global:appName = $null
	## Exit the script, returning the exit code to SCCM
	If (Test-Path -LiteralPath 'variable:HostInvocation') { $script:ExitCode = $exitCode; Exit } Else { Exit $exitCode }
}`
	
Ideally the Teams or card output would be a separate XML file. While this solution is specific to teams it should be compatible with other providers that use similar connectors.

**Comment by RobinBeismann** [comment]
To me, this shouldn't be part of PSADT but instead a Wrapper around it.
You could create a Powershell Script that calls PSADT and sends a Teams Notification based on the Exit Code of PSADT

**Comment by mjr4077au** [comment]
Webhooks are regrettably now deprecated.
