### ISSUE TITLE
Active Setup doesn't executes the StubPath file for the current user ONLY IF the Package is started under SYSTEM with ServiceUIx64.exe

### ISSUE THREAD

**Issue by Oliver495** [PSAppDeployToolkit/PSAppDeployToolkit#614]
It worked under Ver. 3.8.3, but there i reported the bug #579 that the Active Setup is executed every time you start the installation a second time. This is solved, but now the user has to log off and on that the Active Setup runs.

We start our packages under SYSTEM with ServiceUIx64.exe because we want to display PSADT-Prompts.

Example:
Start a CMD as Admin => psexec -s cmd => now the cmd runs under SYSTEM =>
ServiceUIx64.exe -Process:explorer.exe Deploy-Application.exe "-DeployMode 'Interactive' -DeploymentType 'Install' -AllowRebootPassThru

---
Logfile:
<![LOG[[Pre-Installation] :: Adding Active Setup Key for local machine: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\Mozilla_Thunderbird_78.7.0_x86_DE_01].]LOG]!><time="22:17:34.87560" date="02-02-2021" component="Set-ActiveSetup" context="NT-AUTORITÄT\SYSTEM" type="1" thread="5248" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Create registry key [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\Mozilla_Thunderbird_78.7.0_x86_DE_01].]LOG]!><time="22:17:34.90660" date="02-02-2021" component="Set-RegistryKey" context="NT-AUTORITÄT\SYSTEM" type="1" thread="5248" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Set registry key value: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\Mozilla_Thunderbird_78.7.0_x86_DE_01] [(Default) = Thunderbird Installation. Bitte warten...].]LOG]!><time="22:17:34.90660" date="02-02-2021" component="Set-RegistryKey" context="NT-AUTORITÄT\SYSTEM" type="1" thread="5248" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Set registry key value: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\Mozilla_Thunderbird_78.7.0_x86_DE_01] [StubPath = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command "& { & \"C:\Program Files (x86)\Mozilla Thunderbird\ActiveSetupThunderbird.ps1\"}"].]LOG]!><time="22:17:34.92260" date="02-02-2021" component="Set-RegistryKey" context="NT-AUTORITÄT\SYSTEM" type="1" thread="5248" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Set registry key value: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\Mozilla_Thunderbird_78.7.0_x86_DE_01] [Version = 78,7,0,1.0].]LOG]!><time="22:17:34.93760" date="02-02-2021" component="Set-RegistryKey" context="NT-AUTORITÄT\SYSTEM" type="1" thread="5248" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Set registry key value: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\Mozilla_Thunderbird_78.7.0_x86_DE_01] [IsInstalled = 1].]LOG]!><time="22:17:34.95360" date="02-02-2021" component="Set-RegistryKey" context="NT-AUTORITÄT\SYSTEM" type="1" thread="5248" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Failed to set Active Setup registry entry. 
Error Record:
-------------In D:\3.8.4\AppDeployToolkit\AppDeployToolkitMain.ps1:10768 Zeichen:58
+ ... et-RegistryKey -Key $HKCUActiveSetupKey -SID $UserProfile.SID -Value  ...
+                                                  ~~~~~~~~~~~~~~~~
Error Inner Exception(s):
-------------------------]LOG]!><time="22:17:35.03160" date="02-02-2021" component="Set-ActiveSetup" context="NT-AUTORITÄT\SYSTEM" type="3" thread="5248" file="Deploy-Application.ps1">
<![LOG[[Installation] :: [D:\3.8.4\Files\Thunderbird Setup 78.7.0.exe] is a valid fully qualified path, continue.]LOG]!><time="22:17:35.04760" date="02-02-2021" component="Execute-Process" context="NT-AUTORITÄT\SYSTEM" type="1" thread="5248" file="Deploy-Application.ps1">
---

I would prefer getting back the behaviour from 3.8.3 and use my workaroud: In my "ActiveSetupThunderbird.ps1" i check the "Version" Regkey from HKLM and HKCU. If it is the same, i quit my ps1.
Sorry for the inconvenience.

**Comment by luki1412** [comment]
There is another bug present in the function. We will release a fix for it this month.
