### ISSUE TITLE
Show-InstallationRestartPrompt -NoCountdown doesn't display restart prompt

### ISSUE THREAD

**Issue by markaldridge** [PSAppDeployToolkit/PSAppDeployToolkit#617]
**Describe the bug**
When using: Show-InstallationRestartPrompt -NoCountdown
I don't see the restart prompt.

**To Reproduce**
1. Add Show-InstallationRestartPrompt -NoCountdown within the installation section.
2. Run Deploy-Application.exe
3. No restart dialog box is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/26090587/107006772-c37f3e80-67e5-11eb-8acd-f3423ceebea8.png)

**Toolkit Version:**
3.8.4

**Powershell Version:**
5.1

**Comment by luki1412** [comment]
Hello, there is a bug with handling parameters in this function. We will release a new version this month to address it.
