### ISSUE TITLE
Need something like a [DateTime]$StartOfInstallDateTime variable

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#62]
The ToolKit already has:

	[String]$currentTime
	[String]$currentDate

But they are both in [String] format, not [DateTime]. Sure I could try to combine the two and convent back to [DateTime] but you add "Culture" differences into the mix and things will break.

What I need is:

	[DateTime]$CurrentDateTime=Get-Date

Or

	[DateTime]$StartOfInstallDateTime=Get-Date

I'm not picky for the name I just need the functionality and I'd rather it can from the source so that it doesn't cause confusion later.

Mo, can you make it so or did I miss something?

**Comment by mmashwani** [comment]
I think we can change the current variable types from strings to DateTime without any impact. Any situation where the variable is being used like a string, PowerShell will automatically convert a DateTime to a string format. I've updated the toolkit variables types to datetime in the beta.
