### ISSUE TITLE
Cutomize defer balloon notification text and icon + solution

### ISSUE THREAD

**Issue by dianneman** [PSAppDeployToolkit/PSAppDeployToolkit#623]
_**Is your feature request related to a problem? Please describe.**_
It just seems to be the users fault when it defers an installation due to the warning icon shown in the balloon notification. It's something the user initiates and does in my option needs rather a information icon then a warning. It is even better to be able to specify the icon yourself from config. I have also made it possible to adjust the balloon notification text. 

_**Describe the solution you'd like**_
I've already made the solution

_**AppDeployToolkitConfig.xml**_
```
<BalloonText_Defer>postponed</BalloonText_Defer>
<!-- Text displayed in the balloon tip for a postponed deployment -->

```
_**AppDeployToolkitMain.ps1**_
```
# Add to section VARIABLE DECLARATION
[string]$configBalloonTextDefer = $xmlUIMessages.BalloonText_Defer

# Modified part of function Exit-Script
	ElseIf (-not $installSuccess) {
		Write-Log -Message "$installName $deploymentTypeName completed with exit code [$exitcode]." -Source ${CmdletName}

		If (($exitCode -eq $configInstallationDeferExitCode)) {
			[string]$balloonText = "$deploymentTypeName $configBalloonTextDefer"
			If ($configShowBalloonNotifications) { Show-BalloonTip -BalloonTipIcon 'Info' -BalloonTipText $balloonText -NoWait }
		}
		elseIf ($exitCode -eq $configInstallationUIExitCode) {
			[string]$balloonText = "$deploymentTypeName $configBalloonTextFastRetry"
			If ($configShowBalloonNotifications) { Show-BalloonTip -BalloonTipIcon 'Warning' -BalloonTipText $balloonText -NoWait }
		}
		Else {
			[string]$balloonText = "$deploymentTypeName $configBalloonTextError"
			If ($configShowBalloonNotifications) { Show-BalloonTip -BalloonTipIcon 'Error' -BalloonTipText $balloonText -NoWait }
		}
	}

```

**Comment by luki1412** [comment]
The problem with changes like these is that it changes the translations. We try to avoid those because we currently dont have a proper way to translate everything to all languages.

**Comment by mjr4077au** [comment]
The classic dialogs, which has the balloon tips, is now on feature lock. As such I'll close this issue for the time being.
