### ISSUE TITLE
When trying to open "AppDeployToolkitHelp.ps1", an error comes up and it doesn't open

### ISSUE THREAD

**Issue by dclin999** [PSAppDeployToolkit/PSAppDeployToolkit#625]
**Describe the bug**
When trying to open "AppDeployToolkitHelp.ps1", an error comes up and it doesn't open. This happens in v3.8.3 and v3.8.4

**To Reproduce**
1. Right click "AppDeployToolkitHelp.ps1",
2. Click "Run with PowerShell"
3. Click "run once" twice

**Screenshots**

![error](https://user-images.githubusercontent.com/79130444/108025366-753a2d00-707a-11eb-9aaf-bae3c6877121.png)

App Deploy logo banner file not found.
At .......PSAppDeployToolkit_v3.8.4\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1:318 char:76
+ ... -PathType 'Leaf')) { Throw 'App Deploy logo banner file not found.' }
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (App Deploy logo banner file not found.:String) [], RuntimeException
    + FullyQualifiedErrorId : App Deploy logo banner file not found.

**Toolkit Version:**
This happens in 3.8.3 and 3.8.4

**Powershell Version:**
5.1

**Additional context**

**Comment by luki1412** [comment]
$AppDeployLogoIcon is defined inside AppDeployToolkitMain.ps1 that is being dot sourced at the start. Seems like dot sourcing failed or didn't work correctly for you. Check your execution policy.
