### ISSUE TITLE
Active Setup 3.8.4 Inner Exception when toolkit is ran in system context

### ISSUE THREAD

**Issue by Ath3na-UK** [PSAppDeployToolkit/PSAppDeployToolkit#632]
**Describe the bug**
Hi, When ran via MEMCM or via PSEXEC -i -s cmd.exe in system context active 
![1](https://user-images.githubusercontent.com/53652632/110801472-32343980-8275-11eb-8e68-e131d6fd79ff.png)
setup produces an error.

[Installation] :: Failed to set Active Setup registry entry. 
Error Record:
-------------At C:\_PKG\Test\PKG\AppDeployToolkit\AppDeployToolkitMain.ps1:10768 char:58
+ ... et-RegistryKey -Key $HKCUActiveSetupKey -SID $UserProfile.SID -Value  ...
+                                                  ~~~~~~~~~~~~~~~~
Error Inner Exception(s):
-------------------------

command line causing the error.
Set-ActiveSetup -StubExePath "$RK_customisation" -Arguments '/S' -Description 'DocsCorp pdfDocs LS' -Key 'DocsCorp pdfDocs LS' -Locale 'en' -Version '1,0,0'

Older versions of the toolkit don't have this issue. Thanks for all your efforts, love the toolkit!

**Comment by Ath3na-UK** [comment]
The active setup keys are actually created and the next time I login the stub is performed. The old version of the toolkit used to execute the active setup stub straight after creation to save the user having to log out and back in again.

**Comment by luki1412** [comment]
Yes, we are aware of the issue. The next version will compare versions and the bugs are fixed.
