### ISSUE TITLE
PSADT no longer runs on Domain Controllers

### ISSUE THREAD

**Issue by t7504** [PSAppDeployToolkit/PSAppDeployToolkit#634]
Line 270 in AppDeploymentToolkitMain is new with 3.8.4:

[string]$LocalPowerUsersGroup = (New-Object -TypeName System.Security.Principal.SecurityIdentifier -ArgumentList ([Security.Principal.WellKnownSidType]::'BuiltinPowerUsersSid', $null)).Translate([System.Security.Principal.NTAccount]).Value

This line causes PSADT to immediately fail when run on a domain controller:

_**"Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated.""**_

This is because BUILT IN\Power Users doesn't exist on a domain controller.

Until a fix is release, I'll comment out this line to allow the script to proceed.

**Comment by luki1412** [comment]
We are already aware of this issue and a fix has been implemented. Please wait for a new release.
