### ISSUE TITLE
Function to check whether a user or computer is member of a specific Active Directory group without using the Active Directory PowerShell module

### ISSUE THREAD

**Issue by powershellking** [PSAppDeployToolkit/PSAppDeployToolkit#638]
**Is your feature request related to a problem? Please describe.**
In some cases it's necessary to be able to check in which Active Directory groups a user or computer is member.

**Describe the solution you'd like**
I'd like to have a function that checks whether a user or computer is member in a specific active directory group. The function must not rely on the Active Directory module of PowerShell since it's not available on every machine.

**Describe alternatives you've considered**
I've already created such a function and added it to the template of our company's version of PSADT. I just wanted to share it with the community so everyone can use it. I'll soon send a pull request on that.

**Comment by mjr4077au** [comment]
Unfortunately the PR you've submitted is too old to consider merging, however I also don't think this functionality needs to be in the toolkit as you shouldn't be deploying to all users/computers, then doing deterministic actions based on group membership at runtime; rather you should configure SCCM or Intune to deploy to your targeted users/computers instead.
