### ISSUE TITLE
Show-InstallationWelcome enhancement for uninstallation

### ISSUE THREAD

**Issue by manderio** [PSAppDeployToolkit/PSAppDeployToolkit#640]
**Problem**
When using the Show-InstallationWelcome for an unstallation, it will automatically use the $defaultMsiExecutablesList as part of the applications that need to be shut down. This presents an issue as some applications will not close until the uninstallation process is started (msiexec /u application.msi), this behavior does not change when using the -CloseApps option. Not sure if intended behavior or a bug, therefore I will add it as feature request. 

**Solution**
Would be great if there was a fix for this in order to hardcode applications and being able to override the default MSI executable list. Been trying to look through the source code for a way to solve this issue but am yet to find it, please refer me to a solution if one exists. If this is expected behavior, could there be a way to hard code applications?

**Alternative** 
Currently our workaround has been to just not use the Show-InstallationWelcome function during uninstallation process and instead delay the resetart. This is not a viable workaround since this issue may arise for other applications where that is not an option.

**Comment by manderio** [comment]
Realised this after looking through the source code, took me a while though. Is there a way to get this working for uninstallations too? Still feel like you would like to set it, especially if you are doing an upgrade of an application and it already exists. Feels like a bad implementation in my opinion. Especially if you want to warn users and allow them to defer something that requires a restart.

**Comment by manderio** [comment]
Apologies, wording got messed up, and yes, adding that option would be a good solution if possible. The reason i mention uninstall is due to the fact that it's where i have been using the option where it was noticable, apologies for the use of wrong language :)

**Comment by MarsWalker** [comment]
Another issue with Show-InstallationWelcome on the uninstallation is that the it always say "install" and never "uninstall".
It does not respect if it's an install or uninstall.

**Comment by manderio** [comment]
I feel like having a show-welcome function would make more sense than show installation or show uninstallation welcome. It got more use cases and you can utilize it in more diverse ways which would reduce the amount of code required.

**Comment by cfreeman21** [comment]
I am having an issue with Show-InstallationWelcome -CloseApps for DeploymentType Uninstall, but works in DeploymentType Install.  Using latest version 3.8.4 of PSAPDT.

**Comment by mjr4077au** [comment]
> Apologies, wording got messed up, and yes, adding that option would be a good solution if possible. The reason i mention uninstall is due to the fact that it's where i have been using the option where it was noticable, apologies for the use of wrong language :)

Added in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/9fc0da9e240d67d583efebc4df09b7318dcd0347, the rest of the mentioned issues are being tracked elsewhere.
