### ISSUE TITLE
Update Manual for powershell Requirements

### ISSUE THREAD

**Issue by profyt7** [PSAppDeployToolkit/PSAppDeployToolkit#641]
Hi Guys, Noticed the admin guide shows the requirements is Powershell 2.0. I think that should be 2.0 or above. Our security team was leary of approving the toolkits use because the documentation said it required 2.0 to run. Had to prove to them that 2.0 is just the lowest version it works with and not the base requirement.

**Comment by mjr4077au** [comment]
The upcoming v4 release will be Windows PowerShell 5.1 or higher.
