### ISSUE TITLE
PSADT package creates crazy output when writing a file with "Out-File" or "Set-Content"

### ISSUE THREAD

**Issue by Frickeldave** [PSAppDeployToolkit/PSAppDeployToolkit#643]
**Describe the bug**
I try to create a settings.json file for Visual Studio Code (portable) with following code in the Post-Installation section of my PSADT script: 

```
$targetDir="C:\Users\Dave\AppData\Local\msg\Default\VSCode\1.55.2"
$InstallRoot="C:\Users\Dave\AppData\Local\msg"
$ProjectName="Default"
$GitVersion="2.30.2.0"

# Create data directory in target to make the installation portable (https://code.visualstudio.com/docs/editor/portable)
if(!(Test-Path "$targetDir\data")) { New-Folder "$targetDir\data" }
if(!(Test-Path "$targetDir\data\user-data")) { New-Folder "$targetDir\data\user-data" }
if(!(Test-Path "$targetDir\data\user-data\User")) { New-Folder "$targetDir\data\user-data\User" }
		
# Create a Powershell Object from the settings.json
if(!(Test-Path "$targetDir\data\user-data\User\settings.json")) { 
	$settingsJSON=New-Object -TypeName psobject
} else {
	$settingsJSON = Get-Content -Raw -Path "$targetDir\data\user-data\User\settings.json" | ConvertFrom-Json
}

# Write targetpath for git client
if($GitVersion -eq "") {
	$gitPath=""
} else {
	$gitPath="$InstallRoot\$ProjectName\GitClient\$GitVersion\bin\git.exe"
}

# Add property if needed and set value
if (($settingsJSON | Get-Member -Name "git.Path") -eq $null) {
	$settingsJSON | Add-Member -MemberType NoteProperty -Name "git.path" -Value ""
} 
$settingsJSON.'git.Path' = $gitPath

# Write file
$settingsFile ="$targetDir\data\user-data\User\settings.json"
$settingsJSON | ConvertTo-Json -Depth 10 | Set-Content "$settingsFile" -Encoding utf8
```

When opening the settings.json in VScode (after installation of the package with "DeployApplication.ps1"  i get the following result: 

![image](https://user-images.githubusercontent.com/34135598/114861228-44ae0f80-9ded-11eb-889d-28bc2cada8e1.png)

The file opens perfectly fine in Notepad++, but the encoding is set to "UCS-2 LE BOM" (not utf8 as defined in "Set-Content"). When i change the encoding in Notepad++ its also fine in VSCode. 

For another test i reinstalled VSCode with the corrupt settings.json, copied the above code without any change into a new Powershell-Script and run it again from the same Powershell Console, where i ran the Deploy-Application.ps1. The result is, that the file is also fine. So it seems to be just an issue, when the code is running out of a PSADT script. 
Do you have any ideas for me?

**Toolkit Version:** 3.8.4

**Powershell Version:** 5.1.19041.610

**Comment by luki1412** [comment]
UCS-2 LE BOM is UTF16. You can click on the currently used encoding in bottom right corner of VSCode and select 'Reopen with encoding' and select UTF16 LE.

Out-File and Set-Content are not toolkit commands. We do not change their functionality in any way.

**Comment by mjr4077au** [comment]
Not a bug with the toolkit. As mentioned above, PowerShell 5 will use UTF16 LE for `Out-File`, which while is somewhat alien today, is Windows' default Unicode encoding and has been since NT 3.1.
