### ISSUE TITLE
Set-ActiveSetup NOT Working with Logged In User

### ISSUE THREAD

**Issue by Howard0101** [PSAppDeployToolkit/PSAppDeployToolkit#644]
**Describe the bug**
Set-AcitveSetup is not working and breaks out with an error but main script (deploy-application.ps1) is still continueing without error.

**To Reproduce**
1. Use Line like 
Set-ActiveSetup -StubExePath "$envProgramData\JitsiMeetInstaller\$EXEFilename" -Arguments $EXEParams -Description "Jitsi Meet Client" -Key $([IO.Path]::GetFileNameWithoutExtension($EXEFilename)).Replace(' ','')
in Deploy-Application.ps1
2. Installation ends with return code = 0 BUT
3. Logfile shows error:
![Screenshot 2021-04-20 182815](https://user-images.githubusercontent.com/51384617/115432000-381f2200-a206-11eb-831e-afce3000fc41.png)

Analyzing the AppDeployToolKitMain.ps1 I found that the function 'Set-ActiveSetup' on line 10768 uses the variable $UserProfile which is not set anywhere in the function => error raised

**Screenshots**
Attached

**Toolkit Version:**
3.8.4

**Powershell Version:**
5.1.19041.906

**Additional context**
Please fix bug

**Comment by BofilFR** [comment]
I wrote a quick fix for me that I share with you:
After the line #10649 in the **AppDeployToolkitMain.ps1** file of version 3.8.4 of the toolkit, add the following code:
 
`$UserProfile = $CurrentLoggedOnUserSession`

![image](https://user-images.githubusercontent.com/122098453/211017531-32b513e5-500d-434b-8590-638cf12bdeae.png)

Antoher solution is to rename each occurrence of the `$UserProfile` variable by `$CurrentLoggedOnUserSession` in the `Set-ActiveSetup` function.

I'm looking forward the release 3.8.5 gets out!

**Comment by seanlillis** [comment]
Fixed in v3.9.0.
