### ISSUE TITLE
Invoke-HKCURegistrySettingsForAllUsers NOT working for logged in User 

### ISSUE THREAD

**Issue by Howard0101** [PSAppDeployToolkit/PSAppDeployToolkit#647]
**Describe the bug**
When using Invoke-HKCURegistrySettingsForAllUsers the currently logged in user is not modified.

**To Reproduce**
1. Use Invoke-HKCURegistrySettingsForAllUsers in Script deploy-application.ps1
2. Use deploy-application.exe to install the package on a client WHILE a user is logged in
3. Check the registry under HKCU
4. See that the keys are not added/changed

The logfle states it has done the settings for the logged in user but that is not the case. Other users like Default are alright. Just the currently loaded registry hives seem not to be affected.

To clarify: I use SYSTEM account for installation. Still a loaded hive should not be a problem, does it?

**Toolkit Version:**
3.8.4

**Powershell Version:**
5.1

tested on Windows 10 Pro 2004

PS AppDeploy is still the best tool for software deployment. Please carry on the good work. I am loving it.

**Comment by cyborgrd** [comment]
Hi, i tested now on 1909. It works wo problems

![image](https://user-images.githubusercontent.com/16757493/116552255-1e15cb80-a8f9-11eb-801a-d71a78320cae.png)
![image](https://user-images.githubusercontent.com/16757493/116552349-384fa980-a8f9-11eb-9d79-fa8555df1a04.png)

**Comment by Howard0101** [comment]
My mistake: I did not use the -SID parameter in set-registrykey which is mandatory for using HKCU Keys.
I kindly ask to make that fact absolutely clear in the documentation. I seem to have not found a part where it says that it is absolutely mandatory to use the -SID parameter for HKCU Keys in combination with Invoke-HKCURegistrySettingsForAllUsers.
