### ISSUE TITLE
Deploy-application.exe -CUSTOMPARAM not working

### ISSUE THREAD

**Issue by PowershellBacon** [PSAppDeployToolkit/PSAppDeployToolkit#649]
With this latest version I can no longer pass customer parameters with the exe file. Previous versions I had no issues using customer parameters with the exe file like -region or -deadline. Is this intended or not?

**Comment by That-Annoying-Guy** [comment]
Issue confirmed:
https://discourse.psappdeploytoolkit.com/t/will-deploy-application-exe-pass-custom-parameters/3607/11

**Comment by tmeltdowner** [comment]
Have the same issue.

**Comment by scotpower** [comment]
This problem just popped up for me with version 3.8.4. Running a debug on the Deploy-Application.exe source, <code>List<string> commandLineArgs = new List<string>(Environment.GetCommandLineArgs());</code> strips out double quotes (which I had.)  Single quotes are not removed and using them instead worked.

**Comment by middletonk** [comment]
Sorry for the necro post, but I stumbled here via Google. I was able to reproduce this exact same problem on version 3.9.3. However, Scot's comment about using single quotes instead of double continues to work as a workaround! Cheers!

**Comment by mjr4077au** [comment]
Duplicate of #200.
