### ISSUE TITLE
Get-InstalledApplication treats permission error with enumerating Uninstall subkey as a terminating error

### ISSUE THREAD

**Issue by metalicsmell** [PSAppDeployToolkit/PSAppDeployToolkit#65]
I'm using latest beta.

Java x64 not removing while 
![java_before](https://cloud.githubusercontent.com/assets/12895600/8760087/98a4a60e-2d22-11e5-8b7e-f3ecd9e84c9d.JPG)
```RemoveMSI-Application 'Java'```
in same time x86 removed correctly. 
![java_after](https://cloud.githubusercontent.com/assets/12895600/8760088/a6e602b2-2d22-11e5-9f73-0a2e2236f771.JPG)

no logFile in %logdir% - looks like Java x64 not visible for script.
![x86_founded_-x64_is_not](https://cloud.githubusercontent.com/assets/12895600/8760089/b3441882-2d22-11e5-9195-ed627b48efc6.JPG)

Here is a [logfile](http://pastebin.com/eH5Ppz9N)

Please be advised that there are no error in the fact that i'm removing and installing the same version of Java. My test is synthetic and this issue appear with another Java versions too.

**Comment by mmashwani** [comment]
I keep see this error in the log:
```
[Pre-Installation] :: Failed to resolve registry path [HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall]. 
Error Record:
-------------

Message        : Requested registry access is not allowed.
```

It looks like a permissions issue is stopping the script from enumerating the 64-bit portion of the registry that contains install information for 64-bit applications. Can you examine the permissions between these two keys and see what the difference is?

```
'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'
'HKLM:SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall'
```

**Comment by metalicsmell** [comment]
I've just checked it. The permissions are same.

I'm executing ```Deploy-Application.exe``` manually, with my permissions (Administrator), and manually a can enumerate all Keys in ```'HKLM:SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall'```.

**Comment by mmashwani** [comment]
Can you manually enumerate all keys under ```'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'``` using PowerShell?

**Comment by metalicsmell** [comment]
No, it stops.
```
IE40
IE4Data
IE5BAKEX
IEData
Get-ChildItem : Requested registry access is not allowed.
At line:1 char:1
+ Get-ChildItem -LiteralPath 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Unins ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...Security Client:String) [Get-ChildItem], SecurityEx
   ception
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.GetChildItemCommand
```

**Comment by mmashwani** [comment]
Try it by changing the error actin parameter to ```-ErrorAction 'SilentlyContinue'```

```
Get-ChildItem -LiteralPath 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall' -ErrorAction 'SilentlyContinue'
```

Also, if you change the error action in the toolkit to 'SilentlyContinue', does Java x64 then get uninstalled?

**Comment by metalicsmell** [comment]
Yes, it working - enumerate all records. 

In which line i should replace it?

**Comment by mmashwani** [comment]
line 1757

**Comment by metalicsmell** [comment]
Yes, already found it.
```
If (Test-Path -LiteralPath $regKey -ErrorAction 'SilentlyContinue') {
[psobject[]]$regKeyApplication = Get-ChildItem -LiteralPath $regKey -ErrorAction 'SilentlyContinue' | ForEach-Object { Get-ItemProperty -LiteralPath $_.PSPath -ErrorAction 'SilentlyContinue' | Where-Object { $_.DisplayName } }
```
![111](https://cloud.githubusercontent.com/assets/12895600/8764396/5857496c-2def-11e5-9677-33b606955832.JPG)
Looks like working now!

**Comment by mmashwani** [comment]
Yes, you can use * to do wildcard matching. Just make sure to use the -WildCard parameter.

**Comment by mmashwani** [comment]
Issue is now resolved in the latest beta.
