### ISSUE TITLE
Mount and UnMount WIM files

### ISSUE THREAD

**Issue by Sri-Boddupalli** [PSAppDeployToolkit/PSAppDeployToolkit#651]
If we are using WIM files(Mostly for Large Size apps OR package with more than 1000 files) for the deployments we are writing our own code to Mount and Unmount them before and after the installation. This is so far very efficient and working great for us, however if we have the pre-built function in PSADT like Mount-WIMfile and Unmount-WIMfile that would be awesome and eliminates so much pain for us. 

This is the code we are currently using for Mount and Unmount WIM files. We may can make it better and add to our PSADT native functions

Mount-WIMfile

`###############################################################################################
	# Pre-Installation Task for WIM based Installation
	# THIS IS A WIM BASED INSTALLATION.  The following pre-installation tasks mount the wim. 

	If (-not (Test-Path "$dirfiles\$packageName.wim")) { 

        Write-log -message "Did not find $dirfiles\$packageName.wim.  Without wim file, cannot continue." 

        Exit-Script -ExitCode 3   #Cannot find the path specified 

        } 

        Write-Log -message "Preparing mount folder: $envAllUsersProfile\PackageMount\$packageName" 

        If (-not (Test-Path "$envAllUsersProfile\PackageMount\$packageName")) { 

        New-Item -Path "$envAllUsersProfile\PackageMount\$packageName" -ItemType Directory 

        } 

        Else { 

        #Folder already exists.  We need to ensure its clean, so check if it's mounted, then remove it, then re-create it 

        Write-Log -message "Mount folder pre-existed.  Checking if mounted.  If so, dismount, and try cleanup before attempting mount again." 

        $Mounted = Get-WindowsImage -Mounted | Where-Object { $_.MountPath -eq "$envAllUsersProfile\PackageMount\$packageName" } 

        If ([bool]$Mounted) { 

        Write-Log -Message "Mount folder is still an active mount.  Attempting to dismount $envAllUsersProfile\PackageMount\$packageName" 

        try { 

        $Mounted | Dismount-WindowsImage -Discard 

        Clear-WindowsCorruptMountPoint 

        Write-Log -Message "Dismount complete" 

        } 

        catch { 

        #If error caught here, would be nice to call function that sets up scheduled task to perform cleanup at STARTUP as SYSTEM 

        $exceptionMessage = "DISMOUNT ERROR: {0}: '{1}'" -f ($_.Exception.GetType().FullName), ($_.Exception.Message) 

        write-log -message $exceptionMessage 

        Show-InstallationProgress -StatusMessage "ERROR: 69400 while Preparing package for installation" 

        Show-DialogBox -Text "Error preparing package for install. ERROR: 69400. `n`nPlease restart your computer before trying again. `n`nContact the Service Desk if the issue persists." -title "Pre-install Error" -icon 'Stop' 

        Exit-Script -ExitCode 69400 

        } 

        } 

        If ([bool]$Mounted) { Clear-Variable $Mounted } 

        Start-Sleep -Seconds 5 

        Remove-Item -path "$envAllUsersProfile\PackageMount\$packageName" -Recurse -Force 

        New-Item -Path "$envAllUsersProfile\PackageMount\$packageName" -ItemType Directory 

        } 

        Write-Log -message "Attempting to mount $dirfiles\$packageName.wim to $envAllUsersProfile\PackageMount\$packageName" 

        try { 

        Mount-WindowsImage -Path "$envAllUsersProfile\PackageMount\$packageName" -ImagePath "$dirfiles\$packageName.wim" -Index 1 -ReadOnly 

        Write-Log -Message "Mount Complete" 

        } 

        catch { 

        #If error caught, would be nice to call a standard wim cleanup function to try cleanup.  If cleanup function fails, then call function to do next boot cleanup with scheduled task. 

        $exceptionMessage = "MOUNT ERROR: {0}: '{1}'" -f ($_.Exception.GetType().FullName), ($_.Exception.Message) 

        write-log -message $exceptionMessage 

        Show-InstallationProgress -StatusMessage "ERROR 69500 while Preparing package for installation" 

        Show-DialogBox -Text "Error preparing package for install. ERROR: 69500. `n`nPlease try the installation again." -title "Pre-install Error" -icon 'Stop' 

        Exit-Script -ExitCode 69500 

        }
	
	#THIS IS A WIM BASED INSTALLATION.  The ABOVE pre-installation tasks mount the wim. 
	###############################################################################################
`
Unmount-WIMfile

`###############################################################################################
	##Post-Installation
	#THIS IS A WIM BASED INSTALLATION.  The following post-installation tasks dismount the wim. 
  
        Show-InstallationProgress -StatusMessage "Post-Installation Package Cleanup..." 

        $Mounted = Get-WindowsImage -Mounted | Where-Object { $_.MountPath -eq "$envAllUsersProfile\PackageMount\$packageName" } 

        If ([bool]$Mounted) { 

        Write-Log -Message "Mount folder is an active mount.  Attempting to dismount $envAllUsersProfile\PackageMount\$packageName" 

        try { 

        $Mounted | Dismount-WindowsImage -Discard 

        Clear-WindowsCorruptMountPoint 

        Remove-Item -path "$envAllUsersProfile\PackageMount\$packageName" -Recurse -Force 

        write-log -message "Dismount complete on first attempt for: $envAllUsersProfile\PackageMount\$packageName" 

        } 

        catch { 

        #If error caught here, lets wait 30 seconds, and TRY to dismount again.  Gives install processes a bit of extra time to let go of open files. 

        $exceptionMessage = "DISMOUNT ERROR: {0}: '{1}'" -f ($_.Exception.GetType().FullName), ($_.Exception.Message) 

        write-log -message $exceptionMessage 

        Start-Sleep -seconds 30 

        try { 

        $Mounted | Dismount-WindowsImage -Discard 

        Clear-WindowsCorruptMountPoint 

        Remove-Item -path "$envAllUsersProfile\PackageMount\$packageName" -Recurse -Force 

        write-log -message "Dismount complete on second attempt for: $envAllUsersProfile\PackageMount\$packageName" 

        } 

        catch { 

        #This is an error on the 2nd attempt to dismount, so lets stop trying and instead create scheduled task to clean up on next STARTUP as SYSTEM 

        $exceptionMessage = "DISMOUNT ERROR: {0}: '{1}'" -f ($_.Exception.GetType().FullName), ($_.Exception.Message) 

        write-log -message $exceptionMessage 

        write-log -message "Failed twice to dismount $envAllUsersProfile\PackageMount\$packageName. Creating CleanupWIM Scheduled Task to run at next STARTUP." 

        $STAction = New-ScheduledTaskAction -Execute 'Powershell.exe' -Argument '-NoProfile -WindowStyle Hidden -command "& {Get-WindowsImage -Mounted | Where-Object {$_.MountStatus -eq ''Invalid''} | ForEach-Object {$_ | Dismount-WindowsImage -Discard -ErrorVariable wimerr; if ([bool]$wimerr) {$errflag = $true}}; If (-not $errflag) {Clear-WindowsCorruptMountPoint; Unregister-ScheduledTask -TaskName ''CleanupWIM'' -Confirm:$false}}"' 

        $STTrigger = New-ScheduledTaskTrigger -AtStartup 

        Register-ScheduledTask -Action $STAction -Trigger $STTrigger -TaskName "CleanupWIM" -Description "Clean up WIM Mount points that failed to dismount properly" -User "NT AUTHORITY\SYSTEM" -RunLevel Highest -Force

        #Exit code 1641 is SCCM Hard Reboot code.  This will schedule an SCCM computer reboot, and prevent further installations until rebooted. 

        $AllowRebootPassThru = $true 

        Exit-Script -ExitCode 1641 

        } 

        } 

        } 
        
        #THIS IS A WIM BASED INSTALLATION.  The Above post-installation tasks dismount the wim. 
	###############################################################################################
`

**Comment by cyborgrd** [comment]
Hmm, for large installations or lot of small files we are using 7zip...

**Comment by metroidfox** [comment]
That is something I would be also highly interested to have implemanted directly into PSADT. WIM files are just that much fonctionnal than ZIP files. For example, I have an applicaiton with over 60 000 files/15Go. With a zip file, simply unzipping the file takes something like 40 minutes, at which point is a lot of time, while mounting the wim takes about 5-10 seconds.

Also, with Zip files, you need space disk for the file, and the extracted content, while with WIM, no extraction is needed, so it's much easier to install big applications on small disks.

Although, in our case, we added a small cleanup into Exit-Script to dismount any remaining moutns as with some errors, the script will fail before dismounting them on it's own.

**Comment by djyox** [comment]
Care to show an example of how this is implemented and used with PSADT?

**Comment by That-Annoying-Guy** [comment]
There is an extension for WIM files: https://discourse.psappdeploytoolkit.com/t/psadt-extension-psadtwim/2888

**Comment by ElianeMegert** [comment]
Interested here. implemented custom functions in extensions.ps1 so we're fine. still think its a great way compared to zip\unzip sources. From the point of downloading and extracting (hash issues resolved; branch caching) over to virus scan impacts (wont kick in with wim) all the way to speed (much faster) and disk space savings its just brilliant. can only support this request
