### ISSUE TITLE
Adding another Keyvalue to the Output of get-installedapplication

### ISSUE THREAD

**Issue by Akitarmo** [PSAppDeployToolkit/PSAppDeployToolkit#652]
Hi there,

I´m not really good with Powershell and all of this (yet:) so forgive me if I miss something.

But I´m currently trying to MAKE a functioning uninstall for my PSADT Scripts, I´m thinking about using the get-installedApplication Function and while working on this i figured, it would be helpfull if the get-installedapplication could fetch the "WindowsInstaller" KeyValue too, it would help to know wich parameters I have to use to uninstall because it lets you know if the Progam was installed with a msi File or not.

Edit:
Another thing that could be usefull would be to fetch the QuietUninstallString KeyValue, not every Software has it but many do. For Example Discord, Uplay or flux.

Thanks:)

**Comment by Akitarmo** [comment]
Worked with the QuietUninstallString now, its mostly garbage, for almost every Application I tried it, there where changes to be made so it wouldnt add much Value to PSADT, please forget it. 
But the WindowsInstaller Value would still be great.

**Comment by Akitarmo** [comment]
Openend a correctly formatted Feature Request, sorry:)
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/661

**Comment by klawdhfzasjhaa** [comment]
Hello!
I would like to propose a re-open, because we also would like to use the "QuietUninstallString" value. We have two softwares, where we have a valid string in there.
