### ISSUE TITLE
PSADT being blocked by Microsoft Attack Surface Reduction

### ISSUE THREAD

**Issue by ThijsLecomte** [PSAppDeployToolkit/PSAppDeployToolkit#658]
**Describe the bug**
Since last week, we are seeing PSADT being blocked by [Attack Surface Reduction rules by Microsoft](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-execution-of-potentially-obfuscated-scripts). More specially, 'Block execution of potentially obfuscated scripts'. It's been hitting the 'AppDeployToolkitMain.cs' file.

The customer hasn't updated PSADT since 1,5 months and this started happening last week.
I have also reported this to Microsoft, but wanted to report it here because other companies are probably facing the same issue.

**Screenshots**
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/42153270/122012266-44b29780-cdbd-11eb-95da-e4cff18b4b3b.png)

**Toolkit Version:**
Version of our toolkit you are using. For example: 3.8.4

**Powershell Version:**
Version of Powershell you are using to run the toolkit. For example: 5.1

**Additional context**

**Comment by dpknoll** [comment]
This issue started in our environment yesterday. 
Toolkit Version: 3.8.3
Powershell Version: 5.1

I run a test and tried PSADT version 3.8.4 and our ASR rules seemed to be okay with that.

**Comment by HpotsirhcH** [comment]
I also had this Issue with 3.8.3 and could "Fix" it with 3.8.4.

**Comment by ThijsLecomte** [comment]
Seems to be okay with 3.8.4 indeed!
