### ISSUE TITLE
-FilterApplication switch incorrectly filters applications

### ISSUE THREAD

**Issue by codylc** [PSAppDeployToolkit/PSAppDeployToolkit#665]
**Describe the bug**
Remove-MSIApplications cmdlet's "-FilterApplication" switch does not seem to work as documentation describes. I'm using these filters with Java 8 removals, as the documentation was written for. 

I seem to be hitting multiple issues. On a Windows 10 1909 workstation with Java 8 x86 and x64 installed...

1. Using the filter `('Is64BitApplication', $false, 'Exact')` finds no x86 apps meet the filter. No apps are removed.
2. Using the filter `('Is64BitApplication', $false, 'Exact'),('Publisher', 'Oracle Corporation', 'Exact')` the documentation provides will ignore the _Is64BitApplication_ filter requirement and removes all Java installations, regardless of bitness.
3. Using the filter `('Is64BitApplication', $false, 'Exact'),('Publisher', 'Fake Publisher', 'Exact')` to test if the _Publisher_ filter yields different results. Only the x86 version is removed, even though the app didn't meet the _Publisher_ filter requirements.

**To Reproduce**
1. Install Java 8 MSI, both x86 and x64
2. Optional: Run `Get-InstalledApplication -Name "Java 8 Update"` to ensure both variants of Java are installed and _Is64BitApplication_ equals False for the x86 version. 
3. Run `Remove-MSIApplications -Name 'Java 8 Update' -FilterApplication ('Is64BitApplication', $false, 'Exact'),('Publisher', 'Oracle Corporation', 'Exact')`

Expected: Per documentation, "Removes all versions of software that match the name "Java 8 Update" where the software is 32-bits and the publisher is "Oracle Corporation"."
Actual: All versions, both x86 and x64, of Java 8 are removed.

**Screenshots**

**Toolkit Version:**
Reproduced in version 3.8.4. Originally noticed in 3.8.1.

**Powershell Version:**
5.1. Tested in a vanilla 1909 VM.

**Additional context**
I'm over my head trying to debug this one, but I've made a tiny bit of progress in case # 1 above. The ForEach in the Remove-MSIApplications function expects $FilterApplication to be an array with multiple values. However, $Filter is not an array, equals "Is64BitApplication" and all the following if statements end up failing because of it. Because we're assuming $Filter is an array, using $Filter[#] ends up equaling individual letters (e.g. $Filter[0] equals **I**, $Filter[1] equals **s**, $Filter[2] equals **6**).

**Comment by guybw** [comment]
Just to add, we see the same issue on 3.8.4 as well.

**Comment by codylc** [comment]
Tagging Issue #338 as it appears to be related.

**Comment by seanlillis** [comment]
This will be fixed in the next release. Thank you!

**Comment by seanlillis** [comment]
Fixed in v3.9.0.
