### ISSUE TITLE
error updating registry 

### ISSUE THREAD

**Issue by Symbiot78** [PSAppDeployToolkit/PSAppDeployToolkit#67]
Hi

Running the following command gives me some errors:

		
		[scriptblock]$HKCURegistrySettings = {
		
		Set-RegistryKey -Key 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.log\OpenWithList\' -Name 'a' -Value "Trace32.exe" -Type string -SID $UserProfile.SID
		Set-RegistryKey -Key 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.log\OpenWithList\' -Name 'MRUList' -Value "a" -Type string -SID $UserProfile.SID
		Set-RegistryKey -Key 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.log\UserChoice\' -Name 'Progid' -Value "Applications\Trace32.exe" -Type string -SID $UserProfile.SID
        Set-RegistryKey -Key 'HKCU\Software\Classes\Log.File\shell\open\command' -Name '(default)' -Value ""C:\Windows\System32\Trace32.exe""%1"" -Type string -SID $UserProfile.SID
		Set-RegistryKey -Key 'HKCU\Software\Classes\.log' -Name '(default)' -Value "Log.File" -Type string -SID $UserProfile.SID
		Set-RegistryKey -Key 'HKCU\Software\Classes\.lo_' -Name '(default)' -Value "Log.File" -Type string -SID $UserProfile.SID
		Set-RegistryKey -Key 'HKCU\Software\Microsoft\Trace32' -Name 'Register File Types' -Value "1" -Type string -SID $UserProfile.SID		
		}
		
		Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $HKCURegistrySettings
		
		Set-RegistryKey -Key 'HKEY_Classes_Root\Applications\Trace32.exe\shell\open\command' -Name '(Default)' -Value "C:\Windows\System32\Trace32.exe "%1"" -Type string
		Set-RegistryKey -Key 'HKEY_Classes_Root\Log.File\shell\open\command' -Name '(Default)' -Value "C:\Windows\System32\Trace32.exe "%1"" -Type string
				

[07-23-2015 15:32:19.079] [Post-Installation] [Set-RegistryKey] :: Update registry key value: [Registry::HKEY_USERS\S-1-5-21-2076390139-1112687530-1544898942-11893\Software\Microsoft\Windows\CurrentVersion\Explorer\F
ileExts\.log\UserChoice\] [Progid = Applications\Trace32.exe].
[07-23-2015 15:32:19.126] [Post-Installation] [Invoke-HKCURegistrySettingsForAllUsers] :: Failed to modify the registry hive for User [HEF_NT\admin-mrt] with SID [S-1-5-21-2076390139-1112687530-1544898942-11893] 
Error Record:
-------------

Message        : Cannot process argument transformation on parameter 'ContinueOnError'. Cannot convert value "System.String" to type "System.Boolean", parameters of this type only accept booleans or numbers, use $tr
                 ue, $false, 1 or 0 instead.
InnerException : System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert value "System.String" to type "System.Boolean", parameters of this type only accept booleans or numbers, use $tru
                 e, $false, 1 or 0 instead. ---> System.Management.Automation.PSInvalidCastException: Cannot convert value "System.String" to type "System.Boolean", parameters of this type only accept booleans or nu
                 mbers, use $true, $false, 1 or 0 instead.
                    ved System.Management.Automation.ArgumentTypeConverterAttribute.ThrowPSInvalidBooleanArgumentCastException(Type resultType, Type convertType)
                    ved System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                    --- Slut på staksporing af indre undtagelser ---
                    ved System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                    ved System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)

FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-RegistryKey

PositionMessage : 
                  At \\aal-sccm01.hef.dk\AppsAndPackages\Tools\trace32\Deploy-Application.ps1:157 char:24
                  +         Set-RegistryKey <<<<  -Key 'HKCU\Software\Classes\Log.File\shell\open\command' -Name '(default)' -Value ""C:\Windows\System32\Trace32.exe""%1"" -Type string -SID $UserProfile.SID

Error Inner Exception(s):
-------------------------

Message        : Cannot convert value "System.String" to type "System.Boolean", parameters of this type only accept booleans or numbers, use $true, $false, 1 or 0 instead.
InnerException : System.Management.Automation.PSInvalidCastException: Cannot convert value "System.String" to type "System.Boolean", parameters of this type only accept booleans or numbers, use $true, $false, 1 or 0
                  instead.
                    ved System.Management.Automation.ArgumentTypeConverterAttribute.ThrowPSInvalidBooleanArgumentCastException(Type resultType, Type convertType)
                    ved System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Message        : Cannot convert value "System.String" to type "System.Boolean", parameters of this type only accept booleans or numbers, use $true, $false, 1 or 0 instead.
InnerException : 




[07-23-2015 15:32:19.142] [Post-Installation] [Invoke-HKCURegistrySettingsForAllUsers] :: Load the User [HEF_NT\admin] registry hive in path [HKEY_USERS\S-1-5-21-2076390139-1112687530-1544898942-1234].
[07-23-2015 15:32:19.204] [Post-Installation] [Invoke-HKCURegistrySettingsForAllUsers] :: Execute ScriptBlock to modify HKCU registry settings for all users.
[07-23-2015 15:32:19.251] [Post-Installation] [Convert-RegistryPath] :: Return fully qualified registry key path [Registry::HKEY_USERS\S-1-5-21-2076390139-1112687530-1544898942-1234\Software\Microsoft\Windows\Current

**Comment by mmashwani** [comment]
I imagine you haven't escaped your quotation marks correctly. Try this:
```
Set-RegistryKey -Key 'HKCU\Software\Classes\Log.File\shell\open\command' -Name '(default)' -Value "`"C:\Windows\System32\Trace32.exe`" `"%1`"" -Type string -SID $UserProfile.SID

```
