### ISSUE TITLE
Show-InstallationPrompt doesn't work when used with "Title" and "NoWait $true parameters.

### ISSUE THREAD

**Issue by wojdar** [PSAppDeployToolkit/PSAppDeployToolkit#673]
Show-InstallationPrompt doesn't work when used with "Title" and "NoWait $true" parameters.
When Title parameter is not specified in ASYNC mode $title variable is set to 'TRUE' value instead of expected $InstallTitle.
So it looks like type conversion issue.

Toolkit Version: 3.8.4

Thank you.

**Comment by mjr4077au** [comment]
This has all been re-written and refactored for v4.
