### ISSUE TITLE
"Execute-Process -WindowStyle Hidden" not hiding windows

### ISSUE THREAD

**Issue by SimpleJack** [PSAppDeployToolkit/PSAppDeployToolkit#678]
**Describe the bug**
As reported in 2020 the command `Execute-Process -WindowStyle Hidden` does not hide windows as expected.

> For those curious - `Maximized` and `Minimized` also do not work as designed.

[(source: b0n3z)](https://discourse.psappdeploytoolkit.com/t/does-not-work-execute-process-windowstyle-hidden/2546/2)

**To Reproduce**

> Working:
> `Start-Process -FilePath “$env:windir\Notepad.exe” -WindowStyle Hidden`
> 
> Fails:
> `Execute-Process -Path “$envWinDir\Notepad.exe” -WindowStyle Hidden`

[(source: b0n3z)](https://discourse.psappdeploytoolkit.com/t/does-not-work-execute-process-windowstyle-hidden/2546/3)

**Toolkit Version:**
3.8.4

**Powershell Version:**
5.1.19041.1237

**Additional context**
This problem seems to exist at least since May '20.
Reference: [Bug Report in Forum](https://discourse.psappdeploytoolkit.com/t/does-not-work-execute-process-windowstyle-hidden/2546)

Thank you for your Support!

**Comment by SimpleJack** [comment]
Is it still possible to pass key presses to the window? That is my ultimate goal. I need to run an installer that doesn't allow silent installation and pass it some key presses in the background to complete the install wizard.

**Comment by mjr4077au** [comment]
This was addressed long ago.
