### ISSUE TITLE
Execute-Process not exiting script on error 1639

### ISSUE THREAD

**Issue by nlt6444** [PSAppDeployToolkit/PSAppDeployToolkit#68]
Hello,
 
 I am using the Execute-Process function to install an application. An error of 1639 is returned and the installation fails however the toolkit continues to run and finally exits successfully. How can I get the toolkit to exit and fail when 1639 is returned?

Thanks

[Installation] :: Executing [C:\*******\scripts\Files\swwi\data\setup.exe /S /v"/QN TRANSFORMS=C:\**********\Files\swwi\data\solidworks.mst"]...	Execute-Process	7/27/2015 12:06:36 PM	2508 (0x09CC)

[Installation] :: Execution completed with exit code [1639].	Execute-Process	7/27/2015 1:07:13 PM	2508 (0x09CC)

[Post-Installation] :: DassaultSystems_Solidworks_2014SP05_x64_EN_SP05 Installation completed with exit code [0].	Exit-Script	7/27/2015 1:07:30 PM	2508 (0x09CC)

**Comment by mmashwani** [comment]
What is the command you are using for Execute-Process from your Deploy-Aplication.ps1 file? What version of the toolkit are you using? Show the complete log so we can see what is going on.

**Comment by nlt6444** [comment]
I will try to replicate this. My QA person reset the virtual machine this on.
