### ISSUE TITLE
Error when trying to run a compiled "PS2EXE" application

### ISSUE THREAD

**Issue by zeeter82** [PSAppDeployToolkit/PSAppDeployToolkit#683]
**My Question/Issue:**
I'm getting an error while trying to execute my application, but this might be normal behavior.  I'm hoping someone can show me a workaround.  I compiled an application using the [PS2EXE](https://github.com/MScholtes/PS2EXE) module available on github, but when I try to launch this with PSADT it doesn't run and produces an error.  The only reason why I'm trying to run this compiled app this way is because I want to hide the actual code as much as possible.  Haha I know it seems convoluted to be running powershell converted to an exe inside another powershell wrapper.  The exe does run correctly and successfully by itself, just not within PSADT.  Any ideas to make this work?

My single install line looks like this:
`Execute-Process -Path '$dirFiles\test_11172021_sccm.exe' -WindowStyle 'Hidden' -PassThru`

**What I have tried so far:**
I tried changing the PS2EXE options around for compiling the exe, but all results produce error when using the different compiled exe's

**Screenshots or additional details:**
Error log:

`<![LOG[[Installation] :: Function failed, setting exit code to [60002]. 
Error Record:
-------------At P:\scripts\test2021_sccm\AppDeployToolkit\AppDeployToolkitMain.ps1:3074 char:35
+ ... ifiedPath = Get-Command -Name $Path -CommandType 'Application' -Total ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
]LOG]!><time="11:02:49.147-300" date="11-17-2021" component="Execute-Process" context="domain\adminuser" type="3" thread="3264" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Error Record:
-------------At P:\scripts\test2021_sccm\AppDeployToolkit\AppDeployToolkitMain.ps1:3315 char:6
+ ...             Throw "Function failed, setting exit code to [$returnCode ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
]LOG]!><time="11:02:49.166-300" date="11-17-2021" component="Deploy Application" context="domain\adminuser" type="3" thread="3264" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Display Dialog Box with message: Error Record:
-------------At P:\scripts\test2021_sccm\AppDeployToolkit\AppDeployToolkitMain.ps1:3315 char:6
+ ...             Throw "Function failed, setting exit code to [$returnCode ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by CosmicSingularity** [comment]
The first thing I noticed is you are using single quotes for the path which
includes a variable ( Execute-Process -Path '$dirFiles\test_11172021_sccm.exe'
-WindowStyle 'Hidden' -PassThru ) . Single quotes means literal, so it is
not resolving the variable. Use double quotes or don't put $dirFiles, since
PSADT by default will look in the path for the exe.

**Comment by zeeter82** [comment]
Wow that was it.  Haha can't believe I missed that.

Thanks for catching that @CosmicSingularity!
