### ISSUE TITLE
Show-InstallationWelcome maximizes app instead of closing it when users choose "Close Programs"

### ISSUE THREAD

**Issue by LeeViewB** [PSAppDeployToolkit/PSAppDeployToolkit#684]
**Describe the bug**
When we deploy a newer version of "Avaya IX Workplace", we prompt the users to close the process if the older version is running at the time of the installation. The process name is "Avaya IX Workplace.exe".
When the users click on "Close Programs", the application maximizes, but it never closes.
This is the Show-InstallationWelcome command we are using:
Show-InstallationWelcome -CloseApps $ProcessesToClose -AllowDeferCloseApps -DeferTimes 5 -PersistPrompt -MinimizeWindows $false -PromptToSave
Log entries: https://pastebin.com/YXAGR9hf

**To Reproduce**
Install Avaya IX Workplace.
Log in the application. (the issue does not present itself if the users are not logged in).
Run the Deploy-Application.ps1
Choose to close applications
It times out after 120
Users get the prompt to defer or close programs again

**Screenshots**

**Toolkit Version:**
3.8.3. Present in 3.7.0 as well. 

**Powershell Version:**
5.1

**Additional context**
Performing the installation in the SYSTEM Context.
![PSADT-AvayaIXworkplace](https://user-images.githubusercontent.com/31350302/142410853-a45edb62-ae89-4d10-8a91-43b0e40334eb.png)

**Comment by cyborgrd** [comment]
Perhaps it can't be closed by wrapper. Try to kill with taskkill and try

**Comment by LeeViewB** [comment]
Using taskkill works like a charm, but that with that the user won't get the nice "Show-InstallationWelcome" prompt with the deferral option

**Comment by cyborgrd** [comment]
i don't know this tool, but i see it has many different windows (LEft, Right, Top, Bottom). I think after closing through wrapper there still some hidden windows . I had also already with one tool, that had many child processes with same title and hidden. I killed this by taskkill with child

`function Kill-Tree {
	Param([int]$ppid)
	Get-CimInstance Win32_Process | Where-Object { $_.ParentProcessId -eq $ppid } | ForEach-Object	{ Kill-Tree $_.ProcessId }
	Write-Log -Message "Kill process ID $ppid " -Source "Kill-Tree"
	
	Stop-Process -Id $ppid -force
}
		
		$GetProc = Get-Process 'start-cmremote'
		#$GetProc
		If ($GetProc) {
			Write-Log -Message "Process $GetProc found" -Source "Kill-Tree"
			$ProcID = $GetProc.Id
			#$ProcID
			Write-Log -Message "ProcID Found $ProcID" -Source "Kill-Tree"
			
			Kill-Tree $ProcID
		}`

**Comment by adipiciu** [comment]
Remove the -PromptToSave argument. This brings the app to front instead of killing the process.

**Comment by LeeViewB** [comment]
> Remove the -PromptToSave argument. This brings the app to front instead of killing the process.

That did the trick, thank you!
