### ISSUE TITLE
Show-InstallationProgress function will NOT move the progress dialog if the -WindowLocation is changed.

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#685]
**Describe the bug**
Show-InstallationProgress function will NOT move the progress dialog if the -WindowLocation is changed.

**To Reproduce**
Steps to reproduce the behaviour:
```
Show-InstallationProgress -StatusMessage "Bottom Right Test" -WindowLocation 'BottomRight'
pause
Show-InstallationProgress -StatusMessage "Top Center test" -WindowLocation 'TopCenter'
pause
```
The progress dialog will stay 'BottomRight' because `$script:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState`  is 'Running'

**Toolkit Version:**
3.8.4 (3.8.5 beta probably...)

**Powershell Version:**
5.1 (Win10-1909)

**quick and dirty Workaround**
```
Show-InstallationProgress -StatusMessage "Bottom Right Test" -WindowLocation 'BottomRight'
pause
Close-InstallationProgress
Show-InstallationProgress -StatusMessage "Top Center test" -WindowLocation 'TopCenter'
pause
```

**FAILED attempted fix for Show-InstallationProgress Function.**

```
		If ($script:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState -eq 'Running') {
			If ($windowLocation -ne $script:ProgressRunspace.SessionStateProxy.PSVariable.Get("windowLocation").Value) {
				Write-Log "windowLocation has been changed. Killing exising progress dialog..."
				Close-InstallationProgress #Needed to move the -WindowLocation to a different location from before
			}
		}
		## Check if the progress thread is running before invoking methods on it
```
**CAVEAT**:  Does not work because `$script:ProgressRunspace.SessionStateProxy.PSVariable.Get("windowLocation").Value`  is null at **_runtime_**.

**Additional recommended change**
Move the progress dialog as to not pile-up progress dialog on top or under Toasts.
```
If ($windowLocation -eq 'BottomRight') {
	#  Put the window in the corner
	$script:ProgressSyncHash.Window.Left = [Double]($screenCenterWidth)
	$script:ProgressSyncHash.Window.Top = [Double]($screenCenterHeight - 100)  #-100 Needed to not overlap system tray Toasts
}
```

**Comment by seanlillis** [comment]
Fixed in v3.9.0.
