### ISSUE TITLE
Greek language

### ISSUE THREAD

**Issue by ipetrocheilos** [PSAppDeployToolkit/PSAppDeployToolkit#690]
**Is your feature request related to a problem? Please describe.**
I do not have a request basically. This tool has helped me with my work and since it's free, I decided to contribute to it by translating the UI to Greek language, in case you wanted to add this to your list of supported languages. I cannot upload the config file as it won't allow me to do so, so I will post the Greek section of the UI here. Thank you very much and I hope you find it helpful. Lnaguage code is "EL".

Translators: Ioannis Petrocheilos, Paraskevi Gioti

		<UI_Messages_EL>
		
		<DiskSpace_Message>Δεν υπάρχει αρκετός αποθηκευτικός χώρος για να ολοκληρώσετε την εγκατάσταση του:
		{0}

		Απαιτούμενος χώρος: {1}MB
		Διαθέσιμος χώρος: {2}MB

		Παρακαλούμε απελευθερώστε αρκετό χώρο για να προχωρήσει η εγκατάσταση.</DiskSpace_Message>
		<ClosePrompt_ButtonContinue>Συνέχεια</ClosePrompt_ButtonContinue>
		
		<ClosePrompt_ButtonContinueTooltip>Πατήστε "Συνέχεια" μόνο αφού κλείσετε τις παρακάτω εφαρμογές.</ClosePrompt_ButtonContinueTooltip>
		
		<ClosePrompt_ButtonClose>Κλείσιμο</ClosePrompt_ButtonClose>
		
		<ClosePrompt_ButtonDefer>Αναβολή</ClosePrompt_ButtonDefer>
		
		<ClosePrompt_Message>Τα παρακάτω προγράμματα πρέπει να κλείσουν για να προχωρήσει η εγκατάσταση.

		Παρακαλούμε αποθηκεύστε την εργασία σας και, στη συνέχεια, κλείστε τα προγράμματα.
		Εναλλακτικά, αποθηκεύστε την εργασία σας και επιλέξτε "Κλείσιμο", για να κλείσουμε εμείς τα προγράμματα για εσάς.</ClosePrompt_Message>
		
		<ClosePrompt_CountdownMessage>ΕΙΔΟΠΟΙΗΣΗ: Τα προγράμματα θα κλείσουν αυτόματα σε:</ClosePrompt_CountdownMessage>
		
		<DeferPrompt_WelcomeMessage>Πρόκειται να εγκατασταθεί η παρακάτω εφαρμογή:</DeferPrompt_WelcomeMessage>
		
		<DeferPrompt_ExpiryMessage>Μπορείτε να επιλέξετε να αναβάλετε την εγκατάσταση μέχρι να λήξει η προθεσμία αναβολής:</DeferPrompt_ExpiryMessage>
		
		<DeferPrompt_WarningMessage>Μόλις παρέλθει η προθεσμία αναβολής, δεν θα έχετε δυνατότητα να αναβάλετε την εγκατάσταση.</DeferPrompt_WarningMessage>
		
		<DeferPrompt_RemainingDeferrals>Υπολειπόμενες αναβολές:</DeferPrompt_RemainingDeferrals>
		
		<DeferPrompt_Deadline>Προθεσμία:</DeferPrompt_Deadline>
		

		<WelcomePrompt_CountdownMessage>Η {0} θα συνεχίσει αυτόματα σε:</WelcomePrompt_CountdownMessage>
		
		<WelcomePrompt_CustomMessage></WelcomePrompt_CustomMessage>
		

		<DeploymentType_Install>Η εγκατάσταση</DeploymentType_Install>
		
		<DeploymentType_UnInstall>Η απεγκατάσταση</DeploymentType_UnInstall>
		
		<DeploymentType_Repair>Η επιδιόρθωση</DeploymentType_Repair>
		

		
		<BalloonText_Start>ξεκίνησε.</BalloonText_Start>
		
		<BalloonText_Complete>ολοκληρώθηκε.</BalloonText_Complete>
		
		<BalloonText_RestartRequired>ολοκληρώθηκε. Απαιτείται επανεκκίνηση.</BalloonText_RestartRequired>
		
		<BalloonText_Error>απέτυχε.</BalloonText_Error>
		
		<BalloonText_FastRetry>δεν ολοκληρώθηκε.</BalloonText_FastRetry>
		

		<Progress_MessageInstall>Εγκατάσταση σε εξέλιξη. Παρακαλώ περιμένετε...</Progress_MessageInstall>
		
		<Progress_MessageUninstall>Απεγκατάσταση σε εξέλιξη. Παρακαλώ περιμένετε...</Progress_MessageUninstall>
		
		<Progress_MessageRepair>Επιδιόρθωση σε εξέλιξη. Παρακαλώ περιμένετε...</Progress_MessageRepair>
		
		<BlockExecution_Message>Η εκκίνηση της εφαρμογής δεν επιτρέπεται προσωρινά, μέχρι να ολοκληρωθεί η εγκατάσταση.</BlockExecution_Message>
		
		<RestartPrompt_Title>Απαιτείται επανεκκίνηση</RestartPrompt_Title>
		
		<RestartPrompt_Message>Για να ολοκληρωθεί η εγκατάσταση, πρέπει να επανεκκινήσετε τη συσκευή σας.</RestartPrompt_Message>
		<RestartPrompt_MessageTime>Παρακαλούμε αποθηκεύστε την εργασία σας και, επανεκκινήστε τον υπολογιστή εντός του προκαθορισμένου χρόνου.</RestartPrompt_MessageTime>
		<RestartPrompt_MessageRestart>Η συσκευή σας θα επανεκκινηθεί στο τέλος της αντίστροφης μέτρησης.</RestartPrompt_MessageRestart>
		
		<RestartPrompt_TimeRemaining>Χρόνος που απομένει:</RestartPrompt_TimeRemaining>
		<RestartPrompt_ButtonRestartLater>Ελαχιστοποίηση</RestartPrompt_ButtonRestartLater>
		<RestartPrompt_ButtonRestartNow>Επανεκκίνηση τώρα.</RestartPrompt_ButtonRestartNow>
	</UI_Messages_EL>

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by seanlillis** [comment]
Thanks for providing the Greek translations, these will be included in the next release.

**Comment by ipetrocheilos** [comment]
I am glad to have contributed to this powerful and helpful tool. Thank you very much!

**Comment by GeoSimos** [comment]
Great work @ipetrocheilos, some better explanation messages could be used for the hard disk space. I haven't fully reviewed the translation, would happily do if you want -and as time allows-, as I have been translating in the past, several community solutions products to the Greek language.

**Comment by seanlillis** [comment]
Fixed in v3.9.0.
