### ISSUE TITLE
The removal of control characters in Get-InstalledApplication function is TOO aggressive

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#691]
**Describe the bug**
The implemented solution in issue  https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/393  is TOO aggressive.

**To Reproduce**
See https://discourse.psappdeploytoolkit.com/t/get-installedapplication-function-issue/3743

**Screenshots**
See https://discourse.psappdeploytoolkit.com/t/get-installedapplication-function-issue/3743

**Toolkit Version:**
For example: 3.8.4

**Powershell Version:**
Assuming 5.1

**Additional context**
[AndreiV](https://discourse.psappdeploytoolkit.com/u/AndreiV) has come up with a more gentile way of removing control characters:
https://discourse.psappdeploytoolkit.com/t/get-installedapplication-function-issue/3743

Essentially, this:
` $appDisplayName = $regKeyApp.DisplayName -replace ‘[^\u001F-\u007F]’,’’`
 would become:
` $appDisplayName = $regKeyApp.DisplayName --replace "[^\p{L}\p{Nd}\p{Z}\p{P}]",''`

**Comment by seanlillis** [comment]
This fix will be applied in the next release, thank you.

**Comment by seanlillis** [comment]
Fixed in v3.9.0.
