### ISSUE TITLE
Grammar "Comprised" is a poor word choice. PSAppDeployToolkit.pdf v3.8.4

### ISSUE THREAD

**Issue by drfloyd5** [PSAppDeployToolkit/PSAppDeployToolkit#692]
**Describe the bug**
Page 4. The text reads "The toolkit is comprised of the following files" The correct verb in this use is "composed". As in "The toolkit is composed of the following files" If you want to keep the emphasis on the toolkit it needs to read "The toolkit comprises the following files".

**To Reproduce**
1. Open PSAppDeployTookit.pdf
2. Find "comprised"

**Screenshots**
<img width="806" alt="Screen Shot 2022-02-16 at 5 28 00 PM" src="https://user-images.githubusercontent.com/5687006/154368104-604c46b5-18f7-4704-a1aa-0308c0652de3.png">

**Toolkit Version:**
3.8.4

**Powershell Version:**
NA

**Additional context**
https://www.grammarly.com/blog/comprise-vs-compose/

* Comprise means “to include” or “to be composed of.” A basketball team comprises five players.
* Comprise is often misused for compose. It’s common for speakers to say that a basketball team “is comprised of five players” instead of “is composed of five players.”
* If you want to be completely safe from criticism, you should use composed of and not comprised of.

**Comment by mjr4077au** [comment]
This PDF is long gone.
