### ISSUE TITLE
Disable Shell-Transform based on Windows regional settings, use only single langugage

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#70]
Hello,

We have "English" language as a standard for all GUI and application settings.
The problem is that PSAppDeployToolkit thinks it's smarter and automatically sets language based on Windows regional settings.
Would be great to have a setting in "AppDeployToolkitConfig.xml" to disable shell transform and force specific language.

**Comment by mmashwani** [comment]
We already have that option in the config xml. It's called InstallationUI_LanguageOverride.
Set it to: EN
