### ISSUE TITLE
Can you please add more info on how to use Set-IniValue and Get-IniValue?

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#703]
**My Question/Issue:**
PSAppDeployToolkit.pdf does not describe the terms used to describe an INI file.  Even the header of the Set-IniValue and Get-IniValue functions don't have this. While I've figured it out, most novices would have just given up. 

By just adding the following to all three, the confusion is gone:

```
The structure of an .INI file is:
[Section]
Key=value
```

**Comment by mjr4077au** [comment]
The PDF mentioned is long gone.
