### ISSUE TITLE
Bug in Set-ActiveSetup

### ISSUE THREAD

**Issue by CSVDK** [PSAppDeployToolkit/PSAppDeployToolkit#707]
In release 3.8.4 you added the following to the Set-ActiveSetup function:
Function now checks the Active Setup registry key to evaluate whether to execute the StubPath based on the IsInstalled property
This has introduced a bug when executing the script as System.

The following code is executed on line 10785 of AppDeployToolkitMain.ps1
   If ((Get-RegistryKey -Key $HKCUActiveSetupKey -SID **$UserProfile.SID** -Value "IsInstalled" -ContinueOnError $true) -ne 1)
The variable $Userprofile is not available when running under the System account.
The line should be:
   If ((Get-RegistryKey -Key $HKCUActiveSetupKey -SID **$RunAsActiveUser.SID** -Value "IsInstalled" -ContinueOnError $true) -ne 1)

Then the script runs perfectly both under the system account as under a normal (Admin) user account.

Hope you can fix this in your next release.
Kr,
Casper

**Comment by headcra6** [comment]
Agree on above, the same issue reproduced for me. Please update Main with the fix

**Comment by seanlillis** [comment]
Fixed in v3.9.0.
