### ISSUE TITLE
variable $dirAppDeployTemp exist but the folder C:\Users\Public\PSAppDeployToolkit is not present when running the toolkit

### ISSUE THREAD

**Issue by ericvanvoorthuizen** [PSAppDeployToolkit/PSAppDeployToolkit#708]
**Describe the bug**
On a clean machine running the toolkit does not create the C:\Users\Public\PSAppDeployToolkit folder
The SCRIPT DIRECTORIES variable $dirAppDeployTemp exist but actions towards that folder could fail because it does not exist
In version 3.8.4 only the Block-AppExecution function will create that folder
In version 3.8.2 only the Block-AppExecution and Execute-ProcessAsUser function will create that folder

Block-AppExecution
		## Delete this file if it exists as it can cause failures (it is a bug from an older version of the toolkit)
		If (Test-Path -LiteralPath "$configToolkitTempPath\PSAppDeployToolkit" -PathType 'Leaf' -ErrorAction 'SilentlyContinue') {
			$null = Remove-Item -LiteralPath "$configToolkitTempPath\PSAppDeployToolkit" -Force -ErrorAction 'SilentlyContinue'
		}
		## Create Temporary directory (if required) and copy Toolkit so it can be called by scheduled task later if required
		If (-not (Test-Path -LiteralPath $dirAppDeployTemp -PathType 'Container' -ErrorAction 'SilentlyContinue')) {
			$null = New-Item -Path $dirAppDeployTemp -ItemType 'Directory' -ErrorAction 'SilentlyContinue'
		}

Execute-ProcessAsUser
		##  Create the temporary App Deploy Toolkit files folder if it doesn't already exist
		If (-not (Test-Path -LiteralPath $dirAppDeployTemp -PathType 'Container')) {
			New-Item -Path $dirAppDeployTemp -ItemType 'Directory' -Force -ErrorAction 'Stop'
		}

**To Reproduce**
1. On clean machine just run the toolkit once
2. No C:\Users\Public\PSAppDeployToolkit is created
3. Put a Execute-ProcessAsUser function in the Deploy-Application.ps1 script
4. Now C:\Users\Public\PSAppDeployToolkit is created

**Screenshots**

**Toolkit Version:**
3.8.2 and 3.8.4

**Powershell Version:**
5.1

**Additional context**

**Comment by seanlillis** [comment]
Can you elaborate on the use case please, which actions towards that directory would fail, are these actions that you are scripting? The directory is only created as required by the functions that use it.
