### ISSUE TITLE
Defining a variable for c:\windows\syswow64

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#719]
Why not using  [Environment]::GetFolderPath([System.Environment+SpecialFolder]::SystemX86) in a variable instead coding $envwindir\syswow64?

Thanks

**Comment by That-Annoying-Guy** [comment]
Maybe it's because this doesn't work in Windows 7.

**Comment by mjr4077au** [comment]
This has been added to v4 and will be in public preview soon.
