### ISSUE TITLE
No log file is being created if you use a / in the $installName or $installTitle override

### ISSUE THREAD

**Issue by StefanDingemanse** [PSAppDeployToolkit/PSAppDeployToolkit#723]
During testing I noticed that after overriding the default Titles via the $installName and $installTitle with a name which includes a / there is no log file being created.

**Comment by SierraEcoBravo** [comment]
Modifying $InstallTitle can be just about anything. However, when you set $InstallName, you cannot use characters that are not allowed in paths. 

Example:
`
	[string]$installName = "$appname`_$appVersion`_$appArch`_$appLang`_$appRevision"
	## Sanity checks on $installName that are bypassed by the override
	[char[]]$invalidFileNameChars = [IO.Path]::GetInvalidFileNameChars()
	[string]$installName = $installName -replace "[$invalidFileNameChars]", '' -replace ' ', ''
	[string]$installName = $installName.Trim('_') -replace '[_]+', '_'
`

**Comment by mjr4077au** [comment]
This has been addressed for the upcoming v4 preview.
