### ISSUE TITLE
Execute-ProcessAsUser fails if the machine returns messages in another language.

### ISSUE THREAD

**Issue by MarsWalker** [PSAppDeployToolkit/PSAppDeployToolkit#725]
If the machine is in French (for example) the function Execute-ProcessAsUser doesn't work correctly.
I think it needs to have this 3 sentences on the XML in order to have to all languages. 

I had to make a overwrite function:
            [string]$PrivStatus     = "Status"
            [string]$PrivRunning    = "Running"
            [string]$PrivLastResult = "Last Result"
            if($currentLanguage -eq "FR"){
                $PrivStatus = "Statut"
                $PrivRunning = "En cours"
                $PrivLastResult = "Dernier r‚sultat"
            }
and then change:
                    While ((($exeSchTasksResult = & $exeSchTasks /query /TN $schTaskName /V /FO CSV) | ConvertFrom-CSV | Select-Object -ExpandProperty **$PrivStatus** -First 1) -eq **$PrivRunning**) {

and also change:
                    [int32]$executeProcessAsUserExitCode = ($exeSchTasksResult = & $exeSchTasks /query /TN $schTaskName /V /FO CSV) | ConvertFrom-CSV | Select-Object -ExpandProperty **$PrivLastResult** -First 1

**Comment by That-Annoying-Guy** [comment]
This affects this section of code:

```
#If on Windows Vista or higer, Windows Task Scheduler 2.0 is supported. 'Schedule.Service' ComObject output is UI language independent
<Snip>



#Windows Task Scheduler 1.0
Else {
	While ((($exeSchTasksResult = & $exeSchTasks /query /TN $schTaskName /V /FO CSV) | ConvertFrom-CSV | Select-Object -ExpandProperty 'Status' -First 1) -eq 'Running') {
		Start-Sleep -Seconds 5
	}
	#  Get the exit code from the process launched by the scheduled task
	[int32]$executeProcessAsUserExitCode = ($exeSchTasksResult = & $exeSchTasks /query /TN $schTaskName /V /FO CSV) | ConvertFrom-CSV | Select-Object -ExpandProperty 'Last Result' -First 1
}
Write-Log -Message "Exit code from process launched by scheduled task [$executeProcessAsUserExitCode]." -Source ${CmdletName}
```

What version of Windows are you running?

**Comment by MarsWalker** [comment]
We are using windows 10 ( 20h2 ). but the issue affects all windows 10

**Comment by MarsWalker** [comment]
PS C:\WINDOWS\system32> Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer

WindowsProductName    WindowsVersion OsHardwareAbstractionLayer
------------------    -------------- --------------------------
Windows 10 Enterprise 2009           10.0.19041.1806

**Comment by equillibrium** [comment]
Same here for me
WindowsProductName    WindowsVersion OsHardwareAbstractionLayer
------------------    -------------- --------------------------
Windows 10 Enterprise 2009           10.0.19041.2251

**Comment by mjr4077au** [comment]
The function `Execute-ProcessAsUser` has been rewritten into `Start-ADTProcessAsUser` for our upcoming v4 preview release. The issue mentioned here won't be a problem moving forward.
