### ISSUE TITLE
Get-UserProfile - can't use all three parameters?

### ISSUE THREAD

**Issue by Alaknar** [PSAppDeployToolkit/PSAppDeployToolkit#727]
I want to get the path to my users' profiles but only the active users' profiles. No system accounts, no default user, no local admin account we create during build.

My line of thinking was to run this:
```powershell
Get-UserProfiles -ExcludeNTAccount "$env:ComputerName\AdminAccount" -ExcludeDefaultUser $True -ExcludeSystemProfiles $True
```

The documentation for [Get-UserProfiles](https://allnewandimproved.psappdeploytoolkit.com/functions/Get-UserProfiles.html#parameters) says that all three of the parameters can be used regardless of Parameter Set ("Parameter Sets: (All)"). 

When I try my command, however, I get this:
```powershell
Get-UserProfiles : A positional parameter cannot be found that accepts argument 'True'.
At line:1 char:1
+ Get-UserProfiles -ExcludeNTAccount "$env:ComputerName\AdminAccount" -Excl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-UserProfiles], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Get-UserProfiles
```

The cmdlet works perfectly fine when I run it with any combination of parameters, as long as I limit it to TWO of them at once.

For instance:
```powershell
Get-UserProfiles -ExcludeNTAccount "$env:ComputerName\AdminAccount" -ExcludeDefaultUser $True
```

Works perfectly fine. Same as when I leave `-ExcludeSystemProfiles` instead of `-ExcludeDefaultUser`, etc.

Am I doing something dumb or is this a bug?

**Comment by powershellking** [comment]
I found the parameter that causes the trouble. ExcludeSystemProfiles is declared to be a boolean parameter but ExcludeDefaultUser is declared to be a switch parameter. However this is very inconsistent as switch parameters should be preferred. So your line of code should look like this:

`Get-UserProfiles -ExcludeNTAccount "$env:ComputerName\AdminAccount" -ExcludeDefaultUser -ExcludeSystemProfiles $True`

**Comment by mjr4077au** [comment]
This function has been re-written for v4 and includes natural/proper switch usage.
