### ISSUE TITLE
Default-User SID

### ISSUE THREAD

**Issue by Friis86** [PSAppDeployToolkit/PSAppDeployToolkit#729]
**My Question/Issue:**
In line 4791 ins AppDeployTookitMain.ps1. The SID for Default User is being set as 'S-1-5-21-Default-User'.
My question is why it is 'S-1-5-21-Default-User' and not '.DEFAULT' to fit with the default in HKEY_USER where the other SIDs are located?

I do notice that I can remove directly registry keys by "Remove-RegistryKey -Key 'HKEY_USERS\.DEFAULT\..."
But as "Invoke-HKCURegistrySettingsForAllUsers" already opens HKEY_USERS to remove foreach users found, I felt .DEFAULT was left out.

Hope my question makes sense.

**Comment by middletonk** [comment]
Apologies for the delayed reply, but you're falling into a common trap of thinking that .DEFAULT represents the actual default user profile. It does not and instead represents the SYSTEM profile, which is a different profile.

To load the actual default profile, which is what Windows typically uses and copies when creating a new first-time user profile on a fresh login, the registry hive in $env:systemdrive\Users\Default\NTUSER.dat must be loaded or mounted. It's most likely that PSADT is loading this hive and then naming it 'S-1-5-21-Default-User' to prevent any naming issues. This would be expected and desired behavior. 

Said another way, PSADT is helping ensure you edit the thing that actually needs editing, which is the default user profile in Windows. The .DEFAULT hive is a bit of an oddball profile for SYSTEM and is not used in the process of creating a new user profile, to my awareness, nor does it typically need editing.

**Comment by mmashwani** [comment]
@middletonk Thanks for answering this question!
