### ISSUE TITLE
Show-BalloonTip error at 3.9.0

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#733]
I get **access denied** at $notifier.Show($toastXml)

[Pre-Installation] :: Error Record:
-------------

Message        : Ausnahme beim Aufrufen von "Show" mit 1 Argument(en):  "Zugriff verweigert (Ausnahme von HRESULT: 
                 0x80070005 (E_ACCESSDENIED))"
InnerException : System.UnauthorizedAccessException: Zugriff verweigert (Ausnahme von HRESULT: 0x80070005 
                 (E_ACCESSDENIED))
                    bei Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
                    bei CallSite.Target(Closure , CallSite , Object , Object )

FullyQualifiedErrorId : UnauthorizedAccessException
ScriptStackTrace      : bei Show-BalloonTip<Process>, C:\Temp\AppDeployToolkit\AppDeployToolkitMain.ps1: Zeile 10606
                        bei Show-InstallationProgress<Process>, C:\Temp\AppDeployToolkit\AppDeployToolkitMain.ps1: 
                        Zeile 10727
                        bei <ScriptBlock>, C:\Temp\Adobe_Acrobat_20.005.30381_x86.ps1: Zeile 245
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1

PositionMessage : In C:\Temp\AppDeployToolkit\**AppDeployToolkitMain.ps1:10606 Zeichen:13**
                  +             $notifier.Show($toastXml)
                  +             ~~~~~~~~~~~~~~~~~~~~~~~~~

Error Inner Exception(s):
-------------------------

Message        : Zugriff verweigert (Ausnahme von HRESULT: 0x80070005 (E_ACCESSDENIED))
InnerException : 

![image](https://user-images.githubusercontent.com/16757493/211876630-03971b7c-b2e2-4e21-bfa2-cfc765f38fae.png)

I run it with admin rights

**Comment by PowershellBacon** [comment]
Same issue here, running under interactive system account from psexec, which we normally would use for SCCM installs, 
![image](https://user-images.githubusercontent.com/35099241/211918361-64e8187e-9cbb-4f25-a07e-ec13ed9f0a9e.png)

**Comment by ekpat** [comment]
Same here:
![2023-01-12_11h17_25](https://user-images.githubusercontent.com/48695338/212040567-80d49b67-dcb2-4063-a4a2-023846f841e7.png)

**Comment by JFPCreations** [comment]
Same here when using ServiceUI.exe to see the popup without admin right in system mode installation. This worked well with 3.8.4.
![RemoteDesktopManagerFree_ekNM9J6m8v](https://user-images.githubusercontent.com/10256543/212068498-8c3791e2-24d9-4be7-b953-c7cf32bf079a.png)

**Comment by JuryA** [comment]
I have the same problem:

![image](https://user-images.githubusercontent.com/11990780/212199875-54d1e77c-b61c-4797-b74b-b4931456d9be.png)

**Comment by DanGough** [comment]
Does the issue go away if you disable balloon tips in the XML config?

I always do this to my template to avoid doubling up on the popups since Intune creates its own already.

**Comment by ekpat** [comment]
> Does the issue go away if you disable balloon tips in the XML config?
> 
> I always do this to my template to avoid doubling up on the popups since Intune creates its own already.

Yes, it does.

`<ShowBalloonNotifications>False</ShowBalloonNotifications>`

**Comment by bshiznit** [comment]
Was looking at pulling a pull request together to move this to Execute-ProcessAsUser if the processuser <> logged in user:
`If ($RunAsActiveUser -and ($RunAsActiveUser.SID -ine $CurrentProcessSID.Value)) {
                Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & {$notifyToastScriptBlock} `'$BalloonTipText`' `'$BalloonTipTitle`' `'$appDeployLogoImage`'" -RunLevel LeastPrivilege
            }
            Else {
                &$notifyToastScriptBlock `'$BalloonTipText`' `'$BalloonTipTitle`' `'$appDeployLogoImage`'
            }`

Moving the XML and other Toast-specific items into a ScriptBlock... but can never seem to get the blue PowerShell window to not pop! I will keep hammering on it but wanted to at least post some breadcrumbs here

**Comment by equillibrium** [comment]
Also I'd like to add up to the issue to not create another one: for some reason when I run "empty" deployapplication.ps1 (without any installation files) the balloon tooltips run okay, when i run it with installation files the balloon tooltip doesn't show any info, just "windows powershell new notification", like it can't show the actual text (installation begin... etc) for some reason

**Comment by hunterp12** [comment]
What has worked for me until they fix it how they want. I just edited it to act sort of like the balloon tips and to either Invoke if running without Admin or Execute-ProcessAsUser. Be sure to fix the other bug under Execute-ProcessAsUser around line 7498 by adding 

```
$EscapedPath = $Path
$EscapedParameters = $Parameters
```
just under 

```
            [String[]]$executeProcessAsUserScript = "strCommand = $executeProcessAsUserParametersVBS"
            $executeProcessAsUserScript += 'set oWShell = CreateObject("WScript.Shell")'
            $executeProcessAsUserScript += 'intReturn = oWShell.Run(strCommand, 0, true)'
            $executeProcessAsUserScript += 'WScript.Quit intReturn'
            $executeProcessAsUserScript | Out-File -FilePath "$executeAsUserTempPath\$($schTaskName).vbs" -Force -Encoding 'Default' -ErrorAction 'SilentlyContinue'
            $Path = "$envWinDir\System32\wscript.exe"
            $Parameters = "`"$executeAsUserTempPath\$($schTaskName).vbs`""
```

Then this is the fix under the Else statement in Show-BalloonTip for the toast section around line 10541. Hope it helps.

 ```
{
           Write-Log -Message "Displaying toast notification with message [$BalloonTipText]." -Source ${CmdletName}

            [scriptblock]$toastScriptBlock  = {
            Param(
                        [Parameter(Mandatory = $true, Position = 0)]
                        [ValidateNotNullOrEmpty()]
                        [String]$BalloonTipText,
                        [Parameter(Mandatory = $false, Position = 1)]
                        [ValidateNotNullorEmpty()]
                        [String]$BalloonTipTitle,
                        [Parameter(Mandatory = $false, Position = 2)]
                        [ValidateNotNullorEmpty()]
                        [String]$AppDeployLogoImage
                    )
            $toastAppId = '{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe'
            [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
            [Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime] | Out-Null

            ## Gets the Template XML so we can manipulate the values
            $Template = [Windows.UI.Notifications.ToastTemplateType]::ToastImageAndText01
            [xml] $ToastTemplate = ([Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent($Template).GetXml())
            [xml] $ToastTemplate = @"
<toast launch="app-defined-string">
	<visual>
		<binding template="ToastImageAndText02">
			<text id="1">$BalloonTipTitle</text>
			<text id="2">$BalloonTipText</text>
			<image id="1" src="file://$appDeployLogoImage" />
		</binding>
	</visual>
</toast>
"@

            $ToastXml = New-Object -TypeName Windows.Data.Xml.Dom.XmlDocument
            $ToastXml.LoadXml($ToastTemplate.OuterXml)


            $notifier = [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($toastAppId)
            $notifier.Show($toastXml)
            }

            If ( -not $IsAdmin) {
            
            Invoke-Command -ScriptBlock $toastScriptBlock -ArgumentList $BalloonTipText, $BalloonTipTitle, $AppDeployLogoImage

            } Else {
            
            Set-Content "C:\Windows\Temp\PSADTToast.ps1" -Value $toastScriptBlock -Force
            $path = "C:\Windows\Temp\PSADTToast.ps1"
            Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command & { & `"C:\Windows\Temp\PSADTToast.ps1 `'$BalloonTipText`' `'$BalloonTipTitle`' `'$AppDeployLogoImage`'`"; Exit `$LastExitCode }" -Wait
            Remove-Item $path -Force
            
            }
            
            sleep -Seconds 5

        }
```

**Comment by seanlillis** [comment]
Thanks for sharing the fix, I have implemented pushed a commit with a modified version of this for the next release v3.9.1.
