### ISSUE TITLE
Set Permission to path error on 3.9.0

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#734]
I get always error in log

[Pre-Installation] :: Failed to set read permissions on path [C:\Users\Public\KPMG\PSAppDeployToolkit\BlockExecution]. The function might not be able to work correctly.

But the permission is set correctly

![image](https://user-images.githubusercontent.com/16757493/211877982-309eaa08-e5c7-4e96-a2c4-70de69116b9c.png)

The error appears also after removing the folder.

**Comment by bshiznit** [comment]
@seanlillis committed yesterday a pr I put on over the summer to fix this https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/dc2f44c88975606a5df389c1b88f8aaad32f5ba8
