### ISSUE TITLE
Problem on getting the Exit-Code from "Execute-MSI" (reopen issue #686)

### ISSUE THREAD

**Issue by NordicAT** [PSAppDeployToolkit/PSAppDeployToolkit#736]
Hello,

First things first: I am glad to see, that the project is still alive! :blush:

I was the reporter of the issue #686 (**Problem on getting the Exit-Code from "Execute-MSI" ...**), which was supposedly fixed in the latest release **v3.9.0**.

I have just downloaded **PSAppDeployToolkit v3.9.0** and started testing. Unfortunately this is still **NOT** working.
The taken steps to reproduce are the same as in issue #686:

I am using `Execute-MSI` on a random MSI-installer (_in this case Putty-x86_) and trying to get the Exit-Code back.
The basic `Deploy-Application.ps1` file contains the following code in the InstallPhase-block:

```
##*===============================================
##* INSTALLATION
##*===============================================
[string]$installPhase = 'Installation'

$Installer = Join-Path -Path $dirFiles -ChildPath "putty-0.78-installer.msi"        
$Result = Execute-MSI -Action Install -Path $Installer -private:$( $installName + "_MSI" ) -PassThru -Verbose
Write-Log -Message "Exit-Code: $($Result.ExitCode)" -Severity 1
```

When the software is **NOT INSTALLED YET**, it **is fine** and I get back the Exit-Code to `$Result.ExitCode`.

`[01-11-2022 10:11:14.828] [Installation] [Deploy-Application] :: Exit-Code: 0`

But when the software is **ALREADY INSTALLED**, I **do NOT** get anything back. `$Result` is empty.

```
[01-11-2022 10:14:32.487] [Installation] [Execute-MSI] :: The MSI is already installed on this system. Skipping action [Install]...
[01-11-2022 10:14:32.502] [Installation] [Deploy-Application] :: Exit-Code:
```

I do NOT notice any difference in the behaviour since the issue #686 was supposedly fixed in **v3.9.0**.

.

**About the Exit-Code, when the MSI is already installed:**
In #686 I mentioned, that I am NOT sure about setting ExitCode "**0**" is correct and wise, when the MSI is already installed!?

The installation does NOT run in this case! In my humble opinion an appropriate ExitCode for this situation should get send back and the [Microsoft reference for MSI-ExitCodes](https://learn.microsoft.com/en-us/windows/win32/msi/error-codes) lists "**1638**" as suitable Exit-Code:

![MSI-ExitCode-1638](https://user-images.githubusercontent.com/42859522/212691526-912d9cf6-4625-4e29-a6f1-d1ecd0435723.png)

Please have another look on this.

Thank you very much! :pray:

**Toolkit Version:**
3.9.0

**Powershell Version:**
5.1

**Comment by seanlillis** [comment]
@NordicAT Please test v3.9.1 and let us know if this resolves the issue.

**Comment by NordicAT** [comment]
@seanlillis I have tested v3.9.1 and it seems to be working fine for me now. :smiley:
Thank you very much! :thumbsup: :ok_hand: :pray: :yellow_heart:
