### ISSUE TITLE
Zero Config - Possibility to handle MSP?

### ISSUE THREAD

**Issue by stgrdk** [PSAppDeployToolkit/PSAppDeployToolkit#74]
Thanks for solving the MST issue that quick.. :+1: 
How about finding a patch file?

For example: installation of Adobe reader:
Files: AcroRead.msi, AcroRead.mst, AcroRdr2015Upd1500630060_MUI.msp, Data1.cab

Most zero config situations there is a single MST and/or MSP.
and in this example that would result in a total zero config installation..

**Comment by mmashwani** [comment]
I just added this feature to the toolkit. Please test and let me know if it's working as expected.

**Comment by stgrdk** [comment]
I have tested and it worked as expected.
I looked at the addition you made on line 9223 in AppDeployToolkitMain.
Maybe you should put "-First 1" in the end, if there are more patches? or perhaps better, check if there is more than one, and then skip it, because how could one know which to install first.?

**Comment by mmashwani** [comment]
If there is more then one MSP, then name them in alphabetical order according to install order. That way the script installs them in the correct order. I will add a comment to that regard.

**Comment by mmashwani** [comment]
Reopening ticket as I will close it when we come out of beta.
