### ISSUE TITLE
Set-ActiveSetup version comparison goes wrong

### ISSUE THREAD

**Issue by Fredaker** [PSAppDeployToolkit/PSAppDeployToolkit#743]
**Describe the bug**
According to the current version validation, the first step is to compare the count of commas. But according to this logic if the HKCU value is 9,9 and HKLM 1,0,0 then active setup will be executed. According to Microsoft logic in this case AS must not be run.

**To Reproduce**
1) Install AS with any version. For example 5,1
2) try to run Set-ActiveSetup -StubExePath "$PSHOME\powershell.exe" -Arguments "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -File `"c:\temp\ActiveSetup.ps1`"" -Description "test" -Key "{841D3F2F-47D0-5FF1-ADV9-52E800421CC4}" -Version "2,1,1"

Expected result: execution of the AS will be skipped because the 5,1 version is newer than the 2,1,1
Actual result: execution for the current user will be performed

**Toolkit Version:**
3.9.1

**Powershell Version:**
5.1

**Comment by mjr4077au** [comment]
All of this code has been refactored for the upcoming v4 preview release. I'll also note you've used commas instead of dots for the version, which could have very well been your problem.

If this is still ongoing with the v4 preview, please let us know.
