### ISSUE TITLE
Toast notifications not honoring icon file

### ISSUE THREAD

**Issue by t7504** [PSAppDeployToolkit/PSAppDeployToolkit#745]
Starting with 3.9.0, PSADT is no longer honoring the custom ico file for the notification title bar.  Still working fine in the "installation progress" title bar, however.

![psadt_notify](https://user-images.githubusercontent.com/13860727/216410387-96961d4f-5a4d-4cd2-b2ea-cf215344abe4.jpg)

**Comment by rodw-wilkins** [comment]
![Icon Not Showing](https://user-images.githubusercontent.com/65082625/220011788-63cbb2c9-b1ec-48bc-8fc8-1a85be788870.jpg)

Still having a strange problem with Toast notification icons I am using script v3.9.2, and oddly it will sometimes show the icon and other times it is blank, but I'm using the same .png file.

**Comment by Fixfinder** [comment]
same here with 3.9.2
<img width="191" alt="Installation_notification" src="https://user-images.githubusercontent.com/127841020/225026951-6adb0615-10eb-4bc1-942b-2d9bcc25df0d.png">
