### ISSUE TITLE
ExcecuteAsUser not working on 3.9.2

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#749]
something wrong with AppDeployToolkitMain.ps1 7434

![image](https://user-images.githubusercontent.com/16757493/217179475-89cf9dcc-dd79-42f2-a845-0014965f2d9d.png)

The $executeAsUserTempPath and $tempPath are empty. executeAsUser fails because

7495  If (Test-Path -LiteralPath $executeAsUserTempPath -PathType 'Container')

 $executeAsUserTempPath is not set

![image](https://user-images.githubusercontent.com/16757493/217181275-32d1d727-6409-4cb6-9c7b-a9a1aa95b7de.png)

**Comment by cyborgrd** [comment]
I thin the error is because the $tempPath is not set prior theís script part. $tempPath is empty 
this compairment is not working

_If ($null -ne $tempPath)_

I set Write Log an this part 

If ($null -ne $tempPath) {             
 Write-Log -Message "Set executeAsUserTempPath to $tempPath"

and got

"Set executeAsUserTempPath to "

I i change

_If ($null -ne $tempPath)_

to 

_If ($tempPath)_

It is working then. i think the $tempPath is not $null but $false

**Comment by cyborgrd** [comment]
Second issue on the same function

The Variable $Wait is set to $false but the wrapper is waiting

 [Switch]$Wait = $false,

[Post-Installation] :: Waiting for the process launched by the scheduled task [PSAppDeployToolkit-ExecuteAsUser] to complete execution (this may take some time)...

Because

![image](https://user-images.githubusercontent.com/16757493/217190435-1311e2a6-6294-475f-b48c-db7c9477b2bd.png)

**Comment by Steve-Jordan** [comment]
I am not a developer, so I don't have any idea on how to update this myself, but I did want to verify that I was having the exact same issue you were having when trying to use the Execute-ProcessAsUser function.

And I also wanted to verify that your fix for changing AppDeployToolkitMain.ps1 on line 7433 as you described below worked perfectly.

```
If ($null -ne $tempPath)

to

If ($tempPath)
```

**Comment by ryanedlund** [comment]
I am going to try it like this (changes in italics): 

If _(($null -ne $tempPath) -and (!($tempPath)))_{             
            $executeAsUserTempPath = $tempPath
            If (($tempPath -eq $loggedOnUserTempPath) -and ($RunLevel -eq "HighestPrivilege")) {
                Write-Log -Message "WARNING: Using [${CmdletName}] with a user writable directory using the HighestPrivilege creates a security vulnerability. Please use -RunLevel 'LeastPrivilege' when using a user writable _directory_." -Severity 'Warning'

**Comment by cyborgrd** [comment]
|<If (($null -ne $tempPath) -and (!($tempPath))){> 

i think it will never happen because $tempPath is not $null

**Comment by ryanedlund** [comment]
> > If (($null -ne $tempPath) -and (!($tempPath))){
> 
> i think it will never happen because $tempPath is not $null

You are correct... I ended up changing by begin section to this:

`Begin {
        ## Get the name of this function and write header
        [String]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
        Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
        Write-Log -Message "TempPath variable set to: $TempPath" -Severity 1 -Source ${CmdletName}
        If ($tempPath -ne ""){
            $executeAsUserTempPath = $tempPath
            If (($tempPath -eq $loggedOnUserTempPath) -and ($RunLevel -eq "HighestPrivilege")) {
                Write-Log -Message "WARNING: Using [${CmdletName}] with a user writable directory using the HighestPrivilege creates a security vulnerability. Please use -RunLevel 'LeastPrivilege' when using a user writable directory." -Severity 2 -Source ${CmdletName}
            }
        }
        Else {
            Write-Log -Message "dirAppDeployTemp variable set to: $dirAppDeployTemp" -Severity 1 -Source ${CmdletName}
            [String]$executeAsUserTempPath = Join-Path -Path $dirAppDeployTemp -ChildPath 'ExecuteAsUser'

        }
        Write-Log -Message "executeAsUserTempPath variable set to: $executeAsUserTempPath" -Severity 1 -Source ${CmdletName} 
    }`

**Comment by ryanedlund** [comment]
The "ValidateNotNullorEmpty()" parameter does not actually prevent that variable from being empty, so when execute-processasuser is called from in a deploy-application.ps1 without a -temppath path defined it fails.

My guess is if we were to add -Temppath to our existing deploy-application.ps1 syntax it would be fine as-is... otherwise changing that line in AppDeployToolkitMain.ps1 from 
If ($null -ne $tempPath){ 
to 
If ($tempPath -ne ""){  
fixes the problem.

There are instances in the main script that call execute-processasuser with -temppath defined, so I'm guessing there are reasons to have it do something different if that's actually populated.

**Comment by ryanedlund** [comment]
The "ValidateNotNullorEmpty()" parameter does not actually prevent that variable from being empty, so when execute-processasuser is called from in a deploy-application.ps1 without a -temppath path defined it fails.

My guess is if we were to add -Temppath to our existing deploy-application.ps1 syntax it would be fine as-is... otherwise changing that line in AppDeployToolkitMain.ps1 from 
If ($null -ne $tempPath){ 
to 
If ($tempPath -ne ""){  
fixes the problem.

There are instances in the main script that call execute-processasuser with -temppath defined, so I'm guessing there are reasons to have it do something different if that's actually populated.

**Comment by ryanedlund** [comment]
> Waiting for the process launched by the scheduled task

I think what you are seeing as a wait there is the command I have copied below, which runs at the end of Show-BalloonTip. Show-Balloon-Tip is called as part of the Show-InstallationProgress and Exit-Script functions (which would explain why your log there has it as a part of the post-installation section).  In my case it only waits briefly on those waits- about 6 seconds - before continuing on and then exiting as expected. 

Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & `"`'$executeToastAsUserScript`' `'$BalloonTipText`' `'$BalloonTipTitle`' `'$AppDeployLogoImage`' `'$toastAppID`' `'$toastAppDisplayName`'`"; Exit `$LastExitCode }" -TempPath $loggedOnUserTempPath -Wait -RunLevel 'LeastPrivilege'

**Comment by bashtech** [comment]
Also seeing the Wait issue.

`Execute-ProcessAsUser -Path "C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\vpnui.exe" -ContinueOnError $true`

`[Post-Installation] :: Triggering execution of scheduled task with command [C:\WINDOWS\System32\wscript.exe /e:vbscript "C:\Users\username\PSAppDeployToolkit\ExecuteAsUser\PSAppDeployToolkit-ExecuteAsUser.vbs"] as the logged-on user [CWOPA\username]...	Execute-ProcessAsUser	2/11/2023 5:07:45 PM	10616 (0x2978)
[Post-Installation] :: [C:\WINDOWS\System32\schtasks.exe] is a valid fully qualified path, continue.	Execute-Process	2/11/2023 5:07:45 PM	10616 (0x2978)
[Post-Installation] :: Working Directory is [C:\WINDOWS\System32].	Execute-Process	2/11/2023 5:07:45 PM	10616 (0x2978)
[Post-Installation] :: Executing [C:\WINDOWS\System32\schtasks.exe /run /i /tn PSAppDeployToolkit-ExecuteAsUser]...	Execute-Process	2/11/2023 5:07:45 PM	10616 (0x2978)
[Post-Installation] :: PassThru parameter specified, returning execution results object.	Execute-Process	2/11/2023 5:07:45 PM	10616 (0x2978)
[Post-Installation] :: Execution completed successfully with exit code [0].	Execute-Process	2/11/2023 5:07:45 PM	10616 (0x2978)
[Post-Installation] :: Wait : True	Execute-ProcessAsUser	2/11/2023 5:07:45 PM	10616 (0x2978)
[Post-Installation] :: Waiting for the process launched by the scheduled task [PSAppDeployToolkit-ExecuteAsUser] to complete execution (this may take some time)...	Execute-ProcessAsUser	2/11/2023 5:07:45 PM	10616 (0x2978)
`

**Comment by ryanedlund** [comment]
> Also seeing the Wait issue.
> 
> `Execute-ProcessAsUser -Path "C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\vpnui.exe" -ContinueOnError $true`
> 
> [Post-Installation] :: Triggering execution of scheduled task with command [C:\WINDOWS\System32\wscript.exe /e:vbscript "C:\Users\username\PSAppDeployToolkit\ExecuteAsUser\PSAppDeployToolkit-ExecuteAsUser.vbs"] as the logged-on user [CWOPA\username]... Execute-ProcessAsUser 2/11/2023 5:07:45 PM 10616 (0x2978)
> 
> [Post-Installation] :: [C:\WINDOWS\System32\schtasks.exe] is a valid fully qualified path, continue. Execute-Process 2/11/2023 5:07:45 PM 10616 (0x2978)
> 
> [Post-Installation] :: Working Directory is [C:\WINDOWS\System32]. Execute-Process 2/11/2023 5:07:45 PM 10616 (0x2978)
> 
> [Post-Installation] :: Executing [C:\WINDOWS\System32\schtasks.exe /run /i /tn PSAppDeployToolkit-ExecuteAsUser]... Execute-Process 2/11/2023 5:07:45 PM 10616 (0x2978)
> 
> [Post-Installation] :: PassThru parameter specified, returning execution results object. Execute-Process 2/11/2023 5:07:45 PM 10616 (0x2978) [Post-Installation] :: Execution completed successfully with exit code [0]. Execute-Process 2/11/2023 5:07:45 PM 10616 (0x2978)
> 
> [Post-Installation] :: Waiting for the process launched by the scheduled task [PSAppDeployToolkit-ExecuteAsUser] to complete execution (this may take some time)... Execute-ProcessAsUser 2/11/2023 5:07:45 PM 10616 (0x2978)

To me, based on the time stamps, that looks like the only wait that is happening is the one that is triggered with the final Show-BalloonTip toast message.  It appears to me that there is no wait on the Execute-ProcessAsUser command that you manually trigger inside deploy-application.ps1, just the one that the main toolkit script calls as part of the Exit-Script function.  Note that the reference to "waiting" comes after the "Execution completed successfully with exit code [0]. " It appears they intentionally want the script to wait until the toast message actually pops up before exiting - if I recall correctly in my logs that was never more than 15 seconds... my guess is that's how long a toast message is being displayed.

**Comment by bashtech** [comment]
The script waited for at least a 1-2 minutes until the scheduled task was manually stopped. Once the Execute-ProcessAsUser command was removed, the script completed a run successfully with no waits so it is definitely a bug with this command.

**Comment by ryanedlund** [comment]
> 

Strange I didn't see that in my case - possibly because I'm forcing System with my execute-processasuser command in deploy-application. 

Has it been tried to remove the -Wait from line 10663 (in the show-balloontip function)? What I don't know is if the toast messages still show properly like that.

Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & `"`'$executeToastAsUserScript`' `'$BalloonTipText`' `'$BalloonTipTitle`' `'$AppDeployLogoImage`' `'$toastAppID`' `'$toastAppDisplayName`'`"; Exit `$LastExitCode }" -TempPath $loggedOnUserTempPath -RunLevel 'LeastPrivilege'

**Comment by PHCVergouwe** [comment]
Simply bluntly copying the Execute-ProcessAsUser function from previous version 3.9.1 solves the $tempPath issue (I would think that adding parameter -TempPath would solve it too but i did not test that)

**Comment by neo42mgn** [comment]
please just use
(![string]::IsNullOrEmpty($tempPath)
