### ISSUE TITLE
Add ability to Get-MsiTableProperty to apply transforms to MSI

### ISSUE THREAD

**Issue by mmashwani** [PSAppDeployToolkit/PSAppDeployToolkit#75]
Add ability to Get-MsiTableProperty function to allow us to apply a list of transforms to an MSI database before reading data from that database.

**Comment by stgrdk** [comment]
Hi, I get this error:

[08-11-2015 13:00:47.953] [PSAppDeployToolkit] :: Failed to process Zero-Config MSI Deployment. 
Error Record:
-------------

Message        : Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'Table'  Key being added: 'Table'"
InnerException : System.ArgumentException: Item has already been added. Key in dictionary: 'Table'  Key being added: 'Table'
                    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
                    at CallSite.Target(Closure , CallSite , Object , String , String )

FullyQualifiedErrorId : ArgumentException
ScriptStackTrace      : at <ScriptBlock>, C:\Users\Test\AppDeployToolkit\AppDeployToolkitMain.ps1: line 9303
                        at <ScriptBlock>, C:\Users\Test\Deploy-Application.ps1: line 90
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\Users\Test\Desktop\AppDeployToolkit\AppDeployToolkitMain.ps1:9303 char:4
                  +             $GetDefaultMsiTablePropertySplat.Add( 'Table', 'File' )
                  +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



Error Inner Exception(s):
-------------------------

Message        : Item has already been added. Key in dictionary: 'Table'  Key being added: 'Table'
InnerException :

**Comment by mmashwani** [comment]
@stgrdk The above issue should now be fixed.

**Comment by stgrdk** [comment]
Testet and works :+1:
