### ISSUE TITLE
Show-BalloonTip Not showing on Win11 OS as SYSTEM

### ISSUE THREAD

**Issue by Gordy-7** [PSAppDeployToolkit/PSAppDeployToolkit#751]
We have the cmdlet show-balloontip for each process for any install which is fine on a win10 OS using the updated PSADT Version. however, nothing is shown on a win11-os as system.

No errors which i can see are in the logs.

It appears to be writing to this:

"'C:\Users\*Username*\PSAppDeployToolkit\ExecuteAsUserPSAppDeployToolkit-ToastNotification.ps1"

It is running as thoyugh it is set as a noninteractive install which is not what we want for loggedin installations.

**Comment by Gordy-7** [comment]
Windows 10 seems to work but isnt using our logos. 

We have downloaded the latest and apparently these issues have been resolved?

**Comment by mjr4077au** [comment]
This code has been thoroughly reworked for our v4 preview which is due out soon.
