### ISSUE TITLE
Package installation fails on FIPS enabled system - Error 60008

### ISSUE THREAD

**Issue by weiner22** [PSAppDeployToolkit/PSAppDeployToolkit#753]
**My Question/Issue:**
I have got FIPS enabled system where I can´t install some NuGet packages, getting error code 60008. I can install same package(s) on FIPS Disabled system. Where is the problem? Using Chocolatey 1.1.0.

**What I have tried so far:**
System says "FIPS Mode detected - run 'choco feature enable -n useFipsCompliantChecksums'
to use Chocolatey." so I have enabled it.
I tried to sign package with codesigning certificate
tried to install manually

**Screenshots or additional details:**
ERROR: Running ["C:\ProgramData\chocolatey\lib\microsoft_monitoring_agent\tools\package\Deploy-Application.exe" -DeploymentType Install -DeployMode Silent] was not successful. Exit code was '60008'. See log for possible error messages.
The install of microsoft_monitoring_agent was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft
[ChocolateyLog.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/10683607/ChocolateyLog.txt)
_monitoring_agent\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by mmashwani** [comment]
I did a little digging into FIPS mode:
https://www.howtogeek.com/245859/why-you-shouldnt-enable-fips-compliant-encryption-on-windows/
https://techcommunity.microsoft.com/t5/microsoft-security-baselines/why-we-amp-8217-re-not-recommending-amp-8220-fips-mode-amp-8221/ba-p/701037

Other than helping me decide I would never enable FIPS mode, I can't imagine why PSADT would fail on a system where FIPS mode was enabled.

Maybe this is more of a Chocolatey problem. Closing this ticket for now but if you discover an issue with PSADT, feel free to open another ticket with those details.
