### ISSUE TITLE
add a -force Parameter to "Copy-File"

### ISSUE THREAD

**Issue by niceguy0815** [PSAppDeployToolkit/PSAppDeployToolkit#754]
Pleas add a -force Parameter to "Copy-File" to override existend files.

**Comment by HpotsirhcH** [comment]
Do you have any Errors you can share or did you tested it? 

Copy-File is always a "Force" Copy

**Comment by niceguy0815** [comment]
Hi i have testet it with the new 3.9 Toolkit and now it overrides in 3.8.x it did not override  for me.
