### ISSUE TITLE
Execute-MSI creates incorrect uninstall logname

### ISSUE THREAD

**Issue by neo42mgn** [PSAppDeployToolkit/PSAppDeployToolkit#759]
Execute-MSI does not remove the .log from -LogName correctly in case of an uninstall Action with a LogName which already contains a .log exstension.

Execute-MSI -LogName "productname.log" -Action Uninstall ...
creates an uninstall logfile called productname.log_Uninstall.log
while
Execute-MSI -LogName "productname.log" -Action Install ...
creates an install logfile called productname_Install.log

**Toolkit Version:**
Version of our toolkit you are using. For example: 3.9.2

**Powershell Version:**
5.1

**Comment by mmashwani** [comment]
Thanks for reporting this. It will be addressed in the next release.
