### ISSUE TITLE
PSADT UI not displaying User UI language

### ISSUE THREAD

**Issue by Tirakk** [PSAppDeployToolkit/PSAppDeployToolkit#760]
**My Question/Issue:**
Hi, I am using PSADT for a while now and came across an issue I can'T track down:

Our helpdesk send me a screenshot, that Show-InstallationWelcome came up in english, even though the UI language of the user was german and the PSADT log also detected de_DE as culture. However the UI popped up in english.

Did anyone see something similar? I thought about user not beeing logged in, but it is.

**What I have tried so far:**
I tried recreating the issue on several of my test machines, but couldn't recreate it.
Googling also came up with nothing.

**Screenshots or additional details:**
![image](https://user-images.githubusercontent.com/77411182/218421204-505485fd-1d46-423a-bc3b-18c74a59ea77.png)

![image](https://user-images.githubusercontent.com/77411182/218421576-8651133b-231c-4d0a-8e7c-0bdc642d3d64.png)

![image](https://user-images.githubusercontent.com/77411182/218421705-a53a54b7-aaeb-4278-bce9-513f13c79f98.png)

**Comment by stephannn** [comment]
Hi,
have you checked the System-UI language? Not sure how it gets triggered

**Comment by Tirakk** [comment]
> Hi, have you checked the System-UI language? Not sure how it gets triggered

Seems to be running in german too (powershell per psexec runas system):

![image](https://user-images.githubusercontent.com/77411182/219057654-9cd54b8c-1f84-4af5-a9b2-2335e2a291e7.png)

**Comment by Tirakk** [comment]
Cannot reproduce.
