### ISSUE TITLE
Set-ActiveSetup stubpath key can not deal with environment variables

### ISSUE THREAD

**Issue by PHCVergouwe** [PSAppDeployToolkit/PSAppDeployToolkit#761]
**Describe the bug**
Set-ActiveSetup sets a registrykey "StubPath". The type of this key is "REG_SZ", which means, any environment variables are read "literally". For environment variables to be interpreted in this key, the type should be "REG_EXPAND_SZ".
For this to be implemented, the two lines in Set-ActiveSetup containing:

Set-RegistryKey -Key $ActiveSetupRegKey -Name 'StubPath' -Value $StubPath -Type 'String'

Should imho preferably be changed to:

Set-RegistryKey -Key $ActiveSetupRegKey -Name 'StubPath' -Value $StubPath -Type 'ExpandString'

**Toolkit Version:**
Version of our toolkit you are using. 3.9.1

**Powershell Version:**
Version of Powershell you are using to run the toolkit. 7.0

**Additional context**
Running on Windows 10 64-bit.

**Comment by mmashwani** [comment]
Thanks for reporting this. It will be addressed in the next release.
