### ISSUE TITLE
Unterminated string constant in PSAppDeployToolkit-ExecuteAsUser.vbs version 3.9.2

### ISSUE THREAD

**Issue by v-Hartline** [PSAppDeployToolkit/PSAppDeployToolkit#762]
Version 3.9.2
When installing in System Context Show-InstallationPrompt or Show-BalloonTip will throw a VBScript error Unterminated string constant in PSAppDeployToolkit-ExecuteAsUser.vbs.

psexec -s "<PATH>\Deploy-Application.exe"

![image](https://user-images.githubusercontent.com/125566690/219366254-22b26c45-3bc2-4bf7-b5fe-4e93084c5e7f.png)

**Toolkit Version:**
3.9.2

**Powershell Version:**
5.1

**Additional context**
The vbs line is formatted correctly it is just too long.  Breaking it up with " &_ works

**Comment by mmashwani** [comment]
Thanks for reporting this. It will be addressed in the next release.
