### ISSUE TITLE
Asynchronous Show-InstallationPrompt at end of installation shows "Installation incomplete" and exit code 1618.

### ISSUE THREAD

**Issue by PHCVergouwe** [PSAppDeployToolkit/PSAppDeployToolkit#763]
**Describe the bug**
At the end of my script, i used the statement:

Show-InstallationPrompt -Message "Test" -MessageAlignment 'Left' -ButtonRightText 'OK' -Icon 'Information' -NoWait -Timeout 60 -ErrorAction SilentlyContinue.

This lets the script continue to the end (which was my aim), but shows a asynchronous message to the user.

Sadly, the asynchronous message shows at timeout (!) a message in the notification area "Installation incomplete" and exits with 1618.
The script itself exits with 0, the asynchronous message exits with 1618 (all visible in the same application logfile).

Digging deeper in the code, i came to find that line 2531-2533 contain:

                If ($ExitOnTimeout) {
                    Exit-Script -ExitCode $configInstallationUIExitCode
                }
And variable $configInstallationUIExitCode:
- sets $installSuccess = $false
- is set by $xmlConfigUIOptions.InstallationUI_ExitCode. Which happens to be 1618.

I would think that having this errorcode set when an asynchronous action is executed, is not always desirable.

**Comment by mjr4077au** [comment]
This has been addressed for the upcoming v4 preview release.
