### ISSUE TITLE
Toast Notification Image Color

### ISSUE THREAD

**Issue by GubbelVogel** [PSAppDeployToolkit/PSAppDeployToolkit#767]
Hello,
the display of the image file for toast notification is incorrect. The icon (a custom icon) is displaying in yellow color. The original image is in blue color.
And it doesn't matter whether the "Install" or the "Uninstall" process is started.
Additional, the BalloonTipTitle is not viewing correctly. Only "PSAppDeployToolkit" is viewing, not the $installTitle.
Please see at screenshot.

I am using Toolkit version 3.9.2
Powershell version 5.1 is using.

![ToastNotifyIcon](https://user-images.githubusercontent.com/36961940/220068759-50a7d14e-66fa-4362-b1c9-37377fc04e8c.jpg)

**Comment by cfreeman21** [comment]
I am also seeing this exact issue with 3.9.2

**Comment by deilsoncso** [comment]
In addition to the color issue, I also noticed that it is not possible to modify the Toast Notification header, is there any way to edit this?

![Screenshot at Feb 28 04-55-58](https://user-images.githubusercontent.com/37881787/221789273-e6f99839-2559-4355-b2f3-67cab6c4db0b.png)

**Comment by GubbelVogel** [comment]
> In addition to the color issue, I also noticed that it is not possible to modify the Toast Notification header, is there any way to edit this?
> 
> I am 3.9.2 version
> 
> ![Screenshot at Feb 28 04-55-58](https://user-images.githubusercontent.com/37881787/221789273-e6f99839-2559-4355-b2f3-67cab6c4db0b.png)



Hi deilsoncso,
if you want it as a "hardcoded" string?
Hardcoded is very simple:
AppDeployToolkitMain.ps1, search for function Show-BalloonTip and inside this function change
$toastAppID = $appDeployToolkitName
to
$toastAppID = '<Your String here>'

**Comment by rodw-wilkins** [comment]
> In addition to the color issue, I also noticed that it is not possible to modify the Toast Notification header, is there any way to edit this?
> 
> I am 3.9.2 version
> 
> ![Screenshot at Feb 28 04-55-58](https://user-images.githubusercontent.com/37881787/221789273-e6f99839-2559-4355-b2f3-67cab6c4db0b.png)

You can see my reply on a similar question here.   https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/778#issuecomment-1444980954

In my case I edit the $appDeployToolkitName itself in AppDeployToolkitMain.ps1.    Not sure which is the preferred method, might depend on your needs.

**Comment by deilsoncso** [comment]
@GubbelVogel  It worked, but I had to change it in "Variables" for it to work, but when running this new version through the Software Center, Toast does not appear, could it be something about permission?

**Comment by deilsoncso** [comment]
> > In addition to the color issue, I also noticed that it is not possible to modify the Toast Notification header, is there any way to edit this?
> > I am 3.9.2 version
> > ![Screenshot at Feb 28 04-55-58](https://user-images.githubusercontent.com/37881787/221789273-e6f99839-2559-4355-b2f3-67cab6c4db0b.png)
> 
> Hi deilsoncso, if you want it as a "hardcoded" string? Hardcoded is very simple: AppDeployToolkitMain.ps1, search for function Show-BalloonTip and inside this function change $toastAppID = $appDeployToolkitName to $toastAppID = "Your String here"

@GubbelVogel It worked, but I had to change it in "Variables" for it to work, but when running this new version through the Software Center, Toast does not appear, could it be something about permission?

**Comment by deilsoncso** [comment]
> > In addition to the color issue, I also noticed that it is not possible to modify the Toast Notification header, is there any way to edit this?
> > I am 3.9.2 version
> > ![Screenshot at Feb 28 04-55-58](https://user-images.githubusercontent.com/37881787/221789273-e6f99839-2559-4355-b2f3-67cab6c4db0b.png)
> 
> You can see my reply on a similar question here. [#778 (comment)](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/778#issuecomment-1444980954)
> 
> In my case I edit the $appDeployToolkitName itself in AppDeployToolkitMain.ps1. Not sure which is the preferred method, might depend on your needs.

Yes I did that and it worked, however when run with Software Center Toast does not appear.

**Comment by GubbelVogel** [comment]
> > > In addition to the color issue, I also noticed that it is not possible to modify the Toast Notification header, is there any way to edit this?
> > > I am 3.9.2 version
> > > ![Screenshot at Feb 28 04-55-58](https://user-images.githubusercontent.com/37881787/221789273-e6f99839-2559-4355-b2f3-67cab6c4db0b.png)
> > 
> > 
> > Hi deilsoncso, if you want it as a "hardcoded" string? Hardcoded is very simple: AppDeployToolkitMain.ps1, search for function Show-BalloonTip and inside this function change $toastAppID = $appDeployToolkitName to $toastAppID = "Your String here"
> 
> @GubbelVogel It worked, but I had to change it in "Variables" for it to work, but when running this new version through the Software Center, Toast does not appear, could it be something about permission?



Hi,
at me it's working with SoftwareCenter (MECM). Do you have set it up in MECM as Hidden installation? Or the other possibility is, that the Parameter $DeployMode at Deploy-Application.ps1 is set to 'Silent'?

At Deploy-Application.ps1 script, before Pre-Installation is running, you "call" the function Show-InstallationProgress? (This function calls automatically the function Show-BalloonTip)

**Comment by Ath3na-UK** [comment]
I am using a custom icon that is transparent the same size as the original and its working fine on W11 22H2 with any them dark or light.

**Comment by rodw-wilkins** [comment]
> I am using a custom icon that is transparent the same size as the original and its working fine on W11 22H2 with any them dark or light.

From my end it seems to sometimes work but most times it does not.   Does the toolkit have explicit image size and transparency requirements for the .png?    I can preview my icons just fine outside of the toolkit but they don't' always show when used for the toast notification.   Sometimes its just blank.

**Comment by Ath3na-UK** [comment]
I think windows caches the icon for the toast related to the name of the toast. For me the default test package no longer displays on my work device, yet if I run the same package on a clean device toast with icon display accurately,

**Comment by Ath3na-UK** [comment]
I think these issues are caused by a windows caching issue, I have been playing around with new icons and now my icons will not display in the very top left of the toast notification. Copy the same script to a clean device it displays fine.

I remember playing around with the toast notification from [MVP]](https://twitter.com/mwbengtsson) and saw a similar thing. If you change the name displayed in the toast notification then its treated as a new application and the icon appears again. (or the correct icon appears) 
change the name on line 106 [String]$appDeployToolkitName = 'test123' and see if your icon is back to normal. Will run a proc mon and see if I can see where it caches it

**Comment by rodw-wilkins** [comment]
> I think these issues are caused by a windows caching issue, I have been playing around with new icons and now my icons will not display in the very top left of the toast notification. Copy the same script to a clean device it displays fine.
> 
> I remember playing around with the toast notification from [MVP]](https://twitter.com/mwbengtsson) and saw a similar thing. If you change the name displayed in the toast notification then its treated as a new application and the icon appears again. (or the correct icon appears) change the name on line 106 [String]$appDeployToolkitName = 'test123' and see if your icon is back to normal. Will run a proc mon and see if I can see where it caches it

Thanks let me know if you find anything.   I would prefer not to have to change the toolkit name for every instance of the script to ensure it loads the icon unless there is no alternative....

**Comment by Ath3na-UK** [comment]
Can't find it, You can reproduce the missing icon fairly easily. On a working package just rename the root package folder with something like an _ at the start, the icon will then not be present in the toast popup

**Comment by rodw-wilkins** [comment]
> 



> Can't find it, You can reproduce the missing icon fairly easily. On a working package just rename the root package folder with something like an _ at the start, the icon will then not be present in the toast popup

Thanks. However this only illustrates that it can't access the file because the expected path to it has changed, but doesn't explain why a file that is present still doesn't show/load correctly each time.

**Comment by mjr4077au** [comment]
I can't reproduce the image colour issue on Windows 11 23H2 and 24H2 targets, and as discussed above, changing toast notification names etc treats it like a new application.

Our v4 public preview is due out soon, where all this code has undergone significant refactoring. If there's still further issues there (beyond known/expected shortcomings of toast notifications), please re-open this issue or create a new one.
