### ISSUE TITLE
Zero Config - handle -CloseApps parameter

### ISSUE THREAD

**Issue by stgrdk** [PSAppDeployToolkit/PSAppDeployToolkit#77]
Hi, what about instead of hardcoded 'iexplore' allow for -CloseApplication "iexplore,chrome"?

Thx so much for all this.. :+1:

**Comment by mmashwani** [comment]
The Deploy-Application.ps1 provided is just a starting off point for you to create your own customized template for that file. I think it makes more sense if you just make that modification in your own template.

**Comment by stgrdk** [comment]
sure thing.. :) I'll do that.
