### ISSUE TITLE
Active setup is failing as $executeAsUserTempPath is empty not $null

### ISSUE THREAD

**Issue by FRacine** [PSAppDeployToolkit/PSAppDeployToolkit#776]
**Describe the bug**
executeAsUserTempPath is appearing as empty but test as $null

**To Reproduce**

Set-ActiveSetup -StubExePath "$var_ActiveSetup83" -Description "Configuration de $var_PackageLongName" -Key "$var_PackageLongName" -Locale 'Fr'

"$var_ActiveSetup83" is: C:\PROGRA~1\ORGANI~1\INSTTR~1\Trousses\WIRESH~1\ACTIVE~1\ACTIVE~1.PS1
"Configuration de $var_PackageLongName" is: Configuration de Wireshark4_Frv1
"$var_PackageLongName" is: Wireshark4_Frv1

On session 0, the issue is appearing but not when run on a user running the script.

```
In AppDeployToolkitMain.ps1, on line 14426 in function Set-ActiveSetup
If ($CUArguments) {
                                **Execute-ProcessAsUser -Path $CUStubExePath -Parameters $CUArguments -Wait -ContinueOnError $true**
                            }
                            Else {
                                Execute-ProcessAsUser -Path $CUStubExePath -Wait -ContinueOnError $true
                            }
```
Then we reach the function Execute-ProcessAsUser
The temppath variable was not pass from Set-Activesetup

```
If ($null -ne $tempPath) {             
            **$executeAsUserTempPath = $tempPath**
            If (($tempPath -eq $loggedOnUserTempPath) -and ($RunLevel -eq "HighestPrivilege")) {
                Write-Log -Message "WARNING: Using [${CmdletName}] with a user writable directory using the HighestPrivilege creates a security vulnerability. Please use -RunLevel 'LeastPrivilege' when using a user writable directoy." -Severity 'Warning'
            }
        }
        Else {
            [String]$executeAsUserTempPath = Join-Path -Path $dirAppDeployTemp -ChildPath 'ExecuteAsUser'
        }

```
The temppath variable is empty not null here.

Then we reach line 7476:
**If (Test-Path -LiteralPath $executeAsUserTempPath -PathType 'Container') {**
            Write-Log -Message "Previous [$executeAsUserTempPath] found. Attempting removal." -Source ${CmdletName}
            Remove-Folder -Path $executeAsUserTempPath
        }

As $executeAsUserTempPath is empty, we get an error message only on session 0.

[Post-Installation] :: Failed to set Active Setup registry entry. 
Error Record:
-------------

Message        : Impossible de lier l'argument au paramètre « **LiteralPath** », car il s'agit d'une **chaîne vide**.
InnerException : 

FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
                        mand
ScriptStackTrace      : à Execute-ProcessAsUser<Process>, 
                        C:\WINDOWS\ccmcache\c\_Include\**AppDeployToolkit\AppDeployToolkitMain.ps1 : ligne 7476**
                        à Set-ActiveSetup<Process>, 
                        C:\WINDOWS\ccmcache\c\_Include\**AppDeployToolkit\AppDeployToolkitMain.ps1 : ligne 14426**
                        à Add-ActiveSetup<Process>, C:\WINDOWS\ccmcache\c\_include\main.ps1 : ligne 3191
                        à <ScriptBlock>, C:\WINDOWS\ccmcache\c\Wireshark4_Frv1.ps1 : ligne 1614

PositionMessage : Au caractère C:\WINDOWS\ccmcache\c\_Include\AppDeployToolkit\AppDeployToolkitMain.ps1:7476 : 36
                  +         If (Test-Path -LiteralPath $executeAsUserTempPath -PathType ' ...
                  +                                    ~~~~~~~~~~~~~~~~~~~~~~
****Toolkit Version:** --> 3.9.2**

****Powershell Version:** --> 5.1**

**Additional context**

You may reproduce the issue by using psexec
By running PSExec -s -i cmd.exe you will get a command prompt on session 0
**If you run Echo %username%, you will get the computername instead your username. This is what we want.**
Then start powershell from the command prompt
Then type ise

**Comment by cyborgrd** [comment]
same here
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/749
