### ISSUE TITLE
Changing Toast Notification title

### ISSUE THREAD

**Issue by unknownsoldier08** [PSAppDeployToolkit/PSAppDeployToolkit#778]
Is it possible to change the default toast title to be something else besides, "PSAppDeployToolkit"?

If so, where could I change it?

![image](https://user-images.githubusercontent.com/96962453/220876998-7f5ef267-837a-4eed-b16b-2a94696b1746.png)

**Comment by rodw-wilkins** [comment]
You can change this in the  Variables section of the AppDeployToolkitMain.ps1.   Not sure if this is the correct/official way but it will display whatever you enter in that string.

![Title](https://user-images.githubusercontent.com/65082625/221334874-127d2e49-c1cf-4c1e-bd87-65d8e38fe1d2.png)

**Comment by deilsoncso** [comment]
Here in addition to this problem, when executed in SCCM it is not working, Toast does not appear running through the Software Center.

**Comment by Ath3na-UK** [comment]
Make your application in sccm interactive via the checkbox.

**Comment by Ath3na-UK** [comment]
> Here in addition to this problem, when executed in SCCM it is not working, Toast does not appear running through the Software Center.

Make your application interactive via the checkbox, works fine for me.

**Comment by Ath3na-UK** [comment]
> Here in addition to this problem, when executed in SCCM it is not working, Toast does not appear running through the Software Center.

Try making your app interactive via the checkbox in SCCM
