### ISSUE TITLE
Autopilot OOBE user [$($CurrentLoggedOnUserSession.UserName)] or ESP process 'wwahost' detected, changing deployment mode to silent.

### ISSUE THREAD

**Issue by dannz87** [PSAppDeployToolkit/PSAppDeployToolkit#779]
**Describe the bug**
I have some deployments switching to silent because of wwahost.exe is present at the wrong moment i guess. 

**To Reproduce**
I've seen it on newly built machines, but reports show that wwahost is ran even later in Windows life in our environment.
My workaround was to exit 0 when waahost is detected. 

**Screenshots**

**Toolkit Version:**
Version of our toolkit you are using. For example: 3.9.2
**Powershell Version:**
5.1 on W10 21H2

**Additional context**

**Comment by mmashwani** [comment]
Thanks for reporting this. You're right that wwahost.exe can be running in other contexts as it is used for rendering JavaScript for Metro based apps in Windows 8 and above. We will address this in the next release with a different detection method for determining whether ESP is running or not.
