### ISSUE TITLE
Execute-Process doesn't work when setting -Path with a variable

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#78]
Hello,

I have implemented the following block for a pre-installation cleanup:
(Script Version - 3.6.4)
```
## <Perform Pre-Installation tasks here>
$foundProducts = Get-InstalledApplication -Name '*Firefox*' -WildCard
Foreach ($foundProduct in $foundProducts) 
{
	if($foundProduct)
	{
		$Command = $($foundProduct.UninstallString)
		$Arguments = "/S"
		[System.Windows.Forms.MessageBox]::Show("$Command $Arguments")
		Execute-Process -Path $Command -Parameters $Arguments -WindowStyle Hidden
		
	}
}
```
And it fails on "Execute-Process" with error:
```
Message        : Exception calling "IsPathRooted" with "1" argument(s): "Illega
                 l characters in path."
InnerException : System.ArgumentException: Illegal characters in path.
                    at System.IO.Path.CheckInvalidPathChars(String path)
                    at System.IO.Path.IsPathRooted(String path)
                    at IsPathRooted(Object , Object[] )
                    at System.Management.Automation.DotNetAdapter.AuxiliaryMeth
                 odInvoke(Object target, Object[] arguments, MethodInformation 
                 methodInformation, Object[] originalArguments)

FullyQualifiedErrorId : DotNetMethodException

PositionMessage : 
                  At C:\Users\%UserName%\Desktop\Mozilla Firefox 38.1.1\R01\MSI\Ap
                  pDeployToolkit\AppDeployToolkitMain.ps1:2339 char:32
                  +             If (([IO.Path]::IsPathRooted <<<< ($Path)) -and
                   ([IO.Path]::HasExtension($Path))) {

Error Inner Exception(s):
-------------------------
Message        : Illegal characters in path.
InnerException : 
```

When I specify values for -Path and -Parameters directly like this:
```
#Execute-Process -Path "C:\Program Files (x86)\Mozilla Firefox\uninstall\helper.exe" -Parameters "/S" -WindowStyle Hidden
```
then it works fine.
When check $Command and $Arguments values with messagebox it looks exact the same.
This is very strange. It though it would by a simple task, but I already tried specifying variables in double quotes, single quotes etc, nothing works. Please help me.

**Comment by mmashwani** [comment]
$Command may look exactly the same but it most likely isn't exactly the same. There is some illegal character in the path. You may not be able to see it in your dialog because the illegal character doesn't display. You will have to examine it in detail and figure out what the illegal character is and remove it or figure out a different way of specifying the correct path.

**Comment by AcidUser85** [comment]
Okay, I have made Write-Log -Message "BBB $Command $Arguments"
and in log file it shows: "C:\Program Files (x86)\Mozilla Firefox\uninstall\helper.exe" /S
Where no illegal characters exits, and this command works from console CMD window.

**Comment by mmashwani** [comment]
Well it looks like $Command has quotation marks in the path. Those are illegal characters for a path. Ger rid of the quotation marks.

**Comment by AcidUser85** [comment]
Thank you! This solved the problem
