### ISSUE TITLE
Show-InstallationProgress: Text not centered

### ISSUE THREAD

**Issue by PaulM87** [PSAppDeployToolkit/PSAppDeployToolkit#780]
**Describe the bug**

We upgraded from PS App Deployment Toolkit v3.8.4 to v3.9.1. In the new version, when using "Show-InstallationProgress", the text is not centered anymore. It seems that the text is moved from center to the right in relation to the size of the rotating progress ellipse on the left side of the text.

**To Reproduce**

Call the Function "Show-InstallationProgress" with a text by your choice.

**Screenshots**

![PSAppDeployToolkit_3 9 1_Show-InstallationPrompt_TextNotCentered](https://user-images.githubusercontent.com/124249315/222710210-17cae165-c18a-4a68-b5d4-0abc56ceec43.png)

**Toolkit Version:**

3.9.1

**Powershell Version:**

5.1

**Additional comments:**

It does not impact the usability of the toolkit, it's just a matter of "beautifulness". :-)

Best regards from Germany,

Paul

**Comment by mmashwani** [comment]
Thanks for reporting this. We will take a look at this again for the next release.
