### ISSUE TITLE
Deploy-application.exe won't call PS1 when package folder contains a single quote

### ISSUE THREAD

**Issue by rebrec** [PSAppDeployToolkit/PSAppDeployToolkit#781]
**Describe the bug**
Calling deploy-application.exe from c:\some'

**To Reproduce**
1. Unzip psadt toolkit to c:\single'quoted-folder
2. CD to that folder
3. powershell.exe -command '. .\deploy-application.exe'  <==== This should work
4. now run directly deploy-application.exe   <=== process starts but powershell file never gets processed

**Toolkit Version:**
Version : 3.8.4

**Powershell Version:**
Version : 5.1

**Comment by That-Annoying-Guy** [comment]
WARNING: I'm going to be blunt and to the point:
1. This should have been posted in https://discourse.psappdeploytoolkit.com/c/thetoolkit/general-discussion/11
2. Folder names ending with a symbol is just begging for trouble as it is not expected and will cause problems if there's ever a space in the path.
3. With the release of PSADT v3.9.2, version 3.8.4 is now 3 versions behind. I'm sorry, this is not going to get fixed.

**Comment by mmashwani** [comment]
The command in step three should not work. You've enclosed the command in single quotes, which tells PowerShell to treat that path as a string literal and not interpret that path. Deploy-Application could be made to handle paths ending in a single quote better, but you could just as easily avoid using single quotes in the path. Like it was stated above, it's just asking for trouble.

I'll keep this open for now to test out this single quote in a path scenario with some changes I'm making already.

**Comment by rebrec** [comment]
1. Sorry for posting this as an issue and not to https://discourse.psappdeploytoolkit.com/c/thetoolkit/general-discussion/11 , it's my entrypoint to github hosted projects.
2. I agree with you, this should be avoided. We have a folder naming convention which include the MSI `Publisher` in its name. Unfortunatly, I had to package an application whose Publisher is calles `Prim'X`
3. Can you confirm it won't be fixed in the latest release either ? I know I don't use latest version but don't understand in what it relates to the problem (from what I read, recent versions don't fix this, right ?)
4. Feel free to close this issue, I only created one after a discussion on this problem in the Winadmin discord channel where folks suggested me to create an issue ;)

Thanks for your time, I don't need a fix at all, was just raising a problem I faced and took me a little time to understand.
It might have been interesting that deploy-applicat.exe at least complains that the folder path naming is not supported instead of just silently do nothing.

Anyways, this is a great project and you do an amazing job in providing it.
Thanks for that
