### ISSUE TITLE
Show-InstallationRestartPrompt

### ISSUE THREAD

**Issue by TekJunki** [PSAppDeployToolkit/PSAppDeployToolkit#785]
**My Question/Issue:**
So I am using PSADTK v3.9.0 and when using Show-InstallationRestartPrompt -Countdownseconds -60 -NoSilentRestart $False, it is not working and my device does not restarts. All I get is the following in the logs and the devices just sit there.
"**Triggering restart silently because the deploy mode is set to Noninteractive and NoSilentRestart is disabled. Timeout is set to 5 seconds**"

**What I have tried so far:**
I have googled the issue and only saw posts from a few versions back as I believe this was an issue in v3.8.4. I have not seen anything about this on the internet for the current version. I have also followed the built-in Help as well but still can not get the system to reboot automatically once the application is installed. 

Thank you everyone for this awesome tool and hoping to get some feedback if I am doing something wrong.

**Comment by TekJunki** [comment]
So just to add more to my issue, in testing in the older version 3.8.4, I was able to use the following command and the device restarted without any issues. So not sure what might have changed that is causing the Restart not to work in the latest release 3.9.0. 

Show-InstallationRestartPrompt -SilentCountdownSeconds 60 -NoSilentRestart $false

-Deployment Type "Install"
-Deployment Mode "Silent"

**Comment by dobbleg1000** [comment]
I'm having this same behavior on 3.9.2 but not when I reverted to 3.8.4

**Comment by dobbleg1000** [comment]
Looking through changes only difference I can find is there was a change from " to ' sometimes between the changes. Might test reverting that and seeing if it fixed my issue

**Comment by dobbleg1000** [comment]
Found it in commit 68d1c47

**Comment by dobbleg1000** [comment]
Confirmed that broke it so I'd be interested to see what other issues changing quotes broke

**Comment by TekJunki** [comment]
Appreciate your feedback on this and this make me feel better that I am not the only one with this issue. Hopefully this will be looked into as I do like this feature a lot. I have been leveraging the v3.8.4 wherever I need the reboot options implemented.

**Comment by dobbleg1000** [comment]
You can run the new command straight up and it doesn't work so the change was not well vetted
