### ISSUE TITLE
Toast Notification on Win10 install shows wrong Message

### ISSUE THREAD

**Issue by LBVNRW** [PSAppDeployToolkit/PSAppDeployToolkit#787]
**My Question/Issue:**
After starting an installation with Toolkit 3.9.2, the toast notification on Win10 shows the following info "New notification" ?
I'm missing the notification like "Installation of xxx has started." or "The installation of xxx has been completed!" as for example under the toolkit version 3.8.4 from which I have now switched to the new one. Unfortunately, as a user, you can't do anything with the current message. Why is that and where can you correct it?
The heading should normally also show the name of the application. This is no longer the case here either.
I would be happy to receive an answer soon.

**What I have tried so far:**
Googling the issue.

**Screenshots or additional details:**
![2023-03-17 13_46_33-Info](https://user-images.githubusercontent.com/128150846/225908791-1c3d43b6-62a5-44fb-90cd-8c9c862aafaa.png)

**Comment by cyborgrd** [comment]
I think i comes from execute as user. I have the same issue.

**Comment by cyborgrd** [comment]
![image](https://user-images.githubusercontent.com/16757493/227140921-a442d5f5-847e-43ad-acd2-0da82246524a.png)

VBS:
`strCommand = chr(34) & "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" & chr(34) & " -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & " & chr(34) & "'C:\Users\USERNAME\PSAppDeployToolkit\ExecuteAsUserPSAppDeployToolkit-ToastNotification.ps1' 'Installation abgeschlossen. Ein Neustart ist erforderlich.' 'Repstor Affinity inkl. Drive' '\\server\PACKAGE\Intapp\Drive\6.1.1_x64\000012536\Work\AppDeployToolkit\AppDeployToolkitLogo.png' 'PSAppDeployToolkit' 'PSAppDeployToolkit'" & chr(34) & "; Exit $LastExitCode }"
set oWShell = CreateObject("WScript.Shell")
intReturn = oWShell.Run(strCommand, 0, true)
WScript.Quit intReturn
`

**Comment by LBVNRW** [comment]
I run the script from the server with an admin account as usual. As I said in the above version, it still worked. Unfortunately not in this one. What can I do now? By the way, in the log file it looks as if the correct text is being tried to post. Unfortunately, the result looks like in the picture.

**Comment by cyborgrd** [comment]
It runs (Toast) in user context, i have only this issue when i run from server. My loggedon user has no acces to \\server\PACKAGE\Intapp\Drive\6.1.1_x64\000012536\Work\AppDeployToolkit\AppDeployToolkitLogo.png. That was the issue.  I i run locally everything is ok

**Comment by cyborgrd** [comment]
Do you have the same problems even running from C:\Windows\ccmcache?

**Comment by mjr4077au** [comment]
All of this code has been significantly refactored for our upcoming v4 preview.
