### ISSUE TITLE
Set-ActiveSetup runs StubExePath Command immediatly for Current User, but doesnt set the Active Setup Key

### ISSUE THREAD

**Issue by ghost** [PSAppDeployToolkit/PSAppDeployToolkit#789]
**My Question/Issue:**
Set-ActiveSetup runs the command immediatly for Current User but doesnt set the Active Setup Component Key in HKCU aswell.

So, when this user log off and on again, it will be executed again. 

Do you think this is intentional or a bug?

**Comment by seanlillis** [comment]
If Active Setup is executed for the current user immediately, the HKCU key should also be set. Could you share the log files please?

**Comment by mjr4077au** [comment]
This has been addressed in our upcoming v4 preview release.
