### ISSUE TITLE
Show-InstallationWelcome window bugged on 4k screens with higher DPI value

### ISSUE THREAD

**Issue by wfi-jonas** [PSAppDeployToolkit/PSAppDeployToolkit#792]
**Describe the bug**
Our laptops all have 4k built-in screens. We tested with ADT 3.8.4 and 3.9.2 and noticed that when using the Show-InstallationWelcome function, the window size and text is cropped so much it isn't a nice display since Windows 11. When we started on W10 1-2 years ago we didn't had this issue using ADT 3.8.4.

**To Reproduce**
1. Connect laptop to 4k external screen or test on laptop with built-in 4k screen using Windows 11 (22H1 or 22H2) (I know.. )
2. Confirm DPI scaling in Windows is something high like on my laptop it's by default 250%
3. Run ADT application while having the following code in your Powershell script:   Show-InstallationWelcome -CloseApps 'msedge' -BlockExecution -AllowDeferCloseApps -DeferTimes 3 -MinimizeWindows $false -TopMost $true

**Screenshots**

**Toolkit Version:**
tested in 3.8.4 and 3.9.2

**Powershell Version:**
5.1.22621.963

**Additional context**

**Comment by Pollewops** [comment]
Can tell that I see the same behavior and would like to help to get this resolved. If I need to test some changes I really like to do so.

**Comment by rickardmkvist** [comment]
We also have the same issue, not sure how I can resolve this.  Anyone have a solution yet?

**Comment by sintaxasn** [comment]
I'm going to try to dig into this this evening

**Comment by Pollewops** [comment]
Is this also tested with 3.9.3 version?

**Comment by rickardmkvist** [comment]
Yes. I tested it with an older version and the latest version.

**Comment by Pollewops** [comment]
@sintaxasn did you find something?

I also tested yesterday evening and got the issue also with the latest version.

I guess more and more people will run into this issue, since more displays are 4k these days.

**Comment by BrookTownsend** [comment]
I'm also having this issue in my environment. Most of our laptops are 150% scaling by default so popups look pretty bad.

**Comment by BrookTownsend** [comment]
@sintaxasn it appears to be happening if running PSADT as a user other than the one currently signed into Windows.

I can see the DPI scale factor and DPI pixels are incorrect when running PSADT under my admin account while signed into Windows with my standard account. 

Incorrect DPI values run under different user that's not currently signed in:
`[10-11-2023 14:41:56.413] [Initialization] [PSAppDeployToolkit] :: The active logged on user [Admin] has a DPI scale factor of [100] with DPI pixels [96].
`

Correct values when running PSADT under account that is currently signed in:
`[10-11-2023 14:08:42.179] [Initialization] [PSAppDeployToolkit] :: The active logged on user [Standard] has a DPI scale factor of [175] with DPI pixels [168].`

**Comment by Pollewops** [comment]
Humm that make sence.So the dpi is not correctly obtained from the logged on user.Met een glimlach,JohanOp 11 okt 2023 om 19:50 heeft Brook Townsend ***@***.***> het volgende geschreven:﻿
@sintaxasn it appears to be happening if running PSADT as a user other than the one currently signed into Windows.
I can see the DPI scale factor and DPI pixels are incorrect when running PSADT under my admin account while signed into Windows with my standard account.
Incorrect DPI values run under different user that's not currently signed in:
[10-11-2023 14:41:56.413] [Initialization] [PSAppDeployToolkit] :: The active logged on user [Admin] has a DPI scale factor of [100] with DPI pixels [96]. 
Correct values when running PSADT under account that is currently signed in:
[10-11-2023 14:08:42.179] [Initialization] [PSAppDeployToolkit] :: The active logged on user [Standard] has a DPI scale factor of [175] with DPI pixels [168].

**Comment by mjr4077au** [comment]
HiDPI support was added for v3.10 and is working well.
