### ISSUE TITLE
Problem detecting Intune provisioning phase.

### ISSUE THREAD

**Issue by LFM8787** [PSAppDeployToolkit/PSAppDeployToolkit#801]
Hi there, I encountered a problem with the following line in Intune deployments:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/03cf254ab05522b0d52addbd7fec612f93aadb91/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L16142

As you can see in the log, the username is not populated:
![image](https://user-images.githubusercontent.com/13755139/235117114-952b3e6c-7fad-4395-8e82-6d7b265333d1.png)

Also, I've encountered several scenarios when wwahost is running or suspended even if Intune is installing something or not. So, the logical evaluation will always be true.

I've changed it to:

```PowerShell
$RunAsActiveUser.NTAccount -like '*\defaultuser0' -and (((Get-Process -Name 'wwahost' -ErrorAction 'SilentlyContinue').count) -gt 0)
```

This way one can be 99% sure it's the provisioning phase or white glove.

**Comment by seanlillis** [comment]
Thanks @LFM8787, will be added to the next release
