### ISSUE TITLE
Variable $isMultiSessionOS returns false on Windows 11 Enterprise multi-session

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#807]
**Describe the bug**
The variable $isMultiSessionOS returns false on Windows 11 Enterprise multi-session, it should be set to true.

**Screenshots**
![image](https://user-images.githubusercontent.com/15003329/236557397-7f29f2f9-8aa2-4bea-a300-5a51c198b8b2.png)

**Toolkit Version:**
3.9.3

**Powershell Version:**
5.1

**Comment by seanlillis** [comment]
This will be resolved in the next release, thanks!
