### ISSUE TITLE
Extended CloseApps (feature request)

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#81]
Hello,

Sometimes there is need to close only specific process, which may be running multiple with same name.
For example you have a PC running multiple java applications. Of course there will be multiple javaw.exe processes running. But those differ by process parameters such as working directory, arguments, path, etc. During install and uninstall it is needed to close only particular process, not all java applications. What if application executable name is the same as other important windows process? In this case -CloseApps also cannot be used, but if there would be setting to specify location of running executable and/or working directory, etc, it would close exactly required processes.
Would be great to have such options in newer versions. I had such smart close conflicting processes in my own written vbscript deployment wrapper, but some time ago we decided to migrate to PSAppDeployToolkit and my powershell knownledge is poor to implement this.

**Comment by That-Annoying-Guy** [comment]
I did something like this but I had to use WMI b/c Get-Process does not return the CommandLine

	[System.Array]$popupTasks = Get-WmiObject Win32_Process -Filter "name = 'Powershell.exe'" | select CommandLine, ProcessId

	ForEach ($popupTask in $popupTasks) {
		If ( $($popupTask.CommandLine) -match "POPUP" ) {
			Write-Host "Killing [$($popupTask.CommandLine)] "
			Write-Host $popupTask.ProcessId
			Stop-Process -Id $($popupTask.ProcessId) -Force
		}
	}

**Comment by amotaz** [comment]
I really like this, and I've developed some code for this, but it will fundementally change the Show-InstallWelcome function so, I'll add the code in once we're ready for V4

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/extended-closeapps-feature-request/1231

**Comment by mjr4077au** [comment]
This has been added into our develop branch and will be in 4.1.0.

The commit https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/9145690ded862d75fd7d1750ff4b77db79685c12 allows one to perform filtration on each ProcessObject passed through to `Show-ADTInstallationWelcome` based on any property that's within a `System.Diagnostics.Process` object.

An example use of this would be:
```PowerShell
Show-ADTInstallationWelcome -CloseProcesses @{ Name = 'javaw', Filter = { $_.Path -like "C:\Program Files\*" } }
```

Such filtration does not apply to the block execution code.

The commit https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/b8a4a9a4ed748e2b98a1c48ce495e17107c61348 adds CommandLine and Arguments properties to the `System.Diagnostics.Process` objects. These can be used with filtration.

The commit https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/95b6a60a44e0ff6ee29a240232787692d1e8e24d allows processes to be specified by an absolute path, not just a process name. If there's multiple `javaw.exe` instances running, this is a quick way to provide filtration on specific paths only. This is also hooked up in the block execution code.

I considered making `-CloseProcesses` just accept a filter script directly for setups like `Show-ADTInstallationWelcome -CloseProcesses { $_.ProcessName -eq 'javaw' }`, and this would work for closing of apps but such a setup doesn't work with the block execution code, where we need a process name no matter what.

**Comment by mjr4077au** [comment]
This has been re-opened as the setup requires re-thinking before we release 4.1.0 as the code needs to run outside of a PowerShell environment via the PSADT display server.

**Comment by mjr4077au** [comment]
Reference links so I don't lose them. Shared to me by the author of the project.

https://github.com/santisq/PSParallelPipeline
https://github.com/santisq/PSParallelPipeline/blob/main/src/PSParallelPipeline/Extensions.cs#L45-L63
https://github.com/santisq/PSParallelPipeline/blob/main/src/PSParallelPipeline/Extensions.cs#L65-L165

**Comment by neo42JBR** [comment]
> This has been re-opened as the setup requires re-thinking before we release 4.1.0 as the code needs to run outside of a PowerShell environment via the PSADT display server.

Throwing in [PSLambda](https://github.com/SeeminglyScience/PSLambda) as reference.
It translates the PowerShell-AST in LINQ Expressions. Very complex, but one could keep the PS syntax.

**Comment by mjr4077au** [comment]
Looks interesting but seems abandoned. I'll keep it in mind though
