### ISSUE TITLE
Typo on page 5 of PSAppDeployToolkit.pdf

### ISSUE THREAD

**Issue by dtammam** [PSAppDeployToolkit/PSAppDeployToolkit#810]
Super small error, but in the PSAppDeployToolkit.pdf, on page 5 it says 'Simplifies deployment troubleshooting The PSAppDeployToolkit best practice workflow uses robust functions that handle errors and exceptions gratefully' when I think it meant to say 'gracefully'

**Comment by mjr4077au** [comment]
The PDF is long-deprecated, our website is the source of truth now.
