### ISSUE TITLE
Enforce language for entire app

### ISSUE THREAD

**Issue by malvinportner** [PSAppDeployToolkit/PSAppDeployToolkit#811]
**My Question/Issue:**
For my use case, I would like to force only one language for the toolkit so it does not depend on the devices language Settings.

**What I have tried so far:**
I set the Variable "appLang" to "DE"  in the Deploy-Application.ps1 Script.

Is there a possibility to do this?

**Comment by tw-321** [comment]
You can set this in AppDeployToolkit\AppDeployToolkitConfig.xml --> Line 88: 
  <InstallationUI_LanguageOverride>SV</InstallationUI_LanguageOverride>

        <!-- Specify a static UI language using the one of the Language Codes listed below to override the language culture detected on the system.

![pic2](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/139440923/481ead4b-fcdf-4822-bdf2-a44d66ee47a0)

**Comment by malvinportner** [comment]
Thanks a lot, this worked.
