### ISSUE TITLE
UI Options: Language culture Detection

### ISSUE THREAD

**Issue by thomashesse** [PSAppDeployToolkit/PSAppDeployToolkit#82]
### Env
* Windows 7 x64 **MUI**
* PSAppDeployToolkit 3.6.5 Milestone 2

### Error
PSADT UI is english although there would have to be german.

### Solution
Swap the section / Change the order of the section "#  Read language for Win 8 machines" with "#  Read language for Win Vista/Win 7 machines" in AppDeployToolkitMain.ps1 Line  ~250

**Comment by mmashwani** [comment]
I think the Win 8 machine language check isn't even necessary and we can just get rid of it.

**Comment by mmashwani** [comment]
@thomashesse This has been fixed in the latest 3.6.6 beta. Please test and let me know if it's working as expected now.

**Comment by thomashesse** [comment]
The UI language Detection (with Win7 MUI) works now.
