### ISSUE TITLE
Installation error because cant remove BlockExecution\AppDeployToolkitBanner.png

### ISSUE THREAD

**Issue by Hardexit** [PSAppDeployToolkit/PSAppDeployToolkit#820]
**Describe the bug**
When I run the installation, a temporary file cannot be deleted and thus the installation fails.

**To Reproduce**
Run the Deploy-Application.exe in the system context, like intune does.

**Screenshots**
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/112691363/b2ea9518-7873-469d-9a61-76c4d60ac24a)

**Toolkit Version:**
3.9.3

**Powershell Version:**
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  1335
```

**Additional context**
```
Show-InstallationWelcome -CloseApps notes2 -MinimizeWindows $false -BlockExecution -AllowDefer -DeferDays 3
```
If i execute the .ps1
```
Error Record:
-------------

Message        : Das Element C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution\AppDeployToolkitBanner.png kann nicht
                 entfernt werden: Der Prozess kann nicht auf die Datei "AppDeployToolkitBanner.png" zugreifen, da sie
                 von einem anderen Prozess verwendet wird. Das Element
                 C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution kann nicht entfernt werden: Das Verzeichnis ist
                 nicht leer.

InnerException :

FullyQualifiedErrorId : Das Element C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution\AppDeployToolkitBanner.png kann
                        nicht entfernt werden: Der Prozess kann nicht auf die Datei "AppDeployToolkitBanner.png"
                        zugreifen, da sie von einem anderen Prozess verwendet wird. Das Element
                        C:\Windows\TEMP\PSAppDeployToolkit\BlockExecution kann nicht entfernt werden: Das Verzeichnis
                        ist nicht leer.

ScriptStackTrace      : bei Remove-Folder<Process>, C:\Temp\IBM Notes\AppDeployToolkit\AppDeployToolkitMain.ps1: Zeile
                        4975
                        bei Unblock-AppExecution<Process>, C:\Temp\IBM
                        Notes\AppDeployToolkit\AppDeployToolkitMain.ps1: Zeile 8308
                        bei Exit-Script, C:\Temp\IBM Notes\AppDeployToolkit\AppDeployToolkitMain.ps1: Zeile 1677
                        bei Execute-Process<Process>, C:\Temp\IBM Notes\AppDeployToolkit\AppDeployToolkitMain.ps1:
                        Zeile 4503
                        bei Execute-MSI<Process>, C:\Temp\IBM Notes\AppDeployToolkit\AppDeployToolkitMain.ps1: Zeile
                        3657
                        bei <ScriptBlock>, C:\Temp\IBM Notes\Deploy-Application.ps1: Zeile 146
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1

PositionMessage : In C:\Temp\IBM Notes\AppDeployToolkit\AppDeployToolkitMain.ps1:4975 Zeichen:21
                  +                     Throw $ErrorRemoveFolder
                  +                     ~~~~~~~~~~~~~~~~~~~~~~~~




[07-04-2023 16:40:57.150] [Installation] [Exit-Script] :: IBM_Notes_10.0.1FP7_01 Installation completed with exit code [1603].
```

**Comment by Ath3na-UK** [comment]
Try it on a cleanly built windows 11 device, using this in production for a few apps now to all devices with no issues. It could be something in your environment causing the issue,

**Comment by Hardexit** [comment]
I received the error on a newly installed notebook.

**Comment by That-Annoying-Guy** [comment]
I don't know German but it could be the same issue as #822 

As per #822: Changes required to resolve:
- Edit \AppDeployToolkit\AppDeployToolkitMain.ps1
- Search for $appDeployLogoBannerObject.Dispose($true)
- Replace with $appDeployLogoBannerObject.Dispose()

If this works, please reply as such.

**Comment by Oliver495** [comment]
I got the same error message as Hardexit:
Installing two packages with our software deployment software under system context.

1. a package is installing Firefox under system account and displaying the message "Das Starten dieser Anwendung(en) wurde vorübergehend blockiert, damit der Installationsvorgang erfolgreich durchgeführt werden kann." -> that's ok, because in PSADT-Script i have:

Show-InstallationWelcome -CloseApps 'firefox=Firefox Browser' -CheckDiskSpace -RequiredDiskSpace 500 -DeferTimes 2 -ForceCloseAppsCountdown 5400 -AllowDeferCloseApps -PersistPrompt -BlockExecution
---
Now i do NOT close the message box with OK

2. a second package is installing Thunderbird and chrashes with the same error like "Hardexit" got

---
The workaround from "That-Annoying-Guy" #822 works -> THANKS!!!

**Comment by mjr4077au** [comment]
This has been addressed for the upcoming v4 public preview.
