### ISSUE TITLE
Add Write-Log parameter for Green color coded message 

### ISSUE THREAD

**Issue by JonathanPitre** [PSAppDeployToolkit/PSAppDeployToolkit#821]
**Describe the solution you'd like**
With the Write-Log cmdlet, we are able to send host messages with the colors white, yellow and red.

Here's an example:

` Write-Log -Message "Hello world!" -Severity 1 -LogType  CMTrace -WriteHost $True`

Severity 1 is White
Severity 2 is Yellow
Severity 3 is Red

There are many cases where I wish I could send **Green** messages to the host so the admin executing the script would get highlighted feedback.

Please consider adding a Severity 0 parameter for the Green color.

` Write-Log -Message "Hello world!" -Severity 0 -LogType  CMTrace -WriteHost $True`

Thank you!

**Comment by That-Annoying-Guy** [comment]
I had this in an old fork of PSADT.
I remember it being somewhat trivial to add.
Selecting the proper color combinations was the hard part.

**Comment by NordicAT** [comment]
+1
