### ISSUE TITLE
No Title on Baloon if Text is containing sign "&"

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#823]
**[string]$installTitle = 'D&A'**

![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/16757493/2fc2dcdd-32eb-4c21-ac75-6ef728b6d0ec)

[string]$installTitle = 'DA'

![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/16757493/1923fda6-d943-4cff-ac2c-52eb59533cfc)

**Comment by mjr4077au** [comment]
This has been addressed for the upcoming v4 public preview.
