### ISSUE TITLE
Inconsistent AppDeployToolkitBanner.png size restrictions

### ISSUE THREAD

**Issue by forderud** [PSAppDeployToolkit/PSAppDeployToolkit#826]
[AppDeployToolkitBanner.png](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/Toolkit/AppDeployToolkit/AppDeployToolkitBanner.png) have since ee5fd4771259546aa6982d49988ff4141577fed1 grown from 450 x 50 to 450 x 75 pixel size.

This is inconsistent with the following documentation:
* [Toolkit-Usage.md](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/wiki/Toolkit-Usage.md) that claims the PNG must be 450 x 50 in size.
* [PSAppDeployToolkit.pdf](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/PSAppDeployToolkit.pdf) that claims the PNG must be 450 x 50 in size.

**Comment by mjr4077au** [comment]
There's no such restrictions in place since v3.10.

**Comment by forderud** [comment]
Thanks a lot @mjr4077au
