### ISSUE TITLE
Add Toolkit option to NOT append to logfile

### ISSUE THREAD

**Issue by Skeb1ns** [PSAppDeployToolkit/PSAppDeployToolkit#829]
I've setup an Azure Storage account and want to upload failed log files to it (modified Deploy-Application.ps1 to achieve this). However, to keep the size of the logfile to the minimum I would like the option to NOT append to the main log file but to remove an existing one and create a new one each time a deployment runs.

I've added a Test-Path and Remove-Item in the meantime to overcome this but a built in flag in the Config.xml would be helpful :)

**Comment by seanlillis** [comment]
Great idea, thanks! This will be included in the next release.
