### ISSUE TITLE
WelcomePrompt_CountdownMessage not translated in French

### ISSUE THREAD

**Issue by gdordain8** [PSAppDeployToolkit/PSAppDeployToolkit#831]
Hello,

We notices that WelcomePrompt_CountdownMessage is not translated in french in the AppDeployToolkitConfig.xml.

Could you fix it please ?

Regards,
Guillaume

**Comment by gdordain8** [comment]
For information we changed it to : 

> Le {0} va continuer automatiquement:

**Comment by DanGough** [comment]
Already committed here:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/6d6d353f1586a50ccf12d4c817a44442f4fa39c7

And subsequently replaced by:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/1019/commits/61af5878138c9d66a9a7e13dd60a7a02f6caf56f
