### ISSUE TITLE
Change with Show-InstallationWelcome and "Continue" button

### ISSUE THREAD

**Issue by gdordain8** [PSAppDeployToolkit/PSAppDeployToolkit#833]
Hello,

When we use the option "Defer" and the switch "closeapps" With Show-InstallationWelcome, we think that the button "Continue" is confusing for the end user. If you click on it, nothing will happen, just the prompt keeping  showing up. (End user don't like to read too much, and to be honest we found it confusing too, as SCCM Admins.)

We tried to change the variable $buttonContinue.Visible = $false to not show the button, but the two other buttons are not centered, and if  the closeapps applications are not running, we'll just have a window, only asking to defer the installation, so the defer option become useless. 

We'd rather have 2 buttons : 
- One showing "Close Programs and Continue" (or just Continue if the processes specified are not launched)
- One Showing "Defer"

We think that it would be easier to use for the end user.

**Comment by mjr4077au** [comment]
Done with the v4 UI! 🥳
