### ISSUE TITLE
Get-HardwarePlatform - Add Parallels Virtual Machine

### ISSUE THREAD

**Issue by biloumaxou** [PSAppDeployToolkit/PSAppDeployToolkit#838]
**Is your feature request related to a problem? Please describe.**
When calling Get-HardwarePlatform from Parallels Virtual Machine, the function returns only the string "Virtual".

**Describe the solution you'd like**
In the same way Get-HardwarePlatform returns "Virtual:VMWare" or "Virtual:Hyper-V", I would like Get-HardwarePlatform returns "Virtual:Parallels".
To do this just add the following condition
`ElseIf ($hwBIOS.SerialNumber -like '*Parallels*') {
   $hwType = 'Virtual:Parallels'
}
ElseIf ($hwMakeModel.Manufacturer -like '*Parallels*') {
   $hwType = 'Virtual:Parallels'
}`

**Comment by mikeda231023** [comment]
> **Is your feature request related to a problem? Please describe.** When calling Get-HardwarePlatform from Parallels Virtual Machine, the function returns only the string "Virtual".
> 
> **Describe the solution you'd like** In the same way Get-HardwarePlatform returns "Virtual:VMWare" or "Virtual:Hyper-V", I would like Get-HardwarePlatform returns "Virtual:Parallels". To do this just add the following condition `ElseIf ($hwBIOS.SerialNumber -like '*Parallels*') { $hwType = 'Virtual:Parallels' } ElseIf ($hwMakeModel.Manufacturer -like '*Parallels*') { $hwType = 'Virtual:Parallels' }`
