### ISSUE TITLE
Show-InstallationPrompt Icons Not Reflecting DPI Scaling

### ISSUE THREAD

**Issue by GoodThings2Life** [PSAppDeployToolkit/PSAppDeployToolkit#847]
**My Question/Issue:**
When using Show-InstallationPrompt -Message "Blah" -Icon Information, the icon doesn't scale well with higher DPI scaling like 125/150%.

Any thoughts on an easy fix for this? I've tried examining the function used for this, but while the code is simple enough, I don't understand the SystemDrawing options well enough to tinker with them much.

**Comment by DanGough** [comment]
Closing this as the UI scaling has been reworked extensively in 3.10.0 and all assets are provided in a higher resolution than before.
