### ISSUE TITLE
Bug with Function Test-MSUpdates

### ISSUE THREAD

**Issue by pmerigot** [PSAppDeployToolkit/PSAppDeployToolkit#85]
Hi,
I would like to install two msu files with the function dedicate to which is Install_MSUpdates.
This function work well even if the result is not the good one. I have tested this function on 3 différents Workstations where I'm 100% sure those KBs are not installed.
Each time, this function detecte that all Kbs are already installed .. which is not the case.

The problem is in fact Inside the Test-MSUpdates function. You use two detections methods.
The first one use Com Object (impossible for me to give you an analyse .. not an expert), the second one use Get-HotFix.
One of the KBs I would like to install is KB3038936.
You can see below that Get-Hotfix did not find this specific KB installed on my machine ... but it can find a KB already installed..
I use the 3.6.4 Toolkit version.
Don't know if you need more informations.
![pb_install_kb](https://cloud.githubusercontent.com/assets/13960170/9463082/87cf8cf2-4b1a-11e5-9eda-57dd3a914fd0.jpg)

**Comment by mmashwani** [comment]
Use the latest 3.6.5 version of the toolkit. I just fixed some bugs in the toolkit related to this function.

**Comment by pmerigot** [comment]
Thanks Muhammad for your reactivity.
3.6.5 is the good version for my need.

Thanks again.
