### ISSUE TITLE
FEATURE REQUEST: Function to ask for user input

### ISSUE THREAD

**Issue by Itokawa25143** [PSAppDeployToolkit/PSAppDeployToolkit#852]
**Is your feature request related to a problem? Please describe.**

Sometimes software (un)installation needs user input but we don't want to show them anything else. 
For example: software uninstallation tokens that are different for each machine, can't hardcode the tokens. Got to ask the user. 

**Describe the solution you'd like**
To have a function, that will pop-up a window for the user and then the user can give their input there. 
Then the input can be used in the script. 

**Describe alternatives you've considered**
Creating this functionality myself but please do it yourself. :D 

Happy holidays!

**Comment by That-Annoying-Guy** [comment]
have you tried the `Show-InstallationPrompt` function?

**Comment by Itokawa25143** [comment]
> have you tried the `Show-InstallationPrompt` function?

Hi, That-Annoying-Guy

User can't write their input there. Like one user needs to insert something like this "jhjg78cv832yhJghfda1629" and every device has a unique code and there are like 50 thousand devices... I need writable fields. 
I did think that I'd try to create it myself but I found this nice place and thought that there could be more people who could benefit from that functionality. 
Awesome tool tho! 

Happy new year!

**Comment by Sulquendi** [comment]
Hello there !

I would say it is a bad idea to ask for a user input during an installation phase. Your package will be stuck, waiting for user input and if noone answer, it will get delayed/cancelled.

Best practice would be to ask for the user input in active setup phase.

**Comment by Itokawa25143** [comment]
> Hello there !
> 
> I would say it is a bad idea to ask for a user input during an installation phase. Your package will be stuck, waiting for user input and if noone answer, it will get delayed/cancelled.
> 
> Best practice would be to ask for the user input in active setup phase.

Hi
I'm sorry but I don't agree. 
It would be used for Available software. Mostly for uninstallation which will be run manually by clicking Uninstall in Company Portal, not automatically via Intune. It would be for software that is asking for the token/uninstallation code/software password. Quite rare cases but thought that it would be a good idea. 
I only need the user to insert the token and nothing else, no clicking on Next-Next-Next. 

All software is not the same and they get handled differently. End-users also know this. It will not be stuck :). It'll most likely get stuck if it's done forcefully (required software) or the user forgets that they clicked on Uninstall. 

This functionality could be used in other ways also ofc.

**Comment by That-Annoying-Guy** [comment]
would this help?

```
[void][System.Reflection.Assembly]::LoadWithPartialName('Microsoft.VisualBasic')
[String]$Default ="<sample for user>"
[String]$InfoFromUser = [Microsoft.VisualBasic.Interaction]::InputBox("Please provide info `r`nfor install to complete", "Title", $Default) 
```

**Comment by Itokawa25143** [comment]
Yes, yes it will! This solution is OK with me, so I will close this issue. 

If one day you want to make it fancier (with logos and stuff) then it would be very cool also. 

Thank you very much, That-Annoying-Guy
I wish you a great successful year!
