### ISSUE TITLE
Get-UserProfiles throws exceptions in ConvertTo-NTAccountOrSID when old profiles are present

### ISSUE THREAD

**Issue by neo42JBR** [PSAppDeployToolkit/PSAppDeployToolkit#865]
**Describe the bug**
Get-UserProfiles iterates over every entry in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList` to get local account profiles. For these profiles a translation from SID to NTAccount is performed via the `ConvertTo-NTAccountOrSID` function. However, there is no guarantee that these profiles still exist or the cached user information is still present on machine (for times when AD is not reachable). Therefor `ConvertTo-NTAccountOrSID` throws with `Failed to convert the SID [S-1-5-21-3825582838-388289177-2840989877-1234] to an NT Account name. It may not be a valid account anymore or there is some other problem.`. There should be a catch for these occurences and only a warning should be displayed. 
The output of the function does not include these orphaned accounts.

**To Reproduce**
1. Create a local user
2. Sign in with this user (to create the registry entry)
3. Sign out
4. Delete user via compmgmt.msc
5. Run Get-UserProfiles

**Toolkit Version:**
3.9.3

**Powershell Version:**
5.1.22621.2506

**Comment by seanlillis** [comment]
@neo42JBR, I have pushed a fix for this to catch these issues and display a warning rather than an error. Could you please check and confirm if this is what you were hoping for?

**Comment by neo42JBR** [comment]
Hey @seanlillis,

yes, the affected part has been converted into a warning. I am not sure if I am a fan of the stack trace.
I'd argue this warning is to be expected and does not require debugging. This is especially the case kiosk like machines.
