### ISSUE TITLE
PSAppDeploToolkit 3.6.5 Function Show-InstallationRestartPrompt Generates 2nd Log file

### ISSUE THREAD

**Issue by pshellsp** [PSAppDeployToolkit/PSAppDeployToolkit#87]
![image](https://cloud.githubusercontent.com/assets/13984396/9499164/bf9b25a2-4beb-11e5-84a3-08ebf1abcb14.png)

One log is created using the naming convention noted in Variables: Application in the deployapplication.ps1 and then when the Show-InstallationRestartPrompt part of the script runs another log is created named PS_AppDeployToolkitMain_3.6.5_EN_01_PSAppDeployToolkit_Install.log. Thanks for the great tool.

**Comment by mmashwani** [comment]
I forget all of the reasons behind why we had to do that, but it is by design as combining the logs generated by multiple executions of the toolkit caused problems.

**Comment by seanlillis** [comment]
If I recall the main reason was due to the limit on the characters passed to Schtasks. Not on my machine now but if we're using XML now for schtsk creation we may be able to revisit this.

**Comment by That-Annoying-Guy** [comment]
Maybe it's time to steal ideas from [here:](http://psappdeploytoolkit.com/forums/topic/set-scheduledtask-uses-com-object-and-xml-text/)

It uses the COM object and XML files or strings

**Comment by mmashwani** [comment]
Unfortunately the com object method is not compatible with XP. We will use the COM object method with the 4.0 branch when we drop XP support.

**Comment by AcidUser85** [comment]
should've dropped XP long time ago, due to support of already officially not supported XP - only applies brakes on progress

**Comment by pshellsp** [comment]
was this possibly fixed in toolkit version 3.6.7 ?
Thanks 


     On Monday, August 31, 2015 2:04 AM, AcidUser85 <notifications@github.com> wrote:
   

 should've dropped XP long time ago, due to support of already officially not supported XP - only applies brakes on progress—

**Comment by mmashwani** [comment]
The 3.6.8 beta has been updated so that asynchronous executions of the toolkit write to the same log file instead of creating a new one.
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/8accf7d586a0ef4bfceb5d3ad9aea6b16ba5c393

**Comment by pshellsp** [comment]
Thanks. Let me know when 3.6.8 is in production and I'll test it out! 

    On Saturday, January 9, 2016 4:31 AM, Muhammad Mashwani <notifications@github.com> wrote:
 

 The 3.6.8 beta has been updated so that asynchronous executions of the toolkit write to the same log file instead of creating a new one.
8accf7d—
