### ISSUE TITLE
Last checkin into Master has an bug in Configure-EdgeExtension

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#870]
The Function Configure-EdgeExtension need  one  } more at end

**Comment by cyborgrd** [comment]
Second issue: Robocopy enabled in XML.  Copy-File -Path "$dirFiles\VSSetup\*.*" -Destination "c:\Temp\VSSetup"  not working
FullyQualifiedErrorId : CommandNotFoundException
ScriptStackTrace      : bei Copy-File<Process>, C:\Work\test\AppDeployToolkit\AppDeployToolkitMain.ps1: Zeile 5207
                        bei <ScriptBlock>, C:\Work\test\TestVendor_TestApp_8.0_x86.ps1: Zeile 262
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1

PositionMessage : In C:\Work\test\AppDeployToolkit\AppDeployToolkitMain.ps1:5207 Zeichen:26
                  +                         (default) {
                  +                          ~~~~~~~

**Comment by seanlillis** [comment]
I fixed these earlier before seeing this! Thanks for testing and reporting.
