### ISSUE TITLE
Default detection logic

### ISSUE THREAD

**Issue by Dashrathchate** [PSAppDeployToolkit/PSAppDeployToolkit#871]
**Is your feature request related to a problem? Please describe.**
We were using the 3.8.4 version of PSADT, and I saw integrated the Application detection logic in the tool

**Describe the solution you'd like**
If you introduce the solution to the 3.9.4 version it would be great.

**Describe alternatives you've considered**
NA

**Additional context**
I am attaching the old code here

**Comment by DanGough** [comment]
@Dashrathchate any further info here? I'm not aware of any application detection logic that was removed since 3.8.4.
