### ISSUE TITLE
With Remove-RegistryKey, if deleting key with subkeys and -Recurse not specified, script hangs

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#88]
Hello,

I use the following code to cleanup trashy per-user Chrome installations:
```
$UserProfiles = Get-UserProfiles
 
[scriptblock]$HKCURegistrySettings =
{
	Remove-RegistryKey -Key 'Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome' -SID $UserProfile.SID
	Remove-RegistryKey -Key 'HKCU\Software\Classes\\.htm' -SID $UserProfile.SID
	Remove-RegistryKey -Key 'HKCU\Software\Classes\\.html' -SID $UserProfile.SID
	Remove-RegistryKey -Key 'HKCU\Software\Classes\\.shtml' -SID $UserProfile.SID
	Remove-RegistryKey -Key 'HKCU\Software\Classes\\.xht'
	Remove-RegistryKey -Key 'HKCU\Software\Classes\\.xhtml' -SID $UserProfile.SID
	Remove-RegistryKey -Key 'HKCU\Software\Classes\ftp' -SID $UserProfile.SID
	Remove-RegistryKey -Key 'HKCU\Software\Classes\http' -SID $UserProfile.SID
	Remove-RegistryKey -Key 'HKCU\Software\Classes\https' -SID $UserProfile.SID
}
Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $HKCURegistrySettings
```
What I might be doing wrong?
The script hangs as seen from the log:

<![LOG[[Pre-Installation] :: The User [TESTPC\testuser] registry hive is already loaded in path [HKEY_USERS\S-1-5-21-911290157-3523553640-4879166865-1000].]LOG]!><time="15:30:07.490120" date="08-28-2015" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="2384" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Execute ScriptBlock to modify HKCU registry settings for all users.]LOG]!><time="15:30:07.501120" date="08-28-2015" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="2384" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Return fully qualified registry key path [Registry::Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome].]LOG]!><time="15:30:07.539120" date="08-28-2015" component="Convert-RegistryPath" context="NT AUTHORITY\SYSTEM" type="1" thread="2384" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Unable to delete registry key [Registry::Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome] because it does not exist.]LOG]!><time="15:30:07.547120" date="08-28-2015" component="Remove-RegistryKey" context="NT AUTHORITY\SYSTEM" type="2" thread="2384" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Return fully qualified registry key path [Registry::HKEY_USERS\S-1-5-21-911290157-3523553640-4879166865-1000\Software\Classes\\.htm].]LOG]!><time="15:30:07.572120" date="08-28-2015" component="Convert-RegistryPath" context="NT AUTHORITY\SYSTEM" type="1" thread="2384" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Unable to delete registry key [Registry::HKEY_USERS\S-1-5-21-911290157-3523553640-4879166865-1000\Software\Classes\\.htm] because it does not exist.]LOG]!><time="15:30:07.579120" date="08-28-2015" component="Remove-RegistryKey" context="NT AUTHORITY\SYSTEM" type="2" thread="2384" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Return fully qualified registry key path [Registry::HKEY_USERS\S-1-5-21-911290157-3523553640-4879166865-1000\Software\Classes\\.html].]LOG]!><time="15:30:07.604120" date="08-28-2015" component="Convert-RegistryPath" context="NT AUTHORITY\SYSTEM" type="1" thread="2384" file="Deploy-Application.ps1">
<![LOG[[Pre-Installation] :: Delete registry key [Registry::HKEY_USERS\S-1-5-21-911290157-3523553640-4879166865-1000\Software\Classes\\.html].]LOG]!><time="15:30:07.611120" date="08-28-2015" component="Remove-RegistryKey" context="NT AUTHORITY\SYSTEM" type="1" thread="2384" file="Deploy-Application.ps1">

**Comment by mmashwani** [comment]
Is the user with that SID logged in and using Chrome when you're trying to delete that key? That could be what causes a hang.

**Comment by AcidUser85** [comment]
yes user is logged in, but not using Chrome

**Comment by AcidUser85** [comment]
also I see that script cannot find this registry key, but it is there

**Comment by mmashwani** [comment]
I don't know what's going on then. I don't see you doing anything wrong in the code provided. I've never had problems with that function not being able to find a key if it exists. You'll have to debug on your end and please let me know if you find a bug of some sort that I need to implement a fix for.

**Comment by mmashwani** [comment]
Also, keep in mind that Chrome can run in the background/systray to keep running Chrome apps even after you close the Chrome window. So it might be worth verifying that Chrome truly is closed.

**Comment by amotaz** [comment]
The issue appears to be a missing hive designation in your remove-registry call:
Remove-RegistryKey -Key 'Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome' -SID $UserProfile.SID

You dont call out HKCU.
Perhaps with the -SID tag, we could automatically add the HKCU hive?

**Comment by amotaz** [comment]
What we'll do is if the reg key string is not formatted in an expected way, we'll throw an warning in the log.

**Comment by amotaz** [comment]
I pushed the commit to the latest 3.6.6 beta which will throw an error if a registry hive is not specified.

**Comment by AcidUser85** [comment]
Hi, I figured out.
The problem was due to there were subkeys under these registry keys.
Adding "-Recurse" option solved the problem.
From the documentation it was not obvious that this option is required.

However, I guess that if script hangs forever in case if -Recurse not specified - is not what expected by design. It should provide some feedback in logs and definitely not hang.

**Comment by AcidUser85** [comment]
amotaz, no need to push that commit since this functionality already works.
From logs it is seen that script successfully passes through if registry key not found:
<![LOG[[Pre-Installation] :: Return fully qualified registry key path [Registry::Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome].]LOG]!>
<![LOG[[Pre-Installation] :: Unable to delete registry key [Registry::Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome] because it does not exist.]LOG]!>

Script hanged on deleting this registry key: 
![LOG[[Pre-Installation] :: Delete registry key [Registry::HKEY_USERS\S-1-5-21-911290157-3523553640-4879166865-1000\Software\Classes\.html].]LOG]!>
Because "HKEY_USERS\S-1-5-21-911290157-3523553640-4879166865-1000\Software\Classes\.html" had subkey under it.

**Comment by AcidUser85** [comment]
mmashwani Chrome.exe and New_Chrome.exe are killed with Show-InstallationWelcome -CloseApps

**Comment by mmashwani** [comment]
I think having a sanity check that make sure a registry hive is specified is a good idea regardless. I'm confused by why the script would hang at deleting a registry key with a sub key when the -Recurse option is the specified. I will have to investigate that further.

**Comment by AcidUser85** [comment]
It hanged when Registry key has subkeys and -Recurse was NOT specified.
I guess in this case it should produce an error, but not hang.

**Comment by amotaz** [comment]
Added a check for child keys when -Recurse parameter is not specified. It will throw an error if child keys are detected.

**Comment by AcidUser85** [comment]
Thank you!
