### ISSUE TITLE
Change `Toolkit_RequireAdmin` setup to simply run in user context if that's how the caller invokes it.

### ISSUE THREAD

**Issue by mjr4077au** [PSAppDeployToolkit/PSAppDeployToolkit#884]
**Is your feature request related to a problem? Please describe.**
I currently maintain a fork of PSADT where I have wrappers that sit on top of it. I will call those wrappers in the SYSTEM context, or user context as required, and I just need the backend to run in that mode, adjusting paths as required.

**Describe the solution you'd like**
Rather than having `Toolkit_RequireAdmin` and having PSADT bomb out when its set and you're running in user context, just run in user context and log to the relevant location, etc. If something doesn't work, that's the caller's fault and PSADT shouldn't just be either/or here.

**Describe alternatives you've considered**
I maintain my own fork where I set `$configToolkitRequireAdmin` in main to true/false depending on whether the process is running elevated or not. It'd be one less reason to maintain my own fork if I can have PSADT run in whatever context it's called in.

**Additional context**
N/A

**Comment by DanGough** [comment]
It is kind of nice to be able to just double-click Deploy-Application.exe when and have it auto elevate when you want to install something quickly. If making this change we'd have to make users aware they won't be able to do this any more.

**Comment by sintaxasn** [comment]
No that shouldn't be necessary. The Deploy-Application.exe has an embedded manifest that contains instructions for how UAC should behave:

```<requestedExecutionLevel ```**```level="highestAvailable"```**```/>```

When set to highestAvailable, UAC looks to see if the current user is trying to execute the process using a filtered access token, and if yes, it will trip an elevation prompt. Only Administrators get a filtered access token, or split token - this is to restrict their access until required for administrative tasks by the OS. 

So, a standard user will just execute the process as normal without an elevation prompt.
