### ISSUE TITLE
Sapien Powershell compiled Deploy-Application exe fails on retrieving App Deploy icon file

### ISSUE THREAD

**Issue by DennisVH** [PSAppDeployToolkit/PSAppDeployToolkit#90]
I get the following error with PSADT 3.6.5 when running compiled exe:
ERROR: Module [...\AppDeployToolkit\AppDeployToolkitMain.ps1]
ERROR: failed to load:
ERROR: App Deploy logo icon file not found.
ERROR:
ERROR: At ...\AppDeployToolkit\AppDeployToolkitMain.ps1: 221 char:74
ERROR: + If (-not (Test-Path -LiteralPath $appDeployLogoIcon -PathType 'Leaf')) { Throw ' ...
ERROR: + CategoryInfo : NotSpecified: (:) [Write-Error], WriteError Exception 
	 FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

I was able to get it back running by removing the added support for alternative Powershell hosts to retrieve invocation info and reverting to the 3.6.4 code:

#Add support for alternative PowerShell hosts for retrieving invocation info
#If (Test-Path -LiteralPath 'variable:HostInvocation') { $InvocationInfo = $HostInvocation } Else { $InvocationInfo = $MyInvocation }
#[string]$scriptPath = $InvocationInfo.MyCommand.Definition
[string]$scriptPath = $MyInvocation.MyCommand.Definition
[string]$scriptName = [IO.Path]::GetFileNameWithoutExtension($scriptPath)
[string]$scriptFileName = Split-Path -Path $scriptPath -Leaf
[string]$scriptRoot = Split-Path -Path $scriptPath -Parent
#[string]$invokingScript = (Get-Variable -Name 'InvocationInfo').Value.ScriptName
[string]$invokingScript = (Get-Variable -Name MyInvocation).Value.ScriptName

I assume the added support in AppDeployToolkitMain.ps1 is not required because AppDeployToolkitMain.ps1 is called from the compiled Deploy-Application.ps1. (the AppDeployToolkitMain.ps1 itself is not compiled)

**Comment by That-Annoying-Guy** [comment]
FYI: Careful with Compiled PS1 files.

When I compile with PowerGUI it LOCKS the EXE to a minimum version of .Net.
IOW: If you compile on a PC with .Net 4.5.2, It might not run on a PC with .net 4.5.0 and definitely not on a PC with .Net 2.0.

This is regardless if you use functions of higher versions of .Net or not. It's the EXE that locks you.

**Comment by mmashwani** [comment]
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/c11c7f38a8f9918b5a5f454322018ae12d6b8320
