### ISSUE TITLE
Typo in AppDeployToolkitConfig.xml

### ISSUE THREAD

**Issue by Zaare** [PSAppDeployToolkit/PSAppDeployToolkit#91]
Row: **694**
Word: **automatiskt**

Is:
```<ClosePrompt_CountdownMessage>OBS: Programmen kommer automatiskts att avslutas om:</ClosePrompt_CountdownMessage> ```

Should be:
```<ClosePrompt_CountdownMessage>OBS: Programmen kommer automatiskt att avslutas om:</ClosePrompt_CountdownMessage>```

**Comment by mmashwani** [comment]
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/fc6fbc596b42cabbf4ce846581dcf44c480a57cb
