### ISSUE TITLE
Configure-EdgeExtensions is not documented in Help

### ISSUE THREAD

**Issue by excelsi** [PSAppDeployToolkit/PSAppDeployToolkit#916]
Help Documentation is missing
Thanks for updating, great job from you all together!

**Comment by sintaxasn** [comment]
Hi. It is documented on the [website](https://psappdeploytoolkit.com/docs/reference/functions/Configure-EdgeExtension).

**Comment by excelsi** [comment]
Thanks for the hint!

**Comment by xstaindx** [comment]
> Hi. It is documented on the [website](https://psappdeploytoolkit.com/docs/reference/functions/Configure-EdgeExtension).

Hi being new to managing extensions, I had no idea about 2 items required.  What a manifest file was for extensions, and how important it is to this new feature in PSADT so we can locate the UpdateUrl string,  but I found out it its in  %Appdata%\Local\Microsoft\Edge\User Data\Default\Extensions\
