### ISSUE TITLE
Error when Notes is one of the processes to be Closed v3.6.5

### ISSUE THREAD

**Issue by yulasinio** [PSAppDeployToolkit/PSAppDeployToolkit#92]
If I have notes in the -CloseApps parameter the script will throw an error:
Message: Cannot bind argument to parameter 'LiteralPath' because it is null.

This is caused by $notesPath not being set when the $notesPathExes is called. I moved the $notespath before $notesPathExes and script run successfully.

I can see the same is applicable with version 3.6.6

Regards,
Julian

**Comment by mmashwani** [comment]
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/760c4397cf34cdcc54bc40117371b7a8917c7a3f

**Comment by yulasinio** [comment]
Thanks for the quick update.

**Comment by mmashwani** [comment]
Yup, no problem. I'll keep the ticket opened until we finalize the 3.6.6 release.
