### ISSUE TITLE
Source code (zip) file for 3.10.0 has PDF doc from 3.9.3

### ISSUE THREAD

**Issue by JMOC68** [PSAppDeployToolkit/PSAppDeployToolkit#920]
**Describe the bug**
Source code (zip) file for version 3.10.0 has the wrong PDF file included.  It has the PDF for version 3.9.3.

**To Reproduce**
N/A

**Screenshots**

**Toolkit Version:**
3.10.0

**Powershell Version:**
Any

**Additional context**

**Comment by mjr4077au** [comment]
We're past 3.10.0 now.
