### ISSUE TITLE
VScode returning errors in the code in file Deploy-Application.ps1

### ISSUE THREAD

**Issue by azercher** [PSAppDeployToolkit/PSAppDeployToolkit#922]
When loading the above file into VSCode, I am getting the following errors in the code that I did not change or add.

1. Line 104 Col 2: The Try statement is missing its Catch or Finally block.
2. Line 232 Col 47: Missing closing '}' in the statement block or type definition
3. Line 329 Col 55: The string is missing the terminator: '

I attempted to correct these but was unsuccessful.  Please correct.

**Comment by azercher** [comment]
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/94934716/141f309a-65f9-42e0-8d96-4f70105e2eee)

**Comment by mjr4077au** [comment]
Are you sure this isn't just something on your side in your own `Deploy-Application.ps1`? The released copy doesn't even go up to line 329, the last line is 312.

**Comment by azercher** [comment]
Oh right because of me adding some code into the install and uninstall areas. Let me grab screenshots of the errors.

1.
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/94934716/ec02cd40-69e8-42a6-90bb-77bdfe939fd3)

2.
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/94934716/b89e213a-4ed6-4184-af36-450f47c066ef)

3.
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/94934716/ad5f610f-92de-4165-a630-2e27fc72d9bc)

**Comment by mjr4077au** [comment]
That rogue curly brace on 104 is likely causing all the issues, but it's not in the released version, it's something that's snuck in on your end. Try deleting line 104, saving, then trying again.

**Comment by azercher** [comment]
I reverted the file and issue resolved.
