### ISSUE TITLE
Shortcut functions should use "ValidateNotNull" not "ValidateNotNullorEmpty"

### ISSUE THREAD

**Issue by GeoSimos** [PSAppDeployToolkit/PSAppDeployToolkit#923]
This is a change request for the Shortcuts creation functions.

I was creating some shortcuts the other day by using a CSV with their data but not all parameters were required and the DeployApplication.ps1 script was throwing an error that the parameters can't be null or empty.

I checked the code in the toolkit script and changed the parameters that I needed to be "ValidateNotNull" instead of "ValidateNotNullorEmpty". 
If you think about it a bit, not all parameters are required for a properly operating shortcut such as:

1. IconLocation
2. IconIndex
3. Arguments
4. RunAsAdmin
5. WindowStyle
6. HotKey
7. Working Directory (for URL shortcuts)
So having those as ValidateNotNull they can be empty and accepted.

Would you consider this change for a future release please?

Thank you for your great work!

**Comment by mjr4077au** [comment]
This has been addressed in our v4 branch.
