### ISSUE TITLE
.vscode folder part of release

### ISSUE THREAD

**Issue by tinojohn** [PSAppDeployToolkit/PSAppDeployToolkit#925]
In version 3.10.0, there is a .vscode folder containing extensions.json, PSScriptAnalyzerSettings.psd1 and settings.json files.

It is recommended to exclude these files in the build process to ensure that no development tools or settings are inadvertently included in the release version.

**Comment by DanGough** [comment]
These files were placed there intentionally - there are a few benefits such as having VSCode load the correct PowerShell engine (v5.1) if you have v7 installed, and warnings being shown if using any syntax that's incompatible with v3 (which PSADT still officially supports, for now).

They can always be deleted from your own copy of the toolkit as part of the branding and configuration process.

**Comment by tinojohn** [comment]
And now it's back to the "old normal" again. Please define a standard and stick to it.
