### ISSUE TITLE
Get-UserProfiles -ExcludeNTAccount is not excluding

### ISSUE THREAD

**Issue by v-Hartline** [PSAppDeployToolkit/PSAppDeployToolkit#926]
V. 3.9.3
Using the following:
$Profiles = Get-UserProfiles -ExcludeNTAccount @('NT SERVICE\SplunkForwarder',"$envComputerName\Admin","$envComputerName\classic","$envComputerName\altiris","$envComputerName\new","$($LoggedOnUserSessions.DomainName)\AltirisDSsvc")

All excluded items are NOT excluded and are contained in $Profiles.
The only way I can remove the unwanted is to remove them after with:
$Profiles = $Profiles|Where-Object{$_.NTAccount -inotmatch 'altirisdssvc'}, etc.

**Comment by DanGough** [comment]
Working for me on 3.10.0. There have been changes to this function in the last version - please comment back if you feel this needs to be re-opened.

I think it would be a good idea to add an -ExcludeServiceProfiles option to go with -ExcludeSystemProfiles though, that would exclude any account where ProfilePath starts with C:\WINDOWS\ServiceProfiles. That would knock out a lot of those service exclusions you have there currently.

**Comment by v-Hartline** [comment]
As stated, we are using 3.9.3 not 3.10.0.  Updating is out of the question at this time for governmental reasons.
We will use it as we have been , thank you

From: Dan Gough ***@***.***>
Sent: Thursday, April 4, 2024 11:01 AM
To: PSAppDeployToolkit/PSAppDeployToolkit ***@***.***>
Cc: Hartline Virgil P ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [PSAppDeployToolkit/PSAppDeployToolkit] Get-UserProfiles -ExcludeNTAccount is not excluding (Issue #926)


Working for me on 3.10.0. There have been changes to this function in the last version - please comment back if you feel this needs to be re-opened.

I think it would be a good idea to add an -ExcludeServiceProfiles option to go with -ExcludeSystemProfiles though, that would exclude any account where ProfilePath starts with C:\WINDOWS\ServiceProfiles. That would knock out a lot of those service exclusions you have there currently.

**Comment by InnerMomo** [comment]
> Working for me on 3.10.0. There have been changes to this function in the last version - please comment back if you feel this needs to be re-opened.
> 
> I think it would be a good idea to add an -ExcludeServiceProfiles option to go with -ExcludeSystemProfiles though, that would exclude any account where ProfilePath starts with C:\WINDOWS\ServiceProfiles. That would knock out a lot of those service exclusions you have there currently.

I agree, it would be great to add an -ExcludeServiceProfiles option here. I'm working on a similar issue but can't seem to exclude one of our accounts with ProfilePath in C:\WINDOWs\ServiceProfiles with either option mentioned by the OP.

**Comment by DanGough** [comment]
It's been added! It'll be in the next release, which is imminent. 

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/2c09b80d537a96a83c2c9ec2afecc68eb6cd2a2b
