### ISSUE TITLE
Let registry based commandlets handle Microsoft.PowerShell.Core\Registry

### ISSUE THREAD

**Issue by neo42JBR** [PSAppDeployToolkit/PSAppDeployToolkit#930]
**Is your feature request related to a problem? Please describe.**
Currently registry commandlets only accept PSDrive or registry addresses. 
It would be cool if these commandlets would handle `Microsoft.Win32.RegistryKey` directly and dont create issues when using `Microsoft.PowerShell.Core\Registry::` address. These are valid PowerShell paths.

**Describe the solution you'd like**
Allow any valid registry input

**Describe alternatives you've considered**
Parse any input into a `Microsoft.Win32.RegistryKey`

Sample code:
```
@(
    "HKLM:\SOFTWARE"
    "HKEY_LOCAL_MACHINE\SOFTWARE"
    "Registry::HKEY_LOCAL_MACHINE\SOFTWARE"
    "Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE"
    Get-Item "HKLM:\SOFTWARE"
) | ForEach-Object {
    $obj = $_
    try {
        ## Try $_ own type
        [Microsoft.Win32.RegistryKey]$key = Get-Item -Path $obj -ErrorAction Stop
    }
    catch {
        ## Try $_ as string with registry provider
        [Microsoft.Win32.RegistryKey]$key = Get-Item -Path "Registry::$obj" -ErrorAction SilentlyContinue
    }
    $key
}
```

**Comment by mjr4077au** [comment]
I don't know if this was an issue in the past, but all our registry comamnds support proper PSPaths. Further to this, we use PSPaths internally across the entire module for enhanced performance and security.

![image](https://github.com/user-attachments/assets/dabe9c8f-d8f7-478d-a2c2-1484f6095eac)
