### ISSUE TITLE
Execute-Process -IgnoreExitCodes does except wildcard

### ISSUE THREAD

**Issue by GunFood** [PSAppDeployToolkit/PSAppDeployToolkit#932]
As written in documentation for Execute-Process [https://psappdeploytoolkit.com/docs/reference/functions/Execute-Process](url) -IgnoreExitCode does except a wildcard to ignore any exit code.

So
```
-IgnoreExitCodes
List the exit codes to ignore or * to ignore all exit codes.

Type: String
Parameter Sets: (All)
Aliases:

Required: False
Position: 6
Default value: None
Accept pipeline input: False
Accept wildcard characters: False
```
should be
```
-IgnoreExitCodes
List the exit codes to ignore or * to ignore all exit codes.

Type: String
Parameter Sets: (All)
Aliases:

Required: False
Position: 6
Default value: None
Accept pipeline input: False
Accept wildcard characters: **True**
```

**Comment by DanGough** [comment]
Funnily enough I was looking at someone’s script earlier today where they used * here, I never knew it was an option! I usually use -ExitOnProcessFailure $false.

**Comment by GunFood** [comment]
Any update on this issue?

**Comment by mjr4077au** [comment]
The `[SupportsWildcards()]` parameter decoration has been added into our v4 branch.
