### ISSUE TITLE
Robocopy mode of Copy-File fails to copy files or folders when path begins with .\ or ..\

### ISSUE THREAD

**Issue by DanGough** [PSAppDeployToolkit/PSAppDeployToolkit#938]
**Describe the bug**
The Robocopy implementation in Copy-File does not like paths beginning with `.\` or `..\`
Having `\..\` in middle of a folder path does work.

**To Reproduce**

These succeed but fail when -UseRobocopy is set to $true:

```powershell
Copy-File -Path .\toolkit -Destination $env:temp -Recurse -UseRobocopy $false
Copy-File -Path .\TODO.txt -Destination $env:temp -Recurse -UseRobocopy $false
Copy-File -Path ..\PSAppDeployToolkit\TODO.txt -Destination $env:temp -Recurse -UseRobocopy $false
Copy-File -Path ..\PSAppDeployToolkit -Destination $env:temp -Recurse -UseRobocopy $false
```

**Toolkit Version:**
3.10.0 plus latest Copy-File fixes commited to Develop as of Apr 3, 2024.

**Comment by freedbygrace** [comment]
The following will fix seemingly fixes the issue.

$ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath("..\Testing")

**Comment by DanGough** [comment]
Thanks for the tip!
