### ISSUE TITLE
Detect Reboot Pending (feature Request)

### ISSUE THREAD

**Issue by thomashesse** [PSAppDeployToolkit/PSAppDeployToolkit#94]
Please include a reboot pending detection. Like this: [Get-PendingReboot - Query Computer(s) For Pending Reboot State] (https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542)

Some installations fail because a restart is pending. To ignore the "exit code" is not an option.

I think the best way is, to detect a reboot before the installation starts. So that the user can be informed beforehand, it must reboot his PC before the installation can be performed.

Thanks in advance
Thomas

**Comment by mmashwani** [comment]
We have this function in the toolkit already. Look at the latest version.

**Comment by thomashesse** [comment]
Excellent! Thanks for your great work!
p.s. Is there a way to be notified when there is a new version? I cant find this.

**Comment by mmashwani** [comment]
I don't think so. I think all you can do is periodically check the releases tab of the github page. We also post a sticky in the General forum on our site that mentions the latest version. Maybe we will start a project twitter or something to blast out updates.

**Comment by thomashesse** [comment]
Thanks for response. I will check periodically the github page.
