### ISSUE TITLE
[PSADT.UiAutomation] does not contain a method named 'SetProcessDPIAware'

### ISSUE THREAD

**Issue by sjfairchild** [PSAppDeployToolkit/PSAppDeployToolkit#940]
**Describe the bug**
When running Deploy-Application.ps1 in Visual Studio Code on Windows 10 I get this exception. This happens on the base template with zero customizations.

C:\Users\xxxxx\Desktop\PSAppDeployToolkit_3.10.0\Deploy-Application.ps1 : Module 
[C:\Users\xxxxx\Desktop\PSAppDeployToolkit_3.10.0\AppDeployToolkit\AppDeployToolkitMain.ps1] failed to load: 
Method invocation failed because [PSADT.UiAutomation] does not contain a method named 'SetProcessDPIAware'.        
 
At C:\Users\xxxxx\Desktop\PSAppDeployToolkit_3.10.0\Deploy-Application.ps1:164 char:13
+             . $moduleAppDeployToolkitMain
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ . 'C:\Users\xxxxx\Desktop\PSAppDeployToolkit_3.10.0\Deploy-Appl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Deploy-Application.ps1

**Toolkit Version:**
3.10.0

**Powershell Version:**
 5.1

**Additional context**

**Comment by mjr4077au** [comment]
Do you mind please double checking to see you've completely updated your deployment and aren't using an old backend, or at least an old `AppDeployToolkitMain.cs` file? The P/Invoke is definitely present: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/d04eda2cf83762604ae567b050dd7dea9d969d20/Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs#L245-L246

**Comment by sjfairchild** [comment]
Download the zip from https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases

Extract and run Deploy-Application.ps1

That's when I get the error. 

Only happens in Visual Studio Code. PowerShell ISE works fine.

It is a fresh install of Visual Studio Code

**Comment by mjr4077au** [comment]
Visual Studio Code is likely defaulting to attempting to run via PowerShell 7, which is not supported by PSADT. There's PR #901 to address the PowerShell 7 issues which will be merged in due course, I'm sure.

**Comment by sjfairchild** [comment]
I figured it out. I had a corrupt PowerShell profile. Deleting the WindowsPowerShell folder under documents resolved the issue

**Comment by ClientSupportCDB** [comment]
Same as Bug #959 . Still having the same Problem in v3.10.1. Reproducable Problem and no other solution found than removing the Line "[System.Void][PSADT.UiAutomation]::SetProcessDPIAware()"

Nevers logged on that client before, so no Userprofile existed where somehting might be cached.

Running directly from Powershell included in Windows 10 22H2.

Please reopen the Bug
