### ISSUE TITLE
PSADT Runs Silent if Windows Security Service is disabled

### ISSUE THREAD

**Issue by sjfairchild** [PSAppDeployToolkit/PSAppDeployToolkit#941]
**Describe the bug**
If HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Systray does not exist, and the Windows Security Service is disabled via GPO, PSADT runs silent and no dialogs are displayed.

**To Reproduce**
Delete HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Systray if it exists
Set HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SecurityHealthService\Start = 4
Reboot

PSADT v3.9.3 does not exhibit this behaviour

**Toolkit Version:**
3.10.0

**Powershell Version:**
5.1

**Comment by mjr4077au** [comment]
@seanlillis do you think we can just drop this code? The Michael Niehaus method is definitely the best way to detect the OOBE or whether we're pre-provisioning etc.

**Comment by DanGough** [comment]
I ran into this bug today, my machine didn't even have the service disabled. After discussion with the team, these lines will be removed for the next patch release.

**Comment by DanGough** [comment]
PR submitted.
