### ISSUE TITLE
Resolve-Error used by an Az module, clashes and causes exit code 60001

### ISSUE THREAD

**Issue by ivassallo19** [PSAppDeployToolkit/PSAppDeployToolkit#944]
**Describe the bug**
The PowerShell module Az.Accounts version 2.12.1 owns the cmdlet Resolve-Error, causing a clash with the toolkit's usage.
It currently produces an error, and stops execution.

**To Reproduce**
Running: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File Deploy-Application.ps1
Output: 
```
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use
`Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.


Write-Log : The term 'Write-Log' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Windows\IMECache\Test\Sysinternals\Deploy-Application.ps1:498 char:5
+     Write-Log -Message $mainErrorMessage -Severity 3 -Source $deployA ...
+     ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-Log:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Screenshots**
Can provide upon request. Currently N/A.

**Toolkit Version:**
3.10.0

**Powershell Version:**
5.1.19041.4170

**Additional context**

**Comment by ivassallo19** [comment]
Apologies, it seems that this is a result of modification I have made to the toolkit, causing AppDeployToolkitMain.ps1 to fail to import correctly and thus importing the Resolve-Error function.
I am still figuring out what part it is, as failures to import it would result in an error.

**Comment by ivassallo19** [comment]
Ok it was caused by a line I added. Basically a line that involved $String.Substring(0, $String.Length - 1) where .Length is 0.

But, because this issue caused an error, and Resolve-Error still exists because it's from Az.Accounts, it does not produce a meaningful error to me.

**Comment by mjr4077au** [comment]
This isn't something we can adequately address until the 4.0.0 preview is released. Makes sense that the `Substring()` method won't accept a negative signed integer, but agreed something something should be done to get a more meaningful error out of things. I'm not sure what `$String.Substring(0, $String.Length - 1)` is meant to achieve though, all that's going to do is give you a new string with the same contents back.

**Comment by ivassallo19** [comment]
Thanks. Yeah this post isn't so much about that particular line. What it does is return the same string with the last character removed.
I will await 4.0.
I did see a similar post about the handling of Resolve-Error, which causes the error output to be written to a file, but it also gets caught because Resolve-Error already exists.
Will 4.0 rename this function?

**Comment by mjr4077au** [comment]
I'd just do something like `$string -replace '.$'` instead, but you ask 10 different people how they'd do this and you'll get 11 different answers haha

Information about 4.0 will be revealed in an official announcement. There'll be some discussion of it at the PowerShell Global Summit, however.
