### ISSUE TITLE
Get-LoggedOnUser broken within Windows Sandbox due to truncated ComputerName environment variable

### ISSUE THREAD

**Issue by obuolinis** [PSAppDeployToolkit/PSAppDeployToolkit#947]
**Describe the bug**
When run from within Windows Sandbox Get-LoggedOnUser fails with the following error message:
`Exception calling "GetUserSessionInfo" with "1" argument(s): "The operation completed successfully"`

**To Reproduce**
1. Run any PSADT package from within Windows Sandbox (tested on Windows 11 only)
2. You get the error during the Initialization stage in the console and/or in the log.

**Toolkit Version:**
Tested with 3.9.3

**Powershell Version:**
5.1

**Additional context**
This has been bugging me for quite some time already since I really love using Windows Sandbox as my PSADT package testing environment.
According to my investigation this is related to both Windows and Windows Sandbox design. The root cause is that Get-LoggedOnUser is calling GetUserSessionInfo CS function using Windows environment variable _ComputerName_ as the name of the host:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/d04eda2cf83762604ae567b050dd7dea9d969d20/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L15811

An actual computer name within Sandbox is a random GUID whereas ComputerName variable truncates it to 15 chars which is what breaks the function.

**Fix Suggestion**
This could possibly be a rather simple fix - you could be calling GetUserSessionInfo using _DNSHostName_ property value of WMI class _Win32_ComputerSystem_ rather than an environment variable. This property holds a full non-truncated computer name.
I'm not aware of any potential repercussions.

**Comment by AlkHacNar** [comment]
don't work with the 3.10.1 too, but you can fix/workaround it with you change $Env:ComputerName to $(hostname)

**Comment by mjr4077au** [comment]
@AlkHacNar, does `[System.Environment]:: MachineName` work as you'd expect?

**Comment by AlkHacNar** [comment]
no, its the same as $Env:ComputerName
![image](https://github.com/user-attachments/assets/c9daf0ac-e5b0-4221-807d-655174950673)

**Comment by mjr4077au** [comment]
Thanks mate, that's actually really good to know.

**Comment by AlkHacNar** [comment]
just tested (Get-WmiObject win32_computersystem).DNSHostName as @obuolinis mentioned and it works too in the sandbox
![image](https://github.com/user-attachments/assets/ec375d8f-2626-4de9-9938-3f3c29073198)
