### ISSUE TITLE
How important is PowerShell 2.0+ and .NET 3.5+ compatibility?

### ISSUE THREAD

**Issue by Mrman1093** [PSAppDeployToolkit/PSAppDeployToolkit#948]
In snooping through the code of this project I found three instances of the string method IsNullOrWhiteSpace. This method wasn't added to the .NET string class until [.NET framework 4.0](https://learn.microsoft.com/en-us/dotnet/api/system.string?view=netframework-4.0)

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/d04eda2cf83762604ae567b050dd7dea9d969d20/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L1177-L1183

**Comment by mjr4077au** [comment]
This would be my mistake. I'm new to the team and new as a contributor, and because I haven't targeted such an old stack for so long, it got away on me.

Feel free to send a PR through to something that's compatible, otherwise I'll fix it up tonight.

**Comment by Mrman1093** [comment]
Here is the other instance of the `IsNullOrWhiteSpace` method.
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/d04eda2cf83762604ae567b050dd7dea9d969d20/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L9118

**Comment by mjr4077au** [comment]
Thank you, I'll address these mistakes of mine shortly.

**Comment by That-Annoying-Guy** [comment]
FYI: looks like we might have a .Net 3.5 dependency in **RunHidden.vbs**  at line 98:

    Set oArgumentList = CreateObject("System.Collections.ArrayList")


https://discourse.psappdeploytoolkit.com/t/error-runhidden-vbs-set-activesetup/5378/4

**Comment by mjr4077au** [comment]
That's super interesting! I've had the error before but had no idea it was due to lack of netfx 3.5

![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/48643140/8f5708cd-a110-4d40-89f6-2157eb2c0587)

Its possible to use `[System.Collections.ArrayList]` objects in PowerShell without netfx 3.5 so I'm not sure what the go is here. I wonder if we can use a System.Collections.Generic.List[System.String] object.

**Comment by That-Annoying-Guy** [comment]
UPDATE: Someone has replaced the ArrayList array with a regular array and the issue went away.

https://discourse.psappdeploytoolkit.com/t/error-runhidden-vbs-set-activesetup/5378/6
