### ISSUE TITLE
Wrong Version and Date in DeployApplication.ps1 v3.6.7

### ISSUE THREAD

**Issue by thomashesse** [PSAppDeployToolkit/PSAppDeployToolkit#95]
Wrong Version and Date in DeployApplication.ps1 - Line 78/79

	## Variables: Script
	[string]$deployAppScriptFriendlyName = 'Deploy Application'
	[version]$deployAppScriptVersion = [version]'3.6.5'
	[string]$deployAppScriptDate = '08/17/2015'
	[hashtable]$deployAppScriptParameters = $psBoundParameters

**Comment by mmashwani** [comment]
This script file has not changed since 3.6.5. The mail toolkit is at 3.6.7. Other script files are going to be at different version numbers based on the last time they were modified.
