### ISSUE TITLE
Is the goal of this if statement in Write-Log to allow for the creation of blank log lines?

### ISSUE THREAD

**Issue by Mrman1093** [PSAppDeployToolkit/PSAppDeployToolkit#952]
This if statement in Write-Log is only used to determine the creation of the variables $CMTraceMsg, $ConsoleLogLine, and $LegacyTextLogLine. It doesn't prevent the logging function from proceeding, allowing a blank log to be written. I'm currently re-writing this function and if this is the intent, I will leave this part be but if it isn't I'll move the rest of the process block inside of it. Another thing that I noticed was that the current state of this function requires $ScriptSectionDefined to be true for a CMTrace log message to be created whereas legacy and console log lines can be created without it being true. Again, if this is the intent, I will leave it be, but if not I will change it so that the log message is always present in CMTrace log messages.

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/d04eda2cf83762604ae567b050dd7dea9d969d20/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L1330-L1375

**Comment by mjr4077au** [comment]
A more senior operator within the team would be best to answer this, but it does appear to be an oversight that there's execuable code outside the `if ($msg)` branch.

A better fix would be to eliminate the branch in the loop entirely and just filter the `$Message` array before looping through it.

**Comment by Basti890** [comment]
As you're already working to rewrite this funktion: I currently have a strage bug:
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/11937981/5e0b676b-ffdd-4fe2-97cc-aeec1bdb8fbe)

`        #  Get the file name of the source script
        $ScriptSource = If (![System.String]::IsNullOrWhiteSpace($script:MyInvocation.ScriptName)) {
            Split-Path -Path $script:MyInvocation.ScriptName -Leaf -ErrorAction SilentlyContinue
        }
        Else {
     -->>       Split-Path -Path $script:MyInvocation.MyCommand.Definition -Leaf -ErrorAction SilentlyContinue
         }`
I'm not sure it is even possible that the Value providet thr the Path-Argument can be empty, especiall as there are already lines writtel to the log. 

In my Deploy-Application.ps1 I call:
`
        [string[]] $fileExtensions = '.dgn','.dgnlib','.n','.sb','.fb','.dg','.gb','.wb','.t','.bel'
        $fileExtensions.ForEach({
                if (-not (cmd /c assoc ('{0}' -f $_))) {
                    Execute-Process -Path 'cmd.exe' -Parameters ('/c assoc {0}={0}-File' -f $_)
                    Execute-Process -Path 'cmd.exe' -Parameters ('/c ftype {0}-File="PATH_TO_EXE" %1 %*' -f $_)
                }
        })
`

**Comment by mjr4077au** [comment]
@Basti890 can you also please update to 3.10.1 and try again? I just noticed that you seem to be on 3.10.0.

**Comment by mjr4077au** [comment]
The logging code in question has been refactored for our upcoming v4 public preview.
