### ISSUE TITLE
Show-InstallationPrompt: Add ability to prompt for free text value

### ISSUE THREAD

**Issue by niemalsnever** [PSAppDeployToolkit/PSAppDeployToolkit#953]
**Is your feature request related to a problem? Please describe.**
I need the ability for the end user to interactively pass a free text value to my script. Extending the `Show-InstallationPrompt`-prompt with a text field that would be returned to the script feels like the most natural solution for me. As that command already allows for quite a bit of customization, it would feel quite natural to me to add the feature there. My concrete usecase would be prompting for a serial number, but I've had other times where I could've used this option. 

**Describe the solution you'd like**
Provide a parameter `-TextFieldTitle` (or similar) that takes a string value and displays it, and a full width text field beneath it, above the button row on the "Installation Prompt" window. The content of the text field should be returned to the script after the user confirms the installation prompt. An additional parameter for a default value which will get passed, if the script is running silent/non-interactive, could be optionally added, but is not needed. Any kind of validation of the returned value should be handled by the script, after the installation prompt was confirmed and is not part of this feature request.

**Describe alternatives you've considered**
One could use the `-Button[Left|Middle|Right]Text` to at least build an A/B/C choice, but the text field option would be more flexible.

If you have any further questions, I'd be happy to answer them.

**Comment by DanGough** [comment]
If you just want a super basic text entry box for now, this should do the trick:

```powershell
Add-Type -AssemblyName Microsoft.VisualBasic
$Thing = [Microsoft.VisualBasic.Interaction]::InputBox('Input the thing:', 'Thing')
```

![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/21019376/03572e77-b9be-4647-a3e9-93a35a4a26ba)
