### ISSUE TITLE
Configure-EdgeExtension error after ExtensionSettings created with empty string value

### ISSUE THREAD

**Issue by Merbow** [PSAppDeployToolkit/PSAppDeployToolkit#955]
This issue can be created by having a missing or empty string value for the ExtensionSettings Registry Subkey.

Here is the command I have in Deploy-Application.ps1:
`Configure-EdgeExtension -ConfigureMode "Add" -ExtensionID "mhpigfckgphoiifbehgajfbkocihbaho" -InstallationMode "force_installed" -UpdateUrl "https://edge.microsoft.com/extensionwebstorebase/v1/crx"`

Here is the Console Output:
```
Add-Member : Cannot bind argument to parameter 'InputObject' because it is null.
At \\malscm4\source\packages\SAP\SAP GUI 8.00\AppDeployToolkit\AppDeployToolkitMain.ps1:16517 char:40
+ ... xtensions | Add-Member -Name $($extensionID) -Value $(@{ "installatio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand
```

I suspect the Add-Member cmdlet is failing to run because the ExtensionSettings subkey is created with no value. This can be confirmed by manually adding a random string to ExtensionSettings and re-running the script, which then succeeds..

PSADT 3.10
Powershell: 5.1.19041.2673

**Comment by Tirakk** [comment]
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/931
