### ISSUE TITLE
BREAK : Interactive & Allow users to interact with this program

### ISSUE THREAD

**Issue by AntoineRv** [PSAppDeployToolkit/PSAppDeployToolkit#958]
**Describe the bug**
When deploying a program's package with 'Allow users to interact with this program' ticked. DeployApplication.exe is runned as session 0 and not allowing user to interact with the program.

**To Reproduce**
Deploy program's package with 'Allow users to interact with this program' ticked and DeployApplication.exe as Interactive.

**Screenshots**
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/37886941/37673bf0-4ba4-4a39-b7f0-348691f22549)

![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/37886941/fb9459ac-1552-4377-b187-eb5c732838ee)

**Toolkit Version:**
Version of our toolkit you are using. For example: 3.10.0

**Powershell Version:**
Version of Powershell you are using to run the toolkit: 5.1

**Additional context**

**Comment by Ath3na-UK** [comment]
Just downloading 3.10.0 now, I have a new version of an app to do so will give it a try and let you know.

**Comment by AntoineRv** [comment]
> Just downloading 3.10.0 now, I have a new version of an app to do so will give it a try and let you know.

Thanks dude.

**Comment by Ath3na-UK** [comment]
I have tried it via PSEXEC using the system account and interactive installs are working ok.
![1](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/53652632/dfd3ba1e-3f64-4324-af41-99cbf511fe29)
I will stick it in SCCM once its ready later today.

Grab psexec from sysinternals 
Run psexec -i -s cmd.exe

This will give you a command prompt as system. do a whoami to verify.
then try your package.

**Comment by Ath3na-UK** [comment]
Its working fine for me using the app model in Configuration Manager.

**Comment by AntoineRv** [comment]
> Its working fine for me using the app model in Configuration Manager.

Thanks for your feedback!

**Comment by AntoineRv** [comment]
I found where the issue is.
This is this part :

`    [Int]$defenderHideSysTray = Get-RegistryKey -Key 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Systray' -Value 'HideSystray'
    If ($defenderHideSysTray -ne "1" -and ($null -eq (Get-Process -Name SecurityHealthSystray -ErrorAction SilentlyContinue))) {
        $deployMode = 'Silent'
    }`

**Comment by DanGough** [comment]
This will go into 3.10.1, which we're hoping to release very soon.

**Comment by AntoineRv** [comment]
Thanks dude.
