### ISSUE TITLE
The custom welcome message in the XML file

### ISSUE THREAD

**Issue by rickardmkvist** [PSAppDeployToolkit/PSAppDeployToolkit#960]
**My Question/Issue:**
The custom welcome message in the XML file, for each language.

**What I have tried so far:**
Under the English section in the XML file has this syntax but it's missing for every other language. This might not be needed, but it looks like the XML is malformed.

<WelcomePrompt_CustomMessage></WelcomePrompt_CustomMessage>

**Screenshots or additional details:**
If this was intended, how can I add custom text for each language in the XML file?

**Comment by DanGough** [comment]
It's a standard in some XML formatters to replace empty elements with self-closing tags; but this has been reverted to make it easier to fill in the XML, and should be in the next release (3.10.1).
