### ISSUE TITLE
Zip Structure folder changed after v3.9.2

### ISSUE THREAD

**Issue by markusyou** [PSAppDeployToolkit/PSAppDeployToolkit#962]
**Describe the bug**
The documentation shows folder structure like what is visible in v3.9.2.  Zips for v3.9.4 and v3.10.0 do not have folders for Examples and ToolKi. They are missing.

**To Reproduce**
open the zip files

**Screenshots**
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/17938242/b99cd74c-4072-4d52-b0a3-568c93dcda8b)
**Toolkit Version:**
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/17938242/0d0b58f4-25b7-4183-b5ee-1cdd4ccda380)

Version of our toolkit you are using. For example: 3.8.1
v3.10.0

**Powershell Version:**
5.1.19041.4170

**Additional context**

**Comment by tinojohn** [comment]
And now it's back to the "old normal" again. Please define a standard and stick to it. Our automated processes are broken by the back-and-forth.
