### ISSUE TITLE
How to use the AppDeployToolkit with Ivanti EndPoint Manager ?

### ISSUE THREAD

**Issue by fobrien9703** [PSAppDeployToolkit/PSAppDeployToolkit#963]
**My Question/Issue:**
I am posting this message in order to know what the best practice is in order to use the AppDeployToolkit efficiently with Ivanti EndPoint Manager.
Thanks in advance.

**What I have tried so far:**
I have alreeady made some research on the Internet regarding this issue but the only thing I've managed to perform is to use a very old version of AppDeployToolkit and use the "ServiceUI.exe" workaround.
However, the latest version does not seem to work with Ivanti EndPoint Manager.
The deployment does not seem to be able to start completely, should I use a PowerShell package (with Windows PowerShell or PowerShell Core options) or an executable package using the DeployApplication.exe file.

**Screenshots or additional details:**
Taskbar icon doesn't appear either.

**Comment by That-Annoying-Guy** [comment]
I remember someone posting a link to a ServiceUI clone on GitHub.

I just can't find the post mentioning it. I think it was less than a month ago.

**Comment by DanGough** [comment]
The ‘ServiceUI clone’ you speak of might be this?

https://github.com/PhrozenIO/PowerRunAsSystem

I tried it out and could get it to pop up a powershell prompt from session 0 but not Deploy-Application.exe. Need to play with it some more!

Anyhow, assuming Ivanti works like Intune where stuff is executed as system and not visible, this approach should work:

https://gist.github.com/DanGough/7ad3b9193ae66c0573fa5986c181c491
