### ISSUE TITLE
PSAppDeployToolkit version 3.10.0 Deploy-Application.exe doesn't start when display language is set to Finnish

### ISSUE THREAD

**Issue by maribergstrom** [PSAppDeployToolkit/PSAppDeployToolkit#967]
**Describe the bug**
PSAppDeployToolkit version 3.10.0 Deploy-Application.exe and Deploy-Application.ps1 do not start when display language is set to Finnish. If I change the display language to English, sign out and sign back in to Windows, the toolkit works. When Windows language is set to Finnish, the following error is shown when Deploy-Application.ps1 is run. SID and folder path have been redacted from the error.

```
[04-23-2024 17:35:03.886] [Get-LoggedOnUser] :: Getting session information for all logged on users.
[04-23-2024 17:35:04.131] [Get-RegistryKey] :: Registry key [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\MUI\Settings] does not exist. Return $null.
[04-23-2024 17:35:04.162] [Get-RegistryKey] :: Registry key [Registry::HKEY_USERS\[USERSID]\Software\Policies\Microsoft\Windows\Control Panel\Desktop] does not exist. Return $null.
[04-23-2024 17:35:04.178] [Get-RegistryKey] :: Getting registry key [Registry::HKEY_USERS\[USERSID]\Control Panel\Desktop] value [PreferredUILanguages].
C:\Users\username\Downloads\PSAppDeployToolkit_3.10.0\Deploy-Application.ps1 : Module [C:\Users\username\Download
s\PSAppDeployToolkit_3.10.0\AppDeployToolkit\AppDeployToolkitMain.ps1] failed to load:
You cannot call a method on a null-valued expression.

At C:\Users\username\Downloads\PSAppDeployToolkit_3.10.0\Deploy-Application.ps1:154 char:13
+             . $moduleAppDeployToolkitMain
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ .\Deploy-Application.ps1 -DeploymentType Install -DeployMode Interact ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Deploy-Application.ps1
```

**To Reproduce**
1. Download and extract the newest version of PSAppDeployToolkit from GitHub. No need to make changes to Deploy-Application.ps1.
2. On Windows 10, open Settings --> Time & Language --> Language and change Windows display language to Finnish (Suomi). If it is not installed, add it under Preferred languages --> Add a language. Set it as default language, sign out and sign back in.
3. Try to run Deploy-Application.exe and observe that nothing happens.
4. Open PowerShell and try to run Deploy-Application.ps1 -DeploymentType 'Install' -DeployMode 'Interactive' and the error message shown above should appear.

**Toolkit Version:**
3.10.0

**Powershell Version:**
Tested on both Windows 10 and 11 PowerShell versions 5.1.19041.4291 and 5.1.22621.2506

**Comment by DanGough** [comment]
A fix for this will be merged into the next release which we're looking to release asap.
