### ISSUE TITLE
Show-InstallationWelcome not prompting to close software when pushed as a system account

### ISSUE THREAD

**Issue by hockink** [PSAppDeployToolkit/PSAppDeployToolkit#969]
I just downloaded the latest PSADT.  In one of my test scripts I am using Show-InstallationWelcome to prompt to close software.  If the software is closed already the script goes through fine.  If one of the software's is open then it will hang the install without showing the installation welcome page until the software is closed.

If I elevate privileges (run as administrator) the package runs fine and all prompts show up.  
This code worked on PSADT 3.9.3
I also removed our antivirus to make sure that wasn't blocking anything, but same issue.

**To Reproduce**
Software is pushed through Software Center (SCCM) as system

** Script Code being used **
`Show-InstallationWelcome -CloseApps 'winword=Microsoft Word,saplgpad=SAP GUI,saplogon=SAP Logon,sapgui=SAP GUI,sbus=SAP Secure Login Client' -CheckDiskSpace -PersistPrompt -MinimizeWindows $false`

**Toolkit Version:**
3.10.0

**Powershell Version:**
5.1

**Comment by hockink** [comment]
It seems that the Show-InstallationWelcome works differently in SCCM now.

Normally we turn on the option "installation program visibility" to "Hidden", with past versions of PSADT this worked so clients wouldn't see the script window showing up, but the PSADT windows would show up.

It seems with this latest version if we set the "installation program visibility" to "Normal" I can see the windows, but then clients are also stuck seeing the program code as below.

![Snap4](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/107420442/cd833d6d-585f-4808-98fe-478ce010cdd4)

**Comment by AntoineRv** [comment]
@hockink 

Can you show a print of your log file?

**Comment by hockink** [comment]
I've attached the log file here.  In my research it seems it's broken the same way as Intune.  If I use serviceUI.exe to trigger the Deploy-Application.exe I can see all the PSADT windows and keep the install hidden.  But this wasn't an issue in 3.9.3

[SAP_GUI_770.1.7.8962_x86_ML_1.0_PSAppDeployToolkit_Install.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15094301/SAP_GUI_770.1.7.8962_x86_ML_1.0_PSAppDeployToolkit_Install.log)

**Comment by DanGough** [comment]
Can you confirm you've selected this option in SCCM?
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/21019376/355b1d7c-c7d3-486c-99a6-521c5d3bb3f0)

**Comment by hockink** [comment]
Yes I did make sure the option for "Allow users to view and interact with the program installation" was checkmarked.

**Comment by DanGough** [comment]
I should have realised - this is a duplicate issue and it's been fixed in the Develop branch.

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/941
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/961

You can either grab that code and run with that, or wait until an official release of 3.10.1, which will hopefully happen this week.

**Comment by hockink** [comment]
> I should have realised - this is a duplicate issue and it's been fixed in the Develop branch.
> 
> Issue: #941 Pull Request: #961
> 
> You can either grab that code and run with that, or wait until an official release of 3.10.1, which will hopefully happen this week.

Issue is still present in 3.10.1, when pushing as a system account.  If I tell installation welcome to close word if it's open the dialogue doesn't show up.  I know the script is running because if I close word the install continues through.

**Comment by DanGough** [comment]
Working for me using your exact code:

```ps
Show-InstallationWelcome -CloseApps 'winword=Microsoft Word,saplgpad=SAP GUI,saplogon=SAP Logon,sapgui=SAP GUI,sbus=SAP Secure Login Client' -CheckDiskSpace -PersistPrompt -MinimizeWindows $false
```

![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/21019376/34c831af-7529-493d-bf08-57d4231b7426)

**Comment by hockink** [comment]
The only way for this to work in SCCM for me currently is to either use the same workaround we have to with Intune using the serviceui.exe, or if I change the "installation program visibility" from "hidden" to "normal" with the checkmark "Allow users to view and interact with the program installation" in SCCM (but then this displays all windows PSADT and powershell windows during the install)

We've always been triggering the install in SCCM with the following command with no issues
"powershell.exe -ep bypass -file .\Deploy-Application.ps1"

I did also try installing with this command line with the same results:
"powershell.exe -ep bypass -file .\Deploy-Application.exe"

**Comment by DanGough** [comment]
Please try 3.10.1 with Deploy-Application.exe and let us know if it's still a problem?

**Comment by DanGough** [comment]
You can keep it set to hidden, but you definitely need to check the ‘allow users to view and interact’ checkbox.

Running PowerShell directly like that will cause the console window to be visible; that is primarily why Deploy-Application.exe exists, as a host process to launch PowerShell hidden.

I believe it has always been this way, at least in the several years that I have been using it.

**Comment by hockink** [comment]
It seems using depoloy-application.exe is working properly.  I've only been using PSADT for the last 2 or so years but in that time referencing the PS1 script directly we never had any problems.  But as long as we have a work around I am good with that :)

Thanks so much for helping me troubleshoot this more to figure out what is happening
