### ISSUE TITLE
"QuietUninstallString" and "WindowsInstaller" in Get-InstalledApplication (Follow-up of: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/652)

### ISSUE THREAD

**Issue by ll4mat** [PSAppDeployToolkit/PSAppDeployToolkit#974]
Hi There :-)

Since the original Request is closed i like / dare to rise the question again, if we could add "QuiteUninstallString" and "WindowsInstaller" as additional attributes to the "Get-InstalledApplication" function. The way i see it, it would be an added value to be able to use the quiteuninstallstring. I cannot agree to the statement in the original request that this quiteuninstallstring is incorrect anyway in most cases and thus has no added value when added to PSADT.

I think it would only require the following two lines to be added to the two arrays (line: 3166 and line: 3218) in the AppDeployToolkitMain.ps1:

```
QuietUninstallString = $regKeyApp.QuietUninstallString
WindowsInstaller = $regKeyApp.WindowsInstaller
```

Thank you for checking again.

**Comment by DanGough** [comment]
I agree this would be useful to have, and also have plans to add installation context information for MSIs so that you can determine if an MSI is installed per-system, for the current user, or some other user.

**Comment by DanGough** [comment]
I would also like to make Remove-MSIApplications a more generic function to cover non-MSI applications. It would allow you to override or append to the arguments found in UninstallString / SilentUninstallString and attempt the uninstall for exe based installers as well as MSIs.

This would be very useful when deploying an MSI version of an app that was previously deployed using the EXE variant.

**Comment by mjr4077au** [comment]
@DanGough has added these new values into the function within our new v4 branch, which will be in public preview soon. Thank you for the suggestion!
