### ISSUE TITLE
Request: show-installationPrompt Timeout with default button selection

### ISSUE THREAD

**Issue by MaartenPauchet** [PSAppDeployToolkit/PSAppDeployToolkit#98]
It would be interesting to have the possibility to mark one of the buttons as the default one which will be chosen when the timeout value expires. This way you can present a choice during installation but be sure any of the possible options is selected when the panel expires. 

thanks for considering it.

**Comment by mmashwani** [comment]
If the user selected one of the buttons, then the function returns the text of that button. If the function does not returns the text of one of the buttons, then you know that the function timed out. Therefore, you can choose to do whatever default option you wish at that point.

**Comment by MaartenPauchet** [comment]
True but how does my user know what that default action will be? I'm trying to use the function mid ways a deployment to give a final option to abort or not. but I don't want this popup to be the cause of making the deployment timeout simply because users leave it open without selecting an option. So timeout is a good option here. I still have to try it but I guess I can ask here also : does the timeout option come with a countdown like in the other functions (close programs in x time e.g.)? 

I thought making the default button stand out from the other option(s) would visually be interesting for the end user also. Although alternatively I could also just add it to the text (which they never read :) )

**Comment by mmashwani** [comment]
I guess if the user does not take the time to select an option, are they even going to care what the default button is? or even take the time to notice that a certain button has focus and know that it is the default? It seems to me that if a user doesn't select an option, then the person that set up the package makes the decision on what the default option is, user be damned.

If you want to make a button the default, then you can try the following. If you want to make the middle button the default, then set this in the section where the button is defined:
```
$buttonMiddle.NotifyDefault = $true
```

There is no countdown timer displayed on screen.
