### ISSUE TITLE
ClosePrompt_ButtonClose to small with german text

### ISSUE THREAD

**Issue by Klumpatsch-trex** [PSAppDeployToolkit/PSAppDeployToolkit#980]
**Describe the bug**
If german language is used, "Programme schließen" (close programs) is cut on the "n" within the show-installationwelcome message box

**To Reproduce**
1. Use german language
2. set programms to close on show-installationwelcome
3. startup

**Screenshots**

![Close Programs](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/61126036/90c9efef-f936-4df1-91ee-ea80f96af65c)

**Toolkit Version:**
3.10.0

**Powershell Version:**
PSVersion                      5.1.19041.4291

**Comment by Klumpatsch-trex** [comment]
Hi Dan, to my mind, "Programme schließen" would be perfectly fine translation. I cant come up with an better wording on this at the moment.
I`m clearly far from expert: The diffence -to me- seams to be in switching from "Microsoft Sans Serif" (in Version 3.8.4) to now using
[System.Drawing.Font]$defaultFont = [System.Drawing.SystemFonts]::MessageBoxFont

So in the following image, upper Screenshot is 3.8.4, on the bottom 3.10.0. I think the diffent spacing between the letters is causing the problem

![Unbenannt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/61126036/d19a66e5-04f0-4ccb-bfe3-189687cd2258)

Sorry for my english - not a native speaker and pretty rusty

**Comment by That-Annoying-Guy** [comment]
We could reduce the text padding on the left and right to give the text more room inside the button without changing its size.

**Comment by Klumpatsch-trex** [comment]
As a workaround i changed my main.ps1 to

[16808] `## Get the default font to use in the user interface`
[16809] `#[System.Drawing.Font]$defaultFont = [System.Drawing.SystemFonts]::MessageBoxFont`
[16810] `[System.Drawing.Font]$defaultFont = [System.Drawing.SystemFonts]::DefaultFont`

So Microsoft Sans Serif is used. The spacing is correct now. Maybe there is a better solution? As i said, i`m not an expert
