### ISSUE TITLE
Is this a dead variable?

### ISSUE THREAD

**Issue by Mrman1093** [PSAppDeployToolkit/PSAppDeployToolkit#982]
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/dc3c003bbb0e78f025e98b96c3fc9c6e672e9c3e/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L961
Forgive me if I'm wrong but, looking at the use of this variable throughout the main script, it appears that this variable is only actually used in Get-MsiTableProperty. My assumption from looking at older releases of the toolkit is that when Execute-MSP was originally written, the author copied this section from Get-MsiTableProperty and included the variable even though it isn't being used.
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/dc3c003bbb0e78f025e98b96c3fc9c6e672e9c3e/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L12793-L12795

**Comment by Mrman1093** [comment]
While we're at it, there appears to be another variable in Execute-MSP that is redundant/unused.
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/dc3c003bbb0e78f025e98b96c3fc9c6e672e9c3e/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L955-L956
$msiOpenDatabaseModePatchFile is only used to create $msiOpenDatabaseMode which is in turn only used once in the following line.
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/dc3c003bbb0e78f025e98b96c3fc9c6e672e9c3e/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L958
Both of these variables can be removed or for the sake of keeping with the documented comments, can be reduced to only one variable.

**Comment by mjr4077au** [comment]
It's probably been done like that to try and give some better detail around what `32` means, rather than just a literal constant. Ideally there should be an enum for these types.

I wouldn't get too caught up on stack variables in functions though, they're all purged when the function returns. Further to this, there's big refactoring going on for v4.0 where a lot of older code will be revisited.

**Comment by DanGough** [comment]
If we adopt the WiX DTF libraries (which I’ve briefly mentioned but not yet fully discussed with the team) then we get all these enums for free.

@Mrman1093 as @mjr4077au said there are some major changes going on for 4.0 right now, your efforts would be best placed, and much appreciated, by going through that once it’s in public preview!

**Comment by mjr4077au** [comment]
All of the mentioned code areas have been refactored for our upcoming v4 public preview.
