### ISSUE TITLE
AppDeployToolkitConfig.xml have "wrong" version number.

### ISSUE THREAD

**Issue by Latupho** [PSAppDeployToolkit/PSAppDeployToolkit#99]
In this .XML file it say it's version 3.6.6, but the latest version is 3.6.7. Will comment at the code, at the line in a moment.

**Comment by mmashwani** [comment]
The last time the XML file was modified was in the 3.6.6 release. The version number always reflects the last toolkit version that included a change to the XML file. It helps keeps users upgrading their scripts to know if they need to migrate their XML to a newer version of the toolkit or not.

**Comment by mmashwani** [comment]
Also, I think you're looking at an old commit with a changelog file that references the wrong version number. The latest changelog has the correct version numbers listed: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/CHANGELOG.txt

**Comment by Latupho** [comment]
Was looking at https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml

But I see your point, and agree. Just ignore this issue :+1:
