### ISSUE TITLE
[tanslation] <BalloonText_FastRetry> German Translastion

### ISSUE THREAD

**Issue by Klumpatsch-trex** [PSAppDeployToolkit/PSAppDeployToolkit#990]
### Summary of the new feature / enhancement

<BalloonText_FastRetry>nicht abgeschlossen werden.</BalloonText_FastRetry>
should be <BalloonText_FastRetry>konnte nicht abgeschlossen werden.</BalloonText_FastRetry> #translates to "Installation *could not be completed"
or <BalloonText_FastRetry>nicht abgeschlossen.</BalloonText_FastRetry> #translates more to the original "Installation not complete"

**Comment by kaempfde** [comment]
Hi there,

we found the same issue / translation problem.. In the AppDeployToolkitConfig.xml we changed the code in line 375 like above.

We would love if u can implement this in future releases of PSADT so we dont need to change it manually for every new version.

The correct translation would be:
<BalloonText_FastRetry>**konnte** nicht abgeschlossen werden.</BalloonText_FastRetry>

Thanks!

**Comment by mjr4077au** [comment]
This issue should be resolved by https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/b4778e8e02206b040e0b06d5cefd03802f7eae7f, where the strings.psd1 file in v4 for each language has been revised to properly handle install/uninstall/remove operations. If any of the translations are bad or wrong, submissions are most welcome.
