### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Fietspad21** [PSAppDeployToolkit/PSAppDeployToolkit#991]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

Running Deploy-Application.ps1 from a PowerShell Core fails with error You cannot call a method on a null-valued expression.

### Steps to reproduce

1. Launch PowerShell 
2. Call Deploy-Application.ps1 -DeploymentType Install
3. Call Deploy-Application.ps1 -DeploymentType Uninstall

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OSDisplayVersion     : 22H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64 bits
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
```

**Comment by DanGough** [comment]
PowerShell Core is not supported in 3.x, but may be supported in 4.0.
