### ISSUE TITLE
Incorrect information with 'Set-ItemPermission' reference in docs - 'https://psappdeploytoolkit.com/docs/reference/functions/Set-ItemPermission/'

### ISSUE THREAD

**Issue by Lewis-Brown-NHS** [PSAppDeployToolkit/PSAppDeployToolkit#992]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.0

### Describe the bug

Documentation and examples are unclear and imo incorrect. 

1. "Set-ItemPermission -Path 'C:\Temp' -User 'DOMAIN\John', 'BUILTIN\Utilisateurs' -Permission FullControl -Inheritance ObjectInherit,ContainerInherit" should be changed to > "Set-ItemPermission -Path 'C:\Temp' -User ('DOMAIN\John' , 'BUILTIN\Users') -Permission 'FullControl' -Inheritance ('ObjectInherit' , 'ContainerInherit')"
2. If you need to add multiple permission otpions on a directory i.e. CreateFiles and Appenddata then the parameter should be > "-Permission ('CreateFiles' , 'AppendData')"
3. The Examples section is formatted incorrectly - The description is placed in the codebBlockContainer. The example code is placed inside the "< p > < /p >" (These should be swapped around)

### Steps to reproduce

1.When attempting to use the code provided in the examples but trying to add multiple permission options, I receive an error when executing my install stating the arguments do not exist.

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}
KeyboardLayout       : en-GB
TimeZone             : (UTC+00:00) Dublin, Edinburgh, Lisbon, London
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile


Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by DanGough** [comment]
It would be better to use either of these for the users group as they will work no matter which language the system is set to:

`-User $LocalUsersGroup` 

`-User '*S-1-5-32-545'`

**Comment by mjr4077au** [comment]
> "Set-ItemPermission -Path 'C:\Temp' -User 'DOMAIN\John', 'BUILTIN\Utilisateurs' -Permission FullControl -Inheritance ObjectInherit,ContainerInherit" should be changed to > "Set-ItemPermission -Path 'C:\Temp' -User ('DOMAIN\John' , 'BUILTIN\Users') -Permission 'FullControl' -Inheritance ('ObjectInherit' , 'ContainerInherit')"

There's no need to put array items in parentheses like this; there's no difference between `-User 'DOMAIN\John' , 'BUILTIN\Users'` and `-User ('DOMAIN\John' , 'BUILTIN\Users')`. Furthermore, it could be simplified to `-User DOMAIN\John, BUILTIN\Users` since there's no spaces necessitating the quotes.

> If you need to add multiple permission otpions on a directory i.e. CreateFiles and Appenddata then the parameter should be > "-Permission ('CreateFiles' , 'AppendData')"

Again, not necessary.

> The Examples section is formatted incorrectly - The description is placed in the codebBlockContainer. The example code is placed inside the "< p > < /p >" (These should be swapped around)

The documentation for v4 has this resolved: https://psappdeploytoolkit.com/docs/reference/functions/Set-ADTItemPermission#examples
