### ISSUE TITLE
[Documentation] Copy-File documentation needs more info

### ISSUE THREAD

**Issue by ajscott** [PSAppDeployToolkit/PSAppDeployToolkit#995]
The Copy-File command does not create a destination folder if you specify a destination filename. This appears to be by design so the site documentation should be updated to reflect this behavior.

Add a note to [Example1](https://psappdeploytoolkit.com/docs/reference/functions/Copy-File/#notes) that states copy-file will not create the destination folder if a destination filename is specified.

Create Example3 showing a command that will copy a single file and create the destination folder.

`Copy-File -Path "$dirSupportFiles\MyApp.ini" -Destination "$envProgramFiles\NewFolder"`

This is the relevant code from the copy-file function that prevents it from creating a folder if a filename is specified

`
If ((-not ([IO.Path]::HasExtension($Destination))) 
`

**Comment by DanGough** [comment]
I'm not sure which version you tested this against, but 3.10.1 does indeed auto-create the destination folder if it does not exist.

```
[Copy-File] :: Destination path appears to be a file. Falling back to native PowerShell method.
[Copy-File] :: Destination assumed to be a file whose parent folder does not exist, creating destination folder [C:\Temp\NEW FOLDER].
[Copy-File] :: Copying file in path [C:\Temp\Test.txt] to destination [C:\Temp\NEW FOLDER\Test2.txt].
[Copy-File] :: File copy completed successfully.
```
